ORNL-AMO/AMO-Tools-Desktop

- src/app/app.component.html
- src/app/app.component.ts
- src/app/app.module.ts
- src/app/electron.service.spec.ts
- src/app/electron.service.ts
- src/index.html
electron.service utilizes the electron API
app.component makes a call to the electron.service
> example using electron API

- package.json
- src/app/app.component.html
- src/app/app.component.ts
- src/app/app.module.ts
- src/app/demo/demo.component.html
- src/app/demo/demo.component.spec.ts
- src/app/demo/demo.component.ts
- src/app/electron.service.ts
- src/assets/styles/application.scss
app/demo has examples of bootstrap buttons calling electron functions in electron.service
> bootstrap, font-awesome and glyphicons added to application styles

- .env
- README.md
- main.js
- package.json
- src/index.html
.env folder is used to set environment. the PACKAGE flag is checked in main.js by electron
> updated build process and corresponding README

- src/app/app.component.html
- src/app/app.module.ts
- src/app/app.routing.ts
- src/app/contact-form/contact-form.component.html
- src/app/contact-form/contact-form.component.spec.ts
- src/app/contact-form/contact-form.component.ts
- src/app/core/core.component.html
- src/app/core/core.component.spec.ts
- src/app/core/core.component.ts
- src/app/demo/demo.component.html
- src/app/demo/demo.component.ts
routing examples in demo and contact-form components
examples in html files using `routerLink`
> basic application routing

- package.json
- src/app/phast/sankey/sankey.component.ts
> Adds D3 v4 to Sankey instead of D3 v3

- src/app/phast/sankey/sankey.component.html
- src/app/phast/sankey/sankey.component.ts
modified:   src/app/phast/sankey/sankey.component.html
-Values read in will reshape the steam of the Sankey Diagram.
-Sankey has been resized and recolored.
> Makes the Sankey more dynamic based on values

- README.md
- package.json
Added dependencies and updated package.json to build an installer for Windows and a .tar.gz for Linux. Also updated the Readme file for directions on how to build. Did not test this with Mac yet.
> Packaging update

- main.js
Updated main.js to allow installer to run correctly.
> Updated main.js to allow installer to work correctly.

- src/app/app.component.css
- src/app/phast/phast-banner/phast-banner.component.css
- src/app/phast/phast-banner/phast-banner.component.html
- src/app/phast/phast-tabs/phast-tabs.component.css
- src/app/phast/phast.component.css
- src/app/phast/phast.component.html
- src/app/phast/phast.component.ts
- src/app/phast/system-basics/system-basics.component.css
- src/app/phast/system-basics/system-basics.component.html
- src/app/phast/system-basics/system-basics.component.ts
- src/app/psat/psat-banner/psat-banner.component.css
- src/app/psat/psat-banner/psat-banner.component.html
- src/app/psat/psat-tabs/psat-tabs.component.css
- src/app/psat/psat.component.css
- src/app/psat/psat.component.html
- src/app/psat/psat.component.ts
- src/app/psat/system-basics/system-basics.component.css
- src/app/psat/system-basics/system-basics.component.html
- src/app/psat/system-basics/system-basics.component.ts
Still styling work to be done.
PSAT **and** PHAST basics views were done here.
> system basics content with initial styling for psat and phast

- src/app/psat/motor/motor.component.css
- src/app/psat/motor/motor.component.html
- src/app/psat/motor/motor.component.ts
- src/app/psat/pump-fluid/pump-fluid.component.html
View for step 3 (motor details) of PSAT
> psat motor step view

- src/app/assessment/assessment-create/assessment-create.component.html
- src/app/assessment/assessment-create/assessment-create.component.ts
- src/app/assessment/assessment-dashboard/assessment-dashboard.component.ts
- src/app/assessment/assessment.component.ts
- src/app/assessment/assessment.service.spec.ts
- src/app/assessment/assessment.service.ts
- src/app/core/core.module.ts
- src/app/dashboard/dashboard.component.ts
- src/app/phast/operating-hours/operating-hours.component.css
- src/app/phast/operating-hours/operating-hours.component.html
- src/app/phast/operating-hours/operating-hours.component.ts
- src/app/phast/phast-banner/phast-banner.component.html
- src/app/phast/phast-banner/phast-banner.component.ts
- src/app/phast/phast.component.html
- src/app/phast/phast.component.ts
- src/app/psat/psat-banner/psat-banner.component.html
- src/app/psat/psat-banner/psat-banner.component.ts
- src/app/psat/psat.component.html
- src/app/psat/psat.component.ts
- src/app/psat/psat.module.ts
- src/app/shared/mocks/mock-directory.ts
- src/app/shared/model.service.ts
- src/app/shared/models/assessment.ts
- src/app/shared/models/phast.ts
Can create a new assessment of type psat or phast from the main assessment dashboard and be taken to the corresponding assessment screen via the create assessment modal.
> Phast views

- src/app/phast/sankey/sankey.component.ts
> Adds an updated Sankey Diagram inside of PHAST

- src/app/phast/phast.module.ts
- src/app/phast/sankey/sankey-diagram/sankey-diagram.component.spec.ts
- src/app/phast/sankey/sankey-diagram/sankey-diagram.component.ts
- src/app/phast/sankey/sankey.component.html
- src/app/phast/sankey/sankey.component.ts
new file:   src/app/phast/sankey/sankey-diagram/sankey-diagram.component.css
new file:   src/app/phast/sankey/sankey-diagram/sankey-diagram.component.html
new file:   src/app/phast/sankey/sankey-diagram/sankey-diagram.component.spec.ts
new file:   src/app/phast/sankey/sankey-diagram/sankey-diagram.component.ts
modified:   src/app/phast/sankey/sankey.component.html
*Responds to inputs, however changing the useful output will do nothing. 
*The Sankey will also break if values do not match up or are too large. 
*Will fix soon.
> 	modified:   src/app/phast/phast.module.ts

- package.json
- src/app/psat/modify-conditions/adjustment/adjustment.component.html
- src/app/psat/modify-conditions/adjustment/adjustment.component.ts
- src/app/psat/modify-conditions/modify-conditions.component.html
- src/app/psat/modify-conditions/modify-conditions.component.ts
postinstall script for electron-rebuild
delete adjustments for psat working
> Psat data binding

- package.json
- src/app/assessment/assessment-banner/assessment-banner.component.css
- src/app/assessment/assessment-banner/assessment-banner.component.html
- src/app/assessment/assessment-create/assessment-create.component.html
- src/app/assessment/assessment-dashboard/assessment-dashboard.component.html
- src/app/assessment/assessment-grid-view/assessment-card/assessment-card.component.html
- src/app/assessment/assessment-grid-view/assessment-grid-view.component.html
- src/app/assessment/assessment-grid-view/directory-card/directory-card.component.html
- src/app/assessment/assessment-menu/assessment-menu.component.html
- src/app/assessment/assessment-menu/create-folder/create-folder.component.html
- src/app/core/core.component.html
- src/app/dashboard/dashboard.component.css
- src/app/dashboard/dashboard.component.html
- src/app/psat/field-data/field-data.component.html
- src/app/psat/modify-conditions/modify-conditions.component.css
- src/app/psat/modify-conditions/modify-conditions.component.html
- src/app/psat/motor/motor.component.html
- src/app/psat/psat-banner/psat-banner.component.css
- src/app/psat/psat-banner/psat-banner.component.html
- src/app/psat/psat-tabs/psat-tabs.component.css
- src/app/psat/psat-tabs/psat-tabs.component.html
- src/app/psat/psat.component.css
- src/app/psat/psat.component.html
- src/app/psat/pump-fluid/pump-fluid.component.html
- src/app/psat/system-basics/system-basics.component.html
- src/app/sidebar/sidebar.component.css
- src/assets/styles/application.scss
- src/index.html
> Psat modify conditions

- package.json
- src/app/phast/phast.module.ts
- src/app/phast/sankey/sankey.component.html
- src/app/phast/sankey/sankey.component.ts
modified:   src/app/phast/phast.module.ts
modified:   src/app/phast/sankey/sankey.component.html
> 	Adds zoom+pan feature to Sankey, plus the foundation of a color button

- src/app/phast/sankey/sankey.component.html
- src/app/phast/sankey/sankey.component.ts
- src/app/psat/field-data/field-data.component.css
- src/app/psat/field-data/field-data.component.html
modified:   src/app/psat/field-data/field-data.component.css
modified:   src/app/psat/field-data/field-data.component.html
> Complete Dynamic Sankey Gradient, as well as Field-Data help

- main.js
- package.json
Implement autoUpdater code to main.js. Testing was successful.
> Auto updater

- README.md
- main.js
Removed a line of code that forced devtools to open when the application starts. Also added more details to the building section of the README and added an Auto Update section to the README.
> Removed devTools from main.js. Also added to README

- package.json
Customized the installer to give user options while installing.
> Installer Update

- src/app/phast/losses/charge-material/charge-material.component.html
- src/app/phast/losses/charge-material/charge-material.component.ts
- src/app/phast/losses/charge-material/charge-material.service.spec.ts
- src/app/phast/losses/charge-material/charge-material.service.ts
- src/app/phast/losses/losses.component.html
- src/app/phast/losses/losses.component.ts
- src/app/phast/phast.component.html
- src/app/phast/phast.module.ts
- src/app/phast/phast.service.ts
- src/app/shared/mocks/mock-directory.ts
- src/app/shared/models/losses/chargeMaterial.ts
- src/app/shared/models/phast.ts
Mock PHAST 1 has Gas, Solid, and Liquid charge material's with values from cpp unit tests
> added charge-material.service with tests to mocks

- src/app/psat/psat-tabs/psat-tabs.component.html
- src/app/psat/psat.component.html
- src/app/psat/psat.component.ts
- src/app/psat/psat.module.ts
- src/app/psat/system-curve/system-curve-form/system-curve-form.component.html
- src/app/psat/system-curve/system-curve-form/system-curve-form.component.spec.ts
- src/app/psat/system-curve/system-curve-form/system-curve-form.component.ts
- src/app/psat/system-curve/system-curve-graph/system-curve-graph.component.html
- src/app/psat/system-curve/system-curve-graph/system-curve-graph.component.spec.ts
- src/app/psat/system-curve/system-curve-graph/system-curve-graph.component.ts
- src/app/psat/system-curve/system-curve.component.html
- src/app/psat/system-curve/system-curve.component.spec.ts
- src/app/psat/system-curve/system-curve.component.ts
Use input values on system-curve-graph to draw graph
> system curve calculations for static head and loss coefficient

- main.js
- src/app/app.module.ts
- src/app/assessment/assessment.module.ts
- src/app/core/core.module.ts
- src/app/dashboard/dashboard.component.html
- src/app/dashboard/dashboard.component.ts
- src/app/shared/electron.service.ts
- src/app/update-modal/update-modal.component.html
- src/app/update-modal/update-modal.component.spec.ts
- src/app/update-modal/update-modal.component.ts
modified:   src/app/app.module.ts
modified:   src/app/core/core.module.ts
modified:   src/app/dashboard/dashboard.component.html
modified:   src/app/dashboard/dashboard.component.ts
modified:   src/app/shared/electron.service.ts
new file:   src/app/update-modal/update-modal.component.css
new file:   src/app/update-modal/update-modal.component.html
new file:   src/app/update-modal/update-modal.component.spec.ts
new file:   src/app/update-modal/update-modal.component.ts
> Adds a update-modal that doesn't work

- src/app/app.module.ts
- src/app/core/core.component.html
- src/app/core/core.component.ts
- src/app/dashboard/dashboard.component.html
- src/app/dashboard/dashboard.component.ts
- src/app/phast/data-panel/data-panel.component.ts
- src/app/phast/losses/heat-storage/heat-storage-form/heat-storage-form.component.html
- src/app/phast/losses/heat-storage/heat-storage.component.ts
- src/app/psat/psat.component.html
- src/app/psat/system-curve/system-curve-graph/system-curve-graph.component.ts
- src/app/update-modal/update-modal.component.html
- src/app/update-modal/update-modal.component.ts
1)Fixes the update modal so it does not pop up every time the user returns to the home screen. 
2)Adds in the input information for the heat storage in the losses section.
3)Places the SVG for the curve graph in the appropriate section.
> Adds a small update to several different aspects of AMO-Tools-Desktop

- src/app/psat/system-curve/system-curve-form/system-curve-form.component.html
- src/app/psat/system-curve/system-curve-form/system-curve-form.component.ts
- src/app/psat/system-curve/system-curve.component.html
- src/app/psat/system-curve/system-curve.component.ts
Fluid power calculations added for points on system curve per Daryl Cox's equation
fluidPower = (head * flow * specificGravity) / 3960
> fluid power calculations added to system-curve

- src/app/phast/losses/cooling-losses/cooling-losses.service.ts
- src/app/phast/losses/cooling-losses/gas-cooling-losses-form/gas-cooling-losses-form.component.html
- src/app/phast/losses/cooling-losses/liquid-cooling-losses-form/liquid-cooling-losses-form.component.html
- src/app/phast/losses/cooling-losses/water-cooling-losses-form/water-cooling-losses-form.component.html
- src/app/phast/losses/gas-leakage-losses/gas-leakage-losses-form/gas-leakage-losses-form.component.html
- src/app/phast/losses/gas-leakage-losses/gas-leakage-losses-form/gas-leakage-losses-form.component.spec.ts
- src/app/phast/losses/gas-leakage-losses/gas-leakage-losses-form/gas-leakage-losses-form.component.ts
- src/app/phast/losses/gas-leakage-losses/gas-leakage-losses.component.html
- src/app/phast/losses/gas-leakage-losses/gas-leakage-losses.component.spec.ts
- src/app/phast/losses/gas-leakage-losses/gas-leakage-losses.component.ts
- src/app/phast/losses/gas-leakage-losses/gas-leakage-losses.service.spec.ts
- src/app/phast/losses/gas-leakage-losses/gas-leakage-losses.service.ts
- src/app/phast/losses/losses-sidebar/losses-sidebar.component.html
- src/app/phast/losses/losses.component.html
- src/app/phast/losses/losses.component.ts
- src/app/phast/losses/losses.module.ts
- src/app/phast/losses/wall-losses/wall-losses.component.ts
- src/app/phast/phast.service.ts
- src/app/shared/mocks/mock-directory.ts
- src/app/shared/models/losses/leakageLoss.ts
- src/app/shared/models/phast.ts
Leakage losses added and working under assumption of:
coefficient: .8052,
correctionFactor: 1.0
(values taken from cpp unit tests)
> Phast design refactor

- main.js
- package.json
Removed DevTools toggle, updated version of amo-tools-suite in dependencies to 0.1.18, and updated version of Desktop to 0.1.18 as well.
> Ready for Release

- src/app/app.component.css
- src/app/phast/losses/atmosphere-losses/atmosphere-losses.component.html
- src/app/phast/losses/charge-material/charge-material.component.html
- src/app/phast/losses/charge-material/gas-charge-material-form/gas-charge-material-form.component.html
- src/app/phast/losses/charge-material/liquid-charge-material-form/liquid-charge-material-form.component.html
- src/app/phast/losses/charge-material/solid-charge-material-form/solid-charge-material-form.component.html
- src/app/phast/losses/cooling-losses/cooling-losses.component.html
- src/app/phast/losses/extended-surface-losses/extended-surface-losses-form/extended-surface-losses-form.component.css
- src/app/phast/losses/extended-surface-losses/extended-surface-losses.component.html
- src/app/phast/losses/fixture-losses/fixture-losses.component.html
- src/app/phast/losses/flue-gas-losses/flue-gas-losses.component.html
- src/app/phast/losses/gas-leakage-losses/gas-leakage-losses.component.html
- src/app/phast/losses/losses-tabs/losses-tabs.component.html
- src/app/phast/losses/losses.component.css
- src/app/phast/losses/losses.component.html
- src/app/phast/losses/losses.component.ts
- src/app/phast/losses/opening-losses/opening-losses.component.html
- src/app/phast/losses/other-losses/other-losses.component.html
- src/app/phast/losses/wall-losses/wall-losses-form/wall-losses-form.component.html
- src/app/phast/losses/wall-losses/wall-losses.component.html
Initial work on PHAST losses view after design change.
> phast losses modifications updates

- src/app/psat/system-curve/system-curve-graph/system-curve-graph.component.ts
…e-graph.component.ts
Notes:
-Area under curve has been commented out until either Jon or I can find a way to change the print style sheet in a way that excludes svg objects.
> Fixes the System curve as well as adds a style update

- src/app/phast/sankey/sankey.component.ts
Notes) Directly inputting values into the Sankey Diagram is no longer an option and must instead be done through the heat balance forms.
> Links the values from the Heat Balance forms to the Sankey Diagram.

- src/app/phast/sankey/sankey.component.ts
Increases font size and shifts arrows to accommodate that new size size.
> Increases font size of Sankey Losses

- src/app/calculator/utilities/unit-converter/unit-converter.component.html
- src/app/shared/convert-units/convert-units.service.ts
- src/app/shared/convert-units/definitions/apparentPower.ts
- src/app/shared/convert-units/definitions/current.ts
- src/app/shared/convert-units/definitions/energy.ts
- src/app/shared/convert-units/definitions/power.ts
- src/app/shared/convert-units/definitions/reactiveEnergy.ts
- src/app/shared/convert-units/definitions/reactivePower.ts
- src/app/shared/convert-units/definitions/voltage.ts
- src/app/shared/convert-units/definitions/volumeFlowRate.ts
Added definitions for:
apparentPower
current
energy
power
reactiveEnergy
reactivePower
voltage
volumeFlowRate
definitions for from npm package `convert-units`
> added definitions

- src/app/psat/modify-conditions/modify-conditions-tabs/modify-conditions-tabs.component.html
- src/app/psat/modify-conditions/modify-conditions.component.html
- src/app/psat/psat-report/psat-report.component.html
- src/app/psat/psat-tabs/psat-tabs.component.html
- src/app/psat/psat.component.html
- src/app/psat/psat.component.ts
Styling updates needed for psat report but content is in proper place
> moved psat report to modify conditions tab

- src/app/calculator/pumps/achievable-efficiency/achievable-efficiency-graph/achievable-efficiency-graph.component.ts
- src/app/calculator/pumps/motor-performance/motor-performance-graph/motor-performance-graph.component.ts
- src/app/calculator/pumps/specific-speed/specific-speed-graph/specific-speed-graph.component.ts
…e-efficiency-graph/achievable-efficiency-graph.component.ts
modified:   src/app/calculator/pumps/motor-performance/motor-performance-graph/motor-performance-graph.component.ts
modified:   src/app/calculator/pumps/specific-speed/specific-speed-graph/specific-speed-graph.component.ts
> Greatly improves the Specific Speed Graph as well as hides graphs until input has been entered

- src/app/assessment/assessment-create/assessment-create.component.ts
- src/app/calculator/pumps/head-tool/head-tool-form/head-tool-form.component.html
- src/app/calculator/pumps/head-tool/head-tool-form/head-tool-form.component.ts
- src/app/calculator/pumps/head-tool/head-tool.component.html
- src/app/dashboard/dashboard.component.ts
- src/app/phast/phast-tabs/phast-tabs.component.html
- src/app/psat/system-basics/system-basics.component.ts
Updates from meetings feedback
> Psat cleanup

- src/app/assessment/assessment-create/assessment-create.component.html
- src/app/assessment/assessment-menu/assessment-menu.component.html
- src/app/phast/phast-tabs/phast-tabs.component.html
- src/app/phast/phast.component.html
- src/app/phast/phast.component.ts
- src/app/psat/pump-fluid/pump-fluid.component.html
- src/app/sidebar/sidebar.component.html
Quick updates to labels from meeting 5/11
> Meeting updates

- src/app/calculator/pumps/achievable-efficiency/achievable-efficiency-form/achievable-efficiency-form.component.html
- src/app/calculator/pumps/head-tool/head-tool-form/head-tool-form.component.html
- src/app/calculator/pumps/head-tool/head-tool-suction-form/head-tool-suction-form.component.html
- src/app/calculator/pumps/motor-performance/motor-performance-form/motor-performance-form.component.html
- src/app/calculator/pumps/nema-energy-efficiency/nema-energy-efficiency-form/nema-energy-efficiency-form.component.html
- src/app/calculator/pumps/specific-speed/specific-speed-form/specific-speed-form.component.html
- src/app/calculator/pumps/system-curve/system-curve-form/system-curve-form.component.html
- src/app/psat/field-data/field-data.component.html
- src/app/psat/field-data/field-data.component.ts
- src/app/psat/modify-conditions/modify-conditions.component.html
- src/app/psat/modify-conditions/modify-conditions.component.ts
- src/app/psat/motor/motor.component.html
- src/app/psat/motor/motor.component.ts
- src/app/psat/psat.component.ts
- src/app/psat/pump-fluid/pump-fluid.component.html
- src/app/psat/pump-fluid/pump-fluid.component.ts
- src/app/settings/application-settings/application-settings.component.html
working solution for autofocus and selecting text on focus for input fields
> Autofocus fields

- src/app/calculator/pumps/achievable-efficiency/achievable-efficiency-graph/achievable-efficiency-graph.component.ts
- src/app/calculator/pumps/motor-performance/motor-performance-graph/motor-performance-graph.component.ts
- src/app/calculator/pumps/specific-speed/specific-speed-graph/specific-speed-graph.component.ts
- src/app/calculator/pumps/system-curve/system-curve-graph/system-curve-graph.component.ts
Graph updates:
Colors
Detail Boxes for all graphs
Zoom where applicable
Range changes to get rid of unwanted asymptotic lines
> Graph detail boxes

- src/app/calculator/utilities/unit-converter/unit-converter.component.css
- src/app/calculator/utilities/unit-converter/unit-converter.component.html
- src/app/calculator/utilities/unit-converter/unit-converter.component.ts
- src/app/calculator/utilities/utilities.component.html
enhanced layout/functionality for unit converter
> Unit converter design

- src/app/calculator/calculator.module.ts
- src/app/core/core.module.ts
- src/app/psat/field-data/field-data.component.html
- src/app/psat/field-data/field-data.component.ts
- src/app/psat/modify-conditions/modify-conditions.component.css
- src/app/psat/modify-conditions/modify-conditions.component.html
- src/app/psat/modify-conditions/modify-conditions.component.ts
- src/app/psat/psat.module.ts
Overriding z-index on "modification" class when head tool modal opens inside modification context
> Head tool fix

- src/app/psat/field-data/field-data.component.html
- src/app/psat/motor/motor.component.html
- src/app/psat/pump-fluid/pump-fluid.component.html
@rmroot  I fixed decimal user input for PSAT.
> Issue #344 Fixed user input for PSAT. All input="number" accept decimal format.

- package.json
- src/app/calculator/pumps/system-curve/system-curve-form/system-curve-form.component.ts
- src/app/phast/losses/losses.component.html
modified:   package.json
modified:   src/app/calculator/pumps/system-curve/system-curve-form/system-curve-form.component.ts
modified:   src/app/phast/losses/losses.component.html
> updates version to 0.1.27

- src/app/app.component.css
- src/app/calculator/pumps/achievable-efficiency/achievable-efficiency-form/achievable-efficiency-form.component.ts
- src/app/calculator/pumps/achievable-efficiency/achievable-efficiency-graph/achievable-efficiency-graph.component.ts
- src/app/calculator/pumps/achievable-efficiency/achievable-efficiency.component.ts
- src/app/calculator/pumps/motor-performance/motor-performance-graph/motor-performance-graph.component.ts
- src/app/calculator/pumps/specific-speed/specific-speed-form/specific-speed-form.component.html
- src/app/calculator/pumps/specific-speed/specific-speed-graph/specific-speed-graph.component.ts
- src/app/calculator/pumps/system-curve/system-curve-form/system-curve-form.component.html
- src/app/phast/phast.component.html
- src/app/psat/psat.component.html
modified:   src/app/calculator/pumps/achievable-efficiency/achievable-efficiency-form/achievable-efficiency-form.component.ts
modified:   src/app/calculator/pumps/achievable-efficiency/achievable-efficiency-graph/achievable-efficiency-graph.component.ts
modified:   src/app/calculator/pumps/achievable-efficiency/achievable-efficiency.component.ts
modified:   src/app/calculator/pumps/motor-performance/motor-performance-graph/motor-performance-graph.component.ts
modified:   src/app/calculator/pumps/specific-speed/specific-speed-form/specific-speed-form.component.html
modified:   src/app/calculator/pumps/specific-speed/specific-speed-graph/specific-speed-graph.component.ts
modified:   src/app/calculator/pumps/system-curve/system-curve-form/system-curve-form.component.html
modified: …
> Fixes Several Bugs in the PSAT Graphs

- src/app/app.component.css
- src/app/calculator/pumps/achievable-efficiency/achievable-efficiency-form/achievable-efficiency-form.component.ts
- src/app/calculator/pumps/achievable-efficiency/achievable-efficiency-graph/achievable-efficiency-graph.component.ts
- src/app/calculator/pumps/achievable-efficiency/achievable-efficiency.component.ts
- src/app/calculator/pumps/motor-performance/motor-performance-graph/motor-performance-graph.component.ts
- src/app/calculator/pumps/specific-speed/specific-speed-form/specific-speed-form.component.html
- src/app/calculator/pumps/specific-speed/specific-speed-graph/specific-speed-graph.component.ts
- src/app/calculator/pumps/system-curve/system-curve-form/system-curve-form.component.html
- src/app/phast/phast.component.html
- src/app/psat/psat.component.html
Reverts ORNL-AMO/AMO-Tools-Desktop#382
app.component.css changes removed jons latest updates
> Revert "Fixes Several Bugs in the PSAT Graphs"

- src/app/calculator/pumps/achievable-efficiency/achievable-efficiency-graph/achievable-efficiency-graph.component.ts
- src/app/calculator/pumps/motor-performance/motor-performance-graph/motor-performance-graph.component.ts
- src/app/calculator/pumps/specific-speed/specific-speed-graph/specific-speed-graph.component.ts
- src/app/psat/psat-report/input-summary/input-summary.component.html
- src/app/psat/psat.component.html
…e-efficiency-graph/achievable-efficiency-graph.component.ts
modified:   src/app/calculator/pumps/motor-performance/motor-performance-graph/motor-performance-graph.component.ts
modified:   src/app/calculator/pumps/specific-speed/specific-speed-graph/specific-speed-graph.component.ts
modified:   src/app/psat/psat-report/input-summary/input-summary.component.html
modified:   src/app/psat/psat.component.html
> Fixes PSAT Issues

- src/app/phast/phast-tabs/phast-tabs.component.html
- src/app/psat/psat-tabs/psat-tabs.component.html
modified:   src/app/psat/psat-tabs/psat-tabs.component.html
> Fixes PSAT and PHAST Tabs

- src/app/psat/psat-tabs/psat-tabs.component.html
- src/app/psat/psat.component.ts
comment out explore opportunities
> removes explore opportunites

- src/app/calculator/pumps/achievable-efficiency/achievable-efficiency-form/achievable-efficiency-form.component.css
- src/app/calculator/pumps/achievable-efficiency/achievable-efficiency-form/achievable-efficiency-form.component.html
- src/app/calculator/pumps/achievable-efficiency/achievable-efficiency.component.html
- src/app/calculator/pumps/system-curve/system-curve.component.html
- src/app/psat/psat-tabs/psat-tabs.component.html
Fixed  formatting PSAT
- System curve Bootstrap format changes.
- Achievable Pump Efficiency drop down and Flow Rate changed; adjusted gpm. Bootstrap format has changed.
- Extra ">" removed from PSAT menu tab
> Pump Head tool units fix.

- src/app/assessment/assessment.service.ts
- src/app/psat/explore-opportunities/explore-opportunities.component.css
- src/app/psat/explore-opportunities/explore-opportunities.component.html
- src/app/psat/explore-opportunities/explore-opportunities.component.ts
- src/app/psat/psat.component.ts
- src/app/psat/pump-fluid/pump-fluid.component.ts
This branch has the updates for toggle opportunities as well as changing the default pump type. PR is open for toggle opportunities changes and should be merged first.
> Default pump type

- src/app/about-page/about-page.component.html
- src/app/about-page/about-page.component.ts
New content for about page. 
New card and content for FAST.
> New about page.

- src/app/about-page/about-page.component.html
- src/app/about-page/about-page.component.ts
- src/app/calculator/utilities/unit-converter/sort-by.pipe.spec.ts
- src/app/calculator/utilities/unit-converter/sort-by.pipe.ts
- src/app/calculator/utilities/unit-converter/sort-pipe.ts
- src/app/calculator/utilities/unit-converter/unit-converter.component.html
- src/app/calculator/utilities/unit-converter/unit-converter.component.ts
- src/app/calculator/utilities/utilities.module.ts
Unites are sorted in Unit Converter
> Sort for converter

- src/app/app.component.css
- src/app/psat/psat-report/input-summary/input-summary.component.html
- src/app/psat/psat-report/input-summary/input-summary.component.ts
Updates to report to show differences from baseline
> report updates to show different from baseline

- src/app/shared/convert-units/definitions/apparentPower.ts
- src/app/shared/convert-units/definitions/area.ts
- src/app/shared/convert-units/definitions/current.ts
- src/app/shared/convert-units/definitions/digital.ts
- src/app/shared/convert-units/definitions/energy.ts
- src/app/shared/convert-units/definitions/length.ts
- src/app/shared/convert-units/definitions/mass.ts
- src/app/shared/convert-units/definitions/partsPer.ts
- src/app/shared/convert-units/definitions/power.ts
- src/app/shared/convert-units/definitions/pressure.ts
- src/app/shared/convert-units/definitions/reactiveEnergy.ts
- src/app/shared/convert-units/definitions/reactivePower.ts
- src/app/shared/convert-units/definitions/speed.ts
- src/app/shared/convert-units/definitions/temperature.ts
- src/app/shared/convert-units/definitions/time.ts
- src/app/shared/convert-units/definitions/viscosity.ts
- src/app/shared/convert-units/definitions/voltage.ts
- src/app/shared/convert-units/definitions/volume.ts
- src/app/shared/convert-units/definitions/volumeFlowRate.ts
Super script for units and dispaly fix
> Unit conv fix

- src/app/calculator/utilities/unit-converter/unit-converter.component.ts
- src/app/shared/convert-units/convert-units.service.ts
- src/app/shared/convert-units/definitions/force.ts
- src/app/shared/convert-units/definitions/frequency.ts
- src/app/shared/convert-units/definitions/mass.ts
- src/app/shared/convert-units/definitions/pressure.ts
Added new units to unit converter:
- Force
- Mass
- Frequency
- Pressure
> New units conv

- src/app/calculator/pumps/achievable-efficiency/achievable-efficiency-form/achievable-efficiency-form.component.css
- src/app/calculator/pumps/achievable-efficiency/achievable-efficiency-form/achievable-efficiency-form.component.html
- src/app/calculator/utilities/unit-converter/unit-converter.component.html
- Added sorting to units selection in Unite Converter.
- Fixed pump efficiency input box and unit display.
> Added sorting

- src/app/settings/phast-settings/phast-settings.component.css
- src/app/settings/phast-settings/phast-settings.component.html
> Phast engr source

- src/app/assessment/assessment-list-view/assessment-list-item/assessment-list-item.component.html
- src/app/psat/explore-opportunities/explore-opportunities-form/explore-opportunities-form.component.css
- src/app/psat/explore-opportunities/explore-opportunities-form/explore-opportunities-form.component.html
- src/app/psat/explore-opportunities/explore-opportunities.component.css
- src/app/psat/explore-opportunities/explore-opportunities.component.html
- src/app/shared/percent-graph/percent-graph.component.ts
few styling updates and fixed to dynamic percent graph
> Explore opps updates

- src/app/psat/explore-opportunities/explore-opportunities-form/explore-opportunities-form.component.html
- Added step="any" to PSAT in explore opportunities.
- Fixed KwHR to kWh
> Step any and fix for units

- src/app/psat/explore-opportunities/explore-opportunities-form/explore-opportunities-form.component.html
- src/app/psat/explore-opportunities/explore-opportunities-form/explore-opportunities-form.component.ts
> reset data on unselected modification

- src/app/app.component.css
- src/app/calculator/pumps/head-tool/head-tool-form/head-tool-form.component.css
- src/app/calculator/pumps/head-tool/head-tool-form/head-tool-form.component.html
- src/app/calculator/pumps/head-tool/head-tool-form/head-tool-form.component.ts
- src/app/calculator/pumps/head-tool/head-tool-help/head-tool-help.component.html
- src/app/calculator/pumps/head-tool/head-tool-help/head-tool-help.component.ts
- src/app/calculator/pumps/head-tool/head-tool-suction-form/head-tool-suction-form.component.css
- src/app/calculator/pumps/head-tool/head-tool-suction-form/head-tool-suction-form.component.html
- src/app/calculator/pumps/head-tool/head-tool-suction-form/head-tool-suction-form.component.ts
- src/app/calculator/pumps/head-tool/head-tool.component.css
- src/app/calculator/pumps/head-tool/head-tool.component.html
- src/app/calculator/pumps/head-tool/head-tool.component.ts
Field by field help for head tool ready.
Styling and layout updates for head tool.
> Psat calcs

- src/app/psat/motor/motor.component.ts
> Motor rpm fix

- src/app/psat/help-panel/pump-fluid-help/pump-fluid-help.component.html
- src/app/psat/pump-fluid/pump-fluid.component.html
> specified efficiency help field

- src/app/calculator/pumps/achievable-efficiency/achievable-efficiency-form/achievable-efficiency-form.component.css
- src/app/calculator/pumps/achievable-efficiency/achievable-efficiency-form/achievable-efficiency-form.component.html
- src/app/calculator/pumps/achievable-efficiency/achievable-efficiency-form/achievable-efficiency-form.component.ts
Validates user input for flow rate if is smaller than 110 or higher than 5000 gallons.
> Pump graph limits

- src/app/dashboard/dashboard.component.html
- src/app/dashboard/dashboard.component.ts
- src/app/indexedDb/indexed-db.service.ts
initializing db's on startup only fixes app crash on data reset
> Data reset updates

- src/app/phast/losses/atmosphere-losses/atmosphere-losses.component.ts
- src/app/phast/losses/auxiliary-power-losses/auxiliary-power-losses.component.ts
- src/app/phast/losses/charge-material/charge-material.component.ts
- src/app/phast/losses/charge-material/gas-charge-material-form/gas-charge-material-form.component.html
- src/app/phast/losses/charge-material/liquid-charge-material-form/liquid-charge-material-form.component.html
- src/app/phast/losses/cooling-losses/cooling-losses.component.ts
- src/app/phast/losses/cooling-losses/cooling-losses.service.ts
- src/app/phast/losses/energy-input/energy-input-form/energy-input-form.component.html
- src/app/phast/losses/energy-input/energy-input.component.ts
- src/app/phast/losses/extended-surface-losses/extended-surface-losses-form/extended-surface-losses-form.component.html
- src/app/phast/losses/extended-surface-losses/extended-surface-losses.component.ts
- src/app/phast/losses/fixture-losses/fixture-losses.component.ts
- src/app/phast/losses/flue-gas-losses/flue-gas-losses.component.ts
- src/app/phast/losses/flue-gas-losses/flue-gas-losses.service.ts
- src/app/phast/losses/gas-leakage-losses/gas-leakage-losses-form/gas-leakage-losses-form.component.html
- src/app/phast/losses/gas-leakage-losses/gas-leakage-losses.component.ts
- src/app/phast/losses/opening-losses/opening-losses.component.ts
- src/app/phast/losses/opening-losses/opening-losses.service.ts
- src/app/phast/losses/slag/slag-form/slag-form.component.html
- src/app/phast/losses/slag/slag.component.ts
- src/app/phast/losses/wall-losses/wall-losses.component.ts
- src/app/phast/phast.component.ts
- src/app/phast/phast.service.ts
- src/app/shared/models/phast/losses/openingLoss.ts
Using objects for arguments in phast.service calculation calls to addon
> Phast service update

- src/app/psat/explore-opportunities/explore-opportunities-results/explore-opportunities-results.component.html
- src/app/psat/psat-report/input-summary/input-summary.component.html
- src/app/psat/psat-report/output-summary/output-summary.component.html
> updated psat report decimal rounding

- src/app/psat/psat.service.ts
fixed issue #536 Metric units issue
> Motor power units

- src/app/psat/explore-opportunities/explore-opportunities-form/explore-opportunities-form.component.html
- src/app/psat/explore-opportunities/explore-opportunities-form/explore-opportunities-form.component.ts
- src/app/psat/explore-opportunities/explore-opportunities-help/explore-opportunities-help.component.html
Added op fraction and removed pump speed from explore opportunities PSAT.
#541 
#540
> Psat explore opp fields

- README.md
Adds an empty db directory, for use in storing database files and database backup files when the software is updated.  Also adds a small section of information in the README.md file about the database backups.
> Adds empty db directory

- src/app/psat/explore-opportunities/explore-opportunities-form/explore-opportunities-form.component.ts
- src/app/psat/field-data/field-data.component.ts
- src/app/psat/psat.service.ts
- src/app/shared/convert-units/convert-units.service.ts
> flow validation rate fix

- src/app/phast/losses/charge-material/solid-charge-material-form/solid-charge-material-form.component.ts
- src/app/phast/losses/losses-tabs/losses-tabs.component.html
- src/app/phast/losses/losses.component.html
- src/app/phast/operating-hours/operating-hours.component.css
- src/app/phast/operating-hours/operating-hours.component.html
- src/app/phast/operating-hours/operating-hours.component.ts
- src/app/phast/phast.component.html
- src/app/settings/phast-settings/phast-settings.component.html
- src/app/settings/phast-settings/phast-settings.component.ts
- src/app/shared/models/phast/phast.ts
Small updates to phast settings and operating hour functionality
> Phast settings and operating hours

- src/app/psat/psat.service.ts
fix input methods for headTool, was broken due to a change on the backend.
> add headTool objects as input

- package.json
> update version numbers of the desktop and suite

- src/app/psat/help-panel/pump-fluid-help/pump-fluid-help.component.html
Fix for Pump & Motor min and max RPM
> Issue #600

- README.md
- package.json
Adds npm run clean to make life easier, as well as updates the readme slightly to reflect the current build process
> Add npm run clean and update readme a bit

- src/app/core/core.component.html
- src/app/core/core.component.ts
Feedback text for windows:
"Help us further understand your request by downloading and attaching your current data set. If possible, please attach a screen shot of the interface as well."
> hide screenshot for windows

- src/app/calculator/pumps/head-tool/head-tool-form/head-tool-form.component.css
- src/app/calculator/pumps/head-tool/head-tool-form/head-tool-form.component.html
- src/app/calculator/pumps/head-tool/head-tool-form/head-tool-form.component.ts
- src/app/calculator/pumps/head-tool/head-tool-results/head-tool-results.component.css
- src/app/calculator/pumps/head-tool/head-tool-results/head-tool-results.component.html
- src/app/calculator/pumps/head-tool/head-tool-suction-form/head-tool-suction-form.component.html
- src/app/calculator/pumps/head-tool/head-tool-suction-form/head-tool-suction-form.component.ts
- src/app/calculator/pumps/head-tool/head-tool.component.html
- src/app/calculator/pumps/head-tool/head-tool.component.ts
- src/app/psat/field-data/field-data.component.html
- src/app/psat/field-data/field-data.component.ts
> error messaging for head tool

- package.json
- src/app/phast/losses/energy-input/energy-input-compare.service.ts
- src/app/phast/losses/energy-input/energy-input-form/energy-input-form.component.html
- src/app/phast/losses/energy-input/energy-input-form/energy-input-form.component.ts
- src/app/phast/losses/energy-input/energy-input.component.html
- src/app/phast/losses/energy-input/energy-input.component.ts
- src/app/phast/losses/energy-input/energy-input.service.ts
- src/app/phast/losses/exhaust-gas/exhaust-gas-compare.service.ts
- src/app/phast/losses/exhaust-gas/exhaust-gas-form/exhaust-gas-form.component.html
- src/app/phast/losses/exhaust-gas/exhaust-gas-form/exhaust-gas-form.component.ts
- src/app/phast/losses/exhaust-gas/exhaust-gas.component.ts
- src/app/phast/losses/exhaust-gas/exhaust-gas.service.ts
- src/app/phast/phast.component.ts
- src/app/phast/phast.service.ts
- src/app/shared/mocks/mock-directory.ts
- src/app/shared/models/phast/losses/energyInputEAF.ts
- src/app/shared/models/phast/losses/exhaustGasEAF.ts
- src/app/shared/models/phast/phast.ts
Electric Arc Furnace to match new tools-suite
Models and services related to ExhaustGas and EnergyInput updated to reflect changes:
exhaustGas method is now exhaustGasEAF
energyInput method is now energyInputEAF
measuredOxygenFlow and naturalGasFlow are gone from the expected inputs for energyInputEAF
cycleTime, O2 and CO2 are gone from the inputs for exhaustGasEAF
> Tools suite update

- package.json
- src/app/phast/designed-energy/designed-energy-results/designed-energy-results.component.html
- src/app/phast/losses/cooling-losses/cooling-losses-compare.service.ts
- src/app/phast/losses/cooling-losses/cooling-losses.service.ts
- src/app/phast/losses/cooling-losses/gas-cooling-losses-form/gas-cooling-losses-form.component.html
- src/app/phast/losses/cooling-losses/gas-cooling-losses-form/gas-cooling-losses-form.component.ts
- src/app/phast/losses/energy-input/energy-input.component.ts
- src/app/phast/losses/heat-system-efficiency/heat-system-efficiency.component.html
- src/app/phast/losses/losses.component.ts
- src/app/phast/metered-energy/metered-electricity/metered-electricity.component.ts
- src/app/phast/metered-energy/metered-fuel/metered-fuel.component.ts
- src/app/phast/metered-energy/metered-steam/metered-steam.component.ts
- src/app/phast/phast.component.ts
- src/app/phast/phast.service.ts
- src/app/shared/convert-units/definitions/energy.ts
- src/app/shared/mocks/mock-directory.ts
- src/app/shared/models/phast/losses/coolingLoss.ts
npm package updates
issue #641 #635 #630
> Phast updates

- src/app/shared/convert-units/definitions/energy.ts
- src/app/shared/convert-units/definitions/power.ts
- src/app/shared/convert-units/definitions/specificHeat.ts
New conversion units and separation for imperial and metric units
> Specific heat uniits

- src/app/phast/losses/energy-input/energy-input-compare.service.ts
- src/app/phast/losses/energy-input/energy-input-form/energy-input-form.component.html
- src/app/phast/losses/energy-input/energy-input-form/energy-input-form.component.ts
- src/app/phast/losses/energy-input/energy-input.service.ts
- src/app/phast/metered-energy/metered-energy.service.ts
- src/app/phast/metered-energy/metered-fuel/metered-fuel-form/metered-fuel-form.component.html
- src/app/phast/metered-energy/metered-fuel/metered-fuel-form/metered-fuel-form.component.ts
- src/app/phast/metered-energy/metered-fuel/metered-fuel.component.ts
- src/app/shared/mocks/mock-directory.ts
- src/app/shared/models/phast/losses/energyInputEAF.ts
- src/app/shared/models/phast/meteredEnergy.ts
- A new way to calculate Metered Energy, Fuel Energy by using Natural Gas Flow Rate input for fuel fire furnace.
- A new way to calculate Modify Conditions, Energy Input by using Natural Gas Flow Rate input for Electrotechnology furnace.
> Issues 646 & 658

- main.js
- src/app/calculator/calculator.component.html
- src/app/calculator/pumps/pump-curve/pump-curve-equation-form/pump-curve-equation-form.component.html
- src/app/calculator/pumps/pump-curve/pump-curve-form/pump-curve-form.component.html
- src/app/calculator/pumps/pump-curve/pump-curve-graph/pump-curve-graph.component.ts
- Fix for auto-update
- Add "Pump Curve" to "All Calculators"
- Change units in "Pump Curve" for Baseline and Modify Conditions for Speed to "rpm"
- Change verbiage on graph for Pump Curve from gal/min to gpm
> Issues closes #659, closes #660,  closes #664

- src/app/phast/losses/cooling-losses/cooling-losses.service.ts
- src/app/phast/losses/extended-surface-losses/extended-surface-losses.service.ts
- src/app/phast/losses/flue-gas-losses/flue-gas-losses-form-mass/flue-gas-losses-form-mass.component.html
- src/app/phast/losses/flue-gas-losses/flue-gas-losses-form-volume/flue-gas-losses-form-volume.component.html
- src/app/phast/losses/flue-gas-losses/flue-gas-losses.component.ts
- src/app/phast/losses/losses-help/charge-material-help/charge-material-help.component.html
- src/app/phast/losses/losses-help/extended-surface-losses-help/extended-surface-losses-help.component.html
- src/app/phast/losses/losses-help/flue-gas-losses-help/flue-gas-losses-help.component.html
- src/app/phast/losses/losses-help/flue-gas-losses-help/flue-gas-losses-help.component.ts
- src/app/phast/losses/losses-help/other-losses-help/other-losses-help.component.html
- src/app/phast/losses/losses-help/wall-losses-help/wall-losses-help.component.html
- src/app/phast/losses/opening-losses/opening-losses.service.ts
Help fields for PHAST & new default values.
> Phast help

- src/app/psat/help-panel/help-panel.component.html
- src/app/psat/help-panel/pump-fluid-help/pump-fluid-help.component.html
- src/app/psat/help-panel/pump-fluid-help/pump-fluid-help.component.ts
- src/app/psat/pump-fluid/pump-fluid.component.ts
Validation and help for belt drive in max
> Belt drive max

- package.json
- src/app/phast/losses/flue-gas-losses/flue-gas-losses-form-mass/flue-gas-losses-form-mass.component.html
- src/app/phast/phast.service.ts
- src/app/shared/models/materials.ts
- src/app/suiteDb/atmosphere-specific-heat-material/atmosphere-specific-heat-material.component.ts
- src/app/suiteDb/flue-gas-material/flue-gas-material.component.html
- src/app/suiteDb/flue-gas-material/flue-gas-material.component.ts
- src/app/suiteDb/gas-load-charge-material/gas-load-charge-material.component.ts
- src/app/suiteDb/liquid-load-charge-material/liquid-load-charge-material.component.ts
- src/app/suiteDb/solid-liquid-flue-gas-material/solid-liquid-flue-gas-material.component.html
- src/app/suiteDb/solid-liquid-flue-gas-material/solid-liquid-flue-gas-material.component.ts
- src/app/suiteDb/solid-load-charge-material/solid-load-charge-material.component.ts
- src/app/suiteDb/wall-losses-surface/wall-losses-surface.component.ts
completes issue #726 
**Important**
Must update tools suite in npm with corresponding changes before merging this PR
> Flue gas hhv

- src/app/phast/losses/flue-gas-losses/flue-gas-losses-form-mass/flue-gas-losses-form-mass.component.css
- src/app/phast/losses/flue-gas-losses/flue-gas-losses-form-mass/flue-gas-losses-form-mass.component.html
- src/app/phast/losses/flue-gas-losses/flue-gas-losses-form-volume/flue-gas-losses-form-volume.component.css
- src/app/phast/losses/flue-gas-losses/flue-gas-losses-form-volume/flue-gas-losses-form-volume.component.html
- src/app/suiteDb/flue-gas-material/flue-gas-material-help/flue-gas-material-help.component.html
- src/app/suiteDb/flue-gas-material/flue-gas-material-help/flue-gas-material-help.component.spec.ts
- src/app/suiteDb/flue-gas-material/flue-gas-material-help/flue-gas-material-help.component.ts
- src/app/suiteDb/flue-gas-material/flue-gas-material.component.html
- src/app/suiteDb/flue-gas-material/flue-gas-material.component.ts
- src/app/suiteDb/solid-liquid-flue-gas-material/solid-liquid-flue-gas-material-help/solid-liquid-flue-gas-material-help.component.html
- src/app/suiteDb/solid-liquid-flue-gas-material/solid-liquid-flue-gas-material-help/solid-liquid-flue-gas-material-help.component.spec.ts
- src/app/suiteDb/solid-liquid-flue-gas-material/solid-liquid-flue-gas-material-help/solid-liquid-flue-gas-material-help.component.ts
- src/app/suiteDb/solid-liquid-flue-gas-material/solid-liquid-flue-gas-material.component.html
- src/app/suiteDb/solid-liquid-flue-gas-material/solid-liquid-flue-gas-material.component.ts
- src/app/suiteDb/suiteDb.module.ts
Flue Gases Help Field by Field for Add New Gas Modal
> Flue Gases Help Field by Field 

- src/app/phast/losses/auxiliary-power-losses/auxiliary-power-losses-form/auxiliary-power-losses-form.component.html
- src/app/phast/losses/auxiliary-power-losses/auxiliary-power-losses-form/auxiliary-power-losses-form.component.ts
- src/app/phast/losses/auxiliary-power-losses/auxiliary-power-losses.module.ts
- src/app/phast/losses/energy-input-exhaust-gas-losses/energy-input-exhaust-gas-form/energy-input-exhaust-gas-form.component.html
- src/app/phast/losses/energy-input-exhaust-gas-losses/energy-input-exhaust-gas.service.ts
- src/app/phast/losses/energy-input/energy-input-form/energy-input-form.component.html
- src/app/phast/losses/exhaust-gas/exhaust-gas-form/exhaust-gas-form.component.html
- src/app/phast/losses/heat-system-efficiency/heat-system-efficiency.component.html
- src/app/phast/losses/losses-help/auxiliary-power-losses-help/auxiliary-power-losses-help.component.html
- src/app/phast/losses/losses-help/energy-input-exhaust-gas-losses-help/energy-input-exhaust-gas-losses-help.component.html
- src/app/phast/losses/losses-help/energy-input-help/energy-input-help.component.html
- src/app/phast/losses/losses-help/exhaust-gas-help/exhaust-gas-help.component.html
- src/app/phast/losses/losses-help/heat-system-efficiency-help/heat-system-efficiency-help.component.html
- src/app/phast/losses/losses-help/slag-help/slag-help.component.html
- src/app/phast/losses/slag/slag-form/slag-form.component.html
- src/app/shared/mocks/mock-directory.ts
Issue #633 
- Field by field help for PHAST
- New default values for input fields
- Set max and min of input fields
> Rest of the Help for PHAST & New Defaults #633

- src/app/calculator/calculator.component.html
- src/app/calculator/utilities/cash-flow/cash-flow-diagram/cash-flow-diagram.component.css
- src/app/calculator/utilities/cash-flow/cash-flow-diagram/cash-flow-diagram.component.html
- src/app/calculator/utilities/cash-flow/cash-flow-diagram/cash-flow-diagram.component.spec.ts
- src/app/calculator/utilities/cash-flow/cash-flow-diagram/cash-flow-diagram.component.ts
- src/app/calculator/utilities/cash-flow/cash-flow-form/cash-flow-form.component.html
- src/app/calculator/utilities/cash-flow/cash-flow-form/cash-flow-form.component.spec.ts
- src/app/calculator/utilities/cash-flow/cash-flow-form/cash-flow-form.component.ts
- src/app/calculator/utilities/cash-flow/cash-flow-help/cash-flow-help.component.html
- src/app/calculator/utilities/cash-flow/cash-flow-help/cash-flow-help.component.spec.ts
- src/app/calculator/utilities/cash-flow/cash-flow-help/cash-flow-help.component.ts
- src/app/calculator/utilities/cash-flow/cash-flow.component.html
- src/app/calculator/utilities/cash-flow/cash-flow.component.spec.ts
- src/app/calculator/utilities/cash-flow/cash-flow.component.ts
- src/app/calculator/utilities/cash-flow/cash-flow.ts
- src/app/calculator/utilities/utilities.component.html
- src/app/calculator/utilities/utilities.module.ts
New calculator "Cash Flow Calculator" for Utilities
> Cash Flow Calculator

- src/app/phast/losses/heat-system-efficiency/heat-system-efficiency-compare.service.spec.ts
- src/app/phast/losses/heat-system-efficiency/heat-system-efficiency-compare.service.ts
- src/app/phast/losses/heat-system-efficiency/heat-system-efficiency.component.ts
- src/app/phast/losses/heat-system-efficiency/heat-system-efficiency.module.ts
- src/app/phast/losses/losses.module.ts
- src/app/phast/losses/operations/operations-compare.service.spec.ts
- src/app/phast/losses/operations/operations-compare.service.ts
- src/app/phast/losses/operations/operations-form/operations-form.component.ts
- src/app/phast/losses/operations/operations.component.ts
- src/app/phast/losses/operations/operations.module.ts
> Compare services

- src/app/calculator/utilities/cash-flow/cash-flow-diagram/cash-flow-diagram.component.html
- src/app/calculator/utilities/cash-flow/cash-flow.component.html
- src/app/calculator/utilities/cash-flow/cash-flow.component.ts
- src/app/calculator/utilities/utilities.component.html
Just formatting cleanup for cash flow layout and results
> cash flow calc formatting

- src/app/calculator/utilities/cash-flow/cash-flow-form/cash-flow-form.component.html
- src/app/calculator/utilities/cash-flow/cash-flow-form/cash-flow-form.component.ts
- src/app/calculator/utilities/cash-flow/cash-flow-help/cash-flow-help.component.html
- src/app/calculator/utilities/cash-flow/cash-flow-help/cash-flow-help.component.ts
- src/app/calculator/utilities/cash-flow/cash-flow.component.html
- src/app/calculator/utilities/cash-flow/cash-flow.component.ts
- src/app/calculator/utilities/utilities.component.html
Issue #753 
-  Help field by field
- New default values
> Cash flow calculator 

- src/app/shared/convert-units/definitions/volume.ts
- src/app/shared/convert-units/definitions/volumeFlowRate.ts
Issues #781 #783 
-  Gallons changed to U.S Gallons
-  New Volume unit Imperial Gallons
- New Volumetric Flow Rate unit Imperial Gallons per Minute
> New Units for Unit Converter

- src/app/phast/losses/auxiliary-power-losses/auxiliary-power-losses.component.html
- src/app/phast/losses/auxiliary-power-losses/auxiliary-power-losses.component.ts
- src/app/phast/losses/losses-help/losses-help.component.css
- src/app/phast/losses/losses.component.html
- src/app/psat/explore-opportunities/explore-opportunities-form/explore-opportunities-form.component.ts
- src/app/settings/psat-settings/psat-settings.component.ts
- src/app/shared/convert-units/definitions/pressure.ts
- src/app/shared/models/phast/losses/auxiliaryPowerLoss.ts
Issues #794 #787 #784 
-  Fixed typo in PSAT
- PHAST Not EAF Heat output units Btu/hr and kJ/hr
- New custom units for PSAT settings (Bar)
> Updates #794 #787 #784

- src/app/phast/phast-report/executive-summary/executive-summary.component.html
- src/app/phast/phast-report/executive-summary/executive-summary.component.ts
- src/app/phast/phast-report/report-graphs/phast-bar-chart/phast-bar-chart.component.ts
- src/app/phast/phast-report/results-data/results-data.component.html
- src/app/phast/phast-report/results-data/results-data.component.ts
> result units for electrotech

- src/app/calculator/calculator.component.html
- src/app/calculator/utilities/utilities.component.html
- src/app/phast/losses/losses-help/operations-help/operations-help.component.html
Issue #799
- Help fields for PHAST operation cost.
> Help Fields for Operations #799

- src/app/phast/convert-phast.service.ts
- src/app/phast/losses/cooling-losses/cooling-losses-compare.service.ts
- src/app/phast/losses/energy-input/energy-input-form/energy-input-form.component.html
- src/app/phast/losses/fixture-losses/fixture-losses-form/fixture-losses-form.component.html
- src/app/phast/phast.component.html
- src/app/phast/phast.service.ts
- src/app/phast/system-basics/system-basics.component.ts
has changes from pr #804 so that should be done first.
connects #803
> Compare service fix

- src/app/calculator/pumps/head-tool/head-tool.component.ts
- src/app/psat/psat.service.ts
> fix head tool convert units

- src/app/phast/phast-report/energy-used/energy-used.component.html
- src/app/phast/phast-report/energy-used/energy-used.component.ts
- src/app/phast/phast-report/executive-summary/executive-summary.component.html
Issue #756 
Different units are displayed depending on PHAST Setup.
> Issue 756 Units for PHAST Report

- src/app/calculator/furnaces/o2-enrichment/o2-enrichment-form/o2-enrichment-form.component.html
- src/app/calculator/furnaces/o2-enrichment/o2-enrichment-form/o2-enrichment-form.component.ts
- src/app/calculator/furnaces/o2-enrichment/o2-enrichment-graph/o2-enrichment-graph.component.ts
- src/app/calculator/furnaces/o2-enrichment/o2-enrichment-help/o2-enrichment-help.component.html
- src/app/calculator/furnaces/o2-enrichment/o2-enrichment.component.html
- src/app/calculator/furnaces/o2-enrichment/o2-enrichment.component.ts
- tslint.json
connects #700 
connects #810
connects https://github.com/ORNL-AMO/AMO-Tools-Suite/issues/138
Updates the o2 enrichment graph page to be safer behind the scenes and display a popup box that shows previously plotted line conditions, as well as enforcing mins / maxes. The graph state will now be saved when the user selects the help text
> Issue 700 - O2 Enrichment graph updates

- src/app/calculator/pumps/pump-curve/pump-curve-data-form/pump-curve-data-form.component.html
- src/app/calculator/pumps/pump-curve/pump-curve-data-form/pump-curve-data-form.component.ts
- src/app/calculator/pumps/pump-curve/pump-curve-equation-form/pump-curve-equation-form.component.html
- src/app/calculator/pumps/pump-curve/pump-curve-equation-form/pump-curve-equation-form.component.ts
- src/app/calculator/pumps/pump-curve/pump-curve-form/pump-curve-form.component.html
- src/app/calculator/pumps/pump-curve/pump-curve-form/pump-curve-form.component.ts
- src/app/calculator/pumps/pump-curve/pump-curve-graph/pump-curve-graph.component.ts
- src/app/calculator/pumps/pump-curve/pump-curve.component.html
- src/app/calculator/pumps/pump-curve/pump-curve.component.ts
- src/app/psat/psat.component.html
connects #679 
Unit conversion for forms
- Pump curve equation.
- Pump curve data.
- Pump curve graph.
> Unit conversion For PSAT

- src/app/phast/phast-report/phast-report.component.html
- src/app/phast/phast-report/phast-report.component.ts
> checks for setup done

- src/app/phast/losses/energy-input-exhaust-gas-losses/energy-input-exhaust-gas-losses.component.ts
- src/app/phast/losses/fixture-losses/fixture-losses.component.html
- src/app/phast/losses/fixture-losses/fixture-losses.component.ts
- src/app/phast/losses/flue-gas-losses/flue-gas-losses.component.ts
- src/app/phast/losses/heat-system-efficiency/heat-system-efficiency.component.ts
- src/app/phast/losses/losses-help/flue-gas-losses-help/flue-gas-losses-help.component.ts
- src/app/phast/phast-report/phast-report.component.ts
- src/app/phast/phast-results.service.ts
- src/app/phast/phast.service.ts
- src/app/phast/sankey/sankey.service.ts
> convert exothermic for electricity

- src/app/calculator/furnaces/o2-enrichment/o2-enrichment-form/o2-enrichment-form.component.css
- src/app/calculator/furnaces/o2-enrichment/o2-enrichment-form/o2-enrichment-form.component.html
- src/app/calculator/furnaces/o2-enrichment/o2-enrichment-form/o2-enrichment-form.component.ts
- src/app/calculator/furnaces/o2-enrichment/o2-enrichment-graph/o2-enrichment-graph.component.ts
- src/app/calculator/furnaces/o2-enrichment/o2-enrichment.component.html
Update the o2 enrichment graph to make sense and be (hopefully) more user friendly
connects #822
> O2 enrichment tidying

- src/app/psat/field-data/field-data.component.html
- src/app/psat/psat-report/output-summary/output-summary.component.html
- src/app/psat/psat-report/output-summary/output-summary.component.ts
- src/app/psat/psat.service.ts
- src/app/shared/models/psat.ts
> adds implementation costs for psat

- src/app/phast/phast-report/energy-used/energy-used.component.ts
connects ORNL-AMO/AMO-Tools-Suite#141
> fix hhv units in report

- src/app/phast/sankey/sankey.component.ts
- src/app/phast/sankey/sankey.service.ts
Issue #817
Fixed issue with labels layout in Sankey Diagram.
> Sankey layout

- src/app/phast/sankey/sankey.service.ts
connects #831 
connects #832
Fixed conversion to kW where output was divided by 1,000,000.
> Sankey Electrotechnologies

- package.json
- src/app/assessment/assessment-menu/assessment-menu.component.ts
- src/app/calculator/furnaces/o2-enrichment/o2-enrichment-graph/o2-enrichment-graph.component.ts
- src/app/calculator/utilities/cash-flow/cash-flow-diagram/cash-flow-diagram.component.html
- src/app/calculator/utilities/combined-heat-power/combined-heat-power-results/combined-heat-power-results.component.html
- src/app/phast/phast-report/energy-used/energy-used.component.html
- src/app/phast/phast-report/executive-summary/executive-summary.component.html
- src/app/psat/explore-opportunities/explore-opportunities-results/explore-opportunities-results.component.html
- src/app/psat/explore-opportunities/explore-opportunities.component.html
- src/app/psat/psat-report/output-summary/output-summary.component.html
- src/app/report-rollup/report-summary/phast-summary/phast-summary.component.html
- src/app/report-rollup/report-summary/psat-summary/psat-summary.component.html
upgraded angular and dependencies to match Angular V5. 
will need to `npm run clean` and `npm install`
aot still broken
> Angular upgrade

- src/app/phast/sankey/sankey.component.ts
Issue #850 
- Labels and units format update.
- Update for units displays two decimal points.
> Issue #850 Sankey Forrmating Updatets

- src/app/phast/sankey/sankey.component.ts
connects #855
Fixing issue with "Useful Output" going off the screen.
> Issue #855 Sankey Useful Output Format

- main.js
- src/app/phast/losses/wall-losses/wall-losses.component.html
- src/app/phast/phast-report/energy-used/energy-used.component.html
- src/app/phast/phast-report/executive-summary/executive-summary.component.html
- src/app/phast/phast-report/phast-report.module.ts
- src/app/phast/phast-report/results-data/results-data.component.html
- src/app/phast/phast.component.ts
- src/app/phast/phast.service.ts
- src/app/phast/system-basics/system-basics.component.ts
- src/app/psat/psat-report/input-summary/input-summary.component.html
- src/app/psat/psat-report/output-summary/output-summary.component.html
- src/app/settings/application-settings/application-settings.component.html
- src/app/settings/application-settings/application-settings.component.ts
- src/app/settings/phast-settings/phast-settings.component.ts
- src/app/settings/settings.service.ts
- src/app/shared/convert-units/definitions/energy.ts
- src/app/shared/models/settings.ts
- src/app/shared/shared.module.ts
- src/app/shared/sig-figs.pipe.spec.ts
- src/app/shared/sig-figs.pipe.ts
connects #865 
PSAT & PHAST report results with 5 significant figures for all unit types
> Issue #865

- src/app/app.component.css
- src/app/psat/explore-opportunities/explore-opportunities-results/explore-opportunities-results.component.css
- src/app/psat/explore-opportunities/explore-opportunities-results/explore-opportunities-results.component.html
- src/app/psat/psat-report/input-summary/input-summary.component.css
- src/app/psat/psat-report/input-summary/input-summary.component.html
- src/app/psat/psat-report/output-summary/output-summary.component.css
- src/app/psat/psat-report/output-summary/output-summary.component.html
- src/app/shared/percent-graph/percent-graph.component.ts
- src/app/shared/sig-figs.pipe.ts
fixes report donut bugs
removes sig figs from input data in psat
> report bug fix and style updateS

- src/app/psat/explore-opportunities/explore-opportunities-form/explore-opportunities-form.component.html
- src/app/psat/explore-opportunities/explore-opportunities-form/explore-opportunities-form.component.ts
connects #877 
If Optimize checkbox is selected then the field for kinematic viscosity becoming visible.
> Kinematic Viscosity Input Field

- package.json
adds `electron-download-tf` dependency
> add electron-download-tf dependency

- package.json
Updates tools-suite version number to 0.2.9
> update tools-suite version number to 0.2.9

- src/app/version-modal/version-modal.component.html
Updates the release notes within the app
> Update release notes for v0.2.3

- src/app/phast/losses/flue-gas-losses/flue-gas-losses-form-mass/flue-gas-losses-form-mass.component.html
- src/app/phast/losses/flue-gas-losses/flue-gas-losses-form-volume/flue-gas-losses-form-volume.component.html
- src/app/phast/sankey/sankey.component.ts
- src/app/psat/psat-report/output-summary/output-summary.component.html
connect #895 
connect #903 
connect #905
**PHAST**
- Font and location adjustment for Sankey in report section
- Losses Flue Gas label changed from "Gas Temperature" to "Flue Gas Temperature"
**PSAT**
- Significant numbers for Report
> New Font Size for Sankey Report, PSAT Report Significant Numbers  

- src/app/calculator/furnaces/furnaces.component.html
- src/app/phast/losses/charge-material/liquid-charge-material-form/liquid-charge-material-form.component.html
- src/app/phast/losses/flue-gas-losses/flue-gas-losses-form-volume/flue-gas-losses-form-volume.component.html
- src/app/phast/losses/flue-gas-losses/flue-gas-losses-form-volume/flue-gas-losses-form-volume.component.ts
- src/app/phast/losses/gas-leakage-losses/gas-leakage-losses-form/gas-leakage-losses-form.component.html
- src/app/phast/losses/losses-help/charge-material-help/charge-material-help.component.html
- src/app/phast/losses/losses-help/flue-gas-losses-help/flue-gas-losses-help.component.html
- src/app/phast/losses/losses-help/gas-leakage-losses-help/gas-leakage-losses-help.component.html
- src/app/phast/losses/losses-help/wall-losses-help/wall-losses-help.component.html
Mostly help text updates and unit / field name changes
connect #887 
connect #943 
connect #915 
connect #942 
connect #944 
connect #928
> 6 smaller PHAST issues

- package.json
rxjs 5.5.2 works. 5.5.3 does not
per: https://github.com/ReactiveX/rxjs/issues/3151 they are aware of issue and next minor release will have fix
> update rxjs version num

- src/app/acknowledgments-page/acknowledgments-page.component.html
- src/app/acknowledgments-page/acknowledgments-page.component.spec.ts
- src/app/acknowledgments-page/acknowledgments-page.component.ts
- src/app/core/core.module.ts
- src/app/dashboard/dashboard.component.html
- src/app/dashboard/dashboard.component.ts
- src/app/shared/import-export/import-export.component.html
- src/app/sidebar/sidebar.component.html
- src/app/sidebar/sidebar.component.ts
Add Acknowledgments page to the sidebar
connect #935
> add acknowledgments page

- src/app/phast/losses/energy-input-exhaust-gas-losses/energy-input-exhaust-gas-form/energy-input-exhaust-gas-form.component.html
- src/app/phast/losses/exhaust-gas/exhaust-gas-form/exhaust-gas-form.component.html
- src/app/phast/losses/flue-gas-losses/flue-gas-losses-form-mass/flue-gas-losses-form-mass.component.html
- src/app/phast/losses/flue-gas-losses/flue-gas-losses-form-volume/flue-gas-losses-form-volume.component.html
- src/app/phast/losses/losses-help/cooling-losses-help/cooling-losses-help.component.html
- src/app/phast/losses/losses-help/energy-input-exhaust-gas-losses-help/energy-input-exhaust-gas-losses-help.component.html
- src/app/phast/losses/losses-help/exhaust-gas-help/exhaust-gas-help.component.html
- src/app/phast/losses/losses-help/fixture-losses-help/fixture-losses-help.component.html
- src/app/phast/losses/losses-help/flue-gas-losses-help/flue-gas-losses-help.component.html
- src/app/phast/losses/losses-help/slag-help/slag-help.component.html
- src/app/phast/losses/slag/slag-form/slag-form.component.html
Remove minimum values from the PHAST temperature fields specified in the issue. Changes step to be 10 for temperature fields as well and remove keyboard enforced mins of 0
connect #912
> PHAST Help text temperature mins

- src/app/phast/losses/cooling-losses/cooling-losses.component.ts
- src/app/phast/losses/cooling-losses/cooling-losses.service.ts
> fixed issue 916

- src/app/phast/losses/energy-input-exhaust-gas-losses/energy-input-exhaust-gas-losses.component.ts
- src/app/phast/losses/losses.service.ts
- src/app/phast/phast-report/energy-used/energy-used.component.html
- src/app/phast/phast-report/energy-used/energy-used.component.ts
- src/app/phast/phast-report/phast-report.component.html
- src/app/phast/phast.component.ts
- src/app/phast/phast.service.ts
- src/app/phast/sankey/sankey.component.ts
connects #873 
connects #872 
had .PNG instead of .png file extension
> Issue #873 & #872

- package.json
- src/app/calculator/calculator.component.html
- src/app/phast/losses/flue-gas-losses/flue-gas-losses-form-mass/flue-gas-losses-form-mass.component.html
- src/app/phast/losses/flue-gas-losses/flue-gas-losses-form-mass/flue-gas-losses-form-mass.component.ts
- src/app/phast/losses/flue-gas-losses/flue-gas-losses-form-volume/flue-gas-losses-form-volume.component.ts
- src/app/phast/losses/flue-gas-losses/flue-gas-losses.service.ts
- src/app/phast/losses/losses-help/energy-input-exhaust-gas-losses-help/energy-input-exhaust-gas-losses-help.component.html
- src/app/phast/losses/losses-help/flue-gas-losses-help/flue-gas-losses-help.component.html
- src/app/phast/phast.service.ts
- src/app/shared/models/phast/losses/flueGas.ts
Remove help text minimums, add flue gas dropdown menu for solid/liquid/by mass flue gas, and add cash flow diagram description
connect #927 
connect #945 
connect #954
> Flue gas dropdown

- src/app/phast/aux-equipment/aux-equipment-form/aux-equipment-form.component.html
- src/app/phast/aux-equipment/aux-equipment-form/aux-equipment-form.component.ts
- src/app/phast/aux-equipment/aux-equipment-help/aux-equipment-help.component.html
- src/app/phast/losses/auxiliary-power-losses/auxiliary-power-losses-form/auxiliary-power-losses-form.component.html
- src/app/phast/losses/auxiliary-power-losses/auxiliary-power-losses-form/auxiliary-power-losses-form.component.ts
- src/app/phast/losses/auxiliary-power-losses/auxiliary-power-losses.component.html
- src/app/phast/losses/auxiliary-power-losses/auxiliary-power-losses.component.ts
- src/app/phast/losses/losses-help/auxiliary-power-losses-help/auxiliary-power-losses-help.component.html
connect #966
Updates:
1. Furnace Electrotechnologies => Auxiliary Power:
-  Phase drop-down
- Input field Supply Voltage user input validation and new help text Min/max 
2. Aux Equipment
- Supply Voltage user input validation and help text Min/max
> Motor phase and supply voltage in Auxiliary Power

- src/app/calculator/utilities/utilities.component.html
- src/app/phast/help-panel/help-panel.component.html
- src/app/phast/help-panel/help-panel.component.ts
- src/app/phast/losses/charge-material/gas-charge-material-form/gas-charge-material-form.component.ts
- src/app/phast/losses/charge-material/liquid-charge-material-form/liquid-charge-material-form.component.ts
- src/app/phast/losses/charge-material/solid-charge-material-form/solid-charge-material-form.component.ts
- src/app/phast/losses/cooling-losses/gas-cooling-losses-form/gas-cooling-losses-form.component.ts
- src/app/phast/losses/cooling-losses/liquid-cooling-losses-form/liquid-cooling-losses-form.component.ts
- src/app/phast/losses/fixture-losses/fixture-losses-form/fixture-losses-form.component.ts
- src/app/phast/losses/flue-gas-losses/flue-gas-losses-form-mass/flue-gas-losses-form-mass.component.ts
- src/app/phast/losses/wall-losses/wall-losses-form/wall-losses-form.component.ts
- src/app/phast/phast.component.html
connect #973 
connect #911 
connect #976 
Updates:
- PHAST settings help fields for "Operating Hours" and "Operating Costs"
- PHAST typos on user input validation fix
- Cash Flow Calculator new general description
> PHAST Setup Help

- src/app/psat/field-data/field-data.component.html
- src/app/psat/help-panel/field-data-help/field-data-help.component.html
connect #939 
- PSAT Motor Power/Current label changes
- PSAT Motor Power/Current  input field help text verbiage changes
> PSAT Motor Power/Current labels changes

- src/app/about-page/about-page.component.html
- src/app/acknowledgments-page/acknowledgments-page.component.html
Tom requested a rearranged acknowledgments page and that a snippet of text be added to the about page. Found and fixed a couple of small typos while looking through the html
connect #1001
> add text to the about page and rearrange existing acknowledgments page

- src/app/app.component.css
- src/app/phast/losses/charge-material/liquid-charge-material-form/liquid-charge-material-form.component.html
- src/app/phast/losses/charge-material/liquid-charge-material-form/liquid-charge-material-form.component.ts
- src/app/phast/losses/cooling-losses/gas-cooling-losses-form/gas-cooling-losses-form.component.html
- src/app/phast/losses/cooling-losses/gas-cooling-losses-form/gas-cooling-losses-form.component.ts
- src/app/phast/losses/cooling-losses/liquid-cooling-losses-form/liquid-cooling-losses-form.component.html
- src/app/phast/losses/cooling-losses/liquid-cooling-losses-form/liquid-cooling-losses-form.component.ts
- src/app/phast/losses/flue-gas-losses/flue-gas-losses-form-mass/flue-gas-losses-form-mass.component.html
- src/app/phast/losses/flue-gas-losses/flue-gas-losses-form-mass/flue-gas-losses-form-mass.component.ts
- src/app/phast/losses/losses-help/charge-material-help/charge-material-help.component.html
- src/app/phast/losses/losses-help/flue-gas-losses-help/flue-gas-losses-help.component.html
Connects #911
New Min/Max for input fields in PHAST losses.
Update for help content for input fields.
> New Min/Max for PHAST

- src/app/assessment/assessment-create/assessment-create.component.html
- src/app/assessment/assessment-create/assessment-create.component.ts
- src/app/dashboard/dashboard.component.html
- src/app/dashboard/dashboard.component.ts
- src/app/landing-screen/landing-screen.component.css
- src/app/landing-screen/landing-screen.component.html
- src/app/landing-screen/landing-screen.component.ts
- src/app/phast/losses/atmosphere-losses/atmosphere-losses-form/atmosphere-losses-form.component.html
- src/app/phast/losses/losses-result-panel/losses-result-panel.component.html
- src/app/phast/phast-report/report-graphs/phast-bar-chart/phast-bar-chart.component.ts
- src/app/phast/phast.component.css
- src/app/phast/phast.component.html
- src/app/phast/phast.component.ts
- src/app/phast/system-basics/system-basics.component.ts
- src/app/sidebar/sidebar.component.html
- src/app/sidebar/sidebar.component.ts
connects #986 
connects #998 
connects #999 
connects #919 
connects #994 
connects #1000
> Phast bug fixes

- src/app/version-modal/version-modal.component.html
updates release notes for upcoming 0.2.4-beta release
> updates release notes

- src/app/psat/psat.component.html
- src/app/psat/system-basics/system-basics.component.ts
> fix settings modal psat

- src/app/phast/sankey/sankey.component.ts
- src/app/phast/sankey/sankey.service.ts
> Issue 1036

- src/app/phast/losses/losses.component.html
- src/app/phast/losses/losses.component.ts
- src/assets/styles/two-panel.css
connects #995 
connects #1034 
connects #1031
> phast heat balance updates

- src/app/psat/psat-report/psat-report.component.ts
- src/app/psat/psat.component.ts
- src/app/psat/psat.service.ts
- src/app/psat/pump-fluid/pump-fluid.component.html
- src/app/psat/pump-fluid/pump-fluid.component.ts
- src/app/psat/system-basics/system-basics.component.ts
- src/app/settings/psat-settings/psat-settings.component.html
- src/app/settings/psat-settings/psat-settings.component.ts
- src/app/settings/settings.service.ts
- src/app/shared/models/settings.ts
connects #1041 
adds temperature settings options PSAT (F,C,K)
> add temp unit to psat options

- src/app/app.component.css
- src/app/calculator/calculator.component.html
- src/app/calculator/furnaces/furnaces.component.html
- src/app/calculator/furnaces/o2-enrichment/o2-enrichment-form/o2-enrichment-form.component.css
- src/app/calculator/furnaces/o2-enrichment/o2-enrichment-graph/o2-enrichment-graph.component.ts
- src/app/calculator/furnaces/o2-enrichment/o2-enrichment.component.html
- src/app/core/core.component.html
- src/app/phast/losses/losses-tabs/losses-tabs.component.html
connects #1037 
connects #1040 
connects #914 
- O2 enrichment calculator formatting and graph output updates.
- Spinner is working on auto-update
- PHAST badges Flue Gas & Charge Material asterisk change color to green when form is completed
> O2 Enrich. , Spinner, Flue Gas & Charge Material Badges.

- src/app/phast/losses/flue-gas-losses/flue-gas-losses.service.ts
connects #1072 
this will fix flue gas setup
> fix issue-1072

- src/app/settings/settings.service.ts
> Issue 1077

- src/app/phast/losses/losses.component.css
- src/app/phast/losses/losses.component.html
- src/app/phast/losses/losses.component.ts
connects #1070 
Warning modal before adding PHAST modifications
> Warning modal for PHAST adding modifications

- src/app/phast/losses/losses.component.html
- src/app/phast/losses/losses.component.ts
- src/app/shared/models/phast/phast.ts
> update dialog box

- package.json
fixes build issue
connect #1092
> update electron-updater to version ^2.18.2

- src/app/phast/losses/losses-help/gas-leakage-losses-help/gas-leakage-losses-help.component.html
- src/app/phast/phast-report/report-graphs/graphColors.ts
- src/app/phast/phast-report/report-graphs/phast-pie-chart/phast-pie-chart.component.ts
connect #1022 
connect #1035 
- New color for PHAST Pie chart.
- Output values next to pie chart legend 
- Verbiage change for specific density help
> fixes for pie-chart

- package.json
- src/app/assessment/assessment-settings/assessment-settings.component.css
- src/app/assessment/assessment-settings/assessment-settings.component.html
- src/app/dashboard/dashboard.component.html
- src/app/phast/phast-report/executive-summary/executive-summary.component.css
- src/app/phast/phast-report/executive-summary/executive-summary.component.html
- src/app/phast/phast-report/results-data/results-data.component.css
- src/app/phast/phast-report/results-data/results-data.component.html
- src/app/phast/phast-report/results-data/results-data.component.ts
- src/app/phast/system-basics/system-basics.component.html
- src/app/psat/psat-report/output-summary/output-summary.component.css
- src/app/psat/psat-report/output-summary/output-summary.component.html
- src/app/psat/psat-report/output-summary/output-summary.component.ts
- src/app/psat/psat.service.ts
- src/app/psat/system-basics/system-basics.component.html
- src/app/report-rollup/report-rollup.component.css
- src/app/report-rollup/report-rollup.component.html
- src/app/report-rollup/report-rollup.service.ts
- src/app/report-rollup/report-summary/phast-summary/phast-summary.component.html
- src/app/report-rollup/report-summary/phast-summary/phast-summary.component.ts
- src/app/report-rollup/report-summary/report-summary.component.css
- src/app/settings/application-settings/application-settings.component.html
- src/app/settings/application-settings/application-settings.component.ts
- src/app/shared/import-export/import-export.service.ts
> Issue 1023

- src/app/calculator/motors/percent-load-estimation/percent-load-estimation-form/percent-load-estimation-form.component.html
- src/app/calculator/motors/percent-load-estimation/percent-load-estimation-form/percent-load-estimation-form.component.ts
> Added fixes to motor load calculator.

- src/app/phast/losses/cooling-losses/cooling-losses.service.ts
- src/app/phast/losses/energy-input/energy-input-form/energy-input-form.component.html
connects #1107 
connects #1073 
- Default Values for Cooling Medium for EAF Furnace
- Link styling for Energy Input  =>  "Calculate using flow rate"
> Default Values for Cooling Medium

- src/app/calculator/motors/percent-load-estimation/percent-load-estimation-form/percent-load-estimation-form.component.ts
- src/app/calculator/motors/percent-load-estimation/percent-load-estimation.component.ts
- src/app/shared/percent-graph/percent-graph.component.ts
> Added changes to motor load calculator

- src/app/app.component.css
- src/app/calculator/furnaces/efficiency-improvement/efficiency-improvement-form/efficiency-improvement-form.component.html
- src/app/calculator/furnaces/efficiency-improvement/efficiency-improvement-form/efficiency-improvement-form.component.ts
- src/app/calculator/furnaces/efficiency-improvement/efficiency-improvement-help/efficiency-improvement-help.component.html
- src/app/phast/phast-banner/phast-banner.component.html
- src/app/psat/psat-banner/psat-banner.component.html
- src/app/psat/psat-tabs/psat-tabs.component.html
- src/app/sidebar/sidebar.component.html
connects #1038 
connects #1043 
- Renamed Dashboard to Home and connected links
- Italics style for PSAT "Novice View" and "Expert View"
-  Default  help on focus-out from input fields for Efficiency Improvement Calculator
> Rename Dashboard to Home, Default Help

- src/app/suiteDb/liquid-load-charge-material/liquid-load-charge-material.component.html
connects #989 
connects #1117 
connects #1118 
connects #1060
> Added fixes for issues 1117 and 1118

- src/app/suiteDb/atmosphere-specific-heat-material/atmosphere-specific-heat-material-help/atmosphere-specific-heat-material-help.component.html
- src/app/suiteDb/atmosphere-specific-heat-material/atmosphere-specific-heat-material.component.html
- src/app/suiteDb/atmosphere-specific-heat-material/atmosphere-specific-heat-material.component.ts
- src/app/suiteDb/gas-load-charge-material/gas-load-charge-material-help/gas-load-charge-material-help.component.html
- src/app/suiteDb/gas-load-charge-material/gas-load-charge-material.component.html
- src/app/suiteDb/gas-load-charge-material/gas-load-charge-material.component.ts
- src/app/suiteDb/liquid-load-charge-material/liquid-load-charge-material-help/liquid-load-charge-material-help.component.html
- src/app/suiteDb/liquid-load-charge-material/liquid-load-charge-material.component.html
- src/app/suiteDb/liquid-load-charge-material/liquid-load-charge-material.component.ts
- src/app/suiteDb/solid-load-charge-material/solid-load-charge-material-help/solid-load-charge-material-help.component.html
- src/app/suiteDb/solid-load-charge-material/solid-load-charge-material.component.html
- src/app/suiteDb/solid-load-charge-material/solid-load-charge-material.component.ts
- src/app/suiteDb/wall-losses-surface/wall-losses-surface-help/wall-losses-surface-help.component.html
- src/app/suiteDb/wall-losses-surface/wall-losses-surface.component.html
- src/app/suiteDb/wall-losses-surface/wall-losses-surface.component.ts
connects #1115 
Help field by field for PHAST modals loses
- Charge Materials
- Fixtures, Trays, etc.
- Wall
- Atmosphere
> Help Field by Field for PHAST  Loses Modals

- src/app/calculator/furnaces/efficiency-improvement/efficiency-improvement.component.ts
connects #1038 
Display default help field when Efficiency Improvement calculator is open.
> Default help field when opening calculator

- src/app/calculator/furnaces/efficiency-improvement/efficiency-improvement.component.ts
- src/app/calculator/furnaces/o2-enrichment/o2-enrichment-form/o2-enrichment-form.component.html
- src/app/calculator/furnaces/o2-enrichment/o2-enrichment-form/o2-enrichment-form.component.ts
Binds the enter button to the plot function in O2 Enrichment. Also fixes convertUnitsService from crashing on build.
> O2-Enter-Plot

- src/app/phast/sankey/sankey.service.ts
- src/app/psat/psat-sankey/psat-sankey.component.ts
connects #1135  
PSAT & PHAST Sankey verbiage updates
> PSAT & PHAST Sankey labels updates

- src/app/phast/phast-report/report-graphs/report-graphs.component.html
- src/app/phast/phast-report/report-sankey/report-sankey.component.html
- src/app/phast/phast.component.css
- src/app/phast/phast.component.html
- src/app/phast/phast.component.ts
- src/app/phast/sankey/sankey.component.ts
- src/app/psat/psat-sankey/psat-sankey.component.ts
- src/app/psat/psat.component.css
- src/app/psat/psat.component.html
- src/app/psat/psat.component.ts
- src/app/psat/psat.service.ts
> Added drop down selectors for PHAST Sankey and PSAT Sankey

- src/app/calculator/pumps/head-tool/head-tool.component.html
- src/app/calculator/pumps/head-tool/head-tool.component.ts
> fix head tool help

- src/app/phast/losses/energy-input-exhaust-gas-losses/energy-input-exhaust-gas.service.ts
- src/app/phast/losses/losses.component.html
connects #1130 
connects #1128
> New Default Values for Gas Energy Input & New Verbiage for PHAST Add Modification

- src/app/phast/losses/charge-material/liquid-charge-material-form/liquid-charge-material-form.component.html
- src/app/phast/losses/charge-material/liquid-charge-material-form/liquid-charge-material-form.component.ts
- src/app/suiteDb/atmosphere-specific-heat-material/atmosphere-specific-heat-material.component.ts
- src/app/suiteDb/flue-gas-material/flue-gas-material.component.ts
- src/app/suiteDb/gas-load-charge-material/gas-load-charge-material.component.ts
- src/app/suiteDb/liquid-load-charge-material/liquid-load-charge-material.component.html
- src/app/suiteDb/liquid-load-charge-material/liquid-load-charge-material.component.ts
- src/app/suiteDb/solid-liquid-flue-gas-material/solid-liquid-flue-gas-material.component.ts
- src/app/suiteDb/solid-load-charge-material/solid-load-charge-material.component.ts
connects #1118 
connects #989 
connects #1060
> Fixed various PHAST material form bugs

- src/app/phast/losses/atmosphere-losses/atmosphere-losses-form/atmosphere-losses-form.component.ts
- src/app/phast/losses/charge-material/gas-charge-material-form/gas-charge-material-form.component.ts
- src/app/phast/losses/charge-material/liquid-charge-material-form/liquid-charge-material-form.component.ts
- src/app/phast/losses/charge-material/solid-charge-material-form/solid-charge-material-form.component.ts
- src/app/phast/losses/fixture-losses/fixture-losses-form/fixture-losses-form.component.ts
- src/app/phast/losses/flue-gas-losses/flue-gas-losses-form-mass/flue-gas-losses-form-mass.component.ts
- src/app/phast/losses/flue-gas-losses/flue-gas-losses-form-volume/flue-gas-losses-form-volume.component.ts
- src/app/phast/losses/wall-losses/wall-losses-form/wall-losses-form.component.ts
connects #1030 
Rounding to four decimal places values coming from Database for PHAST losses
> Four Decimal places for PHAST losses

- src/app/psat/explore-opportunities/explore-opportunities-sankey/explore-opportunities-sankey.component.ts
> PSAT Sankey Explore Opportunities Verbiage Updates

- src/app/app.component.css
- src/app/phast/phast-banner/phast-banner.component.css
- src/app/phast/phast-banner/phast-banner.component.html
- src/app/phast/phast-banner/phast-banner.component.ts
- src/app/phast/phast-report/phast-report.component.css
- src/app/phast/phast-report/phast-report.component.html
- src/app/phast/phast.component.html
- src/app/phast/system-basics/system-basics.component.ts
> custom furnace display

- src/app/phast/convert-phast.service.ts
> fix issue-1166

- src/app/phast/losses/charge-material/liquid-charge-material-form/liquid-charge-material-form.component.html
- src/app/suiteDb/liquid-load-charge-material/liquid-load-charge-material.component.html
> Fixed Liquid charge material latent heat unit

- src/app/phast/phast-banner/phast-banner.component.html
- src/app/phast/phast-report/phast-report.component.html
- src/app/phast/system-basics/system-basics.component.ts
- src/app/report-rollup/report-rollup.component.css
> furnace type added

- src/app/version-modal/version-modal.component.css
- src/app/version-modal/version-modal.component.html
connects #1173 
release notes 0.2.5-beta
> updated release notes: 0.2.5-beta

- package.json
updates package.json project version number
> update version number to 0.2.5 beta

- src/app/phast/losses/operations/operations-form/operations-form.component.html
- src/app/phast/losses/operations/operations-form/operations-form.component.ts
- src/app/phast/operating-hours/operating-hours.component.ts
connects #1204 
- PHAST User Input validation for "Assessment =>  Operatoins"
> PHAST "Assessment => Operation" User Input Validation

- src/app/landing-screen/landing-screen.component.html
- src/app/phast/losses/energy-input-exhaust-gas-losses/energy-input-exhaust-gas-form/energy-input-exhaust-gas-form.component.html
- src/app/phast/losses/energy-input-exhaust-gas-losses/energy-input-exhaust-gas-form/energy-input-exhaust-gas-form.component.ts
- src/app/phast/losses/losses-help/cooling-losses-help/cooling-losses-help.component.html
- src/app/phast/losses/losses-help/gas-leakage-losses-help/gas-leakage-losses-help.component.html
- src/app/phast/losses/operations/operations-form/operations-form.component.ts
- src/app/phast/losses/operations/operations.component.ts
- src/app/phast/operating-hours/operating-hours.component.ts
connects #1188
connects #1179 
connects #1198 
connects #1186 
connects #1185 
- PHAST Energy Input validation.
- Operating Hours no h / year no decimal places.
-  New landing screen verbiage "Create Process Heating Assessment"
- PHAST Gas Leaked help text update.
- PHAST Cooling Losses help text update.
> PHAST - Warning - Energy Input

- src/app/calculator/calculator.component.html
- src/app/phast/losses/cooling-losses/gas-cooling-losses-form/gas-cooling-losses-form.component.html
- src/app/sidebar/sidebar.component.html
connects #1176 
connects #1121 
- Verbiage changed "Furnace => Process Heating Equipment"
- PHAST Cooling Losses input field new order
- New FontAwesome icon for sidebar "All Assets"
> Verbiage changed "Furnace => Process Heating Equipment"

- src/app/assessment/assessment-create/assessment-create.component.html
- src/app/calculator/furnaces/furnaces.component.html
- src/app/landing-screen/landing-screen.component.css
- src/app/landing-screen/landing-screen.component.html
- src/app/phast/help-panel/help-panel.component.html
- src/app/phast/operating-hours/operating-hours.component.html
- src/app/phast/phast-banner/phast-banner.component.html
- src/app/settings/phast-settings/phast-settings.component.html
connects #1212 
- PHAST verbiage updates Furnace => Process Heat
> PHAST Verbiage updates Furnace => Process Heat

- src/app/app.component.css
- src/app/calculator/utilities/combined-heat-power/combined-heat-power-form/combined-heat-power-form.component.html
- src/app/calculator/utilities/combined-heat-power/combined-heat-power-help/combined-heat-power-help.component.html
- src/app/calculator/utilities/combined-heat-power/combined-heat-power-results/combined-heat-power-results.component.html
- src/app/calculator/utilities/combined-heat-power/combined-heat-power.component.html
- src/app/calculator/utilities/unit-converter/unit-converter.component.css
- src/app/calculator/utilities/unit-converter/unit-converter.component.html
connects #1192 
- Styles Updates to mache resto of application for the Unit converter and CHP Calculator.
> Styles Updates for Unit converter and CHP Calculator

- src/app/calculator/utilities/combined-heat-power/combined-heat-power.component.html
- src/app/landing-screen/landing-screen.component.css
- src/app/landing-screen/landing-screen.component.html
- src/app/phast/help-panel/help-panel.component.html
connects #1212 
connects #1198
> Verbiage updates

- src/app/phast/losses/charge-material/charge-material.component.html
- src/app/phast/losses/charge-material/charge-material.component.ts
- src/app/phast/phast.service.ts
- src/app/shared/models/phast/losses/chargeMaterial.ts
connects #1232 
Adjusts solid / liquid / gas load charge materials page and the load charge material binding wrapper methods to calculate net heat loss, gross heat loss and endo / exothermic heat loss.
> Endothermic / Exothermic Charge Materials Losses

- src/app/app.component.css
- src/app/phast/losses/atmosphere-losses/atmosphere-losses-form/atmosphere-losses-form.component.ts
- src/app/phast/losses/charge-material/gas-charge-material-form/gas-charge-material-form.component.ts
- src/app/phast/losses/charge-material/liquid-charge-material-form/liquid-charge-material-form.component.ts
- src/app/phast/losses/charge-material/solid-charge-material-form/solid-charge-material-form.component.ts
- src/app/phast/losses/fixture-losses/fixture-losses-form/fixture-losses-form.component.ts
- src/app/phast/losses/losses-help/atmosphere-losses-help/atmosphere-losses-help.component.html
- src/app/phast/losses/losses-help/charge-material-help/charge-material-help.component.html
- src/app/phast/losses/losses-help/fixture-losses-help/fixture-losses-help.component.html
connects #1062 
- Warning message for user input for modifying values coming from database
- New green Color-Coded input fields for values coming from database
> New Green Color-Coded Input Fields for Values Coming from Database 

- src/app/settings/application-settings/application-settings.component.html
modified:   src/app/settings/application-settings/application-settings.component.html
> Adds a small fix to the spacing of radio btns in settings

- src/app/settings/application-settings/application-settings.component.html
modified:   src/app/settings/application-settings/application-settings.component.html
This makes sure that the radio buttons are not side by side, but instead bellow one another.
> Adds a block style to Units of Measure radio buttons

- src/app/phast/losses/energy-input-exhaust-gas-losses/energy-input-exhaust-gas-form/energy-input-exhaust-gas-form.component.html
- src/app/phast/losses/losses-help/energy-input-exhaust-gas-losses-help/energy-input-exhaust-gas-losses-help.component.html
- src/app/phast/phast.service.ts
connects #1187 
Change total heat for burners to MMBtu and GJ instead of Btu and kJ
> Total Heat for Burners - Energy Input Exhaust Gas

- src/app/phast/losses/gas-leakage-losses/gas-leakage-losses-form/gas-leakage-losses-form.component.html
- src/app/phast/losses/gas-leakage-losses/gas-leakage-losses-form/gas-leakage-losses-form.component.ts
- src/app/phast/losses/losses-help/gas-leakage-losses-help/gas-leakage-losses-help.component.html
connects #1133 
- Gas Losses Draft Pressure, user input validation and help text
> Gas Losses Draft Pressure, user input validation and help text

- src/app/calculator/calculator.component.html
- src/app/calculator/furnaces/furnaces.component.html
- src/app/calculator/motors/motors.component.html
- src/app/calculator/pumps/pumps.component.html
- src/app/calculator/utilities/utilities.component.html
connects #1262  
- Fixed routing for sidebar calculators
> Fixed Routing for Sidebar Calculators

- src/app/phast/phast-report/results-data/results-data.component.css
- src/app/phast/phast-report/results-data/results-data.component.html
connects #1247
- PHAST Report Results Underline and New Order in report
> PHAST Report Results Underline and New Order

- src/app/calculator/furnaces/o2-enrichment/o2-enrichment-help/o2-enrichment-help.component.html
- src/app/phast/losses/losses-help/atmosphere-losses-help/atmosphere-losses-help.component.html
- src/app/phast/losses/losses-help/charge-material-help/charge-material-help.component.html
- src/app/phast/losses/losses-help/fixture-losses-help/fixture-losses-help.component.html
connects #1062 
connects #1225 
- O2 Enrichment Help Updates
- PHAST Loses Help Updates
> O2 Enrichment Help Updates, PHAST Loses Help Updates

- src/app/psat/field-data/field-data.component.html
- src/app/psat/field-data/field-data.component.ts
- src/app/psat/help-panel/field-data-help/field-data-help.component.html
- src/app/psat/help-panel/field-data-help/field-data-help.component.ts
connects #1207 
- Field Data => Flow Rate input field and help text displaying superscript
> PSAT Field Data => Flow Rate units displaying superscripts

- src/app/report-rollup/phast-rollup/phast-rollup-furnace-summary/phast-rollup-furnace-summary.component.css
- src/app/report-rollup/phast-rollup/phast-rollup-furnace-summary/phast-rollup-furnace-summary.component.html
connects #1161
- Fixing layout of table  `Furnace Summary` in the roll-up report.
> PHAST roll-up report table layout

- src/app/about-page/about-page.component.html
- src/app/acknowledgments-page/acknowledgments-page.component.html
- src/app/assessment/assessment-settings/assessment-settings.component.html
- src/app/calculator/calculator.component.html
- src/app/dashboard/dashboard.component.css
- src/app/dashboard/dashboard.component.html
- src/app/phast/losses/losses.component.html
- src/app/phast/losses/losses.component.ts
connects #1137 
connects #1260
> Issue 1137

- src/app/assessment/folder-contact-info/folder-contact-info.component.ts
- src/app/dashboard/dashboard.component.ts
- src/app/shared/import-export/import-export.component.ts
> fix export/import dir settings

- src/app/report-rollup/phast-rollup/phast-rollup-furnace-summary/phast-rollup-furnace-summary.component.html
connects #1161 
- New table layout for PHAST roll-up report.
> Table Layout Adjustment

- src/app/phast/metered-energy/metered-electricity/metered-electricity-help/metered-electricity-help.component.html
- src/app/phast/metered-energy/metered-fuel/metered-fuel-help/metered-fuel-help.component.html
connects #1284 
- New default help text for Pre-Assesment Calculator
> New Help Text for Pre-Assessment Calculator

- src/app/phast/losses/losses-result-panel/losses-result-panel.component.ts
- src/app/phast/phast.component.ts
- src/app/settings/phast-settings/phast-settings.component.css
- src/app/settings/phast-settings/phast-settings.component.html
- src/app/settings/phast-settings/phast-settings.component.ts
connects #1288 
some additional bug fixes
> fix furnace type and back

- src/app/app.component.css
- src/app/psat/explore-opportunities/explore-opportunities-results/explore-opportunities-results.component.html
- src/app/psat/psat-report/output-summary/output-summary.component.html
- src/app/shared/percent-graph/percent-graph.component.css
- src/app/shared/percent-graph/percent-graph.component.html
- src/app/shared/percent-graph/percent-graph.component.ts
Fixed the gauge chart sizing and download button in PSAT report tables.
> Fixed PSAT gauge formatting across multiple components

- src/app/phast/phast-report/phast-report.component.html
- src/app/phast/phast-report/report-graphs/phast-bar-chart/phast-bar-chart.component.ts
> Fixed PHAST Input data print issue

- src/app/calculator/furnaces/pre-assessment/pre-assessment.component.css
- src/app/calculator/furnaces/pre-assessment/pre-assessment.component.html
- src/app/phast/metered-energy/metered-electricity/metered-electricity-help/metered-electricity-help.component.html
- src/app/phast/metered-energy/metered-fuel/metered-fuel-help/metered-fuel-help.component.html
connects #1284 
- Pre-Assessment Help Update
> Pre-Assessment Help Update

- package.json
- src/app/version-modal/version-modal.component.html
> release notes and version num

- src/app/app.component.css
- src/app/calculator/furnaces/efficiency-improvement/efficiency-improvement.component.html
- src/app/calculator/furnaces/energy-equivalency/energy-equivalency.component.html
- src/app/calculator/furnaces/energy-use/energy-use.component.html
- src/app/calculator/furnaces/o2-enrichment/o2-enrichment.component.html
- src/app/calculator/furnaces/pre-assessment/pre-assessment.component.html
- src/app/calculator/motors/motor-performance/motor-performance.component.html
- src/app/calculator/motors/nema-energy-efficiency/nema-energy-efficiency.component.html
- src/app/calculator/motors/percent-load-estimation/percent-load-estimation.component.html
- src/app/calculator/pumps/achievable-efficiency/achievable-efficiency.component.html
- src/app/calculator/pumps/head-tool/head-tool.component.html
- src/app/calculator/pumps/pump-curve/pump-curve.component.html
- src/app/calculator/pumps/specific-speed/specific-speed.component.html
- src/app/calculator/pumps/system-curve/system-curve.component.html
> icons in calcs

- src/app/phast/phast-report/energy-used/energy-used.component.html
- src/app/phast/system-basics/system-basics.component.css
- src/app/phast/system-basics/system-basics.component.html
- src/app/shared/models/phast/phast.ts
> add equiment notes

- src/app/phast/system-basics/system-basics.component.html
- src/app/phast/system-basics/system-basics.component.ts
- src/app/settings/application-settings/application-settings.component.html
- src/app/settings/application-settings/application-settings.component.ts
> fix saving phast result unit

- src/app/phast/losses/losses-result-panel/losses-result-panel.component.html
- src/app/phast/losses/losses-result-panel/losses-result-panel.component.ts
- src/app/phast/losses/losses.component.html
- src/app/phast/losses/losses.component.ts
- src/app/phast/losses/notes/notes.component.html
- src/app/phast/losses/notes/notes.component.ts
- src/app/psat/help-panel/help-panel.component.html
- src/app/psat/help-panel/help-panel.component.ts
- src/app/psat/modify-conditions/modify-conditions-notes/modify-conditions-notes.component.html
- src/app/psat/modify-conditions/modify-conditions-notes/modify-conditions-notes.component.ts
- src/app/psat/modify-conditions/modify-conditions.component.html
> saving notes

- src/app/calculator/compressed-air/bag-method/bag-method-form/bag-method-form.component.html
- src/app/calculator/compressed-air/flow-factor/flow-factor-form/flow-factor-form.component.html
- src/app/calculator/compressed-air/pneumatic-air/pneumatic-air-form/pneumatic-air-form.component.html
- src/app/calculator/furnaces/efficiency-improvement/efficiency-improvement-form/efficiency-improvement-form.component.html
- src/app/calculator/furnaces/energy-equivalency/energy-equivalency-form/energy-equivalency-form.component.html
- src/app/calculator/furnaces/energy-use/energy-use.component.html
- src/app/calculator/furnaces/o2-enrichment/o2-enrichment-form/o2-enrichment-form.component.html
- src/app/calculator/motors/percent-load-estimation/percent-load-estimation-form/percent-load-estimation-form.component.html
- src/app/calculator/pumps/system-curve/system-curve-form/system-curve-form.component.html
connects #1332 
- Bolded results and output values for calculators
> Bolded Results for All Calculators

- package.json
- src/app/phast/phast-report/report-sankey/report-sankey.component.css
- src/app/phast/phast-report/report-sankey/report-sankey.component.html
- src/app/phast/phast-report/report-sankey/report-sankey.component.ts
> Issue 1229

- package.json
Updates the tools-suite to 0.2.16, which updated NAN to 2.9.2 - should fix the CI issues we had
> update tools-suite version number

- src/app/psat/explore-opportunities/explore-opportunities-sankey/explore-opportunities-sankey.component.ts
- src/app/psat/psat-sankey/psat-sankey.component.ts
> Issue 1233

- src/app/phast/phast-report/report-graphs/phast-pie-chart/phast-pie-chart.component.ts
- src/app/phast/phast-report/report-graphs/report-graphs-print/report-graphs-print.component.css
- src/app/psat/psat-sankey/psat-sankey.component.ts
> Ordered pie chart legends and fit them to print.

- src/app/calculator/compressed-air/bag-method/bag-method.component.html
- src/app/calculator/compressed-air/compressed-air.component.html
- src/app/landing-screen/landing-screen.component.html
- src/app/phast/phast.component.html
- src/app/psat/psat-tabs/psat-tabs.component.html
- src/app/sidebar/assessment-item/assessment-item.component.html
- src/app/version-modal/version-modal.component.html
connects #1309 
connects #1345 
connects #1344 
connects #1326 
- Update homepage and sidebar icons
- Changed name of compress air calculator "Bag Method" to "Leak Loss Estimator - Bag Method"
- Changed label "Modify conditions" in PSAT & PHAST to "Modify All Conditions"
> Multiple fixes for PSAT and PHAST

- src/app/calculator/motors/motor-performance/motor-performance-form/motor-performance-form.component.html
- src/app/calculator/motors/motor-performance/motor-performance-form/motor-performance-form.component.ts
- src/app/psat/help-panel/motor-help/motor-help.component.html
- src/app/psat/motor/motor.component.ts
- src/app/psat/psat.service.ts
connects #1351 
- Updates Standalone calculator Motor Performance => RPM min/max values based on efficency class.
- Updates PSAT Motor => RPM min/max values based on efficency class.
- Updates PSAT Motor => RPM Help field
> PSAT Motor RPM Values Update

- src/app/calculator/compressed-air/compressed-air.component.html
- src/app/calculator/compressed-air/compressed-air.module.ts
- src/app/calculator/compressed-air/pipe-sizing/pipe-sizing-form/pipe-sizing-form.component.html
- src/app/calculator/compressed-air/pipe-sizing/pipe-sizing-form/pipe-sizing-form.component.spec.ts
- src/app/calculator/compressed-air/pipe-sizing/pipe-sizing-form/pipe-sizing-form.component.ts
- src/app/calculator/compressed-air/pipe-sizing/pipe-sizing.component.html
- src/app/calculator/compressed-air/pipe-sizing/pipe-sizing.component.spec.ts
- src/app/calculator/compressed-air/pipe-sizing/pipe-sizing.component.ts
connects #1150 
- New calculator in Compressed Air calculators Pipe Sizing Calculator
> Compressed Air Pipe Sizing Calculator

- src/app/phast/phast-report/phast-input-summary/charge-material-summary/charge-material-summary.component.html
- src/app/phast/phast-report/results-data/results-data.component.html
connects #1104 
Need @koay9f  to sign off on the structure and order of the tables.
> Restructured PHAST Input data

- src/app/calculator/compressed-air/compressed-air.component.html
- src/app/calculator/compressed-air/compressed-air.module.ts
- src/app/calculator/compressed-air/flow-factor/flow-factor-form/flow-factor-form.component.ts
- src/app/calculator/compressed-air/operating-cost/operating-cost-form/operating-cost-form.component.html
- src/app/calculator/compressed-air/operating-cost/operating-cost-form/operating-cost-form.component.spec.ts
- src/app/calculator/compressed-air/operating-cost/operating-cost-form/operating-cost-form.component.ts
- src/app/calculator/compressed-air/operating-cost/operating-cost.component.html
- src/app/calculator/compressed-air/operating-cost/operating-cost.component.spec.ts
- src/app/calculator/compressed-air/operating-cost/operating-cost.component.ts
connects #1147 
- New Compressed Air Calculator / Operation Cost Calculator
> New Calculator Operation Cost

- src/app/calculator/furnaces/energy-use/energy-use-form/energy-use-form.component.ts
- src/app/phast/losses/atmosphere-losses/atmosphere-losses.component.html
- src/app/phast/losses/auxiliary-power-losses/auxiliary-power-losses.component.html
- src/app/phast/losses/charge-material/charge-material.component.html
- src/app/phast/losses/cooling-losses/cooling-losses.component.html
- src/app/phast/losses/energy-input-exhaust-gas-losses/energy-input-exhaust-gas-losses.component.html
- src/app/phast/losses/energy-input/energy-input.component.html
- src/app/phast/losses/exhaust-gas/exhaust-gas.component.html
- src/app/phast/losses/extended-surface-losses/extended-surface-losses.component.html
- src/app/phast/losses/fixture-losses/fixture-losses.component.html
- src/app/phast/losses/flue-gas-losses/flue-gas-losses.component.html
- src/app/phast/losses/gas-leakage-losses/gas-leakage-losses.component.html
- src/app/phast/losses/heat-system-efficiency/heat-system-efficiency.component.html
- src/app/phast/losses/opening-losses/opening-losses-form/opening-losses-form.component.html
- src/app/phast/losses/opening-losses/opening-losses-form/opening-losses-form.component.ts
- src/app/phast/losses/opening-losses/opening-losses.component.html
- src/app/phast/losses/slag/slag.component.html
- src/app/phast/losses/wall-losses/wall-losses.component.html
connects #1354 
connects #1370
> Phast bugs

- src/app/calculator/compressed-air/compressed-air.component.html
- src/app/calculator/compressed-air/compressed-air.module.ts
- src/app/calculator/compressed-air/system-capacity/system-capacity-form/system-capacity-form.component.html
- src/app/calculator/compressed-air/system-capacity/system-capacity-form/system-capacity-form.component.spec.ts
- src/app/calculator/compressed-air/system-capacity/system-capacity-form/system-capacity-form.component.ts
- src/app/calculator/compressed-air/system-capacity/system-capacity.component.html
- src/app/calculator/compressed-air/system-capacity/system-capacity.component.spec.ts
- src/app/calculator/compressed-air/system-capacity/system-capacity.component.ts
connects #1148 
- New Compressed Air Calculator => Air System Capacity
> Compressed Air System Capacity Calculator

- src/app/phast/convert-phast.service.ts
- src/app/phast/designed-energy/designed-energy-electricity/designed-energy-electricity-results/designed-energy-electricity-results.component.css
- src/app/phast/designed-energy/designed-energy-electricity/designed-energy-electricity-results/designed-energy-electricity-results.component.html
- src/app/phast/designed-energy/designed-energy-electricity/designed-energy-electricity-results/designed-energy-electricity-results.component.spec.ts
- src/app/phast/designed-energy/designed-energy-electricity/designed-energy-electricity-results/designed-energy-electricity-results.component.ts
- src/app/phast/designed-energy/designed-energy-electricity/designed-energy-electricity.component.html
- src/app/phast/designed-energy/designed-energy-electricity/designed-energy-electricity.component.ts
- src/app/phast/designed-energy/designed-energy-results/designed-energy-results.component.css
- src/app/phast/designed-energy/designed-energy-results/designed-energy-results.component.html
- src/app/phast/designed-energy/designed-energy-results/designed-energy-results.component.ts
- src/app/phast/designed-energy/designed-energy.module.ts
- src/app/phast/designed-energy/designed-energy.service.ts
- src/app/phast/metered-energy/metered-electricity/metered-electricity-results/metered-electricity-results.component.css
- src/app/phast/metered-energy/metered-electricity/metered-electricity-results/metered-electricity-results.component.html
- src/app/phast/metered-energy/metered-electricity/metered-electricity-results/metered-electricity-results.component.spec.ts
- src/app/phast/metered-energy/metered-electricity/metered-electricity-results/metered-electricity-results.component.ts
- src/app/phast/metered-energy/metered-electricity/metered-electricity.component.html
- src/app/phast/metered-energy/metered-electricity/metered-electricity.component.ts
- src/app/phast/metered-energy/metered-energy-results/metered-energy-results.component.css
- src/app/phast/metered-energy/metered-energy-results/metered-energy-results.component.html
- src/app/phast/metered-energy/metered-energy-results/metered-energy-results.component.ts
- src/app/phast/metered-energy/metered-energy.module.ts
- src/app/phast/metered-energy/metered-energy.service.ts
- src/app/phast/metered-energy/metered-fuel/metered-fuel-form/metered-fuel-form.component.html
- src/app/phast/metered-energy/metered-fuel/metered-fuel-form/metered-fuel-form.component.ts
- src/app/phast/phast-report/energy-used/energy-used.component.html
- src/app/phast/phast-report/energy-used/energy-used.component.ts
> Issue 1189

- src/app/phast/metered-energy/metered-energy.service.ts
> fix metered energy calcs

- src/app/calculator/furnaces/pre-assessment/pre-assessment-graph/pre-assessment-graph.component.css
- src/app/calculator/furnaces/pre-assessment/pre-assessment-graph/pre-assessment-graph.component.html
- src/app/calculator/furnaces/pre-assessment/pre-assessment-graph/pre-assessment-graph.component.ts
- src/app/calculator/furnaces/pre-assessment/pre-assessment.component.css
- src/app/calculator/furnaces/pre-assessment/pre-assessment.component.html
- src/app/calculator/furnaces/pre-assessment/pre-assessment.component.ts
- src/app/dashboard/dashboard.component.html
connects #1381 
updates styles for pre assessment
> Issue 1381

- src/app/phast/phast-results.service.ts
- src/app/phast/phast.service.ts
connects #1379 
fix non eaf calculations
> fix issue 1379

- src/app/assessment/assessment-create/assessment-create.component.html
- src/app/assessment/assessment-create/assessment-create.component.ts
- src/app/assessment/assessment-menu/create-folder/create-folder.component.html
> fix submit

- src/app/phast/losses/wall-losses/wall-losses.service.ts
- src/app/phast/phast.service.ts
> fix issue 1403

- src/app/phast/phast.service.ts
connect #1406 
- Takes water content into account when dealing with endothermic solid load charge materials
> Water content heat reaction

- src/app/calculator/furnaces/pre-assessment/pre-assessment-graph/pre-assessment-graph.component.html
- src/app/dashboard/dashboard.component.ts
- src/app/report-rollup/phast-rollup/phast-rollup.component.ts
- src/app/report-rollup/report-rollup.component.ts
> Issue 1408

- src/app/report-rollup/rollup-bar-chart/rollup-bar-chart.component.ts
- src/app/report-rollup/rollup-pie-chart/rollup-pie-chart.component.ts
> Rollup bar chart now initializing

- src/app/calculator/furnaces/pre-assessment/pre-assessment-form/pre-assessment-designed/pre-assessment-designed.component.html
- src/app/calculator/furnaces/pre-assessment/pre-assessment-form/pre-assessment-designed/pre-assessment-designed.component.ts
- src/app/calculator/furnaces/pre-assessment/pre-assessment-form/pre-assessment-metered/pre-assessment-metered.component.html
- src/app/calculator/furnaces/pre-assessment/pre-assessment.service.ts
> Issue 1380

- src/app/phast/sankey/sankey.component.html
- src/app/phast/sankey/sankey.component.ts
- src/app/phast/sankey/sankey.service.ts
#connects #1410 
This does not address the bar chart issue. This will be a separate issue included in a graph generation refactor.
> Issue 1410

- src/app/app.component.css
- src/app/assessment/assessment-create/assessment-create.component.css
- src/app/assessment/assessment-create/assessment-create.component.html
- src/app/assessment/assessment-create/assessment-create.component.ts
- src/app/assessment/assessment-dashboard/assessment-dashboard.component.css
- src/app/assessment/assessment-dashboard/assessment-dashboard.component.html
- src/app/assessment/assessment-dashboard/assessment-dashboard.component.ts
- src/app/assessment/assessment-grid-view/assessment-grid-view.component.ts
- src/app/assessment/assessment-menu/create-folder/create-folder.component.css
- src/app/assessment/assessment-menu/create-folder/create-folder.component.html
- src/app/assessment/assessment-settings/assessment-settings.component.css
- src/app/assessment/assessment-settings/assessment-settings.component.html
- src/app/assessment/assessment-settings/assessment-settings.component.ts
- src/app/assessment/folder-summary/folder-summary.component.css
- src/app/assessment/folder-summary/folder-summary.component.html
- src/app/assessment/folder-summary/folder-summary.component.ts
- src/app/dashboard/dashboard.component.css
- src/app/dashboard/dashboard.component.html
- src/app/phast/operating-hours/operating-hours.component.html
- src/app/phast/operating-hours/operating-hours.component.ts
- src/app/settings/application-settings/application-settings.component.css
- src/app/settings/application-settings/application-settings.component.html
- src/app/settings/psat-settings/psat-settings.component.css
- src/app/settings/settings.service.ts
- src/app/shared/import-export/import-export.component.css
- src/app/shared/models/settings.ts
- src/app/shared/update-data.service.ts
connects #1438 
tweaks styling to various areas in dashboard
> Issue 1438

- src/app/phast/phast-report/report-graphs/graphColors.ts
- src/app/phast/phast-report/report-graphs/phast-pie-chart/phast-pie-chart.component.css
- src/app/phast/phast-report/report-graphs/phast-pie-chart/phast-pie-chart.component.ts
- src/app/phast/phast-report/report-graphs/report-graphs-print/report-graphs-print.component.css
- src/app/phast/phast-report/report-graphs/report-graphs-print/report-graphs-print.component.html
- src/app/phast/phast-report/report-graphs/report-graphs-print/report-graphs-print.component.ts
- src/app/phast/phast-report/report-graphs/report-graphs.component.html
- src/app/phast/phast-report/report-graphs/report-graphs.component.ts
connects #1443 
Only applies to PHAST report charts. The code is reusable, but a new issue should be made to make this code available to all components using a pie chart.
> D3 pie charts

- src/app/phast/phast-tabs/phast-tabs.component.html
- src/app/phast/tabs.ts
> remove tabs

- src/app/phast/explore-phast-opportunities/explore-phast-opportunities.component.html
> scrolling working for explore help

- src/app/calculator/furnaces/o2-enrichment/o2-enrichment.component.ts
- src/app/calculator/furnaces/pre-assessment/pre-assessment.component.css
- src/app/calculator/furnaces/pre-assessment/pre-assessment.component.html
- src/app/calculator/furnaces/pre-assessment/pre-assessment.component.ts
- src/app/calculator/pumps/system-curve/system-curve.component.ts
- src/app/phast/phast-banner/phast-banner.component.html
- src/app/phast/phast-banner/phast-banner.component.ts
- src/app/psat/psat-banner/psat-banner.component.html
- src/app/psat/psat-banner/psat-banner.component.ts
- src/app/psat/psat.component.html
> calculators always accessable in assessment

- src/app/assessment/assessment-create/assessment-create.component.ts
- src/app/shared/update-data.service.ts
> update operating costs

- src/app/phast/designed-energy/designed-energy-fuel/designed-energy-fuel.component.ts
- src/app/phast/designed-energy/designed-energy-results/designed-energy-results.component.html
- src/app/phast/designed-energy/designed-energy-results/designed-energy-results.component.ts
- src/app/phast/metered-energy/metered-energy-results/metered-energy-results.component.html
- src/app/phast/metered-energy/metered-energy-results/metered-energy-results.component.ts
> Issue 1392

- src/app/settings/phast-settings/phast-settings.component.html
- src/app/settings/phast-settings/phast-settings.component.ts
> remove furnace type for fuel

- src/app/phast/phast.component.html
- src/app/phast/system-basics/system-basics.component.css
- src/app/phast/system-basics/system-basics.component.html
- src/app/settings/phast-settings/phast-settings.component.css
> move operating condition notes

- src/app/phast/sankey/sankey.component.ts
- src/app/phast/sankey/sankey.service.ts
> Fixed sankey text position

- src/app/phast/losses/gas-leakage-losses/gas-leakage-losses.service.ts
- src/app/phast/losses/losses-help/atmosphere-losses-help/atmosphere-losses-help.component.html
connects #1391 
connects #1390
> PHAST text fixes

- src/app/phast/losses/losses.service.ts
- src/app/phast/tabs.ts
> update phast tab order

- src/app/phast/phast-report/report-graphs/report-graphs.component.html
- src/app/report-rollup/phast-rollup/phast-rollup-furnace-summary/phast-rollup-furnace-summary.component.ts
- src/app/report-rollup/phast-rollup/phast-rollup-graphs/phast-rollup-graphs.component.css
- src/app/report-rollup/phast-rollup/phast-rollup-graphs/phast-rollup-graphs.component.html
- src/app/report-rollup/phast-rollup/phast-rollup-graphs/phast-rollup-graphs.component.ts
- src/app/report-rollup/phast-rollup/phast-rollup.component.ts
- src/app/report-rollup/psat-rollup/psat-rollup-graphs/psat-rollup-graphs.component.css
- src/app/report-rollup/psat-rollup/psat-rollup-graphs/psat-rollup-graphs.component.html
- src/app/report-rollup/psat-rollup/psat-rollup-graphs/psat-rollup-graphs.component.ts
- src/app/report-rollup/psat-rollup/psat-rollup-pump-summary/psat-rollup-pump-summary.component.html
- src/app/report-rollup/psat-rollup/psat-rollup-pump-summary/psat-rollup-pump-summary.component.ts
- src/app/report-rollup/rollup-pie-chart/rollup-pie-chart.component.html
- src/app/report-rollup/rollup-pie-chart/rollup-pie-chart.component.ts
- src/app/shared/pie-chart/pie-chart.component.ts
> Updated rollup pie charts

- src/app/phast/phast-report/phast-report.component.css
- src/app/phast/phast-report/phast-report.component.html
- src/app/phast/phast-report/phast-report.component.ts
- src/app/phast/phast-report/phast-report.module.ts
- src/app/shared/animated-checkmark/animated-checkmark.component.css
- src/app/shared/animated-checkmark/animated-checkmark.component.html
- src/app/shared/animated-checkmark/animated-checkmark.component.spec.ts
- src/app/shared/animated-checkmark/animated-checkmark.component.ts
- src/app/shared/shared.module.ts
> Issue 1427

- src/app/report-rollup/phast-rollup/phast-rollup-graphs/phast-rollup-graphs.component.html
> Fixed energy use graph buttons

- src/app/phast/explore-phast-opportunities/explore-phast-opportunities-form/explore-charge-materials-form/explore-charge-materials-form.component.html
- src/app/phast/explore-phast-opportunities/explore-phast-opportunities-form/explore-fixtures-form/explore-fixtures-form.component.html
- src/app/phast/explore-phast-opportunities/explore-phast-opportunities-form/explore-flue-gas-form/explore-flue-gas-form.component.html
- src/app/phast/explore-phast-opportunities/explore-phast-opportunities-form/explore-leakage-form/explore-leakage-form.component.html
- src/app/phast/explore-phast-opportunities/explore-phast-opportunities-form/explore-opening-form/explore-opening-form.component.html
- src/app/phast/explore-phast-opportunities/explore-phast-opportunities-form/explore-operations-form/explore-operations-form.component.html
- src/app/phast/explore-phast-opportunities/explore-phast-opportunities-form/explore-system-efficiency-form/explore-system-efficiency-form.component.html
- src/app/phast/explore-phast-opportunities/explore-phast-opportunities-form/explore-wall-form/explore-wall-form.component.html
connects #1511 
- see title of the PR
> small quick fixes to explore opportunities verbiage

- src/app/phast/phast-report/executive-summary/executive-summary.component.css
- src/app/phast/phast-report/executive-summary/executive-summary.component.html
> Exec summary lines bolded

- src/app/report-rollup/phast-rollup/phast-rollup-graphs/phast-rollup-graphs.component.html
- src/app/report-rollup/phast-rollup/phast-rollup-graphs/phast-rollup-graphs.component.ts
> Fixed the button verbiage in the rollup

- src/app/landing-screen/landing-screen.component.html
- src/app/phast/losses/atmosphere-losses/atmosphere-losses.component.html
- src/app/phast/losses/auxiliary-power-losses/auxiliary-power-losses.component.html
- src/app/phast/losses/charge-material/charge-material.component.html
- src/app/phast/losses/charge-material/charge-material.component.ts
- src/app/phast/losses/cooling-losses/cooling-losses.component.html
- src/app/phast/losses/energy-input-exhaust-gas-losses/energy-input-exhaust-gas-losses.component.html
- src/app/phast/losses/energy-input/energy-input.component.html
- src/app/phast/losses/exhaust-gas/exhaust-gas.component.html
- src/app/phast/losses/extended-surface-losses/extended-surface-losses.component.html
- src/app/phast/losses/extended-surface-losses/extended-surface-losses.component.ts
- src/app/phast/losses/fixture-losses/fixture-losses.component.html
- src/app/phast/losses/fixture-losses/fixture-losses.component.ts
- src/app/phast/losses/flue-gas-losses/flue-gas-losses.component.html
- src/app/phast/losses/gas-leakage-losses/gas-leakage-losses.component.html
- src/app/phast/losses/gas-leakage-losses/gas-leakage-losses.component.ts
- src/app/phast/losses/heat-system-efficiency/heat-system-efficiency.component.html
- src/app/phast/losses/losses.component.ts
- src/app/phast/losses/opening-losses/opening-losses.component.html
- src/app/phast/losses/opening-losses/opening-losses.component.ts
- src/app/phast/losses/other-losses/other-losses.component.html
- src/app/phast/losses/other-losses/other-losses.component.ts
- src/app/phast/losses/slag/slag.component.html
- src/app/phast/losses/wall-losses/wall-losses.component.html
- src/app/phast/losses/wall-losses/wall-losses.component.ts
- src/app/suiteDb/flue-gas-material/flue-gas-material.component.html
- src/assets/styles/utilities.css
connects #1329 
connects #1439
> Miscellaneous Fixes

- src/app/phast/phast-report/phast-report.component.html
- src/app/phast/phast-report/phast-report.component.ts
- src/app/phast/phast-report/report-graphs/report-graphs-print/report-graphs-print.component.css
- src/app/phast/phast-report/report-graphs/report-graphs-print/report-graphs-print.component.html
- src/app/phast/phast-report/report-graphs/report-graphs-print/report-graphs-print.component.ts
- src/app/phast/phast-report/report-graphs/report-graphs.component.html
- src/app/phast/phast-report/report-graphs/report-graphs.component.ts
Resolved a bug preventing user from only printing sankey.
Removed the option to exclude facility info from print.
> Fixed sankey print selection

- src/app/calculator/furnaces/pre-assessment/pre-assessment-graph/pre-assessment-graph.component.ts
- src/app/calculator/furnaces/pre-assessment/pre-assessment.service.ts
- src/app/core/core.component.ts
- src/app/report-rollup/phast-rollup/phast-rollup-pre-assessment-table/phast-rollup-pre-assessment-table.component.css
- src/app/report-rollup/phast-rollup/phast-rollup-pre-assessment-table/phast-rollup-pre-assessment-table.component.html
- src/app/report-rollup/phast-rollup/phast-rollup-pre-assessment-table/phast-rollup-pre-assessment-table.component.ts
- src/app/report-rollup/phast-rollup/phast-rollup.component.html
- src/app/report-rollup/rollup-pie-chart/rollup-pie-chart.component.ts
> Issue 1503

- src/app/phast/modification-list/modification-list.component.css
> fixed menu popup

- src/app/landing-screen/measur/measur.component.html
> Fixed spelling of MEASUR

- src/app/phast/phast-report/report-graphs/report-graphs-print/report-graphs-print.component.html
- src/app/report-rollup/phast-rollup/phast-rollup.component.html
> issue 1541

- src/app/assessment/assessment-dashboard/assessment-dashboard.component.html
- src/app/assessment/folder-contact-info/folder-contact-info.component.css
- src/app/assessment/folder-contact-info/folder-contact-info.component.html
- src/app/assessment/folder-contact-info/folder-contact-info.component.ts
- src/app/assessment/folder-summary/folder-summary.component.html
- src/app/assessment/folder-summary/folder-summary.component.ts
> Moved facility info

- src/app/phast/phast-report/phast-report.component.ts
- src/app/psat/psat-report/psat-report.component.css
- src/app/psat/psat-report/psat-report.component.html
- src/app/psat/psat-report/psat-report.component.ts
- src/app/psat/psat-report/psat-report.service.spec.ts
- src/app/psat/psat-report/psat-report.service.ts
- src/app/psat/psat.module.ts
- src/app/report-rollup/report-rollup.component.html
- src/app/report-rollup/rollup-bar-chart/rollup-bar-chart.component.ts
- src/app/shared/facility-info-summary/facility-info-summary.component.ts
> Updated print options for PSAT

- src/app/assessment/folder-summary/folder-summary.component.html
- src/app/phast/phast-banner/phast-banner.component.html
- src/app/phast/phast-report/phast-report.component.html
- src/app/settings/phast-settings/phast-settings.component.html
- src/app/settings/psat-settings/psat-settings.component.ts
- src/app/shared/convert-units/definitions/temperature.ts
- src/app/shared/import-export/import-export.component.html
- src/app/shared/import-export/import-export.service.ts
- src/app/sidebar/sidebar.component.html
connects #1566 
connects #1568 
connects #1569 
connects #1572 
connects #1574 
connects #1575 
- New format for exported json data: ExportedData_[timestamp].json
- typo fixes
- Default furnace name string changes in phast banner
> Various quick fixes typos

- src/app/psat/pump-fluid/pump-fluid.component.ts
- src/app/shared/convert-units/definitions/temperature.ts
connects #1575 
- Comments out kelvin in the unit converter library and comment out usages of checking for kelvin units
> removes kelvin completely

- src/app/assessment/folder-contact-info/folder-contact-info.component.html
> Added assessment contact

- src/app/phast/phast-report/report-graphs/report-graphs-print/report-graphs-print.component.html
- src/app/phast/phast-report/report-graphs/report-graphs.component.html
- src/app/phast/phast-report/report-graphs/report-graphs.component.ts
- src/app/shared/pie-chart/pie-chart.component.ts
> Issue 1564

- src/app/phast/phast-banner/phast-banner.component.html
> Changed PH System Setup to System Setup

- src/app/assessment/folder-contact-info/folder-contact-info.component.html
> Moved collapsed facility info to one line

- src/app/assessment/folder-contact-info/folder-contact-info.component.html
- src/app/assessment/folder-contact-info/folder-contact-info.component.ts
- src/app/settings/facility-info/facility-info.component.ts
- src/app/shared/facility-info-summary/facility-info-summary.component.html
- src/app/shared/facility-info-summary/facility-info-summary.component.ts
- src/app/shared/pipes/phone.pipe.spec.ts
- src/app/shared/pipes/phone.pipe.ts
- src/app/shared/shared.module.ts
> Issue 1563

- src/app/psat/psat-banner/psat-banner.component.html
> Fixed System Setup tab text

- src/app/assessment/assessment-dashboard/assessment-dashboard.component.css
- src/app/assessment/assessment-dashboard/assessment-dashboard.component.html
- src/app/assessment/assessment-grid-view/assessment-card/assessment-card.component.html
- src/app/assessment/assessment-grid-view/directory-card/directory-card.component.html
- src/app/assessment/assessment-grid-view/pre-assessment-card/pre-assessment-card.component.html
- src/app/assessment/assessment-list-view/assessment-list-view.component.css
- src/app/assessment/assessment-menu/assessment-menu.component.css
- src/app/assessment/assessment-menu/assessment-menu.component.html
- src/app/assessment/folder-contact-info/folder-contact-info.component.css
- src/app/assessment/folder-contact-info/folder-contact-info.component.html
- src/app/assessment/folder-summary/folder-summary.component.css
- src/app/assessment/folder-summary/folder-summary.component.html
- src/app/core/core.service.ts
- src/assets/styles/utilities.css
style changes to assessment dashboard, grid and list views
> style updates assessment dashboard

- src/app/acknowledgments-page/acknowledgments-page.component.html
- src/app/app.component.css
- src/app/assessment/assessment-settings/assessment-settings.component.css
- src/app/assessment/folder-contact-info/folder-contact-info.component.css
- src/app/assessment/folder-contact-info/folder-contact-info.component.html
- src/app/calculator/calculator.component.css
- src/app/calculator/calculator.component.html
- src/app/calculator/compressed-air/compressed-air.component.css
- src/app/calculator/compressed-air/compressed-air.component.html
- src/app/calculator/furnaces/furnaces.component.css
- src/app/calculator/furnaces/furnaces.component.html
- src/app/calculator/motors/motors.component.css
- src/app/calculator/motors/motors.component.html
- src/app/calculator/pumps/pumps.component.css
- src/app/calculator/pumps/pumps.component.html
- src/app/calculator/utilities/utilities.component.css
- src/app/calculator/utilities/utilities.component.html
- src/app/contact-page/contact-page.component.html
- src/app/dashboard/dashboard.component.html
- src/app/settings/facility-info/facility-info.component.html
- src/app/sidebar/assessment-item/assessment-item.component.css
- src/app/sidebar/assessment-item/assessment-item.component.html
- src/app/sidebar/directory-item/directory-item.component.css
- src/app/sidebar/directory-item/directory-item.component.html
- src/app/sidebar/sidebar.component.css
- src/app/sidebar/sidebar.component.html
- src/app/tutorials/tutorials.component.html
connects #1604 
and other style updates
> fix sidebar and other styles

- src/app/psat/explore-opportunities/explore-opportunities-form/explore-opportunities-form.component.html
- src/app/psat/field-data/field-data.component.html
connects #1668 
Comments out specific speed options, so this will be invisible to the user. Will later be re-enabled if we decide that we want to do something with this.
> specific speed disable

- src/app/assessment/assessment-grid-view/pre-assessment-card/pre-assessment-card.component.html
- src/app/assessment/assessment-grid-view/pre-assessment-card/pre-assessment-card.component.ts
- src/app/calculator/utilities/pre-assessment/pre-assessment-help/pre-assessment-help.component.html
- src/app/calculator/utilities/pre-assessment/pre-assessment-help/pre-assessment-help.component.ts
- src/app/calculator/utilities/pre-assessment/pre-assessment.component.html
- src/app/calculator/utilities/pre-assessment/pre-assessment.component.ts
- src/app/phast/designed-energy/designed-energy-electricity/designed-energy-electricity-help/designed-energy-electricity-help.component.html
- src/app/phast/designed-energy/designed-energy-electricity/designed-energy-electricity-help/designed-energy-electricity-help.component.ts
- src/app/phast/designed-energy/designed-energy-fuel/designed-energy-fuel-help/designed-energy-fuel-help.component.html
- src/app/phast/designed-energy/designed-energy-fuel/designed-energy-fuel-help/designed-energy-fuel-help.component.ts
- src/app/phast/designed-energy/designed-energy-steam/designed-energy-steam-help/designed-energy-steam-help.component.html
- src/app/phast/designed-energy/designed-energy-steam/designed-energy-steam-help/designed-energy-steam-help.component.ts
- src/app/phast/metered-energy/metered-electricity/metered-electricity-form/metered-electricity-form.component.html
- src/app/phast/metered-energy/metered-electricity/metered-electricity-help/metered-electricity-help.component.html
- src/app/phast/metered-energy/metered-electricity/metered-electricity-help/metered-electricity-help.component.ts
- src/app/phast/metered-energy/metered-fuel/metered-fuel-help/metered-fuel-help.component.html
- src/app/phast/metered-energy/metered-fuel/metered-fuel-help/metered-fuel-help.component.ts
- src/app/phast/metered-energy/metered-steam/metered-steam-form/metered-steam-form.component.html
- src/app/phast/metered-energy/metered-steam/metered-steam-help/metered-steam-help.component.html
- src/app/phast/metered-energy/metered-steam/metered-steam-help/metered-steam-help.component.ts
connects #1286 
connects #1637
> fix help and remove furnace verbage

- src/app/calculator/utilities/pre-assessment/pre-assessment-help/pre-assessment-help.component.html
- src/app/phast/metered-energy/metered-fuel/metered-fuel-help/metered-fuel-help.component.html
> help updates

- src/app/assessment/assessment-dashboard/assessment-dashboard.component.ts
- src/app/calculator/steam/saturated-properties/saturated-properties-form/saturated-properties-form.component.html
- src/app/calculator/steam/saturated-properties/saturated-properties-form/saturated-properties-form.component.ts
- src/app/calculator/steam/steam-properties/steam-properties-form/steam-properties-form.component.html
- src/app/calculator/steam/steam-properties/steam-properties-form/steam-properties-form.component.ts
Quick updates to create wrappers the steamService calls, so that the aot build will work.
> Wrappers for steamService calls

- src/app/assessment/assessment-grid-view/assessment-card/assessment-card.component.css
- src/app/assessment/assessment-grid-view/assessment-card/assessment-card.component.html
- src/app/dashboard/dashboard.component.css
- src/app/phast/explore-phast-opportunities/explore-phast-opportunities.component.html
- src/app/phast/modification-navbar/modification-navbar.component.css
- src/app/phast/phast-report/phast-report.component.css
- src/app/phast/phast-report/phast-report.component.html
- src/app/phast/phast-report/phast-report.component.ts
- src/app/phast/phast.component.css
- src/app/phast/phast.component.html
- src/app/psat/explore-opportunities/explore-opportunities.component.html
- src/app/psat/explore-opportunities/explore-opportunities.component.ts
- src/app/psat/help-panel/help-panel.component.html
- src/app/psat/help-panel/help-panel.component.ts
- src/app/psat/modify-conditions/modify-conditions.component.css
- src/app/psat/modify-conditions/modify-conditions.component.html
- src/app/psat/modify-conditions/modify-conditions.component.ts
- src/app/psat/psat-report/psat-report.component.css
- src/app/psat/psat-report/psat-report.component.html
- src/app/psat/psat-report/psat-report.component.ts
- src/app/psat/psat-tabs/psat-tabs.component.css
- src/app/psat/psat-tabs/psat-tabs.component.html
- src/app/psat/psat.component.html
- src/app/psat/psat.component.ts
- src/app/report-rollup/report-rollup.component.css
- src/app/report-rollup/report-rollup.component.html
- src/assets/styles/two-panel.css
> Scroll bars

- src/app/psat/modification-list/modification-list.component.html
> add optimized badge

- src/app/assessment/assessment-create/assessment-create.component.css
- src/app/assessment/assessment-create/assessment-create.component.html
- src/app/assessment/assessment-create/assessment-create.component.ts
- src/app/assessment/assessment-menu/assessment-menu.component.html
- src/app/assessment/assessment-menu/create-folder/create-folder.component.html
- src/app/assessment/assessment-menu/create-folder/create-folder.component.ts
- src/app/assessment/folder-contact-info/folder-contact-info.component.html
- src/app/assessment/folder-contact-info/folder-contact-info.component.ts
- src/app/settings/facility-info/facility-info.component.ts
> updated facility info logic

- src/app/calculator/steam/saturated-properties/saturated-properties-form/saturated-properties-form.component.html
- src/app/calculator/steam/saturated-properties/saturated-properties-form/saturated-properties-form.component.ts
- src/app/calculator/steam/saturated-properties/saturated-properties-graph/saturated-properties-graph.component.css
- src/app/calculator/steam/saturated-properties/saturated-properties-graph/saturated-properties-graph.component.html
- src/app/calculator/steam/saturated-properties/saturated-properties-graph/saturated-properties-graph.component.ts
- src/app/calculator/steam/saturated-properties/saturated-properties.component.html
- src/app/calculator/steam/saturated-properties/saturated-properties.component.ts
- src/app/calculator/steam/steam-properties/steam-properties-form/steam-properties-form.component.ts
- src/app/calculator/steam/steam-properties/steam-properties-graph/steam-properties-graph.component.css
- src/app/calculator/steam/steam-properties/steam-properties-graph/steam-properties-graph.component.html
- src/app/calculator/steam/steam-properties/steam-properties-graph/steam-properties-graph.component.ts
- src/app/calculator/steam/steam-properties/steam-properties.component.html
- src/app/calculator/steam/steam-properties/steam-properties.component.ts
- src/app/calculator/steam/steam.service.ts
> Issue 1659

- src/app/calculator/steam/saturated-properties/saturated-properties-graph/saturated-properties-graph.component.ts
- src/app/calculator/steam/steam-properties/steam-properties-graph/steam-properties-graph.component.ts
> Added graph updates

- src/app/assessment/assessment-settings/assessment-settings.component.ts
> fix issues 1760

- src/app/assessment/assessment-grid-view/assessment-card/assessment-card.component.css
- src/app/assessment/assessment-grid-view/assessment-card/assessment-card.component.html
- src/app/assessment/assessment-grid-view/assessment-card/assessment-card.component.ts
- src/app/assessment/assessment-list-view/assessment-list-item/assessment-list-item.component.css
- src/app/assessment/assessment-list-view/assessment-list-item/assessment-list-item.component.html
- src/app/assessment/assessment-list-view/assessment-list-item/assessment-list-item.component.ts
- src/app/dashboard/dashboard.component.ts
> copy delete edit options for assessment items

- src/app/calculator/furnaces/o2-enrichment/o2-enrichment-form/o2-enrichment-form.component.ts
- src/app/calculator/furnaces/o2-enrichment/o2-enrichment-graph/o2-enrichment-graph.component.ts
connects #1711 
- Removes flue gas temp warning in o2 enrichment
> O2 enrichment warning

- src/app/assessment/assessment-dashboard/assessment-dashboard.component.css
- src/app/assessment/assessment.service.ts
- src/app/core/core.component.html
- src/app/core/core.component.ts
- src/app/dashboard/dashboard.component.html
- src/app/phast/phast.component.ts
- src/app/psat/psat.component.ts
- src/app/report-rollup/report-rollup.component.ts
> remove screenshot, fix scrolling

- src/app/calculator/steam/saturated-properties/saturated-properties-form/saturated-properties-form.component.html
- src/app/calculator/steam/saturated-properties/saturated-properties-form/saturated-properties-form.component.ts
- src/app/calculator/steam/saturated-properties/saturated-properties-graph/saturated-properties-graph.component.ts
- src/app/calculator/steam/saturated-properties/saturated-properties.component.html
- src/app/calculator/steam/saturated-properties/saturated-properties.component.ts
- src/app/calculator/steam/steam-properties/steam-properties-form/steam-properties-form.component.ts
- src/app/calculator/steam/steam-properties/steam-properties-graph/steam-properties-graph.component.ts
- src/app/calculator/steam/steam-properties/steam-properties.component.html
- src/app/calculator/steam/steam-properties/steam-properties.component.ts
> Issue 1765

- src/app/phast/phast-report/phast-input-summary/flue-gas-summary/flue-gas-summary.component.html
> Changed Flue gas input summary verbiage

- src/app/phast/system-basics/system-basics.component.html
- src/app/settings/application-settings/application-settings.component.html
- src/app/settings/application-settings/application-settings.component.ts
> Removed duplicate settings from phast system setup

- src/app/phast/losses/charge-material/gas-charge-material-form/gas-charge-material-form.component.html
- src/app/phast/losses/charge-material/gas-charge-material-form/gas-charge-material-form.component.ts
- src/app/phast/losses/charge-material/liquid-charge-material-form/liquid-charge-material-form.component.html
- src/app/phast/losses/charge-material/liquid-charge-material-form/liquid-charge-material-form.component.ts
- src/app/phast/losses/charge-material/solid-charge-material-form/solid-charge-material-form.component.html
- src/app/phast/losses/charge-material/solid-charge-material-form/solid-charge-material-form.component.ts
> Added input warning for charge material initial temp

- src/app/phast/losses/opening-losses/opening-losses-form/opening-losses-form.component.html
- src/app/phast/losses/opening-losses/opening-losses-form/opening-losses-form.component.ts
> Issue 1674

- src/app/phast/phast-report/phast-input-summary/flue-gas-summary/flue-gas-summary.component.html
- src/app/phast/phast-report/phast-input-summary/phast-input-summary.module.ts
> Issue 1683

- src/app/phast/losses/charge-material/gas-charge-material-form/gas-charge-material-form.component.ts
- src/app/phast/losses/charge-material/liquid-charge-material-form/liquid-charge-material-form.component.ts
- src/app/phast/losses/charge-material/solid-charge-material-form/solid-charge-material-form.component.ts
> reversed warning

- src/app/assessment/assessment-grid-view/pre-assessment-card/pre-assessment-card.component.html
- src/app/calculator/utilities/pre-assessment/pre-assessment-cost-form/pre-assessment-cost-form.component.html
- src/app/calculator/utilities/pre-assessment/pre-assessment-cost-form/pre-assessment-cost-form.component.ts
- src/app/calculator/utilities/pre-assessment/pre-assessment-form/pre-assessment-form.component.html
- src/app/calculator/utilities/pre-assessment/pre-assessment.component.html
- src/app/calculator/utilities/pre-assessment/pre-assessment.service.ts
- src/app/calculator/utilities/pre-assessment/pre-assessment.ts
- src/app/dashboard/dashboard.component.html
- src/app/phast/metered-energy/metered-fuel/metered-fuel-form/metered-fuel-form.component.html
connects #1636 
fixes #1639 
connects #1639
> update costs for pre assessments

- src/app/assessment/assessment-grid-view/pre-assessment-card/pre-assessment-card.component.html
- src/app/calculator/utilities/pre-assessment/pre-assessment-cost-form/pre-assessment-cost-form.component.html
- src/app/calculator/utilities/pre-assessment/pre-assessment-cost-form/pre-assessment-cost-form.component.ts
- src/app/calculator/utilities/pre-assessment/pre-assessment-form/pre-assessment-designed/pre-assessment-designed.component.html
- src/app/calculator/utilities/pre-assessment/pre-assessment-form/pre-assessment-designed/pre-assessment-designed.component.ts
- src/app/calculator/utilities/pre-assessment/pre-assessment-form/pre-assessment-form.component.css
- src/app/calculator/utilities/pre-assessment/pre-assessment-form/pre-assessment-form.component.html
- src/app/calculator/utilities/pre-assessment/pre-assessment-form/pre-assessment-form.component.ts
- src/app/calculator/utilities/pre-assessment/pre-assessment-form/pre-assessment-metered/pre-assessment-metered.component.html
- src/app/calculator/utilities/pre-assessment/pre-assessment-form/pre-assessment-metered/pre-assessment-metered.component.ts
- src/app/calculator/utilities/pre-assessment/pre-assessment.component.html
- src/app/calculator/utilities/pre-assessment/pre-assessment.component.ts
- src/app/calculator/utilities/pre-assessment/pre-assessment.service.ts
- src/app/calculator/utilities/pre-assessment/pre-assessment.ts
- src/app/dashboard/dashboard.component.html
- src/app/phast/metered-energy/metered-fuel/metered-fuel-form/metered-fuel-form.component.html
> Issue 1689

- src/app/assessment/assessment-grid-view/pre-assessment-card/pre-assessment-card.component.html
- src/app/calculator/calculator.component.html
- src/app/calculator/utilities/power-factor-correction/power-factor-correction-form/power-factor-correction-form.component.html
- src/app/calculator/utilities/power-factor-correction/power-factor-correction-form/power-factor-correction-form.component.spec.ts
- src/app/calculator/utilities/power-factor-correction/power-factor-correction-form/power-factor-correction-form.component.ts
- src/app/calculator/utilities/power-factor-correction/power-factor-correction-help/power-factor-correction-help.component.html
- src/app/calculator/utilities/power-factor-correction/power-factor-correction-help/power-factor-correction-help.component.spec.ts
- src/app/calculator/utilities/power-factor-correction/power-factor-correction-help/power-factor-correction-help.component.ts
- src/app/calculator/utilities/power-factor-correction/power-factor-correction-results/power-factor-correction-results.component.html
- src/app/calculator/utilities/power-factor-correction/power-factor-correction-results/power-factor-correction-results.component.spec.ts
- src/app/calculator/utilities/power-factor-correction/power-factor-correction-results/power-factor-correction-results.component.ts
- src/app/calculator/utilities/power-factor-correction/power-factor-correction.component.html
- src/app/calculator/utilities/power-factor-correction/power-factor-correction.component.spec.ts
- src/app/calculator/utilities/power-factor-correction/power-factor-correction.component.ts
- src/app/calculator/utilities/power-factor-correction/power-factor-correction.module.ts
- src/app/calculator/utilities/power-factor-correction/power-factor-correction.service.spec.ts
- src/app/calculator/utilities/power-factor-correction/power-factor-correction.service.ts
- src/app/calculator/utilities/pre-assessment/pre-assessment-cost-form/pre-assessment-cost-form.component.html
- src/app/calculator/utilities/pre-assessment/pre-assessment-cost-form/pre-assessment-cost-form.component.ts
- src/app/calculator/utilities/pre-assessment/pre-assessment-form/pre-assessment-form.component.html
- src/app/calculator/utilities/pre-assessment/pre-assessment.component.html
- src/app/calculator/utilities/pre-assessment/pre-assessment.service.ts
- src/app/calculator/utilities/pre-assessment/pre-assessment.ts
- src/app/calculator/utilities/utilities.component.html
- src/app/calculator/utilities/utilities.module.ts
- src/app/dashboard/dashboard.component.html
- src/app/phast/metered-energy/metered-fuel/metered-fuel-form/metered-fuel-form.component.html
> Issue 1612

- src/app/assessment/assessment-grid-view/pre-assessment-card/pre-assessment-card.component.html
- src/app/calculator/motors/motor-drive/motor-drive-form/motor-drive-form.component.html
- src/app/calculator/motors/motor-drive/motor-drive-graph/motor-drive-graph.component.css
- src/app/calculator/motors/motor-drive/motor-drive-graph/motor-drive-graph.component.html
- src/app/calculator/motors/motor-drive/motor-drive-graph/motor-drive-graph.component.ts
- src/app/calculator/motors/motor-drive/motor-drive-table/motor-drive-table.component.html
- src/app/calculator/motors/motor-drive/motor-drive.component.html
- src/app/calculator/motors/motor-drive/motor-drive.service.ts
- src/app/calculator/motors/percent-load-estimation/field-measurement-form/field-measurement-form.component.html
- src/app/calculator/utilities/pre-assessment/pre-assessment-cost-form/pre-assessment-cost-form.component.html
- src/app/calculator/utilities/pre-assessment/pre-assessment-cost-form/pre-assessment-cost-form.component.ts
- src/app/calculator/utilities/pre-assessment/pre-assessment-form/pre-assessment-form.component.html
- src/app/calculator/utilities/pre-assessment/pre-assessment.component.html
- src/app/calculator/utilities/pre-assessment/pre-assessment.service.ts
- src/app/calculator/utilities/pre-assessment/pre-assessment.ts
- src/app/dashboard/dashboard.component.html
- src/app/phast/metered-energy/metered-fuel/metered-fuel-form/metered-fuel-form.component.html
connects #1611 
connects #1608
> Motor calc fixes

- src/app/phast/modification-list/modification-list.component.ts
> fix issue 1676

- src/app/calculator/furnaces/efficiency-improvement/efficiency-improvement-form/efficiency-improvement-form.component.html
- src/app/calculator/furnaces/efficiency-improvement/efficiency-improvement-form/efficiency-improvement-form.component.ts
- src/app/calculator/furnaces/o2-enrichment/o2-enrichment-form/o2-enrichment-form.component.ts
- src/app/phast/losses/flue-gas-losses/flue-gas-losses-form-mass/flue-gas-losses-form-mass.component.html
- src/app/phast/losses/flue-gas-losses/flue-gas-losses-form-mass/flue-gas-losses-form-mass.component.ts
- src/app/phast/losses/flue-gas-losses/flue-gas-losses-form-volume/flue-gas-losses-form-volume.component.html
- src/app/phast/losses/flue-gas-losses/flue-gas-losses-form-volume/flue-gas-losses-form-volume.component.ts
> Added phast warnings for combustion air temperature

- src/app/phast/losses/atmosphere-losses/atmosphere-losses.component.html
- src/app/phast/losses/auxiliary-power-losses/auxiliary-power-losses.component.html
- src/app/phast/losses/charge-material/charge-material.component.html
- src/app/phast/losses/cooling-losses/cooling-losses.component.html
- src/app/phast/losses/energy-input-exhaust-gas-losses/energy-input-exhaust-gas-losses.component.html
- src/app/phast/losses/energy-input/energy-input.component.html
- src/app/phast/losses/exhaust-gas/exhaust-gas.component.html
- src/app/phast/losses/extended-surface-losses/extended-surface-losses.component.html
- src/app/phast/losses/fixture-losses/fixture-losses.component.html
- src/app/phast/losses/flue-gas-losses/flue-gas-losses.component.html
- src/app/phast/losses/gas-leakage-losses/gas-leakage-losses.component.html
- src/app/phast/losses/opening-losses/opening-losses.component.html
- src/app/phast/losses/slag/slag.component.html
- src/app/phast/losses/wall-losses/wall-losses.component.html
> Loss names disable when not selected

- src/app/phast/losses/charge-material/liquid-charge-material-form/liquid-charge-material-form.component.html
- src/app/phast/losses/charge-material/liquid-charge-material-form/liquid-charge-material-form.component.ts
- src/app/phast/losses/charge-material/solid-charge-material-form/solid-charge-material-form.component.html
- src/app/phast/losses/charge-material/solid-charge-material-form/solid-charge-material-form.component.ts
> Added phast charge material warnings

- src/app/phast/losses/energy-input-exhaust-gas-losses/energy-input-exhaust-gas-losses.component.html
- src/app/phast/losses/energy-input-exhaust-gas-losses/energy-input-exhaust-gas-losses.component.ts
- src/app/phast/losses/energy-input/energy-input.component.html
- src/app/phast/losses/energy-input/energy-input.component.ts
- src/app/phast/losses/losses.component.html
- src/app/phast/phast-report/results-data/results-data.component.html
- src/app/phast/phast-results.service.ts
- src/app/shared/models/phast/phast.ts
> fix energy input non EAF

- src/app/calculator/utilities/pre-assessment/pre-assessment.component.ts
- src/app/calculator/utilities/pre-assessment/pre-assessment.service.ts
> fix cost bug

- src/app/phast/modification-list/modification-list.component.ts
- src/app/psat/modification-list/modification-list.component.ts
> close modal after last modification deleted

- src/app/calculator/utilities/pre-assessment/pre-assessment-form/pre-assessment-form.component.html
- src/app/phast/metered-energy/metered-fuel/metered-fuel-form/metered-fuel-form.component.html
> fixes to pre assessment

- src/app/psat/field-data/field-data.component.ts
- src/app/psat/motor/motor.component.ts
- src/app/psat/pump-fluid/pump-fluid.component.ts
- src/app/psat/system-basics/system-basics.component.ts
> fixes fluid temp bugs

- src/app/phast/sankey/sankey.component.ts
- src/app/phast/sankey/sankey.service.ts
> Issue 1833

- src/app/phast/losses/energy-input-exhaust-gas-losses/energy-input-exhaust-gas-form/energy-input-exhaust-gas-form.component.html
- src/app/phast/losses/energy-input-exhaust-gas-losses/energy-input-exhaust-gas-form/energy-input-exhaust-gas-form.component.ts
> Added phast warning for energy input

- src/app/phast/losses/energy-input-exhaust-gas-losses/energy-input-exhaust-gas-form/energy-input-exhaust-gas-form.component.html
- src/app/phast/losses/energy-input-exhaust-gas-losses/energy-input-exhaust-gas-form/energy-input-exhaust-gas-form.component.ts
> removed warning non eaf

- src/app/phast/convert-phast.service.ts
- src/app/phast/losses/losses.component.html
- src/app/phast/phast.component.ts
- src/app/phast/system-basics/system-basics.component.html
- src/app/phast/system-basics/system-basics.component.ts
> Issue 1356

- src/app/phast/explore-phast-opportunities/explore-phast-opportunities-form/explore-fixtures-form/explore-fixtures-form.component.html
- src/app/phast/explore-phast-opportunities/explore-phast-opportunities-form/explore-flue-gas-form/explore-flue-gas-form.component.html
- src/app/phast/explore-phast-opportunities/explore-phast-opportunities-form/explore-leakage-form/explore-leakage-form.component.html
- src/app/phast/explore-phast-opportunities/explore-phast-opportunities-form/explore-opening-form/explore-opening-form.component.html
- src/app/phast/explore-phast-opportunities/explore-phast-opportunities-form/explore-system-efficiency-form/explore-system-efficiency-form.component.html
- src/app/phast/explore-phast-opportunities/explore-phast-opportunities-form/explore-wall-form/explore-wall-form.component.html
- src/app/phast/explore-phast-opportunities/explore-phast-opportunities-form/explore-wall-form/explore-wall-form.component.ts
- src/app/phast/losses/losses.component.ts
> fix explore opps issues

- src/app/phast/phast-report/report-graphs/report-graphs.component.ts
> Issue 1845

- src/app/phast/phast-report/report-graphs/report-graphs-print/report-graphs-print.component.html
- src/app/phast/phast-report/report-sankey/report-sankey.component.html
- src/app/phast/sankey/sankey.component.ts
- src/app/psat/psat-report/psat-report-sankey/psat-report-sankey.component.html
- src/app/psat/psat-sankey/psat-sankey.component.ts
> Issue 1847

- src/app/phast/losses/losses-help/energy-input-exhaust-gas-losses-help/energy-input-exhaust-gas-losses-help.component.html
- src/app/psat/explore-opportunities/explore-opportunities-form/system-data-form/system-data-form.component.html
- src/app/shared/json-to-csv/json-to-csv.service.ts
connect #1688 
Fixed capitalization of units (kW, kWh, MMBtu)
> Issue 1688:  Fixed capitlization errors

- src/app/calculator/steam/saturated-properties/saturated-properties.component.ts
- src/app/calculator/steam/steam-properties/steam-properties-table/steam-properties-table.component.css
- src/app/calculator/steam/steam-properties/steam-properties-table/steam-properties-table.component.html
- src/app/calculator/steam/steam-properties/steam-properties-table/steam-properties-table.component.spec.ts
- src/app/calculator/steam/steam-properties/steam-properties-table/steam-properties-table.component.ts
- src/app/calculator/steam/steam-properties/steam-properties.component.css
- src/app/calculator/steam/steam-properties/steam-properties.component.html
- src/app/calculator/steam/steam-properties/steam-properties.component.ts
- src/app/calculator/steam/steam-properties/steam-properties.module.ts
> Issue 1739

- src/app/phast/losses/losses-help/charge-material-help/charge-material-help.component.html
- src/app/phast/losses/losses-help/energy-input-exhaust-gas-losses-help/energy-input-exhaust-gas-losses-help.component.html
- src/app/phast/losses/losses-help/extended-surface-losses-help/extended-surface-losses-help.component.html
- src/app/phast/losses/losses-help/flue-gas-losses-help/flue-gas-losses-help.component.html
- src/app/phast/losses/losses-help/gas-leakage-losses-help/gas-leakage-losses-help.component.html
- src/app/phast/losses/losses-help/wall-losses-help/wall-losses-help.component.html
- src/app/psat/pump-fluid/pump-fluid.component.ts
- src/app/settings/steam-settings/steam-settings.component.html
> Issue-1878: Fixed temp units and enthalpy default unit in settings

- src/app/phast/losses/energy-input-exhaust-gas-losses/energy-input-exhaust-gas-losses.component.ts
- src/app/phast/phast-results.service.ts
> fix issue 1864

- src/app/calculator/utilities/pre-assessment/pre-assessment-form/pre-assessment-form.component.ts
- src/app/calculator/utilities/pre-assessment/pre-assessment.service.ts
- src/app/core/mockPhast.ts
- src/app/phast/designed-energy/designed-energy-results/designed-energy-results.component.ts
- src/app/phast/designed-energy/designed-energy.service.ts
- src/app/phast/metered-energy/metered-energy-results/metered-energy-results.component.ts
- src/app/phast/metered-energy/metered-energy.component.ts
- src/app/phast/metered-energy/metered-energy.service.ts
connects #1890 
connects #1794
> Finish designed metered

- src/app/fsat/fsat-report/results-summary/results-summary.component.html
- src/app/fsat/fsat-results/fsat-results-panel/fsat-results-panel.component.html
> add energy index to results tbales

- src/app/psat/psat-report/psat-report-graphs/psat-report-graphs-print/psat-report-graphs-print.component.html
- src/app/psat/psat-report/psat-report-sankey/psat-report-sankey.component.html
- src/app/psat/psat-sankey/psat-sankey.component.ts
- src/app/psat/psat.component.html
> fix modified sankeys

- src/app/psat/psat-sankey/psat-sankey.component.ts
> fix psat sankey resultsModified call

- package.json
- src/app/version-modal/version-modal.component.css
- src/app/version-modal/version-modal.component.html
> updated release notes and version number

- src/app/calculator/utilities/power-factor-correction/power-factor-correction-form/power-factor-correction-form.component.html
- src/app/calculator/utilities/power-factor-correction/power-factor-correction-form/power-factor-correction-form.component.ts
- src/app/calculator/utilities/power-factor-correction/power-factor-correction-help/power-factor-correction-help.component.html
- src/app/calculator/utilities/power-factor-correction/power-factor-correction-results/power-factor-correction-results.component.html
- src/app/calculator/utilities/power-factor-correction/power-factor-correction.component.html
- src/app/calculator/utilities/power-factor-correction/power-factor-correction.component.ts
- src/app/calculator/utilities/power-factor-correction/power-factor-correction.service.ts
> Issue 1821

- src/app/update-modal/update-modal.component.html
> Issue-1896: "Thank you for your patience."

- src/app/fsat/fan-setup/fan-setup.component.html
- src/app/fsat/fan-setup/fan-setup.component.ts
- src/app/fsat/fan-setup/fan-setup.service.ts
> updates to specified fan efficiency

- src/app/assessment/assessment.service.ts
- src/app/calculator/fans/fsat-203/fsat-203.component.ts
- src/app/calculator/fans/fsat-203/fsat-203.service.ts
- src/app/fsat/help-panel/fsat-fluid-help/fsat-fluid-help.component.html
connect #1814 
Changed barometric pressure default to standard value.
Changed "barametric" to "barometric"
> Issue 1814

- src/app/fsat/fan-field-data/calculate-inlet-pressure/calculate-inlet-pressure.component.html
- src/app/fsat/fan-field-data/calculate-inlet-pressure/calculate-inlet-pressure.component.ts
- src/app/fsat/fan-field-data/calculate-outlet-pressure/calculate-outlet-pressure.component.html
- src/app/fsat/fan-field-data/calculate-outlet-pressure/calculate-outlet-pressure.component.ts
- src/app/fsat/fan-field-data/fan-field-data.component.html
- src/app/settings/fsat-settings/fsat-settings.component.html
- src/app/settings/fsat-settings/fsat-settings.component.ts
connect #1892 
Added unit formatting adjustments to inlet and outlet calculators
> Added unit formatting adjustmets to inlet and oulet calculators

- src/app/phast/phast.component.html
- src/app/phast/sankey/sankey.component.ts
- src/app/phast/sankey/sankey.service.ts
> Issue 1831 fix

- src/app/calculator/utilities/power-factor-correction/power-factor-correction-form/power-factor-correction-form.component.html
- src/app/calculator/utilities/power-factor-correction/power-factor-correction-results/power-factor-correction-results.component.html
- src/app/calculator/utilities/utilities.component.html
connect #1938 
Removed inputs and changed description
> issue-1938: changed power factor help text

- src/app/fsat/explore-opportunities/explore-opportunities-form/system-data-form/system-data-form.component.html
- src/app/settings/fsat-settings/fsat-settings.component.html
- src/app/settings/fsat-settings/fsat-settings.component.ts
- src/app/settings/settings.service.ts
Fixed default imperial units for fsat flow measurement
Fixed Flow Measurement (fsat) value default & updating with swap to metric
connect #1736
> Issue 1736

- src/app/calculator/motors/motor-performance/motor-performance-form/motor-performance-form.component.ts
- src/app/calculator/motors/nema-energy-efficiency/nema-energy-efficiency-form/nema-energy-efficiency-form.component.ts
- src/app/psat/motor/motor.component.ts
- src/app/settings/psat-settings/psat-settings.component.html
Fixed unit formatting in PSAT assessment settings.
old: ( _unit_ )
new: (_unit_)
connect #1929
> Issue 1929

- src/app/assessment/assessment.service.ts
- src/app/dashboard/dashboard.component.ts
- src/app/phast/phast-banner/phast-banner.component.css
- src/app/phast/phast-banner/phast-banner.component.html
- src/app/phast/phast-banner/phast-banner.component.ts
- src/app/psat/psat-banner/psat-banner.component.css
- src/app/psat/psat-banner/psat-banner.component.html
- src/app/psat/psat-banner/psat-banner.component.ts
- src/app/sidebar/directory-item/directory-item.component.ts
- src/app/sidebar/sidebar.component.ts
> Issue 1579

- src/app/calculator/calculator.component.html
- src/app/calculator/utilities/power-factor-correction/power-factor-correction-form/power-factor-correction-form.component.html
- src/app/calculator/utilities/power-factor-correction/power-factor-correction-help/power-factor-correction-help.component.html
- src/app/calculator/utilities/power-factor-correction/power-factor-correction-results/power-factor-correction-results.component.html
- src/app/calculator/utilities/power-factor-correction/power-factor-correction.component.ts
- src/app/calculator/utilities/power-factor-correction/power-factor-correction.service.ts
- src/app/calculator/utilities/unit-converter/unit-converter.component.ts
- src/app/calculator/utilities/utilities.component.html
Fixed power factor correction calculations
Cleaned up help text and description
connect #1938
> Issue 1938

- src/app/assessment/assessment-grid-view/assessment-card/assessment-card.component.html
- src/app/assessment/assessment-grid-view/directory-card/directory-card.component.html
- src/app/assessment/assessment-grid-view/pre-assessment-card/pre-assessment-card.component.css
- src/app/assessment/assessment-grid-view/pre-assessment-card/pre-assessment-card.component.html
- src/app/assessment/assessment-grid-view/pre-assessment-card/pre-assessment-card.component.ts
- src/app/assessment/assessment-list-view/assessment-list-item/assessment-list-item.component.html
- src/app/assessment/assessment-list-view/pre-assessment-list-item/pre-assessment-list-item.component.css
- src/app/assessment/assessment-list-view/pre-assessment-list-item/pre-assessment-list-item.component.html
- src/app/assessment/assessment-list-view/pre-assessment-list-item/pre-assessment-list-item.component.ts
> Issue 1617

- src/app/assessment/assessment-grid-view/assessment-card/assessment-card.component.html
- src/app/assessment/assessment-grid-view/directory-card/directory-card.component.html
- src/app/assessment/assessment-grid-view/pre-assessment-card/pre-assessment-card.component.css
- src/app/assessment/assessment-grid-view/pre-assessment-card/pre-assessment-card.component.html
- src/app/assessment/assessment-grid-view/pre-assessment-card/pre-assessment-card.component.ts
- src/app/assessment/assessment-list-view/assessment-list-item/assessment-list-item.component.html
- src/app/assessment/assessment-list-view/pre-assessment-list-item/pre-assessment-list-item.component.css
- src/app/assessment/assessment-list-view/pre-assessment-list-item/pre-assessment-list-item.component.html
- src/app/assessment/assessment-list-view/pre-assessment-list-item/pre-assessment-list-item.component.ts
- src/app/calculator/utilities/pre-assessment/pre-assessment-form/pre-assessment-form.component.css
- src/app/calculator/utilities/pre-assessment/pre-assessment.component.css
- src/app/calculator/utilities/pre-assessment/pre-assessment.component.html
- src/app/report-rollup/fsat-rollup/fsat-rollup.component.css
- src/app/report-rollup/fsat-rollup/fsat-rollup.component.ts
- src/app/report-rollup/report-rollup.component.ts
- src/app/report-rollup/report-rollup.service.ts
- src/assets/styles/two-panel.css
connects #1724 
merged in pre assessment updates currently in open PR for 1617
> Issue 1724

- src/app/app.component.css
> fix badges

- src/app/assessment/assessment-settings/assessment-settings.component.css
- src/app/assessment/assessment-settings/assessment-settings.component.html
- src/app/assessment/assessment-settings/assessment-settings.component.ts
- src/app/settings/application-settings/application-settings.component.html
- src/app/settings/phast-settings/phast-settings.component.html
- src/app/settings/phast-settings/phast-settings.component.ts
connects #1589 
Added toggle for each tool in application settings page
Moved common units under Process Heating settings
> Issue 1589

- src/app/settings/settings.service.ts
- src/app/settings/steam-settings/steam-settings.component.html
- src/app/settings/steam-settings/steam-settings.component.ts
- src/app/shared/convert-units/definitions/specificHeat.ts
connects #1978
Fixed specific enthalpy measurement bug. btulb -> btuLb.
Updated steam settings to match others.
Fixed formatting error of temperature units under specific heat (specific entropy).
> issue-1978

- src/app/assessment/assessment-settings/assessment-settings.component.html
connect #1985 
Drop-down text in settings menu
> dropdown descriptions in settings

- src/app/calculator/motors/motor-performance/motor-performance-form/motor-performance-form.component.ts
- src/app/calculator/motors/nema-energy-efficiency/nema-energy-efficiency-form/nema-energy-efficiency-form.component.ts
- src/app/psat/explore-opportunities/explore-opportunities-form/rated-motor-form/rated-motor-form.component.ts
- src/app/psat/explore-opportunities/explore-opportunities-help/explore-opportunities-help.component.html
- src/app/psat/help-panel/motor-help/motor-help.component.html
- src/app/psat/motor/motor.component.ts
connects #1599
changed premium back to premium efficient
> issue 1599

- package.json
> updated tools suite

- src/app/calculator/calculator.component.html
- src/app/calculator/furnaces/energy-use/energy-use-form/energy-use-form.component.html
- src/app/calculator/furnaces/energy-use/energy-use-help/energy-use-help.component.html
- src/app/calculator/furnaces/energy-use/energy-use.component.ts
- src/app/calculator/furnaces/furnaces.component.html
Flow and energy used calculator help text
connect #1633
> Energy used calculator

- src/app/core/core.service.ts
- src/app/core/mockFsat.ts
- src/app/shared/update-data.service.ts
connect #1835 
Added fsat assessment example
> Issue 1835

- src/app/settings/phast-settings/phast-settings.component.html
Fixed issue 1925 by adding conditional logic checking that electricity is selected as fuel type
connects #1925
> issue 1925

- src/app/assessment/assessment-settings/assessment-settings.component.html
connects #2003
Changed FSAT Settings to Fan Settings and text below
> Changed FSAT Settings to Fan Settings and text below

- src/app/phast/aux-equipment/aux-equipment-form/aux-equipment-form.component.html
Repositioned Motor Power and Motor Phase radio buttons in PHAST assessment under Aux Equipment tab
connects #1928
> issue 1928

- src/app/assessment/assessment.service.ts
> fix issue-1981

- src/app/psat/psat-report/input-summary/input-summary.component.html
- src/app/psat/psat-report/input-summary/input-summary.component.ts
Added specified efficiency row to psat input summary with conditional logic
connects #1986
> issue 1986

- src/app/psat/psat-report/psat-report-graphs/psat-report-graphs.component.ts
> Issue 1964

- src/app/calculator/motors/motor-drive/motor-drive-help/motor-drive-help.component.html
connect #2033 
Motor drive help text fix
> changed to kWh in motor drive

- src/app/fsat/fan-field-data/calculate-inlet-pressure/calculate-inlet-pressure-help/calculate-inlet-pressure-help.component.html
- src/app/fsat/fan-field-data/calculate-outlet-pressure/calculate-outlet-pressure-help/calculate-outlet-pressure-help.component.html
Added help text to inlet/outlet pressure modals
connects #1783
> issue 1783

- src/app/fsat/fsat-report/fsat-report-graphs/fsat-bar-chart/fsat-bar-chart.component.ts
- src/app/fsat/fsat-report/fsat-report-graphs/fsat-report-graphs.component.ts
- src/app/psat/psat-report/psat-report-graphs/psat-bar-chart/psat-bar-chart.component.ts
> Fixed graph labels, going to need verification for conversions

- src/app/calculator/calculator.component.css
- src/app/calculator/calculator.component.html
- src/app/calculator/compressed-air/compressed-air.component.css
- src/app/calculator/compressed-air/compressed-air.component.html
- src/app/calculator/furnaces/furnaces.component.css
- src/app/calculator/furnaces/furnaces.component.html
- src/app/calculator/motors/motors.component.css
- src/app/calculator/motors/motors.component.html
- src/app/calculator/pumps/pumps.component.css
- src/app/calculator/pumps/pumps.component.html
- src/app/calculator/steam/steam.component.css
- src/app/calculator/steam/steam.component.html
- src/app/calculator/utilities/utilities.component.css
- src/app/calculator/utilities/utilities.component.html
Added clickable icons to all calculators
connects #1607
> issue 1607

- src/app/calculator/calculator.component.html
Reordered calculators in All Calculators to match sidebar
connects #1926
> issue 1926

- src/app/fsat/fsat-report/fsat-report-graphs/fsat-report-graphs.component.ts
- src/app/psat/psat-report/psat-report-graphs/psat-report-graphs.component.ts
- src/app/shared/pie-chart/pie-chart.component.ts
> Fixed graphing color issue for psat and fsat

- src/app/calculator/fans/fans.component.html
connect #2039 
Added calculator description
> fan eff added description

- src/app/phast/losses/energy-input-exhaust-gas-losses/energy-input-exhaust-gas-form/energy-input-exhaust-gas-form.component.html
- src/app/psat/field-data/field-data.component.html
- src/app/psat/field-data/field-data.component.ts
> fix issue 1893

- src/app/calculator/steam/steam-properties/steam-properties-form/steam-properties-form.component.html
- src/app/calculator/steam/steam-properties/steam-properties-form/steam-properties-form.component.ts
- src/app/calculator/steam/steam.service.ts
> Issue 1990

- src/app/calculator/calculator.component.html
- src/app/calculator/motors/motors.component.html
- src/app/calculator/pumps/pumps.component.html
Fixed typo 'Under description for Pump Efficiency Curves 'various' is misspelled.'
connects #2036
> issue 2036

- src/app/calculator/motors/percent-load-estimation/slip-method-form/slip-method-form.component.html
> Formatted synchronous speed

- src/app/calculator/motors/replace-existing/replace-existing-help/replace-existing-help.component.html
Added help text to Purchase Cost, Replace Existing Motor calc
connects #1346
> issue 1346

- src/app/fsat/add-modification/add-modification.component.ts
- src/app/fsat/explore-opportunities/explore-opportunities-form/explore-opportunities-form.component.html
- src/app/fsat/explore-opportunities/explore-opportunities.component.ts
- src/app/fsat/fsat.component.html
- src/app/fsat/fsat.component.ts
- src/app/fsat/fsat.module.ts
- src/app/fsat/modification-list/modification-list.component.ts
connects #2086 
connects #2087
> toasty messaging added for disclaimer and explore opps

- src/app/sidebar/sidebar.component.html
> navigation back to fans works

- src/app/calculator/fans/fsat-203/operating-points-help/fan-data-help/fan-data-help.component.html
- src/app/calculator/fans/fsat-203/operating-points-help/fan-shaft-power-help/fan-shaft-power-help.component.html
- src/app/calculator/fans/fsat-203/operating-points-help/fsat-basics-help/fsat-basics-help.component.html
- src/app/calculator/fans/fsat-203/operating-points-help/gas-density-help/gas-density-help.component.html
Added help text to operating points calculator
connects #2002
> Issue 2002

- src/app/phast/phast-report/executive-summary/executive-summary.component.css
- src/app/phast/phast-report/executive-summary/executive-summary.component.html
- src/app/phast/phast-report/executive-summary/executive-summary.component.ts
- src/app/shared/percent-graph/percent-graph.component.ts
> Issue 1692

- src/app/calculator/fans/fsat-203/fan-data/fan-data-form/fan-data-form.component.html
- src/app/calculator/fans/fsat-203/fan-data/plane-3-form/plane-3-form.component.html
- src/app/calculator/fans/fsat-203/fan-shaft-power/fan-shaft-power.component.html
- src/app/calculator/fans/fsat-203/fan-shaft-power/fan-shaft-power.component.ts
- src/app/calculator/fans/fsat-203/fsat-203.component.ts
- src/app/calculator/fans/fsat-203/fsat-203.service.ts
- src/app/calculator/fans/fsat-203/gas-density/gas-density.component.ts
- src/app/calculator/fans/fsat-203/operating-points-help/fan-data-help/fan-data-help.component.html
- src/app/fsat/convert-fsat.service.ts
connects #2121  
connects #2119 
connects #2118
connects #2117
> Op points fixes

- src/app/version-modal/version-modal.component.html
> Updated release notes modal

- src/app/calculator/fans/fans.component.html
> issue 2126

- src/app/fsat/help-panel/fsat-fluid-help/fsat-fluid-help.component.html
> Added Gas Type help text

- src/app/calculator/fans/fsat-203/fsat-203.component.ts
- src/app/calculator/fans/fsat-203/fsat-203.service.ts
fixes x100 efficiency results
fixes #2119
> fix op points defaults

- src/app/calculator/fans/fsat-203/fan-shaft-power/fan-shaft-power.component.html
- src/app/calculator/fans/fsat-203/operating-points-help/fan-shaft-power-help/fan-shaft-power-help.component.html
- src/app/calculator/pumps/pump-curve/pump-curve-help/pump-curve-help.component.html
connects #2125 
connects #2120
> fix 2125 and 2120

- main.js
- package.json
- src/app/update-modal/update-modal.component.ts
> Issue 1959

- src/app/dashboard/dashboard.component.html
- src/app/dashboard/dashboard.component.ts
- src/app/landing-screen/landing-screen.component.ts
- src/app/sidebar/directory-item/directory-item.component.ts
- src/app/sidebar/sidebar.component.ts
> fixed dashboard landing screen

- src/app/calculator/steam/steam.component.ts
- src/app/calculator/steam/steam.service.ts
- src/app/shared/models/steam.ts
connects #2153 
connects #2154
> Issue 2153

- src/app/calculator/steam/stack-loss/stack-loss-form/stack-loss-by-mass/stack-loss-by-mass.component.html
- src/app/calculator/steam/stack-loss/stack-loss-form/stack-loss-by-mass/stack-loss-by-mass.component.spec.ts
- src/app/calculator/steam/stack-loss/stack-loss-form/stack-loss-by-mass/stack-loss-by-mass.component.ts
- src/app/calculator/steam/stack-loss/stack-loss-form/stack-loss-by-volume/stack-loss-by-volume.component.html
- src/app/calculator/steam/stack-loss/stack-loss-form/stack-loss-by-volume/stack-loss-by-volume.component.spec.ts
- src/app/calculator/steam/stack-loss/stack-loss-form/stack-loss-by-volume/stack-loss-by-volume.component.ts
- src/app/calculator/steam/stack-loss/stack-loss-form/stack-loss-form.component.html
- src/app/calculator/steam/stack-loss/stack-loss-form/stack-loss-form.component.spec.ts
- src/app/calculator/steam/stack-loss/stack-loss-form/stack-loss-form.component.ts
- src/app/calculator/steam/stack-loss/stack-loss-help/stack-loss-help.component.html
- src/app/calculator/steam/stack-loss/stack-loss-help/stack-loss-help.component.spec.ts
- src/app/calculator/steam/stack-loss/stack-loss-help/stack-loss-help.component.ts
- src/app/calculator/steam/stack-loss/stack-loss.component.html
- src/app/calculator/steam/stack-loss/stack-loss.component.spec.ts
- src/app/calculator/steam/stack-loss/stack-loss.component.ts
- src/app/calculator/steam/stack-loss/stack-loss.module.spec.ts
- src/app/calculator/steam/stack-loss/stack-loss.module.ts
- src/app/calculator/steam/steam.component.html
- src/app/calculator/steam/steam.module.ts
> Issue 2156

- src/app/calculator/utilities/unit-converter/unit-converter.component.ts
- src/app/core/mockFsat.ts
- src/app/core/mockPhast.ts
- src/app/core/mockPsat.ts
- src/app/indexedDb/settings-db.service.ts
- src/app/settings/settings.service.ts
- src/app/shared/convert-units/definitions/mass.ts
> added and updated mass units

- src/app/indexedDb/settings-db.service.ts
fixes bug not allowing assessments to be created
> fix settings check

- src/app/calculator/steam/boiler/boiler-form/boiler-form.component.ts
- src/app/calculator/steam/flash-tank/flash-tank-form/flash-tank-form.component.ts
- src/app/calculator/steam/heat-loss/heat-loss-form/heat-loss-form.component.ts
- src/app/calculator/steam/heat-loss/heat-loss.component.ts
- src/app/calculator/steam/prv/feedwater-form/feedwater-form.component.css
- src/app/calculator/steam/prv/feedwater-form/feedwater-form.component.html
- src/app/calculator/steam/prv/feedwater-form/feedwater-form.component.spec.ts
- src/app/calculator/steam/prv/feedwater-form/feedwater-form.component.ts
- src/app/calculator/steam/prv/inlet-form/inlet-form.component.css
- src/app/calculator/steam/prv/inlet-form/inlet-form.component.html
- src/app/calculator/steam/prv/inlet-form/inlet-form.component.spec.ts
- src/app/calculator/steam/prv/inlet-form/inlet-form.component.ts
- src/app/calculator/steam/prv/prv-help/prv-help.component.html
- src/app/calculator/steam/prv/prv-help/prv-help.component.spec.ts
- src/app/calculator/steam/prv/prv-help/prv-help.component.ts
- src/app/calculator/steam/prv/prv-results/prv-results.component.css
- src/app/calculator/steam/prv/prv-results/prv-results.component.html
- src/app/calculator/steam/prv/prv-results/prv-results.component.spec.ts
- src/app/calculator/steam/prv/prv-results/prv-results.component.ts
- src/app/calculator/steam/prv/prv.component.html
- src/app/calculator/steam/prv/prv.component.spec.ts
- src/app/calculator/steam/prv/prv.component.ts
- src/app/calculator/steam/prv/prv.module.spec.ts
- src/app/calculator/steam/prv/prv.module.ts
- src/app/calculator/steam/prv/prv.service.spec.ts
- src/app/calculator/steam/prv/prv.service.ts
- src/app/calculator/steam/steam.component.html
- src/app/calculator/steam/steam.module.ts
- src/app/calculator/steam/steam.service.ts
- src/app/shared/models/steam.ts
> Issue 2137

- src/app/calculator/steam/header/header.component.html
- src/app/calculator/steam/steam.service.ts
> fix energy flow header calc

- src/app/shared/convert-units/definitions/mass.ts
> fix imperial ton unit

- src/app/calculator/compressed-air/bag-method/bag-method-form/bag-method-form.component.html
- src/app/calculator/compressed-air/bag-method/bag-method.component.ts
> added annual compressed air leakage

- src/app/calculator/compressed-air/bag-method/bag-method-form/bag-method-form.component.html
- src/app/calculator/compressed-air/bag-method/bag-method.component.ts
- src/app/calculator/compressed-air/system-capacity/system-capacity-form/system-capacity-form.component.html
- src/app/calculator/compressed-air/system-capacity/system-capacity.component.html
- src/app/calculator/compressed-air/system-capacity/system-capacity.component.ts
- src/app/calculator/standalone.service.ts
> Issue 2128

- src/app/calculator/steam/steam.service.ts
> fix header energy flow

- src/app/psat/psat-report/psat-report-graphs/psat-bar-chart/psat-bar-chart.component.ts
- src/app/psat/psat-report/psat-report-graphs/psat-report-graphs-print/psat-report-graphs-print.component.html
- src/app/psat/psat-report/psat-report-graphs/psat-report-graphs-print/psat-report-graphs-print.component.ts
- src/app/psat/psat-report/psat-report-graphs/psat-report-graphs.component.html
- src/app/psat/psat-report/psat-report-graphs/psat-report-graphs.component.ts
- src/app/psat/psat-report/psat-report-sankey/psat-report-sankey.component.html
- src/app/psat/psat-sankey/psat-sankey.component.ts
connects #1623 
fixes psat sankey printing
> fixed psat printing graphs

- src/app/calculator/steam/prv/inlet-form/inlet-form.component.html
- src/app/calculator/steam/prv/prv.component.html
- src/app/calculator/steam/prv/prv.component.ts
- src/app/calculator/steam/turbine/turbine-form/turbine-form.component.ts
- src/app/calculator/steam/turbine/turbine.component.html
- src/app/calculator/steam/turbine/turbine.component.ts
- src/app/calculator/steam/turbine/turbine.service.ts
> added steam warnings

- src/app/calculator/pumps/pump-curve/pump-curve-equation-form/pump-curve-equation-form.component.html
- src/app/calculator/pumps/pump-curve/pump-curve-equation-form/pump-curve-equation-form.component.ts
- src/app/calculator/pumps/pump-curve/pump-curve-form/pump-curve-form.component.html
- src/app/calculator/pumps/pump-curve/pump-curve-form/pump-curve-form.component.ts
- src/app/calculator/pumps/pump-curve/pump-curve.service.ts
> Added value restrictions for pump curve

- src/app/psat/explore-opportunities/explore-opportunities-results/explore-opportunities-results.component.html
connects #2221 
connects #2220
> Fixed annual energy psat bug

- src/app/report-rollup/report-rollup.component.html
> Blank rollups won't print anymore

- src/app/psat/psat-sankey/psat-sankey.component.ts
fixes sankey rollup issues
connects #2224
> create input copy for baseline conversions

- src/app/calculator/pumps/pump-curve/pump-curve-help/pump-curve-help.component.html
- src/app/calculator/pumps/pump-curve/pump-curve.component.html
> Added pump speed warning and fixed pump curve title

- src/app/core/core.routing.ts
- src/app/report-rollup/report-rollup.component.html
- src/app/report-rollup/report-rollup.component.ts
> dashboard path to empty string

- src/app/assessment/folder-summary/folder-summary.component.html
- src/app/assessment/folder-summary/folder-summary.component.ts
> Added fans to folder summary

- src/app/acknowledgments-page/acknowledgments-page.component.html
> Added missing people to acknowledgements page

- package.json
- src/app/version-modal/version-modal.component.html
> Updated release notes

- src/app/fsat/fsat-report/fsat-report-graphs/fsat-bar-chart/fsat-bar-chart.component.ts
- src/app/fsat/fsat-report/fsat-report-graphs/fsat-report-graphs-print/fsat-report-graphs-print.component.css
- src/app/fsat/fsat-report/fsat-report-graphs/fsat-report-graphs-print/fsat-report-graphs-print.component.html
- src/app/fsat/fsat-report/fsat-report-graphs/fsat-report-graphs-print/fsat-report-graphs-print.component.spec.ts
- src/app/fsat/fsat-report/fsat-report-graphs/fsat-report-graphs-print/fsat-report-graphs-print.component.ts
- src/app/fsat/fsat-report/fsat-report-graphs/fsat-report-graphs.component.html
- src/app/fsat/fsat-report/fsat-report.component.html
- src/app/fsat/fsat-report/fsat-report.component.ts
- src/app/fsat/fsat-report/fsat-report.module.ts
- src/app/fsat/fsat-report/fsat-report.service.spec.ts
- src/app/fsat/fsat-report/fsat-report.service.ts
- src/app/fsat/fsat-report/input-summary/input-summary.component.css
- src/app/fsat/fsat-report/input-summary/input-summary.component.html
- src/app/fsat/fsat-report/results-summary/results-summary.component.html
- src/app/fsat/fsat-report/results-summary/results-summary.component.ts
- src/app/fsat/fsat-sankey/fsat-sankey.component.ts
- src/app/psat/psat-report/psat-report-graphs/psat-bar-chart/psat-bar-chart.component.html
- src/app/psat/psat-report/psat-report-graphs/psat-report-graphs-print/psat-report-graphs-print.component.html
- src/app/psat/psat-report/psat-report-graphs/psat-report-graphs-print/psat-report-graphs-print.component.ts
- src/app/psat/psat-report/psat-report-graphs/psat-report-graphs.component.html
- src/app/psat/psat-sankey/psat-sankey.component.ts
- src/app/report-rollup/fsat-rollup/fsat-rollup-graphs/fsat-rollup-graphs.component.ts
- src/app/report-rollup/fsat-rollup/fsat-rollup-print/fsat-rollup-print.component.css
- src/app/report-rollup/fsat-rollup/fsat-rollup-print/fsat-rollup-print.component.html
- src/app/report-rollup/fsat-rollup/fsat-rollup-print/fsat-rollup-print.component.spec.ts
- src/app/report-rollup/fsat-rollup/fsat-rollup-print/fsat-rollup-print.component.ts
- src/app/report-rollup/report-rollup-print/report-rollup-print.component.html
- src/app/report-rollup/report-rollup.component.html
- src/app/report-rollup/report-rollup.module.ts
connects #2244 
connects #2245
> Issue 2245

- src/app/phast/losses/energy-input-exhaust-gas-losses/energy-input-exhaust-gas-form/energy-input-exhaust-gas-form.component.ts
> Removed warnings if total heat input is 0

- src/app/phast/losses/energy-input/energy-input-form/energy-input-form.component.html
> Changed electricity input unit to kW

- src/app/calculator/pumps/pump-curve/pump-curve-help/pump-curve-help.component.html
> Updated fan curve help text

- src/app/shared/convert-units/definitions/pressure.ts
> Issue 2188

- src/app/phast/losses/energy-input/energy-input-form/energy-input-form.component.html
- src/app/phast/losses/energy-input/energy-input.component.html
- src/app/phast/losses/energy-input/energy-input.component.ts
- src/app/phast/losses/losses-help/energy-input-help/energy-input-help.component.html
- src/app/phast/losses/losses-tabs/exhaust-gas-tab/exhaust-gas-tab.component.ts
- src/app/phast/phast-results.service.ts
connects #2265 
connects #2296
> Issue 2265

- src/app/phast/explore-phast-opportunities/explore-phast-opportunities-form/explore-cooling-form/explore-cooling-form.component.html
- src/app/phast/explore-phast-opportunities/explore-phast-opportunities-form/explore-cooling-form/explore-cooling-form.component.ts
- src/app/phast/explore-phast-opportunities/explore-phast-opportunities.component.ts
- src/app/phast/modification-list/modification-list.component.ts
- src/app/phast/phast.component.ts
> fix cooling and delete all modification

- src/app/calculator/compressed-air/bag-method/bag-method-form/bag-method-form.component.css
- src/app/calculator/compressed-air/bag-method/bag-method-form/bag-method-form.component.html
- src/app/calculator/compressed-air/bag-method/bag-method-form/bag-method-form.component.ts
- src/app/calculator/compressed-air/bag-method/bag-method.component.css
- src/app/calculator/compressed-air/bag-method/bag-method.component.html
- src/app/calculator/compressed-air/bag-method/bag-method.component.ts
> Issue 2000 dima

- src/app/core/core.component.ts
> fixed dashboard tutorial

- src/app/assessment/assessment-grid-view/assessment-card/fsat-summary-card/fsat-summary-card.component.css
- src/app/assessment/assessment-grid-view/assessment-card/fsat-summary-card/fsat-summary-card.component.html
- src/app/assessment/assessment-grid-view/assessment-card/phast-summary-card/phast-summary-card.component.css
- src/app/assessment/assessment-grid-view/assessment-card/phast-summary-card/phast-summary-card.component.html
- src/app/assessment/assessment-grid-view/assessment-card/psat-summary-card/psat-summary-card.component.css
- src/app/assessment/assessment-grid-view/assessment-card/psat-summary-card/psat-summary-card.component.html
- src/app/assessment/assessment-list-view/assessment-list-item/assessment-list-item.component.css
- src/app/assessment/assessment-list-view/assessment-list-item/assessment-list-item.component.html
> style fixes for quick report

- src/app/calculator/compressed-air/air-velocity/air-velocity.component.ts
- src/app/calculator/compressed-air/bag-method/bag-method.component.ts
- src/app/calculator/compressed-air/compressed-air.service.ts
- src/app/calculator/compressed-air/flow-factor/flow-factor-form/flow-factor-form.component.html
- src/app/calculator/compressed-air/flow-factor/flow-factor.component.ts
- src/app/calculator/compressed-air/operating-cost/operating-cost-form/operating-cost-form.component.html
- src/app/calculator/compressed-air/operating-cost/operating-cost.component.ts
- src/app/calculator/compressed-air/pipe-sizing/pipe-sizing.component.ts
- src/app/calculator/compressed-air/pneumatic-air/pneumatic-air.component.ts
- src/app/calculator/compressed-air/receiver-tank/air-capacity-form/air-capacity-form.component.html
- src/app/calculator/compressed-air/receiver-tank/air-capacity-form/air-capacity-form.component.ts
- src/app/calculator/compressed-air/receiver-tank/dedicated-storage-form/dedicated-storage-form.component.ts
- src/app/calculator/compressed-air/receiver-tank/delay-method-form/delay-method-form.component.ts
- src/app/calculator/compressed-air/receiver-tank/general-method-form/general-method-form.component.ts
- src/app/calculator/compressed-air/receiver-tank/metered-storage-form/metered-storage-form.component.ts
- src/app/calculator/compressed-air/system-capacity/system-capacity-form/system-capacity-form.component.ts
- src/app/calculator/compressed-air/system-capacity/system-capacity.component.html
- src/app/calculator/compressed-air/system-capacity/system-capacity.component.ts
- src/app/calculator/standalone.service.ts
- src/app/calculator/utilities/combined-heat-power/combined-heat-power.component.ts
- src/app/shared/models/standalone.ts
> Issue 2292

- src/app/fsat/fsat-tabs/fsat-tabs.component.ts
- src/app/psat/psat.component.ts
> Issue 2327

- src/app/calculator/compressed-air/air-velocity/air-velocity-form/air-velocity-form.component.html
- src/app/calculator/compressed-air/bag-method/bag-method-form/bag-method-form.component.ts
- src/app/calculator/compressed-air/system-capacity/system-capacity-form/system-capacity-form.component.html
- src/app/calculator/compressed-air/system-capacity/system-capacity.component.ts
- src/app/calculator/standalone.service.ts
- src/app/shared/models/standalone.ts
> fix compressed air conversions

- src/app/fsat/explore-opportunities/explore-opportunities-form/system-data-form/system-data-form.component.html
> fix pressure measurement label, fsat explore opps

- src/app/fsat/fsat-banner/fsat-banner.component.ts
- src/app/fsat/help-panel/help-panel.component.ts
- src/app/fsat/help-panel/modify-conditions-notes/modify-conditions-notes.component.ts
- src/app/fsat/modify-conditions/modify-conditions.component.html
connects #2368 
connects #2369
> fixed 2368 2369

- src/app/fsat/explore-opportunities/explore-opportunities-form/rated-motor-form/rated-motor-form.component.html
- src/app/fsat/explore-opportunities/explore-opportunities-form/rated-motor-form/rated-motor-form.component.ts
- src/app/psat/explore-opportunities/explore-opportunities-form/rated-motor-form/rated-motor-form.component.html
- src/app/psat/explore-opportunities/explore-opportunities-form/rated-motor-form/rated-motor-form.component.ts
- src/app/psat/psat-warning.service.ts
- src/app/psat/psat.component.ts
> Issue 2340

- src/app/fsat/fsat-sankey/fsat-sankey.component.ts
- src/app/phast/sankey/sankey.component.ts
- src/app/psat/psat-sankey/psat-sankey.component.ts
> Fixed window location for sankey gradients

- src/app/calculator/furnaces/energy-equivalency/energy-equivalency-form/energy-equivalency-form.component.html
> Changed hp unit to kW

- src/app/calculator/furnaces/o2-enrichment/o2-enrichment-graph/o2-enrichment-graph.component.html
- src/app/calculator/furnaces/o2-enrichment/o2-enrichment-graph/o2-enrichment-graph.component.ts
- src/app/calculator/furnaces/o2-enrichment/o2-enrichment.component.html
- src/app/calculator/furnaces/o2-enrichment/o2-enrichment.service.ts
- src/app/calculator/motors/motor-performance/motor-performance-graph/motor-performance-graph.component.ts
> Issue 2297

- src/app/calculator/compressed-air/compressed-air.component.html
- src/app/sidebar/calculator-list/calculator-list.component.html
> Hid Pneumatic valve flow factor calculator

- src/app/calculator/compressed-air/pneumatic-air/pneumatic-air.component.html
- src/app/calculator/compressed-air/receiver-tank/air-capacity-form/air-capacity-form.component.html
- src/app/calculator/compressed-air/receiver-tank/air-capacity-help/air-capacity-help.component.html
connects #2397 
connects #2398
> Fixed help text for compressed air calcs

- src/app/calculator/compressed-air/receiver-tank/air-capacity-help/air-capacity-help.component.html
> Fixed typo

- src/app/report-rollup/report-rollup.component.html
> fsat summary no longer printed in rollup if no fsat assessments selected

- src/app/assessment/assessment.service.ts
- src/app/shared/models/steam/ssmt.ts
- src/app/ssmt/compare.service.ts
- src/app/ssmt/header/header-form/header-form.component.html
- src/app/ssmt/header/header-form/header-form.component.ts
- src/app/ssmt/header/header.component.html
- src/app/ssmt/header/header.component.ts
- src/app/ssmt/header/header.service.ts
- src/app/ssmt/help-panel/header-help/header-help.component.html
- src/app/ssmt/help-panel/header-help/header-help.component.spec.ts
- src/app/ssmt/help-panel/header-help/header-help.component.ts
- src/app/ssmt/help-panel/help-panel.component.html
- src/app/ssmt/help-panel/turbine-help/turbine-help.component.html
- src/app/ssmt/help-panel/turbine-help/turbine-help.component.spec.ts
- src/app/ssmt/help-panel/turbine-help/turbine-help.component.ts
- src/app/ssmt/modification-list/modification-list.component.ts
- src/app/ssmt/modify-conditions/modify-conditions-tabs/modify-conditions-tabs.component.html
- src/app/ssmt/modify-conditions/modify-conditions-tabs/modify-conditions-tabs.component.ts
- src/app/ssmt/ssmt.component.html
- src/app/ssmt/ssmt.component.ts
- src/app/ssmt/ssmt.module.ts
- src/app/ssmt/ssmt.service.ts
- src/app/ssmt/turbine/condensing-turbine-form/condensing-turbine-form.component.html
- src/app/ssmt/turbine/condensing-turbine-form/condensing-turbine-form.component.ts
- src/app/ssmt/turbine/pressure-turbine-form/pressure-turbine-form.component.html
- src/app/ssmt/turbine/pressure-turbine-form/pressure-turbine-form.component.ts
- src/app/ssmt/turbine/turbine.component.html
connects #2351 
connects #2366 
Added compare logic
Added badges to tabs
Added badges to modification list
Fixed header UI after feedback
Updated steam header input model
> Issue 2351

- src/app/calculator/pumps/pump-curve/pump-curve-graph/pump-curve-graph.component.ts
- src/app/calculator/pumps/pump-curve/pump-curve.component.ts
> Fixed pump curve/fan curve navigation bug

- src/app/ssmt/header/header-form/header-form.component.html
- src/app/ssmt/turbine/condensing-turbine-form/condensing-turbine-form.component.html
- src/app/ssmt/turbine/pressure-turbine-form/pressure-turbine-form.component.html
connects #2366 
connects #2423
> fix desuperheat temp field

- src/app/calculator/lighting/lighting-replacement/lighting-replacement.component.ts
> fix lighting bug

- src/app/calculator/compressed-air/air-velocity/air-velocity-help/air-velocity-help.component.html
- src/app/calculator/compressed-air/flow-factor/flow-factor.component.html
- src/app/calculator/compressed-air/operating-cost/operating-cost-help/operating-cost-help.component.html
- src/app/calculator/compressed-air/pipe-sizing/pipe-sizing.component.html
- src/app/calculator/compressed-air/receiver-tank/air-capacity-help/air-capacity-help.component.html
- src/app/calculator/compressed-air/receiver-tank/dedicated-storage-help/dedicated-storage-help.component.html
- src/app/calculator/compressed-air/receiver-tank/delay-method-help/delay-method-help.component.html
- src/app/calculator/compressed-air/receiver-tank/general-method-help/general-method-help.component.html
- src/app/calculator/compressed-air/receiver-tank/metered-storage-help/metered-storage-help.component.html
- src/app/calculator/compressed-air/system-capacity/system-capacity.component.html
Capitalization and grammar error corrections within Compressed Air calculators.
> Issue 2434 mark

- src/app/calculator/furnaces/o2-enrichment/o2-enrichment-form/o2-enrichment-form.component.html
- src/app/calculator/lighting/lighting-replacement/lighting-replacement-results/lighting-replacement-results.component.ts
- src/app/calculator/utilities/co2-savings/co2-savings-results/co2-savings-results.component.html
- src/app/calculator/utilities/co2-savings/co2-savings.module.ts
update sig figs
updates for prod build
> Co2 sig figs

- src/app/phast/metered-energy/metered-fuel-help/metered-fuel-help.component.html
> fixed help text

- src/app/ssmt/modify-conditions/modify-conditions.component.html
- src/app/ssmt/ssmt.component.html
> independent help and data entry scrolling

- src/app/assessment/assessment.service.ts
- src/app/fsat/fan-field-data/fan-field-data.component.ts
- src/app/psat/field-data/field-data.component.ts
connects #2430 
using electricity cost for fan and pump assessments.
> Issue 2430

- src/app/fsat/fan-setup/fan-setup.component.ts
- src/app/fsat/fsat.service.ts
> added default value for specified drive efficiency for fans

- src/app/calculator/compressed-air/pneumatic-air/pneumatic-air-form/pneumatic-air-form.component.html
- src/app/calculator/compressed-air/pneumatic-air/pneumatic-air.component.html
- src/app/calculator/standalone.service.ts
> Issue 2404

- src/app/assessment/assessment-create/assessment-create.component.css
- src/app/assessment/assessment-create/assessment-create.component.html
- src/app/ssmt/explore-opportunities/explore-opportunities-form/boiler-form/boiler-form.component.ts
- src/app/ssmt/explore-opportunities/explore-opportunities-form/explore-opportunities-form.component.ts
- src/app/ssmt/explore-opportunities/explore-opportunities-form/header-form/condensate-handling-form/condensate-handling-form.component.ts
- src/app/ssmt/explore-opportunities/explore-opportunities-form/header-form/header-form.component.ts
- src/app/ssmt/explore-opportunities/explore-opportunities-form/operations-form/operations-form.component.ts
- src/app/ssmt/explore-opportunities/explore-opportunities-form/turbine-form/explore-condensing-turbine-form/explore-condensing-turbine-form.component.html
- src/app/ssmt/explore-opportunities/explore-opportunities-form/turbine-form/explore-condensing-turbine-form/explore-condensing-turbine-form.component.ts
- src/app/ssmt/explore-opportunities/explore-opportunities-form/turbine-form/explore-pressure-turbine-form/explore-pressure-turbine-form.component.html
- src/app/ssmt/explore-opportunities/explore-opportunities-form/turbine-form/explore-pressure-turbine-form/explore-pressure-turbine-form.component.ts
- src/app/ssmt/explore-opportunities/explore-opportunities-form/turbine-form/explore-turbine-form/explore-turbine-form.component.ts
- src/app/ssmt/explore-opportunities/explore-opportunities-form/turbine-form/turbine-form.component.ts
- src/app/ssmt/ssmt-tabs/ssmt-tabs.component.html
- src/app/ssmt/ssmt-tabs/ssmt-tabs.component.ts
- src/app/ssmt/ssmt.component.ts
- src/app/ssmt/turbine/turbine.service.ts
connects #2427 
fixes various steam bugs.
> Issue 2427

- src/app/calculator/pumps/pump-curve/pump-curve.component.html
- src/app/calculator/pumps/pump-curve/pump-curve.component.ts
- src/app/calculator/pumps/system-curve/system-curve-form/system-curve-form.component.html
- src/app/calculator/pumps/system-curve/system-curve.component.ts
- src/app/fsat/fsat.component.html
- src/app/psat/psat.component.html
connects #2475 
connects #2471 
connects #2449
> Issue 2449

- src/app/fsat/fan-setup/fan-setup.component.ts
- src/app/fsat/fan-setup/fan-setup.service.ts
> Removed requirement for specified drive efficiency

- src/app/calculator/fans/fsat-203/fsat-203.component.ts
- src/app/fsat/fsat-tabs/fsat-tabs.component.html
- src/app/sidebar/calculator-list/calculator-list.component.html
connects #2470 
connects #2449
> Changed Operating Points to Fan Analysis, fixed calc bug in assessment

- src/app/calculator/pumps/pump-curve/pump-curve-data-form/pump-curve-data-form.component.html
- src/app/calculator/pumps/pump-curve/pump-curve-data-form/pump-curve-data-form.component.ts
- src/app/calculator/pumps/pump-curve/pump-curve-equation-form/pump-curve-equation-form.component.html
- src/app/calculator/pumps/pump-curve/pump-curve-equation-form/pump-curve-equation-form.component.ts
> Added maximum value to flow rates for pump and fan curve

- src/app/calculator/pumps/pump-curve/pump-curve.component.ts
- src/app/calculator/pumps/system-curve/system-curve-form/system-curve-form.component.ts
> Fixed remaining bugs in system curve drop down

- src/app/calculator/pumps/pump-curve/pump-curve-graph/pump-curve-graph.component.ts
- src/app/calculator/pumps/pump-curve/pump-curve.service.ts
> Fixed system curve table error

- main.js
- src/app/core/core.component.html
- src/app/core/core.component.ts
- src/app/update-modal/update-modal.component.html
- src/app/update-modal/update-modal.component.ts
> Issue 2267

- src/app/calculator/utilities/unit-converter/unit-converter.component.html
> added sig figs to unit converter

- src/app/calculator/steam/stack-loss/stack-loss.component.html
- src/app/calculator/steam/stack-loss/stack-loss.component.ts
> added boiler combustion efficiency

- src/app/calculator/utilities/unit-converter/unit-converter.component.html
- src/app/calculator/utilities/unit-converter/unit-converter.component.ts
- src/app/phast/phast-calculator-tabs/phast-calculator-tabs.component.html
- src/app/phast/phast-calculator-tabs/phast-calculator-tabs.component.ts
- src/app/phast/phast.component.html
- src/app/phast/phast.module.ts
- src/app/psat/psat-tabs/psat-tabs.component.html
- src/app/psat/psat.component.html
- src/app/psat/psat.module.ts
> Issue 1042 dima

- src/app/calculator/calculator.component.html
- src/app/calculator/fans/fans.component.html
- src/app/calculator/motors/motors.component.html
- src/app/calculator/utilities/utilities.component.html
connects #2496 
connects #2429
> Issue 2496

- src/app/assessment/assessment-grid-view/pre-assessment-card/pre-assessment-card.component.ts
- src/app/shared/import-export/import.service.ts
> Pre assessment card no longer automatically checked

- src/app/ssmt/modify-conditions/modify-conditions.component.html
- src/app/ssmt/modify-conditions/modify-conditions.component.ts
- src/app/ssmt/ssmt.component.ts
- src/app/ssmt/turbine/turbine.service.ts
> fix bug 2490

- src/app/calculator/pumps/pump-curve/pump-curve-graph/pump-curve-graph.component.ts
- src/app/calculator/pumps/system-curve/system-curve.service.ts
connects #2377 
connects #2521
> Issue 2377

- src/app/shared/convert-units/definitions/volume.ts
- src/app/shared/convert-units/definitions/volumeFlowRate.ts
> Issue 2260

- src/app/calculator/lighting/lighting.component.css
> add cursor pointer on hover to lighting calc

- src/app/fsat/fsat-fluid/fsat-fluid.component.html
- src/app/fsat/fsat-fluid/fsat-fluid.component.ts
- src/app/fsat/fsat-fluid/fsat-fluid.service.ts
- src/app/fsat/fsat-tabs/fsat-tabs.component.ts
- src/app/fsat/fsat-warning.service.ts
- src/app/fsat/modify-conditions/modify-conditions-tabs/modify-conditions-tabs.component.ts
> remove barometric pressure warning

- angular.json
- src/app/assessment/assessment-settings/assessment-settings.component.html
- src/app/assessment/assessment-settings/assessment-settings.component.ts
- src/app/settings/settings.module.ts
- src/app/settings/settings.service.ts
- src/app/settings/tutorial-settings/tutorial-settings.component.html
- src/app/settings/tutorial-settings/tutorial-settings.component.spec.ts
- src/app/settings/tutorial-settings/tutorial-settings.component.ts
- src/assets/styles/toggle-switch.css
> add tutorials show/hide toggle to settings

- src/app/calculator/steam/stack-loss/stack-loss.component.html
> Corrected Slack to Stack in Stack loss calc

- src/app/calculator/pumps/pump-curve/pump-curve.component.html
> Fixed pump/system curve calc names

- src/app/fsat/fsat-report/fsat-report.component.html
- src/app/fsat/fsat-report/fsat-report.component.ts
- src/app/phast/phast-report/phast-report.component.html
- src/app/phast/phast-report/phast-report.component.ts
- src/app/psat/psat-report/psat-report.component.html
- src/app/psat/psat-report/psat-report.component.ts
- src/app/psat/psat.module.ts
- src/app/report-rollup/report-rollup.component.html
- src/app/report-rollup/report-rollup.component.ts
- src/app/report-rollup/report-rollup.module.ts
- src/app/shared/print-options-menu/print-options-menu.component.css
- src/app/shared/print-options-menu/print-options-menu.component.html
- src/app/shared/print-options-menu/print-options-menu.component.spec.ts
- src/app/shared/print-options-menu/print-options-menu.component.ts
- src/app/shared/shared.module.ts
> Issue 2323

- src/app/calculator/compressed-air/compressed-air.component.html
- src/app/calculator/compressed-air/receiver-tank/receiver-tank.component.html
- src/app/calculator/compressed-air/receiver-tank/receiver-tank.component.ts
- src/app/sidebar/calculator-list/calculator-list.component.html
connects #2190 
connects #2420
> Issue 2190

- src/app/calculator/pumps/pump-curve/pump-curve-form/pump-curve-form.component.html
> Removed explore section from pump curve

- package.json
- src/app/assessment/assessment.service.ts
- src/app/calculator/fans/fsat-203/fsat-203.service.ts
- src/app/core/mockFsat.ts
- src/app/fsat/compare.service.ts
- src/app/fsat/fsat-fluid/fsat-fluid.component.ts
- src/app/fsat/fsat-fluid/fsat-fluid.service.ts
- src/app/fsat/fsat-report/input-summary/base-gas-density-summary/base-gas-density-summary.component.html
- src/app/fsat/fsat-report/input-summary/fan-motor-summary/fan-motor-summary.component.html
- src/app/fsat/fsat-report/input-summary/fan-motor-summary/fan-motor-summary.component.ts
- src/app/fsat/fsat-report/input-summary/fan-setup-summary/fan-setup-summary.component.html
- src/app/fsat/fsat-report/input-summary/fan-setup-summary/fan-setup-summary.component.ts
- src/app/fsat/fsat-report/input-summary/field-data-summary/field-data-summary.component.html
- src/app/fsat/fsat-report/input-summary/field-data-summary/field-data-summary.component.ts
- src/app/shared/models/fans.ts
connects #2513 
updated tools-suite version 0.3.3
> updates for fsat input data in report

- src/app/fsat/help-panel/fan-field-data-help/fan-field-data-help.component.html
- src/app/psat/help-panel/field-data-help/field-data-help.component.html
> Updated help text for operating hours

- src/app/fsat/fan-setup/fan-setup.component.html
- src/app/fsat/fan-setup/fan-setup.component.ts
- src/app/fsat/fsat.component.html
> Added dynamic sizing to fan type drop down

- src/app/assessment/assessment-grid-view/assessment-card/assessment-card.component.html
- src/app/assessment/assessment-grid-view/assessment-card/assessment-card.component.ts
> copy calculators when copying assessments

- src/app/fsat/fsat-tabs/fsat-tabs.component.ts
> fix issue 2551

- src/app/psat/explore-opportunities/explore-opportunities.component.ts
> fix issue 2562

- src/app/fsat/explore-opportunities/explore-opportunities-form/fan-data-form/fan-data-form.component.ts
- src/app/psat/explore-opportunities/explore-opportunities-form/pump-data-form/pump-data-form.component.ts
> fix issue 2567

- src/app/calculator/pumps/system-curve/system-curve-help/system-curve-help.component.html
> Updated fluid power note

- src/app/calculator/pumps/system-curve/system-curve.service.ts
> Fixed fluid power in pump/system curve

- src/app/psat/psat-report/psat-report-graphs/psat-report-graphs.component.ts
> Fixed psat graph bug

- src/app/psat/explore-opportunities/explore-opportunities-help/explore-opportunities-help.component.html
- src/app/psat/help-panel/pump-fluid-help/pump-fluid-help.component.html
- src/app/psat/modify-conditions/modify-conditions.component.html
> Updated explore opps help text and expert view help text

- src/app/fsat/help-panel/fan-field-data-help/fan-field-data-help.component.html
- src/app/fsat/modify-conditions/modify-field-data-form/modify-field-data-form.component.html
- src/app/fsat/modify-conditions/modify-field-data-form/modify-field-data-form.component.ts
- src/app/shared/models/fans.ts
> Removed size margin from fan expert view

- src/app/fsat/explore-opportunities/explore-opportunities-form/explore-opportunities-form.component.ts
- src/app/fsat/fan-field-data/fan-field-data.component.ts
- src/app/fsat/fan-motor/fan-motor.component.ts
- src/app/fsat/fsat-tabs/fsat-tabs.component.ts
- src/app/fsat/fsat-warning.service.ts
- src/app/fsat/fsat.service.ts
- src/app/fsat/modify-conditions/modify-conditions-tabs/modify-conditions-tabs.component.ts
- src/app/psat/explore-opportunities/explore-opportunities-form/explore-opportunities-form.component.ts
- src/app/psat/modify-conditions/modify-conditions-tabs/modify-conditions-tabs.component.ts
- src/app/psat/motor/motor.component.ts
- src/app/psat/psat-tabs/psat-tabs.component.ts
- src/app/psat/psat-warning.service.ts
> changed comparison values for motor rated power

- src/app/fsat/help-panel/fan-setup-help/fan-setup-help.component.html
- src/app/psat/explore-opportunities/explore-opportunities-help/explore-opportunities-help.component.html
- src/app/psat/help-panel/pump-fluid-help/pump-fluid-help.component.html
> fix issue 2556

- src/app/psat/psat-report/output-summary/output-summary.component.html
> fix issue 2579

- src/app/core/core.component.ts
- src/app/core/core.service.ts
- src/app/core/mockFsat.ts
- src/app/core/mockPsat.ts
> updated pump and fan examples

- package.json
- src/app/fsat/explore-opportunities/explore-opportunities-form/variable-frequency-drive-form/variable-frequency-drive-form.component.ts
- src/app/psat/psat-report/input-summary/input-summary.component.html
- src/app/version-modal/version-modal.component.html
connects #2598 
connects #2597
> Updates for prod

- src/app/fsat/fan-field-data/fan-field-data.component.ts
- src/app/fsat/fan-field-data/fan-field-data.service.ts
- src/app/fsat/fan-motor/fan-motor.component.html
- src/app/fsat/fan-motor/fan-motor.component.ts
- src/app/fsat/fan-motor/fan-motor.service.ts
- src/app/fsat/fan-setup/fan-setup.component.html
- src/app/fsat/fan-setup/fan-setup.service.ts
- src/app/fsat/fsat-fluid/fsat-fluid.service.ts
- src/app/fsat/fsat-warning.service.ts
- src/app/fsat/modify-conditions/modify-conditions-tabs/modify-conditions-tabs.component.ts
- src/app/psat/pump-fluid/pump-fluid.component.html
fixes some warning messages
disables error messages on initial setup
> Fix examples

- src/app/core/mockPsat.ts
add example boolean to psat example
> psat example fix

- src/app/core/mockPsat.ts
> Fixed system curve data for psat example

- src/app/calculator/pumps/pump-curve/pump-curve.component.ts
> Issue 2604

- package.json
Updated package.json with node.js version 8.11
> Updated node to version 8.11

- src/app/update-modal/update-modal.component.html
Changed AMO-Tools-Desktop to MEASUR in update-modal.component.html
connects #2388
> Changed AMO-Tools-Desktop to MEASUR in update-modal.component.html

- package.json
Updated Bootstrap version to 4.1.2
> Updated Bootstrap version to 4.1.2

- src/app/version-modal/version-modal.component.html
> updated release notes for v0.3.3

- src/app/about-page/about-page.component.html
Fixed About page typos
connects #2643
> Fixed About page typos

- src/app/settings/tutorial-settings/tutorial-settings.component.html
- src/app/settings/tutorial-settings/tutorial-settings.component.ts
*Adds Show/Hide Tutorial button in settings
connects #2606
> Adds Show/Hide Tutorial button in settings

- src/app/dashboard/dashboard.component.html
Removed random line from the middle of the delete selected items dialog box
connects #2654
> Removed random line from the middle of the delete selected items dialog box

- src/app/calculator/furnaces/o2-enrichment/o2-enrichment-graph/o2-enrichment-graph.component.ts
- src/app/calculator/motors/motor-drive/motor-drive-graph/motor-drive-graph.component.ts
- src/app/calculator/motors/motor-performance/motor-performance-graph/motor-performance-graph.component.ts
- src/app/calculator/pumps/achievable-efficiency/achievable-efficiency-graph/achievable-efficiency-graph.component.ts
- src/app/calculator/pumps/pump-curve/pump-curve-graph/pump-curve-graph.component.ts
- src/app/calculator/pumps/specific-speed/specific-speed-graph/specific-speed-graph.component.ts
- src/app/calculator/pumps/system-curve/system-curve-graph/system-curve-graph.component.ts
- src/app/calculator/steam/saturated-properties/saturated-properties-graph/saturated-properties-graph.component.ts
- src/app/calculator/steam/steam-properties/steam-properties-graph/steam-properties-graph.component.ts
- src/app/calculator/utilities/cash-flow/cash-flow-diagram/cash-flow-diagram.component.ts
- src/app/shared/line-chart-helper/line-chart-helper.service.ts
Added Esc Functionality to close modal graphs for:
*Motor drive
*Pumps- System Curve
*Specific Speed
*Pump Effientcy Curve
*Pump Curve
*Fans-System Curve
*Fan Curve
*O2 enrichment
*Steam Properties
*Saturated Properties
*Cash Flow Diagram
connects #2209
> Added Esc Functionality to close modal graphs

- src/app/calculator/motors/replace-existing/replace-existing-results/replace-existing-results.component.html
- src/app/shared/exportable-table/exportable-table.component.css
- src/app/shared/exportable-table/exportable-table.component.html
- src/app/shared/exportable-table/exportable-table.component.ts
- src/app/shared/line-chart-helper/line-chart-helper.service.ts
> Updated exportable table styling, added dot labels to clickable graphs

- src/app/about-page/about-page.component.html
- src/app/calculator/compressed-air/bag-method/bag-method.component.html
- src/app/calculator/compressed-air/compressed-air.component.html
- src/app/calculator/compressed-air/operating-cost/operating-cost-help/operating-cost-help.component.html
- src/app/calculator/compressed-air/pipe-sizing/pipe-sizing.component.html
- src/app/calculator/fans/fans.component.html
- src/app/calculator/fans/fsat-203/fsat-203.component.html
- src/app/calculator/fans/fsat-203/operating-points-help/fan-data-help/fan-data-help.component.html
- src/app/calculator/fans/fsat-203/operating-points-help/gas-density-help/gas-density-help.component.html
- src/app/calculator/lighting/lighting-replacement/lighting-replacement-help/lighting-replacement-help.component.html
- src/app/calculator/motors/motors.component.html
- src/app/calculator/motors/replace-rewind/replace-rewind-help/replace-rewind-help.component.html
- src/app/calculator/pumps/achievable-efficiency/achievable-efficiency.component.html
- src/app/calculator/pumps/head-tool/head-tool-help/head-tool-help.component.html
- src/app/calculator/pumps/pumps.component.html
- src/app/calculator/pumps/system-curve/system-curve-help/system-curve-help.component.html
- src/app/calculator/steam/flash-tank/flash-tank-help/flash-tank-help.component.html
- src/app/calculator/steam/stack-loss/stack-loss-help/stack-loss-help.component.html
- src/app/calculator/utilities/cash-flow/cash-flow-help/cash-flow-help.component.html
- src/app/calculator/utilities/co2-savings/co2-savings-help/co2-savings-help.component.html
- src/app/calculator/utilities/combined-heat-power/combined-heat-power-help/combined-heat-power-help.component.html
- src/app/calculator/utilities/utilities.component.html
- src/app/fsat/help-panel/fan-field-data-help/fan-field-data-help.component.html
- src/app/fsat/help-panel/fan-motor-help/fan-motor-help.component.html
- src/app/fsat/help-panel/fan-setup-help/fan-setup-help.component.html
- src/app/fsat/help-panel/fsat-fluid-help/fsat-fluid-help.component.html
- src/app/update-modal/update-modal.component.html
Fixed typos, punctuation issues, fixed some sentence structure issues, and cleaned up portions of the code for easier readability
> Fixed some typos and sentence structure

- src/app/shared/models/steam/steam-outputs.ts
- src/app/ssmt/ssmt-calculations/calculate-model.service.ts
Updates to the output object to match calculation service
> updated output object, added heat exchanger output object

- src/app/landing-screen/landing-screen.component.html
> Added Lighting calculator to home screen

- src/app/about-page/about-page.component.ts
- src/app/calculator/compressed-air/air-velocity/air-velocity-help/air-velocity-help.component.html
- src/app/calculator/compressed-air/receiver-tank/dedicated-storage-help/dedicated-storage-help.component.html
- src/app/calculator/compressed-air/receiver-tank/receiver-tank.component.html
- src/app/calculator/compressed-air/system-capacity/system-capacity.component.html
- src/app/calculator/fans/fan-efficiency/fan-efficiency-help/fan-efficiency-help.component.html
- src/app/calculator/fans/fsat-203/fsat-203-results/fsat-203-results.component.html
- src/app/calculator/furnaces/energy-equivalency/energy-equivalency-help/energy-equivalency-help.component.html
- src/app/calculator/furnaces/o2-enrichment/o2-enrichment-help/o2-enrichment-help.component.html
- src/app/calculator/pumps/head-tool/head-tool-help/head-tool-help.component.html
- src/app/fsat/help-panel/fan-field-data-help/fan-field-data-help.component.html
- src/app/fsat/help-panel/fan-motor-help/fan-motor-help.component.html
- src/app/phast/losses/losses-help/auxiliary-power-losses-help/auxiliary-power-losses-help.component.html
- src/app/phast/metered-energy/metered-fuel-help/metered-fuel-help.component.html
- src/app/phast/metered-energy/metered-steam-help/metered-steam-help.component.html
- src/app/phast/phast-report/phast-input-summary/phast-input-summary.component.html
- src/app/psat/explore-opportunities/explore-opportunities-help/explore-opportunities-help.component.html
- src/app/psat/psat.component.html
- src/app/suiteDb/atmosphere-specific-heat-material/atmosphere-specific-heat-material.component.html
- src/app/suiteDb/flue-gas-material/flue-gas-material.component.html
- src/app/suiteDb/gas-load-charge-material/gas-load-charge-material.component.html
- src/app/suiteDb/liquid-load-charge-material/liquid-load-charge-material.component.html
- src/app/suiteDb/solid-liquid-flue-gas-material/solid-liquid-flue-gas-material.component.html
- src/app/suiteDb/solid-load-charge-material/solid-load-charge-material.component.html
- src/app/suiteDb/wall-losses-surface/wall-losses-surface.component.html
- src/app/tutorials/phast-assessment-tutorial/phast-assessment-tutorial.component.html
- src/app/update-modal/update-modal.component.html
Modified Help text note for o2 enrichment and removed the note from energy equivalency help, also more typo fixes
connects #1629
> PH Calculator Help text

- src/app/ssmt/ssmt.component.ts
quick fix for breaking bug in steam
> fix console log bug

- src/app/shared/models/steam/steam-outputs.ts
- src/app/ssmt/ssmt-calculations/calculate-model.service.ts
- src/app/ssmt/ssmt-diagram-tab/cost-table/cost-table.component.html
- src/app/ssmt/ssmt-diagram-tab/cost-table/cost-table.component.ts
- src/app/ssmt/ssmt-diagram-tab/ssmt-diagram-tab.component.html
- src/app/ssmt/ssmt.component.ts
> calculate marginal costs working

- src/app/calculator/steam/boiler/boiler.component.ts
- src/app/calculator/steam/deaerator/deaerator.component.ts
- src/app/calculator/steam/flash-tank/flash-tank.component.ts
- src/app/calculator/steam/header/header.component.ts
- src/app/calculator/steam/heat-loss/heat-loss.component.ts
- src/app/calculator/steam/prv/prv.component.ts
- src/app/calculator/steam/saturated-properties/saturated-properties.component.ts
- src/app/calculator/steam/stack-loss/stack-loss.component.ts
- src/app/calculator/steam/steam-properties/steam-properties.component.ts
- src/app/calculator/steam/steam.component.html
- src/app/calculator/steam/turbine/turbine.component.ts
- src/app/ssmt/ssmt-tabs/ssmt-tabs.component.html
- src/app/ssmt/ssmt-tabs/ssmt-tabs.component.ts
- src/app/ssmt/ssmt.component.html
- src/app/ssmt/ssmt.component.ts
- src/app/ssmt/ssmt.module.ts
- src/app/ssmt/ssmt.service.ts
> added calculators to ssmt

- src/app/calculator/motors/replace-existing/replace-existing-form/replace-existing-form.component.html
- src/app/calculator/motors/replace-existing/replace-existing-form/replace-existing-form.component.ts
- src/app/calculator/motors/replace-existing/replace-existing.component.html
- src/app/calculator/motors/replace-existing/replace-existing.component.ts
- src/app/calculator/motors/replace-existing/replace-existing.service.ts
- src/app/calculator/motors/replace-rewind/replace-rewind.component.ts
> Issue 2657

- src/app/app.component.css
- src/app/calculator/steam/boiler/boiler.component.html
- src/app/calculator/steam/deaerator/deaerator.component.html
- src/app/calculator/steam/flash-tank/flash-tank.component.html
- src/app/calculator/steam/header/header.component.html
- src/app/calculator/steam/heat-loss/heat-loss.component.html
- src/app/calculator/steam/prv/prv.component.html
- src/app/calculator/steam/saturated-properties/saturated-properties.component.html
- src/app/calculator/steam/stack-loss/stack-loss.component.html
- src/app/calculator/steam/steam-properties/steam-properties.component.html
- src/app/calculator/steam/turbine/turbine.component.html
- src/app/calculator/utilities/pre-assessment/pre-assessment.component.html
- src/app/phast/help-panel/help-panel.component.html
> Fixed Icon color of motor calculators and pre-assessment calculator

- src/app/ssmt/explore-opportunities/explore-opportunities-form/turbine-form/turbine-form.component.html
> fixed turbine logic in explore opps for steam assessment

- src/app/ssmt/ssmt-report/ssmt-report.component.html
- src/app/ssmt/ssmt-report/ssmt-report.module.ts
> added facility info to ssmt report

- src/app/shared/models/steam/steam-outputs.ts
- src/app/ssmt/ssmt-calculations/calculate-model.service.ts
- src/app/ssmt/ssmt-diagram-tab/cost-table/cost-table.component.html
- src/app/ssmt/ssmt-diagram-tab/ssmt-diagram-tab.component.ts
- src/app/ssmt/ssmt-report/energy-summary/energy-summary.component.html
- src/app/ssmt/ssmt-report/energy-summary/energy-summary.component.ts
- src/app/ssmt/ssmt-report/ssmt-report.component.html
- src/app/ssmt/ssmt-report/ssmt-report.component.ts
- src/app/ssmt/ssmt-report/ssmt-report.module.ts
connects #2702 
connects #2620
> modify conditions calculations and energy summary report

- src/app/ssmt/ssmt-diagram-tab/ssmt-diagram-tab.component.css
- src/app/ssmt/ssmt-diagram-tab/ssmt-diagram-tab.component.html
- src/app/ssmt/ssmt-diagram-tab/ssmt-diagram-tab.component.ts
connects #2723 
merge #2722 first please
> Issue 2723

- src/app/calculator/pumps/pump-curve/pump-curve.component.ts
- src/app/calculator/pumps/system-curve/system-curve.component.ts
> Fixed fluid power calculation and conversion in system curve

- src/app/calculator/compressed-air/compressed-air.component.html
- src/app/calculator/compressed-air/system-capacity/system-capacity-form/system-capacity-form.component.html
- src/app/calculator/compressed-air/system-capacity/system-capacity-form/system-capacity-form.component.ts
- src/app/calculator/compressed-air/system-capacity/system-capacity.component.html
- src/app/calculator/compressed-air/system-capacity/system-capacity.component.ts
Changed Compressed air help text and help text switching functionality depending on what input was clicked
connects #2308
> Changed Compressed air help text and help text switching functionality

- src/app/calculator/fans/fsat-203/fan-shaft-power/fan-shaft-power.component.html
- src/app/calculator/fans/fsat-203/fan-shaft-power/fan-shaft-power.component.ts
- src/app/calculator/fans/fsat-203/fsat-203.component.ts
- src/app/calculator/fans/fsat-203/fsat-203.service.ts
> fixed convergence bug in fan analysis calculation

- src/app/ssmt/ssmt-diagram-tab/ssmt-diagram-tab.component.html
- src/app/ssmt/ssmt-diagram-tab/ssmt-diagram-tab.component.ts
- src/app/ssmt/ssmt-report/ssmt-report.component.html
- src/app/ssmt/ssmt-report/ssmt-report.component.ts
> calculation spinner for ssmt diagram and report

- src/app/settings/steam-settings/steam-settings.component.html
- src/app/settings/steam-settings/steam-settings.component.ts
- src/app/shared/convert-units/definitions/power.ts
> updated unit options for steam

- src/app/shared/pipes/settings-label.pipe.ts
- src/app/ssmt/boiler/boiler.component.html
- src/app/ssmt/explore-opportunities/explore-opportunities-form/boiler-form/boiler-form.component.html
- src/app/ssmt/explore-opportunities/explore-opportunities-form/header-form/condensate-handling-form/condensate-handling-form.component.html
- src/app/ssmt/explore-opportunities/explore-opportunities-form/header-form/header-form.component.html
- src/app/ssmt/explore-opportunities/explore-opportunities-form/operations-form/operations-form.component.html
- src/app/ssmt/explore-opportunities/explore-opportunities-form/turbine-form/explore-condensing-turbine-form/explore-condensing-turbine-form.component.html
- src/app/ssmt/explore-opportunities/explore-opportunities-form/turbine-form/explore-pressure-turbine-form/explore-pressure-turbine-form.component.html
- src/app/ssmt/explore-opportunities/explore-opportunities.module.ts
- src/app/ssmt/header/header-form/header-form.component.html
- src/app/ssmt/operations/general-operations/general-operations.component.html
- src/app/ssmt/operations/operations.module.ts
- src/app/ssmt/turbine/condensing-turbine-form/condensing-turbine-form.component.html
- src/app/ssmt/turbine/pressure-turbine-form/pressure-turbine-form.component.html
> update unit displays to use settings pipe in ssmt

- src/app/shared/models/steam/steam-outputs.ts
- src/app/ssmt/explore-opportunities/explore-opportunities.component.html
- src/app/ssmt/explore-opportunities/explore-opportunities.module.ts
- src/app/ssmt/help-panel/help-panel.component.html
- src/app/ssmt/help-panel/help-panel.module.ts
- src/app/ssmt/ssmt-calculations/calculate-losses.service.ts
- src/app/ssmt/ssmt-report/ssmt-report.component.ts
- src/app/ssmt/ssmt-results-panel/ssmt-results-panel.module.spec.ts
- src/app/ssmt/ssmt-results-panel/ssmt-results-panel.module.ts
- src/app/ssmt/ssmt-results-panel/ssmt-results-panel/ssmt-results-panel.component.css
- src/app/ssmt/ssmt-results-panel/ssmt-results-panel/ssmt-results-panel.component.html
- src/app/ssmt/ssmt-results-panel/ssmt-results-panel/ssmt-results-panel.component.spec.ts
- src/app/ssmt/ssmt-results-panel/ssmt-results-panel/ssmt-results-panel.component.ts
> Issue 2738

- src/app/app.component.css
- src/app/shared/percent-graph/percent-graph.component.html
- src/app/shared/percent-graph/percent-graph.component.ts
- src/app/ssmt/boiler/boiler.component.ts
- src/app/ssmt/explore-opportunities/explore-opportunities-help/explore-opportunities-help.component.ts
- src/app/ssmt/explore-opportunities/explore-opportunities.component.html
- src/app/ssmt/ssmt-banner/ssmt-banner.component.html
- src/app/ssmt/ssmt-calculations/calculate-model.service.ts
- src/app/ssmt/ssmt-report/energy-summary/energy-summary.component.html
- src/app/ssmt/ssmt-report/energy-summary/energy-summary.component.ts
- src/app/ssmt/ssmt-report/executive-summary/executive-summary.component.html
- src/app/ssmt/ssmt-report/executive-summary/executive-summary.component.ts
- src/app/ssmt/ssmt-report/losses-summary/losses-summary.component.html
- src/app/ssmt/ssmt-report/losses-summary/losses-summary.component.ts
- src/app/ssmt/ssmt-report/ssmt-report.component.html
- src/app/ssmt/ssmt-report/ssmt-report.component.ts
- src/app/ssmt/ssmt-results-panel/ssmt-results-panel/ssmt-results-panel.component.html
- src/assets/styles/utilities.css
> Issue 2756

- src/app/ssmt/ssmt-diagram-tab/ssmt-diagram-tab.component.css
- src/app/ssmt/ssmt-diagram-tab/ssmt-diagram-tab.component.html
- src/app/ssmt/ssmt-diagram-tab/ssmt-diagram-tab.component.ts
- src/app/ssmt/ssmt-diagram-tab/ssmt-diagram-tab.module.ts
- src/app/ssmt/ssmt-diagram/hover-table/default-summary-table/default-summary-table.component.html
- src/app/ssmt/ssmt-diagram/hover-table/hover-blowdown-table/hover-blowdown-table.component.html
- src/app/ssmt/ssmt-diagram/hover-table/hover-boiler-table/hover-boiler-table.component.html
- src/app/ssmt/ssmt-diagram/hover-table/hover-condensate-table/hover-condensate-table.component.html
- src/app/ssmt/ssmt-diagram/hover-table/hover-deaerator-table/hover-deaerator-table.component.html
- src/app/ssmt/ssmt-diagram/hover-table/hover-flash-tank-table/hover-flash-tank-table.component.html
- src/app/ssmt/ssmt-diagram/hover-table/hover-header-table/hover-header-table.component.html
- src/app/ssmt/ssmt-diagram/hover-table/hover-makeup-water/hover-makeup-water.component.html
- src/app/ssmt/ssmt-diagram/hover-table/hover-process-usage/hover-process-usage.component.html
- src/app/ssmt/ssmt-diagram/hover-table/hover-prv-table/hover-prv-table.component.html
- src/app/ssmt/ssmt-diagram/hover-table/hover-steam-properties/hover-steam-properties.component.html
- src/app/ssmt/ssmt-diagram/hover-table/hover-table.component.html
- src/app/ssmt/ssmt-diagram/hover-table/hover-turbine-table/hover-turbine-table.component.html
- src/app/ssmt/ssmt-diagram/ssmt-diagram.component.html
- src/app/ssmt/ssmt-report/losses-summary/losses-summary.component.html
- src/app/ssmt/ssmt-report/losses-summary/losses-summary.component.ts
- src/app/ssmt/ssmt-report/report-diagram/report-diagram.component.css
- src/app/ssmt/ssmt-report/report-diagram/report-diagram.component.html
- src/app/ssmt/ssmt-report/report-diagram/report-diagram.component.ts
- src/app/ssmt/ssmt-report/ssmt-report.component.html
- src/app/ssmt/ssmt.component.css
- src/app/ssmt/ssmt.component.html
- src/assets/styles/ssmt-diagram.css
connects #2759 
connects #2619
> Issue 2759

- src/app/calculator/steam/steam.service.ts
> added ideal turbine calculation

- src/app/ssmt/ssmt-calculations/calculate-model.service.ts
- src/app/ssmt/ssmt-report/losses-summary/losses-summary.component.html
connects #2624 
connects #2774
> Issue 2624 fix

- src/app/assessment/assessment-grid-view/assessment-card/assessment-card.component.html
- src/app/assessment/assessment-grid-view/assessment-card/ssmt-summary-card/ssmt-summary-card.component.css
- src/app/assessment/assessment-grid-view/assessment-card/ssmt-summary-card/ssmt-summary-card.component.html
- src/app/assessment/assessment-grid-view/assessment-card/ssmt-summary-card/ssmt-summary-card.component.spec.ts
- src/app/assessment/assessment-grid-view/assessment-card/ssmt-summary-card/ssmt-summary-card.component.ts
- src/app/assessment/assessment-grid-view/directory-card/directory-card.component.html
- src/app/assessment/assessment-list-view/assessment-list-item/assessment-list-item.component.html
- src/app/assessment/assessment-list-view/assessment-list-item/assessment-list-item.component.ts
- src/app/assessment/assessment.module.ts
- src/app/assessment/folder-summary/folder-summary.component.html
- src/app/assessment/folder-summary/folder-summary.component.ts
- src/app/shared/models/steam/ssmt.ts
- src/app/ssmt/explore-opportunities/explore-opportunities-form/explore-opportunities-form.component.ts
- src/app/ssmt/modify-conditions/modify-conditions.component.ts
- src/app/ssmt/ssmt-calculations/calculate-model.service.ts
- src/app/ssmt/ssmt-diagram-tab/cost-table/cost-table.component.css
- src/app/ssmt/ssmt-diagram-tab/cost-table/cost-table.component.html
- src/app/ssmt/ssmt-diagram-tab/cost-table/cost-table.component.ts
- src/app/ssmt/ssmt-diagram-tab/ssmt-diagram-tab.component.html
- src/app/ssmt/ssmt-diagram-tab/ssmt-diagram-tab.component.ts
- src/app/ssmt/ssmt-report/ssmt-report.component.ts
- src/app/ssmt/ssmt-results-panel/ssmt-results-panel/ssmt-results-panel.component.html
- src/app/ssmt/ssmt-results-panel/ssmt-results-panel/ssmt-results-panel.component.ts
- src/app/ssmt/ssmt.component.html
- src/app/ssmt/ssmt.component.ts
- src/app/ssmt/ssmt.service.ts
> Issue 2358

- src/app/calculator/compressed-air/bag-method/bag-method.component.html
> Added Trash bag help text in bag method help

- src/app/calculator/steam/boiler/boiler-results/boiler-results.component.html
- src/app/calculator/steam/deaerator/deaerator-results/deaerator-results.component.html
- src/app/calculator/steam/flash-tank/flash-tank-results/flash-tank-results.component.html
- src/app/calculator/steam/header/header-results/header-results.component.html
- src/app/calculator/steam/prv/prv-results/prv-results.component.html
- src/app/calculator/steam/turbine/turbine-results/turbine-results.component.html
> move steam table units to label

- src/app/calculator/steam/boiler/boiler-results/boiler-results.component.html
- src/app/calculator/steam/deaerator/deaerator-results/deaerator-results.component.html
- src/app/calculator/steam/flash-tank/flash-tank-results/flash-tank-results.component.html
- src/app/calculator/steam/header/header-results/header-results.component.html
- src/app/calculator/steam/prv/prv-results/prv-results.component.html
- src/app/calculator/steam/turbine/turbine-results/turbine-results.component.html
- src/app/fsat/system-basics/system-basics.component.ts
- src/app/ssmt/convert-ssmt.service.spec.ts
- src/app/ssmt/convert-ssmt.service.ts
- src/app/ssmt/ssmt.module.ts
- src/app/ssmt/system-basics/system-basics.component.ts
> Issue 2771

- src/app/ssmt/boiler/boiler.component.ts
- src/app/ssmt/compare.service.ts
- src/app/ssmt/header/header.component.ts
- src/app/ssmt/modification-list/modification-list.component.ts
- src/app/ssmt/modify-conditions/modify-conditions.component.html
- src/app/ssmt/operations/operations.component.ts
- src/app/ssmt/ssmt-tabs/ssmt-tabs.component.ts
- src/app/ssmt/ssmt.component.html
- src/app/ssmt/ssmt.component.ts
- src/app/ssmt/turbine/turbine.component.ts
connects #2735 
connects #2773 (I think these updates will fix this bug)
> Issue 2735

- src/app/ssmt/ssmt-report/energy-summary/energy-summary.component.html
- src/app/ssmt/ssmt-report/energy-summary/energy-summary.component.ts
- src/app/ssmt/ssmt-report/executive-summary/executive-summary.component.html
- src/app/ssmt/ssmt-report/input-summary/boiler-summary/boiler-summary.component.css
- src/app/ssmt/ssmt-report/input-summary/boiler-summary/boiler-summary.component.html
- src/app/ssmt/ssmt-report/input-summary/boiler-summary/boiler-summary.component.ts
- src/app/ssmt/ssmt-report/input-summary/header-summary/header-input-table/header-input-table.component.html
- src/app/ssmt/ssmt-report/input-summary/header-summary/header-input-table/header-input-table.component.ts
- src/app/ssmt/ssmt-report/input-summary/header-summary/header-summary.component.css
- src/app/ssmt/ssmt-report/input-summary/header-summary/header-summary.component.html
- src/app/ssmt/ssmt-report/input-summary/header-summary/header-summary.component.ts
- src/app/ssmt/ssmt-report/input-summary/input-summary.component.html
- src/app/ssmt/ssmt-report/input-summary/operations-summary/operations-summary.component.css
- src/app/ssmt/ssmt-report/input-summary/operations-summary/operations-summary.component.html
- src/app/ssmt/ssmt-report/input-summary/operations-summary/operations-summary.component.ts
- src/app/ssmt/ssmt-report/input-summary/turbine-summary/turbine-input-table/turbine-input-table.component.html
- src/app/ssmt/ssmt-report/input-summary/turbine-summary/turbine-input-table/turbine-input-table.component.ts
- src/app/ssmt/ssmt-report/input-summary/turbine-summary/turbine-summary.component.css
- src/app/ssmt/ssmt-report/input-summary/turbine-summary/turbine-summary.component.html
- src/app/ssmt/ssmt-report/input-summary/turbine-summary/turbine-summary.component.ts
- src/app/ssmt/ssmt-report/losses-summary/losses-summary.component.html
- src/app/ssmt/ssmt-report/losses-summary/losses-summary.component.ts
- src/app/ssmt/ssmt-results-panel/ssmt-results-panel/ssmt-results-panel.component.html
> Issue 2797

- src/app/ssmt/ssmt-calculations/calculate-model.service.ts
- src/app/ssmt/ssmt-diagram/hover-table/hover-condensate-table/hover-condensate-table.component.ts
connects #2647 
connects #2782
> Issue 2647

- src/app/fsat/fan-setup/fan-setup.component.ts
- src/app/fsat/fsat.service.ts
Resolves issue 323 made for the suite, but was actually a bug on the desktop side.
> Fixed faulty logic causing fan drive efficiency bug

- src/app/shared/shared.module.ts
- src/app/shared/waterfall-graph/waterfall-graph.component.css
- src/app/shared/waterfall-graph/waterfall-graph.component.html
- src/app/shared/waterfall-graph/waterfall-graph.component.ts
- src/app/shared/waterfall-graph/waterfall-graph.service.spec.ts
- src/app/shared/waterfall-graph/waterfall-graph.service.ts
- src/app/ssmt/ssmt-report/report-graphs/report-graphs.component.html
- src/app/ssmt/ssmt-report/report-graphs/report-graphs.component.ts
- src/app/ssmt/ssmt-report/ssmt-report.component.html
> Issue 2621 waterfall

- src/app/ssmt/convert-ssmt.service.ts
- src/app/ssmt/ssmt-calculations/calculate-model.service.ts
- src/app/ssmt/system-basics/system-basics.component.ts
> fix unit conversions for ssmt inputs

- src/app/ssmt/compare.service.ts
> fix header compare badge'

- src/app/ssmt/explore-opportunities/explore-opportunities-help/explore-opportunities-help.component.html
Added Explore Opportunities help text for SSMT
connects #2757
> Added Explore Opportunities help text for SSMT

- src/app/ssmt/ssmt-diagram-tab/diagram-help/diagram-help.component.html
Added steam diagram help text
connects #2707
> Added steam diagram help text

- src/app/assessment/assessment-grid-view/assessment-card/ssmt-summary-card/ssmt-summary-card.component.ts
- src/app/assessment/folder-summary/folder-summary.component.ts
- src/app/ssmt/ssmt-calculations/calculate-losses.service.ts
> fixed 2771

- src/app/ssmt/ssmt-calculations/calculate-losses.service.ts
> fixed condensing losses conversion

- src/app/ssmt/boiler/boiler.component.html
- src/app/ssmt/boiler/boiler.component.ts
- src/app/ssmt/boiler/boiler.service.ts
- src/app/ssmt/convert-ssmt.service.ts
> Issue 2828

- src/app/ssmt/explore-opportunities/explore-opportunities-form/turbine-form/explore-condensing-turbine-form/explore-condensing-turbine-form.component.html
- src/app/ssmt/explore-opportunities/explore-opportunities-form/turbine-form/explore-condensing-turbine-form/explore-condensing-turbine-form.component.ts
- src/app/ssmt/explore-opportunities/explore-opportunities-form/turbine-form/explore-pressure-turbine-form/explore-pressure-turbine-form.component.html
- src/app/ssmt/explore-opportunities/explore-opportunities-form/turbine-form/explore-pressure-turbine-form/explore-pressure-turbine-form.component.ts
- src/app/ssmt/explore-opportunities/explore-opportunities-form/turbine-form/explore-turbine-form/explore-turbine-form.component.html
- src/app/ssmt/explore-opportunities/explore-opportunities-form/turbine-form/explore-turbine-form/explore-turbine-form.component.ts
> updates for 2772

- src/app/contact-page/contact-page.component.html
- src/app/sidebar/sidebar.component.html
> Added feedback text

- src/app/calculator/steam/boiler/boiler-results/boiler-results.component.html
- src/app/calculator/steam/deaerator/deaerator-results/deaerator-results.component.html
- src/app/calculator/steam/flash-tank/flash-tank-results/flash-tank-results.component.html
- src/app/calculator/steam/header/header-results/header-results.component.html
- src/app/calculator/steam/heat-loss/heat-loss-results/heat-loss-results.component.html
- src/app/calculator/steam/prv/prv-results/prv-results.component.html
- src/app/calculator/steam/turbine/turbine-results/turbine-results.component.html
- src/app/shared/convert-units/definitions/mass.ts
- src/app/ssmt/ssmt-diagram/hover-table/hover-steam-properties/hover-steam-properties.component.html
- src/app/ssmt/ssmt-diagram/hover-table/hover-steam-properties/hover-steam-properties.component.ts
- src/app/ssmt/ssmt-diagram/hover-table/hover-table.component.html
- src/app/ssmt/ssmt-diagram/makeup-water-diagram/makeup-water-diagram.component.html
- src/app/ssmt/ssmt-report/losses-summary/losses-summary.component.html
> 2775 fixes

- package.json
- src/app/core/core.component.css
- src/app/core/core.component.html
- src/app/core/core.component.ts
> Issue 2838

- src/app/core/core.component.html
- src/app/core/core.component.ts
> destroy survey on hide

- src/app/ssmt/ssmt-diagram/blowdown-flash-tank/blowdown-flash-tank.component.css
- src/app/ssmt/ssmt-diagram/blowdown-flash-tank/blowdown-flash-tank.component.html
- src/app/ssmt/ssmt-diagram/boiler-diagram/boiler-diagram.component.css
- src/app/ssmt/ssmt-diagram/condensate-flash-tank/condensate-flash-tank.component.css
- src/app/ssmt/ssmt-diagram/deaerator-diagram/deaerator-diagram.component.css
- src/app/ssmt/ssmt-diagram/feedwater-diagram/feedwater-diagram.component.css
- src/app/ssmt/ssmt-diagram/flash-tank-diagram/flash-tank-diagram.component.css
- src/app/ssmt/ssmt-diagram/flash-tank-diagram/flash-tank-diagram.component.html
- src/app/ssmt/ssmt-diagram/header-diagram/header-diagram.component.css
- src/app/ssmt/ssmt-diagram/return-condensate-connector/return-condensate-connector.component.css
- src/app/ssmt/ssmt-diagram/return-condensate-header/return-condensate-header.component.css
- src/app/ssmt/ssmt-diagram/return-condensate-header/return-condensate-header.component.html
> steam diagram visual updates

- src/app/shared/waterfall-graph/waterfall-graph.service.ts
- src/app/ssmt/ssmt-report/report-graphs/report-graphs.component.ts
- src/app/ssmt/ssmt-report/report-graphs/report-graphs.service.ts
> Fixed waterfall numbers, added appropriate units

- src/app/shared/models/steam/steam-outputs.ts
- src/app/ssmt/ssmt-calculations/calculate-losses.service.ts
- src/app/ssmt/ssmt-report/losses-summary/losses-summary.component.html
- src/app/ssmt/ssmt-report/losses-summary/losses-summary.component.ts
> added useful energy to losses table

- src/app/assessment/reset-data-modal/reset-data-modal.component.ts
- src/app/core/core.service.ts
- src/app/core/mockSsmt.ts
- src/app/indexedDb/assessment-db.service.ts
- src/app/shared/models/steam/ssmt.ts
- src/app/shared/models/steam/steam-outputs.ts
> add example ssmt

- src/app/update-modal/update-modal.component.ts
> add timer for download

- package.json
- src/app/version-modal/version-modal.component.html
> added release notes and updates version

- src/app/core/core.component.html
> update survey text

- src/app/contact-page/contact-page.component.html
> updated feedback page

- src/app/ssmt/help-panel/boiler-help/boiler-help.component.html
- src/app/ssmt/help-panel/turbine-help/turbine-help.component.html
> Issue 2827

- src/app/calculator/pumps/pump-curve/pump-curve.component.html
> Hid pump curve equation when pump curve is hidden

- src/app/calculator/utilities/utilities.component.html
> Changed description of combined heat and power calculator

- src/app/ssmt/explore-opportunities/explore-opportunities-form/header-form/header-form.component.ts
- src/app/ssmt/header/header-form/header-form.component.html
- src/app/ssmt/header/header.component.ts
- src/app/ssmt/header/header.service.ts
- src/app/ssmt/modify-conditions/modify-conditions-tabs/modify-conditions-tabs.component.ts
- src/app/ssmt/modify-conditions/modify-conditions.component.html
- src/app/ssmt/ssmt-calculations/calculate-losses.service.ts
- src/app/ssmt/ssmt-calculations/calculate-model.service.ts
- src/app/ssmt/ssmt-tabs/ssmt-tabs.component.ts
- src/app/ssmt/ssmt.component.html
- src/app/ssmt/ssmt.component.ts
> Issue 2791

- src/app/ssmt/ssmt-report/executive-summary/executive-summary.component.html
> Added back $K/Year

- src/app/calculator/lighting/lighting-replacement/lighting-replacement-results/lighting-replacement-results.component.html
- src/app/calculator/lighting/lighting-replacement/lighting-replacement-results/lighting-replacement-results.component.ts
- src/app/calculator/lighting/lighting-replacement/lighting-replacement.component.css
- src/app/calculator/lighting/lighting-replacement/lighting-replacement.component.html
- src/app/calculator/lighting/lighting-replacement/lighting-replacement.component.ts
- src/app/calculator/lighting/lighting-replacement/lighting-replacement.service.ts
- src/app/shared/models/lighting.ts
- src/app/shared/models/treasure-hunt.ts
- src/app/treasure-hunt/find-treasure/find-treasure.component.html
- src/app/treasure-hunt/treasure-chest/lighting-replacement-card/lighting-replacement-card.component.html
- src/app/treasure-hunt/treasure-chest/lighting-replacement-card/lighting-replacement-card.component.ts
- src/app/treasure-hunt/treasure-chest/treasure-chest.component.html
- src/app/treasure-hunt/treasure-chest/treasure-chest.component.ts
> added electricity costs to lighting calculator and treasure hunt results

- src/app/assessment/assessment-grid-view/assessment-card/ssmt-summary-card/ssmt-summary-card.component.ts
- src/app/assessment/reset-data-modal/reset-data-modal.component.ts
- src/app/core/core.service.ts
Fix for reset data bug involving settings
> reset steam data fixed

- src/app/shared/validators/greater-than.ts
- src/app/ssmt/boiler/boiler.component.html
- src/app/ssmt/boiler/boiler.component.ts
- src/app/ssmt/header/header-form/header-form.component.html
- src/app/ssmt/header/header-form/header-form.component.ts
- src/app/ssmt/header/header.component.html
- src/app/ssmt/header/header.component.ts
- src/app/ssmt/header/header.service.ts
- src/app/ssmt/modify-conditions/modify-conditions.component.html
- src/app/ssmt/ssmt.component.html
> fix deaerator pressure warning for header

- src/app/calculator/pumps/pump-curve/pump-curve-equation-form/pump-curve-equation-form.component.html
> Repair pump curve by equation

- src/app/assessment/assessment-settings/assessment-settings.component.html
- src/app/settings/application-settings/application-settings.component.html
- src/app/settings/settings.service.ts
- src/app/settings/treasure-hunt-settings/treasure-hunt-settings.component.html
- src/app/shared/animated-checkmark/animated-checkmark.component.html
- src/app/shared/animated-checkmark/animated-checkmark.component.ts
- src/app/shared/models/settings.ts
- src/app/shared/models/treasure-hunt.ts
- src/app/shared/percent-graph/percent-graph.component.css
- src/app/shared/percent-graph/percent-graph.component.html
- src/app/shared/percent-graph/percent-graph.component.ts
- src/app/ssmt/operations/operating-hours/operating-hours.component.ts
- src/app/treasure-hunt/operating-hours/operating-hours.component.html
- src/app/treasure-hunt/operating-hours/operating-hours.component.spec.ts
- src/app/treasure-hunt/operating-hours/operating-hours.component.ts
- src/app/treasure-hunt/operation-costs/operation-costs.component.html
- src/app/treasure-hunt/operation-costs/operation-costs.component.spec.ts
- src/app/treasure-hunt/operation-costs/operation-costs.component.ts
- src/app/treasure-hunt/standalone-opportunity-sheet/opportunity-sheet.service.ts
- src/app/treasure-hunt/treasure-chest/lighting-replacement-card/lighting-replacement-card.component.css
- src/app/treasure-hunt/treasure-chest/lighting-replacement-card/lighting-replacement-card.component.html
- src/app/treasure-hunt/treasure-chest/lighting-replacement-card/lighting-replacement-card.component.ts
- src/app/treasure-hunt/treasure-chest/treasure-chest.component.css
- src/app/treasure-hunt/treasure-chest/treasure-chest.component.html
- src/app/treasure-hunt/treasure-chest/treasure-chest.component.ts
- src/app/treasure-hunt/treasure-hunt-banner/treasure-hunt-banner.component.html
- src/app/treasure-hunt/treasure-hunt.component.html
- src/app/treasure-hunt/treasure-hunt.component.ts
- src/app/treasure-hunt/treasure-hunt.module.ts
connects #2915 
connects #2908
> Issue 2915

- src/app/calculator/steam/steam.service.ts
- src/app/ssmt/ssmt-diagram-tab/deaerator-table/deaerator-table.component.css
- src/app/ssmt/ssmt-diagram-tab/deaerator-table/deaerator-table.component.html
- src/app/ssmt/ssmt-diagram-tab/deaerator-table/deaerator-table.component.ts
- src/app/ssmt/ssmt-diagram-tab/flash-tank-table/flash-tank-table.component.css
- src/app/ssmt/ssmt-diagram-tab/flash-tank-table/flash-tank-table.component.html
- src/app/ssmt/ssmt-diagram-tab/flash-tank-table/flash-tank-table.component.ts
- src/app/ssmt/ssmt-diagram-tab/turbine-table/turbine-table.component.css
- src/app/ssmt/ssmt-diagram-tab/turbine-table/turbine-table.component.html
- src/app/ssmt/ssmt-diagram-tab/turbine-table/turbine-table.component.ts
- src/app/ssmt/ssmt-diagram/condensate-flash-tank/condensate-flash-tank.component.css
- src/app/ssmt/ssmt-diagram/condensate-flash-tank/condensate-flash-tank.component.html
- src/app/ssmt/ssmt-diagram/condensate-flash-tank/condensate-flash-tank.component.ts
- src/app/ssmt/ssmt-diagram/deaerator-diagram/deaerator-diagram.component.css
- src/app/ssmt/ssmt-diagram/deaerator-diagram/deaerator-diagram.component.html
- src/app/ssmt/ssmt-diagram/deaerator-diagram/deaerator-diagram.component.ts
- src/app/ssmt/ssmt-diagram/header-diagram/header-diagram.component.css
- src/app/ssmt/ssmt-diagram/header-diagram/header-diagram.component.html
- src/app/ssmt/ssmt-diagram/header-diagram/header-diagram.component.ts
- src/app/ssmt/ssmt-diagram/hover-table/hover-header-table/hover-header-table.component.css
- src/app/ssmt/ssmt-diagram/hover-table/hover-header-table/hover-header-table.component.html
- src/app/ssmt/ssmt-diagram/hover-table/hover-header-table/hover-header-table.component.ts
- src/app/ssmt/ssmt-diagram/hover-table/hover-steam-properties/hover-steam-properties.component.css
- src/app/ssmt/ssmt-diagram/hover-table/hover-steam-properties/hover-steam-properties.component.html
- src/app/ssmt/ssmt-diagram/turbine-diagram/turbine-diagram.component.css
- src/app/ssmt/ssmt-diagram/turbine-diagram/turbine-diagram.component.html
- src/app/ssmt/ssmt-diagram/turbine-diagram/turbine-diagram.component.ts
connects #2634 
need additions to PRV calculation before adding PRV warnings.
> Issue 2634

- src/app/ssmt/ssmt-diagram-tab/ssmt-diagram-tab.component.css
- src/app/ssmt/ssmt-diagram-tab/ssmt-diagram-tab.component.html
- src/app/ssmt/ssmt-diagram-tab/ssmt-diagram-tab.component.ts
- src/app/ssmt/ssmt-diagram/ssmt-diagram.component.css
- src/app/ssmt/ssmt-diagram/ssmt-diagram.component.html
- src/app/ssmt/ssmt-diagram/ssmt-diagram.component.ts
- src/app/ssmt/ssmt-diagram/ssmt-diagram.module.ts
connects #2810 
connects #2677
> Issue 2810

- src/app/ssmt/ssmt-diagram/deaerator-diagram/deaerator-diagram.component.ts
> fix deaerator warning

- src/app/calculator/lighting/lighting-replacement/lighting-replacement-form/lighting-replacement-form.component.html
- src/app/calculator/lighting/lighting-replacement/lighting-replacement-form/lighting-replacement-form.component.ts
- src/app/calculator/lighting/lighting-replacement/lighting-replacement-help/lighting-replacement-help.component.html
- src/app/calculator/lighting/lighting-replacement/lighting-replacement.component.ts
- src/app/calculator/lighting/lighting-replacement/lighting-replacement.service.ts
- src/app/shared/models/lighting.ts
- src/app/treasure-hunt/find-treasure/find-treasure.component.html
- src/app/treasure-hunt/treasure-chest/treasure-chest.component.html
> refactor operating hours for lighting replacement

- src/app/calculator/motors/motor-drive/motor-drive-form/motor-drive-form.component.html
- src/app/calculator/motors/motor-drive/motor-drive-form/motor-drive-form.component.ts
- src/app/calculator/motors/motor-drive/motor-drive-graph/motor-drive-graph.component.ts
- src/app/calculator/motors/motor-drive/motor-drive-help/motor-drive-help.component.html
- src/app/calculator/motors/motor-drive/motor-drive-table/motor-drive-table.component.css
- src/app/calculator/motors/motor-drive/motor-drive-table/motor-drive-table.component.html
- src/app/calculator/motors/motor-drive/motor-drive-table/motor-drive-table.component.ts
- src/app/calculator/motors/motor-drive/motor-drive.component.css
- src/app/calculator/motors/motor-drive/motor-drive.component.html
- src/app/calculator/motors/motor-drive/motor-drive.component.ts
- src/app/calculator/motors/motor-drive/motor-drive.service.ts
- src/app/calculator/motors/replace-existing/replace-existing.component.html
- src/app/shared/models/calculators.ts
- src/app/shared/models/treasure-hunt.ts
- src/app/treasure-hunt/find-treasure/find-treasure.component.html
- src/app/treasure-hunt/find-treasure/find-treasure.component.ts
- src/app/treasure-hunt/treasure-chest/motor-drive-card/motor-drive-card.component.css
- src/app/treasure-hunt/treasure-chest/motor-drive-card/motor-drive-card.component.html
- src/app/treasure-hunt/treasure-chest/motor-drive-card/motor-drive-card.component.spec.ts
- src/app/treasure-hunt/treasure-chest/motor-drive-card/motor-drive-card.component.ts
- src/app/treasure-hunt/treasure-chest/replace-existing-motor-card/replace-existing-motor-card.component.html
- src/app/treasure-hunt/treasure-chest/summary-card/summary-card.component.ts
- src/app/treasure-hunt/treasure-chest/treasure-chest.component.html
- src/app/treasure-hunt/treasure-chest/treasure-chest.component.ts
- src/app/treasure-hunt/treasure-hunt.component.html
- src/app/treasure-hunt/treasure-hunt.module.ts
> Issue 2740

- src/app/calculator/pumps/pump-curve/pump-curve.component.ts
- src/app/calculator/pumps/system-curve/system-curve.service.ts
> Update default data for system curve

- src/app/calculator/motors/motor-drive/motor-drive-form/motor-drive-form.component.ts
- src/app/calculator/motors/motor-drive/motor-drive-table/motor-drive-table.component.html
- src/app/calculator/motors/motor-drive/motor-drive.service.ts
- src/app/shared/models/calculators.ts
> add direct drive to motor drive calculator

- src/app/treasure-hunt/treasure-chest/summary-card/summary-card.component.ts
> fix th treasure chest bug

- src/app/calculator/furnaces/o2-enrichment/o2-enrichment-form/o2-enrichment-form.component.html
- src/app/calculator/furnaces/o2-enrichment/o2-enrichment-form/o2-enrichment-form.component.ts
- src/app/calculator/furnaces/o2-enrichment/o2-enrichment-graph/o2-enrichment-graph.component.ts
- src/app/calculator/furnaces/o2-enrichment/o2-enrichment.component.ts
- src/app/calculator/furnaces/o2-enrichment/o2-enrichment.service.ts
- src/app/shared/models/phast/o2Enrichment.ts
> Added cost to o2 enrichment

- src/app/assessment/assessment-create/assessment-create.component.ts
- src/app/assessment/assessment.service.ts
- src/app/shared/models/treasure-hunt.ts
- src/app/treasure-hunt/operation-costs/operation-costs.component.html
- src/app/treasure-hunt/operation-costs/operation-costs.component.ts
- src/app/treasure-hunt/treasure-chest/lighting-replacement-card/lighting-replacement-card.component.html
- src/app/treasure-hunt/treasure-chest/motor-drive-card/motor-drive-card.component.html
- src/app/treasure-hunt/treasure-chest/opportunity-sheet-card/opportunity-sheet-card.component.html
- src/app/treasure-hunt/treasure-chest/replace-existing-motor-card/replace-existing-motor-card.component.html
- src/app/treasure-hunt/treasure-chest/summary-card/summary-card.component.html
- src/app/treasure-hunt/treasure-chest/summary-card/summary-card.component.ts
- src/app/treasure-hunt/treasure-chest/treasure-chest-menu/treasure-chest-menu.component.html
- src/app/treasure-hunt/treasure-chest/treasure-chest-menu/treasure-chest-menu.component.spec.ts
- src/app/treasure-hunt/treasure-chest/treasure-chest-menu/treasure-chest-menu.component.ts
- src/app/treasure-hunt/treasure-chest/treasure-chest.component.html
- src/app/treasure-hunt/treasure-chest/treasure-chest.component.ts
- src/app/treasure-hunt/treasure-hunt-banner/treasure-hunt-banner.component.html
- src/app/treasure-hunt/treasure-hunt-banner/treasure-hunt-banner.component.ts
- src/app/treasure-hunt/treasure-hunt-gauge/treasure-hunt-gauge.component.css
- src/app/treasure-hunt/treasure-hunt-gauge/treasure-hunt-gauge.component.html
- src/app/treasure-hunt/treasure-hunt-gauge/treasure-hunt-gauge.component.ts
- src/app/treasure-hunt/treasure-hunt.component.html
- src/app/treasure-hunt/treasure-hunt.component.ts
- src/app/treasure-hunt/treasure-hunt.module.ts
- src/assets/styles/utilities.css
> Issue 2946

- src/app/treasure-hunt/standalone-opportunity-sheet/opportunity-sheet-results/opportunity-sheet-results.component.css
- src/app/treasure-hunt/standalone-opportunity-sheet/opportunity-sheet-results/opportunity-sheet-results.component.html
> Issue 2959

- src/app/shared/models/treasure-hunt.ts
- src/app/treasure-hunt/standalone-opportunity-sheet/opportunity-sheet.service.ts
- src/app/treasure-hunt/treasure-chest/summary-card/summary-card.component.html
- src/app/treasure-hunt/treasure-chest/summary-card/summary-card.component.ts
- src/app/treasure-hunt/treasure-hunt-banner/treasure-hunt-banner.component.html
- src/app/treasure-hunt/treasure-hunt-report/executive-summary/executive-summary.component.css
- src/app/treasure-hunt/treasure-hunt-report/executive-summary/executive-summary.component.html
- src/app/treasure-hunt/treasure-hunt-report/executive-summary/executive-summary.component.spec.ts
- src/app/treasure-hunt/treasure-hunt-report/executive-summary/executive-summary.component.ts
- src/app/treasure-hunt/treasure-hunt-report/opportunity-summary/opportunity-summary.component.html
- src/app/treasure-hunt/treasure-hunt-report/opportunity-summary/opportunity-summary.component.spec.ts
- src/app/treasure-hunt/treasure-hunt-report/opportunity-summary/opportunity-summary.component.ts
- src/app/treasure-hunt/treasure-hunt-report/report-graphs/report-graphs.component.html
- src/app/treasure-hunt/treasure-hunt-report/report-graphs/report-graphs.component.spec.ts
- src/app/treasure-hunt/treasure-hunt-report/report-graphs/report-graphs.component.ts
- src/app/treasure-hunt/treasure-hunt-report/treasure-hunt-report.component.css
- src/app/treasure-hunt/treasure-hunt-report/treasure-hunt-report.component.html
- src/app/treasure-hunt/treasure-hunt-report/treasure-hunt-report.component.spec.ts
- src/app/treasure-hunt/treasure-hunt-report/treasure-hunt-report.component.ts
- src/app/treasure-hunt/treasure-hunt-report/treasure-hunt-report.module.spec.ts
- src/app/treasure-hunt/treasure-hunt-report/treasure-hunt-report.module.ts
- src/app/treasure-hunt/treasure-hunt-report/treasure-hunt-report.service.spec.ts
- src/app/treasure-hunt/treasure-hunt-report/treasure-hunt-report.service.ts
- src/app/treasure-hunt/treasure-hunt.component.html
- src/app/treasure-hunt/treasure-hunt.component.ts
- src/app/treasure-hunt/treasure-hunt.module.ts
> Issue 2944

- src/app/shared/models/treasure-hunt.ts
- src/app/treasure-hunt/find-treasure/find-treasure.component.ts
- src/app/treasure-hunt/standalone-opportunity-sheet/opportunity-sheet.service.ts
- src/app/treasure-hunt/treasure-hunt-report/opportunity-summary/opportunity-summary.component.css
- src/app/treasure-hunt/treasure-hunt-report/opportunity-summary/opportunity-summary.component.html
- src/app/treasure-hunt/treasure-hunt-report/opportunity-summary/opportunity-summary.component.ts
- src/app/treasure-hunt/treasure-hunt-report/treasure-hunt-report.component.html
- src/app/treasure-hunt/treasure-hunt-report/treasure-hunt-report.service.ts
> added opportunity summaries calcs and results to report

- src/app/ssmt/ssmt-report/report-graphs/report-graphs.component.html
- src/app/ssmt/ssmt-report/report-graphs/report-graphs.component.ts
> Issue 2865

- src/app/ssmt/header/header-form/header-form.component.html
> Update desuperheat field titles in ssmt

- src/app/ssmt/boiler/boiler.component.html
- src/app/ssmt/boiler/boiler.service.ts
- src/app/ssmt/header/header-form/header-form.component.html
- src/app/ssmt/header/header-form/header-form.component.ts
- src/app/ssmt/header/header.component.ts
- src/app/ssmt/header/header.service.ts
> Update validators for header pressure

- src/app/treasure-hunt/find-treasure/find-treasure.component.html
- src/app/treasure-hunt/standalone-opportunity-sheet/standalone-opportunity-sheet.component.html
> fix issue 2979

- package.json
- src/app/calculator/furnaces/o2-enrichment/o2-enrichment-form/o2-enrichment-form.component.ts
- src/app/calculator/furnaces/o2-enrichment/o2-enrichment.component.ts
> Issue 2500 fix

- src/app/calculator/furnaces/o2-enrichment/o2-enrichment.component.ts
- src/app/calculator/utilities/electricity-reduction/electricity-reduction-form/electricity-reduction-form.component.html
- src/app/calculator/utilities/electricity-reduction/electricity-reduction-results/electricity-reduction-results.component.html
- src/app/calculator/utilities/natural-gas-reduction/natural-gas-reduction-form/natural-gas-reduction-form.component.html
- src/app/calculator/utilities/natural-gas-reduction/natural-gas-reduction-help/natural-gas-reduction-help.component.html
> Fix decimal formatting, units field labels

- src/app/shared/models/treasure-hunt.ts
- src/app/treasure-hunt/help-panel/help-panel.component.html
- src/app/treasure-hunt/help-panel/help-panel.component.ts
- src/app/treasure-hunt/operation-costs/operation-costs.component.html
- src/app/treasure-hunt/operation-costs/operation-costs.component.ts
- src/app/treasure-hunt/opportunity-sheet/costs-form/costs-form.component.html
- src/app/treasure-hunt/opportunity-sheet/costs-form/costs-form.component.ts
- src/app/treasure-hunt/opportunity-sheet/general-details-form/general-details-form.component.html
- src/app/treasure-hunt/opportunity-sheet/general-details-form/general-details-form.component.ts
- src/app/treasure-hunt/standalone-opportunity-sheet/energy-use-form/energy-use-form.component.html
- src/app/treasure-hunt/standalone-opportunity-sheet/energy-use-form/energy-use-form.component.ts
- src/app/treasure-hunt/standalone-opportunity-sheet/opportunity-sheet-help/opportunity-sheet-help.component.html
- src/app/treasure-hunt/standalone-opportunity-sheet/opportunity-sheet-help/opportunity-sheet-help.component.ts
- src/app/treasure-hunt/standalone-opportunity-sheet/opportunity-sheet-results/opportunity-sheet-results.component.html
- src/app/treasure-hunt/standalone-opportunity-sheet/standalone-opportunity-sheet.component.html
- src/app/treasure-hunt/standalone-opportunity-sheet/standalone-opportunity-sheet.component.ts
- src/app/treasure-hunt/treasure-chest/summary-card/summary-card.component.html
- src/app/treasure-hunt/treasure-hunt-report/opportunity-summary/opportunity-summary.component.html
- src/app/treasure-hunt/treasure-hunt-report/treasure-hunt-report.service.ts
- src/app/treasure-hunt/treasure-hunt.component.html
connects #2987 
connects #2946 
connects #2982
> Issue 2987

- package.json
- src/app/treasure-hunt/treasure-hunt-report/executive-summary/executive-summary.component.css
- src/app/treasure-hunt/treasure-hunt-report/executive-summary/executive-summary.component.html
- src/app/treasure-hunt/treasure-hunt-report/executive-summary/executive-summary.component.ts
- src/app/treasure-hunt/treasure-hunt-report/treasure-hunt-report.component.html
> Issue 2980

- package.json
- src/app/calculator/standalone.service.ts
- src/app/calculator/utilities/natural-gas-reduction/natural-gas-reduction-form/natural-gas-reduction-form.component.ts
- src/app/calculator/utilities/natural-gas-reduction/natural-gas-reduction-results/natural-gas-reduction-results.component.html
- src/app/calculator/utilities/natural-gas-reduction/natural-gas-reduction-results/natural-gas-reduction-results.component.ts
- src/app/calculator/utilities/natural-gas-reduction/natural-gas-reduction.component.css
- src/app/calculator/utilities/natural-gas-reduction/natural-gas-reduction.component.html
- src/app/calculator/utilities/natural-gas-reduction/natural-gas-reduction.component.ts
- src/app/calculator/utilities/natural-gas-reduction/natural-gas-reduction.service.ts
- src/app/shared/models/standalone.ts
- src/app/shared/models/treasure-hunt.ts
- src/app/treasure-hunt/find-treasure/find-treasure.component.html
- src/app/treasure-hunt/find-treasure/find-treasure.component.ts
- src/app/treasure-hunt/treasure-chest/natural-gas-reduction-card/natural-gas-reduction-card.component.css
- src/app/treasure-hunt/treasure-chest/natural-gas-reduction-card/natural-gas-reduction-card.component.html
- src/app/treasure-hunt/treasure-chest/natural-gas-reduction-card/natural-gas-reduction-card.component.spec.ts
- src/app/treasure-hunt/treasure-chest/natural-gas-reduction-card/natural-gas-reduction-card.component.ts
- src/app/treasure-hunt/treasure-chest/treasure-chest.component.html
- src/app/treasure-hunt/treasure-chest/treasure-chest.component.ts
- src/app/treasure-hunt/treasure-hunt-report/treasure-hunt-report.service.ts
- src/app/treasure-hunt/treasure-hunt.module.ts
> Issue 2953

- src/app/calculator/lighting/lighting-replacement/lighting-replacement-form/lighting-replacement-form.component.html
- src/app/calculator/lighting/lighting-replacement/lighting-replacement-form/lighting-replacement-form.component.ts
- src/app/calculator/lighting/lighting-replacement/lighting-replacement-results/lighting-replacement-results.component.html
- src/app/calculator/lighting/lighting-replacement/lighting-replacement-results/lighting-replacement-results.component.ts
- src/app/calculator/lighting/lighting-replacement/lighting-replacement.component.html
- src/app/calculator/lighting/lighting-replacement/lighting-replacement.component.ts
- src/app/calculator/lighting/lighting-replacement/lighting-replacement.service.ts
- src/app/calculator/utilities/electricity-reduction/electricity-reduction-form/electricity-reduction-form.component.html
- src/app/calculator/utilities/electricity-reduction/electricity-reduction-form/electricity-reduction-form.component.ts
- src/app/calculator/utilities/electricity-reduction/electricity-reduction.component.css
- src/app/calculator/utilities/electricity-reduction/electricity-reduction.component.html
- src/app/calculator/utilities/electricity-reduction/electricity-reduction.component.ts
- src/app/calculator/utilities/electricity-reduction/electricity-reduction.service.ts
- src/app/calculator/utilities/natural-gas-reduction/natural-gas-reduction-form/natural-gas-reduction-form.component.html
- src/app/calculator/utilities/natural-gas-reduction/natural-gas-reduction-form/natural-gas-reduction-form.component.ts
- src/app/calculator/utilities/natural-gas-reduction/natural-gas-reduction.component.css
- src/app/calculator/utilities/natural-gas-reduction/natural-gas-reduction.component.html
- src/app/calculator/utilities/natural-gas-reduction/natural-gas-reduction.component.ts
- src/app/calculator/utilities/natural-gas-reduction/natural-gas-reduction.service.ts
- src/app/treasure-hunt/operation-costs/operation-costs.component.html
- src/app/treasure-hunt/treasure-chest/electricity-reduction-card/electricity-reduction-card.component.html
- src/app/treasure-hunt/treasure-chest/electricity-reduction-card/electricity-reduction-card.component.ts
- src/app/treasure-hunt/treasure-chest/natural-gas-reduction-card/natural-gas-reduction-card.component.ts
- src/app/treasure-hunt/treasure-chest/treasure-chest-menu/treasure-chest-menu.component.ts
- src/assets/styles/two-panel.css
connects #3001 
connects #2952 
connects #2953
> Issue 3001

- src/app/shared/models/treasure-hunt.ts
- src/app/treasure-hunt/operation-costs/operation-costs.component.html
- src/app/treasure-hunt/operation-costs/operation-costs.component.ts
- src/app/treasure-hunt/treasure-hunt-report/executive-summary/executive-summary.component.html
- src/app/treasure-hunt/treasure-hunt-report/opportunity-summary/opportunity-summary.component.html
- src/app/treasure-hunt/treasure-hunt-report/opportunity-summary/opportunity-summary.component.ts
- src/app/treasure-hunt/treasure-hunt-report/report-graphs/report-graphs.component.html
- src/app/treasure-hunt/treasure-hunt-report/treasure-hunt-report.service.ts
> Issue 2981

- src/app/ssmt/explore-opportunities/explore-opportunities-form/turbine-form/explore-turbine-form/explore-turbine-form.component.ts
- src/app/ssmt/explore-opportunities/explore-opportunities-form/turbine-form/turbine-form.component.html
- src/app/ssmt/modification-list/modification-list.component.ts
- src/app/ssmt/ssmt-diagram-tab/results-table/results-table.component.ts
- src/app/ssmt/ssmt-diagram-tab/ssmt-diagram-tab.component.html
connects #2998 
connects #2902 
connects #3014
> Issue 2998

- package.json
- src/app/assessment/assessment-create/assessment-create.component.html
- src/app/assessment/assessment-grid-view/assessment-card/assessment-card.component.css
- src/app/assessment/assessment-grid-view/assessment-card/assessment-card.component.html
- src/app/assessment/assessment-grid-view/assessment-card/fsat-summary-card/fsat-summary-card.component.html
- src/app/assessment/assessment-grid-view/assessment-card/phast-summary-card/phast-summary-card.component.html
- src/app/assessment/assessment-grid-view/assessment-card/psat-summary-card/psat-summary-card.component.html
- src/app/assessment/assessment-grid-view/assessment-card/ssmt-summary-card/ssmt-summary-card.component.html
- src/app/assessment/assessment-grid-view/assessment-card/treasure-hunt-summary-card/treasure-hunt-summary-card.component.css
- src/app/assessment/assessment-grid-view/assessment-card/treasure-hunt-summary-card/treasure-hunt-summary-card.component.html
- src/app/assessment/assessment-grid-view/assessment-card/treasure-hunt-summary-card/treasure-hunt-summary-card.component.spec.ts
- src/app/assessment/assessment-grid-view/assessment-card/treasure-hunt-summary-card/treasure-hunt-summary-card.component.ts
- src/app/assessment/assessment-list-view/assessment-list-item/assessment-list-item.component.css
- src/app/assessment/assessment-list-view/assessment-list-item/assessment-list-item.component.html
- src/app/assessment/assessment-list-view/assessment-list-item/assessment-list-item.component.ts
- src/app/assessment/assessment.module.ts
- src/app/assessment/assessment.service.ts
- src/app/shared/models/treasure-hunt.ts
- src/app/treasure-hunt/treasure-hunt-banner/treasure-hunt-banner.component.html
- src/app/treasure-hunt/treasure-hunt-report/opportunity-summary/opportunity-summary.component.html
- src/app/treasure-hunt/treasure-hunt-report/opportunity-summary/opportunity-summary.component.ts
- src/app/treasure-hunt/treasure-hunt-report/treasure-hunt-report.service.ts
- src/app/treasure-hunt/treasure-hunt.component.html
- src/app/treasure-hunt/treasure-hunt.component.ts
> Issue 3003

- package.json
- src/app/calculator/standalone.service.ts
- src/app/calculator/utilities/compressed-air-reduction/compressed-air-reduction-form/compressed-air-reduction-form.component.css
- src/app/calculator/utilities/compressed-air-reduction/compressed-air-reduction-form/compressed-air-reduction-form.component.html
- src/app/calculator/utilities/compressed-air-reduction/compressed-air-reduction-form/compressed-air-reduction-form.component.spec.ts
- src/app/calculator/utilities/compressed-air-reduction/compressed-air-reduction-form/compressed-air-reduction-form.component.ts
- src/app/calculator/utilities/compressed-air-reduction/compressed-air-reduction-help/compressed-air-reduction-help.component.html
- src/app/calculator/utilities/compressed-air-reduction/compressed-air-reduction-help/compressed-air-reduction-help.component.spec.ts
- src/app/calculator/utilities/compressed-air-reduction/compressed-air-reduction-help/compressed-air-reduction-help.component.ts
- src/app/calculator/utilities/compressed-air-reduction/compressed-air-reduction-results/compressed-air-reduction-results.component.css
- src/app/calculator/utilities/compressed-air-reduction/compressed-air-reduction-results/compressed-air-reduction-results.component.html
- src/app/calculator/utilities/compressed-air-reduction/compressed-air-reduction-results/compressed-air-reduction-results.component.spec.ts
- src/app/calculator/utilities/compressed-air-reduction/compressed-air-reduction-results/compressed-air-reduction-results.component.ts
- src/app/calculator/utilities/compressed-air-reduction/compressed-air-reduction.component.css
- src/app/calculator/utilities/compressed-air-reduction/compressed-air-reduction.component.html
- src/app/calculator/utilities/compressed-air-reduction/compressed-air-reduction.component.spec.ts
- src/app/calculator/utilities/compressed-air-reduction/compressed-air-reduction.component.ts
- src/app/calculator/utilities/compressed-air-reduction/compressed-air-reduction.module.spec.ts
- src/app/calculator/utilities/compressed-air-reduction/compressed-air-reduction.module.ts
- src/app/calculator/utilities/compressed-air-reduction/compressed-air-reduction.service.spec.ts
- src/app/calculator/utilities/compressed-air-reduction/compressed-air-reduction.service.ts
- src/app/calculator/utilities/electricity-reduction/electricity-reduction-form/electricity-reduction-form.component.ts
- src/app/calculator/utilities/electricity-reduction/electricity-reduction.component.ts
- src/app/calculator/utilities/electricity-reduction/electricity-reduction.service.ts
- src/app/calculator/utilities/utilities.component.html
- src/app/calculator/utilities/utilities.module.ts
- src/app/shared/models/standalone.ts
- src/app/sidebar/calculator-list/calculator-list.component.html
connects #2822 
connects #3041
> Compressed air reduction

- src/app/ssmt/ssmt-banner/ssmt-banner.component.css
- src/app/ssmt/ssmt-diagram/boiler-diagram/boiler-diagram.component.css
- src/app/ssmt/ssmt-diagram/condensate-flash-tank/condensate-flash-tank.component.css
- src/app/ssmt/ssmt-diagram/flash-tank-diagram/flash-tank-diagram.component.css
> fixes for 3009

- src/app/calculator/utilities/compressed-air-reduction/compressed-air-reduction-form/compressed-air-reduction-form.component.html
> Disable form element in code instead of html

- package.json
- src/app/treasure-hunt/treasure-chest/motor-drive-card/motor-drive-card.component.css
- src/app/treasure-hunt/treasure-chest/motor-drive-card/motor-drive-card.component.html
- src/app/treasure-hunt/treasure-chest/replace-existing-motor-card/replace-existing-motor-card.component.css
- src/app/treasure-hunt/treasure-chest/replace-existing-motor-card/replace-existing-motor-card.component.html
> update motor drive and replace existing icons in treasure chest

- src/app/ssmt/ssmt-results-panel/ssmt-results-panel/ssmt-results-panel.component.html
- src/app/ssmt/ssmt-results-panel/ssmt-results-panel/ssmt-results-panel.component.ts
> fix issue 3049

- package.json
- src/app/treasure-hunt/treasure-hunt-report/executive-summary/executive-summary.component.html
- src/app/treasure-hunt/treasure-hunt-report/executive-summary/executive-summary.component.ts
> Fix cost summary chart and styling

- src/app/calculator/utilities/compressed-air-reduction/compressed-air-reduction-form/compressed-air-reduction-form.component.html
added unit labels for supply pressure.
connects #2822
> Add unit label for supply pressure

- src/app/calculator/motors/motor-drive/motor-drive.component.html
- src/app/settings/application-settings/application-settings.component.html
- src/app/settings/treasure-hunt-settings/treasure-hunt-settings.component.html
- src/app/treasure-hunt/find-treasure/find-treasure.component.html
- src/app/treasure-hunt/operation-costs/operation-costs.component.html
- src/app/treasure-hunt/standalone-opportunity-sheet/energy-use-form/energy-use-form.component.html
- src/app/treasure-hunt/standalone-opportunity-sheet/energy-use-form/energy-use-form.component.ts
- src/app/treasure-hunt/treasure-chest/compressed-air-reduction-card/compressed-air-reduction-card.component.ts
- src/app/treasure-hunt/treasure-hunt-report/executive-summary/executive-summary.component.html
- src/app/treasure-hunt/treasure-hunt-report/opportunity-summary/opportunity-summary.component.html
- src/app/treasure-hunt/treasure-hunt-report/report-graphs/cost-summary-chart/cost-summary-chart.component.ts
> Fix graph margin, update steam and CA units

- src/app/calculator/lighting/lighting-replacement/lighting-replacement.component.html
- src/app/treasure-hunt/find-treasure/find-treasure.component.css
- src/app/treasure-hunt/find-treasure/find-treasure.component.html
- src/app/treasure-hunt/treasure-chest/compressed-air-reduction-card/compressed-air-reduction-card.component.css
- src/app/treasure-hunt/treasure-chest/electricity-reduction-card/electricity-reduction-card.component.css
- src/app/treasure-hunt/treasure-chest/lighting-replacement-card/lighting-replacement-card.component.css
- src/app/treasure-hunt/treasure-chest/motor-drive-card/motor-drive-card.component.css
- src/app/treasure-hunt/treasure-chest/motor-drive-card/motor-drive-card.component.ts
- src/app/treasure-hunt/treasure-chest/natural-gas-reduction-card/natural-gas-reduction-card.component.css
- src/app/treasure-hunt/treasure-chest/opportunity-sheet-card/opportunity-sheet-card.component.css
- src/app/treasure-hunt/treasure-chest/opportunity-sheet-card/opportunity-sheet-card.component.html
- src/app/treasure-hunt/treasure-chest/opportunity-sheet-card/opportunity-sheet-card.component.ts
- src/app/treasure-hunt/treasure-chest/replace-existing-motor-card/replace-existing-motor-card.component.css
- src/app/treasure-hunt/treasure-chest/replace-existing-motor-card/replace-existing-motor-card.component.ts
- src/app/treasure-hunt/treasure-chest/summary-card/summary-card.component.css
- src/app/treasure-hunt/treasure-chest/summary-card/summary-card.component.html
- src/app/treasure-hunt/treasure-chest/treasure-chest-menu/treasure-chest-menu.component.css
- src/app/treasure-hunt/treasure-chest/treasure-chest-menu/treasure-chest-menu.component.ts
- src/app/treasure-hunt/treasure-chest/treasure-chest.component.html
- src/app/treasure-hunt/treasure-chest/treasure-chest.component.ts
- src/app/treasure-hunt/treasure-hunt-gauge/treasure-hunt-gauge.component.ts
- src/app/treasure-hunt/treasure-hunt-report/opportunity-summary.service.ts
- src/app/treasure-hunt/treasure-hunt.component.html
> Issue 3022

- README.md
- src/app/fsat/explore-opportunities/explore-opportunities.component.ts
- src/app/phast/explore-phast-opportunities/explore-phast-opportunities.component.ts
- src/app/psat/explore-opportunities/explore-opportunities.component.html
- src/app/psat/explore-opportunities/explore-opportunities.component.ts
- src/app/psat/psat.component.html
- src/app/psat/psat.component.ts
- src/app/ssmt/explore-opportunities/explore-opportunities.component.html
- src/app/ssmt/explore-opportunities/explore-opportunities.component.ts
- src/app/ssmt/ssmt.component.html
- src/app/ssmt/ssmt.component.ts
connects #2883 
connects #3089 
fixes bug for calculations when changes made to setup in SSMT
adds disclaimer and explore opps toast to SSMT and PSAT
remove waffle from readme
> Issue 2883

- src/app/treasure-hunt/treasure-hunt-report/report-graphs/cost-summary-chart/cost-summary-chart.component.ts
> add min height for cost summary chart

- src/app/ssmt/ssmt-report/input-summary/operations-summary/operations-summary.component.html
- src/app/ssmt/ssmt-report/input-summary/operations-summary/operations-summary.component.ts
- src/app/ssmt/ssmt-report/input-summary/turbine-summary/turbine-input-table/turbine-input-table.component.ts
> fixed issue 3058

- src/app/calculator/utilities/compressed-air-reduction/compressed-air-reduction-form/compressed-air-reduction-form.component.html
- src/app/calculator/utilities/compressed-air-reduction/compressed-air-reduction.service.ts
- src/app/treasure-hunt/operation-costs/operation-costs.component.html
> Consumption unit fix

- src/app/treasure-hunt/operation-costs/operation-costs.component.html
> Switch logic for compressed air cost units

- src/app/dashboard/dashboard.component.ts
- src/app/shared/import-export/export.service.ts
- src/app/shared/import-export/import-export.component.ts
- src/app/ssmt/modification-list/modification-list.component.ts
> Fix import export

- src/app/calculator/pumps/pump-curve/pump-curve-graph/pump-curve-graph.component.ts
- src/app/shared/line-chart-helper/line-chart-helper.service.ts
> Remove NaN labels on system curve and pump curve

- src/app/ssmt/add-modification/add-modification.component.ts
- src/app/treasure-hunt/find-treasure/find-treasure.component.css
- src/app/treasure-hunt/find-treasure/find-treasure.component.html
- src/app/treasure-hunt/find-treasure/find-treasure.component.ts
- src/app/treasure-hunt/treasure-hunt.component.html
- src/app/treasure-hunt/treasure-hunt.component.ts
connects #2993 
fixes a steam add modification.
added disclaimer toast treasure hunt
> Issue 2993

- src/app/core/core.service.ts
- src/app/core/mockTreasureHunt.ts
- src/app/treasure-hunt/treasure-chest/compressed-air-reduction-card/compressed-air-reduction-card.component.html
- src/app/treasure-hunt/treasure-chest/compressed-air-reduction-card/compressed-air-reduction-card.component.ts
- src/app/treasure-hunt/treasure-chest/treasure-chest-menu/treasure-chest-menu.component.html
connects #3070 
connects #3110
> add thunt example. fix comp air gauge

- package.json
- src/app/version-modal/version-modal.component.html
- src/assets/styles/two-panel.css
> Release fixes

- src/app/calculator/motors/percent-load-estimation/slip-method-form/slip-method-form.component.html
> Fix units in percent load estimation calculator

- src/app/shared/import-export/import-export.service.ts
- src/app/shared/models/treasure-hunt.ts
- src/app/shared/toast/toast.component.css
- src/app/treasure-hunt/treasure-chest/import-export-opportunities/import-export-opportunities.component.css
- src/app/treasure-hunt/treasure-chest/import-export-opportunities/import-export-opportunities.component.html
- src/app/treasure-hunt/treasure-chest/import-export-opportunities/import-export-opportunities.component.spec.ts
- src/app/treasure-hunt/treasure-chest/import-export-opportunities/import-export-opportunities.component.ts
- src/app/treasure-hunt/treasure-chest/treasure-chest-menu/treasure-chest-menu.component.css
- src/app/treasure-hunt/treasure-chest/treasure-chest-menu/treasure-chest-menu.component.html
- src/app/treasure-hunt/treasure-chest/treasure-chest-menu/treasure-chest-menu.component.ts
- src/app/treasure-hunt/treasure-chest/treasure-chest.component.html
- src/app/treasure-hunt/treasure-chest/treasure-chest.component.ts
- src/app/treasure-hunt/treasure-hunt.module.ts
- src/app/treasure-hunt/treasure-hunt.service.ts
connects #2957 
Adds import/export functionality for opportunities in the treasure chest.
> Issue 2957

- src/app/calculator/pumps/pump-curve/pump-curve.component.ts
> Repair system curve help init

- src/app/fsat/modify-conditions/modify-conditions-tabs/modify-conditions-tabs.component.ts
- src/app/psat/modify-conditions/modify-conditions-tabs/modify-conditions-tabs.component.ts
- src/app/shared/tabs-tooltip/tabs-tooltip.component.ts
> Fix badge tooltips for fsat and psat

- src/app/calculator/utilities/compressed-air-reduction/compressed-air-reduction-form/compressed-air-reduction-form.component.html
- src/app/calculator/utilities/compressed-air-reduction/compressed-air-reduction.component.ts
- src/app/calculator/utilities/compressed-air-reduction/compressed-air-reduction.service.ts
- src/app/core/mockTreasureHunt.ts
- src/app/shared/models/standalone.ts
> Create independent storage for electricity and compressed air costs

- src/app/calculator/motors/percent-load-estimation/field-measurement-form/field-measurement-form.component.ts
- src/app/calculator/motors/percent-load-estimation/percent-load-estimation.component.html
- src/app/calculator/motors/percent-load-estimation/percent-load-estimation.component.ts
- src/app/calculator/motors/percent-load-estimation/slip-method-form/slip-method-form.component.ts
> Fix reset data for percent load estimation

- src/app/ssmt/ssmt-diagram-tab/results-table/results-table.component.html
- src/app/ssmt/ssmt-diagram/boiler-diagram/boiler-diagram.component.html
- src/app/ssmt/ssmt-diagram/hover-table/hover-blowdown-table/hover-blowdown-table.component.html
- src/app/ssmt/ssmt-diagram/hover-table/hover-blowdown-table/hover-blowdown-table.component.ts
- src/app/ssmt/ssmt-diagram/hover-table/hover-condensate-table/hover-condensate-table.component.html
- src/app/ssmt/ssmt-diagram/hover-table/hover-condensate-table/hover-condensate-table.component.ts
- src/app/ssmt/ssmt-diagram/hover-table/hover-header-table/hover-header-table.component.html
- src/app/ssmt/ssmt-diagram/hover-table/hover-header-table/hover-header-table.component.ts
- src/app/ssmt/ssmt-diagram/hover-table/hover-heat-exchanger/hover-heat-exchanger.component.html
- src/app/ssmt/ssmt-diagram/hover-table/hover-heat-exchanger/hover-heat-exchanger.component.ts
- src/app/ssmt/ssmt-diagram/hover-table/hover-makeup-water/hover-makeup-water.component.html
- src/app/ssmt/ssmt-diagram/hover-table/hover-makeup-water/hover-makeup-water.component.ts
- src/app/ssmt/ssmt-diagram/hover-table/hover-process-usage/hover-process-usage.component.html
- src/app/ssmt/ssmt-diagram/hover-table/hover-process-usage/hover-process-usage.component.ts
- src/app/ssmt/ssmt-diagram/hover-table/hover-steam-properties/hover-steam-properties.component.html
- src/app/ssmt/ssmt-diagram/hover-table/hover-steam-properties/hover-steam-properties.component.ts
> add copy table button  to hover tables

- src/app/core/mockTreasureHunt.ts
- src/app/shared/models/treasure-hunt.ts
- src/app/treasure-hunt/find-treasure/find-treasure.component.html
- src/app/treasure-hunt/find-treasure/find-treasure.component.ts
- src/app/treasure-hunt/operation-costs/operation-costs.component.css
- src/app/treasure-hunt/operation-costs/operation-costs.component.html
- src/app/treasure-hunt/operation-costs/operation-costs.component.ts
- src/app/treasure-hunt/system-basics/system-basics.component.html
- src/app/treasure-hunt/treasure-hunt.component.html
> Issue 3008

- src/app/ssmt/ssmt-calculations/calculate-model.service.ts
Removes unneeded additional algorithm calls for calculate medium pressure header
> remove unneeded algorithm calls

- src/app/calculator/motors/motor-drive/motor-drive-form/motor-drive-form.component.html
- src/app/calculator/motors/motor-drive/motor-drive-form/motor-drive-form.component.ts
- src/app/calculator/motors/motor-drive/motor-drive.component.html
- src/app/calculator/motors/motor-drive/motor-drive.service.ts
update motor power field in motor drive calculator to number input with kW/hp unit
connects #3171
> fix issue 3171

- src/app/calculator/motors/percent-load-estimation/field-measurement-form/field-measurement-form.component.html
- src/app/calculator/motors/percent-load-estimation/percent-load-estimation.service.ts
> fix percent load estimation calculator

- src/app/fsat/fan-field-data/fan-field-data.component.ts
- src/app/fsat/fsat.service.ts
- src/app/shared/models/fans.ts
> fix compressibilty factor conversions

- src/app/fsat/convert-fsat.service.ts
- src/app/fsat/fsat.service.ts
> fix motor power conversions

- src/app/calculator/pumps/system-curve/system-curve-form/system-curve-form.component.html
- src/app/calculator/pumps/system-curve/system-curve-form/system-curve-form.component.ts
- src/app/calculator/pumps/system-curve/system-curve-help/system-curve-help.component.html
- src/app/calculator/pumps/system-curve/system-curve-help/system-curve-help.component.ts
- src/app/calculator/pumps/system-curve/system-curve.component.ts
- src/app/calculator/pumps/system-curve/system-curve.service.ts
> Issue 2928

- src/app/shared/convert-units/definitions/density.ts
> fix density unit labels

- src/app/shared/validators/less-than.ts
- src/app/ssmt/header/header-form/header-form.component.html
- src/app/ssmt/header/header-form/header-form.component.ts
- src/app/ssmt/header/header.component.ts
- src/app/ssmt/header/header.service.ts
> greater than and less than validators in header forms

- src/app/calculator/steam/flash-tank/flash-tank-form/flash-tank-form.component.ts
> fix issue 3128

- src/app/calculator/steam/steam-properties/steam-properties-form/steam-properties-form.component.html
- src/app/calculator/steam/steam-properties/steam-properties.component.ts
- src/app/calculator/steam/steam.service.ts
connects #3155 
*should be issue-3155 branch
> issue 3155
