ORNL-AMO/AMO-Tools-Desktop

src/app/calculator/steam/stack-loss/stack-loss-form/stack-loss-by-mass/stack-loss-by-mass.component.ts, src/app/calculator/steam/stack-loss/stack-loss-form/stack-loss-by-volume/stack-loss-by-volume.component.ts
=> fix stack loss units warning

src/app/fsat/fan-field-data/fan-field-data.component.ts, src/app/fsat/fsat.service.ts, src/app/shared/models/fans.ts
=> fix moverShaftPower input variable

src/app/calculator/pumps/achievable-efficiency/achievable-efficiency.component.html, src/app/calculator/pumps/head-tool/head-tool-form/head-tool-form.component.html, src/app/calculator/pumps/head-tool/head-tool-help/head-tool-help.component.html, src/app/calculator/pumps/head-tool/head-tool-suction-form/head-tool-suction-form.component.html, src/app/calculator/pumps/head-tool/head-tool.component.html, src/app/calculator/pumps/pump-curve/pump-curve-data-form/pump-curve-data-form.component.html, src/app/calculator/pumps/pump-curve/pump-curve-equation-form/pump-curve-equation-form.component.html, src/app/calculator/pumps/pump-curve/pump-curve-help/pump-curve-help.component.html, src/app/calculator/pumps/pump-curve/pump-curve.component.html, src/app/calculator/pumps/pumps.component.html, src/app/calculator/pumps/specific-speed/specific-speed-help/specific-speed-help.component.html, src/app/calculator/pumps/specific-speed/specific-speed.component.html, src/app/calculator/pumps/system-curve/system-curve-help/system-curve-help.component.html, src/app/psat/psat-tabs/psat-tabs.component.html, src/app/sidebar/calculator-list/calculator-list.component.html
=> Issue 3159

src/app/calculator/furnaces/efficiency-improvement/efficiency-improvement-form/efficiency-improvement-form.component.css, src/app/calculator/furnaces/efficiency-improvement/efficiency-improvement-form/efficiency-improvement-form.component.html, src/app/calculator/furnaces/efficiency-improvement/efficiency-improvement-help/efficiency-improvement-help.component.html, src/app/calculator/furnaces/efficiency-improvement/efficiency-improvement.component.html, src/app/calculator/furnaces/energy-equivalency/energy-equivalency-help/energy-equivalency-help.component.html, src/app/calculator/furnaces/energy-equivalency/energy-equivalency.component.html, src/app/calculator/furnaces/energy-use/energy-use-form/energy-use-form.component.html, src/app/calculator/furnaces/energy-use/energy-use-help/energy-use-help.component.html, src/app/calculator/furnaces/energy-use/energy-use.component.html, src/app/calculator/furnaces/o2-enrichment/o2-enrichment-form/o2-enrichment-form.component.html, src/app/calculator/furnaces/o2-enrichment/o2-enrichment-graph/o2-enrichment-graph.component.ts, src/app/calculator/furnaces/o2-enrichment/o2-enrichment-help/o2-enrichment-help.component.html, src/app/calculator/furnaces/o2-enrichment/o2-enrichment.component.html, src/app/phast/phast-report/phast-input-summary/gas-leakage-summary/gas-leakage-summary.component.html, src/app/shared/exportable-table/exportable-table.component.html, src/app/sidebar/calculator-list/calculator-list.component.html
=> Issue 3161

src/app/calculator/pumps/achievable-efficiency/achievable-efficiency.component.html, src/app/calculator/pumps/pump-curve/pump-curve.component.html, src/app/calculator/pumps/pump-curve/pump-curve.component.ts, src/app/calculator/pumps/system-curve/system-curve-form/system-curve-form.component.ts, src/app/calculator/pumps/system-curve/system-curve.component.html
=> fix issue 3159

src/app/calculator/compressed-air/compressed-air.component.html, src/app/calculator/compressed-air/operating-cost/operating-cost-form/operating-cost-form.component.html, src/app/calculator/compressed-air/operating-cost/operating-cost-help/operating-cost-help.component.html, src/app/calculator/compressed-air/operating-cost/operating-cost.component.html, src/app/calculator/compressed-air/pipe-sizing/pipe-sizing.component.html, src/app/calculator/compressed-air/pneumatic-air/pneumatic-air.component.html, src/app/calculator/compressed-air/receiver-tank/receiver-tank.component.html, src/app/sidebar/calculator-list/calculator-list.component.html
=> Issue 3165

src/app/calculator/steam/boiler/boiler-form/boiler-form.component.html, src/app/calculator/steam/boiler/boiler-help/boiler-help.component.html, src/app/calculator/steam/boiler/boiler-results/boiler-results.component.html, src/app/calculator/steam/deaerator/deaerator-form/deaerator-form.component.html, src/app/calculator/steam/deaerator/deaerator-help/deaerator-help.component.html, src/app/calculator/steam/flash-tank/flash-tank-form/flash-tank-form.component.html, src/app/calculator/steam/flash-tank/flash-tank-help/flash-tank-help.component.html, src/app/calculator/steam/header/header-form/header-form.component.html, src/app/calculator/steam/header/header-help/header-help.component.html, src/app/calculator/steam/heat-loss/heat-loss-form/heat-loss-form.component.html, src/app/calculator/steam/heat-loss/heat-loss-help/heat-loss-help.component.html, src/app/calculator/steam/prv/feedwater-form/feedwater-form.component.html, src/app/calculator/steam/prv/inlet-form/inlet-form.component.html, src/app/calculator/steam/prv/prv-help/prv-help.component.html, src/app/calculator/steam/saturated-properties/saturated-properties-help/saturated-properties-help.component.html, src/app/calculator/steam/stack-loss/stack-loss-help/stack-loss-help.component.html, src/app/calculator/steam/steam-properties/steam-properties-form/steam-properties-form.component.html, src/app/calculator/steam/steam-properties/steam-properties-help/steam-properties-help.component.html, src/app/calculator/steam/steam-properties/steam-properties-table/steam-properties-table.component.html, src/app/calculator/steam/steam-properties/steam-properties-table/steam-properties-table.component.ts, src/app/calculator/steam/steam-properties/steam-properties.component.html, src/app/calculator/steam/steam-properties/steam-properties.component.ts, src/app/calculator/steam/steam.service.ts, src/app/calculator/steam/turbine/turbine-form/turbine-form.component.html, src/app/calculator/steam/turbine/turbine-help/turbine-help.component.html
=> Issue 3164

src/app/ssmt/ssmt-calculations/calculate-model.service.ts, src/app/ssmt/ssmt-diagram-tab/cost-table/cost-table.component.html, src/app/ssmt/ssmt-diagram-tab/ssmt-diagram-tab.component.html
=> fix issue 3202 and vented steam energy flow

src/app/assessment/reset-data-modal/reset-data-modal.component.ts, src/app/core/mockTreasureHunt.ts, src/app/indexedDb/assessment-db.service.ts
=> fix issue 3186

src/app/fsat/fsat.service.ts
=> fix compressibility factor conversion

angular.json, package.json, src/app/calculator/standalone.service.ts, src/app/calculator/utilities/compressed-air-reduction/compressed-air-reduction-help/compressed-air-reduction-help.component.ts, src/app/calculator/utilities/compressed-air-reduction/compressed-air-reduction.service.ts, src/app/calculator/utilities/utilities.component.html, src/app/calculator/utilities/utilities.module.ts, src/app/calculator/utilities/water-reduction/water-reduction-form/water-reduction-form.component.css, src/app/calculator/utilities/water-reduction/water-reduction-form/water-reduction-form.component.html, src/app/calculator/utilities/water-reduction/water-reduction-form/water-reduction-form.component.spec.ts, src/app/calculator/utilities/water-reduction/water-reduction-form/water-reduction-form.component.ts, src/app/calculator/utilities/water-reduction/water-reduction-help/water-reduction-help.component.html, src/app/calculator/utilities/water-reduction/water-reduction-help/water-reduction-help.component.spec.ts, src/app/calculator/utilities/water-reduction/water-reduction-help/water-reduction-help.component.ts, src/app/calculator/utilities/water-reduction/water-reduction-results/water-reduction-results.component.css, src/app/calculator/utilities/water-reduction/water-reduction-results/water-reduction-results.component.html, src/app/calculator/utilities/water-reduction/water-reduction-results/water-reduction-results.component.spec.ts, src/app/calculator/utilities/water-reduction/water-reduction-results/water-reduction-results.component.ts, src/app/calculator/utilities/water-reduction/water-reduction.component.css, src/app/calculator/utilities/water-reduction/water-reduction.component.html, src/app/calculator/utilities/water-reduction/water-reduction.component.spec.ts, src/app/calculator/utilities/water-reduction/water-reduction.component.ts, src/app/calculator/utilities/water-reduction/water-reduction.module.ts, src/app/calculator/utilities/water-reduction/water-reduction.service.spec.ts, src/app/calculator/utilities/water-reduction/water-reduction.service.ts, src/app/shared/models/standalone.ts, src/app/shared/models/treasure-hunt.ts, src/app/sidebar/calculator-list/calculator-list.component.html
=> Issue 2821

src/app/calculator/fans/fan-efficiency/fan-efficiency-help/fan-efficiency-help.component.html, src/app/calculator/fans/fan-efficiency/fan-efficiency.component.html, src/app/calculator/fans/fans.component.html, src/app/calculator/pumps/pump-curve/pump-curve-help/pump-curve-help.component.html, src/app/sidebar/calculator-list/calculator-list.component.html
=> Issue 3160

package.json, src/app/calculator/steam/steam.service.ts, src/app/ssmt/ssmt-calculations/heat-exchanger.service.ts
connects #3060 
connects #3225
=> Issue 3225

src/app/psat/help-panel/field-data-help/field-data-help.component.html, src/app/psat/help-panel/pump-fluid-help/pump-fluid-help.component.html
=> updated help test for pump vfd

package.json, src/app/calculator/steam/steam.service.ts, src/app/calculator/steam/turbine/turbine-form/turbine-form.component.html, src/app/settings/steam-settings/steam-settings.component.ts, src/app/ssmt/ssmt-calculations/calculate-model.service.ts, src/app/ssmt/turbine/condensing-turbine-form/condensing-turbine-form.component.html, src/app/ssmt/turbine/pressure-turbine-form/pressure-turbine-form.component.html
fix units bug for steam turbine.
update small fixes for steam calcs
=> Steam turbine units

src/app/calculator/fans/fan-analysis/fan-analysis-form/fan-info-form/fan-info-form.component.ts, src/app/calculator/fans/fan-analysis/fan-analysis.component.ts, src/app/calculator/fans/fan-analysis/fan-analysis.module.ts, src/app/calculator/fans/fan-analysis/fan-analysis.service.ts, src/app/calculator/fans/fan-analysis/help-and-results-panel/planar-results/planar-results.component.css, src/app/calculator/fans/fan-analysis/help-and-results-panel/planar-results/planar-results.component.html, src/app/calculator/fans/fan-analysis/help-and-results-panel/planar-results/planar-results.component.ts, src/app/fsat/calculate-pressures/calculate-flow-pressure/calculate-flow-pressure-banner/calculate-flow-pressure-banner.component.html, src/app/fsat/calculate-pressures/calculate-flow-pressure/calculate-flow-pressure-banner/calculate-flow-pressure-banner.component.spec.ts, src/app/fsat/calculate-pressures/calculate-flow-pressure/calculate-flow-pressure-banner/calculate-flow-pressure-banner.component.ts, src/app/fsat/calculate-pressures/calculate-flow-pressure/calculate-flow-pressure.component.css, src/app/fsat/calculate-pressures/calculate-flow-pressure/calculate-flow-pressure.component.html, src/app/fsat/calculate-pressures/calculate-flow-pressure/calculate-flow-pressure.component.spec.ts, src/app/fsat/calculate-pressures/calculate-flow-pressure/calculate-flow-pressure.component.ts, src/app/fsat/calculate-pressures/calculate-pressures.module.ts, src/app/fsat/fan-field-data/fan-field-data.component.html, src/app/fsat/fan-field-data/fan-field-data.component.ts
=> Issue 3210

package.json, src/app/calculator/utilities/utilities.component.html
=> Update calculator descriptions

src/app/calculator/utilities/co2-savings/co2-savings-results/co2-savings-results.component.html, src/app/calculator/utilities/co2-savings/co2-savings.component.html, src/app/calculator/utilities/compressed-air-reduction/compressed-air-reduction.component.html, src/app/calculator/utilities/electricity-reduction/electricity-reduction.component.html, src/app/calculator/utilities/natural-gas-reduction/natural-gas-reduction.component.html, src/app/core/core.component.html, src/app/shared/toast/toast.component.html
Added a few changes to consolidate widths of result tables in the General standalone calculators. Also added CSS class to hide popups from the printed reports.
=> Hide popups from print, fix result table widths

src/app/calculator/pumps/pump-curve/pump-curve.component.html, src/app/calculator/pumps/pump-curve/pump-curve.service.ts, src/app/treasure-hunt/find-treasure/find-treasure.component.html
=> Minor updates

package.json, src/app/calculator/utilities/compressed-air-pressure-reduction/compressed-air-pressure-reduction-help/compressed-air-pressure-reduction-help.component.html
Update Compressed Air Pressure Reduction help text.
=> Pre release quick fixes

src/app/treasure-hunt/treasure-hunt.component.ts
=> fix treasure hunt opp hours

src/app/treasure-hunt/treasure-hunt-gauge/treasure-hunt-gauge.component.ts, src/app/treasure-hunt/treasure-hunt.component.ts
=> updated treasure chest gauge colors

src/app/fsat/fan-field-data/fan-field-data.component.html, src/app/fsat/fan-field-data/fan-field-data.component.ts, src/app/fsat/fan-field-data/fan-field-data.service.ts, src/app/fsat/fan-motor/fan-motor.service.ts, src/app/fsat/fan-setup/fan-setup.service.ts, src/app/fsat/fsat-fluid/fsat-fluid.service.ts
=> added pressure validation to fan field data

src/app/calculator/steam/boiler/boiler-form/boiler-form.component.html, src/app/calculator/steam/boiler/boiler-form/boiler-form.component.ts, src/app/calculator/steam/boiler/boiler.component.css, src/app/calculator/steam/boiler/boiler.component.html, src/app/calculator/steam/boiler/boiler.component.ts, src/app/calculator/steam/boiler/boiler.module.ts, src/app/calculator/steam/boiler/boiler.service.ts, src/app/calculator/steam/stack-loss/boiler-efficiency-modal/boiler-efficiency-modal.component.css, src/app/calculator/steam/stack-loss/boiler-efficiency-modal/boiler-efficiency-modal.component.html, src/app/calculator/steam/stack-loss/boiler-efficiency-modal/boiler-efficiency-modal.component.spec.ts, src/app/calculator/steam/stack-loss/boiler-efficiency-modal/boiler-efficiency-modal.component.ts, src/app/calculator/steam/stack-loss/stack-loss-form/stack-loss-form.component.html, src/app/calculator/steam/stack-loss/stack-loss-form/stack-loss-form.component.ts, src/app/calculator/steam/stack-loss/stack-loss.component.html, src/app/calculator/steam/stack-loss/stack-loss.component.ts, src/app/calculator/steam/stack-loss/stack-loss.module.ts, src/app/calculator/steam/stack-loss/stack-loss.service.ts, src/app/shared/models/steam/steam-inputs.ts, src/app/ssmt/boiler/boiler.component.html, src/app/ssmt/boiler/boiler.component.ts, src/app/ssmt/ssmt.component.html
=> Issue 3016

src/app/treasure-hunt/treasure-hunt-report/opportunity-payback/opportunity-payback-bar-chart/opportunity-payback-bar-chart.component.ts, src/app/treasure-hunt/treasure-hunt-report/opportunity-payback/opportunity-payback-donut/opportunity-payback-donut.component.ts, src/app/treasure-hunt/treasure-hunt-report/opportunity-payback/opportunity-payback.component.css, src/app/treasure-hunt/treasure-hunt-report/opportunity-payback/opportunity-payback.component.html, src/app/treasure-hunt/treasure-hunt-report/opportunity-payback/opportunity-payback.component.ts, src/app/treasure-hunt/treasure-hunt-report/report-graphs/cost-pie-chart/cost-pie-chart.component.ts, src/app/treasure-hunt/treasure-hunt-report/report-graphs/report-graphs.component.css, src/app/treasure-hunt/treasure-hunt-report/report-graphs/report-graphs.component.html, src/app/treasure-hunt/treasure-hunt-report/report-graphs/utility-donut-chart/utility-donut-chart.component.ts, src/app/treasure-hunt/treasure-hunt-report/treasure-hunt-report.component.html
=> fix th printing

src/app/calculator/pumps/head-tool/head-tool-results/head-tool-results.component.ts, src/app/calculator/steam/saturated-properties/saturated-properties-graph/saturated-properties-graph.component.ts, src/app/calculator/steam/saturated-properties/saturated-properties-ph-graph/saturated-properties-ph-graph.component.ts, src/app/calculator/steam/steam-properties/steam-properties-graph/steam-properties-graph.component.ts, src/app/calculator/steam/steam-properties/steam-properties-ph-graph/steam-properties-ph-graph.component.ts, src/app/calculator/utilities/compressed-air-pressure-reduction/compressed-air-pressure-reduction-results/compressed-air-pressure-reduction-results.component.ts, src/app/calculator/utilities/water-reduction/water-reduction-results/water-reduction-results.component.ts, src/app/shared/exportable-results-table/exportable-table/exportable-table.component.ts
=> fix native element bugs for view child updates in calculators

src/app/core/mockPhast.ts, src/app/core/mockPsat.ts, src/app/core/mockTreasureHunt.ts
=> fix 3268: default panel is results

main.js
=> fix 3289: quit mac on close

package.json, src/app/calculator/utilities/steam-reduction/steam-reduction-form/steam-reduction-form.component.html, src/app/calculator/utilities/steam-reduction/steam-reduction-form/steam-reduction-form.component.ts, src/app/calculator/utilities/steam-reduction/steam-reduction-results/steam-reduction-results.component.html, src/app/calculator/utilities/steam-reduction/steam-reduction-results/steam-reduction-results.component.ts, src/app/calculator/utilities/steam-reduction/steam-reduction.component.html, src/app/calculator/utilities/steam-reduction/steam-reduction.component.ts, src/app/calculator/utilities/steam-reduction/steam-reduction.service.ts
=> Issue 2820

src/app/treasure-hunt/treasure-hunt-report/opportunity-summary/opportunity-summary.component.css, src/app/treasure-hunt/treasure-hunt-report/opportunity-summary/opportunity-summary.component.html, src/app/treasure-hunt/treasure-hunt-report/opportunity-summary/opportunity-summary.component.ts, src/app/treasure-hunt/treasure-hunt-report/opportunity-summary/sort-summaries.pipe.spec.ts, src/app/treasure-hunt/treasure-hunt-report/opportunity-summary/sort-summaries.pipe.ts, src/app/treasure-hunt/treasure-hunt-report/treasure-hunt-report.module.ts
=> add ordering by title in opp summary table of TH report

src/app/treasure-hunt/find-treasure/find-treasure.component.html, src/app/treasure-hunt/treasure-chest/opportunity-cards/opportunity-cards.service.ts, src/app/treasure-hunt/treasure-hunt-report/opportunity-summary.service.ts
=> updated steam reduction in treasure hunt for different utilities

src/app/settings/application-settings/application-settings.component.html, src/app/settings/treasure-hunt-settings/treasure-hunt-settings.component.html, src/app/treasure-hunt/operation-costs/operation-costs.component.html
=> updates for issue 3048

src/app/treasure-hunt/operation-costs/operation-costs.component.html, src/app/treasure-hunt/operation-costs/operation-costs.component.ts, src/app/treasure-hunt/treasure-hunt.component.html
=> fix 3282 savings utility costs

src/app/landing-screen/landing-screen.component.html
=> change plant to facility on homepage

src/app/shared/exportable-results-table/exportable-table/exportable-table.component.css
=> fix 3303 graph scroll bar on hover

src/app/calculator/fans/fan-efficiency/fan-efficiency-form/fan-efficiency-form.component.html, src/app/calculator/fans/fan-efficiency/fan-efficiency-form/fan-efficiency-form.component.ts, src/app/calculator/fans/fan-efficiency/fan-efficiency.module.ts, src/app/calculator/fans/fan-efficiency/fan-efficiency.service.ts, src/app/fsat/fan-field-data/fan-field-data.component.html, src/app/fsat/fan-field-data/fan-field-data.component.ts, src/app/fsat/fan-field-data/fan-field-data.service.ts
=> fix 3254, add validation to achievable eff

src/app/shared/models/steam/ssmt.ts, src/app/ssmt/boiler/boiler.component.ts, src/app/ssmt/explore-opportunities/explore-opportunities-form/boiler-form/boiler-form.component.ts
=> save stack loss inputs in boiler obj

src/app/calculator/motors/replace-existing/replace-existing-form/replace-existing-form.component.html, src/app/calculator/motors/replace-existing/replace-existing.component.ts, src/app/calculator/motors/replace-existing/replace-existing.service.ts, src/app/treasure-hunt/calculators/calculators.component.ts, src/app/treasure-hunt/treasure-chest/opportunity-cards/opportunity-cards.component.ts, src/app/treasure-hunt/treasure-chest/opportunity-cards/opportunity-cards.service.ts, src/app/treasure-hunt/treasure-hunt-report/opportunity-summary.service.ts, src/app/treasure-hunt/treasure-hunt.service.ts
=> add metric conversion for replace existing motor

src/app/calculator/steam/prv/inlet-form/inlet-form.component.html, src/app/calculator/steam/stack-loss/stack-loss.component.html, src/app/calculator/steam/stack-loss/stack-loss.component.ts, src/app/calculator/steam/stack-loss/stack-loss.service.ts
=> Issue 3116

src/app/calculator/compressed-air/compressed-air.service.ts, src/app/calculator/compressed-air/receiver-tank/dedicated-storage-form/dedicated-storage-form.component.ts
=> fixes for 3117

src/app/treasure-hunt/treasure-hunt-report/executive-summary/executive-summary.component.html
=> Truncate currency decimals

src/app/calculator/steam/saturated-properties/saturated-properties-graph/saturated-properties-graph.component.ts, src/app/calculator/steam/steam-properties/steam-properties-graph/steam-properties-graph.component.ts
=> Repair limit on T-S Diagram

src/app/calculator/motors/replace-existing/replace-existing.service.ts
=> fix motor size for replace rewind in metric

src/app/calculator/utilities/co2-savings/co2-savings-results/co2-savings-results.component.html
=> update sig figs for co2 savings calc

src/app/fsat/fsat.component.html, src/app/fsat/fsat.component.ts, src/app/treasure-hunt/treasure-hunt.component.html, src/app/treasure-hunt/treasure-hunt.component.ts
connects #3260 
also fixes fsat btn navigation bug.
=> Issue 3260

src/app/calculator/utilities/compressed-air-pressure-reduction/compressed-air-pressure-reduction-form/compressed-air-pressure-reduction-form.component.html, src/app/calculator/utilities/compressed-air-pressure-reduction/compressed-air-pressure-reduction.module.ts, src/app/calculator/utilities/compressed-air-reduction/compressed-air-reduction-form/compressed-air-reduction-form.component.html, src/app/shared/operating-hours-modal/operating-hours-modal.component.ts, src/app/shared/operating-hours-modal/operating-hours-modal.service.ts
=> fix steam pressure reduction op hours modal and defaults

src/app/calculator/utilities/co2-savings/co2-savings-results/co2-savings-results.component.html, src/app/calculator/utilities/co2-savings/co2-savings-results/co2-savings-results.component.ts, src/app/calculator/utilities/co2-savings/co2-savings.module.ts
=> fix sig figs in co2 calc resutls

src/app/calculator/utilities/water-reduction/water-reduction-form/water-reduction-form.component.html, src/app/calculator/utilities/water-reduction/water-reduction.component.css, src/app/calculator/utilities/water-reduction/water-reduction.component.ts, src/app/calculator/utilities/water-reduction/water-reduction.service.ts
=> fix conversions for water reduction

src/app/calculator/furnaces/energy-equivalency/energy-equivalency.component.html
=> fix electricity calc

src/app/treasure-hunt/treasure-hunt.component.html, src/app/treasure-hunt/treasure-hunt.component.ts
=> remove btn nav on find treasure page:

src/app/calculator/utilities/steam-reduction/steam-reduction-form/steam-reduction-form.component.html, src/app/calculator/utilities/steam-reduction/steam-reduction.service.ts
=> Fix steam reduction individual result errors

src/app/calculator/steam/boiler-blowdown-rate/blowdown-rate-results/blowdown-rate-results.component.html, src/app/calculator/steam/boiler-blowdown-rate/boiler-blowdown-rate.service.ts
=> update units and digits in results

src/app/assessment/assessment.service.ts, src/app/calculator/motors/replace-existing/replace-existing.component.ts, src/app/calculator/utilities/compressed-air-reduction/compressed-air-reduction.service.ts, src/app/calculator/utilities/electricity-reduction/electricity-reduction.service.ts, src/app/calculator/utilities/natural-gas-reduction/natural-gas-reduction.service.ts, src/app/core/mockTreasureHunt.ts, src/app/phast/phast-report/phast-report.component.ts, src/app/shared/helper-services/update-data.service.ts, src/app/treasure-hunt/treasure-hunt.component.ts
=> fix operating hour defaults and replace existing

src/app/shared/exportable-results-table/exportable-results-table.component.css, src/app/shared/exportable-results-table/exportable-table/exportable-table.component.css
=> darker copy table button

src/app/treasure-hunt/treasure-chest/opportunity-cards/opportunity-cards.component.ts, src/app/treasure-hunt/treasure-chest/treasure-chest-menu/treasure-chest-menu.component.html, src/app/treasure-hunt/treasure-chest/treasure-chest-menu/treasure-chest-menu.component.ts, src/app/treasure-hunt/treasure-chest/treasure-chest-menu/treasure-chest-menu.service.ts
connects #3342 
connects #3343
=> Issue 3342

src/app/calculator/steam/boiler-blowdown-rate/blowdown-rate-results/blowdown-rate-results.component.html, src/app/calculator/steam/boiler-blowdown-rate/blowdown-rate-results/blowdown-rate-results.component.ts, src/app/calculator/steam/boiler-blowdown-rate/boiler-blowdown-rate.component.html, src/app/calculator/steam/boiler-blowdown-rate/boiler-blowdown-rate.module.ts, src/app/calculator/steam/saturated-properties/saturated-properties-table/saturated-properties-table.component.html, src/app/calculator/steam/saturated-properties/saturated-properties-table/saturated-properties-table.component.ts, src/app/calculator/steam/saturated-properties/saturated-properties.module.ts, src/app/calculator/steam/steam-properties/steam-properties-table/steam-properties-table.component.html, src/app/calculator/steam/steam-properties/steam-properties-table/steam-properties-table.component.ts, src/app/calculator/steam/steam-properties/steam-properties.module.ts
=> Add table exports

src/app/report-rollup/report-rollup.component.html, src/app/report-rollup/report-rollup.component.ts, src/app/treasure-hunt/treasure-hunt-report/treasure-hunt-report.component.html
=> Add treasure hunt to report rollup

src/app/calculator/utilities/combined-heat-power/combined-heat-power.component.html, src/app/calculator/utilities/natural-gas-reduction/natural-gas-reduction-results/natural-gas-reduction-results.component.html
=> Fixed small calculator bugs

src/app/calculator/lighting/lighting-fixture-data/LED-troffers.ts, src/app/calculator/lighting/lighting-fixture-data/fluorescent-eight-foot.ts, src/app/calculator/lighting/lighting-fixture-data/fluorescent-four-foot.ts, src/app/calculator/lighting/lighting-fixture-data/fluorescent-xp-retrofit.ts, src/app/calculator/lighting/lighting-fixture-data/high-bay-LED.ts, src/app/calculator/lighting/lighting-fixture-data/high-bay-fluorescent.ts, src/app/calculator/lighting/lighting-fixture-data/high-pressure-sodium.ts, src/app/calculator/lighting/lighting-fixture-data/induction-high-bay.ts, src/app/calculator/lighting/lighting-fixture-data/lighting-data.ts, src/app/calculator/lighting/lighting-fixture-data/mercury-vapor.ts, src/app/calculator/lighting/lighting-fixture-data/metal-halide.ts, src/app/calculator/lighting/lighting-replacement/lighting-replacement-form/lighting-replacement-form.component.css, src/app/calculator/lighting/lighting-replacement/lighting-replacement-form/lighting-replacement-form.component.html, src/app/calculator/lighting/lighting-replacement/lighting-replacement-form/lighting-replacement-form.component.ts, src/app/calculator/lighting/lighting-replacement/lighting-replacement-help/lighting-replacement-help.component.html, src/app/calculator/lighting/lighting-replacement/lighting-replacement-help/lighting-replacement-help.component.ts, src/app/calculator/lighting/lighting-replacement/lighting-replacement.component.html, src/app/calculator/lighting/lighting-replacement/lighting-replacement.component.ts, src/app/calculator/lighting/lighting-replacement/lighting-replacement.service.ts, src/app/shared/helper-services/update-data.service.ts, src/app/shared/models/lighting.ts
connects #2381 
Updated lighting calculator with new fields that connect to temporary data arrays. Will be replaced with suite DB values.
=> Issue 2381

src/app/shared/pie-chart/pie-chart.component.ts, src/app/treasure-hunt/treasure-hunt-report/executive-summary/executive-summary.component.html, src/app/treasure-hunt/treasure-hunt-report/executive-summary/executive-summary.component.ts, src/app/treasure-hunt/treasure-hunt-report/treasure-hunt-report.component.html, src/app/treasure-hunt/treasure-hunt-report/treasure-hunt-report.component.ts, src/app/treasure-hunt/treasure-hunt-report/treasure-hunt-report.module.ts
=> Add team summary to executive summary

src/app/calculator/utilities/pre-assessment/pre-assessment.component.ts, src/app/calculator/utilities/pre-assessment/pre-assessment.service.ts
=> Update colors and second example

src/app/calculator/utilities/pre-assessment/pre-assessment.component.ts
=> Update pre assessment reset

src/app/calculator/motors/motor-performance/motor-performance-graph/motor-performance-graph.component.ts
=> Add y axis label for motor performance

src/app/calculator/compressed-air/air-velocity/air-velocity-form/air-velocity-form.component.html
=> Fix units for velocity in pipes

src/app/calculator/utilities/compressed-air-reduction/compressed-air-reduction-form/compressed-air-reduction-form.component.html
=> Fix electricity cost in compressed air reduction

src/app/assessment/folder-summary/folder-summary.component.ts, src/app/calculator/fans/fan-analysis/fan-analysis-form/plane-data-form/plane-info-form/plane-info-form.component.ts, src/app/calculator/motors/motor-performance/motor-performance-graph/motor-performance-graph.component.ts, src/app/calculator/motors/replace-existing/replace-existing.service.ts, src/app/calculator/utilities/electricity-reduction/electricity-reduction-form/electricity-reduction-form.component.html, src/app/calculator/utilities/electricity-reduction/electricity-reduction.service.ts, src/app/calculator/utilities/natural-gas-reduction/natural-gas-reduction-form/natural-gas-reduction-form.component.html, src/app/calculator/utilities/natural-gas-reduction/natural-gas-reduction-results/natural-gas-reduction-results.component.html, src/app/calculator/utilities/natural-gas-reduction/natural-gas-reduction.service.ts, src/app/calculator/utilities/steam-reduction/steam-reduction-form/steam-reduction-form.component.html, src/app/calculator/utilities/water-reduction/water-reduction-form/water-reduction-form.component.html, src/app/shared/convert-units/definitions/volume.ts, src/app/treasure-hunt/calculators/standalone-opportunity-sheet/energy-use-form/energy-use-form.component.ts, src/app/treasure-hunt/calculators/standalone-opportunity-sheet/opportunity-sheet.service.ts, src/app/treasure-hunt/convert-input-data.service.spec.ts, src/app/treasure-hunt/convert-input-data.service.ts, src/app/treasure-hunt/operation-costs/operation-costs.component.html, src/app/treasure-hunt/system-basics/system-basics.component.css, src/app/treasure-hunt/system-basics/system-basics.component.html, src/app/treasure-hunt/system-basics/system-basics.component.ts, src/app/treasure-hunt/treasure-hunt.module.ts
connects #3348 
Additionally:
- Fixed treasure hunt calcs so all units were metric/imperial (labels and conversions)
- Updated treasure hunt fields for natural gas and other fuel to use GJ across the board
=> Issue 3348

src/app/calculator/system-and-equipment-curve/system-and-equipment-curve.component.ts
=> fix savings pump/fan curves for assessments

main.js, src/app/calculator/compressed-air/receiver-tank/receiver-tank.component.ts, src/app/calculator/steam/boiler-blowdown-rate/boiler-blowdown-rate.component.html, src/app/calculator/system-and-equipment-curve/system-and-equipment-curve-graph/system-and-equipment-curve-graph.component.ts, src/app/treasure-hunt/treasure-hunt-report/executive-summary/executive-summary.component.html
connects #3346 
fixes production build bugs
=> fix copy/past in production and fix production build errors

src/app/calculator/utilities/compressed-air-reduction/compressed-air-reduction-form/compressed-air-reduction-form.component.html
=> Remove duplicate electricity cost

src/app/calculator/standalone.service.ts
=> Update output conversion

src/app/calculator/motors/motor-performance/motor-performance-graph/motor-performance-graph.component.ts
=> Add legend for motor performance

src/app/ssmt/header/header.component.html, src/app/ssmt/turbine/turbine.component.html
=> Fix SSMT setup titles

src/app/calculator/motors/motor-performance/motor-performance-graph/motor-performance-graph.component.ts
=> Increase legend font size and line length

src/app/psat/compare.service.ts, src/app/psat/modification-list/modification-list.component.ts, src/app/psat/modify-conditions/modify-conditions-tabs/modify-conditions-tabs.component.ts, src/app/psat/pump-fluid/pump-fluid.component.html, src/app/psat/pump-fluid/pump-fluid.component.ts
=> Issue 3363

src/app/core/mockTreasureHunt.ts
=> update treasure hunt example

src/app/calculator/furnaces/efficiency-improvement/efficiency-improvement.service.ts
=> update efficiency improvement example

src/app/calculator/system-and-equipment-curve/equipment-curve/by-data-form/by-data-form.component.ts, src/app/calculator/system-and-equipment-curve/system-and-equipment-curve-graph/system-and-equipment-curve-graph.component.ts, src/app/calculator/system-and-equipment-curve/system-and-equipment-curve.component.ts
=> fix remove row by data

src/app/calculator/motors/nema-energy-efficiency/nema-energy-efficiency.service.ts, src/app/core/mockPsat.ts
=> updated psat example

package.json, src/app/calculator/steam/steam.service.ts, src/app/psat/help-panel/field-data-help/field-data-help.component.html, src/app/report-rollup/report-rollup.service.ts, src/app/report-rollup/ssmt-rollup/ssmt-rollup-energy-table/ssmt-rollup-energy-table.component.html, src/app/report-rollup/ssmt-rollup/ssmt-rollup-energy-table/ssmt-rollup-energy-table.component.ts, src/app/report-rollup/ssmt-rollup/ssmt-rollup-steam-summary-table/ssmt-rollup-steam-summary-table.component.html, src/app/report-rollup/ssmt-rollup/ssmt-rollup-steam-summary/ssmt-rollup-steam-summary.component.ts, src/app/report-rollup/ssmt-rollup/ssmt-rollup.component.html, src/app/shared/import-export/export.service.ts, src/app/shared/models/operations.ts, src/app/shared/models/steam/ssmt.ts, src/app/ssmt/explore-opportunities/explore-opportunities-form/explore-opportunities-form.component.ts, src/app/ssmt/help-panel/operations-help/operations-help.component.html, src/app/ssmt/operations/operating-costs/operating-costs.component.html, src/app/ssmt/operations/operating-costs/operating-costs.component.ts, src/app/ssmt/operations/operations.component.html, src/app/ssmt/operations/operations.service.ts, src/app/ssmt/ssmt-report/executive-summary/executive-summary.component.html, src/app/ssmt/ssmt-report/executive-summary/executive-summary.component.ts, src/app/ssmt/ssmt-report/ssmt-report.component.html
connects #2996 
connects #3192 
some bug fixes in report rollup.
=> Steam bug fixes

src/app/ssmt/ssmt-report/executive-summary/executive-summary.component.html
=> implementation costs in $/k in executive report

src/app/calculator/steam/prv/prv-help/prv-help.component.html, src/app/calculator/steam/prv/prv-help/prv-help.component.ts, src/app/calculator/steam/prv/prv.component.html, src/app/calculator/steam/prv/prv.component.ts, src/app/calculator/steam/prv/prv.service.ts, src/app/calculator/steam/steam.service.ts, src/app/ssmt/header/header-form/header-form.component.html, src/app/ssmt/header/header-form/header-form.component.ts, src/app/ssmt/header/header.service.ts
=> Issue 3419

src/app/calculator/motors/motor-performance/motor-performance-graph/motor-performance-graph.component.ts
=> reduce text size for motor performance y axis label

src/app/calculator/motors/replace-existing/replace-existing-results/replace-existing-results.component.html, src/app/calculator/motors/replace-existing/replace-existing-results/replace-existing-results.component.ts, src/app/calculator/motors/replace-existing/replace-existing.service.ts, src/app/shared/models/calculators.ts
=> replace existing vs rewind added new table

src/app/calculator/steam/prv/prv-help/prv-help.component.ts, src/app/calculator/steam/prv/prv.component.html, src/app/calculator/steam/prv/prv.component.ts, src/app/calculator/steam/prv/prv.service.ts
=> outlet pressure for desuperheat validation

src/app/ssmt/header/header.service.ts, src/app/ssmt/ssmt-report/executive-summary/executive-summary.component.html, src/app/ssmt/ssmt-report/executive-summary/executive-summary.component.ts
connects  #3419 
connects #2996
=> fix steam bugs

src/app/phast/phast.service.ts, src/app/shared/models/phast/o2Enrichment.ts
=> Fix 02 enrichment conversion

src/app/sidebar/sidebar.component.css, src/app/sidebar/sidebar.component.html, src/app/sidebar/sidebar.component.ts
=> Issue 3447

package.json, src/app/version-modal/version-modal.component.html
=> update release notes and version number

src/app/ssmt/header/header-form/header-form.component.ts, src/app/ssmt/ssmt-diagram/header-diagram/header-diagram.component.html, src/app/ssmt/ssmt.service.ts
=> Modeler issue

src/app/treasure-hunt/treasure-hunt-report/executive-summary/executive-summary.component.ts
=> fix 3460, team summary payback period

src/app/treasure-hunt/treasure-hunt-report/report-graphs/cost-pie-chart/cost-pie-chart.component.ts, src/app/treasure-hunt/treasure-hunt-report/treasure-hunt-report.service.ts
=> fix ustility cost and energy for mixed results

src/app/calculator/utilities/compressed-air-reduction/compressed-air-reduction.component.ts, src/app/calculator/utilities/compressed-air-reduction/compressed-air-reduction.service.ts
=> Fix locking of utility type

src/app/calculator/motors/motor-drive/motor-drive-form/motor-drive-form.component.html, src/app/calculator/motors/motor-drive/motor-drive-help/motor-drive-help.component.html, src/app/calculator/motors/replace-existing/replace-existing-form/replace-existing-form.component.html, src/app/calculator/utilities/electricity-reduction/electricity-reduction-form/electricity-reduction-form.component.html, src/app/calculator/utilities/electricity-reduction/electricity-reduction-help/electricity-reduction-help.component.html, src/app/fsat/fsat-report/results-summary/results-summary.component.html, src/app/fsat/fsat-results/fsat-results-panel/fsat-results-panel.component.html, src/app/psat/explore-opportunities/explore-opportunities-results/explore-opportunities-results.component.html, src/app/psat/psat-report/output-summary/output-summary.component.html
=> Load Factor Revision

src/app/treasure-hunt/treasure-hunt-report/executive-summary/executive-summary.component.ts
=> fix th summary selected only

src/app/calculator/motors/motor-drive/motor-drive.component.ts, src/app/calculator/motors/replace-existing/replace-existing.component.ts, src/app/calculator/utilities/steam-reduction/steam-reduction.component.ts, src/app/treasure-hunt/treasure-chest/opportunity-cards/opportunity-cards.service.ts
=> fix replace existing motor and motor drive in treasure hunt

src/app/core/core.component.html
=> Issue 3480

src/app/dashboard/import-export/export-modal/export-modal.component.ts
=> fix export all data from contacts page

src/app/dashboard/directory-dashboard/directory-dashboard-menu/content-controls/content-controls.component.html, src/app/dashboard/import-export/export-modal/export-modal.component.html, src/app/dashboard/sidebar/assessment-item/assessment-item.component.html
connects #3482 
fixes icon bug and prod build errors
=> fix icons and prod build

package.json, src/app/dashboard/sidebar/version-modal/version-modal.component.html
=> add release notes and update version number

src/app/core/core.routing.ts, src/app/dashboard/sidebar/calculator-list/calculator-list.component.html
Declare children tree for routes not by reference
=> fix prod router tree

src/app/phast/losses/operations/operations-form/operations-form.component.html, src/app/phast/losses/operations/operations-form/operations-form.component.ts, src/app/phast/losses/operations/operations.component.html
=> Fixed unit switching

src/app/ssmt/operations/operating-costs/operating-costs.component.html, src/app/ssmt/ssmt-report/executive-summary/executive-summary.component.html
=> Updated Steam implementation cost

src/app/shared/models/treasure-hunt.ts, src/app/treasure-hunt/calculators/standalone-opportunity-sheet/opportunity-sheet.service.ts, src/app/treasure-hunt/treasure-hunt-report/opportunity-summary.service.ts
=> fix opp sheet bug and issue 3516

src/app/treasure-hunt/treasure-chest/treasure-chest-menu/treasure-chest-menu.component.css, src/app/treasure-hunt/treasure-chest/treasure-chest-menu/treasure-chest-menu.component.html, src/app/treasure-hunt/treasure-chest/treasure-chest-menu/treasure-chest-menu.component.ts
=> add scroll bar to filter menu popup TH

src/app/calculator/lighting/lighting-fixture-data/high-bay-fluorescent.ts
=> Verify lighting database

src/app/treasure-hunt/treasure-hunt-report/report-graphs/cost-summary-chart/cost-summary-chart.service.ts
=> Remove decimal in treasure hunt graph

src/app/treasure-hunt/calculators/opportunity-sheet/general-details-form/general-details-form.component.html, src/app/treasure-hunt/calculators/opportunity-sheet/general-details-form/general-details-form.component.ts
=> add dropdown for process/equipment

src/app/calculator/motors/percent-load-estimation/percent-load-estimation.component.ts, src/app/calculator/motors/percent-load-estimation/percent-load-estimation.service.ts
=> Repair percent load estimation example

src/app/core/core.component.ts
=> call init custom db materials in core

src/app/log-tool/system-setup/setup-data/date-formats.ts
=> Issue 3495

package.json, src/app/log-tool/day-type-analysis/day-type-graph/day-type-graph.component.ts, src/app/log-tool/log-tool.module.ts, src/app/log-tool/log-tool.service.ts, src/app/log-tool/system-setup/clean-data/clean-data.component.html, src/app/log-tool/system-setup/clean-data/clean-data.component.ts, src/app/log-tool/system-setup/clean-data/field-units-modal/field-unit-options.ts, src/app/log-tool/system-setup/clean-data/field-units-modal/field-units-modal.component.css, src/app/log-tool/system-setup/clean-data/field-units-modal/field-units-modal.component.html, src/app/log-tool/system-setup/clean-data/field-units-modal/field-units-modal.component.spec.ts, src/app/log-tool/system-setup/clean-data/field-units-modal/field-units-modal.component.ts, src/app/log-tool/system-setup/system-setup.component.css, src/app/log-tool/system-setup/system-setup.component.html, src/app/log-tool/system-setup/system-setup.component.ts
=> Issue 3524

src/app/calculator/lighting/lighting-replacement/lighting-replacement.component.html, src/app/calculator/lighting/lighting-replacement/lighting-replacement.component.ts, src/app/calculator/motors/motor-drive/motor-drive.component.html, src/app/calculator/motors/motor-drive/motor-drive.component.ts, src/app/calculator/motors/replace-existing/replace-existing.component.html, src/app/calculator/motors/replace-existing/replace-existing.component.ts, src/app/calculator/utilities/compressed-air-pressure-reduction/compressed-air-pressure-reduction.component.html, src/app/calculator/utilities/compressed-air-pressure-reduction/compressed-air-pressure-reduction.component.ts, src/app/calculator/utilities/compressed-air-reduction/compressed-air-reduction.component.html, src/app/calculator/utilities/compressed-air-reduction/compressed-air-reduction.component.ts, src/app/calculator/utilities/electricity-reduction/electricity-reduction.component.html, src/app/calculator/utilities/electricity-reduction/electricity-reduction.component.ts, src/app/calculator/utilities/natural-gas-reduction/natural-gas-reduction.component.html, src/app/calculator/utilities/natural-gas-reduction/natural-gas-reduction.component.ts, src/app/calculator/utilities/pipe-insulation-reduction/pipe-insulation-reduction.component.html, src/app/calculator/utilities/pipe-insulation-reduction/pipe-insulation-reduction.component.ts, src/app/calculator/utilities/steam-reduction/steam-reduction.component.html, src/app/calculator/utilities/steam-reduction/steam-reduction.component.ts, src/app/calculator/utilities/water-reduction/water-reduction.component.html, src/app/calculator/utilities/water-reduction/water-reduction.component.ts, src/app/treasure-hunt/calculators/calculators.component.html, src/app/treasure-hunt/calculators/calculators.component.ts, src/app/treasure-hunt/calculators/opportunity-sheet/opportunity-sheet.component.ts
=> Issue 3477

src/app/treasure-hunt/treasure-hunt-report/opportunity-summary/opportunity-summary.component.css
=> Make opportunity summary landscape

src/app/dashboard/about-page/about-page.component.css, src/app/dashboard/about-page/about-page.component.html, src/app/dashboard/about-page/about-page.component.ts
=> update about page content

src/app/calculator/utilities/pipe-insulation-reduction/pipe-insulation-reduction.component.html, src/app/calculator/utilities/pipe-insulation-reduction/pipe-insulation-reduction.component.ts, src/app/calculator/utilities/pipe-insulation-reduction/pipe-insulation-reduction.service.ts, src/app/shared/models/treasure-hunt.ts, src/app/treasure-hunt/calculators/calculators.component.html, src/app/treasure-hunt/calculators/calculators.component.ts, src/app/treasure-hunt/calculators/calculators.module.ts, src/app/treasure-hunt/calculators/calculators.service.ts, src/app/treasure-hunt/find-treasure/find-treasure.component.html, src/app/treasure-hunt/find-treasure/find-treasure.component.ts, src/app/treasure-hunt/treasure-chest/export-opportunities/export-opportunities.component.html, src/app/treasure-hunt/treasure-chest/export-opportunities/export-opportunities.component.ts, src/app/treasure-hunt/treasure-chest/opportunity-cards/opportunity-cards.component.ts, src/app/treasure-hunt/treasure-chest/opportunity-cards/opportunity-cards.service.ts, src/app/treasure-hunt/treasure-hunt-report/opportunity-summary.service.ts, src/app/treasure-hunt/treasure-hunt.service.ts
=> add pipe insulation calculator to treasure hunt

src/app/phast/designed-energy/designed-energy-help/designed-energy-help.component.html, src/app/phast/designed-energy/designed-energy-results/designed-energy-results.component.html, src/app/phast/losses/losses-help/atmosphere-losses-help/atmosphere-losses-help.component.html, src/app/phast/losses/losses-help/charge-material-help/charge-material-help.component.html, src/app/phast/losses/losses-help/energy-input-help/energy-input-help.component.html, src/app/phast/losses/losses-help/fixture-losses-help/fixture-losses-help.component.html, src/app/phast/metered-energy/metered-energy-help/metered-energy-help.component.html, src/app/phast/metered-energy/metered-energy-results/metered-energy-results.component.html, src/app/phast/phast-report/energy-used/energy-used.component.html, src/app/psat/psat-report/psat-report-graphs/psat-report-graphs-print/psat-report-graphs-print.component.html, src/app/report-rollup/fsat-rollup/fsat-rollup-print/fsat-rollup-print.component.html, src/app/report-rollup/phast-rollup/phast-rollup-print/phast-rollup-print.component.html, src/app/report-rollup/psat-rollup/psat-rollup-print/psat-rollup-print.component.html, src/app/report-rollup/report-rollup.component.html, src/app/report-rollup/report-summary/phast-summary/phast-summary.component.html, src/app/report-rollup/report-summary/report-summary.component.html, src/app/report-rollup/rollup-bar-chart/rollup-bar-chart.component.html, src/app/settings/application-settings/application-settings.component.html, src/app/settings/phast-settings/phast-settings.component.html, src/app/settings/tutorial-settings/tutorial-settings.component.html, src/app/shared/print-options-menu/print-options-menu.component.html
=> Issue 3559

src/app/calculator/pumps/head-tool/head-tool.component.css
=> fix toggle btn styling for head tool

src/app/shared/animated-checkmark/animated-checkmark.component.ts, src/app/treasure-hunt/treasure-hunt-report/opportunity-summary/opportunity-summary.component.css, src/app/treasure-hunt/treasure-hunt-report/opportunity-summary/opportunity-summary.component.html, src/app/treasure-hunt/treasure-hunt-report/opportunity-summary/opportunity-summary.component.ts, src/app/treasure-hunt/treasure-hunt-report/treasure-hunt-report.component.html
=> Add page break functionality

src/app/core/core.routing.ts
=> fix routing for tank insulation reduction

src/app/treasure-hunt/treasure-chest/opportunity-cards/opportunity-cards.component.ts, src/app/treasure-hunt/treasure-chest/opportunity-cards/opportunity-cards.service.ts, src/app/treasure-hunt/treasure-chest/opportunity-cards/sort-cards.service.ts, src/app/treasure-hunt/treasure-chest/treasure-chest-menu/treasure-chest-menu.component.html, src/app/treasure-hunt/treasure-chest/treasure-chest-menu/treasure-chest-menu.component.ts, src/app/treasure-hunt/treasure-chest/treasure-chest-menu/treasure-chest-menu.module.ts, src/app/treasure-hunt/treasure-hunt-report/executive-summary/executive-summary.component.html, src/app/treasure-hunt/treasure-hunt-report/executive-summary/executive-summary.component.ts, src/app/treasure-hunt/treasure-hunt-report/opportunity-payback/opportunity-payback-bar-chart/opportunity-payback-bar-chart.component.ts, src/app/treasure-hunt/treasure-hunt-report/opportunity-payback/opportunity-payback-donut/opportunity-payback-donut.component.ts, src/app/treasure-hunt/treasure-hunt-report/report-graphs/cost-pie-chart/cost-pie-chart.component.ts, src/app/treasure-hunt/treasure-hunt-report/report-graphs/cost-summary-chart/cost-summary-chart.component.ts, src/app/treasure-hunt/treasure-hunt-report/report-graphs/utility-donut-chart/utility-donut-chart.component.ts, src/app/treasure-hunt/treasure-hunt-report/treasure-hunt-report.component.html, src/app/treasure-hunt/treasure-hunt-report/treasure-hunt-report.component.ts, src/app/treasure-hunt/treasure-hunt-report/treasure-hunt-report.module.ts, src/app/treasure-hunt/treasure-hunt.component.ts, src/app/treasure-hunt/treasure-hunt.module.ts
connects #3344 
Add filter menu to treasure hunt report
=> Issue 3344

src/app/phast/phast-report/executive-summary.service.ts
=> fix phast energy intensity

src/app/treasure-hunt/treasure-chest/treasure-chest-menu/treasure-chest-menu.module.ts, src/app/treasure-hunt/treasure-hunt.module.ts
=> Fix thunt menu module

src/app/calculator/lighting/lighting-replacement/lighting-replacement-results/lighting-replacement-results.component.html, src/app/calculator/motors/replace-existing/replace-existing-results/replace-existing-results.component.html, src/app/calculator/utilities/compressed-air-pressure-reduction/compressed-air-pressure-reduction-form/compressed-air-pressure-reduction-form.component.html, src/app/calculator/utilities/compressed-air-pressure-reduction/compressed-air-pressure-reduction-results/compressed-air-pressure-reduction-results.component.html, src/app/calculator/utilities/compressed-air-reduction/compressed-air-reduction-form/compressed-air-reduction-form.component.html, src/app/calculator/utilities/compressed-air-reduction/compressed-air-reduction-results/compressed-air-reduction-results.component.html, src/app/calculator/utilities/electricity-reduction/electricity-reduction-form/electricity-reduction-form.component.html, src/app/calculator/utilities/electricity-reduction/electricity-reduction-results/electricity-reduction-results.component.html, src/app/calculator/utilities/natural-gas-reduction/natural-gas-reduction-form/natural-gas-reduction-form.component.html, src/app/calculator/utilities/natural-gas-reduction/natural-gas-reduction-results/natural-gas-reduction-results.component.html, src/app/calculator/utilities/pipe-insulation-reduction/pipe-insulation-reduction-form/pipe-insulation-reduction-form.component.html, src/app/calculator/utilities/pipe-insulation-reduction/pipe-insulation-reduction-results/pipe-insulation-reduction-results.component.html, src/app/calculator/utilities/steam-reduction/steam-reduction-form/steam-reduction-form.component.html, src/app/calculator/utilities/steam-reduction/steam-reduction-results/steam-reduction-results.component.html, src/app/calculator/utilities/water-reduction/water-reduction-form/water-reduction-form.component.html, src/app/calculator/utilities/water-reduction/water-reduction-results/water-reduction-results.component.html, src/app/treasure-hunt/calculators/standalone-opportunity-sheet/opportunity-sheet-results/opportunity-sheet-results.component.html, src/app/treasure-hunt/treasure-hunt-report/executive-summary/executive-summary.component.html
connects #3552 
-Remove all decimals in Treasure Hunt and corresponding calculators that are NOT 'payback'
=> Treasure Hunt decimal places

src/app/calculator/compressed-air/operating-cost/operating-cost-form/operating-cost-form.component.html, src/app/calculator/furnaces/o2-enrichment/o2-enrichment-form/o2-enrichment-form.component.html, src/app/ssmt/ssmt-report/energy-summary/energy-summary.component.html
connects #3551 
- Removing decimals from missed calculators
- Replacing decimals for marginals
=> Cost Decimal places

src/app/log-tool/system-setup/clean-data/clean-data.component.html, src/app/log-tool/system-setup/clean-data/clean-data.component.ts
=> fix units logic

src/app/core/mockSsmt.ts, src/app/dashboard/assessment.service.ts, src/app/shared/models/steam/ssmt.ts, src/app/ssmt/ssmt-report/energy-summary/energy-summary.component.html, src/app/ssmt/ssmt-report/executive-summary/executive-summary.component.html, src/app/ssmt/ssmt-report/executive-summary/executive-summary.component.ts, src/app/ssmt/ssmt-results-panel/ssmt-results-panel/ssmt-results-panel.component.html
connects #3553 
- Remove $k
- Fix implementationCosts property placement on SSMT interface
- Remove duplicate nested modifications in mockSsmt.ts
=> Display $1000's and fix implementation costs / payback period

src/app/core/mockTreasureHunt.ts, src/app/treasure-hunt/calculators/opportunity-sheet/general-details-form/general-details-form.component.html, src/app/treasure-hunt/calculators/opportunity-sheet/general-details-form/general-details-form.component.ts, src/app/treasure-hunt/calculators/opportunity-sheet/general-details-form/processEquipmentOptions.ts, src/app/treasure-hunt/treasure-chest/opportunity-cards/sort-cards-by.pipe.ts, src/app/treasure-hunt/treasure-chest/opportunity-cards/sort-cards.service.ts, src/app/treasure-hunt/treasure-chest/treasure-chest-menu/treasure-chest-menu.component.css, src/app/treasure-hunt/treasure-chest/treasure-chest-menu/treasure-chest-menu.component.html, src/app/treasure-hunt/treasure-chest/treasure-chest-menu/treasure-chest-menu.component.ts
connects #3584 
connects #3585 
connects #3583 
connects #3593 
Fixes treasure hunt menu logic
add dropdown instead of pop-up in report
Changes Proces / Equipment to just Equipment
Updates equipment options for dropdown
Updates example to match changes
=> Issue 3584

src/app/settings/settings.service.ts
=> default steam unit GJ

src/app/core/core.component.html, src/app/core/core.component.ts, src/app/fsat/fsat.component.html, src/app/fsat/fsat.component.ts, src/app/phast/phast.component.html, src/app/phast/phast.component.ts, src/app/psat/psat.component.html, src/app/psat/psat.component.ts, src/app/shared/models/settings.ts, src/app/shared/toast/toast.component.html, src/app/shared/toast/toast.component.ts, src/app/ssmt/ssmt.component.html, src/app/ssmt/ssmt.component.ts, src/app/treasure-hunt/treasure-hunt.component.html, src/app/treasure-hunt/treasure-hunt.component.ts, src/app/update-toast/update-toast.component.ts
=> disable popups option added

src/app/treasure-hunt/calculators/calculators.component.html, src/app/treasure-hunt/calculators/calculators.component.ts, src/app/treasure-hunt/treasure-chest/treasure-chest-menu/treasure-chest-menu.component.ts
=> fix equipment bug

package.json, src/app/dashboard/sidebar/version-modal/version-modal.component.html, src/app/report-rollup/report-banner/report-banner.component.html, src/app/report-rollup/report-summary/fsat-summary/fsat-summary.component.ts, src/app/report-rollup/report-summary/phast-summary/phast-summary.component.ts, src/app/report-rollup/report-summary/psat-summary/psat-summary.component.ts, src/app/report-rollup/report-summary/report-summary.component.ts, src/app/report-rollup/report-summary/ssmt-summary/ssmt-summary.component.ts, src/app/report-rollup/report-summary/treasure-hunt-summary/treasure-hunt-summary.component.ts
connects #3588 
updates release notes
updates suite and desktop version numbers
disables report rollup printing
fix prod build errors
=> Issue 3588

.travis.yml, package.json, travis_scripts/get_os.sh
Build and release automation for all three platforms (Windows, Linux, Mac) through Travis CI. The Mac installer is not currently automatically signed and notarized.
=> Issue 3505

src/app/dashboard/about-page/about-page.component.html, src/app/dashboard/acknowledgments-page/acknowledgments-page.component.html
=> Amend Acknowledgements and About

src/app/treasure-hunt/calculators/opportunity-sheet/general-details-form/general-details-form.component.html, src/app/treasure-hunt/calculators/standalone-opportunity-sheet/opportunity-sheet-help/opportunity-sheet-help.component.html
=> Treasure Hunt op sheet changes

src/app/fsat/fsat-report/input-summary/base-gas-density-summary/base-gas-density-summary.component.html, src/app/fsat/fsat-report/input-summary/fan-motor-summary/fan-motor-summary.component.html, src/app/fsat/fsat-report/input-summary/fan-setup-summary/fan-setup-summary.component.html, src/app/fsat/fsat-report/input-summary/input-summary.component.html
=> Match Setup headings to report input-summary

src/app/core/mockTreasureHunt.ts
=> fix NG opps in TH Example

src/app/phast/convert-phast.service.ts, src/app/phast/system-basics/system-basics.component.ts
=> add conversion for fuel and steam costs in phast

angular.json, src/app/fsat/explore-opportunities/explore-opportunities-form/fan-data-form/fan-data-form.component.html, src/app/fsat/explore-opportunities/explore-opportunities-form/rated-motor-form/rated-motor-form.component.html, src/app/fsat/explore-opportunities/explore-opportunities-form/system-data-form/system-data-form.component.html, src/app/fsat/explore-opportunities/explore-opportunities-form/variable-frequency-drive-form/variable-frequency-drive-form.component.html, src/assets/styles/explore-opps.css
connects #3644 
- Fan UI enhancement to place explore-opportunities baseline and modification selects side by side
=> (Fans) Enhance explore-opportunities baseline and mod UI

src/app/calculator/utilities/pre-assessment/pre-assessment-form/pre-assessment-designed/pre-assessment-designed.component.ts, src/app/calculator/utilities/pre-assessment/pre-assessment-form/pre-assessment-form.component.html, src/app/calculator/utilities/pre-assessment/pre-assessment-form/pre-assessment-form.component.ts, src/app/calculator/utilities/pre-assessment/pre-assessment-graph/pre-assessment-graph.component.html, src/app/calculator/utilities/pre-assessment/pre-assessment-graph/pre-assessment-graph.component.ts, src/app/calculator/utilities/pre-assessment/pre-assessment.component.html, src/app/calculator/utilities/pre-assessment/pre-assessment.component.ts, src/app/calculator/utilities/pre-assessment/pre-assessment.service.ts, src/app/dashboard/directory-dashboard/pre-assessment-modal/pre-assessment-modal.component.html, src/app/dashboard/directory-dashboard/pre-assessment-modal/pre-assessment-modal.component.ts, src/app/report-rollup/fsat-rollup/fsat-rollup.component.html, src/app/report-rollup/phast-rollup/phast-rollup.component.html, src/app/report-rollup/psat-rollup/psat-rollup.component.html
connects #3628 
fixes bug for designed energy form
changes graph over to plotly
remove metric/imperial choice
=> Issue 3628

src/app/fsat/explore-opportunities/explore-opportunities-form/explore-opportunities-form.component.html, src/app/fsat/explore-opportunities/explore-opportunities-form/explore-opportunities-form.component.ts, src/app/fsat/explore-opportunities/explore-opportunities-form/fan-data-form/fan-data-form.component.html, src/app/fsat/explore-opportunities/explore-opportunities-form/system-data-form/system-data-form.component.html, src/app/fsat/fsat-report/results-summary/results-summary.component.html, src/app/psat/explore-opportunities/explore-opportunities-form/explore-opportunities-form.component.html, src/app/psat/explore-opportunities/explore-opportunities-form/explore-opportunities-form.component.ts, src/app/psat/explore-opportunities/explore-opportunities-form/pump-data-form/pump-data-form.component.html, src/app/psat/explore-opportunities/explore-opportunities-form/pump-data-form/pump-data-form.component.ts, src/app/psat/explore-opportunities/explore-opportunities-form/rated-motor-form/rated-motor-form.component.html, src/app/psat/explore-opportunities/explore-opportunities-form/rated-motor-form/rated-motor-form.component.ts, src/app/psat/explore-opportunities/explore-opportunities-form/system-data-form/system-data-form.component.html, src/app/psat/explore-opportunities/explore-opportunities-form/system-data-form/system-data-form.component.ts, src/app/psat/psat-report/output-summary/output-summary.component.html, src/app/psat/psat-report/output-summary/output-summary.component.ts, src/app/shared/models/psat.ts
connects #3656 
- Show assessment selected energy projects and mods in PSAT report
- Remove 'this' refs from FSAT templates
=> Reflect PSAT selected opps in report

src/app/fsat/explore-opportunities/explore-opportunities-form/system-data-form/system-data-form.component.html, src/app/shared/shared-pipes/option-display-value.pipe.spec.ts, src/app/shared/shared-pipes/option-display-value.pipe.ts, src/app/shared/shared-pipes/shared-pipes.module.ts, src/app/ssmt/explore-opportunities/explore-opportunities-form/boiler-form/boiler-form.component.html, src/app/ssmt/explore-opportunities/explore-opportunities-form/boiler-form/boiler-form.component.ts, src/app/ssmt/explore-opportunities/explore-opportunities-form/header-form/condensate-handling-form/condensate-handling-form.component.html, src/app/ssmt/explore-opportunities/explore-opportunities-form/header-form/header-form.component.html, src/app/ssmt/explore-opportunities/explore-opportunities-form/operations-form/operations-form.component.html, src/app/ssmt/explore-opportunities/explore-opportunities-form/turbine-form/explore-condensing-turbine-form/explore-condensing-turbine-form.component.html, src/app/ssmt/explore-opportunities/explore-opportunities-form/turbine-form/explore-condensing-turbine-form/explore-condensing-turbine-form.component.ts, src/app/ssmt/explore-opportunities/explore-opportunities-form/turbine-form/explore-pressure-turbine-form/explore-pressure-turbine-form.component.html, src/app/ssmt/explore-opportunities/explore-opportunities-form/turbine-form/explore-turbine-form/explore-turbine-form.component.html, src/app/ssmt/explore-opportunities/explore-opportunities-form/turbine-form/explore-turbine-form/explore-turbine-form.component.ts, src/assets/styles/explore-opps.css
connects #3651 
- SSMT UI enhancement to place explore-opportunities baseline and modification selects side by side
- Add pipe to retrieve options list display value
- Add in missing FSAT validation error spans
=> Issue 3651

src/app/report-rollup/assessment-reports/assessment-reports.component.html, src/app/report-rollup/report-rollup-models.ts, src/app/report-rollup/report-rollup.module.ts, src/app/report-rollup/report-rollup.service.ts, src/app/report-rollup/ssmt-rollup/ssmt-rollup.component.css, src/app/report-rollup/treasure-hunt-rollup/treasure-hunt-rollup-print/treasure-hunt-rollup-print.component.css, src/app/report-rollup/treasure-hunt-rollup/treasure-hunt-rollup-print/treasure-hunt-rollup-print.component.html, src/app/report-rollup/treasure-hunt-rollup/treasure-hunt-rollup-print/treasure-hunt-rollup-print.component.spec.ts, src/app/report-rollup/treasure-hunt-rollup/treasure-hunt-rollup-print/treasure-hunt-rollup-print.component.ts, src/app/report-rollup/treasure-hunt-rollup/treasure-hunt-rollup.component.ts, src/app/shared/models/printing.ts, src/app/shared/print-options-menu/print-options-menu.component.html, src/app/shared/print-options-menu/print-options-menu.service.ts, src/app/treasure-hunt/treasure-hunt-report/executive-summary/utility-bar-chart/utility-bar-chart.component.ts, src/app/treasure-hunt/treasure-hunt-report/opportunity-summary/opportunity-summary.component.css, src/app/treasure-hunt/treasure-hunt-report/opportunity-summary/opportunity-summary.component.html, src/app/treasure-hunt/treasure-hunt-report/opportunity-summary/opportunity-summary.component.ts, src/app/treasure-hunt/treasure-hunt-report/treasure-hunt-report.component.ts, src/app/treasure-hunt/treasure-hunt-report/treasure-hunt-report.module.ts
connects #3461 
Adds printing for treasure hunt report rollup
Fixes opportunity summaries printing layout
Fixes opportunity summaries printing select opportunities functionality
=> Issue 3461

src/app/phast/explore-phast-opportunities/explore-phast-opportunities-form/explore-atmosphere-form/explore-atmosphere-form.component.html, src/app/phast/explore-phast-opportunities/explore-phast-opportunities-form/explore-atmosphere-form/explore-atmosphere-form.component.ts, src/app/phast/explore-phast-opportunities/explore-phast-opportunities-form/explore-charge-materials-form/explore-charge-materials-form.component.html, src/app/phast/explore-phast-opportunities/explore-phast-opportunities-form/explore-charge-materials-form/explore-charge-materials-form.component.ts, src/app/phast/explore-phast-opportunities/explore-phast-opportunities-form/explore-cooling-form/explore-cooling-form.component.html, src/app/phast/explore-phast-opportunities/explore-phast-opportunities-form/explore-cooling-form/explore-cooling-form.component.ts, src/app/phast/explore-phast-opportunities/explore-phast-opportunities-form/explore-fixtures-form/explore-fixtures-form.component.html, src/app/phast/explore-phast-opportunities/explore-phast-opportunities-form/explore-fixtures-form/explore-fixtures-form.component.ts, src/app/phast/explore-phast-opportunities/explore-phast-opportunities-form/explore-flue-gas-form/explore-flue-gas-form.component.html, src/app/phast/explore-phast-opportunities/explore-phast-opportunities-form/explore-flue-gas-form/explore-flue-gas-form.component.ts, src/app/phast/explore-phast-opportunities/explore-phast-opportunities-form/explore-leakage-form/explore-leakage-form.component.html, src/app/phast/explore-phast-opportunities/explore-phast-opportunities-form/explore-leakage-form/explore-leakage-form.component.ts, src/app/phast/explore-phast-opportunities/explore-phast-opportunities-form/explore-opening-form/explore-opening-form.component.html, src/app/phast/explore-phast-opportunities/explore-phast-opportunities-form/explore-opening-form/explore-opening-form.component.ts, src/app/phast/explore-phast-opportunities/explore-phast-opportunities-form/explore-operations-form/explore-operations-form.component.html, src/app/phast/explore-phast-opportunities/explore-phast-opportunities-form/explore-operations-form/explore-operations-form.component.ts, src/app/phast/explore-phast-opportunities/explore-phast-opportunities-form/explore-slag-form/explore-slag-form.component.html, src/app/phast/explore-phast-opportunities/explore-phast-opportunities-form/explore-slag-form/explore-slag-form.component.ts, src/app/phast/explore-phast-opportunities/explore-phast-opportunities-form/explore-system-efficiency-form/explore-system-efficiency-form.component.html, src/app/phast/explore-phast-opportunities/explore-phast-opportunities-form/explore-system-efficiency-form/explore-system-efficiency-form.component.ts, src/app/phast/explore-phast-opportunities/explore-phast-opportunities-form/explore-wall-form/explore-wall-form.component.html, src/app/phast/explore-phast-opportunities/explore-phast-opportunities-form/explore-wall-form/explore-wall-form.component.ts, src/app/phast/phast-compare.service.ts, src/app/phast/phast-report/executive-summary/executive-summary.component.html, src/app/phast/phast-report/executive-summary/executive-summary.component.ts, src/app/shared/models/explore-opps.ts, src/app/shared/models/phast/phast.ts
connects #3658 
- Show phast explore-opps changes in the report > executive-summary
=> Issue 3658

src/app/calculator/fans/fan-analysis/fan-analysis-form/gas-density-form/gas-density-form.component.html, src/app/calculator/fans/fan-analysis/help-and-results-panel/operating-points-help/gas-density-help/gas-density-help.component.html, src/app/dashboard/assessment.service.ts, src/app/fsat/fan-field-data/fan-field-data.component.html, src/app/fsat/fan-field-data/fan-field-data.component.ts, src/app/fsat/fanOptions.ts, src/app/fsat/fsat-fluid/fsat-fluid.component.html, src/app/fsat/fsat-report/input-summary/field-data-summary/field-data-summary.component.html, src/app/fsat/help-panel/fan-field-data-help/fan-field-data-help.component.html, src/app/fsat/help-panel/fsat-fluid-help/fsat-fluid-help.component.html, src/app/tutorials/fsat-report-tutorial/fsat-report-tutorial.component.html
connects #3592 
- Also removed Specific Heat Ratio from input-summary and fsat-help
- NOTE: images of specific heat form input still showing in fan tutorial (see issue)
=> Issue 3592

src/app/fsat/fsat-fluid/fsat-fluid.component.html, src/app/fsat/fsat-fluid/fsat-fluid.component.ts, src/app/fsat/help-panel/fsat-fluid-help/fsat-fluid-help.component.html
connects #3590 
- Remove density inputs when gas type is OTHER
- Cleanup fan language
=> Issue 3590

src/app/calculator/fans/fan-analysis/fan-analysis-form/gas-density-form/gas-density-form.component.html, src/app/dashboard/assessment.service.ts, src/app/fsat/fan-field-data/fan-field-data.component.html, src/app/fsat/fan-field-data/fan-field-data.component.ts, src/app/fsat/fsat-fluid/fsat-fluid.component.html, src/app/fsat/fsat-fluid/fsat-fluid.component.ts, src/app/fsat/fsat-report/input-summary/base-gas-density-summary/base-gas-density-summary.component.html, src/app/fsat/fsat-report/input-summary/field-data-summary/field-data-summary.component.html, src/app/fsat/help-panel/fan-field-data-help/fan-field-data-help.component.html
Fixes previous merge connecting #3592 
- Removed specific heat of gas, keep specific heat ratio
=> Issue 3592 (Refactored)

src/app/shared/models/explore-opps.ts, src/app/shared/models/fans.ts, src/app/shared/models/psat.ts, src/app/shared/models/steam/ssmt.ts, src/app/ssmt/explore-opportunities/explore-opportunities-form/boiler-form/boiler-form.component.html, src/app/ssmt/explore-opportunities/explore-opportunities-form/boiler-form/boiler-form.component.ts, src/app/ssmt/explore-opportunities/explore-opportunities-form/header-form/condensate-handling-form/condensate-handling-form.component.html, src/app/ssmt/explore-opportunities/explore-opportunities-form/header-form/condensate-handling-form/condensate-handling-form.component.ts, src/app/ssmt/explore-opportunities/explore-opportunities-form/header-form/header-form.component.html, src/app/ssmt/explore-opportunities/explore-opportunities-form/header-form/header-form.component.ts, src/app/ssmt/explore-opportunities/explore-opportunities-form/operations-form/operations-form.component.html, src/app/ssmt/explore-opportunities/explore-opportunities-form/operations-form/operations-form.component.ts, src/app/ssmt/explore-opportunities/explore-opportunities-form/turbine-form/explore-condensing-turbine-form/explore-condensing-turbine-form.component.ts, src/app/ssmt/explore-opportunities/explore-opportunities-form/turbine-form/explore-pressure-turbine-form/explore-pressure-turbine-form.component.ts, src/app/ssmt/explore-opportunities/explore-opportunities-form/turbine-form/explore-turbine-form/explore-turbine-form.component.ts, src/app/ssmt/explore-opportunities/explore-opportunities-form/turbine-form/turbine-form.component.html, src/app/ssmt/explore-opportunities/explore-opportunities-form/turbine-form/turbine-form.component.ts, src/app/ssmt/ssmt-report/executive-summary/executive-summary.component.html, src/app/ssmt/ssmt-report/executive-summary/executive-summary.component.ts
connects #3657 
Recreating PR #3666 to reset build status
=> Issue 3657

src/app/fsat/fsat-fluid/fsat-fluid.component.html
connects #3590 
- Fixing to still show Gas Density field to user when they have selected 'Other gas' for gas type
=> Issue 3590 (Refactor)

src/app/fsat/explore-opportunities/explore-opportunities-form/fan-data-form/fan-data-form.component.html, src/app/fsat/explore-opportunities/explore-opportunities-form/rated-motor-form/rated-motor-form.component.html, src/app/fsat/explore-opportunities/explore-opportunities-form/system-data-form/system-data-form.component.html, src/app/fsat/explore-opportunities/explore-opportunities-form/variable-frequency-drive-form/variable-frequency-drive-form.component.html, src/assets/styles/explore-opps.css
connects #3644 
- Adding mod-form widths to match steam/phast
- Fix conditional displays re: specified efficiency to display baseline/mod appropriately
=> Issue 3644 (Refactor)

src/app/dashboard/directory-dashboard/directory-items/assessment-item/fsat-summary-card/fsat-summary-card.component.ts, src/app/fsat/explore-opportunities/explore-opportunities.component.html, src/app/fsat/fsat-report/fsat-report-graphs/fsat-report-graphs-print/fsat-report-graphs-print.component.html, src/app/fsat/fsat-report/fsat-report-graphs/fsat-report-graphs.component.html, src/app/fsat/fsat-report/fsat-report-graphs/fsat-report-graphs.component.ts, src/app/fsat/fsat-report/fsat-report.component.html, src/app/fsat/fsat-report/fsat-report.component.ts, src/app/fsat/fsat-report/results-summary/results-summary.component.html, src/app/fsat/fsat-results/fsat-results-panel/fsat-results-panel.component.html, src/app/fsat/fsat-results/fsat-results-panel/fsat-results-panel.component.ts, src/app/fsat/fsat-sankey/fsat-sankey.component.html, src/app/fsat/fsat-sankey/fsat-sankey.component.ts, src/app/fsat/fsat-warning.service.ts, src/app/fsat/fsat.component.ts, src/app/fsat/fsat.service.ts, src/app/psat/explore-opportunities/explore-opportunities-results/explore-opportunities-results.component.html, src/app/psat/explore-opportunities/explore-opportunities-results/explore-opportunities-results.component.ts, src/app/psat/explore-opportunities/explore-opportunities.component.html, src/app/psat/explore-opportunities/explore-opportunities.component.ts, src/app/psat/help-panel/help-panel.component.ts, src/app/psat/psat-report/input-summary/input-summary.component.html, src/app/psat/psat-report/psat-report-graphs/psat-report-graphs-print/psat-report-graphs-print.component.html, src/app/psat/psat-report/psat-report-graphs/psat-report-graphs-print/psat-report-graphs-print.component.ts, src/app/psat/psat-report/psat-report-graphs/psat-report-graphs.component.html, src/app/psat/psat-report/psat-report-graphs/psat-report-graphs.component.ts, src/app/shared/models/fans.ts
connects #3663
connects #3660 
connects #3673 
Adds validation messages for fsat
Fixes updating results in explore opps for fsat
Additions to psat validation messages
=> Issue 3663

src/app/phast/explore-phast-opportunities/explore-phast-opportunities-form/explore-atmosphere-form/explore-atmosphere-form.component.ts, src/app/phast/explore-phast-opportunities/explore-phast-opportunities-form/explore-charge-materials-form/explore-charge-materials-form.component.ts, src/app/phast/explore-phast-opportunities/explore-phast-opportunities-form/explore-cooling-form/explore-cooling-form.component.ts, src/app/phast/explore-phast-opportunities/explore-phast-opportunities-form/explore-fixtures-form/explore-fixtures-form.component.ts, src/app/phast/explore-phast-opportunities/explore-phast-opportunities-form/explore-leakage-form/explore-leakage-form.component.ts, src/app/phast/explore-phast-opportunities/explore-phast-opportunities-form/explore-opening-form/explore-opening-form.component.ts, src/app/phast/explore-phast-opportunities/explore-phast-opportunities-form/explore-wall-form/explore-wall-form.component.ts
connects #3658 
Updating branch to fix bugs noted by @koay9f in https://app.zenhub.com/workspaces/measur-5c9d18415648dd20c601ea26/issues/ornl-amo/amo-tools-desktop/3652
=> Issue-3658 (Refactor)

.travis.yml, src/app/calculator/compressed-air/air-velocity/air-velocity-form/air-velocity-form.component.html, src/app/calculator/compressed-air/system-capacity/system-capacity.service.ts, src/app/shared/models/standalone.ts
Add additional pipe sizes to 'Velocity in Pipes' calculator. This issue should be merged AFTER the corresponding suite issue (issue 491).
=> Issue 3467

src/app/fsat/explore-opportunities/explore-opportunities-form/system-data-form/system-data-form.component.html, src/app/fsat/fsat-report/fsat-report-sankey/fsat-report-sankey.component.html, src/app/shared/print-options-menu/print-options-menu.component.html
Fixing stray compile errors from recent issues
=> Fix compile errors relating to ng-high-memory build

src/app/calculator/utilities/pre-assessment/pre-assessment-form/pre-assessment-form.component.html, src/app/phast/metered-energy/metered-fuel-form/metered-fuel-form.component.html
connects #3672 
- Adding /hr to units in Pre-assessment
- Verified metered fuel calculations to be accurate
=> Issue 3672

src/app/fsat/fsat-fluid/fsat-fluid.component.html
connects #3590 
- Change Air/Gas labels in assessment Gas Density form
=> Issue 3590 (post-verification)

src/app/fsat/explore-opportunities/explore-opportunities-form/fan-data-form/fan-data-form.component.html
connects #3592 
- Replace pump with fan
=> Issue-3592 (post-verification)

src/app/calculator/fans/fan-analysis/convert-fan-analysis.service.ts, src/app/shared/gas-density-results/gas-density-results.component.html
connects #3646
- Fix relative humidity errors found in needs verification
=> Issue 3646 

src/app/fsat/fsat-report/fsat-report-graphs/fsat-report-graphs-print/fsat-report-graphs-print.component.html, src/app/fsat/fsat-report/fsat-report-graphs/fsat-report-graphs.component.html, src/app/psat/psat-report/psat-report-graphs/psat-report-graphs.component.html, src/app/shared/print-options-menu/print-options-menu.component.html
connects #3602 
connects #3597 
fixes psat and fsat printing bugs
changes print options verbage
=> fixes to psat and fsat report graphs

src/app/phast/explore-phast-opportunities/explore-phast-opportunities-form/explore-atmosphere-form/explore-atmosphere-form.component.ts, src/app/phast/explore-phast-opportunities/explore-phast-opportunities-form/explore-cooling-form/explore-cooling-form.component.html
connects #3652 
- Fix ngIf causing uncentered form
- Fix atmosphere checkbox set false on init
=> Issue 3652 (post-verification)

src/app/fsat/explore-opportunities/explore-opportunities-form/rated-motor-form/rated-motor-form.component.html
connects #3701 
- Hide specified motor efficiency inputs when user toggles opportunity off
=> Issue-3701

src/app/shared/models/steam/ssmt.ts, src/app/ssmt/calculate-losses.service.ts, src/app/ssmt/ssmt-report/energy-summary/energy-summary.component.html, src/app/ssmt/ssmt-report/energy-summary/energy-summary.component.ts, src/app/ssmt/ssmt-report/executive-summary/executive-summary.component.html, src/app/ssmt/ssmt-report/input-summary/boiler-summary/boiler-summary.component.html, src/app/ssmt/ssmt-report/input-summary/boiler-summary/boiler-summary.component.ts, src/app/ssmt/ssmt-report/input-summary/header-summary/header-input-table/header-input-table.component.html, src/app/ssmt/ssmt-report/input-summary/header-summary/header-input-table/header-input-table.component.ts, src/app/ssmt/ssmt-report/input-summary/header-summary/header-summary.component.html, src/app/ssmt/ssmt-report/input-summary/header-summary/header-summary.component.ts, src/app/ssmt/ssmt-report/input-summary/operations-summary/operations-summary.component.html, src/app/ssmt/ssmt-report/input-summary/operations-summary/operations-summary.component.ts, src/app/ssmt/ssmt-report/input-summary/turbine-summary/turbine-summary.component.html, src/app/ssmt/ssmt-report/input-summary/turbine-summary/turbine-summary.component.ts, src/app/ssmt/ssmt-report/losses-summary/losses-summary.component.html, src/app/ssmt/ssmt-report/losses-summary/losses-summary.component.ts, src/app/ssmt/ssmt-report/report-diagram/report-diagram.component.html, src/app/ssmt/ssmt-report/report-diagram/report-diagram.component.ts, src/app/ssmt/ssmt-report/report-graphs/report-graphs.component.ts, src/app/ssmt/ssmt-report/report-graphs/ssmt-pie-chart/ssmt-pie-chart.component.html, src/app/ssmt/ssmt-report/report-graphs/ssmt-pie-chart/ssmt-pie-chart.component.ts, src/app/ssmt/ssmt-report/report-graphs/ssmt-waterfall/ssmt-waterfall.component.html, src/app/ssmt/ssmt-report/report-graphs/ssmt-waterfall/ssmt-waterfall.component.ts, src/app/ssmt/ssmt-report/ssmt-report.component.ts, src/app/ssmt/ssmt.component.ts, src/app/ssmt/ssmt.service.ts
connects #3681 
- Add invalid messaging for SSMT modifications
=> Issue 3681

src/app/log-tool/visualize/visualize-graph/visualize-graph.component.ts, src/app/log-tool/visualize/visualize-menu/visualize-menu.component.css, src/app/log-tool/visualize/visualize-menu/visualize-menu.component.html, src/app/log-tool/visualize/visualize-menu/visualize-menu.component.ts, src/app/log-tool/visualize/visualize.component.html
connects #3709 
adds sidebar collapsing to the visualization manu
=> Issue 3709

src/app/calculator/compressed-air/compressedAirConstants.ts, src/app/calculator/compressed-air/system-capacity/system-capacity-form/system-capacity-form.component.css, src/app/calculator/compressed-air/system-capacity/system-capacity-form/system-capacity-form.component.html, src/app/calculator/compressed-air/system-capacity/system-capacity-form/system-capacity-form.component.ts, src/app/calculator/compressed-air/system-capacity/system-capacity.component.html, src/app/calculator/compressed-air/system-capacity/system-capacity.component.ts, src/app/calculator/compressed-air/system-capacity/system-capacity.service.ts, src/app/calculator/standalone.service.ts, src/app/shared/models/standalone.ts
connects: 
#3468  
#2334 
#3717
=> Issue 3468

src/app/shared/models/treasure-hunt.ts, src/app/treasure-hunt/treasure-chest/opportunity-cards/sort-cards-by.pipe.ts, src/app/treasure-hunt/treasure-chest/opportunity-cards/sort-cards.service.ts, src/app/treasure-hunt/treasure-chest/treasure-chest-menu/treasure-chest-menu.component.css, src/app/treasure-hunt/treasure-chest/treasure-chest-menu/treasure-chest-menu.component.html, src/app/treasure-hunt/treasure-chest/treasure-chest-menu/treasure-chest-menu.component.ts, src/app/treasure-hunt/treasure-chest/treasure-chest-menu/treasure-chest-menu.service.ts
connects #3584 
- Add ability to select multiple filters
- Add card/calc count to filter dropdown rows
=> Issue 3584 

src/app/dashboard/landing-screen/landing-screen.component.html
=> fix issue 3728

src/app/phast/losses/energy-input/energy-input.component.ts, src/app/phast/losses/energy-input/energy-input.service.ts, src/app/phast/losses/losses-help/energy-input-help/energy-input-help.component.html
- Add defaults and help text for EAF coalHeating and electrode
=> Issue 3703

src/app/calculator/utilities/compressed-air-reduction/compressed-air-reduction-form/compressed-air-reduction-form.component.html, src/app/calculator/utilities/compressed-air-reduction/compressed-air-reduction-form/compressed-air-reduction-form.component.ts
connects #3730 
- Fix result not showing for specific power (needs two decimal places)
=> Issue 3730

src/app/calculator/fans/fan-analysis/help-and-results-panel/operating-points-help/fan-shaft-power-help/fan-shaft-power-help.component.html, src/app/fsat/help-panel/fan-motor-help/fan-motor-help.component.html, src/app/psat/explore-opportunities/explore-opportunities-help/explore-opportunities-help.component.html, src/app/psat/help-panel/motor-help/motor-help.component.html
connects #3696 
Add help text for pumps/fans motor efficiency
=> Issue 3696

src/app/calculator/compressed-air/operating-cost/operating-cost-form/operating-cost-form.component.html
connects #3735 
add B to motor brake horsepower
=> Issue 3735

src/app/calculator/calculator-routing/calculators.routing.ts, src/app/calculator/calculator-routing/process-cooling.routing.ts, src/app/calculator/calculator.module.ts, src/app/calculator/calculators-list/calculators-list.component.html, src/app/calculator/process-cooling/process-cooling-list/process-cooling-list.component.css, src/app/calculator/process-cooling/process-cooling-list/process-cooling-list.component.html, src/app/calculator/process-cooling/process-cooling-list/process-cooling-list.component.spec.ts, src/app/calculator/process-cooling/process-cooling-list/process-cooling-list.component.ts, src/app/calculator/process-cooling/process-cooling.module.ts, src/app/core/core.routing.ts, src/app/dashboard/landing-screen/landing-screen.component.html, src/app/dashboard/sidebar/calculator-list/calculator-list.component.html, src/assets/styles/tabs.css, src/assets/styles/two-panel.css, src/assets/styles/utilities.css
connects #3743 
Add process cooling calculator folder and module
=> Issue 3743

src/app/calculator/steam/stack-loss/boiler-efficiency-modal/boiler-efficiency-modal.component.html, src/app/calculator/steam/stack-loss/boiler-efficiency-modal/boiler-efficiency-modal.component.ts, src/app/calculator/steam/stack-loss/stack-loss-form/stack-loss-by-mass/stack-loss-by-mass.component.html, src/app/calculator/steam/stack-loss/stack-loss-form/stack-loss-by-mass/stack-loss-by-mass.component.ts, src/app/calculator/steam/stack-loss/stack-loss-form/stack-loss-by-volume/stack-loss-by-volume.component.css, src/app/calculator/steam/stack-loss/stack-loss-form/stack-loss-by-volume/stack-loss-by-volume.component.html, src/app/calculator/steam/stack-loss/stack-loss-form/stack-loss-by-volume/stack-loss-by-volume.component.ts, src/app/calculator/steam/stack-loss/stack-loss-form/stack-loss-form.component.html, src/app/calculator/steam/stack-loss/stack-loss-form/stack-loss-form.component.ts, src/app/calculator/steam/stack-loss/stack-loss.component.css, src/app/calculator/steam/stack-loss/stack-loss.component.html, src/app/calculator/steam/stack-loss/stack-loss.component.ts, src/app/calculator/steam/stack-loss/stack-loss.module.ts, src/app/calculator/steam/stack-loss/stack-loss.service.ts, src/app/phast/phast.service.ts, src/app/suiteDb/suiteDb.module.ts
=> Issue 3506

src/app/fsat/fsat-fluid/fsat-fluid.component.html
connects #3749 
Hide Air Relative Density for gas type of AIR and all input methods
=> Issue 3749

src/app/calculator/fans/fan-efficiency/fan-efficiency-help/fan-efficiency-help.component.html, src/app/fsat/help-panel/fan-setup-help/fan-setup-help.component.html
connects #3750 
Corrects help text for fan type
=> Issue-3750

src/app/fsat/calculate-pressures/calculate-inlet-pressure/calculate-inlet-pressure-help/calculate-inlet-pressure-help.component.html, src/app/fsat/calculate-pressures/calculate-inlet-pressure/calculate-inlet-pressure.component.html, src/app/fsat/calculate-pressures/calculate-inlet-pressure/calculate-inlet-pressure.component.ts, src/app/fsat/calculate-pressures/calculate-outlet-pressure/calculate-outlet-pressure-help/calculate-outlet-pressure-help.component.html, src/app/fsat/calculate-pressures/calculate-outlet-pressure/calculate-outlet-pressure.component.html, src/app/fsat/calculate-pressures/calculate-outlet-pressure/calculate-outlet-pressure.component.ts, src/app/fsat/fan-field-data/fan-field-data.component.ts, src/app/shared/models/fans.ts
connects #3751 
Add new fields to inlet/outlet estimation modals
=> issue-3751

src/app/log-tool/system-setup/clean-data/clean-data.component.css, src/app/log-tool/system-setup/clean-data/clean-data.component.html, src/app/log-tool/system-setup/system-setup.component.html
quick fix for scrolling in setup screens
=> add scrolling to log tool setup screen

package.json, src/app/dashboard/sidebar/version-modal/version-modal.component.html
connects #3792 
updates version numbers for suite and desktop
=> Release notes

src/app/calculator/compressed-air/pipe-sizing/pipe-sizing-form/pipe-sizing-form.component.html, src/app/calculator/compressed-air/pipe-sizing/pipe-sizing.service.ts, src/app/calculator/compressed-air/receiver-tank/air-capacity-form/air-capacity-form.component.html, src/app/calculator/compressed-air/receiver-tank/dedicated-storage-form/dedicated-storage-form.component.html, src/app/calculator/compressed-air/receiver-tank/delay-method-form/delay-method-form.component.html, src/app/calculator/compressed-air/receiver-tank/general-method-form/general-method-form.component.html, src/app/calculator/compressed-air/receiver-tank/metered-storage-form/metered-storage-form.component.html, src/app/calculator/compressed-air/receiver-tank/receiver-tank.service.ts, src/app/calculator/standalone.service.ts
connects #3729 
- Modify compressed air units, cfm -> scfm, psi -> psig
- Changed unit conversion to be semantically accurate, though the value does not change
=> Issue 3729

src/app/fsat/fan-field-data/fan-field-data.component.html, src/app/fsat/fan-field-data/fan-field-data.component.ts, src/app/fsat/fan-motor/fan-motor.component.html, src/app/fsat/fsat-warning.service.ts, src/app/fsat/help-panel/fan-field-data-help/fan-field-data-help.component.html, src/app/fsat/help-panel/fan-motor-help/fan-motor-help.component.html, src/app/psat/help-panel/motor-help/motor-help.component.html, src/app/psat/motor/motor.component.html, src/app/psat/motor/motor.component.ts, src/app/psat/psat-warning.service.ts
connects #3626 
- Advise user to recalculate when inputs change
=> Issue 3626

src/app/psat/psat.service.ts
=> fix calculation call causing crash in psat

src/app/indexedDb/indexed-db.service.ts, src/app/log-tool/day-type-analysis/day-type-analysis.component.ts, src/app/log-tool/day-type-analysis/day-types/day-types.component.ts, src/app/log-tool/log-tool-data.service.ts, src/app/log-tool/log-tool-db.service.spec.ts, src/app/log-tool/log-tool-db.service.ts, src/app/log-tool/log-tool-models.ts, src/app/log-tool/log-tool.component.ts, src/app/log-tool/log-tool.module.ts, src/app/log-tool/log-tool.service.ts, src/app/log-tool/system-setup/clean-data/clean-data.component.ts, src/app/log-tool/system-setup/setup-data/setup-data.component.html, src/app/log-tool/system-setup/setup-data/setup-data.component.ts, src/app/log-tool/visualize/visualize-graph/visualize-graph.component.ts
connects #3778 
log tool data saving in indexedDb and logic setup for using on next session.
indexeddb version 5
=> Issue 3778

src/app/log-tool/log-tool-data.service.ts, src/app/log-tool/visualize/visualize-data/visualize-data.component.html, src/app/log-tool/visualize/visualize-data/visualize-data.component.ts, src/app/log-tool/visualize/visualize-graph/visualize-graph.component.ts, src/app/log-tool/visualize/visualize.service.ts
connects #3780 
Data tables matching graphs in visualization tab.
=> Issue 3780

src/app/calculator/pumps/specific-speed/specific-speed-form/specific-speed-form.component.ts, src/app/calculator/pumps/specific-speed/specific-speed-graph/specific-speed-graph.component.css, src/app/calculator/pumps/specific-speed/specific-speed-graph/specific-speed-graph.component.html, src/app/calculator/pumps/specific-speed/specific-speed-graph/specific-speed-graph.component.ts, src/app/calculator/pumps/specific-speed/specific-speed.component.html, src/app/calculator/pumps/specific-speed/specific-speed.component.ts, src/app/calculator/pumps/specific-speed/specific-speed.service.ts, src/app/shared/models/plotting.ts
connects #3802 
Use Plotly for pump -> specific speed
=> Issue 3802 

src/app/calculator/compressed-air/air-flow-conversion/air-flow-conversion-form/air-flow-conversion-form.component.html, src/app/calculator/compressed-air/air-flow-conversion/air-flow-conversion-help/air-flow-conversion-help.component.html, src/app/calculator/compressed-air/air-flow-conversion/air-flow-conversion-results/air-flow-conversion-results.component.html, src/app/calculator/compressed-air/air-flow-conversion/air-flow-conversion.component.html, src/app/calculator/compressed-air/compressed-air-list/compressed-air-list.component.html, src/app/dashboard/sidebar/calculator-list/calculator-list.component.html
connects #3813 
Remove ACFM/SCFM units in converted, change to Airflow
=> Issue 3813

src/app/core/mockPhast.ts, src/app/core/mockPsat.ts, src/app/core/mockSsmt.ts, src/app/core/mockTreasureHunt.ts
connects #3810 
Use consistent example names
=> Issue-3810

src/app/calculator/compressed-air/compressed-air-pressure-reduction/compressed-air-pressure-reduction-form/compressed-air-pressure-reduction-form.component.html, src/app/calculator/compressed-air/compressed-air-pressure-reduction/compressed-air-pressure-reduction-results/compressed-air-pressure-reduction-results.component.html
connects #3814 
Update pressure reduction labels and results property
=> Issue 3814

src/app/ssmt/help-panel/header-help/header-help.component.html
connects #3620
Add help text for ssmt Heat Loss field
=> Issue 3620

src/app/calculator/fans/fan-analysis/fan-analysis-form/gas-density-form/gas-density-form.service.ts, src/app/calculator/utilities/fan-psychrometric/fan-psychrometric-form/fan-psychrometric-form.component.html, src/app/calculator/utilities/fan-psychrometric/fan-psychrometric-form/fan-psychrometric-form.component.ts, src/app/calculator/utilities/fan-psychrometric/fan-psychrometric.component.html, src/app/calculator/utilities/fan-psychrometric/fan-psychrometric.component.ts, src/app/calculator/utilities/fan-psychrometric/fan-psychrometric.service.ts
connects #3667 
- Fix validation for relative humidity, require greater than 0
- Convert barometric pressure calc to Hg when using imperial units
=> Issue-3667 (post-verification)

src/app/calculator/compressed-air/air-leak/air-leak.component.html, src/app/calculator/compressed-air/air-leak/facility-compressor-data-form/facility-compressor-data-form.component.html, src/app/calculator/compressed-air/air-leak/facility-compressor-data-form/facility-compressor-data-form.component.ts
=> fix utility cost form input in compressed air leak survey

src/app/log-tool/log-tool-models.ts, src/app/log-tool/visualize/visualize-menu/graph-basics/graph-basics.component.html, src/app/log-tool/visualize/visualize-menu/graph-basics/graph-basics.component.ts, src/app/log-tool/visualize/visualize-menu/visualize-menu.service.ts, src/app/log-tool/visualize/visualize.service.ts
add toggle between num and percent data points in histogram visualization menu
connects #3779
=> issue #3779

src/app/calculator/compressed-air/air-leak/air-leak.component.ts, src/app/calculator/compressed-air/air-leak/air-leak.service.ts, src/app/calculator/compressed-air/air-leak/facility-compressor-data-form/facility-compressor-data-form.component.ts
connects #3827 
fixes generate example and reset data buttons.
=> fix reset and generate example

src/app/calculator/process-cooling/cooling-tower/cooling-tower-form/cooling-tower-form.component.html
connects #3790 
Change form input order
=> Issue 3790

package.json, src/app/motor-inventory/motor-inventory-setup/motor-catalog/motor-catalog.service.ts, src/app/motor-inventory/motor-inventory-setup/motor-catalog/select-motor-modal/filter-motor-options.pipe.spec.ts, src/app/motor-inventory/motor-inventory-setup/motor-catalog/select-motor-modal/filter-motor-options.pipe.ts, src/app/motor-inventory/motor-inventory-setup/motor-catalog/select-motor-modal/filter-motors/filter-motors.component.css, src/app/motor-inventory/motor-inventory-setup/motor-catalog/select-motor-modal/filter-motors/filter-motors.component.html, src/app/motor-inventory/motor-inventory-setup/motor-catalog/select-motor-modal/filter-motors/filter-motors.component.spec.ts, src/app/motor-inventory/motor-inventory-setup/motor-catalog/select-motor-modal/filter-motors/filter-motors.component.ts, src/app/motor-inventory/motor-inventory-setup/motor-catalog/select-motor-modal/motor-options-table/motor-options-table.component.css, src/app/motor-inventory/motor-inventory-setup/motor-catalog/select-motor-modal/motor-options-table/motor-options-table.component.html, src/app/motor-inventory/motor-inventory-setup/motor-catalog/select-motor-modal/motor-options-table/motor-options-table.component.spec.ts, src/app/motor-inventory/motor-inventory-setup/motor-catalog/select-motor-modal/motor-options-table/motor-options-table.component.ts, src/app/motor-inventory/motor-inventory-setup/motor-catalog/select-motor-modal/select-motor-modal.component.css, src/app/motor-inventory/motor-inventory-setup/motor-catalog/select-motor-modal/select-motor-modal.component.html, src/app/motor-inventory/motor-inventory-setup/motor-catalog/select-motor-modal/select-motor-modal.component.ts, src/app/motor-inventory/motor-inventory.module.ts
connects #3845 
adds filtering in motor db modal
=> Issue 3845

src/app/dashboard/about-page/about-page.component.html, src/app/dashboard/about-page/about-page.component.ts
=> update about page for data explorer

src/app/calculator/steam/tank-insulation-reduction/tank-insulation-reduction.component.html, src/app/calculator/steam/tank-insulation-reduction/tank-insulation-reduction.component.ts, src/app/shared/models/treasure-hunt.ts, src/app/treasure-hunt/calculators/calculators.component.html, src/app/treasure-hunt/calculators/calculators.component.ts, src/app/treasure-hunt/calculators/calculators.module.ts, src/app/treasure-hunt/calculators/calculators.service.ts, src/app/treasure-hunt/convert-input-data.service.ts, src/app/treasure-hunt/find-treasure/find-treasure.component.html, src/app/treasure-hunt/find-treasure/find-treasure.component.ts, src/app/treasure-hunt/treasure-chest/export-opportunities/export-opportunities.component.html, src/app/treasure-hunt/treasure-chest/export-opportunities/export-opportunities.component.ts, src/app/treasure-hunt/treasure-chest/import-opportunities.service.ts, src/app/treasure-hunt/treasure-chest/opportunity-cards/opportunity-cards.component.html, src/app/treasure-hunt/treasure-chest/opportunity-cards/opportunity-cards.component.ts, src/app/treasure-hunt/treasure-chest/opportunity-cards/opportunity-cards.service.ts, src/app/treasure-hunt/treasure-chest/opportunity-cards/sort-cards.service.ts, src/app/treasure-hunt/treasure-chest/treasure-chest-menu/calculator-type-dropdown/calculator-type-dropdown.component.ts, src/app/treasure-hunt/treasure-hunt-report/opportunity-summary.service.ts, src/app/treasure-hunt/treasure-hunt.service.ts
connects #3834 
Adds tank insulation calculator to treasure hunt
=> Issue 3834

src/app/log-tool/system-setup/help-panel/help-panel.component.html
connects #3854 
update help text for data exploration setup
=> update data exploration help text

src/app/calculator/compressed-air/air-leak/air-leak-copy-table/air-leak-copy-table.component.html, src/app/calculator/compressed-air/air-leak/air-leak.component.html, src/app/calculator/compressed-air/air-leak/air-leak.component.ts, src/app/calculator/compressed-air/air-leak/air-leak.service.ts, src/app/calculator/compressed-air/air-leak/convert-air-leak.service.ts, src/app/calculator/compressed-air/air-leak/facility-compressor-data-form/facility-compressor-data-form.component.html, src/app/shared/models/treasure-hunt.ts, src/app/treasure-hunt/calculators/calculators.component.html, src/app/treasure-hunt/calculators/calculators.component.ts, src/app/treasure-hunt/calculators/calculators.module.ts, src/app/treasure-hunt/calculators/calculators.service.ts, src/app/treasure-hunt/convert-input-data.service.ts, src/app/treasure-hunt/find-treasure/find-treasure.component.html, src/app/treasure-hunt/find-treasure/find-treasure.component.ts, src/app/treasure-hunt/treasure-chest/export-opportunities/export-opportunities.component.html, src/app/treasure-hunt/treasure-chest/export-opportunities/export-opportunities.component.ts, src/app/treasure-hunt/treasure-chest/import-opportunities.service.ts, src/app/treasure-hunt/treasure-chest/opportunity-cards/opportunity-cards.component.ts, src/app/treasure-hunt/treasure-chest/opportunity-cards/opportunity-cards.service.ts, src/app/treasure-hunt/treasure-chest/opportunity-cards/sort-cards.service.ts, src/app/treasure-hunt/treasure-chest/treasure-chest-menu/calculator-type-dropdown/calculator-type-dropdown.component.ts, src/app/treasure-hunt/treasure-hunt-report/opportunity-summary.service.ts, src/app/treasure-hunt/treasure-hunt.service.ts
connects #3835 
Integrates Air Leak Survey into treasure hunt module.
Updates some bugs regarding units and layout within air leak survey calculator
=> Issue 3835

src/app/calculator/utilities/fan-psychrometric/fan-psychrometric-form/fan-psychrometric-form.component.html, src/app/calculator/utilities/fan-psychrometric/fan-psychrometric-help/fan-psychrometric-help.component.html, src/app/calculator/utilities/fan-psychrometric/fan-psychrometric.component.html
connects # 3667 
- Reduce button width 
- Add help text for altitude
=> Issue 3667 (post-verification)

src/app/calculator/compressed-air/air-flow-conversion/air-flow-conversion-form/air-flow-conversion-form.component.html, src/app/calculator/compressed-air/air-flow-conversion/air-flow-conversion-results/air-flow-conversion-results.component.html, src/app/calculator/compressed-air/air-flow-conversion/air-flow-conversion.component.html, src/app/calculator/compressed-air/pipe-sizing/pipe-sizing-form/pipe-sizing-form.component.html, src/app/calculator/compressed-air/receiver-tank/air-capacity-form/air-capacity-form.component.html, src/app/calculator/compressed-air/receiver-tank/dedicated-storage-form/dedicated-storage-form.component.html, src/app/calculator/compressed-air/receiver-tank/delay-method-form/delay-method-form.component.html, src/app/calculator/compressed-air/receiver-tank/general-method-form/general-method-form.component.html, src/app/calculator/compressed-air/receiver-tank/metered-storage-form/metered-storage-form.component.html, src/app/calculator/compressed-air/system-capacity/system-capacity-form/system-capacity-form.component.html
connects #3729 
- Add/Change metric units
=> Issue-3729 (post-verification)

src/app/fsat/fan-field-data/fan-field-data.component.html, src/app/fsat/fan-field-data/fan-field-data.component.ts, src/app/fsat/fan-field-data/fan-field-data.service.ts, src/app/fsat/fsat.service.ts
connects #3764 
still has a bug for specific heat ration = 1. The suite calculation will return NaN because it has (specificHeatRation -1)/x...  in the calculation
=> fix calculate compressibility factor bug

src/app/app.component.css, src/app/motor-inventory/motor-inventory-banner/motor-inventory-banner.component.css, src/app/motor-inventory/motor-inventory-setup/motor-properties/batch-analysis-properties/batch-analysis-properties.component.css, src/app/motor-inventory/motor-inventory-setup/motor-properties/load-characteristic-properties/load-characteristic-properties.component.css, src/app/motor-inventory/motor-inventory-setup/motor-properties/manual-specification-properties/manual-specification-properties.component.css, src/app/motor-inventory/motor-inventory-setup/motor-properties/nameplate-data-properties/nameplate-data-properties.component.css, src/app/motor-inventory/motor-inventory-setup/motor-properties/operation-data-properties/operation-data-properties.component.css, src/app/motor-inventory/motor-inventory-setup/motor-properties/other-properties/other-properties.component.css, src/app/motor-inventory/motor-inventory-setup/motor-properties/purchase-information-properties/purchase-information-properties.component.css, src/app/motor-inventory/motor-inventory-setup/motor-properties/torque-properties/torque-properties.component.css, src/assets/styles/tabs.css, src/assets/styles/two-panel.css
=> Issue 3876

src/app/calculator/pumps/achievable-efficiency/achievable-efficiency-graph/achievable-efficiency-graph.component.ts, src/app/psat/psatConstants.ts
connects #3808 
Add extended ranges for each pump type
=> Issue 3808 (Post Verification)

src/app/log-tool/visualize/visualize-menu/bin-data/bin-data.component.html, src/app/log-tool/visualize/visualize-menu/bin-data/bin-data.component.ts, src/app/log-tool/visualize/visualize-menu/visualize-menu.service.ts
=> add bin minnimum field for histogram

src/app/log-tool/visualize/visualize-menu/bin-data/bin-data.component.html, src/app/log-tool/visualize/visualize-menu/bin-data/bin-data.component.ts
connects #3863 
adds error check for bin data
=> add bin size error check

src/app/motor-inventory/motor-inventory.component.html, src/app/motor-inventory/motor-inventory.component.ts, src/app/shared/models/assessment.ts
add saving data functionality for testing
=> temporary saving motor inventory

src/app/calculator/utilities/cash-flow/cash-flow-diagram/cash-flow-diagram.component.css, src/app/calculator/utilities/cash-flow/cash-flow-diagram/cash-flow-diagram.component.html, src/app/calculator/utilities/cash-flow/cash-flow-diagram/cash-flow-diagram.component.ts, src/app/calculator/utilities/cash-flow/cash-flow.component.ts, src/app/calculator/utilities/cash-flow/cash-flow.service.ts, src/app/shared/models/plotting.ts
connects #3893 
Add Plotly chart to cash flow calc
=> Issue 3893

src/app/psat/psat-warning.service.ts
=> fix flow rate validation bug

src/app/calculator/furnaces/o2-enrichment/o2-enrichment.component.ts, src/app/shared/models/calculators.ts
=> hookup calc saving for o2 enrichment

src/app/calculator/compressed-air/air-leak/air-leak.component.html, src/app/calculator/compressed-air/air-leak/air-leak.component.ts, src/app/calculator/compressed-air/air-leak/air-leak.service.ts, src/app/calculator/compressed-air/air-leak/convert-air-leak.service.ts, src/app/calculator/compressed-air/air-leak/facility-compressor-data-form/facility-compressor-data-form.component.html, src/app/calculator/compressed-air/air-leak/facility-compressor-data-form/facility-compressor-data-form.component.ts
=> fix air leak survey issues in metric

src/app/calculator/compressed-air/receiver-tank/metered-storage-form/metered-storage-form.component.html
connects #3729 
- Fixing units
=> Isse 3729 (Needs-verification)

src/app/calculator/furnaces/o2-enrichment/enrichment-graph/enrichment-graph.component.ts, src/app/calculator/furnaces/o2-enrichment/o2-enrichment.service.ts
connects #1631 
- Add legend to cross reference copy table names vs traces
=> Issue 1631

src/app/calculator/compressed-air/air-leak/air-leak-form/estimate-method-form/estimate-method-form.component.html, src/app/calculator/compressed-air/air-leak/air-leak.service.ts, src/app/calculator/compressed-air/air-leak/convert-air-leak.service.ts
=> fix conversions for air leak

src/app/calculator/motors/motor-performance/motor-performance-chart.service.ts, src/app/shared/models/plotting.ts
connects #3897 
Move legend to horizontal
=> Issue 3897 (post-verification)

src/app/calculator/fans/fan-analysis/fan-analysis-form/fan-info-form/fan-info-form.component.ts, src/app/calculator/fans/fan-analysis/fan-analysis-form/fan-info-form/fan-info-form.service.ts, src/app/calculator/fans/fan-analysis/fan-analysis-form/plane-data-form/plane-data-form.service.ts, src/app/fsat/calculate-pressures/calculate-flow-pressure/calculate-flow-pressure.component.html, src/app/fsat/calculate-pressures/calculate-flow-pressure/calculate-flow-pressure.component.ts, src/app/fsat/fan-field-data/fan-field-data.component.html, src/app/fsat/fan-field-data/fan-field-data.component.ts, src/app/fsat/fsat.service.ts, src/app/shared/models/fans.ts, src/assets/styles/utilities.css
connects #3752 
- Let user save unfinished form without applying to assessment
=> Issue 3752

src/app/calculator/fans/fan-analysis/fan-analysis-form/gas-density-form/gas-density-form.component.html, src/app/calculator/fans/fan-analysis/fan-analysis-form/gas-density-form/gas-density-form.component.ts, src/app/calculator/fans/fan-analysis/fan-analysis-form/gas-density-form/gas-density-form.service.ts, src/app/dashboard/directory-dashboard/directory-items/assessment-item/fsat-summary-card/fsat-summary-card.component.ts, src/app/fsat/fsat-fluid/fsat-fluid.component.html, src/app/fsat/fsat-fluid/fsat-fluid.component.ts, src/app/fsat/fsat-fluid/fsat-fluid.service.ts, src/app/fsat/fsat-report/fsat-report.component.ts, src/app/fsat/fsat-results/fsat-results-panel/fsat-results-panel.component.ts, src/app/fsat/fsat-sankey/fsat-sankey.component.ts, src/app/fsat/fsat-tabs/fsat-tabs.component.ts, src/app/fsat/fsat-warning.service.ts, src/app/fsat/fsat.component.ts, src/app/fsat/fsat.service.ts, src/app/fsat/modify-conditions/modify-conditions-tabs/modify-conditions-tabs.component.ts, src/app/indexedDb/indexed-db.service.ts
connects #3823 
updates validation for base gas density forms to use dry bulb temp as maximum for wet bulb temp and dew point
=> Issue 3823

src/app/log-tool/visualize/visualize-menu/bin-data/bin-data.component.ts, src/app/log-tool/visualize/visualize-menu/visualize-menu.service.ts
=> fixes to binning by size and num bins

src/app/phast/losses/energy-input/energy-input-form/energy-input-form.component.html, src/app/phast/phast.service.ts
=> add metric units and conversion for eaf flow rate

src/app/calculator/system-and-equipment-curve/equipment-curve/by-data-form/by-data-form.component.css, src/app/calculator/system-and-equipment-curve/equipment-curve/by-data-form/by-data-form.component.html, src/app/calculator/system-and-equipment-curve/equipment-curve/by-data-form/by-data-form.component.ts, src/app/calculator/system-and-equipment-curve/equipment-curve/by-equation-form/by-equation-form.component.html, src/app/calculator/system-and-equipment-curve/equipment-curve/by-equation-form/by-equation-form.component.ts, src/app/calculator/system-and-equipment-curve/equipment-curve/equipment-curve.component.html, src/app/calculator/system-and-equipment-curve/equipment-curve/equipment-curve.service.ts, src/app/calculator/system-and-equipment-curve/regression-equations.service.ts, src/app/calculator/system-and-equipment-curve/system-and-equipment-curve-graph/system-and-equipment-curve-graph.component.css, src/app/calculator/system-and-equipment-curve/system-and-equipment-curve-graph/system-and-equipment-curve-graph.component.html, src/app/calculator/system-and-equipment-curve/system-and-equipment-curve-graph/system-and-equipment-curve-graph.component.ts, src/app/calculator/system-and-equipment-curve/system-and-equipment-curve-graph/system-and-equipment-curve-graph.service.ts, src/app/calculator/system-and-equipment-curve/system-and-equipment-curve.component.ts, src/app/calculator/system-and-equipment-curve/system-and-equipment-curve.module.ts, src/app/calculator/system-and-equipment-curve/system-and-equipment-curve.service.ts, src/app/core/mockFsat.ts, src/app/core/mockPsat.ts, src/app/shared/models/plotting.ts, src/app/shared/models/system-and-equipment-curve.ts
connects #2380 
Add power as Y axis option, calculate efficiency for intersections
=> Issue 2380

src/app/shared/models/treasure-hunt.ts, src/app/treasure-hunt/treasure-hunt-report/executive-summary/executive-summary-table/executive-summary-table.component.html, src/app/treasure-hunt/treasure-hunt-report/executive-summary/executive-summary-table/executive-summary-table.component.ts, src/app/treasure-hunt/treasure-hunt-report/executive-summary/team-summary-table/team-summary-table.component.html, src/app/treasure-hunt/treasure-hunt-report/executive-summary/team-summary-table/team-summary-table.component.ts, src/app/treasure-hunt/treasure-hunt-report/opportunity-summary.service.ts, src/app/treasure-hunt/treasure-hunt-report/opportunity-summary/opportunity-summary-copy-table/opportunity-summary-copy-table.component.css, src/app/treasure-hunt/treasure-hunt-report/opportunity-summary/opportunity-summary-copy-table/opportunity-summary-copy-table.component.html, src/app/treasure-hunt/treasure-hunt-report/opportunity-summary/opportunity-summary-copy-table/opportunity-summary-copy-table.component.spec.ts, src/app/treasure-hunt/treasure-hunt-report/opportunity-summary/opportunity-summary-copy-table/opportunity-summary-copy-table.component.ts, src/app/treasure-hunt/treasure-hunt-report/opportunity-summary/opportunity-summary.component.html, src/app/treasure-hunt/treasure-hunt-report/opportunity-summary/opportunity-summary.component.ts, src/app/treasure-hunt/treasure-hunt-report/treasure-hunt-report.module.ts
=> add copy table buttons to treasure hunt report

src/app/shared/models/treasure-hunt.ts, src/app/treasure-hunt/treasure-hunt-report/executive-summary/executive-summary-table/executive-summary-table.component.html, src/app/treasure-hunt/treasure-hunt-report/executive-summary/executive-summary-table/executive-summary-table.component.ts, src/app/treasure-hunt/treasure-hunt-report/executive-summary/team-summary-table/team-summary-table.component.html, src/app/treasure-hunt/treasure-hunt-report/executive-summary/team-summary-table/team-summary-table.component.ts, src/app/treasure-hunt/treasure-hunt-report/opportunity-payback/opportunity-payback-bar-chart/opportunity-payback-bar-chart.component.ts, src/app/treasure-hunt/treasure-hunt-report/opportunity-payback/opportunity-payback-donut/opportunity-payback-donut.component.ts, src/app/treasure-hunt/treasure-hunt-report/opportunity-payback/opportunity-payback.component.html, src/app/treasure-hunt/treasure-hunt-report/opportunity-summary.service.ts, src/app/treasure-hunt/treasure-hunt-report/opportunity-summary/opportunity-summary-copy-table/opportunity-summary-copy-table.component.css, src/app/treasure-hunt/treasure-hunt-report/opportunity-summary/opportunity-summary-copy-table/opportunity-summary-copy-table.component.html, src/app/treasure-hunt/treasure-hunt-report/opportunity-summary/opportunity-summary-copy-table/opportunity-summary-copy-table.component.spec.ts, src/app/treasure-hunt/treasure-hunt-report/opportunity-summary/opportunity-summary-copy-table/opportunity-summary-copy-table.component.ts, src/app/treasure-hunt/treasure-hunt-report/opportunity-summary/opportunity-summary.component.html, src/app/treasure-hunt/treasure-hunt-report/opportunity-summary/opportunity-summary.component.ts, src/app/treasure-hunt/treasure-hunt-report/treasure-hunt-report.module.ts
connects #3902 
updates layout for graph in opportunity payback page
should be merged after https://github.com/ORNL-AMO/AMO-Tools-Desktop/pull/3950
=> Issue 3902

package.json, src/app/phast/convert-phast.service.ts, src/app/phast/losses/energy-input/energy-input-form/energy-input-form.component.html, src/app/phast/losses/energy-input/energy-input-form/energy-input-form.component.ts, src/app/phast/losses/energy-input/energy-input.service.ts
=> convert flow rate input eaf for calculations and on unit changes

package.json, src/app/motor-inventory/motor-inventory-setup/department-catalog-table/department-catalog-table.component.html, src/app/motor-inventory/motor-inventory-setup/department-catalog-table/department-catalog-table.component.ts, src/app/motor-inventory/motor-inventory-setup/motor-catalog/nameplate-data/nameplate-data.component.html, src/app/motor-inventory/motor-inventory-setup/motor-catalog/nameplate-data/nameplate-data.component.ts
connects #3890 
fixes motor power unit in setup
=> Issue 3890

package.json, src/app/core/core.service.ts, src/app/core/mockMotorInventoryData.ts, src/app/indexedDb/inventory-db.service.ts, src/app/motor-inventory/motor-inventory.ts, src/app/settings/assessment-settings/reset-data-modal/reset-data-modal.component.ts
=> add example toy factor for motor inventory

package.json, src/app/calculator/system-and-equipment-curve/chart-hover-data/chart-hover-data.component.html, src/app/calculator/system-and-equipment-curve/chart-hover-data/chart-hover-data.component.ts, src/app/calculator/system-and-equipment-curve/curve-data.service.ts, src/app/calculator/system-and-equipment-curve/equipment-curve/by-data-form/by-data-form.component.html, src/app/calculator/system-and-equipment-curve/equipment-curve/by-equation-form/by-equation-form.component.html, src/app/calculator/system-and-equipment-curve/equipment-curve/by-equation-form/by-equation-form.component.ts, src/app/calculator/system-and-equipment-curve/equipment-curve/equipment-curve.component.html, src/app/calculator/system-and-equipment-curve/equipment-curve/equipment-curve.service.ts, src/app/calculator/system-and-equipment-curve/regression-equations.service.ts, src/app/calculator/system-and-equipment-curve/system-and-equipment-curve-graph/system-and-equipment-curve-graph.component.css, src/app/calculator/system-and-equipment-curve/system-and-equipment-curve-graph/system-and-equipment-curve-graph.component.html, src/app/calculator/system-and-equipment-curve/system-and-equipment-curve-graph/system-and-equipment-curve-graph.component.ts, src/app/calculator/system-and-equipment-curve/system-and-equipment-curve-graph/system-and-equipment-curve-graph.service.ts, src/app/calculator/system-and-equipment-curve/system-and-equipment-curve.component.ts, src/app/calculator/system-and-equipment-curve/system-and-equipment-curve.service.ts, src/app/core/mockFsat.ts, src/app/core/mockPsat.ts, src/app/shared/models/plotting.ts, src/app/shared/models/system-and-equipment-curve.ts
connects #2380 
- Changes to UI after last Thursday demo. Updating example data and other related pieces.
- Keeping comments to easily integrate 3756 branch
=> Improvements to Issue 2380

src/app/motor-inventory/motor-inventory-setup/motor-catalog/delete-motor-modal/delete-motor-modal.component.css, src/app/motor-inventory/motor-inventory-setup/motor-catalog/delete-motor-modal/delete-motor-modal.component.html, src/app/motor-inventory/motor-inventory-setup/motor-catalog/delete-motor-modal/delete-motor-modal.component.spec.ts, src/app/motor-inventory/motor-inventory-setup/motor-catalog/delete-motor-modal/delete-motor-modal.component.ts, src/app/motor-inventory/motor-inventory-setup/motor-catalog/motor-catalog.component.css, src/app/motor-inventory/motor-inventory-setup/motor-catalog/motor-catalog.component.html, src/app/motor-inventory/motor-inventory-setup/motor-catalog/motor-catalog.component.ts, src/app/motor-inventory/motor-inventory-setup/motor-catalog/motor-catalog.module.ts, src/app/motor-inventory/motor-inventory-setup/motor-catalog/select-motor-modal/select-motor-modal.component.ts, src/app/motor-inventory/motor-inventory.service.ts
=> add delete motor functionality to catlog setup

src/app/calculator/compressed-air/air-leak/convert-air-leak.service.ts, src/app/calculator/compressed-air/compressed-air-reduction/compressed-air-reduction.service.ts
connects #3928 
fixes default utility costs
=> Issue 3928

src/app/dashboard/create-inventory/create-inventory.component.ts, src/app/dashboard/directory-dashboard/directory-dashboard.module.ts, src/app/dashboard/directory-dashboard/directory-items/inventory-item/inventory-item.component.css, src/app/dashboard/directory-dashboard/directory-items/inventory-item/inventory-item.component.html, src/app/dashboard/directory-dashboard/directory-items/inventory-item/inventory-item.component.ts, src/app/dashboard/directory-dashboard/directory-items/inventory-item/motor-inventory-card/motor-inventory-card.component.css, src/app/dashboard/directory-dashboard/directory-items/inventory-item/motor-inventory-card/motor-inventory-card.component.html, src/app/dashboard/directory-dashboard/directory-items/inventory-item/motor-inventory-card/motor-inventory-card.component.spec.ts, src/app/dashboard/directory-dashboard/directory-items/inventory-item/motor-inventory-card/motor-inventory-card.component.ts, src/app/motor-inventory/batch-analysis/batch-analysis-banner/batch-analysis-banner.component.css, src/app/motor-inventory/batch-analysis/batch-analysis-banner/batch-analysis-banner.component.html
connects #3847 
add batch analysis data to inventory card in folders
updates inventory card style (WIP)
=> Issue 3847

src/app/dashboard/acknowledgments-page/acknowledgments-page.component.html
connects #3960 
Add Nick and Alex to Acknowledgements
=> Issue 3960

src/app/calculator/compressed-air/air-leak/air-leak.component.html, src/app/calculator/compressed-air/compressed-air-reduction/compressed-air-reduction-form/compressed-air-reduction-form.component.ts, src/app/calculator/compressed-air/compressed-air-reduction/convert-compressed-air-reduction.service.ts
=> convert specific power values from compressor type

src/app/core/mockTreasureHunt.ts
=> remove trailing decimals in th example

src/app/calculator/system-and-equipment-curve/chart-hover-data/chart-hover-data.component.html, src/app/calculator/system-and-equipment-curve/chart-hover-data/chart-hover-data.component.ts, src/app/calculator/system-and-equipment-curve/curve-data.service.ts, src/app/calculator/system-and-equipment-curve/equipment-curve/by-data-form/by-data-form.component.ts, src/app/calculator/system-and-equipment-curve/equipment-curve/by-equation-form/by-equation-form.component.ts, src/app/calculator/system-and-equipment-curve/equipment-curve/equipment-curve-form/equipment-curve-form.component.ts, src/app/calculator/system-and-equipment-curve/equipment-curve/equipment-curve.service.ts, src/app/calculator/system-and-equipment-curve/regression-equations.service.ts, src/app/calculator/system-and-equipment-curve/system-and-equipment-curve-graph/system-and-equipment-curve-graph.component.html, src/app/calculator/system-and-equipment-curve/system-and-equipment-curve-graph/system-and-equipment-curve-graph.component.ts, src/app/calculator/system-and-equipment-curve/system-and-equipment-curve-help/fan-system-curve-help/fan-system-curve-help.component.html, src/app/calculator/system-and-equipment-curve/system-and-equipment-curve-help/pump-curve-help/pump-curve-help.component.html, src/app/calculator/system-and-equipment-curve/system-and-equipment-curve-help/pump-system-curve-help/pump-system-curve-help.component.html, src/app/calculator/system-and-equipment-curve/system-and-equipment-curve.service.ts, src/app/calculator/system-and-equipment-curve/system-curve/fan-system-curve-form.service.ts, src/app/calculator/system-and-equipment-curve/system-curve/fan-system-curve-form/fan-system-curve-form.component.html, src/app/calculator/system-and-equipment-curve/system-curve/fan-system-curve-form/fan-system-curve-form.component.ts, src/app/calculator/system-and-equipment-curve/system-curve/pump-system-curve-form.service.ts, src/app/calculator/system-and-equipment-curve/system-curve/pump-system-curve-form/pump-system-curve-form.component.html, src/app/calculator/system-and-equipment-curve/system-curve/pump-system-curve-form/pump-system-curve-form.component.ts
Cleaning up before final merge of system-curve branch #3756
=> System curve cleanup

src/app/dashboard/about-page/about-page.component.html
connects #3511 
add opening paragraph for inventory in about page
=> issue 3511

src/app/phast/losses/energy-input/energy-input.component.ts, src/app/phast/phast-results.service.ts, src/app/shared/models/phast/phast.ts
connects #1872 
updates EAF exhaust gas calculation for when no exhaust gas loss is added
=> Issue 1872 b

src/app/calculator/steam/pipe-insulation-reduction/pipe-insulation-reduction.service.ts, src/app/calculator/steam/tank-insulation-reduction/tank-insulation-reduction.service.ts
fix tank and pipe insulation treasure hunt no modification bug
connects #3964
=> issue 3964

package.json, src/app/motor-inventory/batch-analysis/batch-analysis-graphs/batch-analysis-graphs.component.css, src/app/motor-inventory/batch-analysis/batch-analysis-graphs/batch-analysis-graphs.component.html, src/app/motor-inventory/batch-analysis/batch-analysis-graphs/energy-cost-pie-chart/energy-cost-pie-chart.component.ts, src/app/motor-inventory/motor-inventory-summary/inventory-summary-overview/inventory-summary-overview.component.css, src/app/motor-inventory/motor-inventory-summary/inventory-summary-overview/inventory-summary-overview.component.html
connects #3846 
add min height for summary graphs
=> issue 3846

src/app/phast/phast-results.service.ts
connects #1872 
more updates to EAF algorithm.
=> update EAF algorithm

src/app/dashboard/landing-screen/landing-screen.component.css, src/app/dashboard/landing-screen/landing-screen.component.html, src/app/dashboard/landing-screen/landing-screen.component.ts
connects #3992 
add inventory management to landing screen
=> add inventory management to landing screen

src/app/dashboard/sidebar/version-modal/version-modal.component.html
=> update release notes for v0.8.0-beta

src/app/calculator/system-and-equipment-curve/curve-data.service.ts, src/app/calculator/system-and-equipment-curve/equipment-curve/by-equation-form/by-equation-form.component.html, src/app/calculator/system-and-equipment-curve/system-and-equipment-curve-graph/system-and-equipment-curve-graph.component.ts, src/app/calculator/system-and-equipment-curve/system-and-equipment-curve-graph/system-and-equipment-curve-graph.service.ts, src/app/calculator/system-and-equipment-curve/system-and-equipment-curve.component.ts, src/app/calculator/system-and-equipment-curve/system-and-equipment-curve.service.ts, src/app/calculator/system-and-equipment-curve/system-curve/fan-system-curve-form.service.ts, src/app/calculator/system-and-equipment-curve/system-curve/fan-system-curve-form/fan-system-curve-form.component.html, src/app/calculator/system-and-equipment-curve/system-curve/fan-system-curve-form/fan-system-curve-form.component.ts, src/app/calculator/system-and-equipment-curve/system-curve/pump-system-curve-form.service.ts, src/app/calculator/system-and-equipment-curve/system-curve/pump-system-curve-form/pump-system-curve-form.component.html, src/app/calculator/system-and-equipment-curve/system-curve/pump-system-curve-form/pump-system-curve-form.component.ts
- Allow large inputs, set performance limits, breakout efficiency and power
=> System-curve bug fixes

src/app/motor-inventory/motor-inventory-setup/motor-catalog/select-motor-modal/filter-motor-options.pipe.ts, src/app/motor-inventory/motor-inventory-setup/motor-catalog/select-motor-modal/select-motor-modal.component.css
connects #4005 
fixes bug in motor list filtering
=> Issue 4005

src/app/calculator/furnaces/efficiency-improvement/efficiency-improvement-form/efficiency-improvement-form.component.css, src/app/calculator/furnaces/efficiency-improvement/efficiency-improvement-form/efficiency-improvement-form.component.html, src/app/calculator/furnaces/efficiency-improvement/efficiency-improvement-form/efficiency-improvement-form.component.ts, src/app/calculator/furnaces/efficiency-improvement/efficiency-improvement-graph.service.spec.ts, src/app/calculator/furnaces/efficiency-improvement/efficiency-improvement-graph.service.ts, src/app/calculator/furnaces/efficiency-improvement/efficiency-improvement-graph/efficiency-improvement-graph.component.css, src/app/calculator/furnaces/efficiency-improvement/efficiency-improvement-graph/efficiency-improvement-graph.component.html, src/app/calculator/furnaces/efficiency-improvement/efficiency-improvement-graph/efficiency-improvement-graph.component.spec.ts, src/app/calculator/furnaces/efficiency-improvement/efficiency-improvement-graph/efficiency-improvement-graph.component.ts, src/app/calculator/furnaces/efficiency-improvement/efficiency-improvement.component.html, src/app/calculator/furnaces/efficiency-improvement/efficiency-improvement.component.ts, src/app/calculator/furnaces/efficiency-improvement/efficiency-improvement.module.ts, src/app/calculator/furnaces/efficiency-improvement/efficiency-improvement.service.ts, src/app/shared/models/phast/efficiencyImprovement.ts
Add chart for efficiency improvement
=> Issue 3832

src/app/motor-inventory/batch-analysis/batch-analysis-graphs/batch-analysis-graphs.component.css, src/app/motor-inventory/batch-analysis/batch-analysis-graphs/batch-analysis-graphs.component.ts, src/app/motor-inventory/batch-analysis/batch-analysis.component.html, src/app/motor-inventory/motor-inventory.component.html
=> fix plotly batch analysis chart bug

src/app/motor-inventory/motor-inventory-setup/motor-catalog/batch-analysis-data/batch-analysis-data.component.html, src/app/motor-inventory/motor-inventory-setup/motor-catalog/batch-analysis-data/batch-analysis-data.component.ts, src/app/motor-inventory/motor-inventory-setup/motor-catalog/load-characteristic-data/load-characteristic-data.component.html, src/app/motor-inventory/motor-inventory-setup/motor-catalog/load-characteristic-data/load-characteristic-data.component.ts, src/app/motor-inventory/motor-inventory-setup/motor-catalog/manual-specification-data/manual-specification-data.component.html, src/app/motor-inventory/motor-inventory-setup/motor-catalog/manual-specification-data/manual-specification-data.component.ts, src/app/motor-inventory/motor-inventory-setup/motor-catalog/nameplate-data/nameplate-data.component.html, src/app/motor-inventory/motor-inventory-setup/motor-catalog/nameplate-data/nameplate-data.component.ts, src/app/motor-inventory/motor-inventory-setup/motor-catalog/operations-data/operations-data.component.html, src/app/motor-inventory/motor-inventory-setup/motor-catalog/operations-data/operations-data.component.ts, src/app/motor-inventory/motor-inventory-setup/motor-catalog/other-data/other-data.component.html, src/app/motor-inventory/motor-inventory-setup/motor-catalog/other-data/other-data.component.ts, src/app/motor-inventory/motor-inventory-setup/motor-catalog/purchase-information-data/purchase-information-data.component.html, src/app/motor-inventory/motor-inventory-setup/motor-catalog/purchase-information-data/purchase-information-data.component.ts, src/app/motor-inventory/motor-inventory-setup/motor-catalog/torque-data/torque-data.component.html, src/app/motor-inventory/motor-inventory-setup/motor-catalog/torque-data/torque-data.component.ts, src/app/motor-inventory/motor-inventory.service.ts
connects #4001 
add FLA and motor rated voltage as defaults
remove focus out for catalog setup
=> issue 4001

src/app/dashboard/sidebar/sidebar.component.css, src/app/dashboard/sidebar/sidebar.component.html, src/app/dashboard/sidebar/sidebar.component.ts, src/app/motor-inventory/motor-inventory-setup/motor-catalog/batch-analysis-data/batch-analysis-data.component.html, src/app/motor-inventory/motor-inventory-setup/motor-catalog/batch-analysis-data/batch-analysis-data.component.ts, src/app/motor-inventory/motor-inventory-setup/motor-catalog/load-characteristic-data/load-characteristic-data.component.html, src/app/motor-inventory/motor-inventory-setup/motor-catalog/load-characteristic-data/load-characteristic-data.component.ts, src/app/motor-inventory/motor-inventory-setup/motor-catalog/manual-specification-data/manual-specification-data.component.html, src/app/motor-inventory/motor-inventory-setup/motor-catalog/manual-specification-data/manual-specification-data.component.ts, src/app/motor-inventory/motor-inventory-setup/motor-catalog/nameplate-data/nameplate-data.component.html, src/app/motor-inventory/motor-inventory-setup/motor-catalog/nameplate-data/nameplate-data.component.ts, src/app/motor-inventory/motor-inventory-setup/motor-catalog/operations-data/operations-data.component.html, src/app/motor-inventory/motor-inventory-setup/motor-catalog/operations-data/operations-data.component.ts, src/app/motor-inventory/motor-inventory-setup/motor-catalog/other-data/other-data.component.html, src/app/motor-inventory/motor-inventory-setup/motor-catalog/other-data/other-data.component.ts, src/app/motor-inventory/motor-inventory-setup/motor-catalog/purchase-information-data/purchase-information-data.component.html, src/app/motor-inventory/motor-inventory-setup/motor-catalog/purchase-information-data/purchase-information-data.component.ts, src/app/motor-inventory/motor-inventory-setup/motor-catalog/torque-data/torque-data.component.html, src/app/motor-inventory/motor-inventory-setup/motor-catalog/torque-data/torque-data.component.ts, src/app/motor-inventory/motor-inventory.service.ts
connects #4014 
updates add new sidebar button to include inventory
=> Issue 4014

src/app/calculator/utilities/electricity-reduction/electricity-reduction-form/electricity-reduction-form.component.html, src/app/calculator/utilities/electricity-reduction/electricity-reduction-form/electricity-reduction-form.component.ts
=> electricity reduction handle VFD and line frequency changes

src/app/log-tool/log-tool.service.ts, src/app/log-tool/system-setup/help-panel/help-panel.component.html, src/app/log-tool/system-setup/setup-data/setup-data.component.css, src/app/log-tool/system-setup/setup-data/setup-data.component.html, src/app/log-tool/system-setup/setup-data/setup-data.component.ts, src/app/shared/helper-services/csv-to-json.service.ts
connects #3856 
updates data explorer to allow user to select header row when inputing files
=> Issue 3856

src/app/motor-inventory/motor-inventory.service.ts
=> full load speed on by default

src/app/log-tool/system-setup/help-panel/help-panel.component.html
=> add .csv clarificaton to help text

src/app/calculator/furnaces/efficiency-improvement/efficiency-improvement-graph.service.ts
=> Issue 3832 (Needs Verification)

src/app/calculator/system-and-equipment-curve/system-and-equipment-curve.service.ts
=> updated efficiency calculations for fan and pump curves

src/app/calculator/compressed-air/air-leak/air-leak-form/air-leak-form.service.ts, src/app/calculator/compressed-air/air-leak/air-leak-help/air-leak-help.component.html, src/app/calculator/compressed-air/air-leak/facility-compressor-data-form/facility-compressor-data-form.component.html, src/app/calculator/compressed-air/air-leak/facility-compressor-data-form/facility-compressor-data-form.component.ts, src/app/calculator/compressed-air/compressed-air-pressure-reduction/compressed-air-pressure-reduction.component.ts, src/app/calculator/compressed-air/compressed-air-reduction/compressed-air-reduction-form/compressed-air-reduction-form.component.html, src/app/calculator/compressed-air/compressed-air-reduction/compressed-air-reduction-form/compressed-air-reduction-form.component.ts, src/app/calculator/compressed-air/compressed-air-reduction/compressed-air-reduction-help/compressed-air-reduction-help.component.html, src/app/calculator/compressed-air/compressed-air-reduction/compressed-air-reduction.component.html, src/app/calculator/compressed-air/compressed-air-reduction/compressed-air-reduction.component.ts, src/app/calculator/compressed-air/compressed-air-reduction/compressed-air-reduction.service.ts, src/app/calculator/lighting/lighting-replacement/lighting-replacement.component.ts, src/app/calculator/motors/motor-drive/motor-drive.component.ts, src/app/calculator/motors/replace-existing/replace-existing.component.ts, src/app/calculator/process-cooling/cooling-tower/cooling-tower.component.ts, src/app/calculator/steam/pipe-insulation-reduction/pipe-insulation-reduction.component.ts, src/app/calculator/steam/steam-reduction/steam-reduction.component.ts, src/app/calculator/steam/tank-insulation-reduction/tank-insulation-reduction.component.ts, src/app/calculator/utilities/co2-savings/co2-savings.component.ts, src/app/calculator/utilities/electricity-reduction/electricity-reduction.component.ts, src/app/calculator/utilities/natural-gas-reduction/natural-gas-reduction.component.ts, src/app/calculator/utilities/water-reduction/water-reduction.component.ts
connects #4013 
updates dropdowns for compressors
fixes scrolling issue for treasure hunt calculators
=> Issue 4013

package.json, src/app/dashboard/sidebar/version-modal/version-modal.component.html
=> update release notes and version number for 0.8.1

src/app/calculator/system-and-equipment-curve/equipment-curve/equipment-curve.service.ts, src/app/calculator/system-and-equipment-curve/system-and-equipment-curve.service.ts
=> fix efficiency calculation for pump/fan curve in metric

src/app/calculator/steam/convert-steam.service.ts, src/app/dashboard/import-export/import.service.ts, src/app/shared/models/steam/steam-outputs.ts, src/app/ssmt/calculate-losses.service.ts, src/app/ssmt/ssmt-diagram/condensate-flash-tank/condensate-flash-tank.component.html, src/app/ssmt/ssmt-diagram/flash-tank-diagram/flash-tank-diagram.component.html, src/app/ssmt/ssmt-report/losses-summary/losses-summary.component.html
connects #4064 
fix vented steam losses and add returned steam and condensate energy calc
fix flash tank visual bug
=> issue 4064

src/app/ssmt/ssmt-report/losses-summary/losses-summary.component.html
=> move returned steam and condensate in table

src/app/calculator/system-and-equipment-curve/regression-equations.service.ts, src/app/calculator/system-and-equipment-curve/system-and-equipment-curve-graph/system-and-equipment-curve-graph.component.ts, src/app/calculator/system-and-equipment-curve/system-and-equipment-curve-graph/system-and-equipment-curve-graph.service.ts, src/app/calculator/system-and-equipment-curve/system-and-equipment-curve.service.ts
connects #3997 
-Add efficiency and power to user selected points
-Exponent in modification curve vs power lines should be different.
=> Issue 3997

src/app/dashboard/assessment-create/assessment-create.component.html, src/app/dashboard/assessment-create/assessment-create.component.ts, src/app/dashboard/assessment.service.ts, src/app/fsat/fsat.component.ts, src/app/phast/phast.component.html, src/app/phast/phast.component.ts, src/app/phast/system-basics/system-basics.component.ts, src/app/psat/psat.component.ts, src/app/settings/phast-settings/phast-settings.component.ts, src/app/ssmt/ssmt.component.ts, src/app/treasure-hunt/treasure-hunt.component.ts
connects #4040 
updates to clean up create assessment logic for all assessments using assessmentDb and settingsDb services.
=> Issue 4040

src/app/waste-water/waste-water.component.html, src/app/waste-water/waste-water.component.ts
connects #4051 
fix settings initialization
=> fix settings initialization

src/app/app.component.css
=> fix report summary th css font size

src/app/calculator/system-and-equipment-curve/system-and-equipment-curve-graph/system-and-equipment-curve-graph.component.ts, src/app/calculator/system-and-equipment-curve/system-and-equipment-curve-graph/system-and-equipment-curve-graph.service.ts
connects #3996 
Adds hover data for intersection points
=> Issue 3996

package.json, src/app/waste-water/waste-water-banner/modify-conditions-tabs/modify-conditions-tabs.component.css, src/app/waste-water/waste-water-banner/modify-conditions-tabs/modify-conditions-tabs.component.html, src/app/waste-water/waste-water-banner/modify-conditions-tabs/modify-conditions-tabs.component.ts, src/app/waste-water/waste-water-banner/setup-tabs/setup-tabs.component.html, src/app/waste-water/waste-water-banner/setup-tabs/setup-tabs.component.spec.ts, src/app/waste-water/waste-water-banner/setup-tabs/setup-tabs.component.ts, src/app/waste-water/waste-water-banner/waste-water-banner.component.html, src/app/waste-water/waste-water-banner/waste-water-banner.component.ts, src/app/waste-water/waste-water.component.html, src/app/waste-water/waste-water.component.ts, src/app/waste-water/waste-water.module.ts, src/assets/styles/tabs.css
connects #4052 
adds badges to tabs
add next/back functionality to footer in setup
=> Issue 4052

src/app/waste-water/activated-sludge-form/activated-sludge-form.component.html, src/app/waste-water/aerator-performance-form/aerator-performance-form.component.html, src/app/waste-water/aerator-performance-form/aerator-performance-form.component.ts, src/app/waste-water/aerator-performance-form/aerator-performance-form.service.ts, src/app/waste-water/results-panel/results-table/results-table.component.html, src/app/waste-water/waste-water-banner/modify-conditions-tabs/modify-conditions-tabs.component.css, src/app/waste-water/waste-water-banner/modify-conditions-tabs/modify-conditions-tabs.component.html, src/app/waste-water/waste-water-banner/modify-conditions-tabs/modify-conditions-tabs.component.ts, src/app/waste-water/waste-water-banner/setup-tabs/setup-tabs.component.html, src/app/waste-water/waste-water-banner/setup-tabs/setup-tabs.component.spec.ts, src/app/waste-water/waste-water-banner/setup-tabs/setup-tabs.component.ts, src/app/waste-water/waste-water-banner/waste-water-banner.component.html, src/app/waste-water/waste-water-banner/waste-water-banner.component.ts, src/app/waste-water/waste-water-report/result-data/result-data.component.html, src/app/waste-water/waste-water.component.html, src/app/waste-water/waste-water.component.ts, src/app/waste-water/waste-water.module.ts, src/assets/styles/tabs.css
connects #4071 
various updates from kristina first pass through waste water module
includes update from issue 4052
=> Issue 4071

src/app/dashboard/assessment.service.ts, src/app/shared/models/waste-water.ts, src/app/waste-water/results-panel/help-panel/system-basics-help/system-basics-help.component.html, src/app/waste-water/results-panel/results-table/results-table.component.html, src/app/waste-water/system-basics/system-basics.component.html, src/app/waste-water/system-basics/system-basics.service.ts, src/app/waste-water/waste-water-report/input-data/input-data.component.html, src/app/waste-water/waste-water-report/result-data/result-data.component.html, src/app/waste-water/waste-water.service.ts
connects #4083 
add operating months field and corresponding logic for annual cost and energy usage
=> add operating months

src/app/phast/losses/heat-system-efficiency/heat-system-efficiency.component.ts
=> fix system efficiency loss calculation

package.json, src/app/dashboard/assessment.service.ts, src/app/dashboard/directory-dashboard/directory-dashboard.component.html, src/app/dashboard/directory-dashboard/directory-dashboard.module.ts, src/app/dashboard/directory-dashboard/directory-items/assessment-item/assessment-item.component.html, src/app/dashboard/directory-dashboard/directory-items/assessment-item/waste-water-summary-card/waste-water-summary-card.component.css, src/app/dashboard/directory-dashboard/directory-items/assessment-item/waste-water-summary-card/waste-water-summary-card.component.html, src/app/dashboard/directory-dashboard/directory-items/assessment-item/waste-water-summary-card/waste-water-summary-card.component.spec.ts, src/app/dashboard/directory-dashboard/directory-items/assessment-item/waste-water-summary-card/waste-water-summary-card.component.ts, src/app/dashboard/directory-dashboard/directory-summary/directory-summary.component.html, src/app/dashboard/directory-dashboard/directory-summary/directory-summary.component.ts, src/app/shared/models/waste-water.ts, src/app/waste-water/results-panel/results-table/results-table.component.html, src/app/waste-water/waste-water-report/result-data/result-data.component.html, src/app/waste-water/waste-water.component.ts, src/app/waste-water/waste-water.service.ts
connects #4047 
adds summary card for waste water
adds waste water to directory summary
connects #4083 
year -> yr
results in kWh -> MWh
=> Issue 4047

src/app/shared/models/printing.ts, src/app/shared/print-options-menu/print-options-menu.component.html, src/app/shared/print-options-menu/print-options-menu.component.ts, src/app/shared/print-options-menu/print-options-menu.service.ts, src/app/waste-water/waste-water-analysis/energy-analysis/energy-analysis-bar-chart/energy-analysis-bar-chart.component.ts, src/app/waste-water/waste-water-analysis/energy-analysis/energy-analysis-table/energy-analysis-table.component.html, src/app/waste-water/waste-water-analysis/energy-analysis/energy-analysis.component.css, src/app/waste-water/waste-water-analysis/energy-analysis/energy-analysis.component.html, src/app/waste-water/waste-water-analysis/energy-analysis/energy-analysis.component.ts, src/app/waste-water/waste-water-analysis/waste-water-analysis.module.ts, src/app/waste-water/waste-water-analysis/waste-water-analysis.service.ts, src/app/waste-water/waste-water-analysis/waste-water-graphs/srt-graph/srt-graph.component.html, src/app/waste-water/waste-water-analysis/waste-water-graphs/srt-graph/srt-graph.component.ts, src/app/waste-water/waste-water-analysis/waste-water-graphs/waste-water-graphs.component.html, src/app/waste-water/waste-water-report/srt-graphs/srt-graphs.component.css, src/app/waste-water/waste-water-report/srt-graphs/srt-graphs.component.html, src/app/waste-water/waste-water-report/srt-graphs/srt-graphs.component.spec.ts, src/app/waste-water/waste-water-report/srt-graphs/srt-graphs.component.ts, src/app/waste-water/waste-water-report/waste-water-report.component.html, src/app/waste-water/waste-water-report/waste-water-report.component.ts, src/app/waste-water/waste-water-report/waste-water-report.module.ts, src/app/waste-water/waste-water.module.ts
connects #4087 
add report graphs and printing to waste water report
=> Issue 4087

src/app/fsat/fsat.component.ts, src/app/phast/phast.component.ts, src/app/psat/psat.component.ts, src/app/settings/settings.service.ts, src/app/ssmt/ssmt.component.ts, src/app/treasure-hunt/treasure-hunt.component.ts
=> fix settings initialization bug from issue 4040

src/app/waste-water/results-panel/results-table/results-table.component.html
=> add SRT days to results panel

src/app/shared/models/steam/sankey.model.ts, src/app/shared/ssmt-sankey/ssmt-sankey.component.ts
connects #2353 
- Add flash condensate and steam vent loss to other losses
- Adjust display value
=> Issue 2353

src/app/phast/phast-results.service.ts, src/app/phast/phast.service.ts
connects #3990 
(this branch should be 3990)
=> fix gross heat input calculation in EAF

src/app/phast/losses/energy-input/energy-input-form/energy-input-form.component.html, src/app/phast/losses/energy-input/energy-input.component.ts, src/app/phast/losses/energy-input/energy-input.service.ts, src/app/phast/losses/exhaust-gas/exhaust-gas.component.html, src/app/phast/losses/losses-help/energy-input-help/energy-input-help.component.html, src/app/phast/losses/losses-help/exhaust-gas-help/exhaust-gas-help.component.html, src/app/phast/losses/losses-tabs/energy-input-tab/energy-input-tab.component.ts, src/app/phast/losses/losses-tabs/losses-tabs.component.html, src/app/phast/phast-report/phast-report.component.ts, src/app/phast/phast-report/results-data/results-data.component.ts, src/app/phast/phast-results.service.ts, src/app/phast/phast-valid.service.ts, src/app/phast/phast.service.ts, src/app/phast/sankey/sankey.component.ts
connects #4103 
updates EAF validation to show errors for negative exhaust gas losses
=> Issue 4103

src/app/phast/phast.service.ts
=> add exothermic heat for min electricity input

package.json, src/app/waste-water/waste-water-report/waste-water-report.component.html, src/app/waste-water/waste-water-report/waste-water-report.component.ts
=> add message for setup not done

src/app/calculator/system-and-equipment-curve/chart-hover-data/chart-hover-data.component.html, src/app/calculator/system-and-equipment-curve/chart-hover-data/chart-hover-data.component.ts, src/app/calculator/system-and-equipment-curve/system-and-equipment-curve-graph/system-and-equipment-curve-graph.component.html, src/app/calculator/system-and-equipment-curve/system-and-equipment-curve-graph/system-and-equipment-curve-graph.component.ts
connects #4122 
Add decimal place for fans imperial view
=> Issue 4122

src/app/calculator/compressed-air/air-leak/air-leak-help/air-leak-help.component.html, src/app/calculator/compressed-air/compressed-air-pressure-reduction/compressed-air-pressure-reduction-help/compressed-air-pressure-reduction-help.component.css, src/app/calculator/compressed-air/compressed-air-pressure-reduction/compressed-air-pressure-reduction-help/compressed-air-pressure-reduction-help.component.html, src/app/calculator/compressed-air/compressed-air-reduction/compressed-air-reduction-help/compressed-air-reduction-help.component.html
=> updates to compressed air help text

src/app/calculator/compressed-air/air-leak/air-leak-form/air-leak-form.service.ts, src/app/calculator/compressed-air/air-leak/air-leak.component.css, src/app/calculator/compressed-air/air-leak/air-leak.component.html, src/app/calculator/compressed-air/air-leak/air-leak.component.ts, src/app/calculator/compressed-air/air-leak/air-leak.service.ts, src/app/calculator/compressed-air/air-leak/convert-air-leak.service.ts, src/app/calculator/compressed-air/air-leak/facility-compressor-data-form/facility-compressor-data-form.component.html, src/app/calculator/compressed-air/air-leak/facility-compressor-data-form/facility-compressor-data-form.component.ts, src/app/calculator/compressed-air/compressed-air-reduction/compressed-air-reduction-form/compressed-air-reduction-form.component.html, src/app/calculator/compressed-air/compressed-air-reduction/compressed-air-reduction-form/compressed-air-reduction-form.component.ts, src/app/calculator/compressed-air/compressed-air-reduction/compressed-air-reduction.service.ts, src/app/calculator/compressed-air/compressed-air-reduction/convert-compressed-air-reduction.service.ts
connects #4091 
compressed air specific power in imperial is no "kw / (100 SCFM)"
fixes layout issues in air leak survey calculator
=> Issue 4091

src/app/calculator/compressed-air/air-leak/air-leak-form/air-leak-form.service.ts, src/app/calculator/compressed-air/air-leak/air-leak.component.css, src/app/calculator/compressed-air/air-leak/air-leak.component.html, src/app/calculator/compressed-air/air-leak/air-leak.component.ts, src/app/calculator/compressed-air/air-leak/air-leak.service.ts, src/app/calculator/compressed-air/air-leak/convert-air-leak.service.ts, src/app/calculator/compressed-air/air-leak/facility-compressor-data-form/facility-compressor-data-form.component.html, src/app/calculator/compressed-air/air-leak/facility-compressor-data-form/facility-compressor-data-form.component.ts, src/app/calculator/compressed-air/compressed-air-reduction/compressed-air-reduction-form/compressed-air-reduction-form.component.html, src/app/calculator/compressed-air/compressed-air-reduction/compressed-air-reduction-form/compressed-air-reduction-form.component.ts, src/app/calculator/compressed-air/compressed-air-reduction/compressed-air-reduction.service.ts, src/app/calculator/compressed-air/compressed-air-reduction/convert-compressed-air-reduction.service.ts
connects #4093 
fixes dropdown logic issues. Other fixes coming from issue 4091 (PR open for that already)
=> Issue 4093

src/app/calculator/furnaces/flue-gas/flue-gas-form-mass/flue-gas-form-mass.component.html, src/app/calculator/furnaces/flue-gas/flue-gas-form-mass/flue-gas-form-mass.component.ts, src/app/calculator/furnaces/flue-gas/flue-gas-form-volume/flue-gas-form-volume.component.html, src/app/calculator/furnaces/flue-gas/flue-gas-form-volume/flue-gas-form-volume.component.ts, src/app/calculator/furnaces/flue-gas/flue-gas-modal/flue-gas-modal.component.css, src/app/calculator/furnaces/flue-gas/flue-gas-modal/flue-gas-modal.component.html, src/app/calculator/furnaces/flue-gas/flue-gas-modal/flue-gas-modal.component.spec.ts, src/app/calculator/furnaces/flue-gas/flue-gas-modal/flue-gas-modal.component.ts, src/app/calculator/furnaces/flue-gas/flue-gas.component.ts, src/app/calculator/furnaces/flue-gas/flue-gas.module.ts, src/app/calculator/furnaces/flue-gas/flue-gas.service.ts
=> Issue 3844

src/app/phast/phast-valid.service.ts, src/app/phast/phast.component.css, src/app/phast/phast.component.ts, src/app/shared/phast-sankey/phast-sankey.component.ts
connects #1832 
- Change Heat input message
- Fix phast energyInputExhaustGasLoss validation
=> Issue 1832

src/app/calculator/furnaces/wall/wall-form.service.ts, src/app/calculator/furnaces/wall/wall-form/wall-form.component.css, src/app/calculator/furnaces/wall/wall-form/wall-form.component.html, src/app/calculator/furnaces/wall/wall-form/wall-form.component.ts, src/app/calculator/furnaces/wall/wall-results/wall-results.component.css, src/app/calculator/furnaces/wall/wall-results/wall-results.component.html, src/app/calculator/furnaces/wall/wall-results/wall-results.component.spec.ts, src/app/calculator/furnaces/wall/wall-results/wall-results.component.ts, src/app/calculator/furnaces/wall/wall.component.html, src/app/calculator/furnaces/wall/wall.component.ts, src/app/calculator/furnaces/wall/wall.module.ts, src/app/calculator/furnaces/wall/wall.service.ts, src/app/phast/losses/wall-losses/wall-losses.component.ts, src/app/shared/models/phast/losses/wallLoss.ts
connects #3838 and #4120 
- Adds results panel
- Adds operating hours, fuel cost, energy source fields
- Fix validation
=> Issue 3838 and 4120

src/app/phast/losses/energy-input/energy-input.component.ts, src/app/phast/losses/losses-tabs/energy-input-tab/energy-input-tab.component.ts, src/app/phast/phast-results.service.ts, src/app/phast/phast-valid.service.ts, src/app/phast/phast.service.ts
=> fix issue 4103

src/app/calculator/fans/fan-analysis/internal-dimension-modal/internal-dimension-modal.component.ts
=> fix clear area calculation

src/app/treasure-hunt/treasure-chest/summary-card/summary-card.component.ts, src/app/treasure-hunt/treasure-chest/summary-card/utility-summary/utility-summary.component.html
=> have treasure chest use facility usage values for calculations

src/app/waste-water/results-panel/results-table/results-table.component.html
=> update decimals displayed in results table

src/app/dashboard/directory-dashboard/directory-items/assessment-item/waste-water-summary-card/waste-water-summary-card.component.html, src/app/dashboard/directory-dashboard/directory-items/assessment-item/waste-water-summary-card/waste-water-summary-card.component.ts, src/app/shared/models/waste-water.ts, src/app/waste-water/activated-sludge-form/activated-sludge-form.component.ts, src/app/waste-water/add-modification-modal/add-modification-modal.component.ts, src/app/waste-water/aerator-performance-form/aerator-performance-form.component.ts, src/app/waste-water/modification-list-modal/modification-list-modal.component.ts, src/app/waste-water/results-panel/results-table/results-table.component.html, src/app/waste-water/results-panel/results-table/results-table.component.ts, src/app/waste-water/system-basics/system-basics.component.ts, src/app/waste-water/waste-water-banner/waste-water-banner.component.ts, src/app/waste-water/waste-water-report/input-data/input-data.component.html, src/app/waste-water/waste-water-report/result-data/result-data.component.html, src/app/waste-water/waste-water-report/waste-water-report.component.html, src/app/waste-water/waste-water-report/waste-water-report.component.ts, src/app/waste-water/waste-water.component.ts, src/app/waste-water/waste-water.service.ts
connects #4048 
connects #4087 
validation checks for waste water
adds error messages to waste water reports
fixes prod build errors
=> Issue 4048

src/app/calculator/furnaces/wall/wall-form/wall-form.component.html, src/app/calculator/furnaces/wall/wall-help/wall-help.component.html
=> Add missing wall energy help text

src/app/fsat/fsat.component.css, src/app/fsat/fsat.component.html, src/app/fsat/fsat.component.ts, src/app/psat/psat.component.css, src/app/psat/psat.component.html, src/app/psat/psat.component.ts, src/app/shared/fsat-sankey/fsat-sankey.component.ts, src/app/shared/psat-sankey/psat-sankey.component.ts, src/app/shared/ssmt-sankey/ssmt-sankey.component.ts, src/app/ssmt/ssmt.component.css, src/app/ssmt/ssmt.component.html, src/app/ssmt/ssmt.component.ts
connects #4099 
Add sankey label options to all assessment sankeys
=> Issue 4099

src/app/shared/models/waste-water.ts, src/app/waste-water/explore-opportunities/explore-opportunities-form/explore-aerator-form/explore-aerator-form.component.css, src/app/waste-water/explore-opportunities/explore-opportunities-form/explore-aerator-form/explore-aerator-form.component.html, src/app/waste-water/explore-opportunities/explore-opportunities-form/explore-aerator-form/explore-aerator-form.component.spec.ts, src/app/waste-water/explore-opportunities/explore-opportunities-form/explore-aerator-form/explore-aerator-form.component.ts, src/app/waste-water/explore-opportunities/explore-opportunities-form/explore-opportunities-form.component.css, src/app/waste-water/explore-opportunities/explore-opportunities-form/explore-opportunities-form.component.html, src/app/waste-water/explore-opportunities/explore-opportunities-form/explore-opportunities-form.component.spec.ts, src/app/waste-water/explore-opportunities/explore-opportunities-form/explore-opportunities-form.component.ts, src/app/waste-water/explore-opportunities/explore-opportunities.component.css, src/app/waste-water/explore-opportunities/explore-opportunities.component.html, src/app/waste-water/explore-opportunities/explore-opportunities.component.ts, src/app/waste-water/waste-water.component.html, src/app/waste-water/waste-water.component.ts, src/app/waste-water/waste-water.module.ts
connects #4044 
adds initial explore opps to waste water.
=> Issue 4044

src/app/calculator/furnaces/flue-gas/energy-form/energy-form.component.css, src/app/calculator/furnaces/flue-gas/energy-form/energy-form.component.html, src/app/calculator/furnaces/flue-gas/energy-form/energy-form.component.spec.ts, src/app/calculator/furnaces/flue-gas/energy-form/energy-form.component.ts, src/app/calculator/furnaces/flue-gas/energy-form/energy-form.service.spec.ts, src/app/calculator/furnaces/flue-gas/energy-form/energy-form.service.ts, src/app/calculator/furnaces/flue-gas/flue-gas-form-mass/flue-gas-form-mass.component.html, src/app/calculator/furnaces/flue-gas/flue-gas-form-mass/flue-gas-form-mass.component.ts, src/app/calculator/furnaces/flue-gas/flue-gas-form-volume/flue-gas-form-volume.component.html, src/app/calculator/furnaces/flue-gas/flue-gas-form-volume/flue-gas-form-volume.component.ts, src/app/calculator/furnaces/flue-gas/flue-gas-form.service.ts, src/app/calculator/furnaces/flue-gas/flue-gas.component.html, src/app/calculator/furnaces/flue-gas/flue-gas.component.ts, src/app/calculator/furnaces/flue-gas/flue-gas.module.ts, src/app/calculator/furnaces/flue-gas/flue-gas.service.ts, src/app/shared/models/phast/losses/flueGas.ts
connects #3837 
Break out energy fields into own form
=> Issue 3837

src/app/calculator/fans/fan-analysis/help-and-results-panel/planar-results/planar-results.component.html
connects # 4169  with parent #3754 
- Change order of plane data table to follow diagram
=> Issue 4169

src/app/calculator/fans/fan-analysis/fan-analysis-banner/fan-analysis-banner.component.html, src/app/calculator/fans/fan-analysis/fan-analysis-form/fan-shaft-power-form/fan-shaft-power-form.component.html, src/app/calculator/fans/fan-analysis/fan-analysis-form/fan-shaft-power-form/fan-shaft-power-form.component.ts, src/app/calculator/fans/fan-analysis/help-and-results-panel/operating-points-help/fan-data-help/fan-data-help.component.html, src/app/calculator/fans/fan-analysis/help-and-results-panel/operating-points-help/fan-shaft-power-help/fan-shaft-power-help.component.html
connects #4168  parent #3754 
- Update help text and naming
- Remove decimal places
=> Issue 4168

src/app/calculator/fans/fan-analysis/fan-analysis-form/plane-data-form/fan-data-form/fan-data-form.component.html, src/app/calculator/fans/fan-analysis/fan-analysis-form/plane-data-form/fan-data-form/fan-data-form.component.ts, src/app/calculator/fans/fan-analysis/fan-analysis-form/plane-data-form/plane-data-form.component.html, src/app/calculator/fans/fan-analysis/fan-analysis-form/plane-data-form/pressure-readings-form/pressure-readings-form.component.html, src/app/calculator/fans/fan-analysis/fan-analysis-form/plane-data-form/pressure-readings-form/pressure-readings-form.component.ts, src/app/calculator/fans/fan-analysis/fan-analysis-form/plane-data-form/traverse-planes/traverse-planes.component.html, src/app/calculator/fans/fan-analysis/fan-analysis-form/plane-data-form/traverse-planes/traverse-planes.component.spec.ts, src/app/calculator/fans/fan-analysis/fan-analysis-form/plane-data-form/traverse-planes/traverse-planes.component.ts, src/app/calculator/fans/fan-analysis/fan-analysis.component.ts, src/app/calculator/fans/fan-analysis/fan-analysis.module.ts, src/app/calculator/fans/fan-analysis/fan-analysis.service.ts, src/app/fsat/fsat.service.ts, src/app/shared/models/fans.ts
connects #4171 parent #3754 
- Adds traverse velocity result 
- Keeping comments used to plan out calc static pressure feature coming next
=> Issue 4171

src/app/calculator/furnaces/charge-material/energy-form/energy-form.component.ts, src/app/calculator/furnaces/charge-material/gas-material-form/gas-material-form.component.html, src/app/calculator/furnaces/charge-material/gas-material-form/gas-material-form.component.ts, src/app/calculator/furnaces/charge-material/liquid-material-form/liquid-material-form.component.html, src/app/calculator/furnaces/charge-material/liquid-material-form/liquid-material-form.component.ts, src/app/calculator/furnaces/charge-material/solid-material-form/solid-material-form.component.html, src/app/calculator/furnaces/charge-material/solid-material-form/solid-material-form.component.ts, src/app/calculator/furnaces/flue-gas/energy-form/energy-form.component.ts, src/app/calculator/furnaces/wall/wall-form/wall-form.component.html, src/app/calculator/furnaces/wall/wall-form/wall-form.component.ts, src/app/calculator/furnaces/wall/wall.component.html, src/app/phast/losses/charge-material/liquid-charge-material-form/liquid-charge-material-form.component.html
- Adds missing IdString properties and removes inconsistent template attr strings
- Defaults index to 0 for calculators that are being worked on to include multiple losses
=> Fix dev build

src/app/calculator/furnaces/flue-gas/flue-gas-help/flue-gas-help.component.html, src/app/calculator/furnaces/wall/wall-form.service.ts, src/app/calculator/furnaces/wall/wall-form/wall-form.component.css, src/app/calculator/furnaces/wall/wall-form/wall-form.component.html, src/app/calculator/furnaces/wall/wall-form/wall-form.component.ts, src/app/calculator/furnaces/wall/wall-help/wall-help.component.css, src/app/calculator/furnaces/wall/wall-help/wall-help.component.html, src/app/calculator/furnaces/wall/wall-results/wall-results.component.html, src/app/calculator/furnaces/wall/wall.component.css, src/app/calculator/furnaces/wall/wall.component.html, src/app/calculator/furnaces/wall/wall.component.ts, src/app/calculator/furnaces/wall/wall.service.ts, src/app/shared/models/phast/losses/wallLoss.ts
connects #3838 
- Adding multiple loss functionality to wall
- Retrofit help text on flue gas calculator
=> Issue 3838

src/app/calculator/fans/fan-analysis/convert-fan-analysis.service.ts, src/app/calculator/fans/fan-analysis/fan-analysis-form/fan-info-form/fan-info-form.component.html, src/app/calculator/fans/fan-analysis/fan-analysis-form/fan-info-form/fan-info-form.component.ts, src/app/calculator/fans/fan-analysis/fan-analysis-form/fan-shaft-power-form/fan-shaft-power-form.component.css, src/app/calculator/fans/fan-analysis/fan-analysis-form/fan-shaft-power-form/fan-shaft-power-form.component.html, src/app/calculator/fans/fan-analysis/fan-analysis-form/fan-shaft-power-form/fan-shaft-power-form.component.ts, src/app/calculator/fans/fan-analysis/fan-analysis-form/fan-shaft-power-form/fan-shaft-power-form.service.ts, src/app/calculator/fans/fan-analysis/fan-analysis-form/gas-density-form/gas-density-form.component.html, src/app/calculator/fans/fan-analysis/fan-analysis-form/gas-density-form/gas-density-form.component.ts, src/app/calculator/fans/fan-analysis/fan-analysis-form/plane-data-form/fan-data-form/fan-data-form.component.html, src/app/calculator/fans/fan-analysis/fan-analysis-form/plane-data-form/fan-data-form/fan-data-form.component.ts, src/app/calculator/fans/fan-analysis/fan-analysis-form/plane-data-form/plane-data-form.service.ts, src/app/calculator/fans/fan-analysis/fan-analysis-form/plane-data-form/plane-info-form/plane-info-form.component.html, src/app/calculator/fans/fan-analysis/fan-analysis-form/plane-data-form/plane-info-form/plane-info-form.component.ts, src/app/calculator/fans/fan-analysis/fan-analysis-form/plane-data-form/pressure-readings-form/pressure-readings-form.component.html, src/app/calculator/fans/fan-analysis/fan-analysis-form/plane-data-form/pressure-readings-form/pressure-readings-form.component.ts, src/app/calculator/fans/fan-analysis/fan-analysis-form/plane-data-form/traverse-planes/traverse-planes.component.css, src/app/calculator/fans/fan-analysis/fan-analysis-form/plane-data-form/traverse-planes/traverse-planes.component.html, src/app/calculator/fans/fan-analysis/fan-analysis-form/plane-data-form/traverse-planes/traverse-planes.component.ts, src/app/calculator/fans/fan-analysis/fan-analysis-results/fan-analysis-results.component.ts, src/app/calculator/fans/fan-analysis/fan-analysis.component.ts, src/app/calculator/fans/fan-analysis/fan-analysis.service.ts, src/app/shared/models/fans.ts
connects #3754 
Remaining issues from 3754
- Add "Calculate Static Pressure" functionality
- Motor Input Power (input change to kW (fix any unit conversions, etc.)
- Add "Fan Shaft Power" Result on page (bold left side result fine)
- Use settingsLabel
Please check the removed 53-66 pressure-readings-form.ts - tested in FSAT and standalone I couldn't find a case where this would be true.
=> Issue 3754

src/app/calculator/fans/fan-analysis/fan-analysis-form/plane-data-form/plane-data-form.service.ts, src/app/calculator/fans/fan-analysis/help-and-results-panel/help-and-results-panel.component.ts
connects #4124 
also fixes help tab selecting when navigating to planar data
=> fix saving variation in barometric pressure

src/app/calculator/motors/motor-performance/motor-performance-chart.service.ts, src/app/calculator/motors/motor-performance/motor-performance-chart/motor-performance-chart.component.ts
connects #4155 
Change power to power factor
=> Issue 4155

src/app/calculator/compressed-air/air-flow-conversion/air-flow-conversion.service.ts
connects #4174 
- Remove redundant elevationOp conversion
=> Issue 4174

src/app/phast/phast-results.service.ts
=> fix EAF validation

src/app/calculator/fans/fan-analysis/fan-analysis-form/fan-shaft-power-form/fan-shaft-power-form.component.html, src/app/calculator/fans/fan-analysis/fan-analysis-results/fan-analysis-results.component.html
connects #4168 
Remove decimal places on calculated voltage, Change Fan shaft power label
=> issue 4168 (post-verification)

src/app/phast/phast-results.service.ts
=> fix calculation for electricit input min

src/app/phast/losses/energy-input/energy-input-form/energy-input-form.component.html, src/app/phast/losses/energy-input/energy-input.service.ts, src/app/phast/phast-results.service.ts
=> fix EAF energy input validation

src/app/calculator/furnaces/atmosphere/atmosphere-form/atmosphere-form.component.html, src/app/calculator/furnaces/atmosphere/atmosphere-help/atmosphere-help.component.html, src/app/calculator/furnaces/charge-material/charge-material-help/charge-material-help.component.html, src/app/calculator/furnaces/charge-material/charge-material.service.ts, src/app/calculator/furnaces/charge-material/gas-material-form/gas-material-form.component.html, src/app/calculator/furnaces/charge-material/liquid-material-form/liquid-material-form.component.html, src/app/calculator/furnaces/charge-material/liquid-material-form/liquid-material-form.service.ts, src/app/calculator/furnaces/charge-material/solid-material-form/solid-material-form.component.html, src/app/calculator/furnaces/charge-material/solid-material-form/solid-material-form.service.ts, src/app/calculator/furnaces/opening/opening-form/opening-form.component.html, src/app/calculator/furnaces/opening/opening-help/opening-help.component.html, src/app/calculator/furnaces/opening/opening.service.ts, src/app/phast/losses/atmosphere-losses/atmosphere-losses-form/atmosphere-losses-form.component.html, src/app/phast/losses/charge-material/gas-charge-material-form/gas-charge-material-form.component.html, src/app/phast/losses/charge-material/liquid-charge-material-form/liquid-charge-material-form.component.html, src/app/phast/losses/charge-material/solid-charge-material-form/solid-charge-material-form.component.html, src/app/phast/losses/cooling-losses/cooling-losses.service.ts, src/app/phast/losses/cooling-losses/gas-cooling-losses-form/gas-cooling-losses-form.component.html, src/app/phast/losses/cooling-losses/liquid-cooling-losses-form/liquid-cooling-losses-form.component.html, src/app/phast/losses/fixture-losses/fixture-losses-form/fixture-losses-form.component.html, src/app/phast/losses/fixture-losses/fixture-losses.service.ts, src/app/phast/losses/gas-leakage-losses/gas-leakage-losses-form/gas-leakage-losses-form.component.html, src/app/phast/losses/gas-leakage-losses/gas-leakage-losses.service.ts, src/app/phast/losses/losses-help/atmosphere-losses-help/atmosphere-losses-help.component.html, src/app/phast/losses/losses-help/charge-material-help/charge-material-help.component.html, src/app/phast/losses/losses-help/cooling-losses-help/cooling-losses-help.component.html, src/app/phast/losses/losses-help/fixture-losses-help/fixture-losses-help.component.html, src/app/phast/losses/losses-help/gas-leakage-losses-help/gas-leakage-losses-help.component.html, src/app/phast/losses/losses-help/opening-losses-help/opening-losses-help.component.html, src/app/phast/losses/opening-losses/opening-losses-form/opening-losses-form.component.html
connects #4133 
Change various PH field labels
=> Issue 4133

src/app/calculator/furnaces/opening/opening-form/opening-form.component.html, src/app/calculator/furnaces/opening/opening-form/opening-form.component.ts, src/app/calculator/furnaces/opening/opening.service.ts, src/app/phast/losses/opening-losses/opening-losses-form/opening-losses-form.component.html, src/app/phast/losses/opening-losses/opening-losses-form/opening-losses-form.component.ts
connects #4198 
Add view factor calculation as link/button for user.
=> Issue 4198

src/app/treasure-hunt/treasure-chest/summary-card/summary-card.component.html, src/app/treasure-hunt/treasure-chest/summary-card/summary-card.component.ts, src/app/treasure-hunt/treasure-chest/summary-card/utility-summary/utility-summary.component.html, src/app/treasure-hunt/treasure-hunt-report/opportunity-summary/opportunity-summary-copy-table/opportunity-summary-copy-table.component.ts, src/app/treasure-hunt/treasure-hunt-report/opportunity-summary/opportunity-summary.component.html, src/app/treasure-hunt/treasure-hunt-report/opportunity-summary/opportunity-summary.component.ts
connects #4191 
connects #4156 
connects #4098 
adds category to treasure chest for "Additional Annual Cost Savings"
subtracts additional savings from other costs in opportunity summary as "Rebate"
=> Issue 4191

src/app/calculator/compressed-air/compressed-air-reduction/compressed-air-reduction.component.ts, src/app/calculator/compressed-air/compressed-air-reduction/compressed-air-reduction.service.ts
connects #4158 
fixes bugs if no baseline data
fixes utility type for additional comp air reduction equipment
=> fix adding new comp air reduction baselines

src/app/shared/models/plotting.ts, src/app/treasure-hunt/treasure-hunt-report/opportunity-payback/opportunity-payback-bar-chart/opportunity-payback-bar-chart.component.ts, src/app/treasure-hunt/treasure-hunt-report/opportunity-payback/opportunity-payback-donut/opportunity-payback-donut.component.ts, src/app/treasure-hunt/treasure-hunt-report/report-graphs/effort-savings-chart/effort-savings-chart.component.css, src/app/treasure-hunt/treasure-hunt-report/report-graphs/effort-savings-chart/effort-savings-chart.component.html, src/app/treasure-hunt/treasure-hunt-report/report-graphs/effort-savings-chart/effort-savings-chart.component.ts, src/app/treasure-hunt/treasure-hunt-report/report-graphs/report-graphs.component.css, src/app/treasure-hunt/treasure-hunt-report/report-graphs/report-graphs.component.html, src/app/treasure-hunt/treasure-hunt-report/report-graphs/utility-donut-chart/utility-donut-chart.component.ts
=> cleanup some printing logic for teasure hunt printing

src/app/calculator/furnaces/atmosphere/atmosphere-form/atmosphere-form.component.ts, src/app/calculator/furnaces/atmosphere/atmosphere-help/atmosphere-help.component.html, src/app/calculator/furnaces/atmosphere/atmosphere.component.html, src/app/calculator/furnaces/atmosphere/atmosphere.service.ts, src/app/calculator/furnaces/charge-material/charge-material-help/charge-material-help.component.html, src/app/calculator/furnaces/charge-material/charge-material.component.html, src/app/calculator/furnaces/charge-material/charge-material.component.ts, src/app/calculator/furnaces/charge-material/charge-material.service.ts, src/app/calculator/furnaces/charge-material/gas-material-form/gas-material-form.component.ts, src/app/calculator/furnaces/charge-material/gas-material-form/gas-material-form.service.ts, src/app/calculator/furnaces/charge-material/liquid-material-form/liquid-material-form.component.ts, src/app/calculator/furnaces/charge-material/liquid-material-form/liquid-material-form.service.ts, src/app/calculator/furnaces/charge-material/solid-material-form/solid-material-form.component.ts, src/app/calculator/furnaces/flue-gas/flue-gas-form-volume/flue-gas-form-volume.component.ts, src/app/calculator/furnaces/flue-gas/flue-gas-help/flue-gas-help.component.html, src/app/calculator/furnaces/flue-gas/flue-gas.component.html, src/app/calculator/furnaces/opening/opening-form/opening-form.component.html, src/app/calculator/furnaces/opening/opening-form/opening-form.component.ts, src/app/calculator/furnaces/opening/opening-help/opening-help.component.html, src/app/calculator/furnaces/opening/opening.component.html, src/app/calculator/furnaces/opening/opening.component.ts, src/app/calculator/furnaces/opening/opening.service.ts, src/app/calculator/furnaces/wall/wall-form/wall-form.component.ts, src/app/calculator/furnaces/wall/wall-help/wall-help.component.html, src/app/calculator/furnaces/wall/wall.component.html, src/app/calculator/furnaces/wall/wall.component.ts, src/app/calculator/furnaces/wall/wall.service.ts
connects #4202 
- Various bug fixes to behavior of subjects/subscribes with multiple losses
- Add loss button now works when no losses exist
- changes to validity checks to better handle disabled forms
- UI consistency fixes
=> Issue 4202

src/app/motor-inventory/motor-inventory-summary/inventory-summary-motor-details/inventory-summary-motor-details.component.css, src/app/motor-inventory/motor-inventory-summary/inventory-summary-motor-details/inventory-summary-motor-details.component.html, src/app/motor-inventory/motor-inventory-summary/inventory-summary-motor-details/inventory-summary-motor-details.component.ts, src/app/motor-inventory/motor-inventory-summary/inventory-summary-motor-details/motor-item-detail/motor-item-detail.component.css, src/app/motor-inventory/motor-inventory-summary/inventory-summary-motor-details/motor-item-detail/motor-item-detail.component.html, src/app/motor-inventory/motor-inventory.component.css
=> add printing to motor details page

src/app/calculator/waste-water/waste-water-list/waste-water-list.component.html
=> fix waste water list title

src/app/calculator/furnaces/atmosphere/atmosphere-help/atmosphere-help.component.html, src/app/calculator/furnaces/charge-material/charge-material-help/charge-material-help.component.html, src/app/phast/losses/losses-help/atmosphere-losses-help/atmosphere-losses-help.component.html, src/app/phast/losses/losses-help/charge-material-help/charge-material-help.component.html, src/app/phast/losses/losses-help/cooling-losses-help/cooling-losses-help.component.html, src/app/phast/losses/losses-help/fixture-losses-help/fixture-losses-help.component.html
=> updates to ph help text

src/app/calculator/compressed-air/air-leak/air-leak-help/air-leak-help.component.html
=> fix air leak survey help text

src/app/calculator/compressed-air/air-leak/air-leak.service.ts
connects https://github.com/ORNL-AMO/AMO-Tools-Suite/issues/544
=> fixes for suite issue 544

src/app/calculator/compressed-air/compressed-air-constants.ts
=> fix issue 4231 air leak example

src/app/calculator/furnaces/atmosphere/atmosphere-form.service.ts, src/app/calculator/furnaces/opening/opening-form.service.ts, src/app/phast/add-modification/add-modification.component.ts, src/app/phast/explore-phast-opportunities/explore-phast-opportunities-form/explore-flue-gas-form/explore-flue-gas-form.component.html, src/app/phast/explore-phast-opportunities/explore-phast-opportunities-form/explore-flue-gas-form/explore-flue-gas-form.component.ts, src/app/phast/explore-phast-opportunities/explore-phast-opportunities-form/explore-opening-form/explore-opening-form.component.ts, src/app/phast/losses/opening-losses/opening-losses-form/opening-losses-form.component.ts, src/app/phast/losses/wall-losses/wall-losses-form/wall-losses-form.component.html, src/app/phast/modification-list/modification-list.component.ts, src/app/phast/phast.component.ts
connects #4203 #4229 
- Add missing warnings to ExOpps for opening and atmosphere. 
- Add default object for mod hasOpportunity properties. add backwards compatibility for old assessments
- Set opening height validator only when not round
=> Issue 4203

src/app/treasure-hunt/treasure-chest/opportunity-cards/opportunity-cards.component.html, src/app/treasure-hunt/treasure-chest/opportunity-cards/opportunity-cards.component.ts
=> fix opportunity card buggy bug

src/app/treasure-hunt/treasure-chest/summary-card/summary-card.component.ts
=> fix for issue 4156

src/app/shared/facility-info-summary/facility-info-summary.component.html, src/app/treasure-hunt/treasure-chest/summary-card/summary-card.component.ts
=> Issue 4151

src/app/phast/losses/gas-leakage-losses/gas-leakage-losses-form/gas-leakage-losses-form.component.html, src/app/phast/losses/gas-leakage-losses/gas-leakage-losses.service.ts, src/app/phast/losses/losses-help/gas-leakage-losses-help/gas-leakage-losses-help.component.html, src/app/phast/phast-report/phast-input-summary/gas-leakage-summary/gas-leakage-summary.component.html
connects #4245 
Change specific density to specific gravity in leakage
=> Issue 4245

src/app/calculator/furnaces/energy-equivalency/energy-equivalency-form/energy-equivalency-form.component.html, src/app/calculator/furnaces/energy-use/energy-use-form/energy-use-form.component.html, src/app/calculator/furnaces/energy-use/energy-use-form/energy-use-form.component.ts, src/app/calculator/furnaces/energy-use/energy-use-help/energy-use-help.component.html, src/app/calculator/furnaces/energy-use/energy-use.component.html
connects #4251 
Making some validation, help, styling improvements in old ph standalones
=> Issue 4251

src/assets/styles/two-panel.css
=> css for calc panels fitting content

src/app/report-rollup/treasure-hunt-rollup/treasure-hunt-rollup.component.html, src/app/report-rollup/treasure-hunt-rollup/treasure-hunt-rollup.component.ts, src/app/treasure-hunt/treasure-chest/summary-card/summary-card.component.html, src/app/treasure-hunt/treasure-hunt-report/opportunity-summary.service.ts, src/app/treasure-hunt/treasure-hunt-report/opportunity-summary/opportunity-summary.component.html
connects #4250 
adds other savings to rollup
fixes payback period calculation
=> Issue 4250

src/app/calculator/furnaces/atmosphere/atmosphere.component.ts, src/app/calculator/furnaces/atmosphere/atmosphere.service.ts
Fixing a bug where hours per year resets on each loss
=> Fix hours per year in atmosphere calc

package.json, src/app/calculator/compressed-air/air-leak/air-leak.service.ts, src/app/calculator/compressed-air/compressed-air-reduction/compressed-air-reduction-form/compressed-air-reduction-form.component.html, src/app/calculator/compressed-air/compressed-air-reduction/compressed-air-reduction-form/compressed-air-reduction-form.component.ts, src/app/calculator/compressed-air/compressed-air-reduction/compressed-air-reduction.component.html, src/app/calculator/compressed-air/compressed-air-reduction/compressed-air-reduction.service.ts
connects #4258 
removes adding more then one compressor for compressed air reduction
properly apply compressor control adjustment math to air leak survey and compressed air reduction
=> Issue 4258

src/app/calculator/furnaces/atmosphere/atmosphere.component.ts, src/app/calculator/furnaces/atmosphere/atmosphere.service.ts, src/app/calculator/furnaces/charge-material/charge-material.component.ts, src/app/calculator/furnaces/opening/opening.component.ts, src/app/calculator/furnaces/opening/opening.service.ts, src/app/calculator/furnaces/wall/wall.component.ts, src/app/calculator/furnaces/wall/wall.service.ts
The rest of the fixes for this bug...
=> Opp Hours bug fix for PH standalones

src/app/calculator/furnaces/flue-gas/flue-gas-form-mass/flue-gas-form-mass.component.ts, src/app/calculator/furnaces/flue-gas/flue-gas-form-volume/flue-gas-form-volume.component.ts, src/app/calculator/steam/stack-loss/stack-loss-form/stack-loss-by-mass/stack-loss-by-mass.component.ts, src/app/calculator/steam/stack-loss/stack-loss-form/stack-loss-by-volume/stack-loss-by-volume.component.ts, src/app/phast/explore-phast-opportunities/explore-phast-opportunities-form/explore-flue-gas-form/explore-flue-gas-form.component.ts, src/app/phast/losses/flue-gas-losses/flue-gas-losses-form-mass/flue-gas-losses-form-mass.component.ts, src/app/phast/losses/flue-gas-losses/flue-gas-losses-form-volume/flue-gas-losses-form-volume.component.ts
connects #4249 
- Update references for MaterialInputProperties
=> Issue 4249

src/app/shared/models/waste-water.ts, src/app/waste-water/activated-sludge-form/activated-sludge-form.component.html, src/app/waste-water/convert-waste-water.service.ts, src/app/waste-water/results-panel/results-table/results-table.component.html, src/app/waste-water/waste-water-analysis/dataTableVariables.ts, src/app/waste-water/waste-water-report/input-data/input-data.component.html, src/app/waste-water/waste-water-report/result-data/result-data.component.html, src/app/waste-water/waste-water-report/srt-graphs/srt-graphs.component.ts, src/app/waste-water/waste-water.service.ts
connects #4255 
Fix labels and decimal precision in SRT
=> Issue 4255

src/app/shared/models/treasure-hunt.ts, src/app/treasure-hunt/treasure-hunt-report/report-graphs/report-graphs.component.html, src/app/treasure-hunt/treasure-hunt-report/report-graphs/report-graphs.component.ts, src/app/treasure-hunt/treasure-hunt-report/report-graphs/utility-donut-chart/utility-donut-chart.component.ts, src/app/treasure-hunt/treasure-hunt-report/treasure-hunt-report.module.ts
connects #4095 
- Add current costs to utility pie
- Show percent in pie labels
=> Issue 4095

src/app/shared/models/waste-water.ts, src/app/waste-water/explore-opportunities/explore-opportunities-form/explore-aerator-form/explore-aerator-form.component.html, src/app/waste-water/explore-opportunities/explore-opportunities-form/explore-aerator-form/explore-aerator-form.component.ts, src/app/waste-water/results-panel/results-table/results-table.component.html
connects #4185 
Add reduce supplied oxygen opportunity.
=> Issue 4185

src/app/dashboard/assessment.service.ts, src/app/waste-water/activated-sludge-form/activated-sludge-form.component.html, src/app/waste-water/aerator-performance-form/aerator-performance-form.component.html, src/app/waste-water/results-panel/help-panel/activated-sludge-help/activated-sludge-help.component.html, src/app/waste-water/results-panel/help-panel/aerator-performance-help/aerator-performance-help.component.html, src/app/waste-water/results-panel/help-panel/system-basics-help/system-basics-help.component.html, src/app/waste-water/system-basics/system-basics.component.html, src/app/waste-water/waste-water-analysis/dataTableVariables.ts, src/app/waste-water/waste-water-report/input-data/input-data.component.html, src/app/waste-water/waste-water-report/srt-graphs/srt-graphs.component.ts
connects #4184
Form label/help fixes, sub in Total O2 graph, sys-basics defaults
=> Issue 4184

src/app/dashboard/directory-dashboard/directory-items/assessment-item/waste-water-summary-card/waste-water-summary-card.component.html, src/app/dashboard/directory-dashboard/directory-summary/directory-summary.component.ts, src/app/report-rollup/report-rollup-models.ts, src/app/report-rollup/report-rollup.module.ts, src/app/report-rollup/report-summary/waste-water-summary/waste-water-summary.component.ts, src/app/report-rollup/waste-water-report-rollup.service.ts, src/app/report-rollup/waste-water-rollup/effluent-energy-use-table/effluent-energy-use-table.component.css, src/app/report-rollup/waste-water-rollup/effluent-energy-use-table/effluent-energy-use-table.component.html, src/app/report-rollup/waste-water-rollup/effluent-energy-use-table/effluent-energy-use-table.component.spec.ts, src/app/report-rollup/waste-water-rollup/effluent-energy-use-table/effluent-energy-use-table.component.ts, src/app/report-rollup/waste-water-rollup/nutrient-removal-table/nutrient-removal-table.component.css, src/app/report-rollup/waste-water-rollup/nutrient-removal-table/nutrient-removal-table.component.html, src/app/report-rollup/waste-water-rollup/nutrient-removal-table/nutrient-removal-table.component.spec.ts, src/app/report-rollup/waste-water-rollup/nutrient-removal-table/nutrient-removal-table.component.ts, src/app/report-rollup/waste-water-rollup/waste-water-rollup.component.html, src/app/report-rollup/waste-water-rollup/waste-water-rollup.component.ts, src/app/shared/models/waste-water.ts, src/app/waste-water/results-panel/results-table/results-table.component.html, src/app/waste-water/waste-water-analysis/dataTableVariables.ts, src/app/waste-water/waste-water-analysis/energy-analysis/energy-analysis-bar-chart/energy-analysis-bar-chart.component.ts, src/app/waste-water/waste-water-analysis/energy-analysis/energy-analysis-table/energy-analysis-table.component.html, src/app/waste-water/waste-water-report/result-data/result-data.component.html, src/app/waste-water/waste-water.service.ts
connects #4159 
- Adding two tables to WW rollup
- Also changing AeEnergy property to AeEnergyAnnual (need to use the raw backend result as energy monthly)
=> Issue 4159

src/app/ssmt/header/header-form/header-form.component.css, src/app/ssmt/header/header-form/header-form.component.html
connects #3886 
Add Condensate Return subheader
=> Issue 3886

src/app/phast/phast.component.ts, src/app/phast/phast.module.ts, src/app/phast/system-basics/system-basics.component.css, src/app/phast/system-basics/system-basics.component.html, src/app/phast/system-basics/system-basics.component.ts, src/app/settings/settings.service.ts, src/app/shared/models/phast/phast.ts, src/app/shared/update-units-modal/update-units-modal.component.css, src/app/shared/update-units-modal/update-units-modal.component.html, src/app/shared/update-units-modal/update-units-modal.component.spec.ts, src/app/shared/update-units-modal/update-units-modal.component.ts, src/app/shared/update-units-modal/update-units-modal.module.ts
connects #4254 
- Add update units modal and confirm when user changes units and assessment contains loss data
- Remove old phast comments
=> Issue 4254

src/app/shared/models/waste-water.ts, src/app/waste-water/aerator-performance-form/aerator-performance-form.component.html, src/app/waste-water/aerator-performance-form/aerator-performance-form.component.ts, src/app/waste-water/aerator-performance-form/aerator-performance-form.service.ts, src/app/waste-water/explore-opportunities/explore-opportunities-form/explore-aerator-form/explore-aerator-form.component.html, src/app/waste-water/explore-opportunities/explore-opportunities-form/explore-aerator-form/explore-aerator-form.component.ts, src/app/waste-water/waste-water-banner/modify-conditions-tabs/modify-conditions-tabs.component.ts, src/app/waste-water/waste-water.service.ts
add new binding for calculating waste water treatment given SRT days
directly calculate optimal DO, Operating Time, and Speed 
set warning for operating hours
connects #4262
=> Issue 4262

src/app/waste-water/waste-water-analysis/waste-water-analysis.component.ts, src/app/waste-water/waste-water-analysis/waste-water-analysis.service.ts, src/app/waste-water/waste-water-analysis/waste-water-graphs/srt-graph/srt-graph.component.ts, src/app/waste-water/waste-water-banner/analysis-menu/analysis-menu.component.html, src/app/waste-water/waste-water-banner/analysis-menu/analysis-menu.component.ts, src/app/waste-water/waste-water-report/srt-graphs/srt-graphs.component.ts
connects #4186 
Allows user to select x axis in analysis graphs
=> Issue 4186

src/app/calculator/furnaces/charge-material/energy-form/energy-form.component.ts, src/app/calculator/furnaces/cooling/energy-form/energy-form.component.ts, src/app/calculator/furnaces/opening/opening-form.service.ts, src/app/calculator/furnaces/opening/opening-form/opening-form.component.ts, src/app/calculator/furnaces/wall/wall-form/wall-form.component.ts, src/app/phast/losses/opening-losses/opening-losses-form/opening-losses-form.component.ts
connects #4298 
calculate AH/ flue gas when modal closes
=> Issue 4298

src/app/dashboard/acknowledgments-page/acknowledgments-page.component.html
=> Add names to acknowledgements

src/app/dashboard/assessment.service.ts, src/app/dashboard/directory-dashboard/directory-items/assessment-item/waste-water-summary-card/waste-water-summary-card.component.ts, src/app/dashboard/directory-dashboard/directory-summary/directory-summary.component.ts, src/app/report-rollup/waste-water-report-rollup.service.ts, src/app/shared/models/waste-water.ts, src/app/waste-water/activated-sludge-form/activated-sludge-form.component.html, src/app/waste-water/activated-sludge-form/activated-sludge-form.component.ts, src/app/waste-water/activated-sludge-form/activated-sludge-form.service.ts, src/app/waste-water/explore-opportunities/explore-opportunities-form/explore-activated-sludge-form/explore-activated-sludge-form.component.css, src/app/waste-water/explore-opportunities/explore-opportunities-form/explore-activated-sludge-form/explore-activated-sludge-form.component.html, src/app/waste-water/explore-opportunities/explore-opportunities-form/explore-activated-sludge-form/explore-activated-sludge-form.component.spec.ts, src/app/waste-water/explore-opportunities/explore-opportunities-form/explore-activated-sludge-form/explore-activated-sludge-form.component.ts, src/app/waste-water/explore-opportunities/explore-opportunities-form/explore-opportunities-form.component.html, src/app/waste-water/modify-conditions/compare.service.ts, src/app/waste-water/results-panel/results-table/results-table.component.ts, src/app/waste-water/waste-water-analysis/waste-water-analysis.service.ts, src/app/waste-water/waste-water-report/waste-water-report.component.ts, src/app/waste-water/waste-water.module.ts, src/app/waste-water/waste-water.service.ts
connects #4284 
adds selection to calculate by SRT day or target MLSSpar
Adds to explore opps and modify conditions
=> Issue 4284

src/app/calculator/compressed-air/air-leak/air-leak.service.ts, src/app/calculator/compressed-air/compressed-air-reduction/compressed-air-reduction-form/compressed-air-reduction-form.component.css, src/app/calculator/compressed-air/compressed-air-reduction/compressed-air-reduction-form/compressed-air-reduction-form.component.html, src/app/calculator/compressed-air/compressed-air-reduction/compressed-air-reduction-form/compressed-air-reduction-form.component.ts, src/app/calculator/compressed-air/compressed-air-reduction/compressed-air-reduction-results/compressed-air-reduction-results.component.html, src/app/calculator/compressed-air/compressed-air-reduction/compressed-air-reduction-results/compressed-air-reduction-results.component.ts, src/app/calculator/compressed-air/compressed-air-reduction/compressed-air-reduction.component.html, src/app/calculator/compressed-air/compressed-air-reduction/compressed-air-reduction.component.ts, src/app/calculator/compressed-air/compressed-air-reduction/compressed-air-reduction.service.ts, src/app/shared/models/standalone.ts, src/app/treasure-hunt/treasure-hunt-report/opportunity-summary.service.ts
connects #4259
- Set final modification energy results after we have savings calculated
- In modification, lock compressor values and msg user
- Calculate energy savings including percentage control adjustment for each equipment
=> Issue 4259

src/app/core/core.service.ts, src/app/dashboard/assessment-create/assessment-create.component.ts, src/app/dashboard/assessment.service.ts, src/app/examples/mockWasteWater.ts, src/app/indexedDb/assessment-db.service.ts, src/app/settings/assessment-settings/reset-data-modal/reset-data-modal.component.ts
connects #4114  #4078 
- Setup example
- Remove defaults from new assessment
=> Issue 4114 4078

src/app/calculator/utilities/fan-psychrometric/fan-psychrometric-form/fan-psychrometric-form.component.ts, src/app/calculator/utilities/fan-psychrometric/fan-psychrometric-help/fan-psychrometric-help.component.html
connects #4315 
Changed the text and verbiage for the Psychrometric calculator.
=> Changed the text and verbiage for the Psychrometric calculator.

src/app/waste-water/aerator-performance-form/aerator-performance-form.component.ts, src/app/waste-water/waste-water-analysis/dataTableVariables.ts, src/app/waste-water/waste-water-analysis/waste-water-analysis.service.ts, src/app/waste-water/waste-water-banner/analysis-menu/analysis-menu.component.html, src/app/waste-water/waste-water-report/result-data/result-data.component.html
=> Waste Water needs verification fixes

src/app/waste-water/waste-water.component.ts
connects #4322 
- Reset the setup tab when user navigates out of assessment
=> Issue 4322

src/app/dashboard/assessment.service.ts, src/app/waste-water/results-panel/results-table/results-table.component.html, src/app/waste-water/results-panel/results-table/results-table.component.ts
connects #4317 
- Show SRT and MLSS results by control point
- Add basics defaults for new WW
=> Issue 4317

src/app/waste-water/waste-water-report/input-data/input-data.component.html
connects #4306 
Changed the waste water input summary form field labels to match with the waste water assessment activated sludge and aerator performance.
=> Issue 4306

src/app/dashboard/acknowledgments-page/acknowledgments-page.component.html
=> move Alex to ORNL staff in acknowledgments

src/app/dashboard/assessment-create/assessment-create.component.ts, src/app/dashboard/assessment.service.ts, src/app/waste-water/results-panel/results-table/results-table.component.html
connects #4078 #4317 
- Adding defaults, set electricityCost to settings
=> Issue 4078, 4317

src/app/fsat/fsat-report/input-summary/fan-setup-summary/fan-setup-summary.component.html, src/app/fsat/fsat-report/input-summary/field-data-summary/field-data-summary.component.html, src/app/psat/psat-report/input-summary/input-summary.component.html
connects #4331 
made changes to the fan report input summary Fan section for fan type and in the Field Data section for load estimated method and motor power.
=> Issue-4331

src/app/calculator/compressed-air/compressed-air-reduction/compressed-air-reduction-form/compressed-air-reduction-form.component.html, src/app/calculator/compressed-air/compressed-air-reduction/compressed-air-reduction-help/compressed-air-reduction-help.component.html
connects #4295 
- Fixs units and add help text
=> Issue 4295

src/app/calculator/compressed-air/compressed-air-pressure-reduction/compressed-air-pressure-reduction-form/compressed-air-pressure-reduction-form.component.html, src/app/calculator/compressed-air/compressed-air-pressure-reduction/compressed-air-pressure-reduction-form/compressed-air-pressure-reduction-form.component.ts, src/app/calculator/compressed-air/compressed-air-pressure-reduction/compressed-air-pressure-reduction-help/compressed-air-pressure-reduction-help.component.html, src/app/calculator/compressed-air/compressed-air-pressure-reduction/compressed-air-pressure-reduction.component.html, src/app/calculator/compressed-air/compressed-air-pressure-reduction/compressed-air-pressure-reduction.component.ts, src/app/calculator/compressed-air/compressed-air-pressure-reduction/compressed-air-pressure-reduction.service.ts, src/app/examples/mockTreasureHunt.ts, src/app/shared/models/standalone.ts
connects #4312 
connects https://github.com/ORNL-AMO/AMO-Tools-Suite/issues/546
adds new fields for modification energy calculations
=> Issue 4312

src/app/fsat/compare.service.ts, src/app/fsat/fan-field-data/fan-field-data.component.html, src/app/fsat/fan-field-data/fan-field-data.component.ts, src/app/fsat/fan-field-data/fan-field-data.service.ts, src/app/fsat/fsat-fluid/fsat-fluid.component.html, src/app/fsat/fsat-fluid/fsat-fluid.service.ts, src/app/fsat/fsat-report/input-summary/base-gas-density-summary/base-gas-density-summary.component.html, src/app/fsat/fsat-report/input-summary/base-gas-density-summary/base-gas-density-summary.component.ts, src/app/fsat/fsat-tabs/fsat-tabs.component.html, src/app/fsat/fsat-warning.service.ts, src/app/fsat/fsat.component.html, src/app/fsat/fsat.module.ts, src/app/fsat/fsat.service.ts
connects #4332 
Added new validation for the fan assessment, field data section and removed other fields.
=> Issue 4332

src/app/fsat/fsat-tabs/fsat-tabs.component.html, src/app/fsat/fsat.component.html, src/app/fsat/fsat.service.ts
connects #4346 
Remove fan analysis from FSAT calculators
=> Issue 4346

src/app/calculator/fans/fan-analysis/fan-analysis-form/gas-density-form/gas-density-form.service.ts, src/app/calculator/fans/fan-analysis/fan-analysis-form/plane-data-form/fan-data-form/fan-data-form.component.ts, src/app/calculator/fans/fan-analysis/fan-analysis-form/plane-data-form/pressure-readings-form/pressure-readings-form.component.ts, src/app/calculator/fans/fan-analysis/fan-analysis-form/plane-data-form/traverse-planes/traverse-planes.component.ts, src/app/calculator/fans/fan-analysis/fan-analysis.service.ts, src/app/calculator/utilities/fan-psychrometric/fan-psychrometric-form/fan-psychrometric-form.component.html, src/app/dashboard/assessment.service.ts, src/app/fsat/calculate-pressures/calculate-flow-pressure/calculate-flow-pressure.component.ts, src/app/fsat/calculate-pressures/calculate-inlet-pressure/calculate-inlet-pressure.component.ts, src/app/fsat/calculate-pressures/calculate-outlet-pressure/calculate-outlet-pressure.component.ts, src/app/fsat/fan-field-data/fan-field-data.component.ts, src/app/fsat/fsat-fluid/fsat-fluid.component.html, src/app/fsat/fsat-fluid/fsat-fluid.service.ts
connects #4347 
- Change defaults in FSAT and PSAT
- Add defaults object for FSAT calculate pressure and flow modal
=> Issue 4347

src/app/shared/convert-units/convert-units.service.ts, src/app/shared/models/waste-water.ts, src/app/shared/shared-pipes/shared-pipes.module.ts, src/app/shared/shared-pipes/waste-water-options-display.pipe.spec.ts, src/app/shared/shared-pipes/waste-water-options-display.pipe.ts, src/app/waste-water/explore-opportunities/explore-opportunities-form/explore-aerator-form/explore-aerator-form.component.html, src/app/waste-water/explore-opportunities/explore-opportunities-form/explore-aerator-form/explore-aerator-form.component.ts, src/app/waste-water/modify-conditions/compare.service.ts, src/app/waste-water/waste-water-report/input-data/input-data.component.html, src/app/waste-water/waste-water-report/waste-water-report.module.ts, src/app/waste-water/waste-water.module.ts
connects #4324 
connects #4306 
adds "Aerator Upgrade" to options in explore opps.
adds Aerator and Type of Aerator to input summary in report.
=> Issue 4324

src/app/waste-water/activated-sludge-form/activated-sludge-form.service.ts, src/app/waste-water/aerator-performance-form/aerator-performance-form.component.html, src/app/waste-water/aerator-performance-form/aerator-performance-form.component.ts, src/app/waste-water/aerator-performance-form/aerator-performance-form.service.ts, src/app/waste-water/explore-opportunities/explore-opportunities-form/explore-aerator-form/explore-aerator-form.component.html, src/app/waste-water/explore-opportunities/explore-opportunities-form/explore-aerator-form/explore-aerator-form.component.ts, src/app/waste-water/waste-water.service.ts
connects #4261 
add info message when value cannot be optimized further
tightens up optimization calculations
=> issue-4261

src/app/dashboard/landing-screen/landing-screen.component.html, src/app/dashboard/sidebar/calculator-list/calculator-list.component.html
connects #4334 
- Remove dupes
- Reorder landing list to match
=> Remove duplicate calcs in list, reorder landing

src/app/calculator/furnaces/air-heating/air-heating-form.service.ts, src/app/calculator/furnaces/air-heating/air-heating-form/air-heating-form.component.html, src/app/calculator/furnaces/air-heating/air-heating-results/air-heating-results.component.css, src/app/calculator/furnaces/air-heating/air-heating-results/air-heating-results.component.html, src/app/calculator/furnaces/air-heating/air-heating-results/air-heating-results.component.ts, src/app/calculator/furnaces/air-heating/air-heating.component.html, src/app/calculator/furnaces/air-heating/air-heating.service.ts, src/app/calculator/furnaces/heat-cascading/heat-cascading-results/heat-cascading-results.component.css, src/app/calculator/furnaces/heat-cascading/heat-cascading-results/heat-cascading-results.component.html, src/app/calculator/furnaces/heat-cascading/heat-cascading-results/heat-cascading-results.component.ts, src/app/calculator/furnaces/heat-cascading/heat-cascading.component.html, src/app/calculator/furnaces/heat-cascading/heat-cascading.service.ts, src/app/shared/models/phast/airHeating.ts
connects #4376 
- Adding cost savings
- Move results to side panel
=> Issue 4376

src/app/waste-water/results-panel/help-panel/activated-sludge-help/activated-sludge-help.component.html, src/app/waste-water/results-panel/help-panel/activated-sludge-help/activated-sludge-help.component.ts, src/app/waste-water/results-panel/help-panel/aerator-performance-help/aerator-performance-help.component.html, src/app/waste-water/results-panel/help-panel/aerator-performance-help/aerator-performance-help.component.ts, src/app/waste-water/results-panel/help-panel/help-panel.component.html
connects #4319 
updated help text and savings suggestions
=> Issue 4319

src/app/fsat/add-modification/add-modification.component.ts, src/app/fsat/fsat.component.ts, src/app/fsat/modify-conditions/modify-conditions.component.ts, src/app/psat/add-modification/add-modification.component.ts, src/app/psat/modify-conditions/modify-conditions.component.ts, src/app/shared/models/waste-water.ts, src/app/ssmt/add-modification/add-modification.component.ts, src/app/ssmt/explore-opportunities/explore-opportunities.component.html, src/app/ssmt/explore-opportunities/explore-opportunities.component.ts, src/app/ssmt/modify-conditions/modify-conditions.component.ts, src/app/waste-water/activated-sludge-form/activated-sludge-form.component.ts, src/app/waste-water/add-modification-modal/add-modification-modal.component.ts, src/app/waste-water/aerator-performance-form/aerator-performance-form.component.ts, src/app/waste-water/explore-opportunities/explore-opportunities-form/explore-opportunities-form.component.ts, src/app/waste-water/explore-opportunities/explore-opportunities.component.html, src/app/waste-water/explore-opportunities/explore-opportunities.component.ts, src/app/waste-water/waste-water-banner/setup-tabs/setup-tabs.component.ts, src/app/waste-water/waste-water.component.html, src/app/waste-water/waste-water.component.ts, src/app/waste-water/waste-water.module.ts
connects #4378 
fix explore opps toast in assessments and add to waste water
=> issue 4378

src/app/phast/explore-phast-opportunities/explore-phast-opportunities-form/explore-atmosphere-form/explore-atmosphere-form.component.ts
=> fix atmosphere explore opps init

src/app/dashboard/directory-dashboard/directory-items/directory-item/directory-item.component.html, src/app/fsat/fsat.service.ts
=> add icons to folder card summary

src/app/fsat/explore-opportunities/explore-opportunities-form/fan-data-form/fan-data-form.component.html, src/app/fsat/explore-opportunities/explore-opportunities-form/fan-data-form/fan-data-form.component.ts
connects #4336 
Find ex ops baseline fan type by value
=> Issue 4336

src/app/waste-water/aerator-performance-form/aerator-performance-form.component.html, src/app/waste-water/aerator-performance-form/aerator-performance-form.component.ts, src/app/waste-water/explore-opportunities/explore-opportunities-form/explore-aerator-form/explore-aerator-form.component.html, src/app/waste-water/explore-opportunities/explore-opportunities-form/explore-aerator-form/explore-aerator-form.component.ts, src/app/waste-water/waste-water.service.ts
connects #4261 
fixes to optimization links.
Disables links when optimization cannot be run
=> fixes to optimization links

src/app/calculator/system-and-equipment-curve/curve-data.service.ts, src/app/calculator/system-and-equipment-curve/system-and-equipment-curve.component.ts, src/app/calculator/system-and-equipment-curve/system-and-equipment-curve.service.ts, src/app/calculator/system-and-equipment-curve/system-curve/fan-system-curve-form/fan-system-curve-form.component.html, src/app/calculator/system-and-equipment-curve/system-curve/fan-system-curve-form/fan-system-curve-form.component.ts, src/app/calculator/system-and-equipment-curve/system-curve/pump-system-curve-form/pump-system-curve-form.component.html, src/app/calculator/system-and-equipment-curve/system-curve/pump-system-curve-form/pump-system-curve-form.component.ts, src/app/examples/mockFsat.ts, src/app/shared/models/system-and-equipment-curve.ts
connects #4359 
Remove fan/pump curve fields
=> Issue 4359

src/app/calculator/furnaces/air-heating/air-heating-results/air-heating-results.component.html, src/app/calculator/furnaces/heat-cascading/heat-cascading-results/heat-cascading-results.component.html, src/app/calculator/furnaces/heat-cascading/heat-cascading.service.ts
connects #4402 
Remove currency pipe, use default HHV
=> Issue 4402

src/app/dashboard/assessment.service.ts, src/app/examples/mockFsat.ts, src/app/fsat/compare.service.ts, src/app/fsat/fan-field-data/fan-field-data.component.html, src/app/fsat/fan-field-data/fan-field-data.component.ts, src/app/fsat/fan-field-data/fan-field-data.service.ts, src/app/fsat/fsat-fluid/fsat-fluid.component.html, src/app/fsat/fsat-fluid/fsat-fluid.component.ts, src/app/fsat/fsat-fluid/fsat-fluid.service.ts, src/app/fsat/fsat-report/input-summary/base-gas-density-summary/base-gas-density-summary.component.html, src/app/fsat/fsat-report/input-summary/base-gas-density-summary/base-gas-density-summary.component.ts, src/app/fsat/fsat-report/input-summary/field-data-summary/field-data-summary.component.html, src/app/fsat/help-panel/fan-field-data-help/fan-field-data-help.component.html, src/app/fsat/help-panel/fsat-fluid-help/fsat-fluid-help.component.html, src/app/shared/helper-services/update-data.service.ts, src/app/shared/models/fans.ts
connects #4361 
Move specific heat ratio to fan fluid form
=> Issue 4361

src/app/calculator/fans/fan-analysis/fan-analysis-form/fan-info-form/fan-info-form.component.html, src/app/calculator/fans/fan-analysis/fan-analysis-form/fan-info-form/fan-info-form.component.ts, src/app/calculator/fans/fan-analysis/fan-analysis-form/plane-data-form/plane-info-form/plane-info-form.component.html, src/app/calculator/fans/fan-analysis/fan-analysis-form/plane-data-form/plane-info-form/plane-info-form.component.ts, src/app/calculator/fans/fan-analysis/fan-analysis.service.ts
connects #4345 
Set barometricP based on planar variation condition
=> Issue 4345

src/app/calculator/furnaces/waste-heat/waste-heat-form/waste-heat-form.component.html, src/app/calculator/furnaces/waste-heat/waste-heat-help/waste-heat-help.component.html
=> Issue 4057

src/app/dashboard/landing-screen/landing-screen.component.html
connects #4365 
Add subtitle to WW landing
=> Issue 4365

src/app/calculator/calculator-routing/steam.routing.ts, src/app/calculator/steam/steam-list/steam-list.component.html, src/app/calculator/steam/steam.module.ts, src/app/calculator/steam/water-heating/water-heating-form.service.spec.ts, src/app/calculator/steam/water-heating/water-heating-form.service.ts, src/app/calculator/steam/water-heating/water-heating-form/water-heating-form.component.css, src/app/calculator/steam/water-heating/water-heating-form/water-heating-form.component.html, src/app/calculator/steam/water-heating/water-heating-form/water-heating-form.component.spec.ts, src/app/calculator/steam/water-heating/water-heating-form/water-heating-form.component.ts, src/app/calculator/steam/water-heating/water-heating-help/water-heating-help.component.css, src/app/calculator/steam/water-heating/water-heating-help/water-heating-help.component.html, src/app/calculator/steam/water-heating/water-heating-help/water-heating-help.component.spec.ts, src/app/calculator/steam/water-heating/water-heating-help/water-heating-help.component.ts, src/app/calculator/steam/water-heating/water-heating-results/water-heating-results.component.css, src/app/calculator/steam/water-heating/water-heating-results/water-heating-results.component.html, src/app/calculator/steam/water-heating/water-heating-results/water-heating-results.component.spec.ts, src/app/calculator/steam/water-heating/water-heating-results/water-heating-results.component.ts, src/app/calculator/steam/water-heating/water-heating.component.css, src/app/calculator/steam/water-heating/water-heating.component.html, src/app/calculator/steam/water-heating/water-heating.component.spec.ts, src/app/calculator/steam/water-heating/water-heating.component.ts, src/app/calculator/steam/water-heating/water-heating.module.ts, src/app/calculator/steam/water-heating/water-heating.service.spec.ts, src/app/calculator/steam/water-heating/water-heating.service.ts, src/app/core/core.routing.ts, src/app/dashboard/sidebar/calculator-list/calculator-list.component.html, src/app/shared/models/steam/waterHeating.ts
connects #4058 
Adds water heating with steam calculator
=> Issue 4058

src/app/dashboard/acknowledgments-page/acknowledgments-page.component.html
connects #4411 
Add Larry Moore to acknowledgements
=> Issue 4411

package.json
update tools suite version to v0.9.1
=> update tools suite version

src/app/calculator/steam/saturated-properties/saturated-properties-form/saturated-properties-form.component.html, src/app/calculator/steam/saturated-properties/saturated-properties-table/saturated-properties-table.component.html, src/app/calculator/steam/steam-properties/steam-properties-form/steam-properties-form.component.html, src/app/calculator/steam/steam-properties/steam-properties-table/steam-properties-table.component.html
=> steam props and sat props results fixes

src/app/calculator/furnaces/furnaces-list/furnaces-list.component.html
=> Issue 4434

package.json, src/app/dashboard/sidebar/version-modal/version-modal.component.html
=> update release notes and version 0.9.1

src/app/calculator/utilities/co2-savings/co2-savings-form/electricityGridRegions.ts
=> update egrid region values

src/app/fsat/calculate-pressures/calculate-flow-pressure/calculate-flow-pressure.component.ts, src/app/fsat/calculate-pressures/calculate-inlet-pressure/calculate-inlet-pressure.component.html, src/app/fsat/calculate-pressures/calculate-inlet-pressure/calculate-inlet-pressure.component.ts, src/app/fsat/calculate-pressures/calculate-outlet-pressure/calculate-outlet-pressure.component.html, src/app/fsat/calculate-pressures/calculate-outlet-pressure/calculate-outlet-pressure.component.ts, src/app/fsat/fan-field-data/fan-field-data.component.css, src/app/fsat/fan-field-data/fan-field-data.component.html, src/app/fsat/fan-field-data/fan-field-data.component.ts, src/app/fsat/fsat-warning.service.ts, src/app/fsat/fsat.service.ts, src/app/shared/models/fans.ts
#connects 4437
- Add inlet velocity pressure to fan field data modals
=> Issue 4437

src/app/calculator/furnaces/o2-enrichment/enrichment-graph/enrichment-graph.component.ts, src/app/calculator/furnaces/o2-enrichment/o2-enrichment-form/o2-enrichment-form.component.html
connects #4309
Update fuel savings in data-summary, change button text
=> Issue 4309

src/app/phast/aux-equipment/aux-equipment-form/aux-equipment-form.component.html, src/app/phast/losses/slag/slag-form/slag-form.component.html
=> Issue-4243: Change Slag Heat Unit Label & list Duty Cycle last

src/app/calculator/furnaces/flue-gas/flue-gas-form-mass/flue-gas-form-mass.component.ts, src/app/calculator/furnaces/flue-gas/flue-gas-form-volume/flue-gas-form-volume.component.ts, src/app/calculator/furnaces/flue-gas/flue-gas-form.service.ts, src/app/calculator/furnaces/flue-gas/flue-gas.component.html, src/app/calculator/furnaces/flue-gas/flue-gas.component.ts, src/app/calculator/furnaces/flue-gas/flue-gas.service.ts, src/app/examples/mockTreasureHunt.ts, src/app/phast/losses/flue-gas-losses/flue-gas-losses-form-mass/flue-gas-losses-form-mass.component.ts, src/app/phast/losses/flue-gas-losses/flue-gas-losses-form-volume/flue-gas-losses-form-volume.component.ts, src/app/phast/losses/losses-tabs/flue-gas-tab/flue-gas-tab.component.ts, src/app/phast/losses/losses-tabs/losses-tabs.component.html, src/app/shared/models/treasure-hunt.ts, src/app/treasure-hunt/calculators/calculators.component.html, src/app/treasure-hunt/calculators/calculators.component.ts, src/app/treasure-hunt/calculators/calculators.module.ts, src/app/treasure-hunt/calculators/calculators.service.ts, src/app/treasure-hunt/calculators/standalone-opportunity-sheet/opportunity-sheet.service.ts, src/app/treasure-hunt/convert-input-data.service.ts, src/app/treasure-hunt/find-treasure/find-treasure.component.html, src/app/treasure-hunt/treasure-chest/export-opportunities/export-opportunities.component.html, src/app/treasure-hunt/treasure-chest/export-opportunities/export-opportunities.component.ts, src/app/treasure-hunt/treasure-chest/import-opportunities.service.ts, src/app/treasure-hunt/treasure-chest/opportunity-cards/opportunity-cards.service.ts, src/app/treasure-hunt/treasure-chest/opportunity-cards/sort-cards.service.ts, src/app/treasure-hunt/treasure-chest/treasure-chest-menu/calculator-type-dropdown/calculator-type-dropdown.component.ts, src/app/treasure-hunt/treasure-hunt-calculator-services/flue-gas-treasure-hunt.service.spec.ts, src/app/treasure-hunt/treasure-hunt-calculator-services/flue-gas-treasure-hunt.service.ts, src/app/treasure-hunt/treasure-hunt-calculator-services/treasure-hunt-opportunity.service.ts, src/app/treasure-hunt/treasure-hunt-report/opportunity-summary.service.ts, src/app/treasure-hunt/treasure-hunt.module.ts
connects #4444 
- Add flue gas to TH
- changing TreasureHuntOpportunity.opportunityType to required, updated field in mockTH (will be overridden anyway in update-data)
- Updated warning for flue gas temp
=> Issue 4444

src/app/report-rollup/phast-rollup/phast-rollup-furnace-summary-table/phast-rollup-furnace-summary-table.component.css, src/app/report-rollup/phast-rollup/phast-rollup-furnace-summary-table/phast-rollup-furnace-summary-table.component.html, src/app/report-rollup/phast-rollup/phast-rollup-furnace-summary-table/phast-rollup-furnace-summary-table.component.ts, src/app/report-rollup/rollup-summary-table/rollup-summary-table.component.css, src/app/report-rollup/rollup-summary-table/rollup-summary-table.component.html, src/app/report-rollup/rollup-summary-table/rollup-summary-table.component.ts
connects #4435 
adds total row to report rollup tables
=> issue 4435

src/app/calculator/utilities/pre-assessment/pre-assessment.service.ts, src/app/dashboard/directory-dashboard/directory-dashboard.component.html
connects #4463 
Check if directory has pre assessments
=> Issue 4463

src/app/calculator/furnaces/furnace-defaults.ts, src/app/calculator/furnaces/wall/wall-form/wall-form.component.html, src/app/calculator/furnaces/wall/wall-form/wall-form.component.ts, src/app/calculator/furnaces/wall/wall.component.html, src/app/calculator/furnaces/wall/wall.component.ts, src/app/calculator/furnaces/wall/wall.service.ts, src/app/shared/models/treasure-hunt.ts, src/app/treasure-hunt/calculators/calculators.component.html, src/app/treasure-hunt/calculators/calculators.module.ts, src/app/treasure-hunt/calculators/calculators.service.ts, src/app/treasure-hunt/convert-input-data.service.ts, src/app/treasure-hunt/find-treasure/find-treasure.component.html, src/app/treasure-hunt/treasure-chest/export-opportunities/export-opportunities.component.html, src/app/treasure-hunt/treasure-chest/export-opportunities/export-opportunities.component.ts, src/app/treasure-hunt/treasure-chest/import-opportunities.service.ts, src/app/treasure-hunt/treasure-chest/opportunity-cards/opportunity-cards.service.ts, src/app/treasure-hunt/treasure-chest/opportunity-cards/sort-cards.service.ts, src/app/treasure-hunt/treasure-hunt-calculator-services/treasure-hunt-opportunity.service.ts, src/app/treasure-hunt/treasure-hunt-calculator-services/wall-treasure-hunt.service.spec.ts, src/app/treasure-hunt/treasure-hunt-calculator-services/wall-treasure-hunt.service.ts, src/app/treasure-hunt/treasure-hunt-report/opportunity-summary.service.ts, src/app/treasure-hunt/treasure-hunt.module.ts
connects #4311 
- Add wall to treasure hunt
=> Issue 4311

src/app/fsat/compare.service.ts, src/app/fsat/fan-field-data/fan-field-data.component.html, src/app/fsat/fan-field-data/fan-field-data.component.ts, src/app/fsat/fsat-warning.service.ts, src/app/fsat/help-panel/fan-field-data-help/fan-field-data-help.component.html, src/app/psat/field-data/field-data.component.html, src/app/psat/field-data/field-data.component.ts, src/app/psat/help-panel/field-data-help/field-data-help.component.html, src/app/psat/psat-warning.service.ts
connects #4464 
- Bring back Measured Voltage in modification and add warning message
=> Issue 4464

src/app/calculator/furnaces/wall/wall-form/wall-form.component.html, src/app/shared/convert-units/convert-units.service.ts, src/app/treasure-hunt/calculators/calculators.service.ts, src/app/treasure-hunt/convert-input-data.service.ts, src/app/treasure-hunt/system-basics/system-basics.component.ts, src/app/treasure-hunt/treasure-chest/opportunity-cards/opportunity-cards.service.ts, src/app/treasure-hunt/treasure-chest/opportunity-cards/sort-cards.service.ts, src/app/treasure-hunt/treasure-hunt-calculator-services/air-leak-treasure-hunt.service.ts, src/app/treasure-hunt/treasure-hunt-calculator-services/ca-pressure-reduction-treasure-hunt.service.ts, src/app/treasure-hunt/treasure-hunt-calculator-services/ca-reduction-treasure-hunt.service.ts, src/app/treasure-hunt/treasure-hunt-calculator-services/electricity-reduction-treasure-hunt.service.ts, src/app/treasure-hunt/treasure-hunt-calculator-services/flue-gas-treasure-hunt.service.ts, src/app/treasure-hunt/treasure-hunt-calculator-services/lighting-replacement-treasure-hunt.service.ts, src/app/treasure-hunt/treasure-hunt-calculator-services/motor-drive-treasure-hunt.service.ts, src/app/treasure-hunt/treasure-hunt-calculator-services/natural-gas-reduction-treasure-hunt.service.ts, src/app/treasure-hunt/treasure-hunt-calculator-services/pipe-insulation-treasure-hunt.service.ts, src/app/treasure-hunt/treasure-hunt-calculator-services/replace-existing-treasure-hunt.service.ts, src/app/treasure-hunt/treasure-hunt-calculator-services/standalone-opportunity-sheet.service.ts, src/app/treasure-hunt/treasure-hunt-calculator-services/steam-reduction-treasure-hunt.service.ts, src/app/treasure-hunt/treasure-hunt-calculator-services/tank-insulation-treasure-hunt.service.ts, src/app/treasure-hunt/treasure-hunt-calculator-services/treasure-hunt-opportunity.service.ts, src/app/treasure-hunt/treasure-hunt-calculator-services/wall-treasure-hunt.service.ts, src/app/treasure-hunt/treasure-hunt-calculator-services/water-reduction-treasure-hunt.service.ts, src/app/treasure-hunt/treasure-hunt.component.ts
connects #4472 
- Move TH conversion and opportunity card logic to services 
- Check for mod before converting Th
=> Issue 4472

src/app/dashboard/directory-dashboard/directory-dashboard-menu/content-controls/content-controls.component.html, src/app/dashboard/directory-dashboard/directory-dashboard-menu/content-controls/content-controls.component.ts, src/app/dashboard/directory-dashboard/directory-dashboard.service.ts, src/app/shared/models/directory-dashboard.ts
connects #4482 
Add Waste water to directory assessments filter
Sorting looks good
=> Issue 4482

src/app/calculator/furnaces/opening/opening-form/opening-form.component.html, src/app/calculator/furnaces/opening/opening-form/opening-form.component.ts, src/app/calculator/furnaces/opening/opening.component.html, src/app/calculator/furnaces/opening/opening.component.ts, src/app/calculator/furnaces/opening/opening.service.ts, src/app/shared/convert-units/convert-units.service.ts, src/app/shared/models/treasure-hunt.ts, src/app/treasure-hunt/calculators/calculators.component.html, src/app/treasure-hunt/calculators/calculators.module.ts, src/app/treasure-hunt/calculators/calculators.service.ts, src/app/treasure-hunt/convert-input-data.service.ts, src/app/treasure-hunt/find-treasure/find-treasure.component.html, src/app/treasure-hunt/treasure-chest/export-opportunities/export-opportunities.component.html, src/app/treasure-hunt/treasure-chest/export-opportunities/export-opportunities.component.ts, src/app/treasure-hunt/treasure-chest/import-opportunities.service.ts, src/app/treasure-hunt/treasure-chest/opportunity-cards/opportunity-cards.service.ts, src/app/treasure-hunt/treasure-chest/opportunity-cards/sort-cards.service.ts, src/app/treasure-hunt/treasure-chest/treasure-chest-menu/calculator-type-dropdown/calculator-type-dropdown.component.ts, src/app/treasure-hunt/treasure-hunt-calculator-services/opening-treasure-hunt.service.spec.ts, src/app/treasure-hunt/treasure-hunt-calculator-services/opening-treasure-hunt.service.ts, src/app/treasure-hunt/treasure-hunt-calculator-services/treasure-hunt-opportunity.service.ts, src/app/treasure-hunt/treasure-hunt-report/opportunity-summary.service.ts, src/app/treasure-hunt/treasure-hunt.module.ts
connects #4445 
Add opening to Treasure hunt
=> Issue 4445

src/app/calculator/furnaces/waste-heat/waste-heat-form.service.ts, src/app/calculator/furnaces/waste-heat/waste-heat-form/waste-heat-form.component.css, src/app/calculator/furnaces/waste-heat/waste-heat-form/waste-heat-form.component.html, src/app/calculator/furnaces/waste-heat/waste-heat-form/waste-heat-form.component.ts, src/app/calculator/furnaces/waste-heat/waste-heat-help/waste-heat-help.component.html, src/app/calculator/furnaces/waste-heat/waste-heat-help/waste-heat-help.component.ts, src/app/calculator/furnaces/waste-heat/waste-heat-results/waste-heat-results.component.html, src/app/calculator/furnaces/waste-heat/waste-heat-results/waste-heat-results.component.ts, src/app/calculator/furnaces/waste-heat/waste-heat.component.css, src/app/calculator/furnaces/waste-heat/waste-heat.component.html, src/app/calculator/furnaces/waste-heat/waste-heat.component.ts, src/app/calculator/furnaces/waste-heat/waste-heat.service.ts, src/app/shared/models/phast/wasteHeat.ts, src/app/shared/models/treasure-hunt.ts, src/app/treasure-hunt/calculators/calculators.component.html, src/app/treasure-hunt/calculators/calculators.module.ts, src/app/treasure-hunt/calculators/calculators.service.ts, src/app/treasure-hunt/convert-input-data.service.ts, src/app/treasure-hunt/find-treasure/find-treasure.component.html, src/app/treasure-hunt/treasure-chest/export-opportunities/export-opportunities.component.html, src/app/treasure-hunt/treasure-chest/export-opportunities/export-opportunities.component.ts, src/app/treasure-hunt/treasure-chest/opportunity-cards/opportunity-cards.service.ts, src/app/treasure-hunt/treasure-chest/opportunity-cards/sort-cards.service.ts, src/app/treasure-hunt/treasure-chest/treasure-chest-menu/calculator-type-dropdown/calculator-type-dropdown.component.ts, src/app/treasure-hunt/treasure-hunt-calculator-services/treasure-hunt-opportunity.service.ts, src/app/treasure-hunt/treasure-hunt-calculator-services/waste-heat-treasure-hunt.service.spec.ts, src/app/treasure-hunt/treasure-hunt-calculator-services/waste-heat-treasure-hunt.service.ts, src/app/treasure-hunt/treasure-hunt-report/opportunity-summary.service.ts, src/app/treasure-hunt/treasure-hunt.module.ts
=> Issue 4480

src/app/calculator/fans/fan-analysis/fan-analysis-form/plane-data-form/pressure-readings-form/pressure-readings-form.component.html, src/app/calculator/fans/fan-analysis/fan-analysis.component.html, src/app/calculator/fans/fan-analysis/help-and-results-panel/help-and-results-panel.component.html, src/app/calculator/fans/fan-analysis/help-and-results-panel/operating-points-help/fan-data-help/fan-data-help.component.html, src/app/calculator/fans/fan-analysis/help-and-results-panel/operating-points-help/fan-data-help/fan-data-help.component.ts, src/app/fsat/calculate-pressures/calculate-flow-pressure/calculate-flow-pressure.component.ts
connects #4510 #4511 #4512 
Add fan plane diagram to help
Fix scroll panel
Add help text
Use default for fan traverse modal Plane 3a drybulbtemp
=> Issue 4510 4511 4512

src/app/tools-suite-api/tools-suite-api.module.ts, src/app/tools-suite-api/waste-water-suite-api.service.spec.ts, src/app/tools-suite-api/waste-water-suite-api.service.ts, src/app/waste-water/waste-water.service.ts
=> Add WASM Module for Waste Water

package.json, src/app/compressed-air-assessment/compressed-air-assessment.component.html, src/app/compressed-air-assessment/compressed-air-assessment.component.ts, src/app/compressed-air-assessment/compressed-air-assessment.module.ts, src/app/compressed-air-assessment/compressed-air-calculation.service.ts, src/app/compressed-air-assessment/inventory/centrifugal-specifics/centrifugal-specifics.component.html, src/app/compressed-air-assessment/inventory/control-data/control-data.component.html, src/app/compressed-air-assessment/inventory/control-data/control-data.component.ts, src/app/compressed-air-assessment/inventory/design-details/design-details.component.html, src/app/compressed-air-assessment/inventory/design-details/design-details.component.ts, src/app/compressed-air-assessment/inventory/generic-compressor-modal/compressor-options-table/compressor-options-table.component.ts, src/app/compressed-air-assessment/inventory/inlet-conditions/inlet-conditions.component.html, src/app/compressed-air-assessment/inventory/inventory.component.html, src/app/compressed-air-assessment/inventory/inventory.service.ts, src/app/compressed-air-assessment/inventory/nameplate-data/nameplate-data.component.html, src/app/compressed-air-assessment/inventory/performance-points/blowoff/blowoff.component.html, src/app/compressed-air-assessment/inventory/performance-points/full-load/full-load.component.html, src/app/compressed-air-assessment/inventory/performance-points/max-full-flow/max-full-flow.component.html, src/app/compressed-air-assessment/inventory/performance-points/no-load/no-load.component.html, src/app/compressed-air-assessment/inventory/performance-points/no-load/no-load.component.ts, src/app/compressed-air-assessment/inventory/performance-points/performance-points.component.html, src/app/compressed-air-assessment/inventory/performance-points/performance-points.component.ts, src/app/compressed-air-assessment/inventory/performance-points/unload-point/unload-point.component.html, src/app/compressed-air-assessment/results-panel/inventory-performance-profile/inventory-performance-profile.component.html, src/app/compressed-air-assessment/results-panel/inventory-performance-profile/inventory-performance-profile.component.spec.ts, src/app/compressed-air-assessment/results-panel/inventory-performance-profile/inventory-performance-profile.component.ts, src/app/compressed-air-assessment/results-panel/inventory-table/inventory-table.component.html, src/app/compressed-air-assessment/results-panel/results-panel.component.html, src/app/compressed-air-assessment/results-panel/results-panel.component.ts, src/app/shared/models/compressed-air-assessment.ts
connects #4503 
updates to performance profiling graphing
updates to mapping to suite inputs
updates to mapping db to inputs
bunch of WIP stuff still but PR for testing purposes
=> Issue 4503

src/app/calculator/furnaces/furnace-defaults.ts, src/app/calculator/furnaces/leakage/leakage-form/leakage-form.component.html, src/app/calculator/furnaces/leakage/leakage-form/leakage-form.component.ts, src/app/calculator/furnaces/opening/opening-form/opening-form.component.html, src/app/calculator/furnaces/opening/opening-form/opening-form.component.ts, src/app/calculator/furnaces/wall/wall-form/wall-form.component.html, src/app/calculator/furnaces/wall/wall-form/wall-form.component.ts, src/app/calculator/furnaces/waste-heat/waste-heat-form/waste-heat-form.component.html, src/app/calculator/furnaces/waste-heat/waste-heat-form/waste-heat-form.component.ts
connects #4462 #4445 #4311 
Change furnace utility option values, fix available heat label
=> Fix UI cosmetics in wall, opening, leakage

src/app/calculator/fans/fan-analysis/help-and-results-panel/operating-points-help/fan-data-help/fan-data-help.component.html, src/app/fsat/calculate-pressures/calculate-flow-pressure/calculate-flow-pressure.component.ts, src/app/psat/psat.component.ts
connects #4464 #4512 
- When custom input type set fan traverse 3a dry bulb blank
- Fix psat overriding measured voltage
- Fix help text
=> Issue 4464, 4512

src/app/calculator/process-cooling/chiller.service.ts, src/app/tools-suite-api/chillers-suite-api.service.spec.ts, src/app/tools-suite-api/chillers-suite-api.service.ts, src/app/tools-suite-api/suite-api-enum.service.ts, src/app/tools-suite-api/tools-suite-api.module.ts
connects #4495 
Tested with in progress chillers (staging, fan, basin). Just need to uncomment once merged.
=> Issue 4495

src/app/calculator/utilities/co2-savings/co2-savings.service.ts
=> Issue-4524 : Update energyType condition in calculate function in co2-savings

src/app/psat/psat-report/output-summary/output-summary.component.html, src/app/report-rollup/fsat-rollup/fsat-rollup.component.html, src/app/report-rollup/fsat-rollup/fsat-rollup.component.ts, src/app/report-rollup/psat-rollup/psat-rollup.component.html, src/app/report-rollup/psat-rollup/psat-rollup.component.ts, src/app/report-rollup/rollup-summary-energy-table/rollup-summary-energy-table.component.ts, src/app/report-rollup/rollup-summary-pie-chart/rollup-summary-pie-chart.component.ts, src/app/report-rollup/rollup-summary-table/rollup-summary-table.component.html, src/app/report-rollup/rollup-summary-table/rollup-summary-table.component.ts
=> Issue-4526: Update Energy Units Fan and Pump rollup

src/app/fsat/fsat-report/results-summary/results-summary.component.html, src/app/fsat/fsat-results/fsat-results-panel/fsat-results-panel.component.html
=> Issue 4541: FEI number format

src/app/calculator/furnaces/leakage/leakage-form/leakage-form.component.html, src/app/calculator/furnaces/leakage/leakage-form/leakage-form.component.ts, src/app/calculator/furnaces/leakage/leakage.component.ts, src/app/calculator/furnaces/leakage/leakage.service.ts, src/app/treasure-hunt/treasure-hunt-calculator-services/leakage-treasure-hunt.service.ts
connects #4462 
Fix TH energySourceType and fuel cost in leakage calculator
=> Issue 4462

src/app/report-rollup/psat-rollup/psat-rollup.component.ts, src/app/report-rollup/rollup-summary-table/rollup-summary-table.component.ts
=> Issue-4526: Pump Payback formatting fixed

src/app/calculator/furnaces/flue-gas/flue-gas-form-volume/flue-gas-form-volume.component.ts, src/app/calculator/furnaces/flue-gas/flue-gas-modal/flue-gas-modal.component.html, src/app/calculator/furnaces/flue-gas/flue-gas-modal/flue-gas-modal.component.ts, src/app/calculator/furnaces/flue-gas/flue-gas.component.ts, src/app/calculator/furnaces/leakage/leakage-form/leakage-form.component.html, src/app/calculator/furnaces/leakage/leakage-form/leakage-form.component.ts, src/app/calculator/furnaces/opening/opening-form/opening-form.component.html, src/app/calculator/furnaces/opening/opening-form/opening-form.component.ts, src/app/calculator/furnaces/wall/wall-form/wall-form.component.html, src/app/calculator/furnaces/wall/wall-form/wall-form.component.ts
connects #4542 
Adding defaults for furnace TH calcs.
=> Issue 4542

src/app/fsat/fsat-report/fsat-report.module.ts, src/app/fsat/fsat-report/input-summary/base-gas-density-summary/base-gas-density-summary.component.html, src/app/fsat/fsat-report/input-summary/fan-motor-summary/fan-motor-summary.component.html, src/app/fsat/fsat-report/input-summary/fan-setup-summary/fan-setup-summary.component.html, src/app/fsat/fsat-report/input-summary/field-data-summary/field-data-summary.component.html, src/app/psat/psat-report/input-summary/input-summary.component.html
connects #4546 #4547 
Add units to fsat input summary, fix psat input summary units
=> Issue 4546, 4547

src/app/calculator/compressed-air/compressed-air-pressure-reduction/compressed-air-pressure-reduction-form/compressed-air-pressure-reduction-form.component.html, src/app/calculator/compressed-air/compressed-air-pressure-reduction/compressed-air-pressure-reduction-form/compressed-air-pressure-reduction-form.component.ts, src/app/calculator/compressed-air/compressed-air-pressure-reduction/compressed-air-pressure-reduction.service.ts, src/app/calculator/standalone.service.ts, src/app/shared/models/standalone.ts, src/index.html
=> Issue 4540

src/app/calculator/furnaces/wall/wall.component.html
Removed this from the ts, and missed the html.
=> Removing operatingHours input

src/app/shared/convert-units/definitions/volumeFlowRate.ts
=> connect #4352

src/app/fsat/fsat-report/input-summary/field-data-summary/field-data-summary.component.html, src/app/fsat/fsat-results/fsat-results-panel/fsat-results-panel.component.html, src/app/psat/explore-opportunities/explore-opportunities-results/explore-opportunities-results.component.html, src/app/psat/psat-report/input-summary/input-summary.component.html
connects #4547 #4546 
Change power/current with units
=> Issue 4547 4546

src/app/psat/compare.service.ts, src/app/psat/field-data/field-data.service.ts, src/app/shared/models/psat.ts
removed unused cost variable
uses implementation costs
=> fix psat implementation costs

src/app/report-rollup/rollup-summary-table/rollup-summary-table.component.html
=> Issue-4526: Format Payback Period number in rollup

src/app/calculator/fans/fan-system-checklist/fan-system-checklist-form/fan-system-checklist-form.component.html, src/app/calculator/fans/fan-system-checklist/fan-system-checklist.component.html, src/app/calculator/fans/fans-list/fans-list.component.html
=> Issue 4528 Fan checklist remove example, fix checkbox clicking

package.json, src/app/dashboard/sidebar/version-modal/version-modal.component.html
connects #4556 
Release notes and version update
=> Issue 4556

src/app/calculator/furnaces/air-heating/air-heating-help/air-heating-help.component.html, src/app/calculator/furnaces/atmosphere/atmosphere-help/atmosphere-help.component.html, src/app/calculator/furnaces/charge-material/charge-material-help/charge-material-help.component.html, src/app/calculator/furnaces/cooling/cooling-help/cooling-help.component.html, src/app/calculator/furnaces/fixture/fixture-help/fixture-help.component.html, src/app/calculator/furnaces/flue-gas/flue-gas-help/flue-gas-help.component.html, src/app/calculator/furnaces/leakage/leakage-help/leakage-help.component.html, src/app/calculator/furnaces/opening/opening-help/opening-help.component.html, src/app/calculator/furnaces/wall/wall-help/wall-help.component.html, src/app/calculator/pumps/head-tool/head-tool-help/head-tool-help.component.html, src/app/calculator/steam/stack-loss/stack-loss-help/stack-loss-help.component.html, src/app/motor-inventory/help-panel/nameplate-data-help/nameplate-data-help.component.html, src/app/phast/losses/losses-help/atmosphere-losses-help/atmosphere-losses-help.component.html, src/app/phast/losses/losses-help/auxiliary-power-losses-help/auxiliary-power-losses-help.component.html, src/app/phast/losses/losses-help/charge-material-help/charge-material-help.component.html, src/app/phast/losses/losses-help/cooling-losses-help/cooling-losses-help.component.html, src/app/phast/losses/losses-help/energy-input-exhaust-gas-losses-help/energy-input-exhaust-gas-losses-help.component.html, src/app/phast/losses/losses-help/energy-input-help/energy-input-help.component.html, src/app/phast/losses/losses-help/exhaust-gas-help/exhaust-gas-help.component.html, src/app/phast/losses/losses-help/extended-surface-losses-help/extended-surface-losses-help.component.html, src/app/phast/losses/losses-help/fixture-losses-help/fixture-losses-help.component.html, src/app/phast/losses/losses-help/flue-gas-losses-help/flue-gas-losses-help.component.html, src/app/phast/losses/losses-help/gas-leakage-losses-help/gas-leakage-losses-help.component.html, src/app/phast/losses/losses-help/opening-losses-help/opening-losses-help.component.html, src/app/phast/losses/losses-help/slag-help/slag-help.component.html, src/app/phast/losses/losses-help/wall-losses-help/wall-losses-help.component.html, src/app/psat/explore-opportunities/explore-opportunities-help/explore-opportunities-help.component.html, src/app/psat/help-panel/field-data-help/field-data-help.component.html, src/app/psat/help-panel/pump-fluid-help/pump-fluid-help.component.html
=> removed min/max tables that don't provide useful information

src/app/settings/assessment-settings/assessment-settings.component.html
=> updated red button text

src/app/calculator/furnaces/heat-cascading/heat-cascading-form.service.ts, src/app/calculator/furnaces/heat-cascading/heat-cascading-form/heat-cascading-form.component.html, src/app/calculator/furnaces/heat-cascading/heat-cascading-form/heat-cascading-form.component.ts, src/app/calculator/furnaces/heat-cascading/heat-cascading-help/heat-cascading-help.component.html, src/app/calculator/furnaces/heat-cascading/heat-cascading-results/heat-cascading-results.component.html, src/app/calculator/furnaces/heat-cascading/heat-cascading-results/heat-cascading-results.component.ts, src/app/calculator/furnaces/heat-cascading/heat-cascading.component.html, src/app/calculator/furnaces/heat-cascading/heat-cascading.component.ts, src/app/calculator/furnaces/heat-cascading/heat-cascading.service.ts, src/app/shared/models/phast/heatCascading.ts, src/app/shared/models/treasure-hunt.ts, src/app/treasure-hunt/calculators/calculators.component.html, src/app/treasure-hunt/calculators/calculators.module.ts, src/app/treasure-hunt/calculators/calculators.service.ts, src/app/treasure-hunt/convert-input-data.service.ts, src/app/treasure-hunt/find-treasure/find-treasure.component.html, src/app/treasure-hunt/treasure-chest/export-opportunities/export-opportunities.component.html, src/app/treasure-hunt/treasure-chest/export-opportunities/export-opportunities.component.ts, src/app/treasure-hunt/treasure-chest/import-opportunities.service.ts, src/app/treasure-hunt/treasure-chest/opportunity-cards/opportunity-cards.service.ts, src/app/treasure-hunt/treasure-chest/opportunity-cards/sort-cards.service.ts, src/app/treasure-hunt/treasure-chest/treasure-chest-menu/calculator-type-dropdown/calculator-type-dropdown.component.ts, src/app/treasure-hunt/treasure-hunt-calculator-services/heat-cascading-treasure-hunt.service.spec.ts, src/app/treasure-hunt/treasure-hunt-calculator-services/heat-cascading-treasure-hunt.service.ts, src/app/treasure-hunt/treasure-hunt-calculator-services/treasure-hunt-opportunity.service.ts, src/app/treasure-hunt/treasure-hunt-report/opportunity-summary.service.ts, src/app/treasure-hunt/treasure-hunt.module.ts
connects #4486 
Add heat cascading calculator to treasure hunt
=> Issue 4486

src/app/fsat/fsat-report/results-summary/results-summary.component.html, src/app/fsat/fsat-report/results-summary/results-summary.component.ts, src/app/psat/psat-report/output-summary/output-summary.component.html, src/app/psat/psat-report/output-summary/output-summary.component.ts, src/app/report-rollup/fsat-report-rollup.service.ts, src/app/report-rollup/psat-report-rollup.service.ts
=> Issue 2383: PSAT & FSAT modification notes on report and rollup

src/app/calculator/furnaces/air-heating/air-heating-form.service.ts, src/app/calculator/furnaces/air-heating/air-heating-form/air-heating-form.component.html, src/app/calculator/furnaces/air-heating/air-heating-form/air-heating-form.component.ts, src/app/calculator/furnaces/air-heating/air-heating-results/air-heating-results.component.html, src/app/calculator/furnaces/air-heating/air-heating-results/air-heating-results.component.ts, src/app/calculator/furnaces/air-heating/air-heating.component.html, src/app/calculator/furnaces/air-heating/air-heating.component.ts, src/app/calculator/furnaces/air-heating/air-heating.service.ts, src/app/shared/models/phast/airHeating.ts, src/app/shared/models/treasure-hunt.ts, src/app/treasure-hunt/calculators/calculators.component.html, src/app/treasure-hunt/calculators/calculators.module.ts, src/app/treasure-hunt/calculators/calculators.service.ts, src/app/treasure-hunt/convert-input-data.service.ts, src/app/treasure-hunt/find-treasure/find-treasure.component.html, src/app/treasure-hunt/treasure-chest/export-opportunities/export-opportunities.component.html, src/app/treasure-hunt/treasure-chest/export-opportunities/export-opportunities.component.ts, src/app/treasure-hunt/treasure-chest/import-opportunities.service.ts, src/app/treasure-hunt/treasure-chest/opportunity-cards/opportunity-cards.service.ts, src/app/treasure-hunt/treasure-chest/opportunity-cards/sort-cards.service.ts, src/app/treasure-hunt/treasure-chest/treasure-chest-menu/calculator-type-dropdown/calculator-type-dropdown.component.ts, src/app/treasure-hunt/treasure-hunt-calculator-services/air-heating-treasure-hunt.service.spec.ts, src/app/treasure-hunt/treasure-hunt-calculator-services/air-heating-treasure-hunt.service.ts, src/app/treasure-hunt/treasure-hunt-calculator-services/treasure-hunt-opportunity.service.ts, src/app/treasure-hunt/treasure-hunt-report/opportunity-summary.service.ts, src/app/treasure-hunt/treasure-hunt.module.ts
connects #4485 
Adding air heating calculator to treasure hunt
=> Issue 4485

src/app/calculator/furnaces/heat-cascading/heat-cascading.component.ts, src/app/calculator/steam/water-heating/water-heating-form.service.ts, src/app/calculator/steam/water-heating/water-heating-form/water-heating-form.component.html, src/app/calculator/steam/water-heating/water-heating-form/water-heating-form.component.ts, src/app/calculator/steam/water-heating/water-heating-results/water-heating-results.component.html, src/app/calculator/steam/water-heating/water-heating-results/water-heating-results.component.ts, src/app/calculator/steam/water-heating/water-heating.component.html, src/app/calculator/steam/water-heating/water-heating.component.ts, src/app/calculator/steam/water-heating/water-heating.service.ts, src/app/shared/models/steam/waterHeating.ts, src/app/shared/models/treasure-hunt.ts, src/app/treasure-hunt/calculators/calculators.component.html, src/app/treasure-hunt/calculators/calculators.module.ts, src/app/treasure-hunt/calculators/calculators.service.ts, src/app/treasure-hunt/convert-input-data.service.ts, src/app/treasure-hunt/find-treasure/find-treasure.component.html, src/app/treasure-hunt/treasure-chest/export-opportunities/export-opportunities.component.html, src/app/treasure-hunt/treasure-chest/export-opportunities/export-opportunities.component.ts, src/app/treasure-hunt/treasure-chest/import-opportunities.service.ts, src/app/treasure-hunt/treasure-chest/opportunity-cards/opportunity-cards.service.ts, src/app/treasure-hunt/treasure-chest/opportunity-cards/sort-cards.service.ts, src/app/treasure-hunt/treasure-chest/treasure-chest-menu/calculator-type-dropdown/calculator-type-dropdown.component.ts, src/app/treasure-hunt/treasure-hunt-calculator-services/treasure-hunt-opportunity.service.ts, src/app/treasure-hunt/treasure-hunt-calculator-services/water-heating-treasure-hunt.service.spec.ts, src/app/treasure-hunt/treasure-hunt-calculator-services/water-heating-treasure-hunt.service.ts, src/app/treasure-hunt/treasure-hunt-report/opportunity-summary.service.ts, src/app/treasure-hunt/treasure-hunt.module.ts
connects #4569 
- Add vent steam to heat water to TH
- set heat cascade inputs undefined on destroy when in th
=> Issue 4569

src/app/calculator/pumps/head-tool/head-tool-help/head-tool-help.component.html, src/app/fsat/help-panel/fan-field-data-help/fan-field-data-help.component.html, src/app/psat/explore-opportunities/explore-opportunities-help/explore-opportunities-help.component.html, src/app/psat/help-panel/field-data-help/field-data-help.component.html, src/app/psat/help-panel/motor-help/motor-help.component.html
=> removed other useless min/max tables

src/app/calculator/furnaces/flue-gas/energy-form.service.spec.ts, src/app/calculator/furnaces/flue-gas/energy-form.service.ts, src/app/calculator/furnaces/flue-gas/energy-form/energy-form.component.html, src/app/calculator/furnaces/flue-gas/energy-form/energy-form.component.ts, src/app/calculator/furnaces/flue-gas/flue-gas-form-volume/flue-gas-form-volume.component.html, src/app/calculator/furnaces/flue-gas/flue-gas-form.service.ts, src/app/calculator/furnaces/flue-gas/flue-gas.component.html, src/app/calculator/furnaces/flue-gas/flue-gas.component.ts, src/app/calculator/furnaces/flue-gas/flue-gas.module.ts, src/app/calculator/furnaces/flue-gas/flue-gas.service.ts, src/app/shared/models/treasure-hunt.ts, src/app/treasure-hunt/treasure-hunt-calculator-services/flue-gas-treasure-hunt.service.ts
connects #4553 
Move utility type above fuel cost
=> Issue 4553 Needs Verification

src/app/ssmt/ssmt.component.ts
connects #4587 
Reset sankey list on ssmt changes
=> Issue 4587

src/app/calculator/furnaces/air-heating/air-heating.service.ts, src/app/calculator/furnaces/heat-cascading/heat-cascading.service.ts, src/app/calculator/furnaces/waste-heat/waste-heat.service.ts, src/app/calculator/steam/stack-loss/stack-loss.service.ts, src/app/calculator/steam/water-heating/water-heating.service.ts, src/app/phast/phast.service.ts, src/app/shared/models/phast/heatCascading.ts, src/app/shared/models/phast/o2Enrichment.ts, src/app/suiteDb/flue-gas-material/flue-gas-material.component.ts, src/app/tools-suite-api/process-heating-api.service.spec.ts, src/app/tools-suite-api/process-heating-api.service.ts, src/app/tools-suite-api/suite-api-enum.service.ts, src/app/tools-suite-api/tools-suite-api.module.ts
connects #4488 
Add PHAST API service
=> Issue 4488

src/app/calculator/fans/fan-system-checklist/fan-system-checklist.service.ts, src/app/calculator/furnaces/flue-gas/flue-gas-form-volume/flue-gas-form-volume.component.ts, src/app/calculator/furnaces/flue-gas/flue-gas-modal/flue-gas-modal.component.html, src/app/calculator/furnaces/flue-gas/flue-gas-modal/flue-gas-modal.component.ts, src/app/calculator/furnaces/heat-cascading/heat-cascading-form.service.ts, src/app/calculator/furnaces/heat-cascading/heat-cascading-form/heat-cascading-form.component.html, src/app/calculator/furnaces/heat-cascading/heat-cascading-form/heat-cascading-form.component.ts, src/app/calculator/furnaces/heat-cascading/heat-cascading-help/heat-cascading-help.component.html, src/app/calculator/furnaces/heat-cascading/heat-cascading-help/heat-cascading-help.component.ts, src/app/calculator/furnaces/heat-cascading/heat-cascading.service.ts, src/app/phast/phast.service.ts, src/app/shared/models/phast/heatCascading.ts, src/app/shared/models/phast/losses/flueGas.ts
connects #4582 
- Populate higher heating value and ah in sec process
- Change rxjs import to stop console warning
=> Issue 4582

src/app/calculator/standalone.service.ts, src/app/shared/models/standalone.ts, src/app/tools-suite-api/standalone-suite-api.service.spec.ts, src/app/tools-suite-api/standalone-suite-api.service.ts, src/app/tools-suite-api/suite-api-enum.service.ts, src/app/tools-suite-api/tools-suite-api.module.ts
=> Add standalone api service

src/app/fsat/explore-opportunities/explore-opportunities-help/explore-opportunities-help.component.html, src/app/fsat/fsat-tabs/fsat-tabs.component.html, src/app/fsat/fsat-tabs/fsat-tabs.component.ts, src/app/fsat/fsat.component.html, src/app/fsat/fsat.component.ts, src/app/fsat/help-panel/fan-setup-help/fan-setup-help.component.html, src/app/fsat/help-panel/fsat-fluid-help/fsat-fluid-help.component.html, src/app/fsat/help-panel/help-panel.component.html, src/app/fsat/modify-conditions/modify-conditions-tabs/modify-conditions-tabs.component.html, src/app/fsat/modify-conditions/modify-conditions.component.html, src/app/psat/pump-fluid/pump-fluid.component.html
=> combined fan and fluid tabs

src/app/calculator/standalone.service.ts, src/app/shared/models/standalone.ts, src/app/tools-suite-api/calculator-suite-api.service.spec.ts, src/app/tools-suite-api/calculator-suite-api.service.ts, src/app/tools-suite-api/tools-suite-api.module.ts
connects #4494 
Add calculator API service
=> Issue 4494

src/app/ssmt/modify-conditions/modify-conditions.component.css, src/app/ssmt/modify-conditions/modify-conditions.component.html
=> Issue 4588

src/app/calculator/compressed-air/air-leak/air-leak-copy-table/air-leak-copy-table.component.css, src/app/calculator/compressed-air/air-leak/air-leak-results/air-leak-results.component.html, src/app/calculator/compressed-air/air-leak/air-leak-results/air-leak-results.component.ts, src/app/calculator/fans/fan-system-checklist/fan-system-checklist-copy-table/fan-system-checklist-copy-table.component.css, src/app/calculator/furnaces/efficiency-improvement/efficiency-improvement-graph/efficiency-improvement-graph.component.css, src/app/calculator/furnaces/o2-enrichment/enrichment-graph/enrichment-graph.component.css, src/app/calculator/furnaces/o2-enrichment/o2-enrichment-copy-table/o2-enrichment-copy-table.component.css, src/app/calculator/furnaces/waste-heat/waste-heat-results/waste-heat-results.component.ts, src/app/calculator/lighting/lighting-replacement/lighting-replacement-results/lighting-replacement-results.component.ts, src/app/calculator/motors/motor-drive/motor-drive-table/motor-drive-table.component.html, src/app/calculator/motors/motor-drive/motor-drive-table/motor-drive-table.component.ts, src/app/calculator/motors/motor-performance/motor-performance-chart/motor-performance-chart.component.css, src/app/calculator/motors/replace-existing/replace-existing-results/replace-existing-results.component.html, src/app/calculator/motors/replace-existing/replace-existing-results/replace-existing-results.component.ts, src/app/calculator/pumps/achievable-efficiency/achievable-efficiency-graph/achievable-efficiency-graph.component.css, src/app/calculator/pumps/specific-speed/specific-speed-graph/specific-speed-graph.component.css, src/app/calculator/steam/saturated-properties/saturated-properties-hidden-copy-table/saturated-properties-hidden-copy-table.component.css, src/app/calculator/steam/saturated-properties/saturated-properties-hidden-copy-table/saturated-properties-hidden-copy-table.component.html, src/app/calculator/steam/saturated-properties/saturated-properties-hidden-copy-table/saturated-properties-hidden-copy-table.component.spec.ts, src/app/calculator/steam/saturated-properties/saturated-properties-hidden-copy-table/saturated-properties-hidden-copy-table.component.ts, src/app/calculator/steam/saturated-properties/saturated-properties-table/saturated-properties-table.component.html, src/app/calculator/steam/saturated-properties/saturated-properties-table/saturated-properties-table.component.ts, src/app/calculator/steam/saturated-properties/saturated-properties.module.ts, src/app/calculator/system-and-equipment-curve/system-and-equipment-curve-graph/system-and-equipment-curve-graph.component.css, src/app/treasure-hunt/treasure-hunt-report/report-graphs/effort-savings-chart/effort-savings-chart.component.css
=> Issue 4143

src/app/calculator/furnaces/atmosphere/atmosphere-form/atmosphere-form.component.ts, src/app/calculator/furnaces/charge-material/gas-material-form/gas-material-form.component.ts, src/app/calculator/furnaces/charge-material/liquid-material-form/liquid-material-form.component.ts, src/app/calculator/furnaces/charge-material/solid-material-form/solid-material-form.component.ts, src/app/calculator/furnaces/fixture/fixture-form/fixture-form.component.ts, src/app/calculator/furnaces/flue-gas/flue-gas-form-mass/flue-gas-form-mass.component.ts, src/app/calculator/furnaces/flue-gas/flue-gas-form-volume/flue-gas-form-volume.component.ts, src/app/calculator/furnaces/wall/wall-form/wall-form.component.ts, src/app/phast/losses/atmosphere-losses/atmosphere-losses-form/atmosphere-losses-form.component.ts, src/app/phast/losses/charge-material/gas-charge-material-form/gas-charge-material-form.component.ts, src/app/phast/losses/charge-material/liquid-charge-material-form/liquid-charge-material-form.component.ts, src/app/phast/losses/charge-material/solid-charge-material-form/solid-charge-material-form.component.ts, src/app/phast/losses/fixture-losses/fixture-losses-form/fixture-losses-form.component.ts, src/app/phast/losses/flue-gas-losses/flue-gas-losses-form-mass/flue-gas-losses-form-mass.component.ts, src/app/phast/losses/flue-gas-losses/flue-gas-losses-form-volume/flue-gas-losses-form-volume.component.ts, src/app/phast/losses/wall-losses/wall-losses-form/wall-losses-form.component.ts
=> PHAST material options update in mod and baseline

src/app/report-rollup/pre-assessment-print/pre-assessment-table/pre-assessment-table.component.ts
=> Issue 1696 Pre-Assessments table in rollup colors fixed

src/app/calculator/compressed-air/compressed-air-pressure-reduction/compressed-air-pressure-reduction-form/compressed-air-pressure-reduction-form.component.html
#4527 
Conditions should check form value
=> Issue 4527

src/app/calculator/furnaces/air-heating/air-heating-form/air-heating-form.component.html, src/app/calculator/furnaces/air-heating/air-heating-form/air-heating-form.component.ts, src/app/calculator/furnaces/air-heating/air-heating.component.ts, src/app/calculator/furnaces/air-heating/air-heating.service.ts, src/app/calculator/furnaces/waste-heat/waste-heat.component.ts, src/app/calculator/furnaces/waste-heat/waste-heat.service.ts, src/app/calculator/steam/water-heating/water-heating-form/water-heating-form.component.html, src/app/calculator/steam/water-heating/water-heating-form/water-heating-form.component.ts, src/app/calculator/steam/water-heating/water-heating.component.ts, src/app/calculator/steam/water-heating/water-heating.service.ts, src/app/treasure-hunt/treasure-hunt-calculator-services/air-heating-treasure-hunt.service.ts, src/app/treasure-hunt/treasure-hunt-calculator-services/waste-heat-treasure-hunt.service.ts, src/app/treasure-hunt/treasure-hunt-calculator-services/water-heating-treasure-hunt.service.ts
connects #4485 #4569 #4480 
Putting these together as is essentially the same changes:
- Calculator should take TH fuel cost
- Fix calculator annual energy cost in summary card
=> Issue 4485 4569 4480

src/app/compressed-air-assessment/inventory/control-data/control-data.component.html, src/app/compressed-air-assessment/inventory/design-details/design-details.component.html, src/app/compressed-air-assessment/inventory/design-details/design-details.component.ts, src/app/compressed-air-assessment/inventory/inventory.service.ts, src/app/compressed-air-assessment/inventory/nameplate-data/nameplate-data.component.html, src/app/compressed-air-assessment/inventory/performance-points/blowoff/blowoff.component.ts, src/app/compressed-air-assessment/inventory/performance-points/calculations/blowoff-calculations.service.ts, src/app/compressed-air-assessment/inventory/performance-points/calculations/full-load-calculations.service.ts, src/app/compressed-air-assessment/inventory/performance-points/calculations/max-full-flow-calculations.service.ts, src/app/compressed-air-assessment/inventory/performance-points/calculations/no-load-calculations.service.ts, src/app/compressed-air-assessment/inventory/performance-points/calculations/performance-point-calculations.service.ts, src/app/compressed-air-assessment/inventory/performance-points/calculations/shared-point-calculations.service.ts, src/app/compressed-air-assessment/inventory/performance-points/calculations/unload-point-calculations.service.ts, src/app/compressed-air-assessment/inventory/performance-points/full-load/full-load.component.ts, src/app/compressed-air-assessment/inventory/performance-points/max-full-flow/max-full-flow.component.ts, src/app/compressed-air-assessment/inventory/performance-points/no-load/no-load.component.ts, src/app/compressed-air-assessment/inventory/performance-points/unload-point/unload-point.component.ts, src/app/shared/models/compressed-air-assessment.ts
connects #4502 
updates calculations for performance points
removes generic compressor usage in calculations
adds field to inventory to get rid of generic compressors
=> Issue 4502

src/app/compressed-air-assessment/compressed-air-assessment.component.ts, src/app/compressed-air-assessment/compressed-air-assessment.service.ts, src/app/compressed-air-assessment/compressed-air-calculation.service.ts, src/app/compressed-air-assessment/day-types/day-types.component.html, src/app/compressed-air-assessment/day-types/day-types.component.ts, src/app/compressed-air-assessment/system-profile/profile-setup-form/profile-setup-form.component.html, src/app/compressed-air-assessment/system-profile/profile-setup-form/profile-setup-form.component.ts, src/app/compressed-air-assessment/system-profile/system-profile-setup/compressor-ordering-table/compressor-ordering-table.component.css, src/app/compressed-air-assessment/system-profile/system-profile-setup/compressor-ordering-table/compressor-ordering-table.component.html, src/app/compressed-air-assessment/system-profile/system-profile-setup/compressor-ordering-table/compressor-ordering-table.component.ts, src/app/compressed-air-assessment/system-profile/system-profile-setup/operating-profile-table/operating-profile-table.component.css, src/app/compressed-air-assessment/system-profile/system-profile-setup/operating-profile-table/operating-profile-table.component.html, src/app/compressed-air-assessment/system-profile/system-profile-setup/operating-profile-table/operating-profile-table.component.ts, src/app/compressed-air-assessment/system-profile/system-profile-setup/system-profile-setup.component.html, src/app/compressed-air-assessment/system-profile/system-profile.service.ts, src/app/dashboard/assessment.service.ts, src/app/dashboard/directory-dashboard/directory-items/assessment-item/assessment-item.component.css, src/app/log-tool/day-type-analysis/day-type-analysis.service.ts, src/app/log-tool/day-type-analysis/day-type-menu/day-type-menu.component.html, src/app/log-tool/day-type-analysis/day-type-menu/select-assessment-modal/select-assessment-modal.component.css, src/app/log-tool/day-type-analysis/day-type-menu/select-assessment-modal/select-assessment-modal.component.html, src/app/log-tool/day-type-analysis/day-type-menu/select-assessment-modal/select-assessment-modal.component.ts, src/app/log-tool/log-tool-models.ts, src/app/log-tool/log-tool.component.ts, src/app/log-tool/log-tool.module.ts, src/app/log-tool/log-tool.service.ts, src/app/log-tool/visualize/visualize-menu/visualize-menu.service.ts, src/app/shared/models/compressed-air-assessment.ts, src/assets/styles/utilities.css
connects #4630 
integrates compressed air day types and data explorer
=> Issue 4630

src/app/compressed-air-assessment/inventory/control-data/control-data.component.ts, src/app/compressed-air-assessment/inventory/performance-points/blowoff/blowoff.component.ts, src/app/compressed-air-assessment/inventory/performance-points/calculations/full-load-calculations.service.ts, src/app/compressed-air-assessment/inventory/performance-points/calculations/max-full-flow-calculations.service.ts, src/app/compressed-air-assessment/inventory/performance-points/calculations/shared-point-calculations.service.ts, src/app/compressed-air-assessment/inventory/performance-points/calculations/unload-point-calculations.service.ts, src/app/compressed-air-assessment/inventory/performance-points/full-load/full-load.component.ts, src/app/compressed-air-assessment/inventory/performance-points/max-full-flow/max-full-flow.component.ts, src/app/compressed-air-assessment/inventory/performance-points/no-load/no-load.component.ts, src/app/compressed-air-assessment/inventory/performance-points/unload-point/unload-point.component.ts
fixes to performance point form updates
fixes to unload point and number of steps on control changes
=> Performance points

src/app/compressed-air-assessment/compressed-air-assessment.component.html, src/app/compressed-air-assessment/compressed-air-banner/setup-tabs/setup-tabs.component.html, src/app/compressed-air-assessment/compressed-air-calculation.service.ts, src/app/compressed-air-assessment/inventory/generic-compressor-modal/filter-compressors/filter-compressors.component.html, src/app/compressed-air-assessment/inventory/nameplate-data/nameplate-data.component.html, src/app/compressed-air-assessment/inventory/performance-points/blowoff/blowoff.component.html, src/app/compressed-air-assessment/inventory/performance-points/blowoff/blowoff.component.ts, src/app/compressed-air-assessment/inventory/performance-points/calculations/full-load-calculations.service.ts, src/app/compressed-air-assessment/inventory/performance-points/calculations/max-full-flow-calculations.service.ts, src/app/compressed-air-assessment/inventory/performance-points/calculations/no-load-calculations.service.ts, src/app/compressed-air-assessment/inventory/performance-points/calculations/performance-point-calculations.service.ts, src/app/compressed-air-assessment/inventory/performance-points/calculations/shared-point-calculations.service.ts, src/app/compressed-air-assessment/inventory/performance-points/calculations/unload-point-calculations.service.ts, src/app/compressed-air-assessment/inventory/performance-points/full-load/full-load.component.html, src/app/compressed-air-assessment/inventory/performance-points/full-load/full-load.component.ts, src/app/compressed-air-assessment/inventory/performance-points/max-full-flow/max-full-flow.component.html, src/app/compressed-air-assessment/inventory/performance-points/max-full-flow/max-full-flow.component.ts, src/app/compressed-air-assessment/inventory/performance-points/no-load/no-load.component.html, src/app/compressed-air-assessment/inventory/performance-points/no-load/no-load.component.ts, src/app/compressed-air-assessment/inventory/performance-points/unload-point/unload-point.component.html, src/app/compressed-air-assessment/inventory/performance-points/unload-point/unload-point.component.ts, src/app/compressed-air-assessment/system-basics/system-basics.component.html, src/app/compressed-air-assessment/system-profile/profile-setup-form/profile-setup-form.component.html, src/app/compressed-air-assessment/system-profile/profile-setup-form/profile-setup-form.component.ts, src/app/compressed-air-assessment/system-profile/system-profile-graphs/system-profile-graphs.component.html, src/app/compressed-air-assessment/system-profile/system-profile-graphs/system-profile-graphs.component.ts, src/app/compressed-air-assessment/system-profile/system-profile-setup/compressor-ordering-table/compressor-ordering-table.component.css, src/app/compressed-air-assessment/system-profile/system-profile-setup/operating-profile-table/operating-profile-table.component.css, src/app/compressed-air-assessment/system-profile/system-profile-setup/operating-profile-table/operating-profile-table.component.ts
connects #4645 
various quick fixes for compressed air
=> Issue 4645

src/app/compressed-air-assessment/inventory/control-data/control-data.component.css, src/app/compressed-air-assessment/inventory/control-data/control-data.component.html, src/app/compressed-air-assessment/inventory/control-data/control-data.component.ts, src/app/compressed-air-assessment/inventory/design-details/design-details.component.css, src/app/compressed-air-assessment/inventory/design-details/design-details.component.html, src/app/compressed-air-assessment/inventory/design-details/design-details.component.ts, src/app/compressed-air-assessment/inventory/inlet-conditions/inlet-conditions.component.css, src/app/compressed-air-assessment/inventory/inlet-conditions/inlet-conditions.component.html, src/app/compressed-air-assessment/inventory/inlet-conditions/inlet-conditions.component.ts, src/app/compressed-air-assessment/inventory/inventory.service.ts, src/app/compressed-air-assessment/inventory/performance-points/performance-points.component.css, src/app/compressed-air-assessment/inventory/performance-points/performance-points.component.html, src/app/compressed-air-assessment/inventory/performance-points/performance-points.component.ts
=> add collapsing for inventory page

src/app/compressed-air-assessment/system-profile/profile-setup-form/profile-setup-form.component.html, src/app/compressed-air-assessment/system-profile/profile-setup-form/profile-setup-form.component.ts, src/app/compressed-air-assessment/system-profile/system-profile-setup/operating-profile-table/operating-profile-table.component.html
update data interval options for profiling
=> Data interval

src/app/calculator/furnaces/air-heating/air-heating.component.ts, src/app/calculator/furnaces/heat-cascading/heat-cascading.component.ts, src/app/calculator/furnaces/waste-heat/waste-heat.component.ts, src/app/calculator/steam/water-heating/water-heating.component.ts
Waste heat, Heat cascading, and air heating calcs in addition to water heating
=> Calculators Display Open Help when Set to in Settings

src/app/log-tool/log-tool-data.service.ts, src/app/log-tool/log-tool-models.ts, src/app/log-tool/log-tool.service.ts, src/app/log-tool/system-setup/clean-data/clean-data.component.html, src/app/log-tool/system-setup/clean-data/clean-data.component.ts, src/app/log-tool/system-setup/setup-data/setup-data.component.html, src/app/log-tool/system-setup/setup-data/setup-data.component.ts
Connects #4609 . Connects #3773 .
=> Added Excel import to Data Explorer and allowed for separate date and time fields

src/app/compressed-air-assessment/compressed-air-assessment.component.ts, src/app/log-tool/day-type-analysis/day-type-menu/select-assessment-modal/select-assessment-modal.component.ts
connects #4666 
fixes setting data from log tool into compressed air assessment day types.
fixes inventory bug when changing assessments
=> fix dependencies for setting compressed air assessment data

src/app/log-tool/visualize/visualize-graph/visualize-graph.component.ts, src/app/log-tool/visualize/visualize-menu/graph-basics/graph-basics.component.html, src/app/log-tool/visualize/visualize-menu/graph-basics/graph-basics.component.ts
=> allowed lines and markers in data explorer scatterplot

src/app/compressed-air-assessment/system-profile/system-profile-graphs/system-profile-graphs.component.ts, src/app/compressed-air-assessment/system-profile/system-profile-summary/system-profile-summary.component.html, src/app/compressed-air-assessment/system-profile/system-profile.service.ts
=> dont add data when compressor is off in ordering

src/app/log-tool/system-setup/setup-data/setup-data.component.html, src/app/log-tool/system-setup/setup-data/setup-data.component.ts
Connects #4609 . Combines the Excel and CSV file imports.
=> combined file imports

src/app/compressed-air-assessment/add-modification-modal/add-modification-modal.component.html, src/app/compressed-air-assessment/add-modification-modal/add-modification-modal.component.spec.ts, src/app/compressed-air-assessment/add-modification-modal/add-modification-modal.component.ts, src/app/compressed-air-assessment/compressed-air-assessment.component.html, src/app/compressed-air-assessment/compressed-air-assessment.component.ts, src/app/compressed-air-assessment/compressed-air-assessment.module.ts, src/app/compressed-air-assessment/compressed-air-assessment.service.ts, src/app/compressed-air-assessment/compressed-air-banner/compressed-air-banner.component.ts, src/app/compressed-air-assessment/explore-opportunities/explore-opportunities.component.ts, src/app/compressed-air-assessment/modification-list-modal/modification-list-modal.component.css, src/app/compressed-air-assessment/modification-list-modal/modification-list-modal.component.html, src/app/compressed-air-assessment/modification-list-modal/modification-list-modal.component.spec.ts, src/app/compressed-air-assessment/modification-list-modal/modification-list-modal.component.ts
=> Add modification modals

src/app/compressed-air-assessment/compressed-air-assessment.component.html, src/app/compressed-air-assessment/system-information/system-capacity-modal/system-capacity-modal.component.ts, src/app/compressed-air-assessment/system-information/system-information.component.html, src/app/compressed-air-assessment/system-information/system-information.component.ts
connects #4669 
Change decimal places and add unit conversion
=> Issue 4669 

src/app/fsat/add-modification/add-modification.component.html, src/app/fsat/add-modification/add-modification.component.ts, src/app/fsat/fsat-report/results-summary/results-summary.component.html, src/app/fsat/fsat-results/fsat-results-panel/fsat-results-panel.component.html, src/app/fsat/fsat-results/fsat-results-panel/fsat-results-panel.component.ts, src/app/fsat/modification-list/modification-list.component.html, src/app/psat/add-modification/add-modification.component.html, src/app/psat/add-modification/add-modification.component.ts, src/app/psat/explore-opportunities/explore-opportunities-results/explore-opportunities-results.component.html, src/app/psat/explore-opportunities/explore-opportunities-results/explore-opportunities-results.component.ts, src/app/psat/modification-list/modification-list.component.html, src/app/psat/psat-report/output-summary/output-summary.component.html
=> Compare two existing pump/fan #4460 - Fixes made

src/app/compressed-air-assessment/compressed-air-assessment.component.html, src/app/compressed-air-assessment/compressed-air-assessment.component.ts, src/app/compressed-air-assessment/compressed-air-banner/setup-tabs/setup-tabs.component.ts, src/app/compressed-air-assessment/day-types/day-types.component.html, src/app/compressed-air-assessment/day-types/day-types.component.ts, src/app/compressed-air-assessment/inventory/inventory.service.ts
=> Issue 4693

src/app/compressed-air-assessment/system-profile/system-profile-setup/operating-profile-table/operating-profile-table.component.html, src/app/compressed-air-assessment/system-profile/system-profile-setup/operating-profile-table/operating-profile-table.component.ts
=> Issue 4697

src/app/compressed-air-assessment/compressed-air-calculation.service.ts, src/app/compressed-air-assessment/system-profile/system-profile-setup/operating-profile-table/operating-profile-table.component.html, src/app/compressed-air-assessment/system-profile/system-profile-setup/operating-profile-table/operating-profile-table.component.ts
connects #4698 
- Update profile on input change
- Saving bug appears to have been when compressor was in invalid state. #4709 will prevent getting to that state.
=> Issue 4698

src/app/compressed-air-assessment/compressed-air-assessment.component.ts, src/app/compressed-air-assessment/compressed-air-banner/setup-tabs/setup-tabs.component.ts, src/app/compressed-air-assessment/inventory/inventory.component.ts, src/app/compressed-air-assessment/inventory/inventory.service.ts, src/app/compressed-air-assessment/inventory/performance-points/performance-points.component.css, src/app/compressed-air-assessment/inventory/performance-points/performance-points.component.html, src/app/compressed-air-assessment/inventory/performance-points/performance-points.component.ts, src/app/compressed-air-assessment/results-panel/inventory-table/inventory-table.component.css, src/app/compressed-air-assessment/results-panel/inventory-table/inventory-table.component.html, src/app/compressed-air-assessment/results-panel/inventory-table/inventory-table.component.ts, src/app/shared/models/compressed-air-assessment.ts
connects #4709 
Add additional compressor validation
=> Issue-4709

src/app/log-tool/log-tool-data.service.ts, src/app/log-tool/system-setup/clean-data/clean-data.component.ts, src/app/log-tool/system-setup/setup-data/setup-data.component.html, src/app/log-tool/system-setup/setup-data/setup-data.component.ts
Connects #4609 . Connects #3773
=> fixed error with separate date and time values

src/app/phast/losses/flue-gas-losses/flue-gas-losses-moisture/flue-gas-losses-moisture.component.html, src/app/phast/losses/flue-gas-losses/flue-gas-losses-moisture/flue-gas-losses-moisture.component.ts, src/app/phast/losses/flue-gas-losses/flue-gas-moisture-results/flue-gas-moisture-results.component.html
=> fixed display of modal

src/app/compressed-air-assessment/inventory/performance-points/blowoff/blowoff.component.css, src/app/compressed-air-assessment/inventory/performance-points/blowoff/blowoff.component.html, src/app/compressed-air-assessment/inventory/performance-points/blowoff/blowoff.component.ts, src/app/compressed-air-assessment/inventory/performance-points/full-load/full-load.component.css, src/app/compressed-air-assessment/inventory/performance-points/full-load/full-load.component.html, src/app/compressed-air-assessment/inventory/performance-points/full-load/full-load.component.ts, src/app/compressed-air-assessment/inventory/performance-points/max-full-flow/max-full-flow.component.css, src/app/compressed-air-assessment/inventory/performance-points/max-full-flow/max-full-flow.component.html, src/app/compressed-air-assessment/inventory/performance-points/max-full-flow/max-full-flow.component.ts, src/app/compressed-air-assessment/inventory/performance-points/no-load/no-load.component.css, src/app/compressed-air-assessment/inventory/performance-points/no-load/no-load.component.html, src/app/compressed-air-assessment/inventory/performance-points/no-load/no-load.component.ts, src/app/compressed-air-assessment/inventory/performance-points/performance-points.component.css, src/app/compressed-air-assessment/inventory/performance-points/performance-points.component.html, src/app/compressed-air-assessment/inventory/performance-points/unload-point/unload-point.component.css, src/app/compressed-air-assessment/inventory/performance-points/unload-point/unload-point.component.html, src/app/compressed-air-assessment/inventory/performance-points/unload-point/unload-point.component.ts
connects #4695 
Change Perf point layout to match airmaster
=> Issue 4695

src/app/compressed-air-assessment/compressed-air-assessment.component.ts, src/app/compressed-air-assessment/compressed-air-assessment.service.ts, src/app/compressed-air-assessment/compressed-air-banner/setup-tabs/setup-tabs.component.ts, src/app/compressed-air-assessment/day-types/day-types.component.html, src/app/compressed-air-assessment/inventory/inventory.service.ts, src/app/compressed-air-assessment/system-information/system-information.component.html, src/app/compressed-air-assessment/system-profile/system-profile-setup/operating-profile-table/operating-profile-table.component.html, src/app/compressed-air-assessment/system-profile/system-profile-setup/operating-profile-table/operating-profile-table.component.ts
=> Fixing setup tabs, next button, modify system-profile validation

src/app/compressed-air-assessment/system-profile/system-profile-setup/operating-profile-table/operating-profile-table.component.html, src/app/compressed-air-assessment/system-profile/system-profile-setup/operating-profile-table/operating-profile-table.component.ts
=> Issue 4710 b

src/app/compressed-air-assessment/inventory/design-details/design-details.component.html, src/app/compressed-air-assessment/inventory/inventory.service.ts, src/app/compressed-air-assessment/inventory/performance-points/blowoff/blowoff.component.ts, src/app/compressed-air-assessment/inventory/performance-points/full-load/full-load.component.ts, src/app/compressed-air-assessment/inventory/performance-points/max-full-flow/max-full-flow.component.html, src/app/compressed-air-assessment/inventory/performance-points/max-full-flow/max-full-flow.component.ts, src/app/compressed-air-assessment/inventory/performance-points/no-load/no-load.component.ts, src/app/compressed-air-assessment/inventory/performance-points/performance-points-form.service.ts, src/app/compressed-air-assessment/inventory/performance-points/unload-point/unload-point.component.html, src/app/compressed-air-assessment/inventory/performance-points/unload-point/unload-point.component.ts
connects #4504
- Fixes known issues from needs verification
- Fix repeated airflow form
=> Ca validation fixes

src/app/compressed-air-assessment/compressed-air-assessment.component.ts, src/app/compressed-air-assessment/compressed-air-assessment.module.ts, src/app/compressed-air-assessment/compressed-air-banner/setup-tabs/setup-tabs.component.ts, src/app/compressed-air-assessment/day-types/day-type.service.spec.ts, src/app/compressed-air-assessment/day-types/day-type.service.ts, src/app/compressed-air-assessment/day-types/day-types.component.html, src/app/compressed-air-assessment/day-types/day-types.component.ts, src/app/compressed-air-assessment/inventory/inventory.service.ts
=> Add validation for daytype inputs, use reactive forms and service

src/app/compressed-air-assessment/results-panel/help-panel/day-types-help/day-types-help.component.html, src/app/log-tool/day-type-analysis/day-type-analysis.component.html, src/app/log-tool/day-type-analysis/day-types/day-types.component.html, src/app/log-tool/system-setup/help-panel/help-panel.component.html
=> Fixed issue 4665 daytype to Day Type

src/app/dashboard/import-export/import-modal/import-modal.component.html, src/app/dashboard/import-export/import-modal/import-modal.component.ts
Added boolean to track treasurehunt files and display correct error message if attempted import into dashboard.
=> Issue #4708

src/app/calculator/compressed-air/receiver-tank/metered-storage-form/metered-storage-form.component.html, src/app/calculator/compressed-air/receiver-tank/receiver-tank.service.ts
=> Issue 4717

src/app/compressed-air-assessment/system-profile/system-profile-setup/compressor-ordering-table/compressor-ordering-table.component.html, src/app/compressed-air-assessment/system-profile/system-profile-setup/operating-profile-table/operating-profile-table.component.html
=> Move system-profile table actions top left

src/app/calculator/calculator-routing/general.routing.ts, src/app/calculator/utilities/altitude-correction/altitude-correction-form/altitude-correction-form.component.html, src/app/calculator/utilities/altitude-correction/altitude-correction-form/altitude-correction-form.component.spec.ts, src/app/calculator/utilities/altitude-correction/altitude-correction-form/altitude-correction-form.component.ts, src/app/calculator/utilities/altitude-correction/altitude-correction-help/altitude-correction-help.component.html, src/app/calculator/utilities/altitude-correction/altitude-correction-help/altitude-correction-help.component.spec.ts, src/app/calculator/utilities/altitude-correction/altitude-correction-help/altitude-correction-help.component.ts, src/app/calculator/utilities/altitude-correction/altitude-correction.component.html, src/app/calculator/utilities/altitude-correction/altitude-correction.component.spec.ts, src/app/calculator/utilities/altitude-correction/altitude-correction.component.ts, src/app/calculator/utilities/altitude-correction/altitude-correction.module.ts, src/app/calculator/utilities/altitude-correction/altitude-correction.service.spec.ts, src/app/calculator/utilities/altitude-correction/altitude-correction.service.ts, src/app/calculator/utilities/utilities-list/utilities-list.component.html, src/app/calculator/utilities/utilities.module.ts, src/app/core/core.routing.ts, src/app/dashboard/sidebar/calculator-list/calculator-list.component.html
=> Issue 4702: Altitude Correction Calculator 

src/app/fsat/fsat-fluid/fsat-fluid.component.html, src/app/shared/gas-density-results/gas-density-results.component.html
=> Issue 4681 Bugs in the psychrometric calc

src/app/phast/phast-report/report-graphs/report-graphs.component.html, src/app/phast/phast-report/report-graphs/report-graphs.component.ts
=> added additional graph

src/app/compressed-air-assessment/compressed-air-assessment.module.ts, src/app/compressed-air-assessment/compressed-air-banner/calculator-tabs/calculator-tabs.component.html, src/app/compressed-air-assessment/compressed-air-calculators/compressed-air-calculators.component.html
=> Issue 4731 and 4740 

src/app/calculator/utilities/weather-bins/weather-bins-form/data-setup-form/data-setup-form.component.html, src/app/calculator/utilities/weather-bins/weather-bins-form/data-setup-form/data-setup-form.component.ts, src/app/calculator/utilities/weather-bins/weather-bins.module.ts, src/app/calculator/utilities/weather-bins/weather-bins.service.ts, src/app/calculator/utilities/weather-bins/weather-db.service.spec.ts, src/app/calculator/utilities/weather-bins/weather-db.service.ts, src/app/indexedDb/indexed-db.service.ts
connects #3734
Will also save binning/case state once data model is modified a bit
=> Issue 4734 (Weather)

src/app/compressed-air-assessment/inventory/performance-points/performance-points-form.service.ts, src/app/compressed-air-assessment/system-information/system-information.component.html
- Listen for input event
- Check for not null form values to mark form dirty
=> CA validation

src/app/compressed-air-assessment/compressed-air-calculation.service.ts, src/app/compressed-air-assessment/inventory/control-data/control-data.component.html, src/app/compressed-air-assessment/inventory/inventory.service.ts, src/app/compressed-air-assessment/results-panel/inventory-performance-profile/inventory-performance-profile.component.ts, src/app/compressed-air-assessment/system-profile/system-profile.service.ts
=> add automatic shutdown timer logic

src/app/compressed-air-assessment/inventory/performance-points/performance-points-form.service.ts, src/app/compressed-air-assessment/results-panel/inventory-table/inventory-table.component.html, src/app/compressed-air-assessment/results-panel/inventory-table/inventory-table.component.ts, src/app/compressed-air-assessment/system-profile/profile-setup-form/profile-setup-form.component.html, src/app/compressed-air-assessment/system-profile/profile-setup-form/profile-setup-form.component.ts
connects #4753 
adds pressure ranges
=> add compressor min and max ranges for display

src/app/dashboard/acknowledgments-page/acknowledgments-page.component.html
=> added my name

src/app/dashboard/acknowledgments-page/acknowledgments-page.component.html
=> Added my name to acknowledgments

src/app/compressed-air-assessment/results-panel/help-panel/system-information-help/system-information-help.component.html, src/app/compressed-air-assessment/system-information/system-information.component.html
=> Added target pressure and variance help text

src/app/ssmt/help-panel/operations-help/operations-help.component.html
=> Updated the help text for Steam Operation Hours

src/app/dashboard/acknowledgments-page/acknowledgments-page.component.html
=> added myself to acknowledgments page

src/app/calculator/process-cooling/chiller-performance/chiller-performance-results/chiller-performance-results.component.ts, src/app/calculator/process-cooling/chiller-performance/chiller-performance.component.css, src/app/calculator/process-cooling/chiller-performance/chiller-performance.component.html, src/app/calculator/process-cooling/chiller-performance/chiller-performance.component.ts, src/app/calculator/process-cooling/chiller-performance/chiller-performance.module.ts, src/app/calculator/process-cooling/chiller-performance/chiller-performance.service.ts, src/app/calculator/utilities/weather-bins/weather-bins-form/data-setup-form/data-setup-form.component.html, src/app/calculator/utilities/weather-bins/weather-bins-form/data-setup-form/data-setup-form.component.ts, src/app/calculator/utilities/weather-bins/weather-bins.component.html, src/app/calculator/utilities/weather-bins/weather-bins.component.ts, src/app/calculator/utilities/weather-bins/weather-bins.module.ts, src/app/shared/models/chillers.ts
connects #4607 
Integrates Weather binning with chiller energy and performance calc
=> Issue 4607 (Cooling/Weather)

src/app/compressed-air-assessment/compressed-air-assessment.module.ts, src/app/compressed-air-assessment/convert-compressed-air.service.spec.ts, src/app/compressed-air-assessment/convert-compressed-air.service.ts, src/app/compressed-air-assessment/inventory/performance-points/calculations/blowoff-calculations.service.ts, src/app/compressed-air-assessment/inventory/performance-points/calculations/full-load-calculations.service.ts, src/app/compressed-air-assessment/inventory/performance-points/calculations/max-full-flow-calculations.service.ts, src/app/compressed-air-assessment/inventory/performance-points/calculations/no-load-calculations.service.ts, src/app/compressed-air-assessment/inventory/performance-points/calculations/unload-point-calculations.service.ts, src/app/shared/models/compressed-air-assessment.ts
connects #4746 
Cleanup perf point decimals
=> Issue 4746

src/app/ssmt/header/header-form/header-form.component.html, src/app/ssmt/help-panel/header-help/header-help.component.html
=> Changed Steam Flash Condensate label and help text

src/app/compressed-air-assessment/inventory/performance-points/max-full-flow/max-full-flow.component.html, src/app/compressed-air-assessment/inventory/performance-points/performance-points-form.service.ts, src/app/compressed-air-assessment/inventory/performance-points/unload-point/unload-point.component.html
Update performance points to v8 doc
=> Issue 4504

src/app/log-tool/visualize/visualize-menu/graph-basics/graph-basics.component.ts, src/app/log-tool/visualize/visualize-menu/visualize-menu.service.ts
=> lines and lines+markers don't display when x-axis is not time series

src/app/psat/compare.service.ts, src/app/psat/explore-opportunities/explore-opportunities-results/explore-opportunities-results.component.ts, src/app/psat/field-data/field-data.component.html, src/app/psat/field-data/field-data.component.ts, src/app/psat/help-panel/help-panel.component.ts, src/app/psat/psat.component.ts, src/app/psat/psat.service.ts
=> Issue 4460: work in progress 

src/app/compressed-air-assessment/results-panel/help-panel/system-information-help/system-information-help.component.html, src/app/compressed-air-assessment/system-information/system-information-form.service.ts, src/app/compressed-air-assessment/system-information/system-information.component.html, src/app/dashboard/assessment.service.ts, src/app/shared/models/compressed-air-assessment.ts
connects #4774 
Removes nominal pressure field
=> Remove nominal pressure field

angular.json, package.json, src/app/core/core.component.ts, src/index.html, src/polyfills.ts
connects #4602 #4614 
- Output client/amo-tools-suite to dist directly
- Add window ref to polyfills.js
- Check if running electron app before running update check
=> Run as webapp fixes (WASM 4602 4614)

src/app/calculator/fans/fan-analysis/convert-fan-analysis.service.ts, src/app/calculator/process-cooling/fan-psychrometric/fan-psychrometric-form/fan-psychrometric-form.component.ts, src/app/calculator/process-cooling/fan-psychrometric/fan-psychrometric.service.ts, src/app/fsat/fsat-fluid/fsat-fluid.component.html, src/app/settings/fsat-settings/fsat-settings.component.ts, src/app/settings/settings.service.ts
=> updated calculations for Bar P, Static P, and Abs P

src/app/calculator/furnaces/atmosphere/atmosphere.component.html, src/app/calculator/furnaces/charge-material/charge-material.component.html, src/app/calculator/furnaces/cooling/cooling.component.html, src/app/calculator/furnaces/fixture/fixture.component.html, src/app/calculator/furnaces/leakage/leakage.component.html, src/app/calculator/furnaces/opening/opening.component.html, src/app/calculator/furnaces/wall/wall.component.html
=> Calcs in Process Heating with multi Bl's and mod's UI fixed

src/app/log-tool/log-tool-data.service.ts
Connects #4609 . The Day Type analysis graph should display normally, and time should not be an option in the other visualizations anymore.
=> time field is now deleted after combining date and time

src/app/calculator/utilities/weather-bins/weather-bins-form/bins-form/bins-form.component.css, src/app/calculator/utilities/weather-bins/weather-bins-form/bins-form/bins-form.component.html, src/app/calculator/utilities/weather-bins/weather-bins-form/bins-form/bins-form.component.ts, src/app/calculator/utilities/weather-bins/weather-bins-form/case-form/case-form.component.ts
=> Issue 4736

src/app/treasure-hunt/find-treasure/find-treasure.component.css, src/app/treasure-hunt/find-treasure/find-treasure.component.html
=> Issue-4574: Treasure Hunt calc cards formatted

src/app/compressed-air-assessment/compressed-air-assessment.service.ts, src/app/compressed-air-assessment/inventory/control-data/control-data.component.html, src/app/compressed-air-assessment/inventory/design-details/design-details.component.html, src/app/compressed-air-assessment/inventory/inventory.component.ts, src/app/compressed-air-assessment/inventory/inventory.service.ts, src/app/compressed-air-assessment/inventory/nameplate-data/nameplate-data.component.html
=> Validation updates

src/app/calculator/process-cooling/cooling-tower-basin/cooling-tower-basin-form/cooling-tower-basin-form.component.html, src/app/calculator/process-cooling/cooling-tower-basin/cooling-tower-basin-form/cooling-tower-basin-form.component.ts, src/app/calculator/process-cooling/cooling-tower-basin/cooling-tower-basin-results/cooling-tower-basin-results.component.html, src/app/calculator/process-cooling/cooling-tower-basin/cooling-tower-basin-results/cooling-tower-basin-results.component.ts, src/app/calculator/process-cooling/cooling-tower-basin/cooling-tower-basin.component.css, src/app/calculator/process-cooling/cooling-tower-basin/cooling-tower-basin.component.html, src/app/calculator/process-cooling/cooling-tower-basin/cooling-tower-basin.component.ts, src/app/calculator/process-cooling/cooling-tower-basin/cooling-tower-basin.module.ts, src/app/calculator/process-cooling/cooling-tower-basin/cooling-tower-basin.service.ts, src/app/calculator/utilities/weather-bins/weather-bins-bar-chart/weather-bins-bar-chart.component.html, src/app/calculator/utilities/weather-bins/weather-bins-form/bins-form/bins-form.component.html, src/app/calculator/utilities/weather-bins/weather-bins-form/bins-form/bins-form.component.ts, src/app/calculator/utilities/weather-bins/weather-bins-form/case-form/case-form.component.html, src/app/calculator/utilities/weather-bins/weather-bins-form/parameter-unit/parameter-unit.component.html, src/app/calculator/utilities/weather-bins/weather-bins-form/weather-bins-form.component.ts, src/app/calculator/utilities/weather-bins/weather-bins.component.ts, src/app/calculator/utilities/weather-bins/weather-bins.service.ts, src/app/shared/cooling-weather-chart/cooling-weather-chart.component.html, src/app/shared/cooling-weather-chart/cooling-weather-chart.component.spec.ts, src/app/shared/cooling-weather-chart/cooling-weather-chart.component.ts, src/app/shared/cooling-weather-chart/cooling-weather-chart.module.ts, src/app/shared/models/chillers.ts
#4770 #4783
Adding integration for weather binning calc and results
=> Issue 4770

src/app/compressed-air-assessment/compressed-air-data-management.service.ts, src/app/compressed-air-assessment/inventory/inventory.service.ts, src/app/compressed-air-assessment/inventory/performance-points/performance-points-form.service.ts
connects #4801 
Handle -9999 values in generic db compressors
=> Issue 4801

src/app/calculator/compressed-air/system-capacity/system-capacity-form/system-capacity-form.component.html, src/app/calculator/compressed-air/system-capacity/system-capacity.component.ts, src/app/calculator/standalone.service.ts, src/app/compressed-air-assessment/system-information/system-capacity-modal/system-capacity-modal.component.ts
connects #4809 
Convert system-capacity results to gal
=> Issue 4809

src/app/calculator/utilities/weather-bins/weather-bins-form/bins-form/bins-form.component.ts
=> cleared existing bins before creating new bin

src/app/compressed-air-assessment/compressed-air-calculation.service.ts, src/app/compressed-air-assessment/inventory/design-details/design-details.component.ts, src/app/compressed-air-assessment/results-panel/inventory-performance-profile/inventory-performance-profile.component.ts
connects #4503 
adds fields for suite calculations accuracy
updates profile graph to increment by 1 until 95-100 then increment by .5
updates logic for display no load power full modulated load factor
=> updated calculations, updateddisplay and passing noLoadPowerFM

src/app/compressed-air-assessment/inventory/performance-points/blowoff/blowoff.component.html, src/app/compressed-air-assessment/inventory/performance-points/full-load/full-load.component.html, src/app/compressed-air-assessment/inventory/performance-points/max-full-flow/max-full-flow.component.html, src/app/compressed-air-assessment/inventory/performance-points/no-load/no-load.component.html, src/app/compressed-air-assessment/inventory/performance-points/unload-point/unload-point.component.html
=> Changed font-awesome calculator to font-awesome refresh

src/app/compressed-air-assessment/compressed-air-assessment.component.html, src/app/compressed-air-assessment/compressed-air-assessment.component.ts, src/app/compressed-air-assessment/compressed-air-assessment.module.ts, src/app/compressed-air-assessment/convert-compressed-air.service.ts, src/app/compressed-air-assessment/inventory/control-data/control-data.component.html, src/app/compressed-air-assessment/inventory/control-data/control-data.component.ts, src/app/compressed-air-assessment/inventory/design-details/design-details.component.html, src/app/compressed-air-assessment/inventory/design-details/design-details.component.ts, src/app/compressed-air-assessment/inventory/inlet-conditions/inlet-conditions.component.html, src/app/compressed-air-assessment/inventory/inlet-conditions/inlet-conditions.component.ts, src/app/compressed-air-assessment/inventory/nameplate-data/nameplate-data.component.html, src/app/compressed-air-assessment/inventory/nameplate-data/nameplate-data.component.ts, src/app/compressed-air-assessment/inventory/performance-points/blowoff/blowoff.component.html, src/app/compressed-air-assessment/inventory/performance-points/blowoff/blowoff.component.ts, src/app/compressed-air-assessment/inventory/performance-points/full-load/full-load.component.html, src/app/compressed-air-assessment/inventory/performance-points/full-load/full-load.component.ts, src/app/compressed-air-assessment/inventory/performance-points/max-full-flow/max-full-flow.component.html, src/app/compressed-air-assessment/inventory/performance-points/max-full-flow/max-full-flow.component.ts, src/app/compressed-air-assessment/inventory/performance-points/no-load/no-load.component.html, src/app/compressed-air-assessment/inventory/performance-points/no-load/no-load.component.ts, src/app/compressed-air-assessment/inventory/performance-points/unload-point/unload-point.component.html, src/app/compressed-air-assessment/inventory/performance-points/unload-point/unload-point.component.ts, src/app/compressed-air-assessment/system-basics/system-basics.component.ts, src/app/compressed-air-assessment/system-information/system-information.component.html, src/app/compressed-air-assessment/system-information/system-information.component.ts, src/app/compressed-air-assessment/system-profile/profile-setup-form/profile-setup-form.component.html, src/app/compressed-air-assessment/system-profile/profile-setup-form/profile-setup-form.component.ts, src/app/shared/models/compressed-air-assessment.ts
connects #4699 
Add unit conversions for CA sys setup
=> Issue 4699

src/app/compressed-air-assessment/compressed-air-assessment-results.service.ts, src/app/compressed-air-assessment/compressed-air-assessment.component.html, src/app/compressed-air-assessment/compressed-air-assessment.module.ts, src/app/compressed-air-assessment/compressed-air-banner/setup-tabs/setup-tabs.component.html, src/app/compressed-air-assessment/system-profile/system-profile-annual-summary/system-profile-annual-summary.component.css, src/app/compressed-air-assessment/system-profile/system-profile-annual-summary/system-profile-annual-summary.component.html, src/app/compressed-air-assessment/system-profile/system-profile-annual-summary/system-profile-annual-summary.component.spec.ts, src/app/compressed-air-assessment/system-profile/system-profile-annual-summary/system-profile-annual-summary.component.ts
=> add baseline annual results to profile

src/app/treasure-hunt/treasure-chest/import-opportunities.service.ts, src/app/treasure-hunt/treasure-hunt-report/opportunity-summary.service.ts
=> Add updates for legacy TH opps

src/app/phast/losses/operations/operating-costs-modal/operating-costs-modal.component.css, src/app/phast/losses/operations/operating-costs-modal/operating-costs-modal.component.ts
=> fixed math and form layout

src/app/calculator/utilities/weather-bins/weather-bins-bar-chart/weather-bins-bar-chart.component.html, src/app/calculator/utilities/weather-bins/weather-bins-bar-chart/weather-bins-bar-chart.component.ts, src/app/calculator/utilities/weather-bins/weather-bins-table/weather-bins-table.component.css, src/app/calculator/utilities/weather-bins/weather-bins-table/weather-bins-table.component.html, src/app/calculator/utilities/weather-bins/weather-bins-table/weather-bins-table.component.spec.ts, src/app/calculator/utilities/weather-bins/weather-bins-table/weather-bins-table.component.ts, src/app/calculator/utilities/weather-bins/weather-bins.module.ts
=> Weather Bins result table

src/app/calculator/utilities/weather-bins/weather-bins-table/weather-bins-table.component.html
=> switched upper and lower bound columns in table

src/app/calculator/compressed-air/receiver-tank/metered-storage-form/metered-storage-form.component.html, src/app/calculator/compressed-air/receiver-tank/receiver-tank.service.ts
=> Issue 4717 merged into develop

src/app/compressed-air-assessment/compressed-air-assessment.component.ts, src/app/compressed-air-assessment/inventory/control-data/control-data.component.html, src/app/compressed-air-assessment/inventory/control-data/control-data.component.ts, src/app/compressed-air-assessment/inventory/design-details/design-details.component.html, src/app/compressed-air-assessment/inventory/inventory.service.ts, src/app/compressed-air-assessment/system-information/system-information-form.service.ts, src/app/compressed-air-assessment/system-information/system-information.component.html, src/app/compressed-air-assessment/system-information/system-information.component.ts
connects #4824 
- Fixing false validation errs in inventory forms
- Fixing issues when compressor type is changed and controlType options dont match.
- Fixing next button
=> Issue 4824

src/app/calculator/utilities/weather-bins/weather-bins-bar-chart/weather-bins-bar-chart.component.ts
=> binned Hours on bar chart

src/app/compressed-air-assessment/compressed-air-assessment-results.service.ts, src/app/compressed-air-assessment/compressed-air-assessment.module.ts, src/app/compressed-air-assessment/compressed-air-calculation.service.ts, src/app/compressed-air-assessment/explore-opportunities/explore-opportunities-results/explore-opportunities-results.component.ts, src/app/compressed-air-assessment/explore-opportunities/explore-opportunities.service.ts, src/app/compressed-air-assessment/explore-opportunities/reduce-run-time/reduce-run-time.component.css, src/app/compressed-air-assessment/explore-opportunities/reduce-run-time/reduce-run-time.component.html, src/app/compressed-air-assessment/explore-opportunities/reduce-run-time/reduce-run-time.component.ts, src/app/compressed-air-assessment/explore-opportunities/use-automatic-sequencer/adjust-sequencer-profile/adjust-sequencer-profile.component.css, src/app/compressed-air-assessment/explore-opportunities/use-automatic-sequencer/adjust-sequencer-profile/adjust-sequencer-profile.component.html, src/app/compressed-air-assessment/explore-opportunities/use-automatic-sequencer/adjust-sequencer-profile/adjust-sequencer-profile.component.spec.ts, src/app/compressed-air-assessment/explore-opportunities/use-automatic-sequencer/adjust-sequencer-profile/adjust-sequencer-profile.component.ts, src/app/compressed-air-assessment/explore-opportunities/use-automatic-sequencer/use-automatic-sequencer.component.css, src/app/compressed-air-assessment/explore-opportunities/use-automatic-sequencer/use-automatic-sequencer.component.html, src/app/compressed-air-assessment/explore-opportunities/use-automatic-sequencer/use-automatic-sequencer.component.ts, src/app/compressed-air-assessment/inventory/control-data/control-data.component.ts, src/app/compressed-air-assessment/inventory/inventory.service.ts, src/app/compressed-air-assessment/inventory/performance-points/calculations/max-full-flow-calculations.service.ts, src/app/compressed-air-assessment/inventory/performance-points/calculations/no-load-calculations.service.ts, src/app/compressed-air-assessment/inventory/performance-points/calculations/unload-point-calculations.service.ts, src/app/compressed-air-assessment/inventory/performance-points/performance-points-form.service.ts, src/app/shared/models/compressed-air-assessment.ts
connects #4647 
add sequencer EEM
fixes to performance point calculations
add automatic shutdown timer and power results to reduce runtime
fixes to modification algorithm calculations
add incremental summarys to results
=> Issue 4647

src/app/log-tool/system-setup/setup-data/setup-data.component.html, src/app/log-tool/system-setup/setup-data/setup-data.component.ts
=> Data Explorer loading screen

src/app/compressed-air-assessment/compressed-air-assessment-results.service.ts, src/app/compressed-air-assessment/compressed-air-calculation.service.ts, src/app/compressed-air-assessment/explore-opportunities/explore-opportunities.component.html, src/app/compressed-air-assessment/explore-opportunities/explore-opportunities.component.ts, src/app/compressed-air-assessment/explore-opportunities/use-automatic-sequencer/use-automatic-sequencer.component.html, src/app/compressed-air-assessment/explore-opportunities/use-automatic-sequencer/use-automatic-sequencer.component.ts, src/app/compressed-air-assessment/system-information/system-information.component.ts, src/app/compressed-air-assessment/system-profile/system-profile-graphs/system-profile-graphs.component.ts, src/app/compressed-air-assessment/system-profile/system-profile-summary/system-profile-summary.component.ts
connects #4860 
apply sequencer logic to baseline and updates to EEM's that cannot be applied when baseline sequencer is on
=> Issue 4860

src/app/core/core.component.html, src/app/core/core.component.ts, src/app/shared/models/settings.ts
connects #4863 
Add beta message for web app
=> Issue 4863

src/app/compressed-air-assessment/compressed-air-assessment-results.service.ts, src/app/compressed-air-assessment/day-types/day-types.component.ts, src/app/compressed-air-assessment/explore-opportunities/explore-opportunities-results/explore-opportunities-results.component.html, src/app/compressed-air-assessment/explore-opportunities/explore-opportunities-results/explore-opportunities-results.component.ts, src/app/compressed-air-assessment/explore-opportunities/explore-opportunities.service.ts, src/app/compressed-air-assessment/explore-opportunities/improve-end-use-efficiency/improve-end-use-efficiency.component.css, src/app/compressed-air-assessment/explore-opportunities/improve-end-use-efficiency/improve-end-use-efficiency.component.html, src/app/compressed-air-assessment/explore-opportunities/improve-end-use-efficiency/improve-end-use-efficiency.component.ts, src/app/compressed-air-assessment/inventory/inventory.service.ts, src/app/shared/models/compressed-air-assessment.ts
connects #4840 
updated efficiency improvement opportunity for multiple additions
updates results calculations
=> Issue 4840

src/app/calculator/process-cooling/cooling-tower-basin/cooling-tower-basin-form/cooling-tower-basin-form.component.html, src/app/calculator/process-cooling/cooling-tower-basin/cooling-tower-basin-form/cooling-tower-basin-form.component.ts, src/app/calculator/process-cooling/cooling-tower-basin/cooling-tower-basin-results/cooling-tower-basin-results.component.html, src/app/calculator/process-cooling/cooling-tower-basin/cooling-tower-basin-results/cooling-tower-basin-results.component.ts, src/app/calculator/process-cooling/cooling-tower-basin/cooling-tower-basin.component.css, src/app/calculator/process-cooling/cooling-tower-basin/cooling-tower-basin.component.html, src/app/calculator/process-cooling/cooling-tower-basin/cooling-tower-basin.component.ts, src/app/calculator/process-cooling/cooling-tower-basin/cooling-tower-basin.service.ts
=> Toggle weather data

src/app/log-tool/export-modal/export-modal.component.css, src/app/log-tool/export-modal/export-modal.component.html, src/app/log-tool/export-modal/export-modal.component.spec.ts, src/app/log-tool/export-modal/export-modal.component.ts, src/app/log-tool/log-tool-banner/log-tool-banner.component.css, src/app/log-tool/log-tool-banner/log-tool-banner.component.html, src/app/log-tool/log-tool-banner/log-tool-banner.component.ts, src/app/log-tool/log-tool-db.service.ts, src/app/log-tool/log-tool-models.ts, src/app/log-tool/log-tool.component.html, src/app/log-tool/log-tool.component.ts, src/app/log-tool/log-tool.module.ts, src/app/log-tool/log-tool.service.ts
=> Issue 4834: Export Data Explorer files

src/app/app.component.ts, src/index.html
connects #4417 
Include analytics in MEASUR
=> Issue 4417

src/app/compressed-air-assessment/compressed-air-assessment.module.ts, src/app/compressed-air-assessment/system-profile/system-profile-graphs/system-profile-graphs.component.html, src/app/compressed-air-assessment/system-profile/system-profile-graphs/system-profile-graphs.component.ts, src/app/compressed-air-assessment/system-profile/system-profile-graphs/system-profile-graphs.service.spec.ts, src/app/compressed-air-assessment/system-profile/system-profile-graphs/system-profile-graphs.service.ts
=> Issue 4788

src/app/compressed-air-assessment/compressed-air-assessment-results.service.ts, src/app/compressed-air-assessment/inventory/inventory.service.ts, src/app/compressed-air-assessment/inventory/inventoryOptions.ts, src/app/compressed-air-assessment/inventory/performance-points/calculations/no-load-calculations.service.ts, src/app/compressed-air-assessment/inventory/performance-points/calculations/performance-point-calculations.service.ts, src/app/compressed-air-assessment/inventory/performance-points/no-load/no-load.component.ts, src/app/compressed-air-assessment/inventory/performance-points/performance-points-form.service.ts, src/app/compressed-air-assessment/results-panel/help-panel/inventory-help/performance-points-help/no-load-help/no-load-help.component.ts
=> fix start/stop and multi stage unloading having wrong value

src/app/calculator/utilities/weather-bins/weather-bins-form/data-setup-form/data-setup-form.component.html, src/app/calculator/utilities/weather-bins/weather-bins-form/data-setup-form/data-setup-form.component.ts, src/app/calculator/utilities/weather-bins/weather-db.service.ts
=> Issue 4818

src/app/compressed-air-assessment/system-profile/system-profile-graphs/system-profile-graphs.component.html, src/app/compressed-air-assessment/system-profile/system-profile-graphs/system-profile-graphs.component.ts
connects #4788 
Change graph name, change to line graph, fix maxlines
=> Issue 4788: The Final Showdown

src/app/compressed-air-assessment/inventory/inventory.service.ts, src/app/compressed-air-assessment/results-panel/inventory-performance-profile/inventory-performance-profile.component.ts, src/app/shared/models/plotting.ts
=> Issue 4827

src/app/log-tool/export-modal/export-modal.component.html, src/app/log-tool/export-modal/export-modal.component.ts, src/app/log-tool/system-setup/setup-data/setup-data.component.html, src/app/log-tool/system-setup/setup-data/setup-data.component.ts
=> Issue 4868: Import .JSON files in Data Explorer 

src/app/calculator/fans/fan-analysis/fan-analysis-form/plane-data-form/pressure-readings-form/pressure-readings-form.component.ts
=> issue-4858: Static Pressure Readings Missing Columns

src/app/compressed-air-assessment/compressed-air-calculation.service.ts
=> add unload point pp input to binding

src/app/fsat/calculate-pressures/calculate-inlet-pressure/calculate-inlet-pressure.component.ts, src/app/fsat/calculate-pressures/calculate-outlet-pressure/calculate-outlet-pressure.component.ts, src/app/fsat/fan-field-data/fan-field-data.component.html
=> Issue 4859

src/app/log-tool/system-setup/system-setup.component.html
=> Issue-4687

src/app/compressed-air-assessment/compressed-air-assessment.module.ts, src/app/compressed-air-assessment/explore-opportunities/adjust-cascading-set-points/adjust-cascading-set-points.component.html, src/app/compressed-air-assessment/explore-opportunities/adjust-cascading-set-points/adjust-cascading-set-points.component.ts, src/app/compressed-air-assessment/results-panel/help-panel/assessment-help/add-receiver-volume-help/add-receiver-volume-help.component.html, src/app/compressed-air-assessment/results-panel/help-panel/assessment-help/adjust-cascading-set-points-help/adjust-cascading-set-points-help.component.html, src/app/compressed-air-assessment/results-panel/help-panel/assessment-help/adjust-cascading-set-points-help/adjust-cascading-set-points-help.component.spec.ts, src/app/compressed-air-assessment/results-panel/help-panel/assessment-help/adjust-cascading-set-points-help/adjust-cascading-set-points-help.component.ts, src/app/compressed-air-assessment/results-panel/help-panel/assessment-help/assessment-help.component.html, src/app/compressed-air-assessment/results-panel/help-panel/assessment-help/improve-end-use-efficiency-help/improve-end-use-efficiency-help.component.html, src/app/compressed-air-assessment/results-panel/help-panel/assessment-help/reduce-air-leaks-help/reduce-air-leaks-help.component.html, src/app/compressed-air-assessment/results-panel/help-panel/assessment-help/reduce-run-time-help/reduce-run-time-help.component.html, src/app/compressed-air-assessment/results-panel/help-panel/assessment-help/reduce-system-air-pressure-help/reduce-system-air-pressure-help.component.html, src/app/compressed-air-assessment/results-panel/help-panel/assessment-help/use-automatic-sequencer-help/use-automatic-sequencer-help.component.html
=> Issue 4633: more help text added

src/app/calculator/furnaces/efficiency-improvement/efficiency-improvement-form/efficiency-improvement-form.component.html, src/app/calculator/furnaces/efficiency-improvement/efficiency-improvement.service.ts
=> Issue-4877: Efficiency Improvement validation bug

src/app/log-tool/log-tool-db.service.ts, src/app/log-tool/system-setup/setup-data/setup-data.component.ts
=> Issue-4888

src/app/calculator/steam/boiler-blowdown-rate/blowdown-rate-form/blowdown-rate-form.component.html
=> issue-4876

src/app/log-tool/visualize/visualize-help/visualize-help.component.html
=> Issue 4846

src/app/waste-water/explore-opportunities/explore-opportunities-form/explore-opportunities-form.component.ts
=> Issue 4861: New modification needs default name

src/app/phast/losses/charge-material/charge-material.component.html, src/app/phast/losses/charge-material/charge-material.component.ts, src/app/phast/losses/flue-gas-losses/flue-gas-losses.component.ts
=> Issue 4853: Charge Material and Flue gas 'Select Type' Dropdowns bugs

src/app/compressed-air-assessment/inventory/performance-points/calculations/full-load-calculations.service.ts
connects #4502 
was passing control type and needed to pass compressor type.
=> pass correct value for full load power performance point calc

src/app/calculator/utilities/altitude-correction/altitude-correction-form/altitude-correction-form.component.html, src/app/calculator/utilities/altitude-correction/altitude-correction.service.ts, src/app/compressed-air-assessment/inventory/design-details/design-details.component.html, src/app/dashboard/assessment.service.ts
=> Issue 4790 - CA little things

src/app/psat/compare.service.ts, src/app/psat/explore-opportunities/explore-opportunities-results/explore-opportunities-results.component.ts, src/app/psat/help-panel/help-panel.component.ts, src/app/psat/psat-report/output-summary/output-summary.component.ts, src/app/report-rollup/report-rollup-units/report-rollup-units.component.ts, src/app/settings/application-settings/application-settings.component.ts
connects #3554 
Fixes a couple PSAT bugs.
Turns off currency option
Moving to inbox for further bug fixing when higher priority
=> Issue 3554

src/app/calculator/utilities/altitude-correction/altitude-correction-form/altitude-correction-form.component.html, src/app/calculator/utilities/altitude-correction/altitude-correction.service.ts, src/app/compressed-air-assessment/compressed-air-assessment-results.service.ts, src/app/compressed-air-assessment/compressed-air-calculation.service.ts, src/app/compressed-air-assessment/compressed-air-report/input-summary/compressor-item-summary/compressor-item-summary.component.html, src/app/compressed-air-assessment/compressed-air-report/input-summary/system-info-summary/system-info-summary.component.html, src/app/compressed-air-assessment/convert-compressed-air.service.ts, src/app/compressed-air-assessment/inventory/inlet-conditions/inlet-conditions.component.html, src/app/compressed-air-assessment/inventory/inventory.service.ts, src/app/compressed-air-assessment/inventory/performance-points/calculations/full-load-calculations.service.ts, src/app/compressed-air-assessment/inventory/performance-points/calculations/max-full-flow-calculations.service.ts, src/app/compressed-air-assessment/inventory/performance-points/calculations/shared-point-calculations.service.ts, src/app/compressed-air-assessment/results-panel/inventory-performance-profile/inventory-performance-profile.component.ts, src/app/compressed-air-assessment/system-information/system-information-form.service.ts, src/app/compressed-air-assessment/system-information/system-information.component.html, src/app/compressed-air-assessment/system-information/system-information.component.ts, src/app/dashboard/assessment.service.ts, src/app/shared/models/compressed-air-assessment.ts
connects #4654 
moves atmospheric pressure to system information
adds calculation (altitude correction calc) for converting system elevation to atmospheric pressure or can be set directly
updates calculations for results to use new field
=> Issue 4654

src/app/compressed-air-assessment/compressed-air-assessment-results.service.ts, src/app/compressed-air-assessment/compressed-air-assessment.component.ts, src/app/compressed-air-assessment/compressed-air-calculation.service.ts
=> fixes to automatic shutdown timer logic

src/app/compressed-air-assessment/profile-summary-table/profile-summary-table.component.html, src/app/compressed-air-assessment/system-profile/system-profile-graphs/system-profile-graphs.component.ts, src/app/compressed-air-assessment/system-profile/system-profile-setup/compressor-ordering-table/compressor-ordering-table.component.html, src/app/compressed-air-assessment/system-profile/system-profile-setup/operating-profile-table/operating-profile-table.component.html, src/app/log-tool/day-type-analysis/day-type-graph/day-type-graph.component.ts, src/app/log-tool/day-type-analysis/day-type-graph/day-type-graph.service.ts, src/app/log-tool/day-type-analysis/day-type-table/day-type-summary-table/day-type-summary-table.component.html, src/app/log-tool/day-type-analysis/day-type-table/individual-day-summary-table/individual-day-summary-table.component.html, src/app/log-tool/day-type-analysis/day-type-table/selected-data-table/selected-data-table.component.html
connects #4902
sets display values for hour intervals in data explorer and compressed air assessment to 1-24
=> Issue 4902

src/app/calculator/compressed-air/air-leak/air-leak-results-table/air-leak-results-table.component.ts, src/app/calculator/compressed-air/air-leak/air-leak.service.ts
=> bug that makes table disappear

src/app/phast/losses/charge-material/liquid-charge-material-form/liquid-charge-material-form.component.ts, src/app/phast/losses/losses.service.ts, src/app/phast/phast-results.service.ts, src/app/phast/phast.service.ts
=> Issue 4856: updated phast service sumChargeMaterials method

src/app/compressed-air-assessment/compressed-air-assessment-results.service.ts, src/app/compressed-air-assessment/explore-opportunities/explore-opportunities-results/explore-opportunities-results.component.html, src/app/compressed-air-assessment/explore-opportunities/explore-opportunities.service.ts, src/app/compressed-air-assessment/explore-opportunities/improve-end-use-efficiency/improve-end-use-efficiency.component.html, src/app/compressed-air-assessment/explore-opportunities/improve-end-use-efficiency/improve-end-use-efficiency.component.ts, src/app/compressed-air-assessment/explore-opportunities/reduce-run-time/reduce-run-time.component.html, src/app/compressed-air-assessment/explore-opportunities/reduce-run-time/reduce-run-time.component.ts, src/app/compressed-air-assessment/explore-opportunities/use-automatic-sequencer/adjust-sequencer-profile/adjust-sequencer-profile.component.html, src/app/compressed-air-assessment/explore-opportunities/use-automatic-sequencer/use-automatic-sequencer.component.ts, src/app/compressed-air-assessment/inventory/inventory.component.ts, src/app/compressed-air-assessment/inventory/inventory.service.ts, src/app/compressed-air-assessment/profile-summary-table/profile-summary-table.component.html, src/app/compressed-air-assessment/results-panel/inventory-table/inventory-table.component.ts, src/app/compressed-air-assessment/system-profile/profile-setup-form/profile-setup-form.component.ts, src/app/compressed-air-assessment/system-profile/system-profile-setup/compressor-ordering-table/compressor-ordering-table.component.css, src/app/compressed-air-assessment/system-profile/system-profile-setup/compressor-ordering-table/compressor-ordering-table.component.html, src/app/compressed-air-assessment/system-profile/system-profile-setup/operating-profile-table/operating-profile-table.component.css, src/app/compressed-air-assessment/system-profile/system-profile-setup/operating-profile-table/operating-profile-table.component.html, src/app/compressed-air-assessment/system-profile/system-profile-setup/operating-profile-table/operating-profile-table.component.ts, src/app/shared/models/compressed-air-assessment.ts
connects #4903 
updates logic throughout assessment to hand 24 hour profiling data option
disabled option if modification exists
updates math to handle selected option
=> Issue 4903

src/app/compressed-air-assessment/inventory/design-details/design-details.component.ts, src/app/compressed-air-assessment/inventory/inventory.service.ts
connects #4857 
display modulating pressure range for variable displacement
calculated value always and disabled input
=> disable and calculate modulating pressure range

src/app/compressed-air-assessment/compressed-air-banner/compressed-air-banner.component.html, src/app/compressed-air-assessment/compressed-air-banner/compressed-air-banner.component.ts, src/app/compressed-air-assessment/compressed-air-report/payback-period/payback-period.component.html, src/app/compressed-air-assessment/compressed-air-report/report-graphs/report-graphs.component.html, src/app/compressed-air-assessment/compressed-air-report/report-graphs/report-graphs.component.ts, src/app/compressed-air-assessment/explore-opportunities/explore-opportunities.component.ts
connects #4946 
various logic to handle assessments without modifications
=> handle assessments without modifications

src/app/phast/losses/flue-gas-losses/flue-gas-losses-form-mass/flue-gas-losses-form-mass.component.ts
=> removed if statement and tested

src/app/dashboard/sidebar/calculator-list/calculator-list.component.html
=> fixed comment

src/app/calculator/steam/condensing-economizer/condensing-economizer-form/condensing-economizer-form.component.html, src/app/calculator/steam/condensing-economizer/condensing-economizer-results/condensing-economizer-results.component.html, src/app/calculator/steam/condensing-economizer/condensing-economizer.service.ts, src/app/dashboard/sidebar/calculator-list/calculator-list.component.html, src/app/shared/models/steam/condensingEconomizer.ts
connects #4972 
Additional changes for condensing economizer
=> Issue 4972

src/app/app.component.css, src/app/compressed-air-assessment/compressed-air-report/compressed-air-report.component.html, src/app/compressed-air-assessment/compressed-air-report/executive-summary/executive-summary.component.html, src/app/compressed-air-assessment/compressed-air-report/executive-summary/executive-summary.component.ts, src/app/report-rollup/assessment-reports/assessment-reports.component.html, src/app/report-rollup/assessment-reports/assessment-reports.component.ts, src/app/report-rollup/compressed-air-report-rollup.service.spec.ts, src/app/report-rollup/compressed-air-report-rollup.service.ts, src/app/report-rollup/compressed-air-rollup/compressed-air-rollup.component.css, src/app/report-rollup/compressed-air-rollup/compressed-air-rollup.component.html, src/app/report-rollup/compressed-air-rollup/compressed-air-rollup.component.spec.ts, src/app/report-rollup/compressed-air-rollup/compressed-air-rollup.component.ts, src/app/report-rollup/report-rollup-modals/report-rollup-modals.component.css, src/app/report-rollup/report-rollup-modals/report-rollup-modals.component.html, src/app/report-rollup/report-rollup-modals/report-rollup-modals.component.ts, src/app/report-rollup/report-rollup-models.ts, src/app/report-rollup/report-rollup.module.ts, src/app/report-rollup/report-rollup.service.ts, src/app/report-rollup/report-summary/compressed-air-summary/compressed-air-summary.component.css, src/app/report-rollup/report-summary/compressed-air-summary/compressed-air-summary.component.html, src/app/report-rollup/report-summary/compressed-air-summary/compressed-air-summary.component.spec.ts, src/app/report-rollup/report-summary/compressed-air-summary/compressed-air-summary.component.ts, src/app/report-rollup/report-summary/report-summary.component.css, src/app/report-rollup/report-summary/report-summary.component.html, src/app/report-rollup/report-summary/report-summary.component.ts, src/app/report-rollup/sidebar/sidebar.component.html, src/app/report-rollup/sidebar/sidebar.component.ts, src/app/report-rollup/ssmt-rollup/ssmt-rollup.component.html, src/assets/styles/two-panel.css
connects #4969 
adds compressed air to report rollup
=> Issue 4969

src/app/compressed-air-assessment/compressed-air-assessment-results.service.ts, src/app/compressed-air-assessment/compressed-air-calculation.service.ts, src/app/compressed-air-assessment/system-profile/profile-setup-form/profile-setup-form.component.html, src/app/compressed-air-assessment/system-profile/system-profile-setup/operating-profile-table/operating-profile-table.component.css, src/app/compressed-air-assessment/system-profile/system-profile-setup/operating-profile-table/operating-profile-table.component.html, src/app/compressed-air-assessment/system-profile/system-profile-setup/operating-profile-table/operating-profile-table.component.ts, src/app/log-tool/day-type-analysis/day-type-menu/select-assessment-modal/select-assessment-modal.component.ts, src/app/shared/models/compressed-air-assessment.ts
connects #4649 
adds profile input data options for % Power and Volts, Amps, Power Factor.
Updates logic so that it can still use data explorer.
=> Issue 4649

src/app/phast/losses/flue-gas-losses/flue-gas-losses-form-mass/flue-gas-losses-form-mass.component.ts, src/app/shared/helper-services/update-data.service.ts
connects #5035 
- Add default 0 for moisture
- Change comparison to 0 for carbon. I double checked for other comparions in FG and opening, but for future ref. this is a side effect of #4855
=> Issue 5035

src/app/compressed-air-assessment/compressed-air-assessment.component.html, src/app/compressed-air-assessment/compressed-air-assessment.component.ts
=> update next buttons for release

src/app/compressed-air-assessment/compressed-air-assessment.component.ts, src/app/compressed-air-assessment/compressed-air-report/system-profiles/system-profiles.component.html, src/app/compressed-air-assessment/explore-opportunities/explore-opportunities.component.html, src/app/compressed-air-assessment/explore-opportunities/explore-opportunities.component.ts, src/app/compressed-air-assessment/explore-opportunities/improve-end-use-efficiency/improve-end-use-efficiency-item/improve-end-use-efficiency-item.component.html, src/app/compressed-air-assessment/explore-opportunities/improve-end-use-efficiency/improve-end-use-efficiency.component.css, src/app/compressed-air-assessment/explore-opportunities/improve-end-use-efficiency/improve-end-use-efficiency.component.html, src/app/compressed-air-assessment/explore-opportunities/reduce-run-time/reduce-run-time.component.html, src/app/compressed-air-assessment/explore-opportunities/use-automatic-sequencer/use-automatic-sequencer.component.html, src/app/compressed-air-assessment/system-information/system-information-form.service.ts
connects #5057 
hides day type dropdowns when only one day type
=> Issue 5057

src/app/compressed-air-assessment/compressed-air-assessment-results.service.ts, src/app/compressed-air-assessment/compressed-air-assessment.component.ts, src/app/compressed-air-assessment/compressed-air-data-management.service.ts, src/app/compressed-air-assessment/explore-opportunities/adjust-cascading-set-points/adjust-cascading-set-points.component.ts, src/app/compressed-air-assessment/explore-opportunities/explore-opportunities-validation.service.ts, src/app/compressed-air-assessment/explore-opportunities/use-automatic-sequencer/use-automatic-sequencer.component.ts, src/app/compressed-air-assessment/inventory/design-details/design-details.component.ts, src/app/compressed-air-assessment/inventory/inlet-conditions/inlet-conditions.component.ts, src/app/compressed-air-assessment/inventory/nameplate-data/nameplate-data.component.ts, src/app/compressed-air-assessment/inventory/performance-points/blowoff/blowoff.component.ts, src/app/compressed-air-assessment/inventory/performance-points/calculations/blowoff-calculations.service.ts, src/app/compressed-air-assessment/inventory/performance-points/calculations/full-load-calculations.service.ts, src/app/compressed-air-assessment/inventory/performance-points/calculations/max-full-flow-calculations.service.ts, src/app/compressed-air-assessment/inventory/performance-points/calculations/no-load-calculations.service.ts, src/app/compressed-air-assessment/inventory/performance-points/calculations/performance-point-calculations.service.ts, src/app/compressed-air-assessment/inventory/performance-points/calculations/shared-point-calculations.service.ts, src/app/compressed-air-assessment/inventory/performance-points/calculations/unload-point-calculations.service.ts, src/app/compressed-air-assessment/inventory/performance-points/full-load/full-load.component.ts, src/app/compressed-air-assessment/inventory/performance-points/max-full-flow/max-full-flow.component.ts, src/app/compressed-air-assessment/inventory/performance-points/no-load/no-load.component.ts, src/app/compressed-air-assessment/inventory/performance-points/unload-point/unload-point.component.ts
connects #5048 
fixes payback period calculation
removes data dependency in performance point calculation and passes value
=> Issue 5048

src/app/calculator/steam/condensing-economizer/condensing-economizer-results/condensing-economizer-results.component.html, src/app/calculator/steam/condensing-economizer/condensing-economizer.service.ts
=> add total heat recovery result

src/app/calculator/furnaces/heat-cascading/heat-cascading.service.ts
=> fix energy calculation in heat cascading calc

src/app/calculator/steam/feedwater-economizer/feedwater-economizer-form.service.ts, src/app/calculator/steam/feedwater-economizer/feedwater-economizer-form/feedwater-economizer-form.component.html, src/app/calculator/steam/feedwater-economizer/feedwater-economizer-form/feedwater-economizer-form.component.ts, src/app/calculator/steam/feedwater-economizer/feedwater-economizer.service.ts, src/app/calculator/steam/steam-list/steam-list.component.html
=> fix steamCondition enum and validation on steam temperature

src/app/calculator/furnaces/air-heating/air-heating.service.ts, src/app/calculator/steam/stack-loss/stack-loss.service.ts, src/app/phast/convert-phast.service.ts, src/app/phast/phast-results.service.ts, src/app/phast/phast.service.ts
=> Moisture divided by 0, ambient/fuel temp conversions, results bug

src/app/compressed-air-assessment/compressed-air-assessment-results.service.ts, src/app/compressed-air-assessment/compressed-air-calculation.service.ts, src/app/compressed-air-assessment/convert-compressed-air.service.ts, src/app/compressed-air-assessment/inventory/performance-points/calculations/unload-point-calculations.service.ts, src/app/compressed-air-assessment/inventory/performance-points/unload-point/unload-point.component.ts, src/app/core/core.service.ts, src/app/examples/mockCompressedAirAssessment.ts, src/app/indexedDb/assessment-db.service.ts, src/app/indexedDb/directory-db.service.ts, src/app/settings/assessment-settings/reset-data-modal/reset-data-modal.component.ts, src/app/shared/models/compressed-air-assessment.ts
connects #4650 
adds example compressed air assessment
fixes conversion of pressure 0 in assessment
=> Issue 4650

src/app/compressed-air-assessment/compressed-air-assessment-results.service.ts, src/app/compressed-air-assessment/compressed-air-report/compressed-air-report.component.html, src/app/compressed-air-assessment/compressed-air-report/payback-period/payback-period.component.html, src/app/compressed-air-assessment/compressed-air-report/payback-period/payback-period.component.ts
=> update payback details to show combined day type results

src/app/compressed-air-assessment/system-profile/system-profile-setup/operating-profile-table/operating-profile-table.component.html
=> decimal values able to be put in profile

src/app/dashboard/directory-dashboard/directory-items/assessment-item/compressed-air-assessment-card/compressed-air-assessment-card.component.html, src/app/dashboard/directory-dashboard/directory-items/assessment-item/compressed-air-assessment-card/compressed-air-assessment-card.component.ts
connects #4971 
dashboard card conversions and correct savings values used.
=> Issue 4971

src/app/compressed-air-assessment/explore-opportunities/improve-end-use-efficiency/improve-end-use-efficiency-item/improve-end-use-efficiency-item.component.html, src/app/compressed-air-assessment/explore-opportunities/improve-end-use-efficiency/improve-end-use-efficiency-item/improve-end-use-efficiency-item.component.ts, src/app/compressed-air-assessment/explore-opportunities/improve-end-use-efficiency/improve-end-use-efficiency.service.ts
=> fix form control binding in efficiency improvement

src/app/compressed-air-assessment/compressed-air-report/compressed-air-report.component.html, src/app/compressed-air-assessment/compressed-air-report/compressed-air-report.component.ts, src/app/compressed-air-assessment/compressed-air-report/compressed-air-report.module.ts, src/app/compressed-air-assessment/compressed-air-report/input-summary/input-summary.component.css, src/app/compressed-air-assessment/compressed-air-report/report-graphs/report-graphs.component.html, src/app/compressed-air-assessment/compressed-air-report/report-graphs/report-graphs.component.ts, src/app/report-rollup/assessment-reports/assessment-reports.component.html, src/app/report-rollup/compressed-air-rollup/compressed-air-rollup-print/compressed-air-rollup-print.component.css, src/app/report-rollup/compressed-air-rollup/compressed-air-rollup-print/compressed-air-rollup-print.component.html, src/app/report-rollup/compressed-air-rollup/compressed-air-rollup-print/compressed-air-rollup-print.component.spec.ts, src/app/report-rollup/compressed-air-rollup/compressed-air-rollup-print/compressed-air-rollup-print.component.ts, src/app/report-rollup/compressed-air-rollup/compressed-air-rollup.component.html, src/app/report-rollup/report-rollup.module.ts, src/app/shared/models/printing.ts, src/app/shared/models/settings.ts, src/app/shared/print-options-menu/print-options-menu.component.html, src/app/shared/print-options-menu/print-options-menu.component.ts, src/app/shared/print-options-menu/print-options-menu.service.ts
connects #4968 
adds printing for compressed air reports in rollup and assessments
=> printing working for compressed air systems

src/app/examples/mockCompressedAirAssessment.ts, src/app/settings/assessment-settings/reset-data-modal/reset-data-modal.component.ts
=> update compressed air example

src/app/dashboard/acknowledgments-page/acknowledgments-page.component.html
=> Issue 5087: updated acknowledgments page

src/app/fsat/modification-list/modification-list.component.html, src/app/psat/modification-list/modification-list.component.html
=> change what if verbage

src/app/compressed-air-assessment/system-profile/system-profile-setup/operating-profile-table/operating-profile-table.component.html
=> profile validation verbage updates

package.json, src/app/dashboard/sidebar/version-modal/version-modal.component.html
=> Issue 5076

package.json
=> fix electron dependency vulnerability

src/app/phast/losses/flue-gas-losses/flue-gas-compare.service.ts, src/app/phast/losses/flue-gas-losses/flue-gas-losses-form-mass/flue-gas-losses-form-mass.component.css, src/app/phast/losses/flue-gas-losses/flue-gas-losses-form-mass/flue-gas-losses-form-mass.component.html, src/app/phast/losses/flue-gas-losses/flue-gas-losses-form-volume/flue-gas-losses-form-volume.component.css, src/app/phast/losses/flue-gas-losses/flue-gas-losses-form-volume/flue-gas-losses-form-volume.component.html, src/app/phast/losses/flue-gas-losses/flue-gas-losses-moisture/flue-gas-losses-moisture.component.css, src/app/phast/losses/flue-gas-losses/flue-gas-losses-moisture/flue-gas-losses-moisture.component.html, src/app/phast/losses/flue-gas-losses/flue-gas-losses-moisture/flue-gas-losses-moisture.component.ts, src/app/phast/losses/flue-gas-losses/flue-gas-moisture-modal/flue-gas-moisture-modal.component.html, src/app/phast/losses/flue-gas-losses/flue-gas-moisture-modal/flue-gas-moisture-modal.component.ts, src/app/phast/losses/flue-gas-losses/flue-gas-moisture-panel/flue-gas-moisture-panel.component.html, src/app/phast/losses/flue-gas-losses/flue-gas-moisture-panel/flue-gas-moisture-panel.component.ts, src/app/phast/losses/flue-gas-losses/flue-gas-moisture-results/flue-gas-moisture-results.component.html, src/app/phast/losses/flue-gas-losses/flue-gas-moisture-results/flue-gas-moisture-results.component.ts, src/app/phast/phast.component.html
connects #5008 
fixes modal size/layout
fixed the modal logic to be used in phast, removed all code that was copy/pasted from fsat
fixed settings to be metric/imperial
=> fixes to moisture modal in phast

src/app/dashboard/copy-items/copy-items.component.css, src/app/dashboard/copy-items/copy-items.component.html, src/app/dashboard/copy-items/copy-items.component.spec.ts, src/app/dashboard/copy-items/copy-items.component.ts, src/app/dashboard/dashboard.component.html, src/app/dashboard/dashboard.component.ts, src/app/dashboard/dashboard.module.ts, src/app/dashboard/dashboard.service.ts, src/app/dashboard/directory-dashboard/directory-dashboard-menu/directory-dashboard-menu.component.html, src/app/dashboard/directory-dashboard/directory-dashboard-menu/directory-dashboard-menu.component.ts, src/app/dashboard/move-items/move-items.component.css, src/app/dashboard/move-items/move-items.component.html
=> Issue 5013: Copy to Folder

src/app/ssmt/ssmt-diagram/blowdown-flash-tank/blowdown-flash-tank.component.css, src/app/ssmt/ssmt-diagram/boiler-diagram/boiler-diagram.component.css, src/app/ssmt/ssmt-diagram/condensate-flash-tank/condensate-flash-tank.component.css, src/app/ssmt/ssmt-diagram/deaerator-diagram/deaerator-diagram.component.css, src/app/ssmt/ssmt-diagram/flash-tank-diagram/flash-tank-diagram.component.css, src/app/ssmt/ssmt-diagram/prv-diagram/prv-diagram.component.css, src/app/ssmt/ssmt-diagram/turbine-diagram/turbine-diagram.component.css
=> changed size of equipment on hover

src/app/report-rollup/rollup-summary-pie-chart/rollup-summary-pie-chart.component.ts, src/app/treasure-hunt/treasure-hunt-report/report-graphs/utility-donut-chart/utility-donut-chart.component.ts
=> Issue-5036: Roll up report graphs too big for spot

src/app/ssmt/ssmt-report/executive-summary/executive-summary.component.html, src/app/ssmt/ssmt-report/input-summary/turbine-summary/turbine-input-table/turbine-input-table.component.html
=> Issue-2869: SSMT Print Report Tweaks

src/app/treasure-hunt/treasure-hunt-calculator-services/water-heating-treasure-hunt.service.ts, src/app/treasure-hunt/treasure-hunt-report/opportunity-summary.service.ts
=> Issue 4590: Setup Vent Steam Calc to handle multiple energy types

src/app/tools-suite-api/steam-suite-api.service.ts
=> fix header not highest pressure not set to null

src/app/calculator/standalone.service.ts, src/app/compressed-air-assessment/compressed-air-calculation.service.ts, src/app/tools-suite-api/compressed-air-suite-api.service.ts, src/app/tools-suite-api/suite-api-helper.service.ts
connects #4497
remove compressorAddon
add compressed air calls to compressed air suite api service
=> issue 4497

src/app/motor-inventory/batch-analysis/batch-analysis-table/batch-analysis-table.component.html, src/app/motor-inventory/motor-inventory-setup/motor-inventory-setup.component.html, src/app/motor-inventory/motor-inventory-setup/motor-inventory-setup.component.ts, src/app/motor-inventory/motor-inventory.component.html
=> Issue-5109: Motor Inventory scrolling

src/app/calculator/utilities/co2-savings/co2-savings-form/co2-savings-form.component.html, src/app/calculator/utilities/co2-savings/co2-savings-form/co2-savings-form.component.ts, src/app/calculator/utilities/co2-savings/co2-savings-help/co2-savings-help.component.css, src/app/calculator/utilities/co2-savings/co2-savings-help/co2-savings-help.component.html, src/app/calculator/utilities/co2-savings/co2-savings-help/co2-savings-help.component.ts, src/app/calculator/utilities/co2-savings/co2-savings.component.html, src/app/calculator/utilities/co2-savings/co2-savings.component.ts
=> Issue 5021 CO2 savings help text

src/app/compressed-air-assessment/explore-opportunities/reduce-run-time/reduce-run-time.component.ts
Looks good. Should work fine.
The problem stems from the modification results being set in the parent explore opps component that is subscribed to compressedAirAssessment value
connects #5114
=> review 5114

src/app/motor-inventory/motor-inventory-setup/department-catalog-table/department-catalog-table.component.html, src/app/motor-inventory/motor-inventory-setup/department-catalog-table/department-catalog-table.component.ts, src/app/motor-inventory/motor-inventory.component.css, src/app/motor-inventory/motor-inventory.component.html, src/app/motor-inventory/motor-inventory.component.ts, src/app/motor-inventory/motor-inventory.module.ts
=> Issue-5118: Motor Inventory: Add copy Motor functionality

src/app/compressed-air-assessment/explore-opportunities/explore-opportunities-results/explore-opportunities-results.component.ts, src/app/compressed-air-assessment/explore-opportunities/reduce-run-time/reduce-run-time.component.ts
connects #5114 
Needed to reset modification based on modificationResults change
=> Issue 5114

src/app/calculator/furnaces/heat-cascading/heat-cascading-results/heat-cascading-results.component.html
=> updated results table verbiage

src/app/calculator/utilities/pre-assessment/pre-assessment-graph/pre-assessment-graph.component.ts
=> Issue 5036: Roll up report graphs too big for spot 

src/app/calculator/furnaces/flue-gas/flue-gas-form.service.ts
connects #5148 
FG validation checks undefined, always add required
=> Issue 5148

src/app/compressed-air-assessment/system-profile/system-profile-annual-summary/system-profile-annual-summary.component.html, src/app/compressed-air-assessment/system-profile/system-profile-annual-summary/system-profile-annual-summary.component.ts
connects #5050 
add annual summary for individual compressors
=> Issue 5050

main.js
=> add dev tools open by keyboard functionality

src/app/examples/mockTreasureHunt.ts, src/app/shared/models/treasure-hunt.ts, src/app/treasure-hunt/operation-costs/operation-costs.component.html, src/app/treasure-hunt/operation-costs/operation-costs.component.ts
=> Issue 5156: Add Total Emission Output Rate field to Water, WW, CA, and Steam in TH

src/app/examples/mockTreasureHunt.ts, src/app/shared/models/treasure-hunt.ts, src/app/treasure-hunt/operation-costs/operation-costs.component.css, src/app/treasure-hunt/operation-costs/operation-costs.component.html, src/app/treasure-hunt/operation-costs/operation-costs.component.ts, src/app/treasure-hunt/treasure-hunt.component.ts, src/app/treasure-hunt/treasure-hunt.module.ts
=> Issue 5157: Add CO2 saving field for Electricity in TH

src/app/ssmt/boiler/boiler.component.html, src/app/ssmt/boiler/boiler.service.ts, src/app/ssmt/header/header.service.ts, src/app/ssmt/operations/general-operations/general-operations.component.html, src/app/ssmt/operations/operations.service.ts
connects #3420
Needs verification fixes - Remove conversion, move display unit
=> Issue 3420

src/app/calculator/steam/condensing-economizer/condensing-economizer-form/condensing-economizer-form.component.html, src/app/calculator/steam/feedwater-economizer/feedwater-economizer-form/feedwater-economizer-form.component.html, src/app/calculator/steam/water-heating/water-heating-form/water-heating-form.component.html
connects #5066 
Now using steam settings for units in new steam calcs. 
Also added units in validation msg where possible
=> Issue 5066

src/app/compressed-air-assessment/compressed-air-assessment.component.ts
connects #5164 
Fixes button disabled due to invalid profile. Couldn't reproduce larger issue
=> Issue 5164

src/app/shared/assessment-co2-savings/assessment-co2-savings.component.html, src/app/shared/assessment-co2-savings/assessment-co2-savings.component.ts, src/app/shared/models/treasure-hunt.ts, src/app/treasure-hunt/convert-input-data.service.ts, src/app/treasure-hunt/help-panel/help-panel.component.html, src/app/treasure-hunt/help-panel/help-panel.component.ts, src/app/treasure-hunt/mixed-co2-emissions/mixed-co2-emissions.component.ts, src/app/treasure-hunt/operation-costs/operation-costs.component.html, src/app/treasure-hunt/operation-costs/operation-costs.component.ts, src/app/treasure-hunt/treasure-hunt-report/executive-summary/carbon-emissions-summary-table/carbon-emissions-summary-table.component.css, src/app/treasure-hunt/treasure-hunt-report/executive-summary/carbon-emissions-summary-table/carbon-emissions-summary-table.component.html, src/app/treasure-hunt/treasure-hunt-report/executive-summary/carbon-emissions-summary-table/carbon-emissions-summary-table.component.spec.ts, src/app/treasure-hunt/treasure-hunt-report/executive-summary/carbon-emissions-summary-table/carbon-emissions-summary-table.component.ts, src/app/treasure-hunt/treasure-hunt-report/executive-summary/executive-summary.component.html, src/app/treasure-hunt/treasure-hunt-report/treasure-hunt-report.component.ts, src/app/treasure-hunt/treasure-hunt-report/treasure-hunt-report.module.ts, src/app/treasure-hunt/treasure-hunt-report/treasure-hunt-report.service.ts, src/app/treasure-hunt/treasure-hunt.service.ts
=> Issue 5160: Add CO2 emission results in TH

src/app/calculator/furnaces/flue-gas/flue-gas-modal/flue-gas-modal.component.html, src/app/calculator/furnaces/flue-gas/flue-gas.component.html, src/app/phast/losses/flue-gas-losses/flue-gas-losses.component.html, src/app/phast/losses/flue-gas-losses/flue-gas-losses.component.ts
connects #5061 
Show o2 and excess air results when solid fg
=> Issue 5061

src/app/calculator/steam/stack-loss/stack-loss-help/stack-loss-help.component.html, src/app/ssmt/boiler/boiler.component.html, src/app/ssmt/boiler/boiler.component.ts
connects #5205 
Remove fuel options from boiler form, update help text
=> Issue 5205
