- src/app/calculator/utilities/unit-converter/unit-converter.component.html
- src/app/settings/psat-settings/psat-settings.component.html
- src/app/settings/psat-settings/psat-settings.component.ts
- src/app/shared/convert-units/definitions/volume.ts
- src/app/shared/convert-units/definitions/volumeFlowRate.ts
Changed all instances of litre to liter and the associated acronym from l to L according to technical editor's advice. Added acronyms of units to the unit converter and assessment settings page. Only text should have been edited.
> Liter and acronym in unit converter and assessment settings

- src/app/psat/psat.service.ts
> change spelling of two variable names

- package.json
updates version number and gets rid of the npm error that happens when the package-lock.json file doesn't exist
> update version number and npm run clean command

- src/app/phast/convert-phast.service.ts
- src/app/phast/losses/energy-input/energy-input-form/energy-input-form.component.html
- src/app/phast/losses/fixture-losses/fixture-losses-form/fixture-losses-form.component.html
- src/app/phast/phast.component.html
- src/app/phast/phast.service.ts
- src/app/phast/system-basics/system-basics.component.ts
connects #755 
the behavior in 755 was most likely from errors being thrown while converting. A few of the conversions had the wrong unit signatures for the service and could have thrown errors that caused issues. Those have been resolved
> Phast updates

- main.js
- src/app/calculator/furnaces/o2-enrichment/o2-enrichment-graph/o2-enrichment-graph.component.ts
Integrates crash reporting through use of a backtrace.io hosted server. Fixes potential bug in which the user may try to continually plot lines when they have only changed base conditions, resulting in `n` detail boxes with only one plotted line.
> Integrate crash reporting and fix potential o2 enrichment "bug"

- .travis.yml
Adds `travis_retry` to the `npm installs` which will prevent random network disconnects on the travis CI machines (that rarely, but still do happen). `travis_retry` simply retries the command up to 3 times if it returned non-zero. 
connect #844
> add travis_retry command to `npm install`

- src/app/about-page/about-page.component.html
- src/app/phast/losses/extended-surface-losses/extended-surface-losses-form/extended-surface-losses-form.component.html
- src/app/phast/losses/extended-surface-losses/extended-surface-losses-form/extended-surface-losses-form.component.ts
- src/app/phast/losses/flue-gas-losses/flue-gas-losses-form-mass/flue-gas-losses-form-mass.component.html
- src/app/phast/losses/losses-help/cooling-losses-help/cooling-losses-help.component.html
- src/app/phast/losses/losses-help/extended-surface-losses-help/extended-surface-losses-help.component.html
- src/app/phast/losses/losses-help/flue-gas-losses-help/flue-gas-losses-help.component.html
- src/app/phast/losses/losses-help/opening-losses-help/opening-losses-help.component.html
- src/app/phast/losses/losses-help/wall-losses-help/wall-losses-help.component.html
- src/app/phast/losses/opening-losses/opening-losses-form/opening-losses-form.component.ts
- src/app/phast/losses/wall-losses/wall-losses-form/wall-losses-form.component.html
- src/app/phast/losses/wall-losses/wall-losses-form/wall-losses-form.component.ts
- src/app/phast/losses/wall-losses/wall-losses.service.ts
-Fixes unit bug in opening losses area calculation
-Adds wall losses defaults on form init
-Adds new PHAST paragraph in the "About" section
-Update cooling losses help text
-Change Moisture in Air Composition to Moisture in Air Combustion for Solid/Liquid Flue Gas
-Enforce emissivity mins and maxes across all of PHAST and make their keyboard increment values to be 0.1 
connect #913 
connect #926 
connect #920 
connect #936 
connect #917 
connect #929
> Various phast issues - see description

- package.json
- src/app/phast/losses/flue-gas-losses/flue-gas-compare.service.ts
- src/app/phast/losses/flue-gas-losses/flue-gas-losses-form-volume/flue-gas-losses-form-volume.component.html
- src/app/phast/losses/flue-gas-losses/flue-gas-losses-form-volume/flue-gas-losses-form-volume.component.ts
- src/app/phast/losses/flue-gas-losses/flue-gas-losses.service.ts
- src/app/phast/phast.service.ts
- src/app/shared/mocks/mock-directory.ts
- src/app/shared/models/phast/losses/flueGas.ts
Allows the user to select excess air or oxygen in flue gas via dropdown menu for the flue gas by volume calculation. The non-selected field will be shown as a calculated, non-editable value.
connect #927
> Adds Flue Gas Oxygen Calculation Method Dropdown

- src/app/settings/phast-settings/phast-settings.component.css
- src/app/settings/phast-settings/phast-settings.component.html
connects #1056 
While selecting furnace type label is changing color to dark orange. Making UI easier to read for a user.
> Radio-button furnace type label color change  

- src/app/phast/metered-energy/metered-fuel/metered-fuel-form/metered-fuel-form.component.html
- src/app/phast/metered-energy/metered-fuel/metered-fuel-form/metered-fuel-form.component.ts
- src/app/suiteDb/solid-liquid-flue-gas-material/solid-liquid-flue-gas-material.component.html
- src/app/suiteDb/solid-liquid-flue-gas-material/solid-liquid-flue-gas-material.component.ts
connect #1095 
connect #1075 
connect #1094 
Updates units in metered energy and "Add solid / liquid fuel" pages / modals. Fixes bug that crashed the app due to invalid solid / liquid database input
> Update heating value units

- package.json
- src/app/psat/psat-report/output-summary/output-summary.component.ts
- src/app/report-rollup/report-rollup.service.ts
updated psat report rollup to match phast methods
set electron-builder version to know working version without ^
> fix psat report, set version num electron-builder

- src/app/calculator/furnaces/efficiency-improvement/efficiency-improvement.component.ts
- src/app/calculator/pumps/specific-speed/specific-speed-graph/specific-speed-graph.component.ts
modified:   src/app/calculator/furnaces/efficiency-improvement/efficiency-improvement.component.ts
modified:   src/app/calculator/pumps/specific-speed/specific-speed-graph/specific-speed-graph.component.ts
Limits the values shown on the Specific Speed graph depending on if the pump type is VTP or not. Values that are outside the range are valid inputs in the text box, but will not show as a point on the graph.
connects #892
> Adds limiting values to the Specific Speed graph

- src/app/phast/losses/charge-material/charge-material.component.ts
- src/app/phast/losses/charge-material/charge-material.service.ts
- src/app/phast/losses/flue-gas-losses/flue-gas-losses.component.html
- src/app/phast/losses/flue-gas-losses/flue-gas-losses.component.ts
- src/app/phast/phast-report/phast-input-summary/cooling-summary/cooling-summary.component.html
- src/app/phast/phast-report/phast-input-summary/cooling-summary/cooling-summary.component.ts
- src/app/phast/phast-report/results-data/results-data.component.html
- src/app/phast/phast-results.service.ts
- src/app/phast/phast.service.ts
- src/app/settings/phast-settings/phast-settings.component.ts
- src/app/shared/json-to-csv/json-to-csv.service.ts
connects #1106
connects #1184
connects #1200
connects #1242
connects #1244
connects #1245
connects #1246 
-Adds cooling medium name for cooling losses in reports
-Changes Charge Materials "Loss" default name to "Material" default name
-Export to CSV for PSAT now includes fluid type and fluid temperature
-When using Steam as a furnace type, the furnace type now defaults "Steam" instead of Ladle
-Exothermic heating values are now computed correctly for charge materials
-System Losses is now Flue Gas Losses on the flue gas page, the results page results are computed the same way as the immediate values on the flue gas page
-Available heat has one more sig fig, for a total of 3 sig figs
> Various PHAST issues

- src/app/calculator/furnaces/efficiency-improvement/efficiency-improvement-form/efficiency-improvement-form.component.html
- src/app/calculator/furnaces/efficiency-improvement/efficiency-improvement-help/efficiency-improvement-help.component.html
- src/app/calculator/furnaces/energy-use/energy-use-help/energy-use-help.component.html
- src/app/calculator/furnaces/o2-enrichment/o2-enrichment-form/o2-enrichment-form.component.html
- src/app/calculator/furnaces/o2-enrichment/o2-enrichment-help/o2-enrichment-help.component.html
- src/app/phast/losses/losses-help/atmosphere-losses-help/atmosphere-losses-help.component.html
- src/app/phast/losses/losses-help/exhaust-gas-help/exhaust-gas-help.component.html
connects #1217 
connects #1224 
connects #1225 
connects #1226 
- Fixing typo in help text atmosphere  Initial Temperature = Inlet Temperature
- Corrected help description for combustible Gas as CH4 and Total Volumetric Flow Rate
- Removed double help text for O2 in combustion Air
- Removed Maximum Values Allowed for calculators:
1. O2 Enrichment
2. Efficiency Improvement
3. Energy Equivalency
4. Flow Calculations Energy Use
5. Pre-Assessment
> Typos and Max Value Fixes

- src/app/calculator/furnaces/energy-equivalency/energy-equivalency-form/energy-equivalency-form.component.html
- src/app/calculator/furnaces/energy-equivalency/energy-equivalency-form/energy-equivalency-form.component.ts
- src/app/calculator/furnaces/energy-equivalency/energy-equivalency-help/energy-equivalency-help.component.html
- src/app/calculator/furnaces/energy-equivalency/energy-equivalency.component.ts
- src/app/calculator/furnaces/o2-enrichment/o2-enrichment-form/o2-enrichment-form.component.html
- src/app/calculator/furnaces/o2-enrichment/o2-enrichment-form/o2-enrichment-form.component.ts
- src/app/calculator/furnaces/o2-enrichment/o2-enrichment-help/o2-enrichment-help.component.html
- src/app/calculator/furnaces/o2-enrichment/o2-enrichment.component.ts
- src/app/phast/losses/fixture-losses/fixture-losses-form/fixture-losses-form.component.ts
- src/app/phast/losses/flue-gas-losses/flue-gas-losses-form-mass/flue-gas-losses-form-mass.component.html
- src/app/phast/losses/flue-gas-losses/flue-gas-losses-form-mass/flue-gas-losses-form-mass.component.ts
- src/app/phast/phast-report/phast-input-summary/flue-gas-summary/flue-gas-summary.component.html
- src/app/phast/phast-report/results-data/results-data.component.css
- src/app/phast/phast-report/results-data/results-data.component.html
- src/app/shared/sig-figs.pipe.ts
connects #1333 
connects #1337 
connects #1336 
connects #1334 
- Adds a note to O2 enrichment & Energy Equivalency calculators when out of focus from an input field.
- Fixes significant figures displays and pipe.
- Fixture Specific Heat displaying 3 decimals places.
- Solid Fuels change "Moisture in Air Combustion" to "Moisture in Combustion Air". Label, help text and report.
- Fixes borders outline for results data.
> Fixing Multiple Issues

- src/app/calculator/compressed-air/compressed-air.component.html
- src/app/phast/explore-phast-opportunities/explore-phast-opportunities-form/explore-charge-materials-form/explore-charge-materials-form.component.html
- src/app/phast/explore-phast-opportunities/explore-phast-opportunities-form/explore-fixtures-form/explore-fixtures-form.component.html
- src/app/phast/explore-phast-opportunities/explore-phast-opportunities-form/explore-flue-gas-form/explore-flue-gas-form.component.html
- src/app/phast/explore-phast-opportunities/explore-phast-opportunities-form/explore-leakage-form/explore-leakage-form.component.html
- src/app/phast/explore-phast-opportunities/explore-phast-opportunities-form/explore-opening-form/explore-opening-form.component.html
- src/app/phast/explore-phast-opportunities/explore-phast-opportunities-form/explore-operations-form/explore-operations-form.component.html
- src/app/phast/explore-phast-opportunities/explore-phast-opportunities-form/explore-system-efficiency-form/explore-system-efficiency-form.component.html
- src/app/phast/explore-phast-opportunities/explore-phast-opportunities-form/explore-wall-form/explore-wall-form.component.html
- src/app/phast/explore-phast-opportunities/explore-phast-opportunities.component.html
- src/app/phast/losses/losses.component.html
- src/app/phast/losses/opening-losses/opening-losses-form/opening-losses-form.component.html
- src/app/psat/psat.component.html
connect #1493 
connect #1485 
connect #1401 
connect #1498 
connect #1441 
- Verbiage changes for added help text and buttons / dropdown choices
- Baseline losses forms are now disabled in explore opportunities, preventing the user from changing their baseline setup via explore ops
> Quick fixes for PHAST

- src/app/psat/explore-opportunities/explore-opportunities-form/pump-data-form/pump-data-form.component.html
- src/app/psat/explore-opportunities/explore-opportunities-form/rated-motor-form/rated-motor-form.component.html
- src/app/psat/explore-opportunities/explore-opportunities-form/system-data-form/system-data-form.component.html
connects #1493 
- Disables baseline fields when using PSAT's explore opportunities forms
> disable baseline fields in explore opportunities for PSAT

- src/app/calculator/furnaces/energy-use/energy-use.component.ts
- src/app/phast/losses/losses-help/wall-losses-help/wall-losses-help.component.html
- src/app/psat/psat.service.ts
- src/app/suiteDb/wall-losses-surface/wall-losses-surface.component.html
connects #1649 
connects #1638 
connects https://github.com/ORNL-AMO/AMO-Tools-Suite/issues/224
- min rpm for psat motors is now 1
- add the word factor to surface shape / orientation
- change default natural gas heating value
> fix psat motor rpm range issue, and two other quick issues

- src/app/calculator/compressed-air/receiver-tank/air-capacity-help/air-capacity-help.component.html
- src/app/calculator/compressed-air/receiver-tank/receiver-tank.component.html
- src/app/calculator/compressed-air/receiver-tank/receiver-tank.component.ts
connects #1450 
Moves the air capacity calculator to be shown by default under the receiver tank page.
> Air Capacity relocation

- src/app/calculator/steam/steam-properties/steam-properties-form/steam-properties-form.component.ts
- src/app/settings/psat-settings/psat-settings.component.html
- src/app/settings/psat-settings/psat-settings.component.ts
- src/app/settings/steam-settings/steam-settings.component.html
- src/app/shared/convert-units/definitions/specificHeat.ts
- src/app/shared/convert-units/definitions/temperature.ts
- src/app/shared/convert-units/definitions/volumetricHeat.ts
Changes: in settings dropdown menus added degree symbols to temperature units; some units were formatted ( unit ) and other were (unit), consolidated all formatting into (unit) i.e. no spaces; corrected specific volume units under steam settings to have superscript 3
connect #1738
> Unit fixes in settings menu

- src/app/settings/settings.service.ts
connect #1940 
"switching units of measure to imperial (if already on imperial, switching to metric and back) clears units for Pressure Measurement without assigning new ones."
> Fixed issue

- src/app/calculator/motors/motor-performance/motor-performance-form/motor-performance-form.component.ts
- src/app/calculator/motors/nema-energy-efficiency/nema-energy-efficiency-form/nema-energy-efficiency-form.component.ts
- src/app/psat/motor/motor.component.ts
- src/app/psat/psat.service.ts
Changed option in Efficiency Class dropdown from Premium to Premium Efficient in 3 places;
Nema energy calc, Motor perf. calc, and PSAT assessment field data tab
connect #1599
> issue 1599 - renaming Premium to Premium Efficient

- package.json
connects #2639 
updated version number for release.
Tested with auto updater, still works.
> updated executable and product name to MEASUR, updated version number

- src/app/calculator/compressed-air/system-capacity/system-capacity-form/system-capacity-form.component.html
connects #3468 
Custom pipe units should be inches. (Metric equivalent is mm for this case)
> Issue-3468 (post-verification)

- src/app/calculator/furnaces/o2-enrichment/o2-enrichment-form.service.ts
Change request commented to issue 3852 "one unit conversion problem. "Combustion Air Preheat Temp" is not converting when "generate example"
connects #3822 
Convert example temp combAirTemp.
> Issue 3822 (post-verification)

- src/app/shared/helper-services/update-data.service.ts
This was causing a crash for Kiran when testing. I think it was a bug for an assessment he had created on a non-production installer but this check doesn't hurt to have in there.
> thunt update assessment bug check

- src/app/calculator/compressed-air/compressed-air-pressure-reduction/compressed-air-pressure-reduction.service.ts
- src/app/calculator/compressed-air/compressed-air-reduction/compressed-air-reduction.service.ts
- src/app/calculator/steam/steam-reduction/steam-reduction.service.ts
- src/app/calculator/utilities/electricity-reduction/electricity-reduction.service.ts
- src/app/calculator/utilities/natural-gas-reduction/natural-gas-reduction.service.ts
- src/app/calculator/utilities/water-reduction/water-reduction.service.ts
connects #3964 
fixes bug that causes opportunity calculation errors for opportunities without modifications by setting the modification result to the baseline. (0 savings)
> fix treasure hunt modification results bug

- src/app/phast/explore-phast-opportunities/explore-phast-opportunities-form/explore-flue-gas-form/explore-flue-gas-form.component.ts
Sets warnings null on init to avoid object undefined console errors. 
Both checkWarnings methods return currently, though it seems like the calculate event that's emitted while checking baseline warnings resets the component state before it can set this.modificationWarnings - so is undefined.
> PH excessAirWarnings undefined

- src/app/phast/system-basics/system-basics.component.ts
connects #4138 
- Allow user to change energy source when no losses exist
Should we refine how loss arrays are added to the PHAST object? Currently, we set an empty phast.losses object that will exist if you click over to the loss screen. Also if you create a loss and remove it, the loss array is still existing on the object. Seemed a little unexpected.
> Issue 4138

- src/app/psat/motor/motor.component.html
connects #4115 
Removed pristine condition. Message wouldn't appear if user calculated FLA without touching input first.
> Issue 4115

- src/app/calculator/furnaces/atmosphere/atmosphere.service.ts
- src/app/calculator/furnaces/charge-material/charge-material.service.ts
- src/app/calculator/furnaces/fixture/fixture.service.ts
- src/app/calculator/furnaces/opening/opening.service.ts
- src/app/calculator/furnaces/wall/wall.service.ts
Don't access -1 index on losses array. Pass undefined loss object instead...
This follows up a leakage PR review last week. Adding the same change to other PH calcs.
> PH standalones - stop accessing -1 index

- src/app/calculator/utilities/pre-assessment/pre-assessment-form/pre-assessment-form.component.html
- src/app/phast/designed-energy/designed-energy-results/designed-energy-results.component.html
- src/app/phast/designed-energy/designed-energy.component.ts
- src/app/phast/designed-energy/designed-energy.service.ts
- src/app/phast/metered-energy/metered-energy-results/metered-energy-results.component.html
- src/app/phast/metered-energy/metered-energy.component.ts
- src/app/phast/metered-energy/metered-energy.service.ts
- src/app/phast/phast-report/energy-used/energy-used.component.html
- src/app/phast/phast-report/energy-used/energy-used.component.ts
- src/app/shared/models/phast/designedEnergy.ts
- src/app/shared/models/phast/meteredEnergy.ts
connects #4299 
- Add hourly and annual results for designed-metered energy
- Some of the naming/grouping in designed/metered/calculated results methods is a bit confusing and could probably be broken up, but didn't want to get out of scope for this.
> Issue 4299

- src/app/calculator/fans/fan-analysis/fan-analysis-form/fan-info-form/fan-info-form.component.html
- src/app/calculator/fans/fan-analysis/fan-analysis-form/fan-info-form/fan-info-form.component.ts
- src/app/fsat/calculate-pressures/calculate-flow-pressure/calculate-flow-pressure.component.html
- src/app/fsat/calculate-pressures/calculate-flow-pressure/calculate-flow-pressure.component.ts
- src/app/fsat/fan-field-data/fan-field-data.component.html
- src/app/fsat/fan-field-data/fan-field-data.component.ts
- src/app/shared/models/fans.ts
connects #4345 #4354 
- Hide corrected fields and use defaults
- Use assessment gas density in modal
Changed tempFsatCopy to modalFieldData - modal only assigning to field data so don't need to save the whole FSAT object
> issue-4345

- src/app/compressed-air-assessment/compressed-air-assessment.component.html
- src/app/compressed-air-assessment/compressed-air-banner/setup-tabs/setup-tabs.component.html
- src/app/compressed-air-assessment/system-profile/system-profile-graphs/system-profile-graphs.component.html
- src/app/compressed-air-assessment/system-profile/system-profile-graphs/system-profile-graphs.component.ts
- src/app/compressed-air-assessment/system-profile/system-profile-setup/compressor-ordering-table/compressor-ordering-table.component.css
- src/app/compressed-air-assessment/system-profile/system-profile-setup/compressor-ordering-table/compressor-ordering-table.component.html
- src/app/compressed-air-assessment/system-profile/system-profile-setup/operating-profile-table/operating-profile-table.component.css
- src/app/compressed-air-assessment/system-profile/system-profile-setup/operating-profile-table/operating-profile-table.component.html
- src/app/compressed-air-assessment/system-profile/system-profile-setup/operating-profile-table/operating-profile-table.component.ts
- src/app/compressed-air-assessment/system-profile/system-profile-setup/profile-setup-form/profile-setup-form.component.html
- src/app/compressed-air-assessment/system-profile/system-profile-setup/system-profile-setup.component.html
- src/app/compressed-air-assessment/system-profile/system-profile-summary/system-profile-summary.component.css
- src/app/compressed-air-assessment/system-profile/system-profile-summary/system-profile-summary.component.html
- src/app/compressed-air-assessment/system-profile/system-profile-summary/system-profile-summary.component.ts
- src/app/compressed-air-assessment/system-profile/system-profile.service.ts
- src/app/dashboard/assessment.service.ts
- src/app/shared/models/compressed-air-assessment.ts
connects #4617 
Adds logic for system profiling. Currently just setting random numbers for % Capacity and using them for profiling. Numbers always being randomly generated on init, will be fixed when integrating day types.
Ordering not implemented.
Results summary added and working based on dummy numbers.
Results graphs implemented based on dummy numbers.
No help text panel for profiling, need the screen space...
> Issue 4617

- src/app/log-tool/system-setup/setup-data/setup-data.component.ts
Connects #4609 . Seconds should now be stored regardless of the date format on the Excel file.
> excel import stores seconds now regardless of format

- src/app/compressed-air-assessment/compressed-air-assessment-results.service.ts
- src/app/compressed-air-assessment/compressed-air-report/executive-summary/executive-summary.component.html
- src/app/compressed-air-assessment/compressed-air-report/executive-summary/executive-summary.component.ts
- src/app/compressed-air-assessment/explore-opportunities/explore-opportunities-results/explore-opportunities-results.component.html
- src/app/compressed-air-assessment/explore-opportunities/explore-opportunities-results/explore-opportunities-results.component.ts
connects #4892 
adds peak demand, cost and savings to results
calculates hours per year based on hours on instead of 24 hours by default
> add peak demand values to results

- src/app/compressed-air-assessment/compressed-air-report/executive-summary/executive-summary.component.html
- src/app/compressed-air-assessment/explore-opportunities/explore-opportunities-results/explore-opportunities-results.component.html
- src/app/compressed-air-assessment/explore-opportunities/explore-opportunities.component.ts
- src/app/compressed-air-assessment/inventory/design-details/design-details.component.ts
- src/app/compressed-air-assessment/inventory/generic-compressor-modal/filter-compressors/filter-compressors.component.html
- src/app/compressed-air-assessment/inventory/generic-compressor-modal/filter-compressors/filter-compressors.component.ts
- src/app/compressed-air-assessment/system-information/system-information.component.ts
- src/app/compressed-air-assessment/system-profile/profile-setup-form/profile-setup-form.component.html
connects #4941 
- Remove "calc" from profile dropdown
- Filter control type dropdown based on compressor type selection in inventory modal
- Rounding for calculated input values
- Move demand values in results reports
- Quick fix selected day type bug in explore opps when navigating tabs
> Issue 4941

- src/app/psat/psat-warning.service.ts
- src/app/psat/pump-fluid/pump-fluid.component.ts
- src/app/shared/helper-services/update-data.service.ts
connects #5007 
The bugs were in Pump Fluid and Motor. The Pump Fluid bug occurred when Fluid Type = "Other", the property Boiling Point could not be calculated, so when Fluid Type = "Other" the form does not check for warnings or validation. 
The Motor bug was cause by older PSAT having the line_frequency property set to 0 or 1, so the fix was to check for those values and set line_frequency = 50 if value was 0 and set it to 60 if value was 1.
> Issue-5007: Old Pump Assessment Bugged

- src/app/phast/phast.component.ts
connects #5102 
I fixed this bug by added the lifecycle hook ngAfterContentInit() to check for tutorials after all subscriptions have been made
> Issue-5102: Old tutorial step bug in PHAST

- src/app/waste-water/waste-water-report/waste-water-report.component.ts
- src/app/waste-water/waste-water.service.ts
Example waste water was causing crash in rollup because valid was not a set property. Quick fix
> quick fix waste water report

- src/app/psat/add-modification/add-modification.component.ts
- src/app/psat/psat.component.ts
- src/app/shared/assessment-co2-savings/assessment-co2-savings.component.ts
connects #4924 
When user has old assessment with existing mods --> populate co2Data from baseline on unselected mods without user needing to view operations page for each.
> Update existing mods co2savings

- src/app/phast/convert-phast.service.ts
- src/app/phast/losses/operations/co2-savings-phast/co2-savings-phast.component.html
- src/app/phast/losses/operations/co2-savings-phast/co2-savings-phast.service.ts
- src/app/phast/phast-report/executive-summary.service.ts
- src/app/phast/phast-report/phast-input-summary/operation-data/operation-data.component.html
- src/app/phast/phast-report/results-data/results-data.component.html
- src/app/phast/phast-report/results-data/results-data.component.ts
- src/app/phast/phast-results.service.ts
- src/app/settings/phast-settings/phast-settings.component.html
- src/app/settings/phast-settings/phast-settings.component.ts
- src/app/shared/models/phast/phast.ts
connects #5267 #4923 #5325
fixed incorrect electricity use bug
fixed incorrect Nat gas cost bug
fixed coal carbon and electrode costs - no longer using cost conversion
changed coal carbon emission math and units to MMBtu
fixed - 'calculate net co2.. only appears when mixed selected'
added unit defaults for when fuel-fired/electro/steam is switched
fixed carbon emissions output number not updating
added input summary fields
> Various EAF and Co2 issues in PHAST

- src/app/shared/assessment-co2-savings/assessment-co2-savings.component.ts
- src/app/shared/helper-services/update-data.service.ts
connects #5458 
BugFix: only set locked values when co2 moddata sub emits.
Also move redundant if condition and unneed update data service object
> Issue 5262 Hotfix

- src/app/compressed-air-assessment/system-profile/profile-setup-form/profile-setup-form.component.html
- src/app/compressed-air-assessment/system-profile/profile-setup-form/profile-setup-form.component.ts
- src/app/compressed-air-assessment/system-profile/system-profile-setup/operating-profile-table/operating-profile-table.component.html
connects #5580 
profile data is set dependent on the selected profile option for each day type. Added warning to indicate this.
Also resets selection when profile data option is changed
> add warning about profile option for setting data from explorer

- src/app/compressed-air-assessment/system-information/system-capacity-modal/system-capacity-modal.component.html
- src/app/compressed-air-assessment/system-information/system-capacity-modal/system-capacity-modal.component.ts
- src/app/compressed-air-assessment/system-information/system-information.component.html
- src/app/compressed-air-assessment/system-information/system-information.component.ts
#5614 
Fixes state where modal won't open if was previously closed by clicking backdrop area
> Issue 5614 - System capacity modal parent should handle open and close

- src/app/calculator/motors/nema-energy-efficiency/nema-energy-efficiency-form/nema-energy-efficiency-form.component.html
- src/app/fsat/fan-field-data/fan-field-data.component.html
- src/app/psat/field-data/field-data.component.html
connects #5668 
we already have our own version of input min/max validation, so we don't need to depend on the browser's built-in validation
> fix min=1/min=0.1 forms causing increments to bork

- src/app/calculator/steam/pipe-insulation-reduction/pipe-insulation-reduction.service.ts
- src/app/indexedDb/settings-db.service.ts
- src/app/shared/helper-services/update-data.service.ts
#6026 
Situation: if !co2data exists, it is set from settings --> eaf emissions properties don't exist on old assessment settings
#6037 
Set mod utility cost from baseline
> Issue 6026 6037

- package-lock.json
- package.json
This still needs to be tested on someone elses machine, going from 1.2.3 to 1.2.4
> Rollback electron-builder to prevent installer breaking on different versions

- src/app/log-tool/log-tool-data.service.ts
- src/app/log-tool/visualize/visualize-graph/visualize-graph.component.ts
- src/app/log-tool/visualize/visualize.service.ts
#6108 
- meaningful change is in getAxisOptionGraphData()
- keeping comments
- also streamlined some logic and changed naming while trying to understand what was going on here.
> Issue 6108 - Fix doubled time-series segments when duplicate names present

- src/app/treasure-hunt/treasure-hunt-calculator-services/air-leak-treasure-hunt.service.ts
- src/app/treasure-hunt/treasure-hunt-calculator-services/ca-pressure-reduction-treasure-hunt.service.ts
- src/app/treasure-hunt/treasure-hunt-calculator-services/ca-reduction-treasure-hunt.service.ts
- src/app/treasure-hunt/treasure-hunt-calculator-services/cooling-tower-makeup-treasure-hunt.service.ts
- src/app/treasure-hunt/treasure-hunt-calculator-services/electricity-reduction-treasure-hunt.service.ts
- src/app/treasure-hunt/treasure-hunt-calculator-services/lighting-replacement-treasure-hunt.service.ts
- src/app/treasure-hunt/treasure-hunt-calculator-services/natural-gas-reduction-treasure-hunt.service.ts
- src/app/treasure-hunt/treasure-hunt-calculator-services/steam-reduction-treasure-hunt.service.ts
- src/app/treasure-hunt/treasure-hunt-calculator-services/water-reduction-treasure-hunt.service.ts
#6226 
We were assigning TH calc inputs from the saved ref, so changes were being saved even when the cancel was clicked
> Issue 6226 - TH calc that save when they shouldn't

- src/app/log-tool/visualize/visualize-graph/visualize-graph.component.ts
- src/app/log-tool/visualize/visualize-menu/visualize-menu.service.ts
- src/app/log-tool/visualize/visualize-menu/y-axis-data/y-axis-data.component.html
- src/app/log-tool/visualize/visualize-menu/y-axis-data/y-axis-data.component.ts
#6225 
- commented out filterTimeSeriesForSelectedY() - I don't know why this is no longer needed. Can't replicate the scenario that required this, but leaving the method for now.
- everything else is context comments/notes
> Issue 6225 - Remove filtering of axis data from time series segments

- src/app/calculator/furnaces/air-heating/air-heating-form/air-heating-form.component.html
- src/app/calculator/furnaces/air-heating/air-heating.component.html
- src/app/calculator/furnaces/air-heating/air-heating.component.ts
- src/app/calculator/furnaces/flue-gas/flue-gas.component.ts
- src/app/calculator/furnaces/heat-cascading/heat-cascading.component.html
- src/app/phast/phast-report/phast-input-summary/flue-gas-summary/flue-gas-summary.component.html
- src/app/suiteDb/custom-materials/custom-flue-gas-materials/custom-flue-gas-materials.component.html
- src/app/suiteDb/flue-gas-material/flue-gas-material.component.html
Connects #6296 
(also some of the chemical formulas had extra space between the subscripts so I changed those as well)
after change:
> Issue 6296: Heat Cascading Modal backdrop bug

- src/app/phast/phast-calculator-tabs/phast-calculator-tabs.component.html
> Issue 5720: Remove operating costs tab in phast calculators

- src/app/dashboard/sidebar/sidebar.component.ts
Connects #6281 
Previously , changing the dimensions of the app might have altered the sidebar width too much - so I just commented that code out so the sidebar length remains constant
> Issue 6281: Side bar too big

- src/app/shared/analytics/analytics.service.ts
I accidentally removed this check so http errors pile up trying to connect to the dev server. Harmless but annoying
> Fix http error - don't send test calls in dev

- src/app/log-tool/visualize/visualize-graph/visualize-graph.component.ts
- src/app/log-tool/visualize/visualize-menu/visualize-menu.component.css
- src/app/log-tool/visualize/visualize-menu/y-axis-data/y-axis-data.component.ts
- src/app/shared/models/plotting.ts
#6436 
- Fix broken use second axis flag
- restore css classes that were moved to outer scope (was being overridden)
> Issue 6436 - Add missing use second axis flag

- src/app/phast/losses/energy-input-exhaust-gas-losses/energy-input-exhaust-gas-form/energy-input-exhaust-gas-form.component.html
- src/app/phast/losses/energy-input-exhaust-gas-losses/energy-input-exhaust-gas-losses.component.html
- src/app/phast/losses/energy-input-exhaust-gas-losses/energy-input-exhaust-gas-losses.component.ts
- src/app/phast/losses/energy-input-exhaust-gas-losses/energy-input-exhaust-gas.service.ts
- src/app/phast/losses/losses-help/energy-input-exhaust-gas-losses-help/energy-input-exhaust-gas-losses-help.component.html
- src/app/phast/losses/losses-help/exhaust-gas-help/exhaust-gas-help.component.html
- src/app/phast/losses/operations/co2-savings-phast/co2-savings-phast.service.ts
- src/app/phast/phast-report/phast-input-summary/energy-input-exhaust-gas-summary/energy-input-exhaust-gas-summary.component.html
- src/app/phast/phast-report/results-data/results-data.component.html
- src/app/phast/phast-results.service.ts
- src/app/phast/phast.component.html
- src/app/phast/phast.service.ts
- src/app/shared/models/phast/losses/energyInputExhaustGasLosses.ts
- src/app/shared/models/phast/phast.ts
- src/app/tools-suite-api/process-heating-api.service.ts
#6538 #6536 #6526
Add electrical efficiency input, electrical heater losses result
remove/cleanup redundant form call to results
remove mx-auto causing sankey width problem
Change field names and help text
Stopped adding exhaust gas losses to "gross heat input"
Stop setting named result "input total" to "gross heat input" as a default value
Add results totalProvidedElectricalHeat, totalAdditionalFuelHeat
+ various name changes from 6536 and 6526
> Issue 6538, 6526, 6536

- src/app/calculator/utilities/unit-converter/unit-converter.component.html
- src/app/dashboard/copy-items/copy-items.component.css
- src/app/dashboard/copy-items/copy-items.component.html
- src/app/dashboard/copy-items/copy-items.component.ts
- src/app/dashboard/directory-dashboard/directory-dashboard-menu/directory-dashboard-menu.component.ts
- src/app/dashboard/move-items/move-items.component.ts
#6555 #6652 
- Allow copy directories
- Don't call reset directories from DB until changes are made - was overriding selected state
- Also fixes units calculator sorting is reversed
> Issue 6555 - Allow copy directories

- .github/workflows/main.yml
- .github/workflows/web.yml
- Updated runner labels used for deployment jobs to `prod` and `dev`
- Added job to deploy web builds to development environment if merging into `develop` branch
> Updated workflow files - added dev deploy, updated runner labels

- .github/workflows/web.yml
Piggybacking change: 
Update node setup step to dynamically set the node version based on the engine version of Node in `package.json`
> Updated web.yml - use dynamic node version setting for build job

- .github/workflows/web.yml
Missed change. `--legacy-peer-deps` flag must be used with `npm install` to resolve dependencies.
> Updated web.yml - add legacy-peer-deps flag for dependency resolution

- .github/workflows/web.yml
The following change appends the current commit's sha to the current `version` value in `package.json` which resolves #6683.
> [Resolves #6683] Updated web.yml - added step to append sha to package.json version

- package.json
Resolves #6835. 
Set build target architectures for both dmg and zip targets for MacOS to universal. The zip was set to universal due to otherwise providing only a zip of the architecture the build has been done on.
> Update mac build targets to universal architecture to support x86_64 and arm64

- src/app/update-toast/update-toast.component.ts
#6856 
This is causing the ghost error to display - I don't believe this is needed. Errors should be caught by the error sub defined on init...
> Remove updater download timeout

- src/app/ssmt/ssmt-diagram/flash-tank-diagram/flash-tank-diagram.component.ts
- src/app/tools-suite-api/steam-suite-api.service.ts
connects #6949 
The translation of the WASM binding was pointing one level too high for mediumPressureCondensateFlashTank. 
Fixed.
> Issue-6949 fix binding translation for mediumPressureCondensateFlashTank

- src/app/compressed-air-assessment/compressed-air-data-management.service.ts
- src/app/compressed-air-assessment/system-profile-graphs/system-profile-graphs.component.ts
- Fix bug when navigating away from system profile graphs in CA assessment
- Update system profile when control type is 'baseTrim'
connects #6969 
TODO: we need to update the logic for basetrim ordering to have the selected trim compressor be last. This isn't easily done given the current setup of the profile. Further work to come on this.
> Issue 6969

- .github/workflows/electron.yml
- .github/workflows/main.yml
- package.json
Automated building and packaging of Linux, Windows and MacOS builds
- Supports: automated notarization, release drafting and tagging
- Caveat: Windows must be signed separately for a given build at this time
- TODO: Implement automated .exe codesigning
Note on artifact uploading: assuming no files are found that are intended to be uploaded after a build, this will result in an error being thrown. Build artifacts are also retained for only 3 days as it stands as they're intended for a drafted release anyways.
> Implement automated desktop build pipeline

- src/app/app.component.ts
- src/app/shared/analytics/analytics.service.ts
- src/app/shared/analytics/analyticsEventTypes.ts
#6984 
- Change to new event name (fix bunk data in GA)
- Prevent measur_app_open_v2 being called twice in electron. Logic got a little circular when we built this up - I have a note on some improvements to be made hwen we look at this closer.
- Removed redundant method
> Issue 6984 - use new measur_app_open_v2

- .github/workflows/electron.yml
- .github/workflows/web.yml
Implements automation for signing Windows builds via Jsign. 
Additional changes: 
- Upgraded to usage of `upload-artifact@v4` and `download-artifact@v4` which implement artifact immutability
- Applies to both web and desktop pipelines
- Reduced compression for uploading build artifacts for desktop releases given the artifact contents
- Reduced artifact retention rules given artifacts are ultimately uploaded to releases
> Automate Windows build signing

- .github/workflows/electron.yml
[hotfix/automate-windows-build-signing 3dacbc577] Updated electron.yml - fix typo to use ggrep instead of grep since macos runner used by build job for desktop builds
> hotfix/automate-windows-build-signing - fix typo to use ggrep instead of grep

- .github/workflows/electron.yml
[hotfix/automate-windows-build-signing 87ab23162] Updated electron.yml - add cleanup of output dir on self hosted runner, fix sed formatting for macos
> hotfix/automate-windows-build-signing - add cleanup during setup and fix sed

- src/app/compressed-air-assessment/system-profile-graphs/system-profile-graphs.component.ts
> Issue 7096 - Fix skipped  falsy values in max/peak line traces

- src/app/tools-suite-api/compressed-air-suite-api.service.ts
#7250 
Control type is already an enum - do not convert.
Also checked other suite endpoints for same issue.
> Issue 7250 - CA Performance Profile bug

- src/app/compressed-air-assessment/compressed-air-assessment-results.service.ts
> Issue 7258 - Fix: percent cost savings equals savings divided by total baseline cost

- src/app/calculator/utilities/power-factor-triangle/power-factor-triangle-results/power-factor-triangle-results.component.ts
- src/app/calculator/utilities/power-factor-triangle/power-factor-triangle.service.ts
> Issue 7313: fixed validation bug in PF Triangle calc and graph

- src/app/calculator/furnaces/atmosphere/atmosphere-form/atmosphere-form.component.ts
- src/app/calculator/furnaces/charge-material/solid-material-form/solid-material-form.component.ts
- src/app/calculator/furnaces/fixture/fixture-form/fixture-form.component.ts
- src/app/core/core.service.ts
- src/app/indexedDb/solid-load-material-db.service.ts
- src/app/phast/explore-phast-opportunities/explore-phast-opportunities-form/explore-fixtures-form/explore-fixtures-form.component.ts
- src/app/phast/losses/charge-material/solid-charge-material-form/solid-charge-material-form.component.ts
- src/app/phast/losses/fixture-losses/fixture-losses-form/fixture-losses-form.component.ts
- src/app/phast/phast-report/phast-input-summary/charge-material-summary/charge-material-summary.component.ts
- src/app/phast/phast-report/phast-input-summary/fixture-summary/fixture-summary.component.ts
- src/app/shared/import-backup.service.ts
- src/app/shared/models/materials.ts
- src/app/suiteDb/custom-materials/custom-materials.service.ts
- src/app/suiteDb/solid-load-charge-material/solid-load-charge-material.component.ts
- src/app/tools-suite-api/sql-db-api.service.ts
connects #7714 
This pull request refactors how solid load charge materials are accessed and managed across several furnace calculator components. The main change is the migration from using the `SqlDbApiService` to the new `SolidLoadMaterialDbService`, which provides asynchronous, observable-based access to material data and supports default material initialization. Several synchronous methods are now asynchronous, and helper functions have been centralized for consistency.
**Migration to SolidLoadMaterialDbService and Asynchronous Data Access:**
* Replaced all uses of `SqlDbApiService` for solid load charge material queries (e.g., `selectSolidLoadChargeMaterials`, `selectSolidLoadChargeMaterialById`) with asynchronous methods from `SolidLoadMaterialDbService`, such as …
> Issue 7714: Remove SQLite suite calls for Solid Charge Materials

- .github/workflows/release_desktop.yml
- .gitignore
- .travis.yml
- README.md
- package.json
- travis_scripts/build.sh
- Output path for electron bundles revised: `../output/` to `output/`
- Relevant files updated to align with revision
- Codesigning revised in accordance to relocation
- Artifact naming and  artifact path updates
- Align upload-artifact steps to output path update
- Artifact names updated to clearly indicate purposes
> ci/codesigning-relocation - Relocate codesigning process

- .github/workflows/release_desktop.yml
Currently facing issues with the self-hosted build server following a system upgrade, so the proposed changes relocate building and desktop bundling to provided runners.
Split building `dist/` and bundling `output/` into separate jobs.
> Refactor for split bundling on provided runners

- .github/workflows/release_desktop.yml
Using the default shell from the `windows-2025` causes the `bundle_win` workflow to error out upon reaching the `Bundle` step. Resolution of this can be done via switching the shell the step uses to `bash` in similar fashion to setting the shell to `bash` for the `*npm-setup` anchor.
> FIX: windows bundle shell switch

- src/app/calculator/steam/pipe-insulation-reduction/pipe-insulation-reduction-form/pipe-insulation-reduction-form.component.html
- src/app/calculator/steam/pipe-insulation-reduction/pipe-insulation-reduction-form/pipe-insulation-reduction-form.component.ts
- src/app/calculator/steam/pipe-insulation-reduction/pipe-insulation-reduction.service.ts
connects #7796 
This pull request introduces validation for the average temperature in the Pipe Insulation Reduction calculator, ensuring that the average of the pipe and ambient temperatures does not exceed the maximum allowed for certain insulation materials. It also updates the UI to display relevant validation errors and ensures calculations are only performed when inputs are valid.
**Validation logic and calculation updates:**
* Added average temperature validation to the form, restricting the average of pipe and ambient temperatures for specific insulation materials (e.g., glass and resin, polystyrene) according to their maximum allowed values, with unit conversion support. (`pipe-insulation-reduction.service.ts`)
* Implemented `setAverageTemperatureValidation` and …
> Issue 7796: Add validation for average temp in pipe insulation
