ORNL-AMO/AMO-Tools-Desktop

src/app/phast/convert-phast.service.ts
src/app/phast/losses/operations/co2-savings-phast/co2-savings-phast.component.ts
src/app/phast/phast-report/executive-summary/executive-summary.component.html
src/app/phast/phast-report/results-data/results-data.component.html
src/app/phast/phast-results.service.ts

Issue-4923: Add CO2 Emissions Results to PHAST

---

src/app/calculator/utilities/weather-bins/weather-bins-bar-chart/weather-bins-bar-chart.component.ts

Issue 4800: Add Bin table/matrix to Weather Binning Calculator

---

src/app/report-rollup/assessment-reports/assessment-reports.component.html
src/app/report-rollup/fsat-rollup/fsat-rollup.component.ts
src/app/report-rollup/phast-rollup/phast-rollup.component.ts
src/app/report-rollup/psat-rollup/psat-rollup.component.ts
src/app/report-rollup/treasure-hunt-rollup/treasure-hunt-rollup-print/treasure-hunt-rollup-print.component.html
src/app/report-rollup/treasure-hunt-rollup/treasure-hunt-rollup.component.ts
src/app/report-rollup/waste-water-rollup/waste-water-rollup.component.ts
src/app/shared/models/treasure-hunt.ts
src/app/treasure-hunt/operation-costs/operation-costs.component.ts
src/app/treasure-hunt/treasure-hunt-report/executive-summary/carbon-emissions-summary-table/carbon-emissions-summary-table.component.html
src/app/treasure-hunt/treasure-hunt-report/executive-summary/carbon-emissions-summary-table/carbon-emissions-summary-table.component.ts
src/app/treasure-hunt/treasure-hunt-report/executive-summary/executive-summary.component.html
src/app/treasure-hunt/treasure-hunt-report/report-graphs/report-graphs.component.html
src/app/treasure-hunt/treasure-hunt-report/treasure-hunt-report.component.ts
src/app/treasure-hunt/treasure-hunt-report/treasure-hunt-report.service.ts
src/app/waste-water/waste-water-analysis/energy-analysis/energy-analysis-table/energy-analysis-table.component.ts
src/app/waste-water/waste-water-analysis/energy-analysis/energy-analysis.component.html

Issue 5193 5213

---

src/app/report-rollup/fsat-rollup/fsat-rollup.component.ts
src/app/report-rollup/phast-rollup/phast-rollup.component.ts
src/app/report-rollup/psat-rollup/psat-rollup.component.ts
src/app/report-rollup/treasure-hunt-rollup/treasure-hunt-rollup-print/treasure-hunt-rollup-print.component.html
src/app/report-rollup/treasure-hunt-rollup/treasure-hunt-rollup.component.ts
src/app/treasure-hunt/treasure-hunt-report/report-graphs/report-graphs.component.html
src/app/waste-water/waste-water-analysis/energy-analysis/energy-analysis-table/energy-analysis-table.component.ts
src/app/waste-water/waste-water-analysis/energy-analysis/energy-analysis.component.html

connects #5193 
all non treasure hunt related rollup printing errors have been addressed

Issue 5193: Rollup Report Printing Errors

---

src/app/shared/models/treasure-hunt.ts
src/app/treasure-hunt/operation-costs/operation-costs.component.ts
src/app/treasure-hunt/treasure-hunt-report/executive-summary/carbon-emissions-summary-table/carbon-emissions-summary-table.component.html
src/app/treasure-hunt/treasure-hunt-report/executive-summary/carbon-emissions-summary-table/carbon-emissions-summary-table.component.ts
src/app/treasure-hunt/treasure-hunt-report/executive-summary/executive-summary.component.html
src/app/treasure-hunt/treasure-hunt-report/treasure-hunt-report.component.ts
src/app/treasure-hunt/treasure-hunt-report/treasure-hunt-report.service.ts

Issue-5213: Treasure Hunt rollup report errors

---

src/app/shared/assessment-co2-savings/assessment-co2-savings.component.ts

Issue-5219: TH kg/MWh to kg/kWh conversions fixed

---

src/app/calculator/utilities/co2-savings/co2-savings.service.ts
src/app/examples/mockSsmt.ts
src/app/shared/assessment-co2-savings/assessment-co2-savings.service.ts
src/app/shared/models/settings.ts
src/app/shared/models/steam/ssmt.ts
src/app/shared/models/steam/steam-outputs.ts
src/app/ssmt/help-panel/operations-help/operations-help.component.html
src/app/ssmt/operations/general-operations/general-operations.component.css
src/app/ssmt/operations/general-operations/general-operations.component.html
src/app/ssmt/operations/operating-costs/operating-costs.component.html
src/app/ssmt/operations/operations.component.html
src/app/ssmt/operations/operations.component.ts
src/app/ssmt/operations/operations.module.ts
src/app/ssmt/ssmt-diagram-tab/diagram-summary-table/diagram-summary-table.component.html
src/app/ssmt/ssmt-diagram-tab/diagram-summary-table/diagram-summary-table.component.ts
src/app/ssmt/ssmt-diagram-tab/results-table/results-table.component.html
src/app/ssmt/ssmt-report/energy-summary/energy-summary.component.html
src/app/ssmt/ssmt-report/input-summary/operations-summary/operations-summary.component.html
src/app/ssmt/ssmt-report/input-summary/operations-summary/operations-summary.component.ts
src/app/ssmt/ssmt-results-panel/ssmt-results-panel/ssmt-results-panel.component.html
src/app/ssmt/ssmt-results-panel/ssmt-results-panel/ssmt-results-panel.component.ts
src/app/ssmt/ssmt.component.ts
src/app/ssmt/ssmt.service.ts

connects #4925 
add co2 savings to steam

Issue 4925

---

src/app/dashboard/directory-dashboard/directory-items/assessment-item/waste-water-summary-card/waste-water-summary-card.component.ts
src/app/dashboard/directory-dashboard/directory-summary/directory-summary.component.ts
src/app/examples/mockWasteWater.ts
src/app/report-rollup/waste-water-report-rollup.service.ts
src/app/shared/models/waste-water.ts
src/app/waste-water/modify-conditions/compare.service.ts
src/app/waste-water/results-panel/help-panel/operations-help/operations-help.component.html
src/app/waste-water/results-panel/results-table/results-table.component.html
src/app/waste-water/results-panel/results-table/results-table.component.ts
src/app/waste-water/waste-water-analysis/waste-water-analysis.service.ts
src/app/waste-water/waste-water-operations/waste-water-operations.component.html
src/app/waste-water/waste-water-operations/waste-water-operations.component.ts
src/app/waste-water/waste-water-report/input-data/input-data.component.html
src/app/waste-water/waste-water-report/input-data/input-data.component.ts
src/app/waste-water/waste-water-report/result-data/result-data.component.html
src/app/waste-water/waste-water-report/waste-water-report.component.ts
src/app/waste-water/waste-water.component.ts
src/app/waste-water/waste-water.module.ts
src/app/waste-water/waste-water.service.ts

connects #4926 
Add co2 emissions to waste water

Issue 4926

---

src/app/calculator/utilities/co2-savings/co2-savings-form/co2-savings-form.component.html
src/app/calculator/utilities/co2-savings/co2-savings-help/co2-savings-help.component.html
src/app/fsat/help-panel/fan-operations-help/fan-operations-help.component.html
src/app/motor-inventory/help-panel/help-panel.component.html
src/app/phast/losses/losses-help/operations-help/operations-help.component.html
src/app/phast/losses/operations/co2-savings-phast/co2-savings-phast.component.html
src/app/psat/help-panel/pump-operations-help/pump-operations-help.component.html
src/app/shared/assessment-co2-savings/assessment-co2-savings.component.html
src/app/ssmt/help-panel/operations-help/operations-help.component.html
src/app/treasure-hunt/operation-costs/operation-costs.component.html

Issue-5185: zip code spelling fix

---

src/app/calculator/waste-water/o2-utilization-rate/o2-utilization-rate-form/o2-utilization-rate-form.component.html
src/app/calculator/waste-water/o2-utilization-rate/o2-utilization-rate-help/o2-utilization-rate-help.component.html
src/app/calculator/waste-water/waste-water-list/waste-water-list.component.html
src/app/dashboard/assessment-create/assessment-create.component.html
src/app/dashboard/directory-dashboard/directory-dashboard-menu/content-controls/content-controls.component.html
src/app/dashboard/directory-dashboard/directory-summary/directory-summary.component.html
src/app/dashboard/landing-screen/landing-screen.component.html
src/app/dashboard/sidebar/calculator-list/calculator-list.component.html
src/app/report-rollup/report-rollup-units/report-rollup-units.component.html
src/app/report-rollup/report-summary/waste-water-summary/waste-water-summary.component.html
src/app/report-rollup/waste-water-rollup/effluent-energy-use-table/effluent-energy-use-table.component.html
src/app/report-rollup/waste-water-rollup/nutrient-removal-table/nutrient-removal-table.component.html
src/app/report-rollup/waste-water-rollup/waste-water-rollup-print/waste-water-rollup-print.component.html
src/app/report-rollup/waste-water-rollup/waste-water-rollup.component.html
src/app/settings/print-settings/print-settings.component.html
src/app/settings/treasure-hunt-settings/treasure-hunt-settings.component.html
src/app/shared/print-options-menu/print-options-menu.component.html
src/app/treasure-hunt/calculators/standalone-opportunity-sheet/opportunity-sheet-results/opportunity-sheet-results.component.html
src/app/treasure-hunt/find-treasure/find-treasure.component.html
src/app/treasure-hunt/operation-costs/operation-costs.component.html
src/app/treasure-hunt/treasure-chest/summary-card/summary-card.component.html
src/app/treasure-hunt/treasure-hunt-report/executive-summary/carbon-emissions-summary-table/carbon-emissions-summary-table.component.html
src/app/treasure-hunt/treasure-hunt-report/executive-summary/executive-summary-table/executive-summary-table.component.html
src/app/waste-water/waste-water-report/waste-water-report.component.html

issue #5232 spelling error corrections

---

src/app/ssmt/ssmt-diagram/blowdown-flash-tank/blowdown-flash-tank.component.html

Issue 5181 - Steam Blowdown Flashed results

---

angular.json
ngsw-config.json
package.json
src/app/app.module.ts
src/app/core/core.component.ts
src/app/tools-suite-api/sql-db-api.service.ts
src/environments/environment.prod.ts
src/index.html
src/main.ts
src/manifest.webmanifest

connects #4961
Adding PWA config
The dbInstance change also takes care of Module.Sqlite error from #5236 4931

Issue 4961

---

src/app/ssmt/ssmt-report/ssmt-report.component.css

Issue-5204

---

src/app/treasure-hunt/operation-costs/operation-costs.component.html
src/app/waste-water/results-panel/help-panel/operations-help/operations-help.component.html

Issue-5185: zip code spelling fixed

---

src/app/log-tool/visualize/visualize-menu/visualize-menu.service.ts

Issue 4846 - Default to markers option when not in time series

---

src/app/motor-inventory/motor-inventory-setup/motor-catalog/load-characteristic-data/load-characteristic-data.component.html
src/app/motor-inventory/motor-inventory-setup/motor-catalog/load-characteristic-data/load-characteristic-data.component.ts

Issue 5119 - Add motor power factor calculator to  catalog

---

src/app/dashboard/directory-dashboard/directory-items/inventory-item/motor-inventory-card/motor-inventory-card.component.ts

Issue-5175: Motor Inventory bug

---

src/app/shared/helper-services/update-data.service.ts

Prevent crash for user that has PHAST with no losses.

Prevent crash for user that has PHAST with no losses

---

src/app/calculator/process-cooling/cooling-tower/cooling-tower.service.ts

Issue 5225 Change temp difference conversion to  k --> R

---

src/app/phast/losses/operations/co2-savings-phast/co2-savings-phast.component.ts
src/app/shared/assessment-co2-savings/assessment-co2-savings.component.ts
src/app/treasure-hunt/operation-costs/operation-costs.component.ts

Issue-5219: TH and PH kg/MWh to kg/kWh conversion fixed

---

src/app/report-rollup/assessment-reports/assessment-reports.component.ts
src/app/report-rollup/compressed-air-report-rollup.service.ts
src/app/report-rollup/fsat-report-rollup.service.ts
src/app/report-rollup/phast-report-rollup.service.ts
src/app/report-rollup/psat-report-rollup.service.ts
src/app/report-rollup/report-rollup-models.ts
src/app/report-rollup/report-rollup-units/report-rollup-units.component.ts
src/app/report-rollup/report-rollup.component.ts
src/app/report-rollup/report-summary-graphs/report-summary-graphs.service.ts
src/app/report-rollup/report-summary/compressed-air-summary/compressed-air-summary.component.ts
src/app/report-rollup/report-summary/fsat-summary/fsat-summary.component.ts
src/app/report-rollup/report-summary/phast-summary/phast-summary.component.ts
src/app/report-rollup/report-summary/psat-summary/psat-summary.component.ts
src/app/report-rollup/report-summary/ssmt-summary/ssmt-summary.component.ts
src/app/report-rollup/report-summary/waste-water-summary/waste-water-summary.component.ts
src/app/report-rollup/ssmt-report-rollup.service.ts
src/app/report-rollup/waste-water-report-rollup.service.ts

connects #5038 
calculations for totals moved to assessment rollup services. 
Totals then used to build graph data

add calculation totals to assessment services

---

src/app/waste-water/waste-water-report/input-data/input-data.component.html

Hotfix for WW input summary

---

src/app/calculator/steam/steam.service.ts
src/app/calculator/steam/turbine/turbine-form/turbine-form.component.ts

connects #5273 
updates form validation for turbine quantities on changes
will need updated suite to fix calculation bug causing crash.

fixes to turbine form validation

---

src/app/compressed-air-assessment/compressed-air-report/executive-summary/executive-summary.component.ts

fix supply/demand list in CA report

---

src/app/compressed-air-assessment/explore-opportunities/add-receiver-volume/add-receiver-volume.component.css
src/app/compressed-air-assessment/explore-opportunities/add-receiver-volume/add-receiver-volume.component.html
src/app/compressed-air-assessment/explore-opportunities/adjust-cascading-set-points/adjust-cascading-set-points.component.css
src/app/compressed-air-assessment/explore-opportunities/adjust-cascading-set-points/adjust-cascading-set-points.component.html
src/app/compressed-air-assessment/explore-opportunities/improve-end-use-efficiency/improve-end-use-efficiency.component.css
src/app/compressed-air-assessment/explore-opportunities/improve-end-use-efficiency/improve-end-use-efficiency.component.html
src/app/compressed-air-assessment/explore-opportunities/reduce-air-leaks/reduce-air-leaks.component.css
src/app/compressed-air-assessment/explore-opportunities/reduce-air-leaks/reduce-air-leaks.component.html
src/app/compressed-air-assessment/explore-opportunities/reduce-run-time/reduce-run-time.component.css
src/app/compressed-air-assessment/explore-opportunities/reduce-run-time/reduce-run-time.component.html
src/app/compressed-air-assessment/explore-opportunities/reduce-system-air-pressure/reduce-system-air-pressure.component.css
src/app/compressed-air-assessment/explore-opportunities/reduce-system-air-pressure/reduce-system-air-pressure.component.html
src/app/compressed-air-assessment/explore-opportunities/use-automatic-sequencer/use-automatic-sequencer.component.css
src/app/compressed-air-assessment/explore-opportunities/use-automatic-sequencer/use-automatic-sequencer.component.html

add supply/demand label to the explore opps labels

---

src/app/compressed-air-assessment/compressed-air-assessment.service.ts
src/app/compressed-air-assessment/system-profile/system-profile-setup/operating-profile-table/operating-profile-table.component.css
src/app/compressed-air-assessment/system-profile/system-profile-setup/operating-profile-table/operating-profile-table.component.html

fix system profile validation

---

src/app/shared/helper-services/update-data.service.ts

Issue 5256 review update-data service for issues

---

src/app/calculator/furnaces/flue-gas/flue-gas.service.ts
src/app/phast/losses/flue-gas-losses/flue-gas-losses-form-mass/flue-gas-losses-form-mass.component.ts
src/app/phast/losses/flue-gas-losses/flue-gas-losses.component.ts
src/app/phast/phast-results.service.ts
src/app/phast/phast.service.ts
src/app/shared/models/phast/losses/flueGas.ts

connects #5061 
adds excess air and o2 calculations to flue gas by mass
creating issue for later consolidation of methods

calculate excess air and o2 in flue gas

---

src/app/calculator/fans/fan-analysis/convert-fan-analysis.service.ts
src/app/calculator/process-cooling/fan-psychrometric/fan-psychrometric.component.ts
src/app/calculator/process-cooling/fan-psychrometric/fan-psychrometric.service.ts
src/app/dashboard/assessment-create/assessment-create.component.ts
src/app/dashboard/assessment.service.ts

connects #5224 
fixes psychometric calculator in metric and fan assessments created in metric.
BaseGasDensity values that were not being displayed were not being converted on creation of defaults

Issue 5224

---

src/app/calculator/steam/stack-loss/stack-loss-form/stack-loss-by-volume/stack-loss-by-volume.component.html
src/app/calculator/steam/stack-loss/stack-loss-form/stack-loss-by-volume/stack-loss-by-volume.component.ts
src/app/calculator/steam/stack-loss/stack-loss.component.ts
src/app/calculator/steam/stack-loss/stack-loss.service.ts

connects #5250 
I went with solution 1

Issue-5250: updated stack loss calc

---

src/app/calculator/steam/prv/prv-help/prv-help.component.html

Issue 5257 - Calculator Text

---

src/app/calculator/compressed-air/compressed-air-pressure-reduction/compressed-air-pressure-reduction-results/compressed-air-pressure-reduction-results.component.html
src/app/calculator/furnaces/air-heating/air-heating-results/air-heating-results.component.html
src/app/calculator/furnaces/heat-cascading/heat-cascading-results/heat-cascading-results.component.html
src/app/calculator/furnaces/waste-heat/waste-heat-results/waste-heat-results.component.html
src/app/calculator/motors/replace-existing/replace-existing-results/replace-existing-results.component.html
src/app/calculator/steam/condensing-economizer/condensing-economizer-results/condensing-economizer-results.component.html
src/app/calculator/steam/feedwater-economizer/feedwater-economizer-results/feedwater-economizer-results.component.html
src/app/calculator/steam/water-heating/water-heating-results/water-heating-results.component.html
src/app/calculator/utilities/cash-flow/cash-flow-form/cash-flow-form.component.html
src/app/calculator/utilities/natural-gas-reduction/natural-gas-reduction-results/natural-gas-reduction-results.component.html
src/app/compressed-air-assessment/system-profile/system-profile-annual-summary/system-profile-annual-summary.component.html
src/app/dashboard/directory-dashboard/directory-items/assessment-item/ssmt-summary-card/ssmt-summary-card.component.html
src/app/dashboard/directory-dashboard/directory-items/assessment-item/waste-water-summary-card/waste-water-summary-card.component.html
src/app/dashboard/directory-dashboard/directory-items/inventory-item/motor-inventory-card/motor-inventory-card.component.html
src/app/phast/designed-energy/designed-energy-results/designed-energy-results.component.html
src/app/phast/metered-energy/metered-energy-results/metered-energy-results.component.html
src/app/report-rollup/phast-rollup/phast-rollup-energy-use-table/phast-rollup-energy-use-table.component.html
src/app/report-rollup/rollup-summary-table/rollup-summary-table.component.html
src/app/ssmt/ssmt-report/executive-summary/executive-summary.component.html
src/app/ssmt/ssmt-results-panel/ssmt-results-panel/ssmt-results-panel.component.html
src/app/treasure-hunt/operation-costs/operation-costs.component.html
src/app/waste-water/waste-water-analysis/energy-analysis/energy-analysis-table/energy-analysis-table.component.html

Issue 5248 - Annual Results

---

src/app/dashboard/copy-items/copy-items.component.ts
src/app/dashboard/directory-dashboard/directory-items/assessment-item/assessment-item.component.ts

Issue 5311 - CA Copy Assessment

---

src/app/compressed-air-assessment/explore-opportunities/add-receiver-volume/add-receiver-volume.component.css
src/app/compressed-air-assessment/explore-opportunities/add-receiver-volume/add-receiver-volume.component.html
src/app/compressed-air-assessment/explore-opportunities/adjust-cascading-set-points/adjust-cascading-set-points.component.css
src/app/compressed-air-assessment/explore-opportunities/adjust-cascading-set-points/adjust-cascading-set-points.component.html
src/app/compressed-air-assessment/explore-opportunities/improve-end-use-efficiency/improve-end-use-efficiency.component.css
src/app/compressed-air-assessment/explore-opportunities/improve-end-use-efficiency/improve-end-use-efficiency.component.html
src/app/compressed-air-assessment/explore-opportunities/reduce-air-leaks/reduce-air-leaks.component.css
src/app/compressed-air-assessment/explore-opportunities/reduce-air-leaks/reduce-air-leaks.component.html
src/app/compressed-air-assessment/explore-opportunities/reduce-run-time/reduce-run-time.component.css
src/app/compressed-air-assessment/explore-opportunities/reduce-run-time/reduce-run-time.component.html
src/app/compressed-air-assessment/explore-opportunities/reduce-system-air-pressure/reduce-system-air-pressure.component.css
src/app/compressed-air-assessment/explore-opportunities/reduce-system-air-pressure/reduce-system-air-pressure.component.html
src/app/compressed-air-assessment/explore-opportunities/use-automatic-sequencer/use-automatic-sequencer.component.css
src/app/compressed-air-assessment/explore-opportunities/use-automatic-sequencer/use-automatic-sequencer.component.html

update supply/demand labels in explore opps

---

src/app/fsat/fsat.service.ts

fix wet bulb calc, hard code specificHeatGas

---

src/app/dashboard/copy-items/copy-items.component.ts
src/app/dashboard/directory-dashboard/directory-items/assessment-item/assessment-item.component.ts
src/app/waste-water/explore-opportunities/explore-opportunities.component.html
src/app/waste-water/explore-opportunities/explore-opportunities.component.ts

Issue 5308 - Copy Assessment Include Mods

---

src/app/compressed-air-assessment/compressed-air-report/compressed-air-report.component.html
src/app/compressed-air-assessment/compressed-air-report/system-profiles/system-profiles.component.html
src/app/fsat/fsat-report/fsat-report.component.html
src/app/phast/phast-report/phast-report.component.html
src/app/psat/psat-report/psat-report.component.html
src/app/settings/print-settings/print-settings.component.html
src/app/settings/print-settings/print-settings.component.ts
src/app/shared/models/printing.ts
src/app/shared/models/settings.ts
src/app/shared/print-options-menu/print-options-menu.component.html
src/app/shared/print-options-menu/print-options-menu.service.ts
src/app/ssmt/ssmt-report/ssmt-report.component.html
src/app/waste-water/waste-water-report/waste-water-report.component.html

Issue 5329 - Assessment/Rollup Report Always Includes Current Tab in Printout

---

src/app/report-rollup/compressed-air-rollup/compressed-air-rollup.component.ts
src/app/report-rollup/rollup-summary-table/rollup-summary-table.component.html

Issue-5094: CA roll up table

---

src/app/shared/print-options-menu/print-options-menu.component.html

connects #5310 
temporarily removing the option to print system profiles per Kristina

Issue 5310 - CA Assessment and Rollup Printing

---

package-lock.json
package.json
src/app/report-rollup/report-summary-graphs/report-summary-graphs.component.html

- Bumps package as suggested from dependabot
- Removes leftover print var

update karma package, fix prod build template error

---

src/app/compressed-air-assessment/compressed-air-report/executive-summary/executive-summary.component.html
src/app/compressed-air-assessment/explore-opportunities/explore-opportunities-results/explore-opportunities-results.component.html

Issue 5249

---

src/app/phast/losses/energy-input-exhaust-gas-losses/energy-input-exhaust-gas-compare.service.ts
src/app/phast/losses/energy-input-exhaust-gas-losses/energy-input-exhaust-gas-form/energy-input-exhaust-gas-form.component.html
src/app/phast/losses/energy-input-exhaust-gas-losses/energy-input-exhaust-gas-form/energy-input-exhaust-gas-form.component.ts
src/app/phast/losses/energy-input-exhaust-gas-losses/energy-input-exhaust-gas-losses.component.html
src/app/phast/losses/energy-input-exhaust-gas-losses/energy-input-exhaust-gas-losses.component.ts
src/app/phast/losses/energy-input-exhaust-gas-losses/energy-input-exhaust-gas.service.ts
src/app/phast/losses/energy-input/energy-input.component.html
src/app/phast/losses/energy-input/energy-input.component.ts
src/app/phast/losses/losses-help/energy-input-exhaust-gas-losses-help/energy-input-exhaust-gas-losses-help.component.html
src/app/phast/phast-report/phast-input-summary/energy-input-exhaust-gas-summary/energy-input-exhaust-gas-summary.component.html
src/app/phast/phast-results.service.ts
src/app/shared/models/phast/losses/energyInputExhaustGasLosses.ts

connects #5340 
1. Electrical power input - unused, remove
2. Electrical heat delivered 
- if negative show dashes
- Show error msg

Issue 5340 - EAF form input/result changes

---

src/app/ssmt/ssmt-diagram-tab/ssmt-diagram-tab.component.css
src/app/ssmt/ssmt-diagram-tab/ssmt-diagram-tab.component.html
src/app/ssmt/ssmt-diagram-tab/ssmt-diagram-tab.component.ts

Issue 2632- SSMT Diagram - Collapse Help

---

src/app/phast/phast-report/energy-used/energy-used.component.ts
src/app/phast/phast-results.service.ts
src/app/report-rollup/phast-report-rollup.service.ts
src/app/report-rollup/phast-rollup/phast-rollup-energy-table/phast-rollup-energy-table.component.html
src/app/report-rollup/phast-rollup/phast-rollup-energy-table/phast-rollup-energy-table.component.ts
src/app/report-rollup/phast-rollup/phast-rollup-energy-use-table/phast-rollup-energy-use-table.component.html
src/app/report-rollup/phast-rollup/phast-rollup-energy-use-table/phast-rollup-energy-use-table.component.ts
src/app/report-rollup/phast-rollup/phast-rollup.component.ts
src/app/report-rollup/rollup-summary-pie-chart/rollup-summary-pie-chart.component.ts
src/app/shared/models/phast/phast.ts

connects #5283 
- Integrate Electrotech and EAF results in rollup and rollup summary graphs
- Add constant heating value for natural gas
Opened issue 5354 found during testing

Issue 5283 Integrate EAF and Electrotech with Rollup

---

src/app/shared/models/steam/steam-outputs.ts
src/app/ssmt/ssmt-diagram-tab/diagram-summary-table/diagram-summary-table.component.html
src/app/ssmt/ssmt-report/energy-summary/energy-summary.component.html
src/app/ssmt/ssmt.service.ts

connects #5326 
- Add 'from selling' and 'from change' results to steam diagram and report
- Add energy summary section for new results

Issue 5326 Change Steam emissions

---

src/app/report-rollup/rollup-summary-table/rollup-summary-table.component.html

Issue-5094: CA rollup table

---

src/app/report-rollup/report-summary-graphs/report-summary-graphs-print/report-summary-graphs-print.component.css
src/app/report-rollup/report-summary-graphs/report-summary-graphs-print/report-summary-graphs-print.component.html

Issue-5309: Roll up printing Misc

---

src/app/phast/losses/operations/co2-savings-phast/co2-savings-phast.service.ts
src/app/phast/phast-report/executive-summary.service.ts

connects #5325
Fix cost and convert emissions to tonne

Issue 5325 Additional EAF fixes

---

src/app/compressed-air-assessment/explore-opportunities/explore-opportunities-results/explore-opportunities-results.component.html
src/app/ssmt/ssmt-results-panel/ssmt-results-panel/ssmt-results-panel.component.html

connects #5249 #5326 
Label changes in steam and CA

Issue 5249, 5326 Change steam and CA labels

---

src/app/compressed-air-assessment/compressed-air-assessment-results.service.ts
src/app/compressed-air-assessment/compressed-air-report/executive-summary/executive-summary.component.html
src/app/compressed-air-assessment/compressed-air-report/payback-period/payback-period.component.css
src/app/compressed-air-assessment/compressed-air-report/payback-period/payback-period.component.html

connects #4648 
updates to compressed air payback period table from feedback
graphs already added

Issue 4648

---

src/app/compressed-air-assessment/compressed-air-report/executive-summary/executive-summary.component.html

Issue 5361- More Annual Results

---

package-lock.json

update package lock to test ci build

---

src/app/examples/mockTreasureHunt.ts
src/app/phast/losses/operations/co2-savings-phast/co2-savings-phast.component.ts
src/app/shared/assessment-co2-savings/assessment-co2-savings.component.ts
src/app/shared/convert-units/convert-units.service.ts
src/app/ssmt/convert-ssmt.service.ts
src/app/treasure-hunt/convert-input-data.service.ts
src/app/treasure-hunt/operation-costs/operation-costs.component.ts

#5382 
Use inverted energy conversion for steam and th

Issue 5382 Inverted energy conversion for SSMT and TH

---

src/app/phast/convert-phast.service.ts
src/app/phast/losses/operations/co2-savings-phast/co2-savings-phast.service.ts
src/app/phast/phast-report/energy-used/energy-used.component.html
src/app/phast/phast-report/results-data/results-data.component.html
src/app/phast/phast-results.service.ts
src/app/shared/models/phast/phast.ts

connects #5325 
- electrode emissions is missing a conversion
- electrode use and electrode energy use are different values

Issue 5325 Electrode emissions needs conversion

---

src/app/compressed-air-assessment/compressed-air-assessment-results.service.ts

Issue 5196 & 5195: Compressed Air: Isentropic efficiency

---

src/app/calculator/furnaces/furnaces-list/furnaces-list.component.html
src/app/phast/phast-calculator-tabs/phast-calculator-tabs.component.html
src/app/phast/phast.component.html

Issue-3007 efficiency improvement calculator shall henceforth be hidden

---

src/app/ssmt/header/header.service.ts

Issue 5371- Steam New Assessment Bug

---

package.json

Issue 5426 add electron-builder ignore files

---

src/app/waste-water/waste-water-operations/waste-water-operations.component.html

Issue 5430 - Highlight Differences from BL - Waste Water

---

src/app/fsat/fan-field-data/fan-field-data.component.html

Issue 5431 - Highlight Differences from BL - Fans

---

src/app/fsat/operations/operations.component.html
src/app/psat/pump-operations/pump-operations.component.html

#5440 
Fix Angular showing native validation

Issue 5440 Fix Angular showing native validation

---

src/app/examples/mockMotorInventoryData.ts

Issue 5423 - Agitator Typo in Motor Inventory

---

src/app/compressed-air-assessment/compressed-air-assessment-results.service.ts
src/app/compressed-air-assessment/compressed-air-report/payback-period/payback-period.component.html

update payback details aux power incorportation

---

src/app/settings/assessment-settings/reset-data-modal/reset-data-modal.component.html

don't force check reset examples if delete user assessments selected

---

src/app/calculator/compressed-air/air-leak/air-leak-form/orifice-method-form/orifice-method-form.component.html
src/app/calculator/compressed-air/air-leak/convert-air-leak.service.ts

desktop changes for suite issue 644:
https://github.com/ORNL-AMO/AMO-Tools-Suite/issues/644

change supply pressure to psig (orrifice method)

---

src/app/waste-water/aerator-performance-form/aerator-performance-form.component.html
src/app/waste-water/aerator-performance-form/aerator-performance-form.component.ts
src/app/waste-water/explore-opportunities/explore-opportunities-form/explore-aerator-form/explore-aerator-form.component.html
src/app/waste-water/explore-opportunities/explore-opportunities-form/explore-aerator-form/explore-aerator-form.component.ts
src/app/waste-water/results-panel/results-table/results-table.component.html
src/app/waste-water/waste-water-banner/modify-conditions-tabs/modify-conditions-tabs.component.html
src/app/waste-water/waste-water-banner/setup-tabs/setup-tabs.component.html
src/app/waste-water/waste-water-report/input-data/input-data.component.html
src/app/waste-water/waste-water-report/result-data/result-data.component.html

connects #5435 
updates labels for Aerator in wastewater to include Blower case

Issue 5435

---

src/app/settings/print-settings/print-settings.component.html
src/app/settings/print-settings/print-settings.component.ts
src/app/shared/print-options-menu/print-options-menu.component.html

Issue-5378: Tidy global print settings

---

src/app/compressed-air-assessment/inventory/generic-compressor-modal/compressor-options-table/compressor-options-table.component.html

update compressor option table to fix select bug

---

src/app/phast/losses/charge-material/charge-material-compare.service.ts
src/app/phast/losses/charge-material/charge-material.component.html
src/app/phast/losses/charge-material/charge-material.component.ts
src/app/phast/losses/flue-gas-losses/flue-gas-compare.service.ts

Issue 5364 - Highlight Differences from BL - PHAST

---

src/app/ssmt/compare.service.ts

Issue 5461 - Highlight Differences from BL - Steam

---

src/app/calculator/steam/steam.service.ts
src/app/shared/models/steam/steam-outputs.ts
src/app/shared/ssmt-sankey/ssmt-sankey.component.html
src/app/shared/ssmt-sankey/ssmt-sankey.component.ts
src/app/ssmt/calculate-losses.service.ts
src/app/ssmt/ssmt-report/ssmt-report.component.ts
src/app/ssmt/ssmt.component.html
src/app/ssmt/ssmt.component.ts
src/app/ssmt/ssmt.service.ts

connects #5369 
There's a version of this where we only need to change two files to add the behavior subject/error messaging and a mock empty results unit full of 0's. Steam doesn't handle the 0's very well visually --> so I think this solution is the best way, combining bs error message with the style of checking Rachel's branch has

Issue 5369 Add steam modeler error results and msg

---

src/app/phast/losses/charge-material/charge-material-compare.service.ts

Issue 5364 - Hotfix for new PHAST assessment

---

src/app/compressed-air-assessment/compressed-air-report/performance-profiles/performance-profiles.component.css

Issue-5335: Performance Profile graphs

---

src/app/dashboard/sidebar/calculator-list/calculator-list.component.html

Issue 3007

---

src/app/fsat/fan-field-data/fan-field-data.component.html
src/app/fsat/fan-field-data/fan-field-data.component.ts
src/app/fsat/fan-field-data/fan-field-data.service.ts
src/app/shared/models/fans.ts

user defined compressibility factor and inlet velocity pressure for fans

---

src/app/compressed-air-assessment/compressed-air-assessment.component.html
src/app/fsat/compare.service.ts
src/app/fsat/fsat.component.html
src/app/fsat/fsat.component.ts
src/app/phast/phast.component.html
src/app/phast/phast.component.ts
src/app/psat/psat.component.html
src/app/psat/psat.component.ts
src/app/ssmt/ssmt.component.html
src/app/ssmt/ssmt.component.ts
src/app/waste-water/waste-water.component.html

bugs in assessments when deleting modification in modal
connects #5481

fix for 5481 bug

---

package.json
src/app/dashboard/sidebar/version-modal/version-modal.component.html

update version modal and build commands
connects #5496

update version modal

---

src/app/fsat/compare.service.ts
src/app/fsat/modify-conditions/modify-conditions-tabs/modify-conditions-tabs.component.ts
src/app/fsat/operations/operations.component.html
src/app/fsat/operations/operations.component.ts
src/app/shared/assessment-co2-savings/assessment-co2-savings.component.css
src/app/shared/assessment-co2-savings/assessment-co2-savings.component.html
src/app/shared/assessment-co2-savings/assessment-co2-savings.component.ts
src/app/shared/assessment-co2-savings/assessment-co2-savings.service.ts

Issue 5500 - Highlight differences from BL - Co2 FSAT

---

src/app/treasure-hunt/treasure-hunt-report/opportunity-summary/opportunity-summary-copy-table/opportunity-summary-copy-table.component.css
src/app/treasure-hunt/treasure-hunt-report/opportunity-summary/opportunity-summary-copy-table/opportunity-summary-copy-table.component.html
src/app/treasure-hunt/treasure-hunt-report/opportunity-summary/opportunity-summary-copy-table/opportunity-summary-copy-table.component.ts
src/app/treasure-hunt/treasure-hunt-report/treasure-hunt-report.module.ts

Issue-3321: TH Tracking

---

src/app/calculator/furnaces/flue-gas/flue-gas-form-mass/flue-gas-form-mass.component.html
src/app/calculator/furnaces/flue-gas/flue-gas-form-mass/flue-gas-form-mass.component.ts
src/app/calculator/furnaces/flue-gas/flue-gas-form-volume/flue-gas-form-volume.component.html
src/app/calculator/furnaces/flue-gas/flue-gas-form-volume/flue-gas-form-volume.component.ts
src/app/calculator/furnaces/flue-gas/flue-gas-form.service.ts
src/app/calculator/furnaces/flue-gas/flue-gas.component.ts
src/app/calculator/furnaces/flue-gas/flue-gas.service.ts

connects #5401 
this is the issue for the default values and higher heating value.

Issue-5401: Flue Gas Calc Help improvement

---

src/app/phast/losses/energy-input-exhaust-gas-losses/energy-input-exhaust-gas-losses.component.ts
src/app/phast/losses/energy-input/energy-input-form/energy-input-form.component.html
src/app/phast/losses/energy-input/energy-input-form/energy-input-form.component.ts
src/app/phast/losses/energy-input/energy-input.component.html
src/app/phast/losses/energy-input/energy-input.component.ts
src/app/phast/losses/losses-tabs/energy-input-tab/energy-input-tab.component.ts
src/app/phast/phast-results.service.ts

Issue 5485: Additional EAF Validation

---

src/app/dashboard/directory-dashboard/directory-items/assessment-item/ssmt-summary-card/ssmt-summary-card.component.html
src/app/dashboard/directory-dashboard/directory-items/assessment-item/ssmt-summary-card/ssmt-summary-card.component.ts
src/app/dashboard/directory-dashboard/directory-summary/directory-summary.component.ts

Issue 5497 - Steam in Folder Summary

---

src/app/compressed-air-assessment/system-profile-graphs/system-profile-graphs.component.html

Issue 5509 - Profile Summary Graphs Styling

---

package-lock.json
package.json

Fixes a globally scoped call in one of our third party dependencies

Fix Develop build - Update types to satisfy 3rd party deps, (moment)

---

src/app/dashboard/assessment.service.ts
src/app/examples/mockWasteWater.ts
src/app/shared/helper-services/update-data.service.ts
src/app/shared/models/waste-water.ts
src/app/waste-water/activated-sludge-form/activated-sludge-form.component.html
src/app/waste-water/activated-sludge-form/activated-sludge-form.component.ts
src/app/waste-water/activated-sludge-form/activated-sludge-form.service.ts
src/app/waste-water/modify-conditions/compare.service.ts
src/app/waste-water/results-panel/help-panel/activated-sludge-help/activated-sludge-help.component.html
src/app/waste-water/waste-water.service.ts

Issue 5436 - WW Influent CBOD5 help text

---

src/app/waste-water/aerator-performance-form/aerator-performance-form.component.html
src/app/waste-water/aerator-performance-form/aerator-performance-form.component.ts
src/app/waste-water/explore-opportunities/explore-opportunities-form/explore-aerator-form/explore-aerator-form.component.ts

Issue 5529 - WW SOTR field not saving input

---

src/app/waste-water/waste-water-banner/waste-water-banner.component.html

Issue 5536 - WW Assessment tab styling

---

src/app/phast/losses/flue-gas-losses/flue-gas-compare.service.ts
src/app/phast/losses/flue-gas-losses/flue-gas-losses-form-volume/flue-gas-losses-form-volume.component.html
src/app/phast/losses/flue-gas-losses/flue-gas-losses-form-volume/flue-gas-losses-form-volume.component.ts

Issue 5364 - Highlight differences from BL PHAST

---

src/app/log-tool/system-setup/clean-data/clean-data.component.ts

parsing of time field in data explorer causing issues. Commented code
connects #5574

fix for time field selection in data explorer

---

src/app/compressed-air-assessment/centrifugal-graph/centrifugal-graph.component.ts
src/app/compressed-air-assessment/inventory-performance-profile/inventory-performance-profile.component.html
src/app/compressed-air-assessment/inventory-performance-profile/inventory-performance-profile.component.ts

#5561 
Display perf profiles and centrifugal graphs at the correct times

Issue 5561

---

src/app/treasure-hunt/treasure-hunt-calculator-services/pipe-insulation-treasure-hunt.service.ts

#5554 
Check baseline utility type in pipe insulation

Issue 5554

---

src/app/treasure-hunt/treasure-hunt-report/treasure-hunt-ppt.service.ts
src/app/treasure-hunt/treasure-hunt-report/treasure-hunt-report.component.ts

Issue 5583 : TH- PPT report

---

src/app/compressed-air-assessment/explore-opportunities/explore-opportunities.component.ts
src/app/dashboard/import-export/export.service.ts

connects #5589 
fixes bug when naming modification
delete data explorer data on export to reduce file size

CA Quick Fixes

---

src/app/calculator/process-cooling/fan-psychrometric/fan-psychrometric-chart/fan-psychrometric-chart.component.ts

Tighten up resolution for generating user red trace

---

main.js
package.json
src/app/dashboard/sidebar/version-modal/version-modal.component.html

update release notes and version number for v1.0.1

---

src/app/treasure-hunt/treasure-hunt-report/treasure-hunt-ppt.service.ts
src/app/treasure-hunt/treasure-hunt-report/treasure-hunt-report.component.ts

Issue 5576 - TH Report PPT: add Energy Utility Usage & Cost table

---

src/app/treasure-hunt/treasure-hunt-report/treasure-hunt-ppt.service.ts

replaced N/A's with dashes in TH PPT report
connects #5613

Issue 5613: Fix "N/A" in TH PPT report

---

src/app/calculator/compressed-air/air-leak/air-leak-form/air-leak-form.service.ts
src/app/calculator/compressed-air/compressed-air-constants.ts

Issue 5609: CA Update leak Survey Orifice Method example

---

src/app/calculator/motors/full-load-amps/full-load-amps.component.html
src/app/calculator/motors/full-load-amps/full-load-amps.component.ts
src/app/compressed-air-assessment/compressed-air-assessment.module.ts
src/app/compressed-air-assessment/inventory/nameplate-data/fla-modal/fla-modal.component.css
src/app/compressed-air-assessment/inventory/nameplate-data/fla-modal/fla-modal.component.html
src/app/compressed-air-assessment/inventory/nameplate-data/fla-modal/fla-modal.component.spec.ts
src/app/compressed-air-assessment/inventory/nameplate-data/fla-modal/fla-modal.component.ts
src/app/compressed-air-assessment/inventory/nameplate-data/nameplate-data.component.html
src/app/compressed-air-assessment/inventory/nameplate-data/nameplate-data.component.ts

Issue 5570 - Add FLA calc modal to CA inventory

---

src/app/treasure-hunt/convert-input-data.service.ts
src/app/treasure-hunt/system-basics/system-basics.component.ts

Issue 5573: Unit change messaging

---

src/app/calculator/process-cooling/chiller-performance/chiller-performance.component.html
src/app/calculator/utilities/weather-bins/weather-bins-bar-chart/weather-bins-bar-chart.component.html
src/app/calculator/utilities/weather-bins/weather-bins-bar-chart/weather-bins-bar-chart.component.ts
src/app/calculator/utilities/weather-bins/weather-bins-form/bins-form/bins-form.component.ts
src/app/calculator/utilities/weather-bins/weather-bins-form/parameter-unit/parameter-unit.component.html
src/app/calculator/utilities/weather-bins/weather-bins-table/weather-bins-table.component.html
src/app/calculator/utilities/weather-bins/weather-bins-table/weather-bins-table.component.ts
src/app/calculator/utilities/weather-bins/weather-bins.component.html
src/app/calculator/utilities/weather-bins/weather-bins.service.ts

#5626 
- Adding units for wet bulb, table lower and upper bound
- cleaning shared code and condensing in a few places

Issue 5626 - Add Wet bulb and lower/upper bound units to table

---

src/app/calculator/compressed-air/compressed-air-pressure-reduction/compressed-air-pressure-reduction-help/compressed-air-pressure-reduction-help.component.html

Issue 4523: Pressure Reduction Help Text additions

---

src/app/calculator/process-cooling/fan-psychrometric/fan-psychrometric-results/fan-psychrometric-results.component.html
src/app/calculator/process-cooling/fan-psychrometric/fan-psychrometric-results/fan-psychrometric-results.component.ts
src/app/calculator/process-cooling/fan-psychrometric/fan-psychrometric.service.ts
src/app/fsat/fsat-report/detailed-results/detailed-results.component.html
src/app/fsat/fsat-report/detailed-results/detailed-results.component.ts
src/app/phast/losses/flue-gas-losses/flue-gas-moisture-results/flue-gas-moisture-results.component.html
src/app/phast/losses/flue-gas-losses/flue-gas-moisture-results/flue-gas-moisture-results.component.ts
src/app/shared/gas-density-results/gas-density-results.component.html
src/app/shared/gas-density-results/gas-density-results.component.ts

#5596 
- Add results validation and hide results for psychrometric components

Issue 5596 - Psychrometric result validation

---

src/app/log-tool/log-tool-data.service.ts
src/app/log-tool/log-tool-models.ts
src/app/log-tool/system-setup/clean-data/clean-data.component.html
src/app/log-tool/system-setup/clean-data/clean-data.component.ts
src/app/log-tool/system-setup/help-panel/help-panel.component.html

Issue 5595: Data Explorer seconds getting lost

---

src/app/dashboard/assessment.service.ts
src/app/dashboard/import-export/export.service.ts

#5602 
Also changes a few param names I encountered earlier in the issue

Issue 5602 - Keep certain logtool data

---

src/app/calculator/compressed-air/receiver-tank/compressor-cycle-form/compressor-cycle-form.component.css
src/app/calculator/compressed-air/receiver-tank/compressor-cycle-form/compressor-cycle-form.component.html
src/app/calculator/compressed-air/receiver-tank/compressor-cycle-form/compressor-cycle-form.component.spec.ts
src/app/calculator/compressed-air/receiver-tank/compressor-cycle-form/compressor-cycle-form.component.ts
src/app/calculator/compressed-air/receiver-tank/compressor-cycle-help/compressor-cycle-help.component.css
src/app/calculator/compressed-air/receiver-tank/compressor-cycle-help/compressor-cycle-help.component.html
src/app/calculator/compressed-air/receiver-tank/compressor-cycle-help/compressor-cycle-help.component.spec.ts
src/app/calculator/compressed-air/receiver-tank/compressor-cycle-help/compressor-cycle-help.component.ts
src/app/calculator/compressed-air/receiver-tank/receiver-tank.component.html
src/app/calculator/compressed-air/receiver-tank/receiver-tank.component.ts
src/app/calculator/compressed-air/receiver-tank/receiver-tank.module.ts
src/app/calculator/compressed-air/receiver-tank/receiver-tank.service.ts
src/app/shared/models/standalone.ts

Issue 5317: CA Air Storage capacity Stand-alone

---

src/app/calculator/process-cooling/chiller-performance/chiller-performance-form/chiller-performance-form.component.html
src/app/calculator/process-cooling/chiller-performance/chiller-performance-help/chiller-performance-help.component.html
src/app/calculator/process-cooling/chiller-staging/chiller-staging-form/chiller-staging-form.component.html
src/app/calculator/process-cooling/chiller-staging/chiller-staging-help/chiller-staging-help.component.html
src/app/calculator/process-cooling/cooling-tower-basin/cooling-tower-basin-help/cooling-tower-basin-help.component.html
src/app/calculator/process-cooling/cooling-tower-basin/cooling-tower-basin-help/cooling-tower-basin-help.component.ts
src/app/calculator/process-cooling/cooling-tower-fan/cooling-tower-fan-form/cooling-tower-fan-form.component.html
src/app/calculator/process-cooling/cooling-tower-fan/cooling-tower-fan-help/cooling-tower-fan-help.component.html
src/app/calculator/process-cooling/cooling-tower/cooling-tower-form/cooling-tower-form.component.html
src/app/calculator/process-cooling/cooling-tower/cooling-tower-help/cooling-tower-help.component.html
src/app/calculator/utilities/weather-bins/weather-bins-form/bins-form/bins-form.component.html
src/app/calculator/utilities/weather-bins/weather-bins-form/bins-form/bins-form.component.ts
src/app/calculator/utilities/weather-bins/weather-bins-form/case-form/case-form.component.html
src/app/calculator/utilities/weather-bins/weather-bins-form/case-form/case-form.component.ts
src/app/calculator/utilities/weather-bins/weather-bins-form/data-setup-form/data-setup-form.component.html
src/app/calculator/utilities/weather-bins/weather-bins-form/data-setup-form/data-setup-form.component.ts
src/app/calculator/utilities/weather-bins/weather-bins-help/weather-bins-help.component.html
src/app/calculator/utilities/weather-bins/weather-bins-help/weather-bins-help.component.ts
src/app/calculator/utilities/weather-bins/weather-bins.service.ts
src/app/calculator/utilities/weather-bins/weather-db.service.ts

Help text update for process cooling and weather bins tab

Issue 5628

---

src/app/calculator/process-cooling/chiller-performance/chiller-performance-form/chiller-performance-form.component.ts
src/app/calculator/process-cooling/chiller-staging/chiller-staging-form/chiller-staging-form.component.ts

Waiting for word from Wei on whether we do want to switch the default cooler type from Centrifugal to Screw (third bullet point of #5652). This PR does not include that requested change.

#5652 Chiller Staging/Performance calc improvement

---

src/app/treasure-hunt/treasure-chest/import-opportunities.service.ts

fix TH import opps bug

---

src/app/calculator/furnaces/flue-gas/flue-gas-form.service.ts
src/app/phast/losses/flue-gas-losses/flue-gas-losses-form-mass/flue-gas-losses-form-mass.component.html
src/app/phast/losses/flue-gas-losses/flue-gas-losses-form-mass/flue-gas-losses-form-mass.component.ts
src/app/phast/losses/flue-gas-losses/flue-gas-losses-form-volume/flue-gas-losses-form-volume.component.html
src/app/phast/losses/flue-gas-losses/flue-gas-losses-form-volume/flue-gas-losses-form-volume.component.ts
src/app/shared/models/materials.ts
src/app/shared/models/phast/losses/flueGas.ts
src/app/suiteDb/solid-liquid-flue-gas-material/solid-liquid-flue-gas-material-help/solid-liquid-flue-gas-material-help.component.html
src/app/suiteDb/solid-liquid-flue-gas-material/solid-liquid-flue-gas-material.component.html
src/app/suiteDb/solid-liquid-flue-gas-material/solid-liquid-flue-gas-material.component.ts

Issue 5674: Update PHAST Flue Gas losses when sql db items deleted

---

src/app/calculator/furnaces/fixture/fixture-form.service.ts
src/app/phast/losses/atmosphere-losses/atmosphere-losses-form/atmosphere-losses-form.component.html
src/app/phast/losses/atmosphere-losses/atmosphere-losses-form/atmosphere-losses-form.component.ts
src/app/phast/losses/fixture-losses/fixture-losses-form/fixture-losses-form.component.html
src/app/phast/losses/fixture-losses/fixture-losses-form/fixture-losses-form.component.ts
src/app/phast/losses/fixture-losses/fixture-losses.component.ts
src/app/phast/losses/wall-losses/wall-losses-form/wall-losses-form.component.html
src/app/phast/losses/wall-losses/wall-losses-form/wall-losses-form.component.ts
src/app/shared/models/phast/losses/fixtureLoss.ts

Issue 5675: Update PHAST Fixture, Wall and Atmosphere losses when sql db items deleted

---

src/app/calculator/process-cooling/chiller-performance/chiller-performance-help/chiller-performance-help.component.html
src/app/calculator/process-cooling/cooling-tower-basin/cooling-tower-basin-help/cooling-tower-basin-help.component.html
src/app/calculator/process-cooling/cooling-tower-basin/cooling-tower-basin.component.html
src/app/calculator/process-cooling/process-cooling-list/process-cooling-list.component.html
src/app/calculator/utilities/weather-bins/weather-bins-help/weather-bins-help.component.html
src/app/calculator/utilities/weather-bins/weather-bins-help/weather-bins-help.component.ts
src/app/shared/weather-station-lookup/weather-station-lookup.component.ts

Issue 5628: Requested changes to help text

---

src/app/calculator/compressed-air/bleed-test/bleed-test-form/bleed-test-form.component.ts
src/app/calculator/compressed-air/bleed-test/bleed-test.service.ts
src/app/calculator/compressed-air/compressed-air-list/compressed-air-list.component.html

Issue 4248: fixes to CA bleed test calc

---

src/app/calculator/process-cooling/chiller-performance/chiller-performance-form.service.ts
src/app/calculator/process-cooling/chiller-performance/chiller-performance-form/chiller-performance-form.component.html
src/app/calculator/process-cooling/chiller-performance/chiller-performance-form/chiller-performance-form.component.ts
src/app/calculator/process-cooling/chiller-staging/chiller-staging-form.service.ts
src/app/calculator/process-cooling/chiller-staging/chiller-staging-form/chiller-staging-form.component.html
src/app/calculator/process-cooling/chiller-staging/chiller-staging-form/chiller-staging-form.component.ts
src/app/calculator/process-cooling/cooling-tower-basin/cooling-tower-basin-form.service.ts
src/app/calculator/process-cooling/cooling-tower-basin/cooling-tower-basin-form/cooling-tower-basin-form.component.html
src/app/calculator/process-cooling/cooling-tower-basin/cooling-tower-basin-form/cooling-tower-basin-form.component.ts
src/app/calculator/process-cooling/cooling-tower-basin/cooling-tower-basin.service.ts
src/app/calculator/process-cooling/cooling-tower-fan/cooling-tower-fan-form.service.ts
src/app/calculator/process-cooling/cooling-tower-fan/cooling-tower-fan-form/cooling-tower-fan-form.component.html
src/app/calculator/process-cooling/cooling-tower-fan/cooling-tower-fan-form/cooling-tower-fan-form.component.ts
src/app/calculator/process-cooling/cooling-tower-fan/cooling-tower-fan.service.ts
src/app/calculator/utilities/weather-bins/weather-bins-form/data-setup-form/data-setup-form.component.html

#5703 #5661
Adds updated validation to process cooling calculators

Issue 5703, 5661 Add validation for process cooling calculators

---

src/app/calculator/process-cooling/chiller-performance/chiller-performance-form.service.ts
src/app/calculator/process-cooling/chiller-performance/chiller-performance.component.html
src/app/calculator/process-cooling/chiller-performance/chiller-performance.component.ts
src/app/calculator/process-cooling/chiller-performance/chiller-performance.service.ts
src/app/calculator/process-cooling/chiller-staging/chiller-staging-form.service.ts
src/app/calculator/process-cooling/chiller-staging/chiller-staging.component.html
src/app/calculator/process-cooling/chiller-staging/chiller-staging.component.ts
src/app/calculator/process-cooling/cooling-tower-basin/cooling-tower-basin-results/cooling-tower-basin-results.component.html
src/app/calculator/process-cooling/cooling-tower-basin/cooling-tower-basin-results/cooling-tower-basin-results.component.ts
src/app/calculator/process-cooling/cooling-tower-basin/cooling-tower-basin.component.html
src/app/calculator/process-cooling/cooling-tower-basin/cooling-tower-basin.component.ts
src/app/calculator/process-cooling/cooling-tower-basin/cooling-tower-basin.service.ts
src/app/calculator/utilities/utilities-list/utilities-list.component.html
src/app/calculator/utilities/weather-bins/weather-bins-bar-chart/weather-bins-bar-chart.component.ts
src/app/shared/cooling-weather-chart/cooling-weather-chart.component.ts

#5634 #5707 #5716
Chiller Performance - hide weather integration
Chiller Staging - Make sure results panel width adjustment is hidden (5634)
Cooling tower basin 
- hiding table under graph
- total annual results shouldn't be undefined when has data
- graph resize on tab change
- selected bin on tab change
Weather - update descrp text -'Perform a bin analysis on TMY data to determine the number of hours per year that meet specific weather conditions'
Selected weather bin result will stay in memory when clicking between results/help tab, but not weather results/vs calculated results toggle, in which case I was unable to get angular change detection to pick it up

Issue 5634, 5707 - Various Process Cooling Fixes

---

src/app/calculator/compressed-air/bleed-test/bleed-test.service.ts

Issue 4248 Bleed test calculation correction

---

package-lock.json
package.json
src/app/dashboard/sidebar/version-modal/version-modal.component.html

Issue 5697 - Update release notes and version to 1.1.0

---

src/app/calculator/process-cooling/cooling-tower-fan/cooling-tower-fan-form/cooling-tower-fan-form.component.html

#5661 
access waterFlowRate control error

5661 access waterFlowRate control error

---

src/app/examples/mockFsat.ts
src/app/fsat/explore-opportunities/explore-opportunities-form/explore-opportunities-form.component.ts
src/app/fsat/fan-field-data/fan-field-data.component.ts
src/app/fsat/fan-field-data/fan-field-data.service.ts
src/app/fsat/fsat.service.ts

 Issue 5642: FSAT Field data - compressibility Factor isn't set properly on a new setup/assessment

---

src/app/fsat/fan-motor/fan-motor.component.html
src/app/fsat/fsat-fluid/fsat-fluid.component.html
src/app/fsat/operations/operations.component.html
src/app/psat/field-data/field-data.component.html
src/app/psat/motor/motor.component.html
src/app/psat/pump-fluid/pump-fluid.component.html
src/app/psat/pump-operations/pump-operations.component.html

#5668 pump/motor/fan number field steps

---

src/app/calculator/compressed-air/compressed-air-pressure-reduction/compressed-air-pressure-reduction-form/compressed-air-pressure-reduction-form.component.html
src/app/compressed-air-assessment/inventory/design-details/design-details.component.html
src/app/compressed-air-assessment/inventory/nameplate-data/nameplate-data.component.html
src/app/compressed-air-assessment/system-basics/system-basics.component.html
src/app/compressed-air-assessment/system-information/system-information.component.html

Arrow key - Compressed Air assessments #5669

---

src/app/treasure-hunt/calculators/opportunity-sheet/costs-form/costs-form.component.html
src/app/treasure-hunt/operation-costs/operation-costs.component.html

Arrow key - Treasure hunt #5684

---

src/app/waste-water/activated-sludge-form/activated-sludge-form.component.html
src/app/waste-water/aerator-performance-form/aerator-performance-form.component.html
src/app/waste-water/waste-water-operations/waste-water-operations.component.html

Arrow key - Wastewater #5670

---

src/app/motor-inventory/motor-inventory-setup/department-setup/department-setup.component.html
src/app/motor-inventory/motor-inventory-setup/motor-catalog/batch-analysis-data/batch-analysis-data.component.html
src/app/motor-inventory/motor-inventory-setup/motor-catalog/manual-specification-data/manual-specification-data.component.html
src/app/motor-inventory/motor-inventory-setup/motor-catalog/nameplate-data/nameplate-data.component.html
src/app/motor-inventory/motor-inventory-setup/motor-catalog/operations-data/operations-data.component.html
src/app/motor-inventory/motor-inventory-setup/motor-catalog/purchase-information-data/purchase-information-data.component.html
src/app/motor-inventory/motor-inventory-setup/motor-catalog/torque-data/torque-data.component.html
src/app/settings/application-settings/application-settings.component.html

Arrow key - Motor Inventory #5683

---

src/app/app.component.css
src/app/dashboard/sidebar/directory-item/directory-item.component.css
src/app/dashboard/sidebar/directory-item/directory-item.component.html
src/app/dashboard/sidebar/sidebar.component.css
src/app/dashboard/sidebar/sidebar.component.html
src/assets/styles/sidebar.css
src/assets/styles/two-panel.css

connects #5717
Purely visual modification

#5717 Visual improvement to side bar

---

src/app/examples/mockPsat.ts
src/app/psat/explore-opportunities/explore-opportunities.component.ts

fix what if scenario bug for PSAT example

---

.gitignore
README.md
package-lock.json
package.json
scripts/download-stats.ts

#5648 Download statistics

---

src/app/dashboard/about-page/about-page.component.html
src/app/dashboard/acknowledgments-page/acknowledgments-page.component.html
src/app/dashboard/contact-page/contact-page.component.html
src/app/settings/assessment-settings/assessment-settings.component.html
src/app/suiteDb/custom-materials/custom-materials.component.html
src/app/tutorials/tutorials.component.html

Connects #5753 
Merge this before pull #5754, I think it'll make the merge easier

Horizontal scrollbar exists when it shouldnt #5753

---

src/app/compressed-air-assessment/inventory/generic-compressor-modal/filter-compressors/filter-compressors.component.css
src/app/compressed-air-assessment/inventory/generic-compressor-modal/filter-compressors/filter-compressors.component.html
src/app/compressed-air-assessment/inventory/generic-compressor-modal/filter-compressors/filter-compressors.component.ts
src/app/motor-inventory/motor-inventory-banner/summary-filter/selected-options/selected-options.component.css
src/app/motor-inventory/motor-inventory-banner/summary-filter/selected-options/selected-options.component.html
src/app/motor-inventory/motor-inventory-banner/summary-filter/selected-options/selected-options.component.ts
src/app/motor-inventory/motor-inventory-setup/motor-catalog/select-motor-modal/filter-motors/filter-motors.component.css
src/app/motor-inventory/motor-inventory-setup/motor-catalog/select-motor-modal/filter-motors/filter-motors.component.html
src/app/motor-inventory/motor-inventory-setup/motor-catalog/select-motor-modal/filter-motors/filter-motors.component.ts
src/app/treasure-hunt/treasure-chest/treasure-chest-menu/treasure-chest-menu.component.css
src/app/treasure-hunt/treasure-chest/treasure-chest-menu/treasure-chest-menu.component.html

Issue 5666: Filter Reset btns

---

src/app/log-tool/system-setup/clean-data/clean-data.component.ts

Issue 5763 Data Explorer: add 3 second interval

---

src/app/calculator/process-cooling/fan-psychrometric/fan-psychrometric-chart/fan-psychrometric-chart.component.ts
src/app/calculator/process-cooling/fan-psychrometric/fan-psychrometric-table/fan-psychrometric-table.component.css
src/app/calculator/process-cooling/fan-psychrometric/fan-psychrometric-table/fan-psychrometric-table.component.html
src/app/calculator/process-cooling/fan-psychrometric/fan-psychrometric.component.css
src/app/calculator/process-cooling/fan-psychrometric/fan-psychrometric.component.html
src/app/calculator/process-cooling/fan-psychrometric/fan-psychrometric.service.ts

#5601
Cleaning this up a big before additional features are added
- Condensing logic for building lines
- Be DRY with units
- Cleaning up leftover naming that corresponded to colored lines
- Tightened up table styles

Issue 5601 - Psycrometric Chart

---

src/app/dashboard/about-page/about-page.component.html
src/app/settings/assessment-settings/assessment-settings.component.html
src/app/suiteDb/custom-materials/custom-atmosphere-specific-heat-materials/custom-atmosphere-specific-heat-materials.component.ts
src/app/suiteDb/custom-materials/custom-flue-gas-materials/custom-flue-gas-materials.component.ts
src/app/suiteDb/custom-materials/custom-gas-load-charge-materials/custom-gas-load-charge-materials.component.ts
src/app/suiteDb/custom-materials/custom-liquid-load-charge-materials/custom-liquid-load-charge-materials.component.ts
src/app/suiteDb/custom-materials/custom-materials.component.html
src/app/suiteDb/custom-materials/custom-materials.component.ts
src/app/suiteDb/custom-materials/custom-solid-liquid-flue-gas-materials/custom-solid-liquid-flue-gas-materials.component.ts
src/app/suiteDb/custom-materials/custom-solid-load-charge-materials/custom-solid-load-charge-materials.component.ts
src/app/suiteDb/custom-materials/custom-wall-losses-sufaces/custom-wall-losses-surfaces.component.ts

Issue 5742 and 5743: Custom materials dropdown

---

src/app/app.component.ts
src/app/fsat/fsat.component.html
src/app/fsat/fsat.component.ts
src/app/phast/phast.component.html
src/app/phast/phast.component.ts
src/app/psat/psat.component.html
src/app/psat/psat.component.ts
src/app/shared/fsat-sankey/fsat-sankey.component.ts
src/app/shared/phast-sankey/phast-sankey.component.ts
src/app/shared/psat-sankey/psat-sankey.component.ts
src/app/shared/ssmt-sankey/ssmt-sankey.component.ts
src/app/ssmt/ssmt.component.ts

Connects #5146 
(See notes on the aforementioned issue for details)

Retrofit FSAT/PSAT sankeys #5146

---

src/app/treasure-hunt/treasure-chest/treasure-chest-menu/treasure-chest-menu.component.html

Issue 5667 TH filter bar rearrangement

---

src/app/compressed-air-assessment/compressed-air-report/compressed-air-report.component.html
src/app/compressed-air-assessment/compressed-air-report/report-graphs/report-graphs.component.ts

#5773 
Use combinedDayTypeResults for report barchart

Issue-5773 CA report bar chart results

---

src/app/calculator/fans/fan-analysis/fan-analysis-form/gas-density-form/gas-density-form.component.ts
src/app/calculator/fans/fan-analysis/fan-analysis-form/gas-density-form/gas-density-form.service.ts
src/app/calculator/process-cooling/fan-psychrometric/fan-psychrometric.service.ts
src/app/calculator/process-cooling/process-cooling-list/process-cooling-list.component.html
src/app/phast/losses/flue-gas-losses/flue-gas-losses-moisture/flue-gas-losses-moisture.component.ts

#5781 
Psychrometric relativeHumidity method needs baromP validation, fix conflicting calc list order

Issue 5781 Psychrometric input freezing suite calculation

---

src/app/calculator/process-cooling/chiller-staging/chiller-staging-form/chiller-staging-form.component.html

connects #5785 
header was removed

issue 5785: PC Typo

---

src/app/calculator/utilities/co2-savings/co2-savings-form/co2FuelSavingsFuels.ts
src/app/phast/losses/operations/co2-savings-phast/co2-savings-phast.component.ts
src/app/ssmt/operations/operations.component.ts

#5556 
Add Hydrogren to other fuels, fix shouldSet output rate bug (strictly typed check for undefined)

Issue 5556 Add Other fuels hydrogen

---

src/app/phast/system-basics/system-basics.component.html
src/app/settings/phast-settings/phast-settings.component.html
src/app/settings/phast-settings/phast-settings.component.ts

#5784 
Remove unused rollup units, only set default units when changing ener…gy source or null

Issue 5784 PHAST custom units bugs

---

src/app/log-tool/log-tool-data.service.ts

fix log tool data item dropping bug

---

package-lock.json
src/app/compressed-air-assessment/compressed-air-assessment-results.service.ts

connects #5194 
fixes averages for annual profile summary to correctly use number of data points for averages.

Fixes Profile Annual summary

---

src/app/compressed-air-assessment/system-profile/profile-setup-form/profile-setup-form.component.html

fix interval dropdown order

---

src/app/compressed-air-assessment/compressed-air-assessment.service.ts

connects #5810 
adds max validation to profile for % power and % airflow

Issue 5810

---

package-lock.json
package.json
src/app/calculator/furnaces/waste-heat/waste-heat.service.ts
src/app/calculator/steam/condensing-economizer/condensing-economizer.service.ts
src/app/calculator/steam/feedwater-economizer/feedwater-economizer.service.ts
src/app/calculator/steam/water-heating/water-heating.service.ts
src/app/calculator/waste-water/state-point-analysis/state-point-analysis.service.ts
src/app/fsat/fan-field-data/fan-field-data.service.ts
src/app/fsat/fsat.service.ts
src/app/phast/phast.service.ts
src/app/psat/psat.service.ts
src/app/tools-suite-api/fans-suite-api.service.ts
src/app/tools-suite-api/svi-suite-api.service.spec.ts
src/app/tools-suite-api/svi-suite-api.service.ts
src/app/tools-suite-api/tools-suite-api.module.ts
src/index.html

connects #5814 
connects #5821 
removes all references to "Addon"
adds suite api service for SVI
fixes compressibility factor = null

Suite call fixes for SVI and Compressibility Factor

---

src/app/log-tool/system-setup/clean-data/clean-data.component.ts

Issue 5826 : Data Explorer: Add 4 second interval option

---

src/app/calculator/pumps/specific-speed/specific-speed-form/specific-speed-form.component.html

Issue 5548: User feedback: Stage specific speed correction

---

package-lock.json
src/app/suiteDb/solid-liquid-flue-gas-material/solid-liquid-flue-gas-material.component.ts

Connects #5752 
When reviewing, please see my comment in issue #5752 and triage as necessary.

#5752 Rounded conversions to/from percents

---

src/app/compressed-air-assessment/compressed-air-assessment.service.ts

fix validation when compressors are turned off in profile

---

src/assets/styles/utilities.css

Issue 5806: Lighting Icon Background

---

src/app/compressed-air-assessment/compressed-air-assessment.service.ts
src/app/log-tool/system-setup/clean-data/clean-data.component.html

Issue 5772

---

src/app/compressed-air-assessment/compressed-air-report/input-summary/end-use-summary/end-use-summary.component.html
src/app/examples/mockCompressedAirAssessment.ts

Issue 5841- New CA example

---

src/app/compressed-air-assessment/compressed-air-sankey/airflow-sankey/airflow-sankey.component.html
src/app/compressed-air-assessment/compressed-air-sankey/airflow-sankey/airflow-sankey.component.ts
src/app/compressed-air-assessment/compressed-air-sankey/airflow-sankey/airflow-sankey.service.ts
src/app/compressed-air-assessment/compressed-air-sankey/power-sankey/power-sankey.component.html
src/app/compressed-air-assessment/day-types/day-types.component.html
src/app/compressed-air-assessment/end-use-chart/end-use-chart.component.html
src/app/compressed-air-assessment/end-use-chart/end-use-chart.component.ts
src/app/compressed-air-assessment/end-uses/end-uses.service.ts
src/app/compressed-air-assessment/results-panel/end-use-table/end-use-table.component.html
src/app/compressed-air-assessment/results-panel/end-use-table/end-use-table.component.ts
src/app/shared/models/compressed-air-assessment.ts

Issue 5836, 5837 Validation additions, Restrict day type modifications

---

package-lock.json
package.json
src/app/dashboard/sidebar/version-modal/version-modal.component.html

Issue 5819

---

src/app/dashboard/acknowledgments-page/acknowledgments-page.component.html

#5862 - adding yours truly (& fixing bad html)

---

src/app/dashboard/dashboard.component.html
src/app/dashboard/dashboard.component.ts
src/app/dashboard/dashboard.service.ts
src/app/dashboard/landing-screen/measur/measur.component.css
src/app/dashboard/sidebar/sidebar.component.html
src/app/dashboard/sidebar/sidebar.component.ts

Review 5788 nick

---

src/app/dashboard/dashboard.component.css
src/app/dashboard/dashboard.component.html
src/app/dashboard/dashboard.component.ts
src/app/dashboard/dashboard.service.ts
src/app/dashboard/drag-bar/drag-bar.component.ts
src/app/dashboard/landing-screen/measur/measur.component.css
src/app/dashboard/sidebar/sidebar.component.css
src/app/dashboard/sidebar/sidebar.component.html
src/app/dashboard/sidebar/sidebar.component.ts

Issue 5788: Make side bar menu collapsible for phone/tablet screens

---

src/app/dashboard/dashboard.component.css
src/app/dashboard/dashboard.component.html
src/app/dashboard/dashboard.component.ts
src/app/dashboard/dashboard.service.ts
src/app/dashboard/sidebar/calculator-list/calculator-list.component.html
src/app/dashboard/sidebar/calculator-list/calculator-list.component.ts
src/app/dashboard/sidebar/sidebar.component.css
src/app/dashboard/sidebar/sidebar.component.html
src/app/dashboard/sidebar/sidebar.component.ts

Updates to previously merged #5788 
Add collapsed sidebar divider, collapse on route nav, 1024 or lower functionality.

Sidebar updates

---

src/app/calculator/compressed-air/compressed-air-list/compressed-air-list.component.html
src/app/calculator/fans/fans-list/fans-list.component.html
src/app/calculator/furnaces/furnaces-list/furnaces-list.component.html
src/app/calculator/lighting/lighting-list/lighting-list.component.html
src/app/calculator/motors/motors-list/motors-list.component.html
src/app/calculator/process-cooling/process-cooling-list/process-cooling-list.component.html
src/app/calculator/pumps/pumps-list/pumps-list.component.html
src/app/calculator/steam/steam-list/steam-list.component.html
src/app/calculator/utilities/utilities-list/utilities-list.component.html
src/app/calculator/waste-water/waste-water-list/waste-water-list.component.html

Issue 5870: Make Calculator Icons looks good in Mobile UI

---

src/app/calculator/compressed-air/compressed-air-pressure-reduction/compressed-air-pressure-reduction.component.html
src/app/calculator/compressed-air/compressed-air-pressure-reduction/compressed-air-pressure-reduction.component.ts
src/app/calculator/lighting/lighting-replacement/lighting-replacement.component.html
src/app/calculator/lighting/lighting-replacement/lighting-replacement.component.ts
src/app/calculator/pumps/head-tool/head-tool.component.css
src/app/calculator/pumps/head-tool/head-tool.component.html
src/app/calculator/pumps/head-tool/head-tool.component.ts

Issue 5881 Lighting calc, Pump Head Tool and Compresses Air Pressure Reduction

---

src/app/calculator/pumps/head-tool/head-tool-results/head-tool-results.component.ts
src/app/calculator/system-and-equipment-curve/system-and-equipment-curve.service.ts

Issue 5876 - Pump bugs

---

src/app/calculator/steam/pipe-insulation-reduction/pipe-insulation-reduction.component.html
src/app/calculator/steam/pipe-insulation-reduction/pipe-insulation-reduction.component.ts
src/app/calculator/steam/stack-loss/stack-loss.component.html
src/app/calculator/steam/stack-loss/stack-loss.component.ts

Issue 5890 - small screen styles for stack loss and pipe insulation

---

src/app/shared/operating-hours-modal/operating-hours-modal.component.ts

Issue 5893: operating hours modal for mobile UI 

---

src/app/calculator/motors/motor-performance/motor-performance.component.css
src/app/calculator/motors/motor-performance/motor-performance.component.html
src/app/calculator/motors/nema-energy-efficiency/nema-energy-efficiency.component.css
src/app/calculator/motors/nema-energy-efficiency/nema-energy-efficiency.component.html
src/app/calculator/pumps/achievable-efficiency/achievable-efficiency.component.css
src/app/calculator/pumps/achievable-efficiency/achievable-efficiency.component.html
src/app/calculator/pumps/specific-speed/specific-speed.component.css
src/app/calculator/pumps/specific-speed/specific-speed.component.html
src/app/calculator/system-and-equipment-curve/system-and-equipment-curve.component.css
src/app/calculator/system-and-equipment-curve/system-and-equipment-curve.component.html
src/app/psat/explore-opportunities/explore-opportunities.component.css
src/app/psat/explore-opportunities/explore-opportunities.component.html
src/app/psat/help-panel/help-panel.component.html
src/app/psat/modification-list/modification-list.component.html
src/app/psat/modify-conditions/modify-conditions-tabs/modify-conditions-tabs.component.html
src/app/psat/modify-conditions/modify-conditions.component.css
src/app/psat/modify-conditions/modify-conditions.component.html
src/app/psat/modify-conditions/modify-conditions.component.ts
src/app/psat/psat-banner/psat-banner.component.html
src/app/psat/psat-banner/psat-banner.component.ts
src/app/psat/psat-report/psat-report.component.html
src/app/psat/psat-report/psat-report.component.ts
src/app/psat/psat-tabs/psat-tabs.component.css
src/app/psat/psat-tabs/psat-tabs.component.html
src/app/psat/psat-tabs/psat-tabs.component.ts
src/app/psat/psat.component.css
src/app/psat/psat.component.html

Issue 5793: modify PSAT for phone/table UI

---

src/app/psat/modify-conditions/modify-conditions.component.css
src/app/psat/modify-conditions/modify-conditions.component.html
src/app/psat/modify-conditions/modify-conditions.component.ts

Fix mobile heights and scroll - update on resize

---

src/app/dashboard/acknowledgments-page/acknowledgments-page.component.html

Issue 5861 - Add Wahlberg to Acknowledgements

---

src/app/calculator/steam/pipe-insulation-reduction/pipe-insulation-reduction.component.html
src/app/calculator/steam/pipe-insulation-reduction/pipe-insulation-reduction.component.ts
src/app/calculator/steam/stack-loss/stack-loss.component.html
src/app/calculator/steam/stack-loss/stack-loss.component.ts
src/app/dashboard/sidebar/calculator-list/calculator-list.component.html

fix stack loss, pipe insulation heights, collapse sidebar on navigate

---

src/app/calculator/motors/motor-performance/motor-performance.component.css
src/app/calculator/motors/motor-performance/motor-performance.component.html
src/app/calculator/motors/motor-performance/motor-performance.component.ts
src/app/calculator/motors/nema-energy-efficiency/nema-energy-efficiency.component.css
src/app/calculator/motors/nema-energy-efficiency/nema-energy-efficiency.component.html
src/app/calculator/motors/nema-energy-efficiency/nema-energy-efficiency.component.ts
src/app/calculator/pumps/achievable-efficiency/achievable-efficiency.component.css
src/app/calculator/pumps/achievable-efficiency/achievable-efficiency.component.html
src/app/calculator/pumps/achievable-efficiency/achievable-efficiency.component.ts
src/app/calculator/pumps/specific-speed/specific-speed.component.css
src/app/calculator/pumps/specific-speed/specific-speed.component.html
src/app/calculator/pumps/specific-speed/specific-speed.component.ts
src/app/calculator/system-and-equipment-curve/system-and-equipment-curve.component.css
src/app/calculator/system-and-equipment-curve/system-and-equipment-curve.component.html
src/app/calculator/system-and-equipment-curve/system-and-equipment-curve.component.ts

Issue 5900: PSAT calcs for Mobile UI

---

src/app/calculator/motors/motor-performance/motor-performance.component.html
src/app/calculator/motors/motor-performance/motor-performance.component.ts
src/app/calculator/motors/nema-energy-efficiency/nema-energy-efficiency.component.html
src/app/calculator/motors/nema-energy-efficiency/nema-energy-efficiency.component.ts
src/app/calculator/pumps/achievable-efficiency/achievable-efficiency.component.html
src/app/calculator/pumps/achievable-efficiency/achievable-efficiency.component.ts
src/app/calculator/pumps/specific-speed/specific-speed.component.html
src/app/calculator/pumps/specific-speed/specific-speed.component.ts
src/app/calculator/system-and-equipment-curve/system-and-equipment-curve.component.html
src/app/calculator/system-and-equipment-curve/system-and-equipment-curve.component.ts
src/assets/styles/responsive-calculators.css

#5900 
hide full height scroll, timeout for orientation flip, restore bg colors

Issue 5900 Keep original styles with mobile

---

package.json
src/app/dashboard/sidebar/version-modal/version-modal.component.html

Issue 5889 - Version update

---

src/app/dashboard/dashboard.component.css

#5899
Return scroll bar track and more usable width to scrollbar

Issue 5899 revert scrollbar track changes from 5717

---

src/app/dashboard/acknowledgments-page/acknowledgments-page.component.html

Issue 5861 acknlowdgements position for Wahlberg

---

src/app/calculator/process-cooling/cooling-tower/cooling-tower-form/cooling-tower-form.component.html
src/app/calculator/process-cooling/cooling-tower/cooling-tower-results/cooling-tower-results.component.html
src/app/calculator/process-cooling/cooling-tower/cooling-tower.component.html
src/app/calculator/process-cooling/cooling-tower/cooling-tower.component.ts
src/app/calculator/process-cooling/cooling-tower/cooling-tower.service.ts
src/app/shared/models/chillers.ts
src/app/shared/models/treasure-hunt.ts
src/app/treasure-hunt/calculators/calculators.component.html
src/app/treasure-hunt/calculators/calculators.module.ts
src/app/treasure-hunt/calculators/calculators.service.ts
src/app/treasure-hunt/convert-input-data.service.ts
src/app/treasure-hunt/find-treasure/find-treasure.component.css
src/app/treasure-hunt/find-treasure/find-treasure.component.html
src/app/treasure-hunt/treasure-chest/export-opportunities/export-opportunities.component.html
src/app/treasure-hunt/treasure-chest/export-opportunities/export-opportunities.component.ts
src/app/treasure-hunt/treasure-chest/import-opportunities.service.ts
src/app/treasure-hunt/treasure-chest/opportunity-cards/opportunity-cards.component.css
src/app/treasure-hunt/treasure-chest/opportunity-cards/opportunity-cards.component.html
src/app/treasure-hunt/treasure-chest/opportunity-cards/opportunity-cards.service.ts
src/app/treasure-hunt/treasure-chest/opportunity-cards/sort-cards.service.ts
src/app/treasure-hunt/treasure-chest/treasure-chest-menu/calculator-type-dropdown/calculator-type-dropdown.component.ts
src/app/treasure-hunt/treasure-hunt-calculator-services/cooling-tower-makeup-treasure-hunt.service.spec.ts
src/app/treasure-hunt/treasure-hunt-calculator-services/cooling-tower-makeup-treasure-hunt.service.ts
src/app/treasure-hunt/treasure-hunt-calculator-services/treasure-hunt-opportunity.service.ts
src/app/treasure-hunt/treasure-hunt-report/opportunity-summary.service.ts
src/app/treasure-hunt/treasure-hunt.module.ts

connects #5761 
Add cooling tower makeup water to TH

Issue 5761 - Cooling tower in TH

---

src/app/calculator/process-cooling/chiller-staging/chiller-staging-form.service.ts
src/app/calculator/process-cooling/chiller-staging/chiller-staging-form/chiller-staging-form.component.html
src/app/calculator/process-cooling/chiller-staging/chiller-staging-help/chiller-staging-help.component.html
src/app/calculator/process-cooling/chiller-staging/chiller-staging-results/chiller-staging-results.component.html
src/app/calculator/process-cooling/chiller-staging/chiller-staging.component.html
src/app/calculator/process-cooling/chiller-staging/chiller-staging.component.ts
src/app/calculator/process-cooling/chiller-staging/chiller-staging.service.ts
src/app/shared/models/chillers.ts
src/app/shared/models/treasure-hunt.ts
src/app/treasure-hunt/calculators/calculators.component.html
src/app/treasure-hunt/calculators/calculators.module.ts
src/app/treasure-hunt/calculators/calculators.service.ts
src/app/treasure-hunt/convert-input-data.service.ts
src/app/treasure-hunt/find-treasure/find-treasure.component.css
src/app/treasure-hunt/find-treasure/find-treasure.component.html
src/app/treasure-hunt/treasure-chest/export-opportunities/export-opportunities.component.html
src/app/treasure-hunt/treasure-chest/export-opportunities/export-opportunities.component.ts
src/app/treasure-hunt/treasure-chest/import-opportunities.service.ts
src/app/treasure-hunt/treasure-chest/opportunity-cards/opportunity-cards.service.ts
src/app/treasure-hunt/treasure-chest/opportunity-cards/sort-cards.service.ts
src/app/treasure-hunt/treasure-chest/treasure-chest-menu/calculator-type-dropdown/calculator-type-dropdown.component.ts
src/app/treasure-hunt/treasure-hunt-calculator-services/chiller-staging-treasure-hunt.service.spec.ts
src/app/treasure-hunt/treasure-hunt-calculator-services/chiller-staging-treasure-hunt.service.ts
src/app/treasure-hunt/treasure-hunt-calculator-services/treasure-hunt-opportunity.service.ts
src/app/treasure-hunt/treasure-hunt-report/opportunity-summary.service.ts
src/app/treasure-hunt/treasure-hunt.module.ts

Issue 5757: Chiller Staging TH integration

---

src/app/compressed-air-assessment/compressed-air-report/executive-summary/executive-summary.component.html
src/app/compressed-air-assessment/explore-opportunities/explore-opportunities-results/explore-opportunities-results.component.html
src/app/phast/phast-report/results-data/results-data.component.html

Issue 5917: Carbon emission unit labels

---

src/app/calculator/process-cooling/chiller-performance/chiller-performance-form.service.ts
src/app/calculator/process-cooling/chiller-performance/chiller-performance-form/chiller-performance-form.component.html
src/app/calculator/process-cooling/chiller-performance/chiller-performance-help/chiller-performance-help.component.html
src/app/calculator/process-cooling/chiller-performance/chiller-performance-results/chiller-performance-results.component.html
src/app/calculator/process-cooling/chiller-performance/chiller-performance.component.html
src/app/calculator/process-cooling/chiller-performance/chiller-performance.component.ts
src/app/calculator/process-cooling/chiller-performance/chiller-performance.service.ts
src/app/shared/models/chillers.ts
src/app/shared/models/treasure-hunt.ts
src/app/treasure-hunt/calculators/calculators.component.html
src/app/treasure-hunt/calculators/calculators.module.ts
src/app/treasure-hunt/calculators/calculators.service.ts
src/app/treasure-hunt/convert-input-data.service.ts
src/app/treasure-hunt/find-treasure/find-treasure.component.html
src/app/treasure-hunt/treasure-chest/export-opportunities/export-opportunities.component.html
src/app/treasure-hunt/treasure-chest/export-opportunities/export-opportunities.component.ts
src/app/treasure-hunt/treasure-chest/import-opportunities.service.ts
src/app/treasure-hunt/treasure-chest/opportunity-cards/opportunity-cards.service.ts
src/app/treasure-hunt/treasure-chest/opportunity-cards/sort-cards.service.ts
src/app/treasure-hunt/treasure-chest/treasure-chest-menu/calculator-type-dropdown/calculator-type-dropdown.component.ts
src/app/treasure-hunt/treasure-hunt-calculator-services/chiller-performance-treasure-hunt.service.spec.ts
src/app/treasure-hunt/treasure-hunt-calculator-services/chiller-performance-treasure-hunt.service.ts
src/app/treasure-hunt/treasure-hunt-calculator-services/treasure-hunt-opportunity.service.ts
src/app/treasure-hunt/treasure-hunt-report/opportunity-summary.service.ts
src/app/treasure-hunt/treasure-hunt.module.ts

Issue 5758: Chiller Performance TH Integration

---

src/app/calculator/furnaces/air-heating/air-heating-form/air-heating-form.component.html
src/app/calculator/furnaces/air-heating/air-heating.component.html
src/app/calculator/furnaces/air-heating/air-heating.component.ts
src/app/calculator/furnaces/atmosphere/atmosphere.component.html
src/app/calculator/furnaces/atmosphere/atmosphere.component.ts
src/app/calculator/furnaces/charge-material/charge-material.component.html
src/app/calculator/furnaces/charge-material/charge-material.component.ts
src/app/calculator/furnaces/cooling/cooling.component.html
src/app/calculator/furnaces/cooling/cooling.component.ts
src/app/calculator/furnaces/energy-equivalency/energy-equivalency.component.html
src/app/calculator/furnaces/energy-equivalency/energy-equivalency.component.ts
src/app/calculator/furnaces/energy-use/energy-use.component.html
src/app/calculator/furnaces/energy-use/energy-use.component.ts
src/app/calculator/furnaces/fixture/fixture.component.html
src/app/calculator/furnaces/fixture/fixture.component.ts
src/app/calculator/furnaces/heat-cascading/heat-cascading-form/heat-cascading-form.component.html
src/app/calculator/furnaces/heat-cascading/heat-cascading.component.html
src/app/calculator/furnaces/heat-cascading/heat-cascading.component.ts
src/app/calculator/furnaces/leakage/leakage.component.html
src/app/calculator/furnaces/leakage/leakage.component.ts
src/app/calculator/furnaces/o2-enrichment/o2-enrichment.component.html
src/app/calculator/furnaces/o2-enrichment/o2-enrichment.component.ts
src/app/calculator/furnaces/opening/opening.component.html
src/app/calculator/furnaces/opening/opening.component.ts
src/app/calculator/furnaces/waste-heat/waste-heat.component.html
src/app/calculator/furnaces/waste-heat/waste-heat.component.ts

Issue 5885: Low Priority Calculators for Training Release

---

src/app/calculator/compressed-air/air-flow-conversion/air-flow-conversion-help/air-flow-conversion-help.component.html
src/app/calculator/compressed-air/air-flow-conversion/air-flow-conversion.component.html
src/app/calculator/compressed-air/air-flow-conversion/air-flow-conversion.component.ts
src/app/calculator/compressed-air/air-leak/air-leak.component.ts
src/app/calculator/compressed-air/air-velocity/air-velocity.component.html
src/app/calculator/compressed-air/air-velocity/air-velocity.component.ts
src/app/calculator/compressed-air/bag-method/bag-method.component.html
src/app/calculator/compressed-air/bag-method/bag-method.component.ts
src/app/calculator/compressed-air/bleed-test/bleed-test.component.html
src/app/calculator/compressed-air/bleed-test/bleed-test.component.ts
src/app/calculator/compressed-air/compressed-air-pressure-reduction/compressed-air-pressure-reduction.component.html
src/app/calculator/compressed-air/compressed-air-reduction/compressed-air-reduction.component.html
src/app/calculator/compressed-air/compressed-air-reduction/compressed-air-reduction.component.ts
src/app/calculator/compressed-air/operating-cost/operating-cost.component.html
src/app/calculator/compressed-air/operating-cost/operating-cost.component.ts
src/app/calculator/compressed-air/pipe-sizing/pipe-sizing.component.html
src/app/calculator/compressed-air/pipe-sizing/pipe-sizing.component.ts
src/app/calculator/compressed-air/pneumatic-air/pneumatic-air.component.html
src/app/calculator/compressed-air/pneumatic-air/pneumatic-air.component.ts
src/app/calculator/compressed-air/receiver-tank/receiver-tank.component.html
src/app/calculator/compressed-air/receiver-tank/receiver-tank.component.ts
src/app/calculator/compressed-air/system-capacity/system-capacity.component.html
src/app/calculator/compressed-air/system-capacity/system-capacity.component.ts

Issue 5854: Apply mobile UI to Compressed Air calculators

---

src/app/calculator/utilities/altitude-correction/altitude-correction.component.css
src/app/calculator/utilities/altitude-correction/altitude-correction.component.html
src/app/calculator/utilities/altitude-correction/altitude-correction.component.ts
src/app/calculator/utilities/cash-flow/cash-flow.component.html
src/app/calculator/utilities/cash-flow/cash-flow.component.ts
src/app/calculator/utilities/co2-savings/co2-savings.component.html
src/app/calculator/utilities/co2-savings/co2-savings.component.ts
src/app/calculator/utilities/combined-heat-power/combined-heat-power.component.html
src/app/calculator/utilities/combined-heat-power/combined-heat-power.component.ts
src/app/calculator/utilities/electricity-reduction/electricity-reduction.component.html
src/app/calculator/utilities/electricity-reduction/electricity-reduction.component.ts
src/app/calculator/utilities/natural-gas-reduction/natural-gas-reduction.component.html
src/app/calculator/utilities/natural-gas-reduction/natural-gas-reduction.component.ts
src/app/calculator/utilities/power-factor-correction/power-factor-correction.component.html
src/app/calculator/utilities/power-factor-correction/power-factor-correction.component.ts
src/app/calculator/utilities/pre-assessment/pre-assessment.component.html
src/app/calculator/utilities/pre-assessment/pre-assessment.component.ts
src/app/calculator/utilities/unit-converter/unit-converter.component.html
src/app/calculator/utilities/weather-bins/weather-bins.component.html
src/app/calculator/utilities/weather-bins/weather-bins.component.ts

Issue 5853: Apply mobile UI to General/Utility calculators

---

src/app/calculator/motors/full-load-amps/full-load-amps.component.html
src/app/calculator/motors/full-load-amps/full-load-amps.component.ts
src/app/calculator/motors/motor-drive/motor-drive.component.html
src/app/calculator/motors/motor-drive/motor-drive.component.ts
src/app/calculator/motors/percent-load-estimation/percent-load-estimation.component.html
src/app/calculator/motors/percent-load-estimation/percent-load-estimation.component.ts
src/app/calculator/motors/replace-existing/replace-existing-form/replace-existing-form.component.html
src/app/calculator/motors/replace-existing/replace-existing.component.html
src/app/calculator/motors/replace-existing/replace-existing.component.ts

Issue 5856: Apply mobile UI to Motor calculators

---

src/app/calculator/utilities/pre-assessment/pre-assessment-graph/pre-assessment-graph.component.ts

Issue 5914 - remove dollar sign from units on Pre-assessment graph

---

src/app/dashboard/copy-items/copy-items.component.ts
src/app/dashboard/directory-dashboard/directory-items/assessment-item/assessment-item.component.ts

Issue 5791 - Don't delete copied example assessments

---

src/app/treasure-hunt/treasure-hunt-calculator-services/cooling-tower-makeup-treasure-hunt.service.ts

Issue 5761 - BUG convert flow rate to gpm, not gal

---

src/app/tools-suite-api/calculator-suite-api.service.ts

Convert percent to fraction

---

src/app/calculator/fans/fan-analysis/fan-analysis-banner/fan-analysis-banner.component.css
src/app/calculator/fans/fan-analysis/fan-analysis-banner/fan-analysis-banner.component.html
src/app/calculator/fans/fan-analysis/fan-analysis-banner/fan-analysis-banner.component.ts
src/app/calculator/fans/fan-analysis/fan-analysis-results/fan-analysis-results.component.html
src/app/calculator/fans/fan-analysis/fan-analysis.component.css
src/app/calculator/fans/fan-analysis/fan-analysis.component.html
src/app/calculator/fans/fan-analysis/fan-analysis.component.ts
src/app/calculator/fans/fan-analysis/help-and-results-panel/help-and-results-panel.component.html
src/app/calculator/fans/fan-efficiency/fan-efficiency.component.html
src/app/calculator/fans/fan-efficiency/fan-efficiency.component.ts
src/app/calculator/fans/fan-system-checklist/fan-system-checklist-form/fan-system-checklist-form.component.html
src/app/calculator/fans/fan-system-checklist/fan-system-checklist.component.html
src/app/calculator/fans/fan-system-checklist/fan-system-checklist.component.ts
src/app/calculator/system-and-equipment-curve/system-and-equipment-curve-graph/system-and-equipment-curve-graph.component.ts
src/app/calculator/waste-water/o2-utilization-rate/o2-utilization-rate.component.html
src/app/calculator/waste-water/o2-utilization-rate/o2-utilization-rate.component.ts
src/app/calculator/waste-water/state-point-analysis/state-point-analysis.component.html
src/app/calculator/waste-water/state-point-analysis/state-point-analysis.component.ts
src/app/calculator/waste-water/water-reduction/water-reduction.component.html
src/app/calculator/waste-water/water-reduction/water-reduction.component.ts

Issue 5855: Apply mobile UI to Fans, Lighting, Wastewater and Pump calculators

---

src/app/calculator/lighting/lighting-replacement/lighting-replacement.component.html

Issue 5946: Lightning Replacement BL form locked

---

src/app/calculator/utilities/pre-assessment/pre-assessment.component.css
src/app/calculator/utilities/pre-assessment/pre-assessment.component.html

Issue 5931: Pre-Assessment Screening calculator facelift

---

src/app/dashboard/sidebar/directory-item/directory-item.component.html
src/app/dashboard/sidebar/directory-item/directory-item.component.ts
src/app/dashboard/sidebar/sidebar.component.html

Issue 5938: Sidebar fullscreen folder navigation

---

src/app/calculator/process-cooling/chiller-performance/chiller-performance-form/chiller-performance-form.component.html
src/app/calculator/process-cooling/chiller-performance/chiller-performance.component.html
src/app/calculator/process-cooling/chiller-performance/chiller-performance.component.ts
src/app/calculator/process-cooling/chiller-staging/chiller-staging-form/chiller-staging-form.component.html
src/app/calculator/process-cooling/chiller-staging/chiller-staging.component.html
src/app/calculator/process-cooling/chiller-staging/chiller-staging.component.ts
src/app/calculator/process-cooling/cooling-tower-basin/cooling-tower-basin-form/cooling-tower-basin-form.component.html
src/app/calculator/process-cooling/cooling-tower-basin/cooling-tower-basin.component.css
src/app/calculator/process-cooling/cooling-tower-basin/cooling-tower-basin.component.html
src/app/calculator/process-cooling/cooling-tower-basin/cooling-tower-basin.component.ts
src/app/calculator/process-cooling/cooling-tower-fan/cooling-tower-fan-form/cooling-tower-fan-form.component.html
src/app/calculator/process-cooling/cooling-tower-fan/cooling-tower-fan.component.html
src/app/calculator/process-cooling/cooling-tower-fan/cooling-tower-fan.component.ts
src/app/calculator/process-cooling/cooling-tower/cooling-tower.component.html
src/app/calculator/process-cooling/cooling-tower/cooling-tower.component.ts
src/app/calculator/process-cooling/fan-psychrometric/fan-psychrometric.component.html
src/app/calculator/process-cooling/fan-psychrometric/fan-psychrometric.component.ts

Issue 5857: Apply mobile UI to Process Cooling calculators

---

src/app/ssmt/ssmt-diagram-tab/ssmt-diagram-tab.component.html
src/app/ssmt/ssmt-diagram-tab/ssmt-diagram-tab.component.ts

connects #5909 
Subtract results header tabs from container height

Issue 5909

---

src/app/calculator/steam/tank-insulation-reduction/tank-insulation-reduction-form/tank-insulation-reduction-form.component.html
src/app/calculator/steam/tank-insulation-reduction/tank-insulation-reduction-form/tank-insulation-reduction-form.component.ts
src/app/calculator/steam/tank-insulation-reduction/tank-insulation-reduction.service.ts
src/app/shared/models/standalone.ts

Issue 5941: Tank Insulation Calc - New Field

---

package-lock.json
src/app/ssmt/boiler/boiler.component.ts
src/app/ssmt/explore-opportunities/explore-opportunities-form/header-form/condensate-handling-form/condensate-handling-form.component.html
src/app/ssmt/explore-opportunities/explore-opportunities-form/header-form/condensate-handling-form/condensate-handling-form.component.ts
src/app/ssmt/explore-opportunities/explore-opportunities-form/header-form/header-form.component.html
src/app/ssmt/explore-opportunities/explore-opportunities-form/header-form/header-form.component.ts
src/app/ssmt/header/header-form/header-form.component.html
src/app/ssmt/header/header-form/header-form.component.ts
src/app/ssmt/header/header.component.ts
src/app/ssmt/header/header.service.ts

connects #5939 
updated warnings for condensate return temperature based on lowest pressure header

Issue 5939

---

src/app/calculator/process-cooling/cooling-tower-fan/cooling-tower-fan-form.service.ts
src/app/calculator/process-cooling/cooling-tower-fan/cooling-tower-fan-form/cooling-tower-fan-form.component.html
src/app/calculator/process-cooling/cooling-tower-fan/cooling-tower-fan-help/cooling-tower-fan-help.component.html
src/app/calculator/process-cooling/cooling-tower-fan/cooling-tower-fan-results/cooling-tower-fan-results.component.html
src/app/calculator/process-cooling/cooling-tower-fan/cooling-tower-fan.component.html
src/app/calculator/process-cooling/cooling-tower-fan/cooling-tower-fan.component.ts
src/app/calculator/process-cooling/cooling-tower-fan/cooling-tower-fan.service.ts
src/app/shared/convert-units/convert-units.service.ts
src/app/shared/models/chillers.ts
src/app/shared/models/treasure-hunt.ts
src/app/treasure-hunt/calculators/calculators.component.html
src/app/treasure-hunt/calculators/calculators.module.ts
src/app/treasure-hunt/calculators/calculators.service.ts
src/app/treasure-hunt/convert-input-data.service.ts
src/app/treasure-hunt/find-treasure/find-treasure.component.html
src/app/treasure-hunt/treasure-chest/export-opportunities/export-opportunities.component.html
src/app/treasure-hunt/treasure-chest/export-opportunities/export-opportunities.component.ts
src/app/treasure-hunt/treasure-chest/import-opportunities.service.ts
src/app/treasure-hunt/treasure-chest/opportunity-cards/opportunity-cards.service.ts
src/app/treasure-hunt/treasure-chest/opportunity-cards/sort-cards.service.ts
src/app/treasure-hunt/treasure-chest/treasure-chest-menu/calculator-type-dropdown/calculator-type-dropdown.component.ts
src/app/treasure-hunt/treasure-hunt-calculator-services/cooling-tower-fan-treasure-hunt.service.spec.ts
src/app/treasure-hunt/treasure-hunt-calculator-services/cooling-tower-fan-treasure-hunt.service.ts
src/app/treasure-hunt/treasure-hunt-calculator-services/treasure-hunt-opportunity.service.ts
src/app/treasure-hunt/treasure-hunt-report/opportunity-summary.service.ts
src/app/treasure-hunt/treasure-hunt.module.ts

Issue 5759: Cooling Tower Fan TH Integration

---

src/app/calculator/utilities/cash-flow/cash-flow-diagram/cash-flow-diagram.component.html
src/app/calculator/utilities/cash-flow/cash-flow.component.html
src/app/calculator/utilities/cash-flow/cash-flow.component.ts

Issue 5936: Cash Flow app Reset button

---

src/app/log-tool/system-setup/clean-data/clean-data.component.ts
src/app/log-tool/visualize/visualize-menu/visualize-menu.service.ts

Remove restriction for same csv comparison. Enforce date/time marked fields are used.

Issue 5918 - Visualizer bug fix

---

src/app/app.module.ts
src/index.html

#5911 
Instance WASM with an APP_INITIALIZER

Issue 5911 - adding WASM module app initializer

---

src/app/phast/losses/operations/operations-form/operations-form.component.ts
src/app/ssmt/explore-opportunities/explore-opportunities-form/boiler-form/boiler-form.component.html
src/app/ssmt/explore-opportunities/explore-opportunities-form/boiler-form/boiler-form.component.ts
src/app/ssmt/explore-opportunities/explore-opportunities-form/header-form/header-form.component.ts
src/app/ssmt/operations/operations.component.ts

#5945 
- Also adding missing natural gas default emissions rate to ssmt and phast

Issue 5945 - Add co2 fuel selections to explore opps ssmt

---

src/app/ssmt/explore-opportunities/explore-opportunities-form/turbine-form/explore-pressure-turbine-form/explore-pressure-turbine-form.component.ts
src/app/ssmt/explore-opportunities/explore-opportunities-form/turbine-form/turbine-form.component.html

fix missing show turbine call

---

src/app/ssmt/header/header-form/header-form.component.html
src/app/ssmt/header/header-form/header-form.component.ts
src/app/ssmt/header/header.component.html
src/app/ssmt/header/header.component.ts
src/app/ssmt/header/header.service.ts

#5960 #5961
-Fix multi header form validation
-don't validate when no constraint fields
-show validation message on form init
-capitalize Field names in validation like the rest of the app

Issue 5960 5961

---

src/app/compressed-air-assessment/inventory/inventory.service.ts
src/app/compressed-air-assessment/inventory/performance-points/performance-points-form.service.ts

#5972 
Turn on PP validation, fix max full flow validation when VFD

Issue 5972 - Max Full flow VFD bug, and turn on PP validation

---

src/app/ssmt/explore-opportunities/explore-opportunities-form/boiler-form/boiler-form.component.ts

#5945 
Reset the ex opps co2savingsdata object and modification fuel options on uncheck

Issue 5945 - Fix persisting Co2savings results and incorrect fields

---

src/app/psat/explore-opportunities/explore-opportunities-form/explore-opportunities-form.component.html
src/app/psat/explore-opportunities/explore-opportunities-form/system-data-form/system-data-form.component.html
src/app/psat/explore-opportunities/explore-opportunities-form/system-data-form/system-data-form.component.ts
src/app/psat/explore-opportunities/explore-opportunities.component.html

#5974 
Add panel-container class for group-label width, fix form refs in adjust system-data

Issue 5974 Pumps hotfix

---

src/app/compressed-air-assessment/inventory/performance-points/performance-points-form.service.ts

#5972 
Show validation on form init for fields with no value/required

Issue 5972 - PP validation

---

src/app/calculator/process-cooling/cooling-tower-basin/cooling-tower-basin-results/cooling-tower-basin-results.component.html
src/app/calculator/process-cooling/cooling-tower-basin/cooling-tower-basin-results/cooling-tower-basin-results.component.ts
src/app/calculator/process-cooling/cooling-tower-basin/cooling-tower-basin.component.html
src/app/calculator/process-cooling/cooling-tower-basin/cooling-tower-basin.component.ts

Issue 5760: Cooling Tower Basin TH Integration

---

src/app/ssmt/explore-opportunities/explore-opportunities-form/boiler-form/boiler-form.component.ts

fix checkbox on create new modification

---

src/app/ssmt/explore-opportunities/explore-opportunities-form/header-form/header-form.component.ts
src/app/ssmt/header/header-form/header-form.component.html
src/app/ssmt/header/header-form/header-form.component.ts
src/app/ssmt/header/header.component.ts
src/app/ssmt/header/header.service.ts

#5961 
Add deaerator min, update tab status when changing headers, general fixed, readabiity

Issue 5961 - header validation

---

src/app/shared/models/steam/ssmt.ts
src/app/ssmt/operations/operations.component.ts
src/app/ssmt/ssmt-results-panel/ssmt-results-panel/ssmt-results-panel.component.html
src/app/ssmt/ssmt-results-panel/ssmt-results-panel/ssmt-results-panel.component.ts
src/app/ssmt/ssmt.service.ts

#5979 
Check valid and remove errors in result panel, ngChangedAfterChecked in co2savingsDifferent

Issue 5979 - Result panel errors from invalid forms

---

src/app/calculator/process-cooling/cooling-tower-basin/cooling-tower-basin-results/cooling-tower-basin-results.component.html

Issue 5760 fix missing output results error in cooling basin

---

package-lock.json
package.json
src/app/dashboard/sidebar/version-modal/version-modal.component.html

update version modal, suite version

---

src/app/log-tool/data-setup/data-setup.component.ts
src/app/log-tool/data-setup/import-data/import-data.component.css
src/app/log-tool/data-setup/import-data/import-data.component.html
src/app/log-tool/data-setup/import-data/import-data.component.ts
src/app/log-tool/data-setup/refine-data/refine-data.component.html
src/app/log-tool/data-setup/refine-data/refine-data.component.ts
src/app/log-tool/data-setup/select-data-header/select-data-header.component.ts
src/app/log-tool/day-type-analysis/day-type-analysis.component.html
src/app/log-tool/day-type-analysis/day-type-analysis.component.ts
src/app/log-tool/log-tool-data.service.ts
src/app/log-tool/log-tool-db.service.ts
src/app/log-tool/system-setup/setup-data/setup-data.component.ts
src/app/shared/helper-services/csv-to-json.service.ts

#5839 
Add larger upload button, use papaparse web worker to speed import
leaving old components with comment blocks for reference

Issue 5839 - Data Explorer importer

---

src/app/app.module.ts
src/index.html
src/main.ts

#5996 
Message will display if any error during app load
Keeping comments in

Issue 5996

---

src/app/motor-inventory/motor-inventory-setup/motor-catalog/select-motor-modal/filter-motor-options.pipe.ts
src/app/motor-inventory/motor-inventory-setup/motor-catalog/select-motor-modal/motor-options-table/motor-options-table.component.ts
src/app/phast/designed-energy/designed-energy-help/designed-energy-help.component.html

Issue 5990, 5916

---

src/app/dashboard/directory-dashboard/directory-contact-info/directory-contact-info.component.html
src/app/dashboard/directory-dashboard/directory-dashboard-menu/content-controls/content-controls.component.css
src/app/dashboard/directory-dashboard/directory-dashboard-menu/content-controls/content-controls.component.html
src/app/dashboard/directory-dashboard/directory-dashboard-menu/directory-dashboard-menu.component.css
src/app/dashboard/directory-dashboard/directory-dashboard-menu/directory-dashboard-menu.component.html
src/app/dashboard/directory-dashboard/directory-dashboard-menu/directory-dashboard-menu.component.ts
src/app/dashboard/directory-dashboard/directory-dashboard.component.css
src/app/dashboard/directory-dashboard/directory-dashboard.component.html
src/app/dashboard/directory-dashboard/directory-dashboard.component.ts
src/app/dashboard/directory-dashboard/directory-summary/directory-summary.component.css
src/app/dashboard/directory-dashboard/directory-summary/directory-summary.component.html

Issue 6005: Apply Mobile UI to Dashboard

---

src/app/fsat/calculate-pressures/calculate-flow-pressure/calculate-flow-pressure.component.html
src/app/fsat/calculate-pressures/calculate-inlet-pressure/calculate-inlet-pressure.component.html
src/app/fsat/calculate-pressures/calculate-outlet-pressure/calculate-outlet-pressure.component.html
src/app/fsat/fan-field-data/fan-field-data.component.html
src/app/fsat/fsat-banner/fsat-banner.component.css
src/app/fsat/fsat-banner/fsat-banner.component.html
src/app/fsat/fsat-banner/fsat-banner.component.ts
src/app/psat/field-data/field-data.component.css
src/app/psat/psat-banner/psat-banner.component.css
src/app/psat/psat-banner/psat-banner.component.html
src/app/psat/psat-banner/psat-banner.component.ts

Issue 6014: Add nav arrows to FSAT and PSAT banners

---

src/app/log-tool/data-setup/map-time-data/map-time-data.component.css
src/app/log-tool/data-setup/map-time-data/map-time-data.component.html
src/app/log-tool/data-setup/refine-data/refine-data.component.css
src/app/log-tool/data-setup/refine-data/refine-data.component.html
src/app/log-tool/data-setup/select-data-header/select-data-header.component.css
src/assets/styles/two-panel.css

#6011 
- Still has a problem with outer scroll bars (scrolling past the sub headder)  in these panels - it's fixed in 3777

Issue 6011 - Fix scroll areas in data-setup

---

src/app/log-tool/data-setup/map-time-data/map-time-data.component.html
src/app/log-tool/data-setup/map-time-data/map-time-data.component.ts
src/app/log-tool/data-setup/refine-data/refine-data.component.html
src/app/log-tool/data-setup/refine-data/refine-data.component.ts
src/app/log-tool/data-setup/select-data-header/select-data-header.component.css
src/app/log-tool/data-setup/select-data-header/select-data-header.component.html
src/app/log-tool/data-setup/select-data-header/select-data-header.component.ts

#5954 
- Add apply all to all data setup tabs

Issue 5954 - Apply to all datasets feature in DE

---

src/app/log-tool/visualize/visualize-graph/visualize-graph.component.ts
src/app/log-tool/visualize/visualize-menu/visualize-menu.component.ts

Issue 3777 - Make time series segments less stupid, fix date range text

---

src/app/treasure-hunt/treasure-chest/opportunity-cards/opportunity-cards.component.ts
src/app/treasure-hunt/treasure-chest/opportunity-cards/sort-cards-by.pipe.ts
src/app/treasure-hunt/treasure-hunt-report/report-graphs/utility-donut-chart/utility-donut-chart.component.ts

#6028 
May or may not have fixed the freezing, but still necessary fixes:
- use pure pipe function - sort cards was being called on every dom change
- remove automargin property causing loop

Issue 6028 - Investigate TH freezing

---

src/app/treasure-hunt/treasure-chest/opportunity-cards/opportunity-cards.component.html
src/app/treasure-hunt/treasure-chest/summary-card/summary-card.component.html
src/app/treasure-hunt/treasure-chest/summary-card/summary-card.component.ts
src/app/treasure-hunt/treasure-chest/summary-card/utility-summary/utility-summary.component.html
src/app/treasure-hunt/treasure-chest/treasure-chest-menu/treasure-chest-menu.component.css
src/app/treasure-hunt/treasure-chest/treasure-chest-menu/treasure-chest-menu.component.ts
src/app/treasure-hunt/treasure-chest/treasure-chest.component.ts
src/app/treasure-hunt/treasure-hunt-gauge/treasure-hunt-gauge.component.ts
src/app/treasure-hunt/treasure-hunt-report/executive-summary/carbon-emissions-summary-pie-chart/carbon-emissions-summary-pie-chart.component.html
src/app/treasure-hunt/treasure-hunt-report/executive-summary/carbon-emissions-summary-pie-chart/carbon-emissions-summary-pie-chart.component.spec.ts
src/app/treasure-hunt/treasure-hunt-report/executive-summary/carbon-emissions-summary-pie-chart/carbon-emissions-summary-pie-chart.component.ts
src/app/treasure-hunt/treasure-hunt-report/executive-summary/executive-summary.component.html
src/app/treasure-hunt/treasure-hunt-report/executive-summary/team-summary-pie-chart/team-summary-pie-chart.component.ts
src/app/treasure-hunt/treasure-hunt-report/opportunity-payback/opportunity-payback-bar-chart/opportunity-payback-bar-chart.component.ts
src/app/treasure-hunt/treasure-hunt-report/opportunity-payback/opportunity-payback-donut/opportunity-payback-donut.component.ts
src/app/treasure-hunt/treasure-hunt-report/report-graphs/cost-pie-chart/cost-pie-chart.component.ts
src/app/treasure-hunt/treasure-hunt-report/report-graphs/effort-savings-chart/effort-savings-chart.component.ts
src/app/treasure-hunt/treasure-hunt-report/report-graphs/report-graphs.component.css
src/app/treasure-hunt/treasure-hunt-report/report-graphs/report-graphs.component.html
src/app/treasure-hunt/treasure-hunt-report/report-graphs/report-graphs.component.ts
src/app/treasure-hunt/treasure-hunt-report/report-graphs/utility-donut-chart/utility-donut-chart.component.ts
src/app/treasure-hunt/treasure-hunt-report/treasure-hunt-report.component.html
src/app/treasure-hunt/treasure-hunt-report/treasure-hunt-report.module.ts

Issue 6000 & 6019 Graphs in TH

---

src/app/phast/losses/losses-tabs/energy-input-tab/energy-input-tab.component.ts

#6026 
Pass correct phast to min energy validation

Issue 6026 - Energy Input bug 

---

src/app/tools-suite-api/calculator-suite-api.service.ts

#5955 
Mult tank insulation result by 100 to adjust for different bindings unit

Issue 5955

---

src/app/log-tool/log-tool-models.ts
src/app/log-tool/visualize/visualize-graph/visualize-graph.component.ts
src/app/log-tool/visualize/visualize-menu/visualize-menu.service.ts
src/app/log-tool/visualize/visualize-menu/y-axis-data/y-axis-data.component.ts
src/app/log-tool/visualize/visualize.service.ts

#6052 
Fixes for annotations with multiple data series

Issue 6052 DE updates to support annotations

---

src/app/shared/models/treasure-hunt.ts
src/app/treasure-hunt/treasure-hunt-report/report-graphs/report-graphs.component.ts
src/app/treasure-hunt/treasure-hunt-report/report-graphs/utility-donut-chart/utility-donut-chart.component.ts

Issue 6053 - Add number formatting for TH report donut charts

---

package.json
src/app/dashboard/sidebar/version-modal/version-modal.component.html

Issue 6049 - Update version and release notes to v1.2.3

---

src/app/log-tool/data-setup/import-data/import-data.component.ts
src/app/log-tool/data-setup/map-time-data/map-time-data.component.css
src/app/log-tool/data-setup/map-time-data/map-time-data.component.html
src/app/log-tool/data-setup/map-time-data/map-time-data.component.ts
src/app/log-tool/day-type-analysis/day-type-graph/day-type-graph.service.ts
src/app/log-tool/export-modal/export-modal.component.html
src/app/log-tool/log-tool-data.service.ts
src/app/log-tool/visualize/visualize-graph/visualize-graph.component.ts
src/app/log-tool/visualize/visualize-menu/graph-basics/graph-basics.component.ts
src/app/log-tool/visualize/visualize-menu/visualize-menu.component.ts
src/app/log-tool/visualize/visualize-menu/x-axis-data/x-axis-data.component.ts
src/app/log-tool/visualize/visualize-menu/y-axis-data/y-axis-data.component.ts
src/app/log-tool/visualize/visualize-tabs/visualize-tabs.component.ts
src/app/shared/helper-services/csv-to-json.service.ts

#6065 
detail-tooltip will probably be turned into a shared component/ng-template when it isn't hours before a release.

Issue 6065- DE post verification enhancements

---

src/app/log-tool/visualize/visualize-graph/visualize-graph.component.ts

#6075 
Fix bug where time series segment created annotations dissapear when changing to all datapoints

Issue 6075 - Fix annotation bug

---

src/app/treasure-hunt/treasure-hunt-report/treasure-hunt-ppt.service.ts

Issue 6018

---

src/app/compressed-air-assessment/system-profile/system-profile-setup/operating-profile-table/operating-profile-table.component.ts

Issue 6081 - Check validity on profile data updated by data explorer

---

src/app/compressed-air-assessment/system-profile/system-profile-setup/operating-profile-table/operating-profile-table.component.ts
src/app/log-tool/data-setup/map-time-data/map-time-data.component.html
src/app/log-tool/data-setup/map-time-data/map-time-data.component.ts
src/app/log-tool/day-type-analysis/day-type-analysis.component.html
src/app/log-tool/day-type-analysis/day-type-analysis.component.ts
src/app/log-tool/day-type-analysis/day-type-analysis.service.ts
src/app/log-tool/day-type-analysis/day-type-graph/day-type-graph.component.ts
src/app/log-tool/day-type-analysis/day-type-graph/day-type-graph.service.ts
src/app/log-tool/day-type-analysis/day-type-menu/select-assessment-modal/select-assessment-modal.component.ts
src/app/log-tool/day-type-analysis/day-type-table/day-type-summary-table/day-type-summary-table.component.html
src/app/log-tool/day-type-analysis/day-type-table/individual-day-summary-table/individual-day-summary-table.component.html
src/app/log-tool/day-type-analysis/day-type-table/selected-data-table/selected-data-table.component.html
src/app/log-tool/log-tool-data.service.ts
src/app/log-tool/log-tool-models.ts
src/app/log-tool/log-tool.service.ts

#5800 
Add 15, 30 min, 1 hr, 24hr intervals to DE for intergration with CA

Issue 5800 - Day Type Average Intervals

---

src/app/core/core.component.ts
src/app/indexedDb/analytics-data-idb.service.spec.ts
src/app/indexedDb/analytics-data-idb.service.ts
src/app/indexedDb/dbConfig.ts
src/app/shared/analytics/analytics.service.ts

#6023
Add analyticsData store to track app client instances and future data

Issue 6023 - Add analytics data store

---

src/app/log-tool/day-type-analysis/day-type-analysis.component.html
src/app/log-tool/day-type-analysis/day-type-analysis.service.ts
src/app/log-tool/day-type-analysis/day-type-graph/day-type-graph.service.ts
src/app/log-tool/day-type-analysis/day-type-table/individual-day-summary-table/individual-day-summary-table.component.html
src/app/log-tool/day-type-analysis/day-type-table/selected-data-table/selected-data-table.component.html
src/app/log-tool/day-type-analysis/day-type-table/selected-data-table/selected-data-table.component.ts
src/app/log-tool/log-tool-data.service.ts
src/app/log-tool/log-tool-db.service.ts
src/app/log-tool/log-tool-models.ts

#5800 
Fix missing intervals in day type analysis tables, add offset interval for displaying data (1-24 vs 0-23)
Supports old De exports,  adds scrollbar

Issue 5800 Day Type Intervals - Fix interval bugs, support old exports

---

src/app/log-tool/data-setup/refine-data/refine-data.component.html
src/app/log-tool/data-setup/refine-data/refine-data.component.ts
src/app/log-tool/day-type-analysis/day-type-analysis.component.css
src/app/log-tool/day-type-analysis/day-type-analysis.component.html
src/app/log-tool/day-type-analysis/day-type-analysis.component.ts
src/app/log-tool/day-type-analysis/day-type-analysis.service.ts
src/app/log-tool/day-type-analysis/day-type-calendar/day-type-calendar.component.css
src/app/log-tool/day-type-analysis/day-type-graph/day-type-graph.component.ts
src/app/log-tool/day-type-analysis/day-type-menu/day-type-menu.component.css
src/app/log-tool/day-type-analysis/day-type-menu/day-type-menu.component.html
src/app/log-tool/day-type-analysis/day-type-menu/day-type-menu.component.ts
src/app/log-tool/day-type-analysis/day-types/day-types.component.html
src/app/log-tool/log-tool-data.service.ts
src/app/log-tool/log-tool-models.ts
src/app/log-tool/visualize/visualize.service.ts
src/assets/styles/two-panel.css

#6072 
- Added interval total aggregation for all data readings, ability to select which are used
- Restyled navbar menu to prevent visual jumping and dissapearing toggles
- Make calendar pickers responsively styled

Issue 6072 - Add interval total aggregation for all data readings

---

src/app/calculator/utilities/electricity-reduction/electricity-reduction-form/electricity-reduction-form.component.html
src/app/calculator/utilities/electricity-reduction/electricity-reduction-form/electricity-reduction-form.component.ts
src/app/calculator/utilities/electricity-reduction/electricity-reduction.component.html
src/app/calculator/utilities/electricity-reduction/electricity-reduction.component.ts
src/app/calculator/utilities/electricity-reduction/electricity-reduction.service.ts
src/app/examples/mockTreasureHunt.ts
src/app/shared/helper-services/update-data.service.ts
src/app/shared/models/standalone.ts
src/app/treasure-hunt/convert-input-data.service.ts
src/app/treasure-hunt/treasure-hunt-calculator-services/electricity-reduction-treasure-hunt.service.ts

Issue 6021

---

src/app/compressed-air-assessment/compressed-air-assessment-results.service.ts
src/app/compressed-air-assessment/compressed-air-data-management.service.ts
src/app/compressed-air-assessment/compressed-air-sankey/power-sankey/power-sankey.service.ts
src/app/compressed-air-assessment/explore-opportunities/explore-opportunities.component.ts
src/app/compressed-air-assessment/explore-opportunities/use-automatic-sequencer/use-automatic-sequencer.component.ts
src/app/compressed-air-assessment/inventory-performance-profile/inventory-performance-profile.component.ts
src/app/compressed-air-assessment/inventory/inventory.service.ts
src/app/compressed-air-assessment/inventory/performance-points/blowoff/blowoff.component.ts
src/app/compressed-air-assessment/inventory/performance-points/calculations/full-load-calculations.service.ts
src/app/compressed-air-assessment/inventory/performance-points/full-load/full-load.component.ts
src/app/compressed-air-assessment/inventory/performance-points/max-full-flow/max-full-flow.component.ts
src/app/compressed-air-assessment/inventory/performance-points/mid-turndown/mid-turndown.component.ts
src/app/compressed-air-assessment/inventory/performance-points/no-load/no-load.component.ts
src/app/compressed-air-assessment/inventory/performance-points/performance-points-form.service.ts
src/app/compressed-air-assessment/inventory/performance-points/performance-points.component.ts
src/app/compressed-air-assessment/inventory/performance-points/turndown/turndown.component.ts
src/app/compressed-air-assessment/inventory/performance-points/unload-point/unload-point.component.ts
src/app/compressed-air-assessment/results-panel/inventory-table/inventory-table.component.ts
src/app/compressed-air-assessment/system-information/system-information-form.service.ts
src/app/compressed-air-assessment/system-information/system-information.component.html
src/app/compressed-air-assessment/system-information/system-information.component.ts
src/app/compressed-air-assessment/system-profile/system-profile-setup/compressor-ordering-table/compressor-ordering-table.component.html
src/app/compressed-air-assessment/system-profile/system-profile-setup/compressor-ordering-table/compressor-ordering-table.component.ts
src/app/compressed-air-assessment/system-profile/system-profile.service.ts
src/app/dashboard/assessment.service.ts
src/app/examples/mockCompressedAirAssessment.ts
src/app/shared/helper-services/update-data.service.ts
src/app/shared/models/compressed-air-assessment.ts

Adds setup for selection of different multi compressor control options.
Implements isentropic efficiency option

Issue 6113

---

src/app/examples/mockMotorInventoryData.ts

Issue 6106 - Change motor inventory example name

---

package-lock.json
package.json

Update ajv to 8.12.0 to fix breaking build

---

src/app/calculator/steam/tank-insulation-reduction/tank-insulation-reduction-form/tank-insulation-reduction-form.component.ts
src/app/calculator/steam/tank-insulation-reduction/tank-insulation-reduction.component.html
src/app/calculator/steam/tank-insulation-reduction/tank-insulation-reduction.component.ts
src/app/calculator/steam/tank-insulation-reduction/tank-insulation-reduction.service.ts

Issue 5955 Tank insulation - Don't disable mod utility cost

---

src/app/calculator/steam/tank-insulation-reduction/tank-insulation-reduction-form/tank-insulation-reduction-form.component.ts
src/app/calculator/steam/tank-insulation-reduction/tank-insulation-reduction.component.html
src/app/calculator/steam/tank-insulation-reduction/tank-insulation-reduction.component.ts
src/app/calculator/steam/tank-insulation-reduction/tank-insulation-reduction.service.ts

5955 Tank insulation - Don't disable mod utility cost

---

src/app/log-tool/day-type-analysis/day-type-analysis.component.ts
src/app/log-tool/log-tool-data.service.ts

#5800 
- Fix default hourly interval
- Change start/end interval offset to match CA

Issue 5800 Day type Averages

---

src/app/log-tool/data-setup/data-setup.component.html
src/app/log-tool/data-setup/data-setup.component.ts
src/app/log-tool/data-setup/map-time-data/map-time-data.component.html
src/app/log-tool/data-setup/map-time-data/map-time-data.component.ts
src/app/log-tool/day-type-analysis/day-type-analysis.component.html
src/app/log-tool/day-type-analysis/day-type-calendar/day-type-calendar.component.css
src/app/log-tool/day-type-analysis/day-type-graph/day-type-graph.component.css
src/app/log-tool/day-type-analysis/day-types/day-types.component.css
src/app/log-tool/log-tool-models.ts

#6072 
- Fix next/finish button confusion
- Use alias in DTA graph instead of fieldname
- Lose box shadows to match visualize tab

6072 Day Type analysis graph

---

package-lock.json
src/app/tools-suite-api/process-heating-api.service.ts

#6135 
Cooling loss calls wrong method

Issue 6135

---

src/app/dashboard/directory-dashboard/directory-items/assessment-item/assessment-item.component.ts
src/app/dashboard/directory-dashboard/directory-items/inventory-item/inventory-item.component.ts
src/app/dashboard/move-items/move-items.component.ts
src/app/indexedDb/directory-db.service.ts
src/app/settings/assessment-settings/reset-data-modal/reset-data-modal.component.ts

Issue 6119 Moved examples are now user assessments

---

src/app/compressed-air-assessment/system-information/system-information.component.html

Issue 6114 - Remove load sharing option 

---

src/app/calculator/motors/motors-list/motors-list.component.html
src/app/calculator/motors/percent-load-estimation/field-measurement-form/field-measurement-form.component.html
src/app/calculator/motors/percent-load-estimation/field-measurement-form/field-measurement-form.component.ts
src/app/calculator/motors/percent-load-estimation/percent-load-estimation.component.html
src/app/calculator/motors/percent-load-estimation/percent-load-estimation.component.ts

Issue 6097

---

angular.json
package-lock.json
src/app/calculator/pumps/head-tool/head-tool-form/head-tool-form.component.html
src/assets/styles/c3-charts.css
src/assets/styles/utilities.css

Issue 6139, 6121  Fix TH gauge background, padding on pump head tool

---

src/app/treasure-hunt/treasure-hunt-gauge/treasure-hunt-gauge.component.ts
src/app/treasure-hunt/treasure-hunt-report/report-graphs/report-graphs.component.ts

connects #6086 
the branch is the wrong issue number, my dyslexia brain didn't see that till now

Issue 6086: Treasure Hunt Report Graphs bug

---

src/app/compressed-air-assessment/system-profile/system-profile-setup/compressor-ordering-table/compressor-ordering-table.component.html

decimal places for isentropic efficiency

---

src/app/dashboard/about-page/about-page.component.html
src/app/log-tool/data-setup/import-data/import-data.component.html
src/app/log-tool/data-setup/import-data/import-data.component.ts
src/app/log-tool/data-setup/map-time-data/map-time-data.component.html
src/app/log-tool/day-type-analysis/day-type-analysis.component.ts
src/app/log-tool/day-type-analysis/day-type-graph/day-type-graph.service.ts
src/app/log-tool/log-tool-data.service.ts
src/app/shared/date-format-help/date-format-help.component.html

#5800 #6150 #6078
Fix interval offsets for 24 hr, example data dta totals, timestamp spelling

Issue 5800 6078, 6150 Various Data Explorer

---

package.json
src/app/dashboard/sidebar/version-modal/version-modal.component.html

Issue 6049 1.2.4 release notes

---

src/app/compressed-air-assessment/compressed-air-assessment.service.ts
src/app/compressed-air-assessment/explore-opportunities/improve-end-use-efficiency/improve-end-use-efficiency.component.ts
src/app/compressed-air-assessment/explore-opportunities/reduce-run-time/reduce-run-time.component.html
src/app/compressed-air-assessment/interval-hour-label/interval-hour-label.pipe.ts
src/app/compressed-air-assessment/profile-summary-table/profile-summary-table.component.html
src/app/compressed-air-assessment/system-profile-graphs/system-profile-graphs.component.ts
src/app/compressed-air-assessment/system-profile/system-profile-setup/compressor-ordering-table/compressor-ordering-table.component.ts
src/app/compressed-air-assessment/system-profile/system-profile-setup/operating-profile-table/operating-profile-table.component.ts
src/app/log-tool/log-tool-data.service.ts

#6130 
Changing start/end of intervals so DE and CA are the same.
Keeping hourly ticks shown in graphs. This can easily be turned back

Issue 6130

---

src/app/log-tool/day-type-analysis/day-type-graph/day-type-graph.service.ts

#6130 
Fixing wrong interval display issue from my previous PR

Issue 6130 Use display string not offset

---

main.js
preload.js
src/app/core/core.component.html
src/app/core/core.component.ts
src/app/core/core.module.ts
src/app/core/core.service.ts
src/app/dashboard/about-page/about-page.component.ts
src/app/electron/electron.service.spec.ts
src/app/electron/electron.service.ts
src/app/settings/assessment-settings/reset-data-modal/reset-data-modal.component.ts
src/app/update-toast/update-toast.component.ts

Issue 4425 Remove ngx electorn in develop

---

src/app/compressed-air-assessment/day-types/day-types.component.html
src/app/compressed-air-assessment/day-types/day-types.component.ts
src/app/compressed-air-assessment/system-profile/system-profile-setup/operating-profile-table/operating-profile-table.component.html
src/app/compressed-air-assessment/system-profile/system-profile-setup/operating-profile-table/operating-profile-table.component.ts
src/app/log-tool/day-type-analysis/day-type-menu/select-assessment-modal/select-assessment-modal.component.html
src/app/log-tool/day-type-analysis/day-type-menu/select-assessment-modal/select-assessment-modal.component.ts

Issue 5801 - Add messaging and navigation between de and CA

---

src/app/log-tool/data-setup/import-data/import-data.component.ts
src/app/log-tool/log-tool-db.service.ts

Issue 6170 Check for existing day types on import

---

src/app/log-tool/day-type-analysis/day-type-analysis.service.ts
src/app/log-tool/log-tool-data.service.ts

Issue 6179 - Don't add NANS to aggregate totals, naming changes

---

src/app/compressed-air-assessment/compressed-air-assessment.component.ts
src/app/compressed-air-assessment/compressed-air-sankey/power-sankey/power-sankey.component.ts
src/app/shared/helper-services/air-properties-csv.service.ts
src/app/shared/print-options-menu/print-options-menu.component.html
src/app/shared/print-options-menu/print-options-menu.component.ts
src/app/shared/print-options-menu/print-options-menu.service.ts

#6181 
- Async data call never finished for rollup printing of ca sankey

Issue 6181- Fix CA sankey printing

---

src/app/calculator/compressed-air/system-capacity/system-capacity-form/system-capacity-form.component.html
src/app/calculator/compressed-air/system-capacity/system-capacity-form/system-capacity-form.component.ts
src/app/shared/models/standalone.ts

Issue 6171 - Add cubic feet results to imperial sys capacity calc

---

src/app/core/core.component.ts
src/app/shared/analytics/analytics.service.ts

#6176 
- Add measur-desktop param for tracking
- Move logic to service

Issue 6176 - Analytics - add measurments for platform, Move logic to service

---

package-lock.json
src/app/app.component.ts
src/app/core/core.component.ts

#6176 
- add measur-web param
- only set config once

Issue 6176 WASM - Analytics add measur-web param

---

src/app/calculator/utilities/electricity-reduction/electricity-reduction-form/electricity-reduction-form.component.html
src/app/calculator/utilities/electricity-reduction/electricity-reduction-form/electricity-reduction-form.component.ts
src/app/calculator/utilities/electricity-reduction/electricity-reduction-help/electricity-reduction-help.component.html
src/app/calculator/utilities/electricity-reduction/electricity-reduction.component.html
src/app/calculator/utilities/electricity-reduction/electricity-reduction.component.ts
src/app/calculator/utilities/electricity-reduction/electricity-reduction.service.ts

Issue 6102: Electricity Reduction Help text tweak

---

src/app/core/core.component.html
src/app/core/core.component.ts
src/app/core/core.service.ts
src/app/dashboard/sidebar/sidebar.component.html
src/app/dashboard/sidebar/sidebar.component.ts
src/app/settings/application-settings/application-settings.component.html
src/app/settings/application-settings/application-settings.component.ts
src/index.html

#6192 
Free google translate widget is no longer supported - removing

Issue 6192 - Remove google translate in desktop

---

src/app/core/core.component.ts
src/app/dashboard/sidebar/sidebar.component.html
src/app/settings/application-settings/application-settings.component.html

Issue 6192 (Web) - Remove google translate remnants from Web

---

src/app/treasure-hunt/treasure-chest/opportunity-cards/opportunity-cards.component.html
src/app/treasure-hunt/treasure-chest/opportunity-cards/opportunity-cards.component.ts

#6211 
- Create new array ref to update pipe on delete, rename list
- changed 'data' to 'list' in var name. 'data' is an item in the list

Issue 6211 - Update card list on delete

---

src/app/log-tool/log-tool-models.ts
src/app/log-tool/visualize/visualize-graph/visualize-graph.component.ts
src/app/log-tool/visualize/visualize-menu/graph-basics/graph-basics.component.html
src/app/log-tool/visualize/visualize-menu/graph-basics/graph-basics.component.ts
src/app/log-tool/visualize/visualize-menu/visualize-menu.service.ts
src/app/log-tool/visualize/visualize.component.ts
src/app/log-tool/visualize/visualize.service.ts

#6131 
- Keeping comments with context/reasons why
- This needs #6225 to work with time segments

Issue 6131 - Save annotations in memory

---

src/app/treasure-hunt/treasure-hunt-report/opportunity-summary/opportunity-summary-copy-table/opportunity-summary-copy-table.component.html
src/app/treasure-hunt/treasure-hunt-report/opportunity-summary/opportunity-summary-copy-table/opportunity-summary-copy-table.component.ts

Issue 6236 & 6210: Implementation Tracker Bug/TH Excel bug

---

src/app/treasure-hunt/treasure-hunt-report/treasure-hunt-ppt.service.ts

Issue 6217: TH PPT extension

---

src/app/dashboard/assessment-create/assessment-create.component.ts
src/app/dashboard/create-inventory/create-inventory.component.ts

Issue 6235 - Close sidebar when new assessment or inventory

---

src/app/calculator/process-cooling/cooling-tower-fan/cooling-tower-fan-chart/cooling-tower-fan-chart.component.ts
src/app/calculator/process-cooling/cooling-tower-fan/cooling-tower-fan-form/cooling-tower-fan-form.component.html
src/app/calculator/process-cooling/cooling-tower-fan/cooling-tower-fan-help/cooling-tower-fan-help.component.html
src/app/calculator/process-cooling/cooling-tower-fan/cooling-tower-fan-results/cooling-tower-fan-results.component.html

#6204 
Change waterFlowRate name, add help, % units to power units

Issue 6204 - Cooling Tower Fan changes

---

src/app/motor-inventory/batch-analysis/batch-analysis-table/batch-analysis-table.component.html
src/app/motor-inventory/batch-analysis/batch-analysis-table/batch-analysis-table.component.ts
src/app/motor-inventory/convert-motor-inventory.service.spec.ts
src/app/motor-inventory/convert-motor-inventory.service.ts
src/app/motor-inventory/motor-inventory-setup/department-catalog-table/department-catalog-table.component.css
src/app/motor-inventory/motor-inventory-setup/department-catalog-table/department-catalog-table.component.html
src/app/motor-inventory/motor-inventory-setup/department-catalog-table/department-catalog-table.component.ts
src/app/motor-inventory/motor-inventory-setup/motor-catalog/motor-catalog.component.ts
src/app/motor-inventory/motor-inventory-setup/plant-setup/plant-setup.component.html
src/app/motor-inventory/motor-inventory-setup/plant-setup/plant-setup.component.ts
src/app/motor-inventory/motor-inventory-summary/inventory-summary-graphs/inventory-summary-graph/inventory-summary-graph.component.ts
src/app/motor-inventory/motor-inventory-summary/inventory-summary-graphs/inventory-summary-graphs.service.ts
src/app/motor-inventory/motor-inventory-summary/inventory-summary-motor-details/motor-item-detail/nameplate-details/nameplate-details.component.html
src/app/motor-inventory/motor-inventory.module.ts
src/app/motor-inventory/motor-inventory.ts
src/app/shared/convert-units/convert-units.service.ts
src/app/shared/convert-units/definitions/torque.ts

Issue 6233, 6238 - Motor inventory unit conversion, chart updates

---

src/app/fsat/fsat.component.ts
src/app/log-tool/data-setup/import-data/import-data.component.ts
src/app/psat/explore-opportunities/explore-opportunities-form/explore-opportunities-form.component.ts
src/app/psat/modify-conditions/modify-conditions-tabs/modify-conditions-tabs.component.ts
src/app/psat/psat-tabs/psat-tabs.component.ts
src/app/psat/psat.component.ts
src/app/psat/pump-operations/pump-operations.component.ts
src/app/psat/pump-operations/pump-operations.service.ts
src/app/ssmt/ssmt.component.ts
src/app/waste-water/waste-water.component.html
src/app/waste-water/waste-water.component.ts

Issue 6177: Assessment Operations Pages - footer next button

---

src/app/dashboard/copy-items/copy-items.component.ts

Issue 6182: Copying Multiple assessments

---

src/app/ssmt/explore-opportunities/explore-opportunities.component.css
src/app/ssmt/explore-opportunities/explore-opportunities.component.html
src/app/ssmt/modify-conditions/modify-conditions-tabs/modify-conditions-tabs.component.html
src/app/ssmt/modify-conditions/modify-conditions.component.css
src/app/ssmt/modify-conditions/modify-conditions.component.html
src/app/ssmt/modify-conditions/modify-conditions.component.ts
src/app/ssmt/ssmt-banner/ssmt-banner.component.css
src/app/ssmt/ssmt-banner/ssmt-banner.component.html
src/app/ssmt/ssmt-banner/ssmt-banner.component.ts
src/app/ssmt/ssmt-diagram-tab/ssmt-diagram-tab.component.html
src/app/ssmt/ssmt-diagram/ssmt-diagram.component.html
src/app/ssmt/ssmt-report/report-diagram/report-diagram.component.html
src/app/ssmt/ssmt-report/report-graphs/report-graphs.component.html
src/app/ssmt/ssmt-report/ssmt-report.component.html
src/app/ssmt/ssmt-report/ssmt-report.component.ts
src/app/ssmt/ssmt-tabs/ssmt-tabs.component.css
src/app/ssmt/ssmt-tabs/ssmt-tabs.component.html
src/app/ssmt/ssmt-tabs/ssmt-tabs.component.ts
src/app/ssmt/ssmt.component.css
src/app/ssmt/ssmt.component.html
src/app/ssmt/ssmt.service.ts

connects #5872 
Steam diagram is hidden when in mobile view

issue 5872: Apply Mobile UI to Steam assessment 

---

src/app/motor-inventory/motor-inventory-setup/department-setup/department-setup.component.html

issue 6251 Motor Department delete behavior

---

src/app/ssmt/modify-conditions/modify-conditions-tabs/modify-conditions-tabs.component.html
src/app/waste-water/modify-conditions/modify-conditions.component.css
src/app/waste-water/modify-conditions/modify-conditions.component.html
src/app/waste-water/modify-conditions/modify-conditions.component.ts
src/app/waste-water/waste-water-analysis/energy-analysis/energy-analysis.component.html
src/app/waste-water/waste-water-banner/calculator-tabs/calculator-tabs.component.html
src/app/waste-water/waste-water-banner/calculator-tabs/calculator-tabs.component.ts
src/app/waste-water/waste-water-banner/modify-conditions-tabs/modify-conditions-tabs.component.html
src/app/waste-water/waste-water-banner/setup-tabs/setup-tabs.component.html
src/app/waste-water/waste-water-banner/setup-tabs/setup-tabs.component.ts
src/app/waste-water/waste-water-banner/waste-water-banner.component.css
src/app/waste-water/waste-water-banner/waste-water-banner.component.html
src/app/waste-water/waste-water-banner/waste-water-banner.component.ts
src/app/waste-water/waste-water-report/waste-water-report.component.html
src/app/waste-water/waste-water-report/waste-water-report.component.ts
src/app/waste-water/waste-water.component.css
src/app/waste-water/waste-water.component.html
src/app/waste-water/waste-water.service.ts

waste water mobile UI implemented

---

src/app/phast/aux-equipment/aux-equipment.component.css
src/app/phast/aux-equipment/aux-equipment.component.html
src/app/phast/designed-energy/designed-energy.component.css
src/app/phast/designed-energy/designed-energy.component.html
src/app/phast/explore-phast-opportunities/explore-phast-opportunities.component.css
src/app/phast/explore-phast-opportunities/explore-phast-opportunities.component.html
src/app/phast/losses/losses-result-panel/losses-result-panel.component.html
src/app/phast/losses/losses-tabs/losses-tabs.component.html
src/app/phast/losses/losses-tabs/losses-tabs.component.ts
src/app/phast/losses/losses.component.css
src/app/phast/losses/losses.component.html
src/app/phast/losses/losses.component.ts
src/app/phast/metered-energy/metered-energy.component.css
src/app/phast/metered-energy/metered-energy.component.html
src/app/phast/modification-navbar/modification-navbar.component.html
src/app/phast/modification-navbar/modification-navbar.component.ts
src/app/phast/phast-banner/phast-banner.component.css
src/app/phast/phast-banner/phast-banner.component.html
src/app/phast/phast-banner/phast-banner.component.ts
src/app/phast/phast-calculator-tabs/phast-calculator-tabs.component.html
src/app/phast/phast-calculator-tabs/phast-calculator-tabs.component.ts
src/app/phast/phast-report/phast-report.component.html
src/app/phast/phast-report/phast-report.component.ts
src/app/phast/phast-report/report-graphs/report-graphs.component.html
src/app/phast/phast-tabs/phast-tabs.component.css
src/app/phast/phast-tabs/phast-tabs.component.html
src/app/phast/phast-tabs/phast-tabs.component.ts
src/app/phast/phast.component.css
src/app/phast/phast.component.html
src/app/phast/phast.service.ts

Issue 5874: PHAST mobile UI

---

src/app/calculator/motors/full-load-amps/full-load-amps-help/full-load-amps-help.component.html
src/app/calculator/motors/full-load-amps/full-load-amps.service.ts
src/app/fsat/fsat-warning.service.ts
src/app/fsat/help-panel/fan-motor-help/fan-motor-help.component.html
src/app/psat/help-panel/motor-help/motor-help.component.html
src/app/psat/psat-warning.service.ts

Issue 6098: Full load amps

---

src/app/dashboard/import-export/export-modal/export-modal.component.ts

Issue 5645: Export Assessment default name

---

src/app/calculator/furnaces/energy-equivalency/energy-equivalency-form/energy-equivalency-form.component.ts

Issue 6275: Energy Equivalency calc bug

---

src/app/calculator/utilities/electricity-reduction/electricity-reduction.service.ts

connects #6102 
Electricity Reduction calculator help text quick fix

Issue 6102

---

src/app/calculator/furnaces/air-heating/air-heating-form/air-heating-form.component.html
src/app/calculator/furnaces/air-heating/air-heating-help/air-heating-help.component.html
src/app/calculator/furnaces/flue-gas/flue-gas-form-mass/flue-gas-form-mass.component.html
src/app/calculator/furnaces/flue-gas/flue-gas-form-mass/flue-gas-form-mass.component.ts
src/app/calculator/furnaces/flue-gas/flue-gas-form-volume/flue-gas-form-volume.component.html
src/app/calculator/furnaces/flue-gas/flue-gas-form-volume/flue-gas-form-volume.component.ts
src/app/calculator/furnaces/flue-gas/flue-gas-help/flue-gas-help.component.html
src/app/calculator/furnaces/flue-gas/flue-gas-modal/flue-gas-modal.component.html
src/app/calculator/furnaces/flue-gas/flue-gas.component.html
src/app/calculator/furnaces/heat-cascading/heat-cascading-help/heat-cascading-help.component.html
src/app/calculator/steam/condensing-economizer/condensing-economizer-form/condensing-economizer-form.component.html
src/app/calculator/steam/condensing-economizer/condensing-economizer-help/condensing-economizer-help.component.html
src/app/calculator/steam/feedwater-economizer/feedwater-economizer-form/feedwater-economizer-form.component.html
src/app/calculator/steam/feedwater-economizer/feedwater-economizer-help/feedwater-economizer-help.component.html
src/app/calculator/steam/stack-loss/stack-loss-form/stack-loss-by-mass/stack-loss-by-mass.component.html
src/app/calculator/steam/stack-loss/stack-loss-form/stack-loss-by-volume/stack-loss-by-volume.component.html
src/app/calculator/steam/stack-loss/stack-loss-help/stack-loss-help.component.html
src/app/calculator/steam/stack-loss/stack-loss-help/stack-loss-help.component.ts
src/app/calculator/steam/stack-loss/stack-loss.component.html
src/app/phast/losses/flue-gas-losses/flue-gas-losses-form-mass/flue-gas-losses-form-mass.component.html
src/app/phast/losses/flue-gas-losses/flue-gas-losses-form-volume/flue-gas-losses-form-volume.component.html
src/app/phast/losses/flue-gas-losses/flue-gas-losses.component.html
src/app/phast/losses/losses-help/flue-gas-losses-help/flue-gas-losses-help.component.html
src/app/phast/phast-report/phast-input-summary/flue-gas-summary/flue-gas-summary.component.html
src/app/suiteDb/solid-liquid-flue-gas-material/solid-liquid-flue-gas-material-help/solid-liquid-flue-gas-material-help.component.html
src/app/suiteDb/solid-liquid-flue-gas-material/solid-liquid-flue-gas-material-help/solid-liquid-flue-gas-material-help.component.ts
src/app/suiteDb/solid-liquid-flue-gas-material/solid-liquid-flue-gas-material.component.html

Connects https://github.com/ORNL-AMO/AMO-Tools-Desktop/issues/5520
note: I also changed a bunch of other files that shared the same text as the Flue Gas calculator for consistency

Issue 5520: Flue Gas Calc Help Text improvements #6298

---

src/app/calculator/furnaces/flue-gas/flue-gas-help/flue-gas-help.component.html
src/app/calculator/furnaces/flue-gas/flue-gas-help/flue-gas-help.component.ts
src/app/calculator/steam/stack-loss/stack-loss-help/stack-loss-help.component.html

Issue 6297: Standalone Flue Gas Calc drop-down suggestions #6301

---

src/app/app.component.css
src/app/fsat/fsat-tabs/fsat-tabs.component.html
src/app/phast/modification-navbar/modification-navbar.component.html
src/app/waste-water/waste-water-banner/waste-water-banner.component.html

Issue 6286: PH Assessment Novice/Expert toggle

---

src/app/log-tool/visualize/visualize-data/visualize-data.component.ts

Issue 6076: Resolve Scatter plot confusion

---

src/app/report-rollup/assessment-reports/assessment-reports.component.css
src/app/report-rollup/assessment-reports/assessment-reports.component.html
src/app/report-rollup/assessment-reports/assessment-reports.component.ts
src/app/report-rollup/report-rollup-modals/report-rollup-modals.component.html
src/app/report-rollup/report-rollup.component.css
src/app/report-rollup/report-rollup.module.ts
src/app/report-rollup/report-summary-graphs/report-summary-graphs.component.html
src/app/report-rollup/report-summary-graphs/report-summary-graphs.component.ts
src/app/report-rollup/report-summary/compressed-air-summary/compressed-air-summary.component.html
src/app/report-rollup/report-summary/fsat-summary/fsat-summary.component.html
src/app/report-rollup/report-summary/phast-summary/phast-summary.component.html
src/app/report-rollup/report-summary/psat-summary/psat-summary.component.html
src/app/report-rollup/report-summary/report-summary.component.css
src/app/report-rollup/report-summary/report-summary.component.html
src/app/report-rollup/report-summary/report-summary.component.ts
src/app/report-rollup/report-summary/ssmt-summary/ssmt-summary.component.html
src/app/report-rollup/report-summary/treasure-hunt-summary/treasure-hunt-summary.component.html
src/app/report-rollup/report-summary/waste-water-summary/waste-water-summary.component.html

Issue 6015: Apply Mobile UI to Report Rollup

---

src/app/compressed-air-assessment/system-profile/system-profile-setup/operating-profile-table/operating-profile-table.component.html

Issue 5801: Navigation back to data explorer once applied data to CA

---

src/app/calculator/process-cooling/cooling-tower-basin/cooling-tower-basin.component.css
src/app/calculator/process-cooling/cooling-tower-basin/cooling-tower-basin.component.html

Issue 6295: Cooling Tower Basin Calc Weather Header Styling

---

src/app/calculator/compressed-air/bleed-test/bleed-test-form/bleed-test-form.component.html
src/app/calculator/compressed-air/bleed-test/bleed-test.component.html

Issue 6326: Compressed air Bleed test - time unit label

---

src/app/core/core.component.ts
src/app/shared/analytics/analytics.service.ts

#6294 
- Fix async call order problem
- modify inventory url's to track consistently
- remove extra production check

Issue 6294 GA endpoint issue

---

src/app/calculator/process-cooling/cooling-tower-basin/cooling-tower-basin.component.html

Issue 6295: Weather data looks good but now the calc title is acting weird

---

src/app/dashboard/import-export/export-modal/export-modal.component.html
src/app/dashboard/import-export/export-modal/export-modal.component.ts
src/app/dashboard/import-export/export.service.ts

#6334 
Also reducing some complexity/readability in these comps

Issue 6334 - Fix duplicate inventory items showing

---

src/app/psat/psat-warning.service.ts
src/app/pump-inventory/pump-inventory-setup/pump-catalog/pump-catalog.component.html
src/app/pump-inventory/pump-inventory-setup/pump-catalog/pump-equipment-catalog/pump-equipment-catalog.component.html
src/app/pump-inventory/pump-inventory-setup/pump-properties/pump-properties.component.html

Isssue 6336 6338 6299 - NV related Pumps fixes

---

src/app/compressed-air-assessment/compressed-air-assessment.service.ts
src/app/compressed-air-assessment/system-profile/profile-setup-form/profile-setup-form.component.html
src/app/compressed-air-assessment/system-profile/profile-setup-form/profile-setup-form.component.ts
src/app/shared/models/compressed-air-assessment.ts

Issue 6287: Compressed Air - System Profile workflow

---

src/app/compressed-air-assessment/welcome-screen/welcome-screen.component.css
src/app/compressed-air-assessment/welcome-screen/welcome-screen.component.html
src/app/fsat/welcome-screen/welcome-screen.component.css
src/app/log-tool/welcome-screen/welcome-screen.component.css
src/app/motor-inventory/welcome-screen/welcome-screen.component.css
src/app/phast/welcome-screen/welcome-screen.component.css
src/app/psat/welcome-screen/welcome-screen.component.css
src/app/ssmt/welcome-screen/welcome-screen.component.css
src/app/treasure-hunt/welcome-screen/welcome-screen.component.css
src/app/tutorials/opening-tutorial/opening-tutorial.component.css
src/app/waste-water/welcome-screen/welcome-screen.component.css
src/assets/styles/welcome-screen.css

Issue 6202:  Banner and Welcome Screen styling

---

src/app/log-tool/data-setup/map-time-data/map-time-data.component.css
src/app/log-tool/data-setup/map-time-data/map-time-data.component.html
src/app/log-tool/data-setup/map-time-data/map-time-data.component.ts

Data Explorer Tooltips

---

src/app/dashboard/acknowledgments-page/acknowledgments-page.component.html

:D :D :D :D 
Connects #6356
Also added some space here as requested

Issue 6339: Add yourself to Acknowledgements Page

---

src/app/calculator/fans/fan-analysis/fan-analysis-form/fan-shaft-power-form/fan-shaft-power-form.component.html
src/app/calculator/fans/fan-analysis/help-and-results-panel/operating-points-help/fan-shaft-power-help/fan-shaft-power-help.component.html
src/app/calculator/process-cooling/cooling-tower-basin/cooling-tower-basin-help/cooling-tower-basin-help.component.html
src/app/calculator/steam/steam-reduction/steam-reduction-help/steam-reduction-help.component.html
src/app/calculator/utilities/electricity-reduction/electricity-reduction-form/electricity-reduction-form.component.ts
src/app/calculator/utilities/electricity-reduction/electricity-reduction-help/electricity-reduction-help.component.html

Issue 6020: Check for Nameplate spelling 

---

src/app/suiteDb/custom-materials/custom-materials.service.ts

Issue 5657: Custom Gas Load Charge Materials not deleting

---

src/app/treasure-hunt/operation-costs/operation-costs.component.css
src/app/treasure-hunt/operation-costs/operation-costs.component.html
src/app/treasure-hunt/operation-costs/operation-costs.component.ts

Issue 6215: Calculate values in Facility Basics

---

src/app/calculator/compressed-air/air-leak/air-leak-form/air-leak-form.component.ts
src/app/calculator/compressed-air/air-leak/air-leak.component.ts
src/app/calculator/compressed-air/air-leak/air-leak.service.ts

#6257 
Was only able to find bugs where leak index != count of leaks array by doing:
- Add a handful of leaks, delete them, change utility type, add leaks again, reset.
- "   ", lastly generate example.
The way this is setup creates some race conditions - if we find more bugs it's time to refactor this.

Issue 6257 Air leak Bug hunt

---

src/app/compressed-air-assessment/compressed-air-assessment.component.css
src/app/compressed-air-assessment/compressed-air-assessment.component.html
src/app/compressed-air-assessment/compressed-air-assessment.service.ts
src/app/compressed-air-assessment/compressed-air-banner/calculator-tabs/calculator-tabs.component.html
src/app/compressed-air-assessment/compressed-air-banner/calculator-tabs/calculator-tabs.component.ts
src/app/compressed-air-assessment/compressed-air-banner/compressed-air-banner.component.css
src/app/compressed-air-assessment/compressed-air-banner/compressed-air-banner.component.html
src/app/compressed-air-assessment/compressed-air-banner/compressed-air-banner.component.ts
src/app/compressed-air-assessment/compressed-air-banner/setup-tabs/setup-tabs.component.html
src/app/compressed-air-assessment/compressed-air-banner/setup-tabs/setup-tabs.component.ts
src/app/compressed-air-assessment/compressed-air-report/compressed-air-report.component.html
src/app/compressed-air-assessment/compressed-air-report/compressed-air-report.component.ts
src/app/compressed-air-assessment/compressed-air-sankey/compressed-air-sankey.component.html
src/app/compressed-air-assessment/explore-opportunities/explore-opportunities.component.css
src/app/compressed-air-assessment/explore-opportunities/explore-opportunities.component.html
src/app/compressed-air-assessment/explore-opportunities/explore-opportunities.component.ts
src/app/compressed-air-assessment/system-profile/compressor-summary/compressor-summary.component.html
src/app/compressed-air-assessment/system-profile/profile-setup-form/profile-setup-form.component.html
src/app/compressed-air-assessment/system-profile/system-profile-annual-summary/system-profile-annual-summary.component.html

Issue 6262: Apply Mobile UI to Compressed Air

---

package-lock.json
package.json
src/app/dashboard/sidebar/version-modal/version-modal.component.html
src/app/log-tool/visualize/visualize-menu/visualize-menu.service.ts

Update wasm 1.3.0

---

src/app/dashboard/create-folder/create-folder.component.css
src/app/dashboard/create-inventory/create-inventory.component.css
src/app/shared/create-assessment-modal/create-assessment-modal.component.css

connects #6282
fixes the error where entering the create new folder/assessment/inventory modal from an assessment and in mobile view would make the modal too big

Issue 6282: Mobile UI - Add New Assessment Modal

---

src/app/motor-inventory/motor-inventory-banner/motor-inventory-banner.component.css
src/app/motor-inventory/motor-inventory-banner/motor-inventory-banner.component.html
src/app/motor-inventory/motor-inventory-banner/motor-inventory-banner.component.ts
src/app/motor-inventory/motor-inventory-banner/summary-filter/summary-filter.component.css
src/app/motor-inventory/motor-inventory-banner/summary-filter/summary-filter.component.html
src/app/motor-inventory/motor-inventory-banner/summary-filter/summary-filter.component.ts
src/app/motor-inventory/motor-inventory-setup/motor-catalog/select-motor-modal/filter-motors/filter-motors.component.html
src/app/motor-inventory/motor-inventory-setup/motor-inventory-setup.component.css
src/app/motor-inventory/motor-inventory-setup/motor-inventory-setup.component.html
src/app/motor-inventory/motor-inventory-setup/motor-inventory-setup.component.ts
src/app/motor-inventory/motor-inventory-setup/plant-setup/plant-setup.component.html
src/app/motor-inventory/motor-inventory-summary/inventory-summary-overview/inventory-summary-overview.component.html
src/app/motor-inventory/motor-inventory.component.css
src/app/motor-inventory/motor-inventory.component.html

Issue 6263: Apply Mobile UI to Motor Inventory

---

src/app/dashboard/directory-dashboard/directory-items/directory-item/directory-item.component.html
src/app/examples/mockPumpInventoryData.ts
src/app/indexedDb/inventory-db.service.ts
src/app/settings/assessment-settings/reset-data-modal/reset-data-modal.component.html
src/app/settings/assessment-settings/reset-data-modal/reset-data-modal.component.ts

Issue 6342 - Fix reset example assessments-items, directory item link

---

src/app/calculator/steam/turbine/turbine-form/turbine-form.component.html
src/app/phast/losses/operations/co2-savings-phast/co2-savings-phast.component.html
src/app/ssmt/boiler/boiler.component.html
src/app/ssmt/header/header-form/header-form.component.html
src/app/ssmt/operations/general-operations/general-operations.component.html
src/app/ssmt/operations/operating-costs/operating-costs.component.html
src/app/ssmt/turbine/condensing-turbine-form/condensing-turbine-form.component.html
src/app/ssmt/turbine/pressure-turbine-form/pressure-turbine-form.component.html

Issue 6400: Arrow key - Steam

---

package.json

Connects #6260 
Implemented npm run windows-clean for powershell

Issue 6260: Add package.json script for 'clean' on Windows

---

src/app/motor-inventory/motor-inventory.component.html
src/app/pump-inventory/pump-inventory-banner/pump-inventory-banner.component.css
src/app/pump-inventory/pump-inventory-banner/pump-inventory-banner.component.html
src/app/pump-inventory/pump-inventory-banner/pump-inventory-banner.component.ts
src/app/pump-inventory/pump-inventory-banner/summary-filter/summary-filter.component.css
src/app/pump-inventory/pump-inventory-banner/summary-filter/summary-filter.component.html
src/app/pump-inventory/pump-inventory-banner/summary-filter/summary-filter.component.ts
src/app/pump-inventory/pump-inventory-setup/plant-setup/plant-setup.component.html
src/app/pump-inventory/pump-inventory-setup/pump-inventory-setup.component.css
src/app/pump-inventory/pump-inventory-setup/pump-inventory-setup.component.html
src/app/pump-inventory/pump-inventory-setup/pump-inventory-setup.component.ts
src/app/pump-inventory/pump-inventory-summary/inventory-summary-overview/inventory-summary-overview.component.html
src/app/pump-inventory/pump-inventory.component.css
src/app/pump-inventory/pump-inventory.component.html

Issue 6264: Apply Mobile UI to Pump Inventory

---

src/app/core/core.component.html
src/app/indexedDb/settings-db.service.ts
src/app/tutorials/dashboard-tutorial/dashboard-tutorial.component.ts
src/app/tutorials/opening-tutorial/opening-tutorial.component.ts

Issue 6266 - disable tutorials in dev

---

src/app/dashboard/directory-dashboard/directory-items/assessment-item/assessment-item.component.ts
src/app/indexedDb/delete-data.service.ts
src/app/motor-inventory/motor-inventory-setup/motor-catalog/nameplate-data/nameplate-data.component.ts
src/app/motor-inventory/motor-inventory.ts
src/app/psat/integrate-pump-inventory/integrate-pump-inventory.component.ts
src/app/psat/motor/motor.component.html
src/app/psat/motor/motor.component.ts
src/app/psat/psat.component.html
src/app/psat/psat.component.ts
src/app/psat/pump-fluid/pump-fluid.component.html
src/app/psat/pump-fluid/pump-fluid.component.ts
src/app/pump-inventory/pump-inventory-setup/plant-setup/plant-setup.component.ts
src/app/pump-inventory/pump-inventory-setup/pump-catalog/fluid-catalog/fluid-catalog.component.html
src/app/pump-inventory/pump-inventory-setup/pump-catalog/fluid-catalog/fluid-catalog.component.ts
src/app/pump-inventory/pump-inventory-setup/pump-catalog/pump-equipment-catalog/pump-equipment-catalog.component.html
src/app/pump-inventory/pump-inventory-setup/pump-catalog/pump-equipment-catalog/pump-equipment-catalog.component.ts
src/app/pump-inventory/pump-inventory-setup/pump-catalog/pump-motor-catalog/pump-motor-catalog.component.html
src/app/pump-inventory/pump-inventory-setup/pump-catalog/pump-motor-catalog/pump-motor-catalog.component.ts
src/app/pump-inventory/pump-inventory-setup/pump-catalog/system-catalog/system-catalog.component.html
src/app/pump-inventory/pump-inventory-setup/pump-catalog/system-catalog/system-catalog.component.ts
src/app/shared/assessment-integration/assessment-integration-status/assessment-integration-status.component.ts
src/app/shared/assessment-integration/integrations.ts
src/app/shared/assessment-integration/inventory-integration/inventory-integration.component.html
src/app/shared/assessment-integration/inventory-integration/inventory-integration.component.ts
src/app/shared/assessment-integration/motor-integration.service.ts
src/app/shared/assessment-integration/psat-integration.service.ts
src/assets/styles/integrations.css

Issue 6274 - Connect motor item to PSAT

---

src/app/treasure-hunt/treasure-hunt-report/treasure-hunt-ppt.service.ts

TH PPT fix

---

package.json
src/app/dashboard/sidebar/version-modal/version-modal.component.html
src/app/treasure-hunt/treasure-hunt-report/treasure-hunt-ppt.service.ts

Update wasm with patch release

Wasm 1.3.1

---

src/app/fsat/fsat-tabs/fsat-tabs.component.html
src/app/fsat/modify-conditions/modify-conditions-tabs/modify-conditions-tabs.component.css
src/app/fsat/modify-conditions/modify-conditions-tabs/modify-conditions-tabs.component.html
src/app/fsat/modify-conditions/modify-conditions-tabs/modify-conditions-tabs.component.ts
src/app/phast/losses/losses-tabs/losses-tabs.component.css
src/app/psat/modify-conditions/modify-conditions-tabs/modify-conditions-tabs.component.css
src/app/psat/modify-conditions/modify-conditions-tabs/modify-conditions-tabs.component.html
src/app/psat/modify-conditions/modify-conditions-tabs/modify-conditions-tabs.component.ts
src/app/psat/psat-tabs/psat-tabs.component.html
src/app/ssmt/modify-conditions/modify-conditions-tabs/modify-conditions-tabs.component.css
src/app/ssmt/modify-conditions/modify-conditions-tabs/modify-conditions-tabs.component.html
src/app/ssmt/modify-conditions/modify-conditions-tabs/modify-conditions-tabs.component.ts
src/app/ssmt/ssmt-tabs/ssmt-tabs.component.html
src/app/waste-water/waste-water-banner/modify-conditions-tabs/modify-conditions-tabs.component.css
src/app/waste-water/waste-water-banner/modify-conditions-tabs/modify-conditions-tabs.component.html
src/app/waste-water/waste-water-banner/modify-conditions-tabs/modify-conditions-tabs.component.ts
src/app/waste-water/waste-water-banner/setup-tabs/setup-tabs.component.css
src/app/waste-water/waste-water-banner/setup-tabs/setup-tabs.component.html

issue 6377: Assessment menu tab update

---

src/app/log-tool/visualize/visualize-menu/visualize-menu.service.ts

Issue 6371 - Check Data option exists when changing graph type

---

src/app/dashboard/dashboard.component.css
src/app/dashboard/dashboard.component.html
src/app/dashboard/dashboard.component.ts
src/app/dashboard/import-export/export-modal/export-modal.component.ts
src/app/dashboard/import-export/import-export.service.ts

Issue 6374 - Add loading screen to prevent user actions before os save window load

---

src/app/dashboard/landing-screen/landing-screen.component.css
src/app/dashboard/landing-screen/landing-screen.component.html
src/app/dashboard/landing-screen/measur/measur.component.css
src/app/dashboard/landing-screen/measur/measur.component.html
src/app/dashboard/landing-screen/measur/measur.component.ts

Issue 6376: Clean up home page for mobile UI

---

src/app/treasure-hunt/treasure-chest/treasure-chest-menu/calculator-type-dropdown/calculator-type-dropdown.component.css
src/app/treasure-hunt/treasure-chest/treasure-chest-menu/equipments-dropdown/equipments-dropdown.component.css
src/app/treasure-hunt/treasure-chest/treasure-chest-menu/teams-dropdown/teams-dropdown.component.css
src/app/treasure-hunt/treasure-chest/treasure-chest-menu/treasure-chest-menu.component.css
src/app/treasure-hunt/treasure-chest/treasure-chest-menu/treasure-chest-menu.component.html
src/app/treasure-hunt/treasure-chest/treasure-chest-menu/treasure-chest-menu.component.ts
src/app/treasure-hunt/treasure-chest/treasure-chest-menu/utility-type-dropdown/utility-type-dropdown.component.css

Issue 6416: Treasure Hunt export opportunities button 

---

src/app/indexedDb/assessment-db.service.ts
src/app/shared/helper-services/update-data.service.ts

Issue 5750 Only check to update old versions one time

---

src/app/fsat/fsat-warning.service.ts
src/app/fsat/operations/operations.component.html
src/app/psat/psat-warning.service.ts
src/app/psat/pump-operations/pump-operations.component.html
src/app/psat/pump-operations/pump-operations.service.ts

Issue 5994 - Remove max for electricity costs

---

src/app/calculator/steam/stack-loss/stack-loss-form/stack-loss-by-mass/stack-loss-by-mass.component.html
src/app/calculator/steam/stack-loss/stack-loss-form/stack-loss-by-volume/stack-loss-by-volume.component.html
src/app/calculator/steam/stack-loss/stack-loss-help/stack-loss-help.component.html
src/app/calculator/steam/stack-loss/stack-loss.service.ts

#5919 
Remove user field for moisture in combustion air
Fix expected unit sent to suite
update example vals

Issue 5919 - Update moisture in combustion stack loss calc

---

src/app/compressed-air-assessment/compressed-air-assessment.component.html
src/app/compressed-air-assessment/compressed-air-assessment.component.ts
src/app/compressed-air-assessment/compressed-air-assessment.module.ts
src/app/compressed-air-assessment/compressed-air-assessment.service.ts
src/app/compressed-air-assessment/compressed-air-banner/compressed-air-banner.component.css
src/app/compressed-air-assessment/compressed-air-banner/compressed-air-banner.component.html
src/app/compressed-air-assessment/compressed-air-banner/compressed-air-banner.component.ts
src/app/shared/import-export/export-modal/export-modal.component.ts
src/app/shared/import-export/export.service.ts

Issue 6421: Compressed Air export btn

---

src/app/dashboard/directory-dashboard/directory-dashboard-menu/directory-dashboard-menu.component.ts

issue 6473: Copy Items btn bug

---

src/app/fsat/fsat-banner/fsat-banner.component.css
src/app/fsat/fsat-banner/fsat-banner.component.html
src/app/fsat/fsat-banner/fsat-banner.component.ts
src/app/fsat/fsat.component.html
src/app/fsat/fsat.component.ts
src/app/fsat/fsat.module.ts
src/app/fsat/fsat.service.ts
src/app/psat/psat-banner/psat-banner.component.css

issue 6420: FSAT export btn

---

src/app/waste-water/waste-water-banner/waste-water-banner.component.css
src/app/waste-water/waste-water-banner/waste-water-banner.component.html
src/app/waste-water/waste-water-banner/waste-water-banner.component.ts
src/app/waste-water/waste-water.component.html
src/app/waste-water/waste-water.component.ts
src/app/waste-water/waste-water.module.ts
src/app/waste-water/waste-water.service.ts

issue 6422:  Waste Water export btn

---

src/app/treasure-hunt/treasure-hunt-banner/treasure-hunt-banner.component.css
src/app/treasure-hunt/treasure-hunt-banner/treasure-hunt-banner.component.html
src/app/treasure-hunt/treasure-hunt-banner/treasure-hunt-banner.component.ts
src/app/treasure-hunt/treasure-hunt.component.html
src/app/treasure-hunt/treasure-hunt.component.ts
src/app/treasure-hunt/treasure-hunt.module.ts
src/app/treasure-hunt/treasure-hunt.service.ts

issue 6418: Treasure Hunt Export btn

---

src/app/ssmt/ssmt-banner/ssmt-banner.component.css
src/app/ssmt/ssmt-banner/ssmt-banner.component.html
src/app/ssmt/ssmt-banner/ssmt-banner.component.ts
src/app/ssmt/ssmt.component.html
src/app/ssmt/ssmt.component.ts
src/app/ssmt/ssmt.module.ts
src/app/ssmt/ssmt.service.ts

issue 6429: Steam export btn

---

src/app/phast/phast-banner/phast-banner.component.css
src/app/phast/phast-banner/phast-banner.component.html
src/app/phast/phast-banner/phast-banner.component.ts
src/app/phast/phast.component.html
src/app/phast/phast.component.ts
src/app/phast/phast.module.ts
src/app/phast/phast.service.ts

issue 6413: Process Heating export btn

---

src/app/motor-inventory/motor-inventory-banner/motor-inventory-banner.component.css
src/app/motor-inventory/motor-inventory-banner/motor-inventory-banner.component.html
src/app/motor-inventory/motor-inventory-banner/motor-inventory-banner.component.ts
src/app/motor-inventory/motor-inventory.component.html
src/app/motor-inventory/motor-inventory.component.ts
src/app/motor-inventory/motor-inventory.module.ts
src/app/motor-inventory/motor-inventory.service.ts
src/app/pump-inventory/pump-inventory-banner/pump-inventory-banner.component.css
src/app/pump-inventory/pump-inventory-banner/pump-inventory-banner.component.html
src/app/pump-inventory/pump-inventory-banner/pump-inventory-banner.component.ts
src/app/pump-inventory/pump-inventory.component.html
src/app/pump-inventory/pump-inventory.component.ts
src/app/pump-inventory/pump-inventory.module.ts
src/app/pump-inventory/pump-inventory.service.ts
src/app/shared/import-export/export-modal/export-modal.component.ts
src/app/shared/import-export/export.service.ts

Issues 6432 & 6430: Pump and Motor Inventory export btn

---

src/app/dashboard/directory-dashboard/delete-items-modal/delete-items-modal.component.ts
src/app/dashboard/directory-dashboard/directory-dashboard.component.ts
src/app/dashboard/directory-dashboard/directory-items/inventory-item/inventory-item.component.css
src/app/dashboard/directory-dashboard/directory-items/inventory-item/inventory-item.component.html
src/app/dashboard/sidebar/directory-item/directory-item.component.ts
src/app/indexedDb/delete-data.service.ts

#6445 #6444 
- Make sure directoriy listings and UI are updated on delete
- Fix directory dashboard list view styling

Issue 6445, 6444 - Directory bugs/styling

---

src/app/calculator/compressed-air/air-leak/air-leak.component.ts
src/app/treasure-hunt/operation-costs/operation-costs.component.html
src/app/treasure-hunt/treasure-hunt-calculator-services/air-leak-treasure-hunt.service.ts

#6471 
#6257 
Merging in some fixes already published to last web hotfix

Issue 6257 6471 - Air leak hotfix into dev

---

scripts/download-stats.js
src/app/treasure-hunt/calculators/standalone-opportunity-sheet/energy-use-form/energy-use-form.component.css
src/app/treasure-hunt/calculators/standalone-opportunity-sheet/standalone-opportunity-sheet.component.css
src/app/treasure-hunt/calculators/standalone-opportunity-sheet/standalone-opportunity-sheet.component.html
src/assets/styles/two-panel.css

Issue 6481- Th big white space and small style tweaks

---

src/app/log-tool/log-tool-banner/log-tool-banner.component.css
src/app/log-tool/log-tool-banner/log-tool-banner.component.html
src/app/log-tool/log-tool-banner/log-tool-banner.component.ts
src/app/log-tool/log-tool.component.html

issue 6265 Apply Mobile UI to Data Explorer

---

src/app/phast/losses/charge-material/liquid-charge-material-form/liquid-charge-material-form.component.html
src/app/phast/losses/charge-material/solid-charge-material-form/solid-charge-material-form.component.html

Issue 6510, 6355 - Remove native validation on heat of reaction

---

src/assets/styles/two-panel.css

Issue 6458 - restore 100% width group labels

---

src/app/pump-inventory/pump-inventory-banner/pump-inventory-banner.component.html
src/app/pump-inventory/pump-inventory-banner/pump-inventory-banner.component.ts

Issue 6264

---

src/app/calculator/lighting/lighting-replacement/lighting-replacement-help/lighting-replacement-help.component.html

Issue 6476: Help text addition for lighting calc

---

src/app/phast/losses/losses.component.html

Issue 6500: PHAST styles bug

---

src/app/log-tool/data-setup/data-setup.component.ts
src/app/log-tool/data-setup/import-data/import-data.component.ts
src/app/log-tool/data-setup/map-time-data/map-time-data.component.html
src/app/log-tool/data-setup/refine-data/refine-data.component.ts
src/app/log-tool/data-setup/select-data-header/select-data-header.component.ts
src/app/log-tool/log-tool-data.service.ts
src/app/log-tool/log-tool-models.ts
src/app/log-tool/visualize/visualize-data/visualize-data.component.ts
src/app/log-tool/visualize/visualize-graph/visualize-graph.component.html
src/app/log-tool/visualize/visualize-graph/visualize-graph.component.ts
src/app/log-tool/visualize/visualize-sidebar/bin-data/bin-data.component.html
src/app/log-tool/visualize/visualize-sidebar/graph-series/graph-series.component.html
src/app/log-tool/visualize/visualize-sidebar/visualize-sidebar.component.css
src/app/log-tool/visualize/visualize-sidebar/visualize-sidebar.component.html
src/app/log-tool/visualize/visualize-sidebar/visualize-sidebar.service.ts
src/app/log-tool/visualize/visualize.service.ts

#6507 #6362 #6512
Combo of NV fixes and adding enhancement: setup/validation messaging
Main info on NV fixes is in 6507

Issue 6507, 6362 - Enforce header select, check data invalid, display msgs

---

src/app/calculator/steam/pipe-insulation-reduction/pipe-insulation-reduction-form/pipe-insulation-reduction-form.component.html
src/app/calculator/steam/pipe-insulation-reduction/pipe-insulation-reduction-form/pipe-insulation-reduction-form.component.ts
src/app/calculator/steam/pipe-insulation-reduction/pipe-insulation-reduction.service.ts
src/app/calculator/steam/tank-insulation-reduction/tank-insulation-reduction-form/tank-insulation-reduction-form.component.html
src/app/calculator/steam/tank-insulation-reduction/tank-insulation-reduction-form/tank-insulation-reduction-form.component.ts
src/app/calculator/steam/tank-insulation-reduction/tank-insulation-reduction.service.ts

Issue 6478: Remove validation from Insulation calc's efficiency field

---

src/app/compressed-air-assessment/explore-opportunities/explore-opportunities-results/explore-opportunities-results.component.html
src/app/fsat/fsat-results/fsat-results-panel/fsat-results-panel.component.html
src/app/psat/explore-opportunities/explore-opportunities-results/explore-opportunities-results.component.html
src/app/ssmt/ssmt-results-panel/ssmt-results-panel/ssmt-results-panel.component.html
src/app/waste-water/results-panel/results-table/results-table.component.html

connects #6335 
also removed the percent gauges in the results tables in PSAT, FSAT, SSMT, waste water and compressed air

Issue 6335: Mobile UI Explore Opps

---

src/app/phast/losses/energy-input-exhaust-gas-losses/energy-input-exhaust-gas-form/energy-input-exhaust-gas-form.component.ts
src/app/phast/losses/energy-input-exhaust-gas-losses/energy-input-exhaust-gas-losses.component.ts
src/app/phast/losses/energy-input-exhaust-gas-losses/energy-input-exhaust-gas.service.ts
src/app/phast/losses/energy-input/energy-input.component.ts
src/app/phast/losses/energy-input/energy-input.service.ts
src/app/phast/losses/losses-tabs/energy-input-exhaust-gas-tab/energy-input-exhaust-gas-tab.component.ts
src/app/phast/losses/losses-tabs/energy-input-tab/energy-input-tab.component.ts
src/app/phast/phast-results.service.ts
src/app/phast/phast-valid.service.ts
src/app/phast/phast.service.ts
src/app/tools-suite-api/process-heating-api.service.ts

#6537 
fixed available heat result
#6539 
fixed - energy input  exhaust gas tab not checking energyInputheatDelivered warning
fixed - energy input tab - was not checking energy input heat delivered
fixed - energy input tab - not checking warnings on modification
remove "heat warning" exhaust gas temp warning (field no longer used)
remove energy input exhaust gas method call to suite

Issue 6537 6539 - PHAST electrotech

---

src/app/log-tool/visualize/visualize-graph/visualize-graph.component.html
src/app/log-tool/visualize/visualize-sidebar/graph-series/graph-series.component.html
src/app/log-tool/visualize/visualize-sidebar/visualize-sidebar.component.css
src/app/log-tool/visualize/visualize.component.html
src/app/log-tool/visualize/visualize.component.ts

Issue 6553 - Fix various scroll issues

---

src/app/compressed-air-assessment/compressed-air-report/compressed-air-report.component.html
src/app/compressed-air-assessment/compressed-air-sankey/compressed-air-sankey.component.html
src/app/compressed-air-assessment/compressed-air-sankey/compressed-air-sankey.component.ts
src/app/compressed-air-assessment/compressed-air-sankey/power-sankey/power-sankey.component.ts
src/app/shared/print-options-menu/print-options-menu.component.html
src/app/shared/print-options-menu/print-options-menu.component.ts

#6523 
Also adding better comments to explain async and timeout behavior in print functions

Issue 6523 - Fix multiple bugs re: general printing and ca sankey printing

---

src/app/psat/psatConstants.ts

Issue 6564 - Remove drive types from pumptypes constant

---

src/app/shared/phast-sankey/phast-sankey.component.ts
src/app/shared/phast-sankey/sankey.service.ts

Issue 6556 - Update sankey with electrical losses

---

src/app/treasure-hunt/treasure-hunt-gauge/treasure-hunt-gauge.component.html

Issue 6503 - Center TH charts

---

main.js

#6348 
Tested everything mentioned in issue, just needs one change below

Issue 6348 - Post web integration testing

---

src/app/calculator/steam/boiler-blowdown-rate/blowdown-rate-form/blowdown-rate-form.component.html
src/app/calculator/steam/boiler-blowdown-rate/blowdown-rate-form/blowdown-rate-form.component.ts
src/app/calculator/steam/boiler-blowdown-rate/blowdown-rate-results/blowdown-rate-results.component.html
src/app/calculator/steam/boiler-blowdown-rate/blowdown-rate-results/blowdown-rate-results.component.ts
src/app/calculator/steam/boiler-blowdown-rate/boiler-blowdown-rate.component.html
src/app/calculator/steam/boiler-blowdown-rate/boiler-blowdown-rate.component.ts
src/app/calculator/steam/boiler-blowdown-rate/boiler-blowdown-rate.service.ts
src/app/shared/models/treasure-hunt.ts
src/app/treasure-hunt/calculators/calculators.component.html
src/app/treasure-hunt/calculators/calculators.module.ts
src/app/treasure-hunt/calculators/calculators.service.ts
src/app/treasure-hunt/convert-input-data.service.ts
src/app/treasure-hunt/find-treasure/find-treasure.component.html
src/app/treasure-hunt/treasure-chest/export-opportunities/export-opportunities.component.html
src/app/treasure-hunt/treasure-chest/export-opportunities/export-opportunities.component.ts
src/app/treasure-hunt/treasure-chest/import-opportunities.service.ts
src/app/treasure-hunt/treasure-chest/opportunity-cards/opportunity-cards.service.ts
src/app/treasure-hunt/treasure-chest/opportunity-cards/sort-cards.service.ts
src/app/treasure-hunt/treasure-chest/treasure-chest-menu/calculator-type-dropdown/calculator-type-dropdown.component.ts
src/app/treasure-hunt/treasure-hunt-calculator-services/boiler-blowdown-rate-treasure-hunt.service.spec.ts
src/app/treasure-hunt/treasure-hunt-calculator-services/boiler-blowdown-rate-treasure-hunt.service.ts
src/app/treasure-hunt/treasure-hunt-calculator-services/treasure-hunt-opportunity.service.ts
src/app/treasure-hunt/treasure-hunt-report/opportunity-summary.service.ts
src/app/treasure-hunt/treasure-hunt.module.ts

Issue 5538: Add Boiler blowdown rate calc to TH

---

src/app/fsat/calculate-pressures/calculate-inlet-pressure/calculate-inlet-pressure.component.ts
src/app/fsat/calculate-pressures/calculate-outlet-pressure/calculate-outlet-pressure.component.ts
src/app/fsat/convert-fsat.service.ts
src/app/fsat/fan-field-data/fan-field-data.component.html
src/app/fsat/fan-field-data/fan-field-data.component.ts
src/app/fsat/fan-field-data/fan-field-data.service.ts
src/app/fsat/fsat.service.ts

#6573 
Remove outletpressure validation, fix calculation for inlet velocity …

Issue 6573 - Fan Field Data issues

---

src/app/shared/ssmt-sankey/ssmt-sankey.component.ts

Issue 6580 - Steam sankey returned condensate result

---

src/app/dashboard/acknowledgments-page/acknowledgments-page.component.html

move Mark's entry in acknowledgements

---

src/app/psat/compare.service.ts
src/app/psat/explore-opportunities/explore-opportunities-form/explore-opportunities-form.component.html
src/app/psat/explore-opportunities/explore-opportunities-form/explore-opportunities-form.component.ts
src/app/psat/explore-opportunities/explore-opportunities.module.ts
src/app/psat/integrate-pump-inventory/integrate-pump-inventory.component.html
src/app/psat/modify-conditions/modify-conditions.component.html
src/app/psat/motor/motor.component.html
src/app/psat/motor/motor.component.ts
src/app/psat/psat.component.ts
src/app/psat/pump-fluid/pump-fluid.component.html
src/app/psat/pump-fluid/pump-fluid.component.ts
src/app/pump-inventory/pump-inventory-setup/pump-catalog/pump-motor-catalog/pump-motor-catalog.component.ts
src/app/shared/connected-inventory/integration-state.service.ts
src/app/shared/connected-inventory/inventory-integration/inventory-integration.component.css
src/app/shared/connected-inventory/inventory-integration/inventory-integration.component.html
src/app/shared/connected-inventory/inventory-integration/inventory-integration.component.ts
src/app/shared/connected-inventory/psat-integration.service.ts
src/assets/styles/integrations.css

#6572 
Allowing user to better see integration status in modify-conditions/explore opps.

Issue 6572

---

src/app/phast/losses/losses-tabs/energy-input-exhaust-gas-tab/energy-input-exhaust-gas-tab.component.ts

Issue-6539 Use phast calculated result when not in energy input exgas form

---

src/app/treasure-hunt/find-treasure/find-treasure.component.html

Issue 5538: Hiding Boiler Blowdown rate calc in TH

---

src/app/fsat/explore-opportunities/explore-opportunities-form/explore-opportunities-form.component.html
src/app/fsat/explore-opportunities/explore-opportunities-form/explore-opportunities-form.component.ts
src/app/fsat/fsat-report/results-summary/results-summary.component.html
src/app/fsat/fsat-report/results-summary/results-summary.component.ts
src/app/phast/explore-phast-opportunities/explore-phast-opportunities-form/explore-phast-opportunities-form.component.html
src/app/phast/explore-phast-opportunities/explore-phast-opportunities-form/explore-phast-opportunities-form.component.ts
src/app/phast/explore-phast-opportunities/explore-phast-opportunities.module.ts
src/app/psat/explore-opportunities/explore-opportunities-form/explore-opportunities-form.component.html
src/app/shared/models/waste-water.ts
src/app/ssmt/explore-opportunities/explore-opportunities-form/explore-opportunities-form.component.html
src/app/ssmt/explore-opportunities/explore-opportunities-form/explore-opportunities-form.component.ts
src/app/waste-water/explore-opportunities/explore-opportunities-form/explore-opportunities-form.component.html
src/app/waste-water/explore-opportunities/explore-opportunities-form/explore-opportunities-form.component.ts
src/app/waste-water/waste-water-operations/waste-water-operations.component.html
src/app/waste-water/waste-water-operations/waste-water-operations.service.ts
src/app/waste-water/waste-water-report/result-data/result-data.component.html
src/app/waste-water/waste-water-report/result-data/result-data.component.ts

Issue 6509: Add "implementation cost" to "Explore Opportunities" Page

---

src/app/fsat/fsat.service.ts
src/app/phast/phast-integration.service.ts
src/app/psat/psat.service.ts
src/app/shared/assessment-integration/assessment-integration.component.html
src/app/shared/assessment-integration/assessment-integration.service.ts
src/app/shared/models/treasure-hunt.ts
src/app/treasure-hunt/calculators/assessment-opportunity/assessment-opportunity.component.html
src/app/treasure-hunt/calculators/standalone-opportunity-sheet/energy-use-form/energy-use-form.component.html
src/app/treasure-hunt/calculators/standalone-opportunity-sheet/energy-use-form/energy-use-form.component.ts
src/app/treasure-hunt/calculators/standalone-opportunity-sheet/opportunity-sheet-results/opportunity-sheet-results.component.html
src/app/treasure-hunt/treasure-chest/opportunity-cards/opportunity-cards.service.ts
src/app/treasure-hunt/treasure-hunt-calculator-services/assessment-opportunity.service.ts
src/app/treasure-hunt/treasure-hunt-report/opportunity-summary.service.ts
src/app/treasure-hunt/treasure-hunt-report/treasure-hunt-report.service.ts

#6453 
-Leaving explanatory comments
-Fix units, utility type categorization vs Mixed, co2 results for assessment ops

Issue 6453 - Assessment Opps

---

src/app/tools-suite-api/pumps-suite-api.service.ts

Issue 6588 - Deal with known null input sent to suite

---

src/app/calculator/steam/boiler-blowdown-rate/blowdown-rate-form/blowdown-rate-form.component.html
src/app/calculator/steam/boiler-blowdown-rate/blowdown-rate-form/blowdown-rate-form.component.ts
src/app/calculator/steam/boiler-blowdown-rate/boiler-blowdown-rate.module.ts
src/app/calculator/steam/boiler-blowdown-rate/boiler-blowdown-rate.service.ts
src/app/treasure-hunt/find-treasure/find-treasure.component.html

Issue 5538 & 6593 Boiler Blowdown rate clac

---

src/app/phast/phast-integration.service.ts
src/app/phast/phast-results.service.ts

#6453 
Leaving comments that explain old code setup when not expected behavior

Issue 6453 - Assessment Opportunity - Change to proper units, use yearly energy numbers

---

src/app/psat/motor/motor.component.ts

- await async method already awaiting, don't disable in mod

Issue 6607 - Async timing

---

src/app/calculator/compressed-air/air-leak/air-leak-form/decibel-method-form/decibel-method-form.component.html
src/app/calculator/compressed-air/air-leak/air-leak-help/air-leak-help.component.html
src/app/calculator/compressed-air/compressed-air-reduction/compressed-air-reduction.service.ts

Issue 6582: small CA issues

---

src/app/treasure-hunt/treasure-hunt-report/treasure-hunt-ppt/treasure-hunt-ppt.service.ts

#6615 
@rhernandez-intertech - At minimum this just stops the breaking. Please test to ensure the exported report is rendered as it should be and pick up this issue if not.

Issue 6615 - Don't try to push undefined opps

---

src/app/calculator/compressed-air/air-leak/air-leak-form/air-leak-form.service.ts

Issue 6582

---

src/app/report-rollup/report-summary-graphs/report-summary-graphs.component.html
src/app/report-rollup/report-summary-graphs/report-summary-pie-chart/report-summary-pie-chart.component.ts
src/app/shared/models/treasure-hunt.ts
src/app/treasure-hunt/treasure-chest/export-opportunities/export-opportunities.component.html
src/app/treasure-hunt/treasure-chest/export-opportunities/export-opportunities.component.ts
src/app/treasure-hunt/treasure-chest/import-opportunities.service.ts
src/app/treasure-hunt/treasure-hunt-calculator-services/assessment-opportunity.service.ts

Issue 6613, 6618 - Fix combined other energy, implement import/export

---

.github/workflows/main.yml
.github/workflows/web.yml

Required for Hayden to do automated build/release

Integrate CICD actions and config

---

src/app/fsat/fsat.service.ts
src/app/psat/psat.service.ts
src/app/waste-water/waste-water.service.ts

Issue 6604: CO2 emissions not calculating right away

---

package-lock.json
package.json
src/app/dashboard/sidebar/version-modal/version-modal.component.html

Issue 6608 - update version and release notes to 1.4.0

---

src/app/shared/assessment-integration/assessment-integration.component.ts

fix for report modal in TH assessment integration

---

src/app/treasure-hunt/treasure-chest/opportunity-cards/opportunity-cards.component.ts

Issue 6546 - TH copy opp - Create new array to trigger sort pipe

---

src/app/treasure-hunt/calculators/assessment-opportunity/assessment-opportunity-help/assessment-opportunity-help.component.html
src/app/treasure-hunt/calculators/assessment-opportunity/assessment-opportunity-help/assessment-opportunity-help.component.spec.ts
src/app/treasure-hunt/calculators/assessment-opportunity/assessment-opportunity-help/assessment-opportunity-help.component.ts
src/app/treasure-hunt/calculators/assessment-opportunity/assessment-opportunity.component.html
src/app/treasure-hunt/calculators/calculators.module.ts

Issue 6562 - Add assessment opportunity help text

---

src/app/phast/phast-report/phast-report.component.html

Issue 6641 - Print options should match phast template

---

src/app/compressed-air-assessment/compressed-air-assessment-results.service.ts
src/app/compressed-air-assessment/compressed-air-report/compressed-air-report.component.ts
src/app/shared/assessment-integration/assessment-integration.component.html
src/app/shared/assessment-integration/assessment-integration.component.ts
src/app/shared/assessment-integration/assessment-integration.module.ts
src/app/shared/assessment-integration/assessment-integration.service.ts

Issue 6560: CA assessment opportunities

---

src/app/calculator/furnaces/furnaces-list/furnaces-list.component.html
src/app/core/core.routing.ts
src/app/phast/phast-calculator-tabs/phast-calculator-tabs.component.html

Just adding comments to make it more immediately clear this calc is hidden.

Add comments for hidden calc

---

src/app/tools-suite-api/standalone-suite-api.service.ts

Issue 6648 - passing wrong property to OperatingCost binding method

---

src/app/calculator/system-and-equipment-curve/system-and-equipment-curve-graph/system-and-equipment-curve-graph.component.html
src/app/calculator/system-and-equipment-curve/system-and-equipment-curve-graph/system-and-equipment-curve-graph.component.ts
src/app/calculator/system-and-equipment-curve/system-and-equipment-curve-graph/system-and-equipment-curve-graph.service.ts

#6636 
Fix delete trace, reload data points after help tab, smarter point colors

Issue 6636 - System Curve graph fixup

---

src/app/compressed-air-assessment/compressed-air-assessment.service.ts
src/app/compressed-air-assessment/inventory/inventory.service.ts
src/app/compressed-air-assessment/system-profile/profile-setup-form/profile-setup-form.component.html
src/app/compressed-air-assessment/system-profile/profile-setup-form/profile-setup-form.component.ts
src/app/compressed-air-assessment/system-profile/system-profile-setup/compressor-ordering-table/compressor-ordering-table.component.ts
src/app/log-tool/day-type-analysis/day-type-menu/select-assessment-modal/select-assessment-modal.component.ts

#6672 
Reset trim selections when importing DE day types, ignore unused daytypes in trim validation

Issue 6672 - User bug report - Trim Selection on DE import and validation

---

.github/workflows/web.yml

Change to use `npm install` after switching to dynamically setting node version.

Updated web.yml - switch to npm install

---

src/app/calculator/fans/fan-analysis/fan-analysis-form/plane-data-form/traverse-planes/traverse-planes.component.html
src/app/calculator/utilities/weather-bins/weather-bins-form/bins-form/bins-form.component.css
src/app/calculator/utilities/weather-bins/weather-bins-form/bins-form/bins-form.component.html
src/app/calculator/utilities/weather-bins/weather-bins-form/bins-form/bins-form.component.ts
src/app/calculator/utilities/weather-bins/weather-bins-form/case-form/case-form.component.html
src/app/calculator/utilities/weather-bins/weather-bins-form/weather-bins-form.service.spec.ts
src/app/calculator/utilities/weather-bins/weather-bins-form/weather-bins-form.service.ts
src/app/calculator/utilities/weather-bins/weather-bins.module.ts
src/app/calculator/utilities/weather-bins/weather-bins.service.ts
src/app/dashboard/dashboard.component.ts
src/assets/styles/utilities.css

#6657 
- First part of dual binning, updates forms only
- Fixes a sidebar bug, and styling pollution from app-pressure-reading

Issue 6657 - Add starting bin value, multiple bins, use reactive forms

---

src/app/tools-suite-api/process-heating-api.service.ts

Issue 6685- Remove 100 multiplier on HHV

---

src/app/phast/phast-report/phast-report.component.html
src/app/phast/phast-report/report-sankey/report-sankey.component.html
src/app/phast/phast-report/report-sankey/report-sankey.component.ts
src/app/shared/phast-sankey/phast-sankey.component.ts

Issue 6641 - Fix sankey report, change sankey proportions, remove unused

---

src/app/shared/analytics/analytics.service.ts

Issue 6583 add measur_version

---

package-lock.json
package.json

Satisfy server security vuln messages

Update to node 20.11.1

---

src/app/settings/assessment-settings/reset-data-modal/reset-data-modal.component.ts

Issue 6703 - Call to update directorydb after reset

---

package-lock.json
src/app/compressed-air-assessment/compressed-air-banner/compressed-air-banner.component.html
src/app/compressed-air-assessment/compressed-air-banner/compressed-air-banner.component.ts
src/app/core/not-found/not-found.component.ts
src/app/fsat/fsat-banner/fsat-banner.component.html
src/app/fsat/fsat-banner/fsat-banner.component.ts
src/app/log-tool/log-tool-banner/log-tool-banner.component.html
src/app/log-tool/log-tool-banner/log-tool-banner.component.ts
src/app/motor-inventory/motor-inventory-banner/motor-inventory-banner.component.html
src/app/motor-inventory/motor-inventory-banner/motor-inventory-banner.component.ts
src/app/phast/phast-banner/phast-banner.component.html
src/app/phast/phast-banner/phast-banner.component.ts
src/app/psat/psat-banner/psat-banner.component.html
src/app/psat/psat-banner/psat-banner.component.ts
src/app/pump-inventory/pump-inventory-banner/pump-inventory-banner.component.html
src/app/pump-inventory/pump-inventory-banner/pump-inventory-banner.component.ts
src/app/shared/email-measur-data/email-measur-data-modal/email-measur-data-modal.component.css
src/app/shared/email-measur-data/email-measur-data-modal/email-measur-data-modal.component.html
src/app/shared/email-measur-data/email-measur-data.component.css
src/app/shared/email-measur-data/email-measur-data.component.html
src/app/shared/email-measur-data/email-measur-data.service.ts
src/app/shared/models/app.ts
src/app/ssmt/ssmt-banner/ssmt-banner.component.html
src/app/ssmt/ssmt-banner/ssmt-banner.component.ts
src/app/waste-water/waste-water-banner/waste-water-banner.component.html
src/app/waste-water/waste-water-banner/waste-water-banner.component.ts

#6696 
Also removing very old commented out code
data explorer email link intentionally commented out

Issue 6696 - Add email attachment functionality to assessment and inventories

---

src/app/calculator/steam/steam-reduction/steam-reduction.service.ts
src/app/calculator/utilities/natural-gas-reduction/natural-gas-reduction-results/natural-gas-reduction-results.component.html
src/app/calculator/utilities/natural-gas-reduction/natural-gas-reduction.service.ts

Issue 6732, 6709 - Send inputs in as fractions, move misplaced /yr

---

src/app/report-rollup/treasure-hunt-rollup/treasure-hunt-rollup.component.html

connects #6625 
the component to display the pie charts was missing input data, so that input data was added

Issue 6625

---

src/app/ssmt/operations/general-operations/general-operations.component.html
src/app/ssmt/ssmt-report/input-summary/operations-summary/operations-summary.component.html
src/app/ssmt/ssmt.component.ts

connects #6760 
sets the site power import of modifications on save. Modification should always match baseline.
Fix to bug in input summary of steam for site power import.

set mod site power import on save

---

src/app/calculator/process-cooling/fan-psychrometric/fan-psychrometric-chart/fan-psychrometric-chart.component.html
src/app/calculator/process-cooling/fan-psychrometric/fan-psychrometric-chart/fan-psychrometric-chart.component.ts
src/app/calculator/process-cooling/fan-psychrometric/fan-psychrometric-form/fan-psychrometric-form.component.ts
src/app/calculator/process-cooling/fan-psychrometric/fan-psychrometric-results/fan-psychrometric-results.component.html
src/app/calculator/process-cooling/fan-psychrometric/fan-psychrometric-results/fan-psychrometric-results.component.ts
src/app/calculator/process-cooling/fan-psychrometric/fan-psychrometric-table/fan-psychrometric-table.component.ts
src/app/calculator/process-cooling/fan-psychrometric/fan-psychrometric.component.css
src/app/calculator/process-cooling/fan-psychrometric/fan-psychrometric.component.html
src/app/calculator/process-cooling/fan-psychrometric/fan-psychrometric.component.ts
src/app/calculator/process-cooling/fan-psychrometric/fan-psychrometric.service.ts

Issue 5597: Psychrometric Chart Enhancements

---

src/app/compressed-air-assessment/compressed-air-banner/compressed-air-banner.component.ts
src/app/fsat/fsat-banner/fsat-banner.component.ts
src/app/motor-inventory/motor-inventory-banner/motor-inventory-banner.component.ts
src/app/phast/phast-banner/phast-banner.component.ts
src/app/psat/psat-banner/psat-banner.component.ts
src/app/pump-inventory/pump-inventory-banner/pump-inventory-banner.component.ts
src/app/shared/analytics/analyticsEventTypes.ts
src/app/shared/email-measur-data/email-measur-data.service.ts
src/app/ssmt/ssmt-banner/ssmt-banner.component.ts
src/app/treasure-hunt/treasure-hunt-banner/treasure-hunt-banner.component.ts
src/app/waste-water/waste-water-banner/waste-water-banner.component.ts

Issue 6721: Send analytics event on send email attachment feature

---

src/app/treasure-hunt/treasure-hunt-report/opportunity-summary.service.ts

Issue 6752 - Fix bug, let users continue to delete sole energy source

---

src/app/calculator/steam/pipe-insulation-reduction/pipe-insulation-reduction.service.ts
src/app/calculator/steam/tank-insulation-reduction/tank-insulation-reduction-form/tank-insulation-reduction-form.component.html
src/app/calculator/steam/tank-insulation-reduction/tank-insulation-reduction-form/tank-insulation-reduction-form.component.ts
src/app/calculator/steam/tank-insulation-reduction/tank-insulation-reduction.service.ts

Issue 6776: Tank Ins validation

---

src/app/calculator/system-and-equipment-curve/curve-data.service.ts
src/app/calculator/system-and-equipment-curve/equipment-curve/by-equation-form/by-equation-form.component.ts
src/app/calculator/system-and-equipment-curve/equipment-curve/equipment-curve.service.ts
src/app/calculator/system-and-equipment-curve/regression-equations.service.ts

Fix system/fan/pump curve examples in imperial and metric

---

src/app/compressed-air-assessment/compressed-air-assessment.service.ts
src/app/compressed-air-assessment/inventory/inventory.service.ts
src/app/compressed-air-assessment/system-profile/profile-setup-form/profile-setup-form.component.html
src/app/compressed-air-assessment/system-profile/profile-setup-form/profile-setup-form.component.ts
src/app/compressed-air-assessment/system-profile/system-profile-setup/compressor-ordering-table/compressor-ordering-table.component.ts
src/app/log-tool/day-type-analysis/day-type-menu/select-assessment-modal/select-assessment-modal.component.ts

HOTFIX Prod server - CA trim selection day types fix

---

src/app/calculator/furnaces/heat-cascading/heat-cascading-form.service.ts
src/app/calculator/furnaces/heat-cascading/heat-cascading-form/heat-cascading-form.component.html
src/app/calculator/furnaces/heat-cascading/heat-cascading.service.ts
src/app/calculator/furnaces/waste-heat/waste-heat.component.html
src/app/shared/models/phast/heatCascading.ts

issue 6751

---

src/app/calculator/utilities/weather-bins/weather-bins-heat-map/weather-bins-heat-map.component.html
src/app/calculator/utilities/weather-bins/weather-bins-heat-map/weather-bins-heat-map.component.ts

Issue 6659 Update - heatmap should output tab delimited data

---

src/app/calculator/steam/steam.service.ts
src/app/ssmt/calculate-losses.service.ts
src/app/ssmt/help-panel/help-panel.component.html
src/app/ssmt/ssmt-results-panel/ssmt-results-panel/ssmt-results-panel.component.html
src/app/ssmt/ssmt-results-panel/ssmt-results-panel/ssmt-results-panel.component.ts
src/app/ssmt/ssmt.component.html

Issue 6758 & 6759: Steam results fixes 

---

src/app/calculator/utilities/weather-bins/weather-bins-form/bins-form/bins-form.component.html
src/app/calculator/utilities/weather-bins/weather-bins-form/bins-form/bins-form.component.ts
src/app/calculator/utilities/weather-bins/weather-bins-form/weather-bins-form.service.ts
src/app/calculator/utilities/weather-bins/weather-bins.service.ts

#6375 
commenting out binCount feature and creating separate issue. Will do if time permits

Issue 6375 - Update validation, resize end bin 

---

src/app/shared/helper-services/update-data.service.ts
src/app/shared/import-export/import.service.ts

Issue 6821 - Add imported calculators prior to assessment version check

---

src/app/ssmt/calculate-losses.service.ts
src/app/ssmt/ssmt-results-panel/ssmt-results-panel/ssmt-results-panel.component.ts

Issue 6759

---

src/app/calculator/utilities/weather-bins/weather-bins-form/bins-form/bins-form.component.ts
src/app/calculator/utilities/weather-bins/weather-bins-form/weather-bins-form.service.ts
src/app/calculator/utilities/weather-bins/weather-bins.service.ts

#6375 
End of range remains in tail bin, update validation and defaults on param change

Issue 6375 - Add remaining range values to bin tail, reset param defaults on change

---

src/app/calculator/utilities/weather-bins/weather-bins-form/bins-form/bins-form.component.ts
src/app/calculator/utilities/weather-bins/weather-bins-form/weather-bins-form.service.ts

Issue 6375 - Force ng form change detection on param validator changes

---

src/app/calculator/utilities/weather-bins/weather-bins.service.ts

Issue 6375 - fix auto sub bins

---

package.json
src/app/dashboard/sidebar/version-modal/version-modal.component.html

Issue 6832 - Add version 1.5.0 release notes

---

src/app/phast/losses/operations/co2-savings-phast/co2-savings-phast.service.ts
src/app/phast/phast-integration.service.ts

Issue 6860, 6861

---

src/app/update-toast/update-toast.component.html

Issue 6869 - Add download link, make close button available

---

src/app/calculator/process-cooling/cooling-tower/cooling-tower.component.ts
src/app/calculator/process-cooling/cooling-tower/cooling-tower.service.ts

Issue 6863 - Use TH water cost, fix missing data update for water cost

---

src/app/calculator/utilities/co2-savings/co2-savings-form/co2FuelSavingsFuels.ts
src/app/ssmt/explore-opportunities/explore-opportunities-form/boiler-form/boiler-form.component.html
src/app/ssmt/explore-opportunities/explore-opportunities-form/boiler-form/boiler-form.component.ts
src/app/ssmt/operations/operations.component.ts

#6830 
Add missing Mixed Fuels, fuelType. Hide fuel type for mixed fuels
Stop assigning form data reference to global ssmt - certain input change timing/event will repopulate this with default value coming from baseline (ssmt.component updateModificationWithBaseline())

Issue 6830 - Fix SSMT Co2 field issues

---

process-flow-diagram-component/src/App.css
process-flow-diagram-component/src/components/Edges/SelfConnectingEdge.tsx
process-flow-diagram-component/src/components/Flow/FlowTypes.ts
process-flow-diagram-component/src/components/Flow/FlowUtils.ts
process-flow-diagram-component/src/components/Flow/index.tsx
process-flow-diagram-component/src/components/Nodes/ProcessFlowComponentNode.tsx
process-flow-diagram-component/src/components/Nodes/SplitterNode.tsx
process-flow-diagram-component/src/components/Nodes/SplitterNodeEight.tsx
process-flow-diagram-component/src/components/Nodes/SplitterNodeFour.tsx
process-flow-diagram-component/src/components/Sidebar/Sidebar.tsx
src/process-flow-types/shared-process-flow-types.ts

Issue 6877 - Add splitter nodes, circular connections, prototype custom splitter

---

src/app/dashboard/assessment.service.ts
src/app/examples/mockWaterAssessment.ts
src/app/shared/models/water-assessment.ts
src/app/water-process-diagram/water-diagram-connections.service.ts
src/app/water/discharge-outlet/discharge-outlet.component.css
src/app/water/discharge-outlet/discharge-outlet.component.html
src/app/water/discharge-outlet/discharge-outlet.component.spec.ts
src/app/water/discharge-outlet/discharge-outlet.component.ts
src/app/water/intake-source/intake-source.component.ts
src/app/water/water-assessment-connections.service.ts
src/app/water/water-assessment.component.html
src/app/water/water-assessment.service.ts
src/app/water/water-banner/setup-tabs/setup-tabs.component.html
src/app/water/water-banner/setup-tabs/setup-tabs.component.ts
src/app/water/water-system-component.service.ts
src/app/water/water-using-system/water-using-system.component.ts
src/app/water/water.module.ts
src/app/water/waterConstants.ts
src/process-flow-types/shared-process-flow-types.ts

Issue 6771 - UI for intake/discharge, fix lost splitters node sync

---

src/app/calculator/utilities/power-factor-correction/power-factor-correction-form/power-factor-correction-form.component.css
src/app/calculator/utilities/power-factor-correction/power-factor-correction-form/power-factor-correction-form.component.html
src/app/calculator/utilities/power-factor-correction/power-factor-correction-form/power-factor-correction-form.component.ts
src/app/calculator/utilities/power-factor-correction/power-factor-correction-help/power-factor-correction-help.component.html
src/app/calculator/utilities/power-factor-correction/power-factor-correction-results/power-factor-correction-results.component.css
src/app/calculator/utilities/power-factor-correction/power-factor-correction-results/power-factor-correction-results.component.html
src/app/calculator/utilities/power-factor-correction/power-factor-correction-results/power-factor-correction-results.component.ts
src/app/calculator/utilities/power-factor-correction/power-factor-correction.component.html
src/app/calculator/utilities/power-factor-correction/power-factor-correction.component.ts
src/app/calculator/utilities/power-factor-correction/power-factor-correction.service.ts

Issue 6744: Upgrade Power Factor Calculator

---

src/app/compressed-air-assessment/system-information/system-information.component.html

add load sharing option back in for testing

---

src/app/calculator/utilities/power-factor-correction/power-factor-correction-form/power-factor-correction-form.component.html
src/app/calculator/utilities/power-factor-correction/power-factor-correction-form/power-factor-correction-form.component.ts
src/app/calculator/utilities/power-factor-correction/power-factor-correction-results/power-factor-correction-results.component.html
src/app/calculator/utilities/power-factor-correction/power-factor-correction.component.ts
src/app/calculator/utilities/power-factor-correction/power-factor-correction.service.ts

issue 6921: PF Correction calc fixes

---

src/app/calculator/utilities/power-factor-correction/power-factor-correction-form/power-factor-correction-form.component.html
src/app/calculator/utilities/power-factor-correction/power-factor-correction-form/power-factor-correction-form.component.ts

Issue 6921

---

package-lock.json
src/app/compressed-air-assessment/explore-opportunities/improve-end-use-efficiency/improve-end-use-efficiency-item/improve-end-use-efficiency-item.component.html
src/app/compressed-air-assessment/explore-opportunities/improve-end-use-efficiency/improve-end-use-efficiency-item/improve-end-use-efficiency-item.component.ts
src/app/compressed-air-assessment/explore-opportunities/reduce-run-time/reduce-run-time.component.html
src/app/compressed-air-assessment/explore-opportunities/reduce-run-time/reduce-run-time.component.ts
src/app/compressed-air-assessment/system-profile/system-profile-setup/compressor-ordering-table/compressor-ordering-table.component.html
src/app/compressed-air-assessment/system-profile/system-profile-setup/compressor-ordering-table/compressor-ordering-table.component.ts

Issue 6934, 6933 - CA ordering table and profile updates

---

src/assets/styles/utilities.css

Issue 6944 - Add global checkbox hover

---

src/app/log-tool/log-tool-models.ts
src/app/log-tool/visualize/visualize-graph/visualize-graph.component.ts
src/app/log-tool/visualize/visualize.service.ts

Issue 6935 - Add spikelines to visualizer, toggle button for rangeslider

---

src/app/compressed-air-assessment/system-profile-graphs/system-profile-graphs.component.ts

Issue 6931 - Add peak line trace for profile airflow and power graphs

---

src/app/calculator/motors/replace-existing/replace-existing.service.ts
src/app/calculator/steam/pipe-insulation-reduction/pipe-insulation-reduction.service.ts
src/app/calculator/steam/tank-insulation-reduction/tank-insulation-reduction.component.ts
src/app/calculator/steam/tank-insulation-reduction/tank-insulation-reduction.service.ts
src/app/tools-suite-api/compressed-air-suite-api.service.ts
src/app/tools-suite-api/pumps-suite-api.service.ts

Issue 6912, 6929, 6951 - Pipe/Tank calc, Motor inventory Co2, WASM null input issues

---

src/app/calculator/steam/steam-reduction/steam-reduction-form/steam-reduction-form.component.html
src/app/calculator/steam/steam-reduction/steam-reduction-form/steam-reduction-form.component.ts
src/app/calculator/steam/steam-reduction/steam-reduction.component.ts
src/app/calculator/steam/steam-reduction/steam-reduction.service.ts
src/app/shared/models/standalone.ts
src/app/tools-suite-api/calculator-suite-api.service.ts

Issue 6686

---

src/app/calculator/steam/steam-reduction/steam-reduction-form/steam-reduction-form.component.html
src/app/calculator/steam/steam-reduction/steam-reduction-form/steam-reduction-form.component.ts
src/app/calculator/steam/steam-reduction/steam-reduction.component.ts
src/app/calculator/steam/steam-reduction/steam-reduction.service.ts
src/app/tools-suite-api/calculator-suite-api.service.ts

Issue 6686: Steam Reduction Calc Fixes

---

src/app/compressed-air-assessment/inventory/performance-points/performance-points-form.service.ts

Issue 6967 - Use Turndown dP for VFD high range

---

src/app/shared/assessment-co2-savings/assessment-co2-savings.service.ts

Issue 6981 - Fix tonne conversion on emissions output rate in compressed air

---

.github/workflows/electron.yml

Corrected `needs` requirement for release job.

Updated electron.yml - fix release conditional run requirement

---

src/app/dashboard/assessment.service.ts
src/app/examples/mockWaterAssessment.ts
src/app/shared/models/water-assessment.ts
src/app/water/convert-water-assessment.service.ts
src/app/water/system-basics/system-basics.component.html
src/app/water/system-basics/system-basics.component.ts
src/app/water/system-basics/system-basics.service.ts
src/app/water/waste-water-treatment/waste-water-treatment.component.html
src/app/water/waste-water-treatment/waste-water-treatment.component.ts
src/app/water/water-assessment-results.service.ts
src/app/water/water-treatment/water-treatment.component.html
src/app/water/water-treatment/water-treatment.component.ts
src/app/water/water-using-system/water-system-data/boiler-water/boiler-water.component.html
src/app/water/water-using-system/water-system-data/boiler-water/boiler-water.component.ts
src/app/water/water-using-system/water-system-data/cooling-tower/cooling-tower.component.html
src/app/water/water-using-system/water-system-data/cooling-tower/cooling-tower.component.ts
src/app/water/water-using-system/water-system-data/kitchen-restroom/kitchen-restroom.component.html
src/app/water/water-using-system/water-system-data/landscaping/landscaping.component.html
src/app/water/water-using-system/water-system-data/water-system-data.component.ts

Issue 6907 - Add conversions and system basics touch up

---

src/app/examples/mockWaterAssessment.ts
src/app/shared/models/water-assessment.ts
src/app/water/discharge-outlet/discharge-outlet.component.css
src/app/water/discharge-outlet/discharge-outlet.component.html
src/app/water/discharge-outlet/discharge-outlet.component.ts
src/app/water/intake-source/intake-source.component.css
src/app/water/intake-source/intake-source.component.html
src/app/water/intake-source/intake-source.component.ts
src/app/water/water-system-component.service.ts

Issue 6916 - Allow added motor energy in plant-wide intake and discharge

---

src/app/calculator/motors/full-load-amps/full-load-amps-help/full-load-amps-help.component.html
src/app/calculator/motors/motor-performance/motor-performance-help/motor-performance-help.component.html
src/app/calculator/motors/nema-energy-efficiency/nema-energy-efficiency-form/nema-energy-efficiency-form.component.html
src/app/calculator/motors/nema-energy-efficiency/nema-energy-efficiency-help/nema-energy-efficiency-help.component.html
src/app/fsat/explore-opportunities/explore-opportunities-form/rated-motor-form/rated-motor-form.component.html
src/app/fsat/help-panel/fan-motor-help/fan-motor-help.component.html
src/app/psat/explore-opportunities/explore-opportunities-help/explore-opportunities-help.component.html
src/app/psat/help-panel/motor-help/motor-help.component.html
src/app/pump-inventory/help-panel/pump-motor-help/pump-motor-help.component.html

Issue 7017 - Update efficiency class and efficiency help

---

src/app/core/core.component.ts
src/app/suiteDb/custom-materials/custom-solid-liquid-flue-gas-materials/custom-solid-liquid-flue-gas-materials.component.html
src/app/suiteDb/solid-liquid-flue-gas-material/solid-liquid-flue-gas-material.component.ts

Issue 7000, 7027  - Fix new fuel modal percentage, load custom materials on start

---

src/app/tools-suite-api/water-suite-api.service.ts
src/app/water/convert-water-assessment.service.ts
src/app/water/waste-water-treatment/waste-water-treatment-wrapper/waste-water-treatment-wrapper.component.html
src/app/water/water-assessment-results.service.ts
src/app/water/water-using-system/water-system-data/boiler-water/boiler-water.component.html
src/app/water/water-using-system/water-system-data/cooling-tower/cooling-tower.component.html
src/app/water/water-using-system/water-system-data/process-use/process-use.component.html
src/app/water/water-using-system/water-system-data/water-system-data.component.html
src/app/water/water-using-system/water-system-data/water-system-data.component.ts

#7034 Add conversions for water system results, fix load factor and units, …fix process water loss metrix

Issue 7034 - Fixes from Water System estimate flows testing

---

src/app/tools-suite-api/compressed-air-suite-api.service.ts

issue-7040: fix binding conversion for multi step unloading

---

src/app/log-tool/visualize/visualize-graph/visualize-graph.component.ts
src/app/log-tool/visualize/visualize-sidebar/graph-data-selection/graph-data-selection.component.html
src/app/log-tool/visualize/visualize-sidebar/graph-series-management/graph-series-management.component.html
src/app/log-tool/visualize/visualize-sidebar/graph-series-management/graph-series-management.component.ts

Issue 6940, 6769 DE visualize bugs

---

src/app/calculator/process-cooling/chiller-staging/chiller-staging-form.service.ts
src/app/calculator/process-cooling/chiller-staging/chiller-staging-form/chiller-staging-form.component.html
src/app/calculator/process-cooling/chiller-staging/chiller-staging-form/chiller-staging-form.component.ts

Issue 7035 - Validate bl and mod chiller load totals

---

src/app/log-tool/data-setup/map-time-data/map-time-data.component.html
src/app/log-tool/data-setup/map-time-data/map-time-data.component.ts
src/app/log-tool/log-tool-data.service.ts
src/app/log-tool/visualize/visualize-sidebar/graph-series/graph-series.component.html

Issue - 7005 Fix disabled histogram setting, add default data collect interval

---

src/app/tools-suite-api/compressed-air-suite-api.service.ts

fix loadunload

---

src/app/calculator/utilities/power-factor-correction/power-factor-correction-form/power-factor-correction-form.component.html
src/app/calculator/utilities/power-factor-correction/power-factor-correction-form/power-factor-correction-form.component.ts

Issue 6921: bug fix to PF Correction Calc

---

src/app/compressed-air-assessment/inventory/control-data/control-data.component.html
src/app/compressed-air-assessment/inventory/control-data/control-data.component.ts

issue 7040: fix multi step unloading disabled field and errors

---

src/app/tools-suite-api/pumps-suite-api.service.ts

#7031 #7032 
Reverting some changes based on suite 742

Change adjusted suite inputs from 7031, 7032

---

src/app/update-toast/update-toast.component.html

Issue 7006 - Release name now has MEASUR in it, remove plain text 'MEASUR'

---

src/app/core/core.service.ts
src/app/dashboard/directory-dashboard/directory-items/diagram-item/diagram-item.component.ts
src/app/indexedDb/dbConfig.ts
src/app/settings/assessment-settings/reset-data-modal/reset-data-modal.component.ts
src/app/shared/create-assessment-modal/create-assessment-modal.component.ts
src/app/shared/import-export/export.service.ts
src/app/shared/import-export/import.service.ts
src/app/shared/models/diagram.ts
src/app/water-process-diagram/water-diagram-connections.service.ts
src/app/water-process-diagram/water-process-diagram.component.html
src/app/water-process-diagram/water-process-diagram.component.ts
src/app/water/water-assessment-connections.service.ts

Issue 7083 Change diagram model, upgrade db

---

process-flow-diagram-component/src/components/Drawer/ComponentDataForm.tsx
process-flow-diagram-component/src/components/Drawer/ManageDataContextDrawer.tsx

Issue 6939 - Fix flow value input bug

---

src/app/calculator/standalone.service.ts
src/app/calculator/utilities/power-factor-triangle/power-factor-triangle-form/power-factor-triangle-form.component.css
src/app/calculator/utilities/power-factor-triangle/power-factor-triangle-form/power-factor-triangle-form.component.html
src/app/calculator/utilities/power-factor-triangle/power-factor-triangle-form/power-factor-triangle-form.component.spec.ts
src/app/calculator/utilities/power-factor-triangle/power-factor-triangle-form/power-factor-triangle-form.component.ts
src/app/calculator/utilities/power-factor-triangle/power-factor-triangle-help/power-factor-triangle-help.component.html
src/app/calculator/utilities/power-factor-triangle/power-factor-triangle-help/power-factor-triangle-help.component.spec.ts
src/app/calculator/utilities/power-factor-triangle/power-factor-triangle-help/power-factor-triangle-help.component.ts
src/app/calculator/utilities/power-factor-triangle/power-factor-triangle-results/power-factor-triangle-results.component.css
src/app/calculator/utilities/power-factor-triangle/power-factor-triangle-results/power-factor-triangle-results.component.html
src/app/calculator/utilities/power-factor-triangle/power-factor-triangle-results/power-factor-triangle-results.component.spec.ts
src/app/calculator/utilities/power-factor-triangle/power-factor-triangle-results/power-factor-triangle-results.component.ts
src/app/calculator/utilities/power-factor-triangle/power-factor-triangle.component.css
src/app/calculator/utilities/power-factor-triangle/power-factor-triangle.component.html
src/app/calculator/utilities/power-factor-triangle/power-factor-triangle.component.spec.ts
src/app/calculator/utilities/power-factor-triangle/power-factor-triangle.component.ts
src/app/calculator/utilities/power-factor-triangle/power-factor-triangle.module.ts
src/app/calculator/utilities/power-factor-triangle/power-factor-triangle.service.spec.ts
src/app/calculator/utilities/power-factor-triangle/power-factor-triangle.service.ts
src/app/calculator/utilities/utilities-list/utilities-list.component.html
src/app/calculator/utilities/utilities.module.ts
src/app/core/core.routing.ts
src/app/dashboard/sidebar/calculator-list/calculator-list.component.html
src/app/shared/analytics/analyticsEventTypes.ts
src/app/shared/models/standalone.ts
src/app/tools-suite-api/calculator-suite-api.service.ts

Issue 1947: Power Factor Triangle Calc

---

src/app/compressed-air-assessment/system-information/system-information.component.html

Turn on load sharing for compressed air team testing

uncomment load sharing option

---

src/app/calculator/steam/boiler-blowdown-rate/blowdown-rate-results/blowdown-rate-results.component.ts
src/app/calculator/steam/boiler-blowdown-rate/boiler-blowdown-rate.component.html
src/app/treasure-hunt/calculators/standalone-opportunity-sheet/opportunity-sheet.service.ts

Issues 6844 & 6922

---

src/app/compressed-air-assessment/compressed-air-sankey/power-sankey/power-sankey.service.ts

Fix conversion for power sankey psia to psig

---

src/app/calculator/furnaces/energy-equivalency/energy-equivalency-help/energy-equivalency-help.component.html
src/app/calculator/furnaces/energy-equivalency/energy-equivalency.component.html
src/app/calculator/furnaces/energy-use/energy-use-help/energy-use-help.component.html
src/app/calculator/furnaces/energy-use/energy-use.component.html
src/app/calculator/furnaces/furnaces-list/furnaces-list.component.html
src/app/dashboard/about-page/about-page.component.html
src/app/dashboard/acknowledgments-page/acknowledgments-page.component.html
src/app/phast/phast-calculator-tabs/phast-calculator-tabs.component.html

Issues 7075 7091 6852

---

src/app/fsat/fan-field-data/fan-field-data.component.ts
src/app/fsat/fan-field-data/fan-field-data.service.ts
src/app/fsat/fsat.component.html
src/app/fsat/fsat.component.ts
src/app/tools-suite-api/fans-suite-api.service.ts

#7095 
Has fixes for 1 and 2 mentioned in issue

Issue 7095 - Fan wasm fix

---

src/app/dashboard/assessment.service.ts
src/app/shared/create-assessment-modal/create-assessment-modal.component.ts

Issue 6763 - Fix folder cost settings as fsat, ssmt defaults

---

src/app/calculator/utilities/co2-savings/co2-savings-form/co2-savings-form.component.ts
src/app/calculator/utilities/co2-savings/co2-savings-results/co2-savings-results.component.html
src/app/calculator/utilities/co2-savings/co2-savings-results/co2-savings-results.component.ts
src/app/calculator/utilities/co2-savings/co2-savings.component.html
src/app/calculator/utilities/co2-savings/co2-savings.service.ts

Issue 7118 - Add conversion for metric emissions

---

src/app/calculator/utilities/power-factor-triangle/power-factor-triangle-results/power-factor-triangle-results.component.html
src/app/calculator/utilities/power-factor-triangle/power-factor-triangle-results/power-factor-triangle-results.component.ts
src/app/calculator/utilities/power-factor-triangle/power-factor-triangle.service.ts
src/app/shared/models/standalone.ts
src/app/tools-suite-api/calculator-suite-api.service.ts
src/app/tools-suite-api/suite-api-helper.service.ts

Issue 7117: PF Triangle bug fixes

---

src/app/calculator/compressed-air/compressed-air-reduction/compressed-air-reduction-form/compressed-air-reduction-form.component.html
src/app/calculator/compressed-air/compressed-air-reduction/compressed-air-reduction-form/compressed-air-reduction-form.component.ts
src/app/calculator/compressed-air/compressed-air-reduction/compressed-air-reduction.component.ts

Issue 6765 - Ca Reduction equipment add and remove

---

src/app/compressed-air-assessment/compressor-summary-table/compressor-summary-table.component.html
src/app/compressed-air-assessment/compressor-summary-table/compressor-summary-table.component.ts

Issue 7127 - Infinity Value should show 'no flow'

---

src/app/indexedDb/settings-db.service.ts
src/app/report-rollup/report-rollup.service.ts
src/app/settings/application-settings/application-settings.component.html
src/app/settings/assessment-settings/assessment-settings.component.html

Issue 7134 - Patch old user assessment and settings with emissionsUnit

---

src/app/treasure-hunt/treasure-hunt-report/treasure-hunt-ppt/treasure-hunt-ppt.service.ts

Issue 7045: TH PPT only makes silds for selected opps

---

src/app/calculator/utilities/power-factor-triangle/power-factor-triangle-form/power-factor-triangle-form.component.html
src/app/calculator/utilities/power-factor-triangle/power-factor-triangle-form/power-factor-triangle-form.component.ts
src/app/calculator/utilities/power-factor-triangle/power-factor-triangle-results/power-factor-triangle-results.component.ts
src/app/tools-suite-api/calculator-suite-api.service.ts

Issue 7117

---

src/app/calculator/steam/boiler/boiler-form/boiler-form.component.ts

#7143 Fix: boiler does not call calculate after modal

---

src/app/fsat/fsat.service.ts
src/app/psat/add-modification/add-modification.component.ts
src/app/psat/modification-list/modification-list.component.ts
src/app/psat/psat.component.ts
src/app/waste-water/add-modification-modal/add-modification-modal.component.ts
src/app/waste-water/explore-opportunities/explore-opportunities-form/explore-opportunities-form.component.ts
src/app/waste-water/explore-opportunities/explore-opportunities.component.ts
src/app/waste-water/modification-list-modal/modification-list-modal.component.ts

#7116 
co2SavingsProperty does not exist if operations tab is not visited

Issue 7116 - co2 values carrying over to mod

---

src/app/compressed-air-assessment/system-information/system-information.component.html

Issue 6114 - Change load sharing text

---

.github/workflows/electron.yml
.github/workflows/web.yml
package-lock.json
package.json
src/app/dashboard/sidebar/version-modal/version-modal.component.html

#7137 
Update version, packages, no longer need legacy-peer deps flag

Update app version, packages, version command

---

package-lock.json
process-flow-diagram-component/.eslintrc.cjs
process-flow-diagram-component/package-lock.json
process-flow-diagram-component/package.json
process-flow-diagram-component/src/components/Flow/FlowUtils.ts
process-flow-diagram-component/src/components/Flow/index.tsx
process-flow-diagram-component/src/components/Sidebar/DownloadButton.tsx

Issue 7088 - Set line type to smooth, upgrade TS, test SVG export

---

src/app/treasure-hunt/treasure-hunt-report/treasure-hunt-ppt/treasure-hunt-ppt-properties.service.ts
src/app/treasure-hunt/treasure-hunt-report/treasure-hunt-ppt/treasure-hunt-ppt.service.ts

Issue 6712 TH PPT

---

process-flow-diagram-component/src/App.css
process-flow-diagram-component/src/components/Flow/FlowTypes.ts
process-flow-diagram-component/src/components/Flow/FlowUtils.ts
process-flow-diagram-component/src/components/Flow/index.tsx
process-flow-diagram-component/src/components/Nodes/KnownLossNode.tsx
src/app/shared/models/water-assessment.ts
src/app/water-process-diagram/water-diagram-connections.service.ts
src/app/water/waste-water-treatment/waste-water-treatment.service.ts
src/app/water/water-assessment-connections.service.ts
src/app/water/water-system-component.service.ts
src/app/water/water-treatment/water-treatment.service.ts
src/app/water/water-using-system/water-using-system.service.ts
src/process-flow-types/shared-process-flow-types.ts

Issue 7069 - Fix lost known-loss on create assessment, change for consistent naming

---

src/app/treasure-hunt/treasure-hunt-report/treasure-hunt-ppt/treasure-hunt-ppt.service.ts

Issue 6712: TH PPT 

---

process-flow-diagram-component/src/components/Drawer/ComponentDataForm.tsx
process-flow-diagram-component/src/components/Drawer/CustomizeEdge.tsx
process-flow-diagram-component/src/components/Drawer/ManageDataContextDrawer.tsx
process-flow-diagram-component/src/components/Edges/DiagramBaseEdge.tsx
process-flow-diagram-component/src/components/Flow/FlowUtils.ts
src/app/dashboard/assessment.service.ts
src/app/examples/mockWaterAssessment.ts
src/app/examples/mockWaterDiagram.ts
src/app/shared/import-export/export-modal/export-modal.component.html
src/app/shared/models/water-assessment.ts
src/app/water-process-diagram/water-diagram-connections.service.ts
src/app/water/convert-water-assessment.service.ts
src/app/water/discharge-outlet/discharge-outlet.component.ts
src/app/water/intake-source/intake-source.component.ts
src/app/water/water-assessment-connections.service.ts
src/app/water/water-assessment-results.service.ts
src/app/water/water-banner/setup-tabs/setup-tabs.component.ts
src/app/water/water-system-component.service.ts
src/app/water/water-using-system/added-energy/added-energy.component.html
src/app/water/water-using-system/added-energy/added-energy.component.ts
src/app/water/water-using-system/added-energy/motor-energy/motor-energy.service.ts
src/app/water/water-using-system/water-system-data/water-system-data.component.css
src/app/water/water-using-system/water-system-data/water-system-data.component.html
src/app/water/water-using-system/water-system-data/water-system-data.component.ts
src/app/water/water-using-system/water-using-system.service.ts
src/process-flow-types/shared-process-flow-types.ts

Issue 7160 - Populate assessment water flows from diagram, fix BS modal

---

src/app/treasure-hunt/treasure-hunt-report/treasure-hunt-ppt/treasure-hunt-ppt.service.ts
src/app/treasure-hunt/treasure-hunt-report/treasure-hunt-report.component.html
src/app/treasure-hunt/treasure-hunt-report/treasure-hunt-report.component.ts

Issue 7165

---

src/app/calculator/utilities/power-factor-triangle/power-factor-triangle-form/power-factor-triangle-form.component.html
src/app/calculator/utilities/power-factor-triangle/power-factor-triangle.module.ts

Issue 7172 

---

src/app/calculator/utilities/power-factor-triangle/power-factor-triangle-form/power-factor-triangle-form.component.ts
src/app/calculator/utilities/power-factor-triangle/power-factor-triangle-results/power-factor-triangle-results.component.ts

issue 7172

---

src/app/calculator/pumps/head-tool/head-tool.component.html
src/app/compressed-air-assessment/compressed-air-assessment.service.ts
src/app/settings/assessment-settings/reset-data-modal/reset-data-modal.component.html
src/app/settings/tutorial-settings/tutorial-settings.component.html
src/app/settings/tutorial-settings/tutorial-settings.component.ts

Issue 7162, 7174, 7173 - Head calc, settings message, CA validation

---

src/app/treasure-hunt/treasure-hunt-report/opportunity-payback.service.ts
src/app/treasure-hunt/treasure-hunt-report/treasure-hunt-ppt/treasure-hunt-ppt-table.service.ts
src/app/treasure-hunt/treasure-hunt-report/treasure-hunt-ppt/treasure-hunt-ppt.service.ts

Issue 6778

---

src/app/calculator/motors/motor-performance/motor-performance-chart.service.ts
src/app/shared/models/plotting.ts

Issue 7199 - Motor Performance change hover, tick formatting

---

src/app/calculator/motors/motor-performance/motor-performance-help/motor-performance-help.component.html
src/app/calculator/pumps/achievable-efficiency/achievable-efficiency-help/achievable-efficiency-help.component.html

Issue 7206 - Change motor perf and achievably eff help text

---

package-lock.json
package.json
src/app/dashboard/sidebar/version-modal/version-modal.component.html

MEASUR Add changes for version 1.5.5

---

src/app/water/convert-water-assessment.service.ts
src/app/water/water-assessment-results.service.ts

Issue 7215 - Fix landscaping conversion bug

---

process-flow-diagram-component/src/components/Drawer/ContinuousSlider.tsx
process-flow-diagram-component/src/components/Drawer/MenuSidebar.tsx
process-flow-diagram-component/src/components/Edges/DiagramBaseEdge.tsx
process-flow-diagram-component/src/components/Flow/FlowUtils.ts
process-flow-diagram-component/src/components/Flow/index.tsx
src/app/examples/mockWaterDiagram.ts
src/process-flow-types/shared-process-flow-types.ts

Issue 7192 - Add slider control for flow label size

---

process-flow-diagram-component/src/AppWebComponent.tsx

Water web component - Set aria-hidden false, web component elements need to receive focus

---

process-flow-diagram-component/src/components/Drawer/ComponentDataForm.tsx
process-flow-diagram-component/src/components/Drawer/DataDrawer.tsx
process-flow-diagram-component/src/components/Drawer/MenuSidebar.tsx
process-flow-diagram-component/src/components/Drawer/SideDrawer.tsx
process-flow-diagram-component/src/components/Flow/FlowUtils.ts
process-flow-diagram-component/src/components/Flow/index.tsx
process-flow-diagram-component/src/components/Nodes/ProcessFlowComponentNode.tsx
src/app/examples/mockWaterAssessment.ts
src/app/examples/mockWaterDiagram.ts
src/app/shared/process-flow-diagram-wrapper/process-flow-diagram.service.ts
src/app/water-process-diagram/water-process-diagram.service.ts
src/process-flow-types/shared-process-flow-types.ts

Issue 7193, 7194

---

src/app/calculator/utilities/power-factor-correction/power-factor-correction.component.ts
src/app/calculator/utilities/power-factor-correction/power-factor-correction.service.ts
src/app/shared/helper-services/update-data.service.ts
src/app/shared/models/treasure-hunt.ts
src/app/treasure-hunt/calculators/calculators.service.ts
src/app/treasure-hunt/treasure-chest/export-opportunities/export-opportunities.component.html
src/app/treasure-hunt/treasure-chest/export-opportunities/export-opportunities.component.ts
src/app/treasure-hunt/treasure-chest/import-opportunities.service.ts
src/app/treasure-hunt/treasure-chest/opportunity-cards/opportunity-cards.component.css
src/app/treasure-hunt/treasure-chest/opportunity-cards/opportunity-cards.component.html
src/app/treasure-hunt/treasure-chest/opportunity-cards/opportunity-cards.service.ts
src/app/treasure-hunt/treasure-chest/opportunity-cards/sort-cards.service.ts
src/app/treasure-hunt/treasure-chest/treasure-chest-menu/calculator-type-dropdown/calculator-type-dropdown.component.ts
src/app/treasure-hunt/treasure-hunt-calculator-services/power-factor-correction-treasure-hunt.service.ts
src/app/treasure-hunt/treasure-hunt-calculator-services/treasure-hunt-opportunity.service.ts
src/app/treasure-hunt/treasure-hunt-report/opportunity-summary.service.ts

Issue 7204

---

process-flow-diagram-component/src/components/Drawer/MenuSidebar.tsx
process-flow-diagram-component/src/components/Drawer/SideDrawer.tsx

Issue 7191 - Add help text for key commands

---

src/app/calculator/pumps/achievable-efficiency/achievable-efficiency-graph/achievable-efficiency-graph.component.html
src/app/calculator/pumps/achievable-efficiency/achievable-efficiency-graph/achievable-efficiency-graph.component.ts
src/app/calculator/pumps/achievable-efficiency/achievable-efficiency.component.ts
src/app/calculator/pumps/achievable-efficiency/achievable-efficiency.service.ts

Issue 7207 - Fix graph updated rendering, change avg-max column and points displayed

---

process-flow-diagram-component/src/components/Drawer/MenuSidebar.tsx
process-flow-diagram-component/src/components/Flow/index.tsx

#7088 
Number 2 from 7088, plus font/text touch up

Adjust diagram fit view to be more zoomed out

---

process-flow-diagram-component/src/App.css
process-flow-diagram-component/src/components/Drawer/ColorPicker.tsx
process-flow-diagram-component/src/components/Drawer/ComponentHandles.tsx
process-flow-diagram-component/src/components/Drawer/CustomizeEdge.tsx
process-flow-diagram-component/src/components/Drawer/CustomizeNode.tsx
process-flow-diagram-component/src/components/Drawer/DataDrawer.tsx
process-flow-diagram-component/src/components/Drawer/PresetColorPicker.tsx
process-flow-diagram-component/src/components/Flow/FlowUtils.ts
process-flow-diagram-component/src/components/Flow/index.tsx
process-flow-diagram-component/src/components/Nodes/SplitterNode.tsx
src/app/examples/mockWaterDiagram.ts
src/app/shared/process-flow-diagram-wrapper/process-flow-diagram.service.ts
src/app/water-process-diagram/water-process-diagram.service.ts
src/process-flow-types/shared-process-flow-types.ts

Issue 7190

---

process-flow-diagram-component/src/components/Drawer/DataDrawer.tsx
process-flow-diagram-component/src/components/Drawer/MenuSidebar.tsx
process-flow-diagram-component/src/components/Drawer/TabPanel.tsx

Separate delete buttons in UI, use secondary

---

src/app/shared/models/treasure-hunt.ts
src/app/treasure-hunt/treasure-hunt-calculator-services/power-factor-correction-treasure-hunt.service.ts
src/app/treasure-hunt/treasure-hunt-report/executive-summary/executive-summary-table/executive-summary-table.component.html
src/app/treasure-hunt/treasure-hunt-report/treasure-hunt-report.service.ts

Issue 7204: adding 'Other' costs savings data to TH report

---

src/app/calculator/motors/motor-performance/motor-performance-chart.service.ts
src/app/calculator/motors/motor-performance/motor-performance-chart/motor-performance-chart.component.html
src/app/psat/psat.service.ts

Issue 7214  - Revise decimal precision on calculated motor perf

---

src/app/treasure-hunt/treasure-hunt-calculator-services/air-heating-treasure-hunt.service.ts
src/app/treasure-hunt/treasure-hunt-calculator-services/air-leak-treasure-hunt.service.ts
src/app/treasure-hunt/treasure-hunt-calculator-services/boiler-blowdown-rate-treasure-hunt.service.ts
src/app/treasure-hunt/treasure-hunt-calculator-services/ca-pressure-reduction-treasure-hunt.service.ts
src/app/treasure-hunt/treasure-hunt-calculator-services/ca-reduction-treasure-hunt.service.ts
src/app/treasure-hunt/treasure-hunt-calculator-services/chiller-performance-treasure-hunt.service.ts
src/app/treasure-hunt/treasure-hunt-calculator-services/chiller-staging-treasure-hunt.service.ts
src/app/treasure-hunt/treasure-hunt-calculator-services/cooling-tower-basin-treasure-hunt.service.ts
src/app/treasure-hunt/treasure-hunt-calculator-services/cooling-tower-fan-treasure-hunt.service.ts
src/app/treasure-hunt/treasure-hunt-calculator-services/cooling-tower-makeup-treasure-hunt.service.ts
src/app/treasure-hunt/treasure-hunt-calculator-services/electricity-reduction-treasure-hunt.service.ts
src/app/treasure-hunt/treasure-hunt-calculator-services/flue-gas-treasure-hunt.service.ts
src/app/treasure-hunt/treasure-hunt-calculator-services/heat-cascading-treasure-hunt.service.ts
src/app/treasure-hunt/treasure-hunt-calculator-services/leakage-treasure-hunt.service.ts
src/app/treasure-hunt/treasure-hunt-calculator-services/lighting-replacement-treasure-hunt.service.ts
src/app/treasure-hunt/treasure-hunt-calculator-services/motor-drive-treasure-hunt.service.ts
src/app/treasure-hunt/treasure-hunt-calculator-services/natural-gas-reduction-treasure-hunt.service.ts
src/app/treasure-hunt/treasure-hunt-calculator-services/opening-treasure-hunt.service.ts
src/app/treasure-hunt/treasure-hunt-calculator-services/pipe-insulation-treasure-hunt.service.ts
src/app/treasure-hunt/treasure-hunt-calculator-services/power-factor-correction-treasure-hunt.service.ts
src/app/treasure-hunt/treasure-hunt-calculator-services/replace-existing-treasure-hunt.service.ts
src/app/treasure-hunt/treasure-hunt-calculator-services/steam-reduction-treasure-hunt.service.ts
src/app/treasure-hunt/treasure-hunt-calculator-services/tank-insulation-treasure-hunt.service.ts
src/app/treasure-hunt/treasure-hunt-calculator-services/wall-treasure-hunt.service.ts
src/app/treasure-hunt/treasure-hunt-calculator-services/waste-heat-treasure-hunt.service.ts
src/app/treasure-hunt/treasure-hunt-calculator-services/water-heating-treasure-hunt.service.ts
src/app/treasure-hunt/treasure-hunt-calculator-services/water-reduction-treasure-hunt.service.ts

Issue 7234

---

src/app/treasure-hunt/treasure-hunt-report/treasure-hunt-ppt/treasure-hunt-ppt-table.service.ts
src/app/treasure-hunt/treasure-hunt-report/treasure-hunt-ppt/treasure-hunt-ppt.service.ts

issue 7244 TH PPT bug from PF calc fix

---

src/app/calculator/motors/motor-performance/motor-performance-chart/motor-performance-chart.component.ts
src/app/calculator/pumps/achievable-efficiency/achievable-efficiency-graph/achievable-efficiency-graph.component.html

Issue 7214, 7207 - changes to motor perf decimal precision, add label to pump eff

---

package-lock.json
package.json
src/app/dashboard/sidebar/version-modal/version-modal.component.html

Issue 7236 - Update release notes and version to 1.5.6

---

src/app/shared/models/water-assessment.ts
src/app/water/results-panel/water-balance-results-table/water-balance-results-table.component.css
src/app/water/results-panel/water-balance-results-table/water-balance-results-table.component.html
src/app/water/water-assessment-results.service.ts

Add grouping table headers, adjust results

---

package.json
src/app/dashboard/sidebar/version-modal/version-modal.component.html

Update version to hotfix 1.5.7, update notes

---

src/app/calculator/steam/boiler-blowdown-rate/boiler-blowdown-rate.service.ts

Issue 7260 - Fix: boiler blowdown calculation

---

package.json
src/app/dashboard/sidebar/version-modal/version-modal.component.html

Update version for patch release 1.5.8

---

src/app/compressed-air-assessment/explore-opportunities/explore-opportunities.component.ts

#7274 
Fix setFlowReallocationSummaries should use systemBasics electricityCost, not settings

Issue 7274 - Incorrect Flow Reallocation EEM cost savings

---

src/app/compressed-air-assessment/compressed-air-assessment-results.service.ts
src/app/compressed-air-assessment/compressed-air-assessment.service.ts
src/app/dashboard/directory-dashboard/directory-items/assessment-item/compressed-air-assessment-card/compressed-air-assessment-card.component.ts

#7264 
Detail in issue
Fixed: check for missing trimSelection compressorId's, defense conditions on results, set setupDone on import

Issue 7264 Fixed: CA Trim selection with no PP bug

---

src/app/compressed-air-assessment/profile-summary-table/profile-summary-table.component.html
src/app/compressed-air-assessment/profile-summary-table/profile-summary-table.component.ts
src/app/compressed-air-assessment/system-profile/system-profile-setup/compressor-ordering-table/compressor-ordering-table.component.html

Issue 6986 - Show Base/Trim instead of order in ordering table and summary table

---

src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-inventory-setup.component.css
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-inventory-setup.component.html
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-inventory-setup.module.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/plant-setup/plant-setup.component.html
src/app/compressed-air-inventory/compressed-air-inventory-setup/plant-setup/plant-setup.component.spec.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/plant-setup/plant-setup.component.ts

Plant setup form added to CA inventory

---

src/app/dashboard/sidebar/sidebar.component.ts

Issue 7177 - Bug fix electron updateAvailable still present in web, use separate observables

---

package-lock.json
package.json
src/app/dashboard/sidebar/version-modal/version-modal.component.html

Update develop version to 1.5.9

---

src/app/compressed-air-inventory/compressed-air-inventory-banner/compressed-air-inventory-banner.component.css
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-inventory-setup.component.css
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-inventory-setup.component.html
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-inventory-setup.module.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/department-catalog-table/department-catalog-table.component.html
src/app/compressed-air-inventory/compressed-air-inventory-setup/department-catalog-table/department-catalog-table.component.spec.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/department-catalog-table/department-catalog-table.component.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/department-setup/department-setup.component.html
src/app/compressed-air-inventory/compressed-air-inventory-setup/department-setup/department-setup.component.spec.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/department-setup/department-setup.component.ts
src/app/compressed-air-inventory/compressed-air-inventory.component.css
src/app/compressed-air-inventory/compressed-air-inventory.service.ts
src/app/compressed-air-inventory/compressed-air-inventory.ts
src/app/dashboard/directory-dashboard/directory-items/inventory-item/inventory-item.component.css
src/app/dashboard/landing-screen/landing-screen.component.css
src/app/examples/mockCompressedAirInventoryData.ts
src/assets/styles/assessment-banner.css
src/assets/styles/tabs.css
src/assets/styles/two-panel.css

Issue 7271 Department tab

---

process-flow-diagram-component/src/App.css
process-flow-diagram-component/src/components/Drawer/ComponentDataForm.tsx
process-flow-diagram-component/src/components/Drawer/ContinuousSlider.tsx
process-flow-diagram-component/src/components/Drawer/MenuSidebar.tsx
process-flow-diagram-component/src/components/Drawer/SideDrawer.tsx
process-flow-diagram-component/src/components/Drawer/TabPanel.tsx
process-flow-diagram-component/src/components/Edges/DiagramBaseEdge.tsx
process-flow-diagram-component/src/components/Flow/FlowUtils.ts
process-flow-diagram-component/src/components/Flow/index.tsx
process-flow-diagram-component/src/components/Nodes/ProcessFlowComponentNode.tsx
src/app/examples/mockWaterDiagram.ts
src/process-flow-types/shared-process-flow-types.ts

Issue 7240 - Add Decimal Precision Option, menu bar style cleanup

---

src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-inventory-setup.component.html
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-inventory-setup.module.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-properties/compressed-air-controls-properties/compressed-air-controls-properties.component.html
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-properties/compressed-air-controls-properties/compressed-air-controls-properties.component.spec.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-properties/compressed-air-controls-properties/compressed-air-controls-properties.component.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-properties/compressed-air-motor-properties/compressed-air-motor-properties.component.css
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-properties/compressed-air-motor-properties/compressed-air-motor-properties.component.html
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-properties/compressed-air-motor-properties/compressed-air-motor-properties.component.spec.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-properties/compressed-air-motor-properties/compressed-air-motor-properties.component.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-properties/compressed-air-properties.component.html
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-properties/compressed-air-properties.component.spec.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-properties/compressed-air-properties.component.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-properties/compressed-air-properties.module.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-properties/design-details-properties/design-details-properties.component.html
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-properties/design-details-properties/design-details-properties.component.spec.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-properties/design-details-properties/design-details-properties.component.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-properties/nameplate-data-properties/nameplate-data-properties.component.css
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-properties/nameplate-data-properties/nameplate-data-properties.component.html
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-properties/nameplate-data-properties/nameplate-data-properties.component.spec.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-properties/nameplate-data-properties/nameplate-data-properties.component.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-properties/performance-points-properties/performance-points-properties.component.html
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-properties/performance-points-properties/performance-points-properties.component.spec.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-properties/performance-points-properties/performance-points-properties.component.ts
src/app/compressed-air-inventory/compressed-air-inventory.service.ts
src/app/compressed-air-inventory/compressed-air-inventory.ts
src/app/compressed-air-inventory/help-panel/help-panel.component.html
src/app/examples/mockCompressedAirInventoryData.ts

Issue 7252

---

src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-catalog/centrifugal-specifics-catalog/centrifugal-specifics-catalog.component.html
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-catalog/centrifugal-specifics-catalog/centrifugal-specifics-catalog.component.spec.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-catalog/centrifugal-specifics-catalog/centrifugal-specifics-catalog.component.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-catalog/centrifugal-specifics-catalog/centrifugal-specifics-catalog.service.spec.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-catalog/centrifugal-specifics-catalog/centrifugal-specifics-catalog.service.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-catalog/compressed-air-catalog.component.html
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-catalog/compressed-air-catalog.module.ts

Issue 7312: Centrifugal Specifics into catalog

---

src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-catalog/compressed-air-catalog.module.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-catalog/performance-points-catalog/max-full-flow-catalog/max-full-flow-catalog.component.html
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-catalog/performance-points-catalog/max-full-flow-catalog/max-full-flow-catalog.component.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-catalog/performance-points-catalog/max-full-flow-catalog/max-full-flow-catalog.service.spec.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-catalog/performance-points-catalog/max-full-flow-catalog/max-full-flow-catalog.service.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-catalog/performance-points-catalog/performance-points-catalog.component.html

Issue 7305: added max full flow PP to catalog

---

src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-catalog/compressed-air-catalog.module.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-catalog/performance-points-catalog/mid-turndown-catalog/mid-turndown-catalog.component.css
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-catalog/performance-points-catalog/mid-turndown-catalog/mid-turndown-catalog.component.html
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-catalog/performance-points-catalog/mid-turndown-catalog/mid-turndown-catalog.component.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-catalog/performance-points-catalog/mid-turndown-catalog/mid-turndown-catalog.service.spec.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-catalog/performance-points-catalog/mid-turndown-catalog/mid-turndown-catalog.service.ts

Issue 7307: add mid turndown PP to catalog

---

src/app/calculator/process-cooling/chiller-staging/chiller-staging.component.ts
src/app/calculator/process-cooling/chiller-staging/chiller-staging.service.ts

Issue 7324 - Fix: Return chiller staging output when input invalid

---

src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-catalog/compressed-air-catalog.module.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-catalog/performance-points-catalog/mid-turndown-catalog/mid-turndown-catalog.component.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-catalog/performance-points-catalog/performance-points-catalog.component.html
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-catalog/performance-points-catalog/turndown-catalog/turndown-catalog.component.css
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-catalog/performance-points-catalog/turndown-catalog/turndown-catalog.component.html
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-catalog/performance-points-catalog/turndown-catalog/turndown-catalog.component.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-catalog/performance-points-catalog/turndown-catalog/turndown-catalog.service.spec.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-catalog/performance-points-catalog/turndown-catalog/turndown-catalog.service.ts

Issue 7308: added turndown PP to catalog

---

src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-catalog/compressed-air-catalog.module.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-catalog/performance-points-catalog/mid-turndown-catalog/mid-turndown-catalog.component.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-catalog/performance-points-catalog/no-load-catalog/no-load-catalog.component.css
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-catalog/performance-points-catalog/no-load-catalog/no-load-catalog.component.html
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-catalog/performance-points-catalog/no-load-catalog/no-load-catalog.component.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-catalog/performance-points-catalog/no-load-catalog/no-load-catalog.service.spec.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-catalog/performance-points-catalog/no-load-catalog/no-load-catalog.service.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-catalog/performance-points-catalog/performance-points-catalog.component.html
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-catalog/performance-points-catalog/turndown-catalog/turndown-catalog.component.css
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-catalog/performance-points-catalog/turndown-catalog/turndown-catalog.component.html
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-catalog/performance-points-catalog/turndown-catalog/turndown-catalog.component.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-catalog/performance-points-catalog/turndown-catalog/turndown-catalog.service.spec.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-catalog/performance-points-catalog/turndown-catalog/turndown-catalog.service.ts

Issue 7309: added no load PP to catalog

---

process-flow-diagram-component/README.md
process-flow-diagram-component/src/components/Diagram/Diagram.tsx
process-flow-diagram-component/src/components/Diagram/FlowUtils.ts
process-flow-diagram-component/src/components/Diagram/diagramReducer.ts
process-flow-diagram-component/src/components/Diagram/store.ts
process-flow-diagram-component/src/components/Drawer/ComponentConnectionList.tsx
process-flow-diagram-component/src/components/Drawer/DataDrawer.tsx
process-flow-diagram-component/src/components/Drawer/DownloadButton.tsx
process-flow-diagram-component/src/components/Forms/ComponentDataForm.tsx
process-flow-diagram-component/src/components/Forms/DischargeFlowForm.tsx
process-flow-diagram-component/src/components/Forms/SourceFlowForm.tsx
process-flow-diagram-component/src/components/Nodes/ProcessFlowComponentNode.tsx
process-flow-diagram-component/src/validation/Validation.ts
src/app/examples/mockWaterDiagram.ts
src/app/water-process-diagram/water-process-diagram.service.ts
src/app/water/convert-water-assessment.service.ts
src/process-flow-types/shared-process-flow-types.ts

6918 - Simplify form state and rendering for validation

---

src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-catalog/performance-points-catalog/full-load-catalog/full-load-catalog.component.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-catalog/performance-points-catalog/max-full-flow-catalog/max-full-flow-catalog.component.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-catalog/performance-points-catalog/mid-turndown-catalog/mid-turndown-catalog.component.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-catalog/performance-points-catalog/turndown-catalog/turndown-catalog.component.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/plant-setup/plant-setup.component.html
src/app/compressed-air-inventory/compressed-air-inventory-setup/plant-setup/plant-setup.component.ts
src/app/compressed-air-inventory/compressed-air-inventory.service.ts
src/app/compressed-air-inventory/compressed-air-inventory.ts
src/app/examples/mockCompressedAirInventoryData.ts

Issue 7321: added atmospheric Pressure to plant setup

---

src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-catalog/performance-points-catalog/full-load-catalog/full-load-catalog.component.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-catalog/performance-points-catalog/max-full-flow-catalog/max-full-flow-catalog.component.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-catalog/performance-points-catalog/mid-turndown-catalog/mid-turndown-catalog.component.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-catalog/performance-points-catalog/turndown-catalog/turndown-catalog.component.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-inventory-setup.module.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/plant-setup/plant-setup.component.html
src/app/compressed-air-inventory/compressed-air-inventory-setup/plant-setup/plant-setup.component.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/plant-setup/system-capacity-inventory-modal/system-capacity-inventory-modal.component.css
src/app/compressed-air-inventory/compressed-air-inventory-setup/plant-setup/system-capacity-inventory-modal/system-capacity-inventory-modal.component.html
src/app/compressed-air-inventory/compressed-air-inventory-setup/plant-setup/system-capacity-inventory-modal/system-capacity-inventory-modal.component.spec.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/plant-setup/system-capacity-inventory-modal/system-capacity-inventory-modal.component.ts
src/app/compressed-air-inventory/compressed-air-inventory.service.ts
src/app/compressed-air-inventory/compressed-air-inventory.ts
src/app/examples/mockCompressedAirInventoryData.ts

Issue 7332: Added System Capacity Modal to CA Inventory 

---

src/app/calculator/steam/feedwater-economizer/feedwater-economizer-form/feedwater-economizer-form.component.html
src/app/calculator/steam/feedwater-economizer/feedwater-economizer-form/feedwater-economizer-form.component.ts
src/app/calculator/steam/feedwater-economizer/feedwater-economizer-help/feedwater-economizer-help.component.html
src/app/calculator/steam/feedwater-economizer/feedwater-economizer.module.ts

Issue 6854 - Add moisture calc modal, use html symbols for Fahrenheit

---

src/app/calculator/motors/motor-performance/motor-performance-chart.service.ts

Issue 7214 - Fix conflicting formatting propeties

---

src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-catalog/compressed-air-catalog.component.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-catalog/performance-points-catalog/performance-points-catalog.service.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/department-catalog-table/department-catalog-table.component.css
src/app/compressed-air-inventory/compressed-air-inventory-setup/department-catalog-table/department-catalog-table.component.html
src/app/compressed-air-inventory/compressed-air-inventory-setup/department-catalog-table/department-catalog-table.component.ts

Issue 7297: added department catalog table to CA Inventory

---

src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-catalog/compressed-air-catalog.component.html
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-catalog/compressed-air-catalog.module.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-catalog/compressed-air-catalog.service.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-catalog/field-measurements-catalog/field-measurements-catalog.component.css
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-catalog/field-measurements-catalog/field-measurements-catalog.component.html
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-catalog/field-measurements-catalog/field-measurements-catalog.component.spec.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-catalog/field-measurements-catalog/field-measurements-catalog.component.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-catalog/field-measurements-catalog/field-measurements-catalog.service.spec.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-catalog/field-measurements-catalog/field-measurements-catalog.service.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-properties/compressed-air-properties.component.html
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-properties/compressed-air-properties.module.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-properties/field-measurements-properties/field-measurements-properties.component.css
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-properties/field-measurements-properties/field-measurements-properties.component.html
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-properties/field-measurements-properties/field-measurements-properties.component.spec.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-properties/field-measurements-properties/field-measurements-properties.component.ts
src/app/compressed-air-inventory/compressed-air-inventory.service.ts
src/app/compressed-air-inventory/compressed-air-inventory.ts
src/app/examples/mockCompressedAirInventoryData.ts

Issue 7347: Add Field Measurements to Compressed Air Inventory Properties and Catalog

---

src/app/compressed-air-inventory/compressed-air-inventory-setup/department-catalog-table/department-catalog-table.component.ts

Issue 7348: added op hours to department catalog table

---

package-lock.json
package.json
process-flow-diagram-component/src/components/Diagram/Diagram.tsx
process-flow-diagram-component/src/components/Diagram/FlowUtils.ts
process-flow-diagram-component/src/components/Diagram/diagramReducer.ts
process-flow-diagram-component/src/components/Diagram/store.ts
process-flow-diagram-component/src/components/Edges/DiagramBaseEdge.tsx
process-flow-diagram-component/src/components/Forms/ComponentDataForm.tsx
process-flow-diagram-component/src/components/Forms/DischargeFlowForm.tsx
process-flow-diagram-component/src/components/Forms/DistributeTotalFlowField.tsx
process-flow-diagram-component/src/components/Forms/SourceFlowForm.tsx
process-flow-diagram-component/src/components/Forms/UpdateNodeErrors.tsx
process-flow-diagram-component/src/validation/InvalidIcon.tsx
process-flow-diagram-component/src/validation/Validation.ts
src/process-flow-types/shared-process-flow-types.ts

Issue 6918 - Add drawer validation

---

src/app/compressed-air-inventory/compressed-air-inventory.component.ts

Issue 7319: CA Inventory fixed saving bug

---

src/app/compressed-air-inventory/compressed-air-inventory-banner/compressed-air-inventory-banner.component.html
src/app/compressed-air-inventory/compressed-air-inventory-banner/compressed-air-inventory-banner.component.ts
src/app/compressed-air-inventory/compressed-air-inventory.service.ts

Issue 7363: added system tabs to catalog page

---

.gitignore
process-flow-diagram-component/src/components/Diagram/FlowUtils.ts
process-flow-diagram-component/src/components/Diagram/store.ts
src/app/water/results-panel/water-balance-results-table/water-balance-results-table.component.html
src/app/water/results-panel/water-balance-results-table/water-balance-results-table.component.ts
src/app/water/water-assessment-results.service.ts

7322 - Fix bugs

---

src/app/water/discharge-outlet/discharge-outlet.component.html
src/app/water/discharge-outlet/discharge-outlet.component.ts
src/app/water/intake-source/intake-source.component.html
src/app/water/intake-source/intake-source.component.ts
src/app/water/water-assessment.service.ts
src/app/water/water-banner/setup-tabs/setup-tabs.component.html
src/app/water/water-banner/setup-tabs/setup-tabs.component.ts

Issue 7241 - Change to Intake/discharge sub tabs

---

process-flow-diagram-component/src/components/Drawer/ManageComponent.tsx
process-flow-diagram-component/src/components/Forms/ComponentDataForm.tsx
process-flow-diagram-component/src/components/Forms/DischargeFlowForm.tsx
process-flow-diagram-component/src/components/Forms/ToggleDataEntryUnitButton.tsx
process-flow-diagram-component/src/components/StyledMUI/AccordianComponents.tsx

Issue 7383 - Discharge and data drawer enhancements

---

process-flow-diagram-component/src/components/Drawer/MenuSidebar.tsx

Issue 7389 - fix disabled tab, hide summing node

---

process-flow-diagram-component/src/components/Diagram/FlowUtils.ts
process-flow-diagram-component/src/components/Diagram/diagramReducer.ts
process-flow-diagram-component/src/components/Forms/ComponentDataForm.tsx
process-flow-diagram-component/src/components/Forms/DischargeFlowForm.tsx
process-flow-diagram-component/src/components/Forms/SourceFlowForm.tsx
process-flow-diagram-component/src/components/Forms/WaterSystemEstimation/EstimateWaterSystem.tsx
process-flow-diagram-component/src/validation/Validation.ts
src/app/water/water-assessment-connections.service.ts
src/app/water/water-using-system/water-system-data/water-system-data.component.html
src/app/water/water-using-system/water-system-data/water-system-data.component.ts
src/process-flow-types/shared-process-flow-types.ts

Issue 7383 - Update Discharge form Total Known Losses and Water In Product

---

src/app/water/waste-water-treatment/waste-water-treatment-wrapper/waste-water-treatment-wrapper.component.ts
src/app/water/water-assessment.component.html
src/app/water/water-banner/setup-tabs/setup-tabs.component.html
src/app/water/water-banner/setup-tabs/setup-tabs.component.ts
src/app/water/water-treatment/water-treatment-wrapper/water-treatment-wrapper.component.ts

Issue 7337 - Water treatment vs in-system treatment touch ups

---

src/app/compressed-air-inventory/compressed-air-inventory-banner/compressed-air-inventory-banner.component.html
src/app/compressed-air-inventory/compressed-air-inventory-setup/end-uses-setup/end-uses-setup.component.html
src/app/compressed-air-inventory/compressed-air-inventory-setup/end-uses-setup/end-uses-setup.component.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/end-uses-setup/end-uses.service.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/end-uses-table/end-uses-table.component.html
src/app/compressed-air-inventory/compressed-air-inventory-setup/end-uses-table/end-uses-table.component.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/system-setup/system-setup.component.html
src/app/compressed-air-inventory/compressed-air-inventory.service.ts
src/app/compressed-air-inventory/compressed-air-inventory.ts
src/app/examples/mockCompressedAirInventoryData.ts

Issue 7404

---

process-flow-diagram-component/src/components/Forms/ComponentDataForm.tsx

Issue 7429 - Update system imbalance alerts

---

process-flow-diagram-component/src/components/Diagram/store.ts
process-flow-diagram-component/src/components/Drawer/DiagramResults.tsx
process-flow-diagram-component/src/components/Drawer/MenuSidebar.tsx
process-flow-diagram-component/src/components/Forms/ComponentDataForm.tsx
src/app/examples/mockWaterAssessment.ts
src/app/water/discharge-outlet/discharge-outlet.component.html
src/app/water/intake-source/intake-source.component.html
src/app/water/waste-water-treatment/waste-water-treatment.component.html
src/app/water/waste-water-treatment/waste-water-treatment.service.ts
src/app/water/water-system-component.service.ts
src/app/water/water-treatment/water-treatment.component.html
src/app/water/water-treatment/water-treatment.service.ts
src/app/water/water-using-system/water-system-data/water-system-data.component.html
src/app/water/water-using-system/water-using-system.service.ts
src/process-flow-lib/water/logic/results.ts
src/process-flow-lib/water/logic/water-components.ts
src/process-flow-lib/water/types/diagram.ts

Issue 7415 - Prototype rough cost calculations, add cost field to diagram

---

src/app/calculator/steam/feedwater-economizer/feedwater-economizer-help/feedwater-economizer-help.component.html

Issue 7374: Feedwater Economizer calculator help

---

process-flow-diagram-component/src/components/Diagram/diagramReducer.ts
process-flow-diagram-component/src/components/Diagram/store.ts
process-flow-diagram-component/src/components/Drawer/DiagramResults.tsx
process-flow-diagram-component/src/components/Drawer/MenuSidebar.tsx
process-flow-diagram-component/src/components/Forms/ComponentDataForm.tsx
src/app/water/water-assessment-connections.service.ts
src/app/water/water-assessment.service.ts
src/app/water/water-system-component.service.ts
src/app/water/water-using-system/added-energy/added-energy.component.ts
src/app/water/water-using-system/added-energy/motor-energy/motor-energy.service.ts
src/process-flow-lib/water/logic/results.ts
src/process-flow-lib/water/logic/water-components.ts

Issue 7415 - Update Costs and results

---

process-flow-diagram-component/src/components/Drawer/DiagramResults.tsx
process-flow-diagram-component/src/components/Forms/ComponentDataForm.tsx
src/app/water/discharge-outlet/discharge-outlet.component.html
src/app/water/discharge-outlet/discharge-outlet.component.ts
src/app/water/intake-source/intake-source.component.html
src/app/water/intake-source/intake-source.component.ts
src/app/water/results-panel/results-panel.component.html
src/app/water/water-assessment.service.ts
src/app/water/water-banner/setup-tabs/setup-tabs.component.html
src/app/water/water-banner/setup-tabs/setup-tabs.component.ts
src/app/water/water-using-system/water-system-data/water-system-data-modal/water-system-data-modal.component.ts
src/app/water/water-using-system/water-system-data/water-system-data.component.html
src/process-flow-lib/water/logic/results.ts
src/process-flow-lib/water/logic/water-components.ts

Issue 7434 - Hotfix bugs

---

src/app/calculator/furnaces/flue-gas/flue-gas-form-mass/flue-gas-form-mass.component.html
src/app/calculator/furnaces/flue-gas/flue-gas-form-volume/flue-gas-form-volume.component.html
src/app/calculator/furnaces/flue-gas/flue-gas-help/flue-gas-help.component.html
src/app/calculator/furnaces/flue-gas/flue-gas-results/flue-gas-results.component.html
src/app/calculator/furnaces/flue-gas/flue-gas.component.html
src/app/calculator/furnaces/flue-gas/flue-gas.service.ts
src/app/shared/models/phast/losses/flueGas.ts
src/app/tools-suite-api/fans-suite-api.service.ts

Issue 7401, 7366 -Update Flue gas calc, Fix fan traverse planes

---

src/app/shared/convert-units/definitions/energy.ts

Issue 7416 - Update energy units

---

src/app/calculator/compressed-air/air-leak/air-leak-results-table/air-leak-results-table.component.html
src/app/calculator/compressed-air/air-leak/air-leak-results-table/air-leak-results-table.component.ts
src/app/calculator/compressed-air/air-leak/air-leak.service.ts

Issue 7449: CA Leak Calculator - select all button

---

src/app/treasure-hunt/treasure-hunt-report/treasure-hunt-ppt/treasure-hunt-ppt.service.ts

Issue 7268: TH PPT add two slides 

---

src/app/calculator/utilities/cash-flow/cash-flow-diagram/cash-flow-diagram.component.html
src/app/calculator/utilities/cash-flow/cash-flow-diagram/cash-flow-diagram.component.ts
src/app/calculator/utilities/cash-flow/cash-flow-form/cash-flow-form.component.css
src/app/calculator/utilities/cash-flow/cash-flow-form/cash-flow-form.component.html
src/app/calculator/utilities/cash-flow/cash-flow-form/cash-flow-form.component.ts
src/app/calculator/utilities/cash-flow/cash-flow-help/cash-flow-help.component.html
src/app/calculator/utilities/cash-flow/cash-flow-results/cash-flow-results.component.css
src/app/calculator/utilities/cash-flow/cash-flow-results/cash-flow-results.component.html
src/app/calculator/utilities/cash-flow/cash-flow-results/cash-flow-results.component.spec.ts
src/app/calculator/utilities/cash-flow/cash-flow-results/cash-flow-results.component.ts
src/app/calculator/utilities/cash-flow/cash-flow.component.html
src/app/calculator/utilities/cash-flow/cash-flow.component.ts
src/app/calculator/utilities/cash-flow/cash-flow.module.ts
src/app/calculator/utilities/cash-flow/cash-flow.service.ts
src/app/calculator/utilities/cash-flow/cash-flow.ts

Issue 7316: Cash Flow Calc upgrade

---

src/app/core/core.component.ts
src/app/shared/measur-survey/measur-survey.service.ts

Issue 7465 - Don't show toast on first open

---

src/app/calculator/steam/feedwater-economizer/feedwater-economizer-help/feedwater-economizer-help.component.html

Issue 7374: fixed help text Feed Water economizer

---

src/app/core/core.component.ts
src/app/shared/measur-survey/measur-survey.service.ts

Issue 7465 - remove time constraints for survey display

---

angular.json
package-lock.json
package.json
src/app/psat/explore-opportunities/explore-opportunities-results/explore-opportunities-results.component.html
src/app/psat/psat-report/output-summary/output-summary.component.html
src/app/psat/psat-report/psat-report-graphs/psat-report-graphs.component.ts
src/app/psat/psat.service.ts
src/app/shared/models/psat.ts
src/app/shared/psat-sankey/psat-sankey.component.ts
src/app/tools-suite-api/calculator-suite-api.service.ts
src/app/tools-suite-api/pumps-suite-api.service.ts

#7293 
Update of previous commit for new release that includes angular.json changes and additional api changes

7293 - Fixed - Add measur-tools-suite changes, including InsulatedPipeReduction, angular json changes

---

src/app/calculator/utilities/cash-flow/cash-flow-diagram/cash-flow-diagram.component.ts
src/app/calculator/utilities/cash-flow/cash-flow-form/cash-flow-form.component.html
src/app/calculator/utilities/cash-flow/cash-flow-help/cash-flow-help.component.html
src/app/calculator/utilities/cash-flow/cash-flow-results/cash-flow-results.component.html

Issue 7476: Cash flow tweaks

---

src/app/compressed-air-assessment/compressed-air-assessment-results.service.ts
src/app/compressed-air-assessment/compressed-air-report/payback-period/payback-period.component.html
src/app/compressed-air-assessment/explore-opportunities/explore-opportunities.component.html
src/app/compressed-air-assessment/explore-opportunities/explore-opportunities.component.ts
src/app/compressed-air-assessment/explore-opportunities/explore-opportunities.service.ts
src/app/compressed-air-assessment/results-panel/help-panel/assessment-help/assessment-help.component.html
src/app/examples/mockCompressedAirAssessment.ts
src/app/shared/models/compressed-air-assessment.ts

Issue 7475: Flow reallocation implementation cost

---

.gitignore
process-flow-diagram-component/src/components/Forms/ComponentDataForm.tsx
process-flow-diagram-component/src/components/Forms/SelectTreatmentType.tsx
src/app/water-process-diagram/update-diagram-from-assessment.service.ts
src/app/water/discharge-outlet/discharge-outlet.component.html
src/app/water/intake-source/intake-source.component.html
src/app/water/monthly-flow-modal/monthly-flow-modal.component.html
src/app/water/water-banner/setup-tabs/setup-tabs.component.html
src/app/water/water-using-system/added-energy/added-energy.component.html
src/app/water/water-using-system/added-energy/added-energy.component.ts
src/app/water/water-using-system/water-system-data/water-system-data.component.html
src/process-flow-lib/water/logic/water-components.ts

Issue 7484 - hotfixes to treatment types and labelling changes

---

src/app/compressed-air-assessment/results-panel/end-use-table/end-use-table.component.html
src/app/compressed-air-assessment/results-panel/end-use-table/end-use-table.component.ts
src/app/compressed-air-assessment/results-panel/inventory-table/inventory-table.component.ts

Issue 7438: No name end uses unrecoverable

---

src/app/compressed-air-assessment/compressed-air-banner/compressed-air-banner.component.html
src/app/fsat/fsat-tabs/fsat-tabs.component.html
src/app/phast/modification-navbar/modification-navbar.component.html
src/app/psat/psat-tabs/psat-tabs.component.html
src/app/ssmt/ssmt-tabs/ssmt-tabs.component.html
src/app/waste-water/waste-water-banner/waste-water-banner.component.html

Issue 5039

---

src/app/calculator/pumps/achievable-efficiency/achievable-efficiency-form/achievable-efficiency-form.component.html
src/app/calculator/pumps/achievable-efficiency/achievable-efficiency-graph/achievable-efficiency-graph.component.ts
src/app/calculator/pumps/achievable-efficiency/achievable-efficiency-help/achievable-efficiency-help.component.html
src/app/calculator/pumps/achievable-efficiency/achievable-efficiency.component.ts
src/app/calculator/pumps/achievable-efficiency/achievable-efficiency.service.ts
src/app/psat/explore-opportunities/explore-opportunities-form/pump-data-form/pump-data-form.component.ts
src/app/psat/psat.service.ts
src/app/psat/pump-fluid/pump-fluid.component.ts
src/app/tools-suite-api/pumps-suite-api.service.ts

Issue 7420: Updates to PumpEfficiency

---

package-lock.json
package.json
src/app/shared/update-application/release-notes-modal/release-notes-modal.component.html

#7483 
Requires measur-tools-suite PR for 1.0.10 to latest

Release 1.5.12 into dev

---

.gitignore
process-flow-diagram-component/src/components/Diagram/diagramReducer.ts
process-flow-diagram-component/src/components/Diagram/store.ts
process-flow-diagram-component/src/components/Drawer/DiagramResults.tsx
process-flow-diagram-component/src/components/Drawer/MenuSidebar.tsx
process-flow-diagram-component/src/components/Nodes/ProcessFlowComponentNode.tsx
process-flow-diagram-component/src/components/StyledMUI/ResultTables.tsx
src/app/examples/mockWaterDiagram.ts
src/app/water-process-diagram/update-diagram-from-assessment.service.ts
src/app/water-process-diagram/water-process-diagram.service.ts
src/app/water/update-assessment-from-diagram.service.ts
src/process-flow-lib/graph.ts
src/process-flow-lib/index.ts
src/process-flow-lib/water/logic/results.ts
src/process-flow-lib/water/logic/water-components.ts
src/process-flow-lib/water/types/diagram.ts

Issue 7410 - Add true cost calculations

---

src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-catalog/compressed-air-basics/compressed-air-basics.component.html
src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-catalog/compressed-air-basics/compressed-air-basics.service.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/end-uses-table/end-uses-table.component.ts
src/app/compressed-air-inventory/compressed-air-inventory-setup/system-catalog-table/system-catalog-table.component.ts

Issue 7492: CA end use table bug

---

src/app/water/water-assessment.component.html
src/app/water/water-assessment.component.ts
src/app/water/water-assessment.service.ts
src/app/water/water-banner/water-banner.component.html
src/app/water/water-banner/water-banner.component.ts

Issue 7491 - Change system-setup refs to baseline

---

process-flow-diagram-component/src/components/Diagram/Diagram.tsx
process-flow-diagram-component/src/components/Diagram/diagramReducer.ts
process-flow-diagram-component/src/components/Diagram/store.ts
process-flow-diagram-component/src/components/Drawer/DownloadButton.tsx
src/app/examples/mockWaterDiagram.ts
src/app/water-process-diagram/update-diagram-from-assessment.service.ts
src/app/water-process-diagram/water-process-diagram.service.ts
src/app/water/waste-water-treatment/waste-water-treatment.component.html
src/app/water/water-treatment/water-treatment.component.html
src/process-flow-lib/water/logic/results.ts
src/process-flow-lib/water/types/diagram.ts

#7481 
Fix treatment units, fix userdiagramoptions reducer update, populate …correct assessment flow fields

Issue 7481 - Various bugs

---

src/app/compressed-air-inventory/compressed-air-inventory-setup/plant-setup/plant-setup.component.ts
src/app/compressed-air-inventory/compressed-air-inventory.module.ts
src/app/compressed-air-inventory/convert-compressed-air-inventory.service.spec.ts
src/app/compressed-air-inventory/convert-compressed-air-inventory.service.ts

Issue 7295: Add conversion logic to CA Inventory

---

src/app/water/water-assessment-results.service.ts
src/app/water/water-report/system-true-cost-bar/system-true-cost-bar.component.html
src/app/water/water-report/system-true-cost-bar/system-true-cost-bar.component.spec.ts
src/app/water/water-report/system-true-cost-bar/system-true-cost-bar.component.ts
src/app/water/water-report/system-true-cost-report/system-true-cost-report.component.html
src/app/water/water-report/system-true-cost-report/system-true-cost-report.component.ts
src/app/water/water-report/water-report.component.ts
src/app/water/water-report/water-report.module.ts
src/app/water/water-report/water-report.service.spec.ts
src/app/water/water-report/water-report.service.ts
src/process-flow-lib/water/logic/results.ts

Add system true cost report bar

---

process-flow-diagram-component/src/components/Diagram/ResultsPanel.tsx
process-flow-diagram-component/src/components/Drawer/DebugResults.tsx
process-flow-diagram-component/src/components/Drawer/DiagramResults.tsx
process-flow-diagram-component/src/components/Drawer/MenuSidebar.tsx
process-flow-diagram-component/src/components/Drawer/SideDrawer.tsx
src/app/water/results-panel/monthly-flow-chart/monthly-flow-chart.component.ts
src/app/water/water-assessment-results.service.ts
src/process-flow-lib/water/logic/results.ts

Issue 7520 - Add results tab, Fix exec sumary results

---

process-flow-diagram-component/src/components/Diagram/Diagram.tsx
process-flow-diagram-component/src/components/Drawer/BetaChip.tsx
process-flow-diagram-component/src/components/Drawer/SideDrawer.tsx
src/app/dashboard/dashboard.module.ts
src/app/dashboard/landing-screen/landing-screen.component.css
src/app/dashboard/landing-screen/landing-screen.component.html
src/app/shared/alert-badge/alert-badge.component.css
src/app/shared/alert-badge/alert-badge.component.html
src/app/shared/alert-badge/alert-badge.component.spec.ts
src/app/shared/alert-badge/alert-badge.component.ts
src/app/shared/alert-info-container/alert-info-container.component.css
src/app/shared/alert-info-container/alert-info-container.component.html
src/app/shared/alert-info-container/alert-info-container.component.spec.ts
src/app/shared/alert-info-container/alert-info-container.component.ts
src/app/water-process-diagram/water-diagram-banner/water-diagram-banner.component.html
src/app/water-process-diagram/water-process-diagram.module.ts
src/app/water/discharge-outlet/discharge-outlet.component.html
src/app/water/intake-source/intake-source.component.html
src/app/water/waste-water-treatment/waste-water-treatment.component.html
src/app/water/water-banner/water-banner.component.css
src/app/water/water-banner/water-banner.component.html
src/app/water/water-treatment/water-treatment.component.html
src/app/water/water-using-system/water-system-data/water-system-data.component.html
src/app/water/water.module.ts

Issue 7493 - Add badges and info for water module beta

---

process-flow-diagram-component/src/components/Diagram/Diagram.tsx
process-flow-diagram-component/src/components/Drawer/DebugResults.tsx
process-flow-diagram-component/src/components/Drawer/DownloadButton.tsx
process-flow-diagram-component/src/components/Forms/InSystemTreatmentForm.tsx
process-flow-diagram-component/src/components/Forms/StaticModal.tsx
process-flow-diagram-component/src/components/Forms/WaterSystemEstimation/BoilerWaterForm.tsx
process-flow-diagram-component/src/components/Forms/WaterSystemEstimation/CoolingTowerForm.tsx
process-flow-diagram-component/src/components/Forms/WaterSystemEstimation/EstimateWaterSystem.tsx
process-flow-diagram-component/src/components/Forms/WaterSystemEstimation/KitchenRestroomForm.tsx
process-flow-diagram-component/src/components/Forms/WaterSystemEstimation/LandscapingForm.tsx
process-flow-diagram-component/src/components/StyledMUI/ResultTables.tsx
src/app/water/water-assessment-results.service.ts
src/app/water/water-using-system/system-treatment/system-treatment.component.ts
src/process-flow-lib/water/constants.ts
src/process-flow-lib/water/logic/results.ts

Issue 7521 - Support WWT, WT Recycled Costs with Multiple receivers/inputs

---

src/app/shared/models/printing.ts
src/app/shared/models/settings.ts
src/app/shared/print-options-menu/print-options-menu.component.html
src/app/shared/print-options-menu/print-options-menu.service.ts
src/app/water/water-report/executive-summary/executive-summary.component.css
src/app/water/water-report/system-true-cost-bar/system-true-cost-bar.component.css
src/app/water/water-report/system-true-cost-bar/system-true-cost-bar.component.html
src/app/water/water-report/system-true-cost-bar/system-true-cost-bar.component.ts
src/app/water/water-report/system-true-cost-report/system-true-cost-report.component.css
src/app/water/water-report/system-true-cost-report/system-true-cost-report.component.html
src/app/water/water-report/water-report.component.html
src/app/water/water-report/water-report.module.ts

Issue 7512 - Add report printing

---

process-flow-diagram-component/src/components/Diagram/Diagram.tsx
process-flow-diagram-component/src/components/Diagram/ValidationWindow.tsx
process-flow-diagram-component/src/components/Diagram/diagramReducer.ts
process-flow-diagram-component/src/components/Drawer/MenuSidebar.tsx
process-flow-diagram-component/src/components/Forms/WaterSystemEstimation/ProcessUseForm.tsx
src/app/dashboard/assessment.service.ts
src/app/dashboard/directory-dashboard/directory-dashboard-menu/directory-dashboard-menu.component.ts
src/app/dashboard/directory-dashboard/directory-items/assessment-item/water-summary-card/water-summary-card.component.html
src/app/dashboard/directory-dashboard/directory-items/assessment-item/water-summary-card/water-summary-card.component.ts
src/app/examples/mockWaterAssessment.ts
src/app/examples/mockWaterDiagram.ts
src/app/shared/alert-info-container/alert-info-container.component.html
src/app/shared/alert-info-container/alert-info-container.component.ts
src/app/water-process-diagram/water-process-diagram.component.ts
src/app/water/convert-water-assessment.service.ts
src/app/water/results-panel/monthly-flow-chart/monthly-flow-chart.component.html
src/app/water/results-panel/monthly-flow-chart/monthly-flow-chart.component.ts
src/app/water/results-panel/results-panel.component.html
src/app/water/results-panel/results-panel.component.ts
src/app/water/water-report/system-summary-report/system-summary-report.component.html
src/app/water/water-report/system-summary-report/system-summary-report.component.ts
src/app/water/water-report/water-report.component.ts
src/app/water/water-report/water-report.module.ts
src/app/water/water-using-system/water-system-data/water-system-data.component.html

Issue 7481 - Update Water examples, hide dashboard copymove, fix various bugs, fix conversions rounding, fix html exposed

---

process-flow-diagram-component/src/components/Drawer/DebugResults.tsx
process-flow-diagram-component/src/components/Drawer/DiagramResults.tsx
src/app/dashboard/assessment.service.ts
src/app/examples/mockWaterAssessment.ts
src/app/examples/mockWaterDiagram.ts
src/app/water-process-diagram/update-diagram-from-assessment.service.ts
src/app/water-process-diagram/water-process-diagram.service.ts
src/app/water/system-basics/system-basics.component.html
src/app/water/system-basics/system-basics.service.ts
src/app/water/water-assessment-results.service.ts
src/app/water/water-using-system/added-energy/motor-energy/motor-energy.component.html
src/process-flow-lib/water/logic/results.ts
src/process-flow-lib/water/logic/water-components.ts
src/process-flow-lib/water/types/assessment.ts
src/process-flow-lib/water/types/diagram.ts
src/process-flow-lib/water/types/water-components.ts

Issue 7481 - Feedback fixes -- update heat enegy and pump energy results, add fuel cost

---

src/process-flow-lib/water/logic/results.ts

Fix modifying frozen waterUsingsystem object

Issue 7481 - hotfix 

---

src/app/water-process-diagram/update-diagram-from-assessment.service.ts
src/app/water/water-assessment-results.service.ts

Issue 7525 - Fix broken assessment summary card on diagram delete

---

process-flow-diagram-component/src/components/Forms/DischargeFlowForm.tsx
process-flow-diagram-component/src/components/Forms/SourceFlowForm.tsx
process-flow-diagram-component/src/validation/Validation.ts

Issue 7481 - Update validation to compare rounded value to user decimal precision

---

process-flow-diagram-component/src/components/Diagram/Diagram.tsx
process-flow-diagram-component/src/components/Diagram/diagramReducer.ts
process-flow-diagram-component/src/components/Drawer/DiagramResults.tsx
process-flow-diagram-component/src/components/Drawer/MenuSidebar.tsx
src/app/shared/import-export/import.service.ts
src/app/water/update-assessment-from-diagram.service.ts
src/app/water/water-assessment.service.ts
src/process-flow-lib/water/logic/results.ts
src/process-flow-lib/water/logic/validation.ts

Issue 7481 - Change result name, fix assessment populated flows from diagram, water treatment actions in asessment table

---

src/app/log-tool/data-setup/map-time-data/map-time-data.component.ts
src/app/log-tool/day-type-analysis/day-type-analysis.component.ts
src/app/log-tool/day-type-analysis/day-type-analysis.service.ts
src/app/log-tool/day-type-analysis/day-type-graph/day-type-graph.service.ts
src/app/log-tool/day-type-analysis/day-type-table/selected-data-table/selected-data-table.component.ts
src/app/log-tool/log-tool-data.service.ts

#7495 
Also adding console timers for future benchmarking

Issue 7495 - Data Explorer DTA expected results

---

src/app/log-tool/data-setup/import-data/import-data.component.html
src/app/log-tool/data-setup/import-data/import-data.component.ts
src/app/log-tool/data-setup/refine-data/refine-data.component.html
src/app/log-tool/data-setup/refine-data/refine-data.component.ts
src/app/log-tool/export-modal/export-modal.component.css
src/app/log-tool/export-modal/export-modal.component.html
src/app/log-tool/export-modal/export-modal.component.ts
src/app/log-tool/log-tool.component.html
src/app/log-tool/log-tool.module.ts
src/app/log-tool/visualize/visualize-graph/visualize-graph.component.ts
src/app/shared/import-export/export-modal/export-modal.component.ts
src/app/shared/import-export/import-export.service.ts

Add gzipped for Data Explorer, Fix refine data apply all bug, graph visualizer missing click function

---

src/app/dashboard/data-and-backup/data-and-backup.component.html
src/app/dashboard/data-and-backup/data-and-backup.component.ts
src/app/shared/analytics/analyticsEventTypes.ts
src/app/shared/import-backup-modal/import-backup-modal.component.ts
src/app/shared/import-backup.service.ts
src/app/shared/import-export/import-modal/import-modal.component.html
src/app/shared/import-export/import-modal/import-modal.component.ts
src/app/shared/import-export/import.service.ts

Issue 7344 - Add useful messaging for measur import/export types during import

---

package-lock.json
src/app/app.component.css
src/app/dashboard/assessment.service.ts
src/app/examples/mockProcessCooling.ts
src/app/process-cooling/convert-process-cooling.service.spec.ts
src/app/process-cooling/convert-process-cooling.service.ts
src/app/process-cooling/process-cooling-banner/process-cooling-banner.component.html
src/app/process-cooling/process-cooling-report/process-cooling-report.component.css
src/app/process-cooling/process-cooling-report/process-cooling-report.component.html
src/app/process-cooling/process-cooling-report/process-cooling-report.component.spec.ts
src/app/process-cooling/process-cooling-report/process-cooling-report.component.ts
src/app/process-cooling/process-cooling-report/process-cooling-report.service.spec.ts
src/app/process-cooling/process-cooling-report/process-cooling-report.service.ts
src/app/process-cooling/process-cooling.component.html
src/app/process-cooling/process-cooling.module.ts
src/app/process-cooling/system-basics/system-basics-form.service.spec.ts
src/app/process-cooling/system-basics/system-basics-form.service.ts
src/app/process-cooling/system-basics/system-basics.component.html
src/app/process-cooling/system-basics/system-basics.component.spec.ts
src/app/process-cooling/system-basics/system-basics.component.ts
src/app/shared/models/process-cooling-assessment.ts

Issue 7602 - Create Assessment Settings and conversion service, add report tab and components

---

src/app/calculator/steam/steam-reduction/steam-reduction-form/steam-reduction-form.component.ts

Issue 7609 - Steam Reduction Fix typo on form control name

---

src/app/calculator/compressed-air/air-leak/air-leak-help/air-leak-help.component.html
src/app/calculator/compressed-air/air-leak/air-leak-results/air-leak-results.component.html
src/app/calculator/compressed-air/air-leak/air-leak-results/air-leak-results.component.ts
src/app/calculator/compressed-air/air-leak/facility-compressor-data-form/facility-compressor-data-form.component.html
src/app/calculator/compressed-air/compressed-air-reduction/compressed-air-reduction-form/compressed-air-reduction-form.component.html
src/app/calculator/compressed-air/compressed-air-reduction/compressed-air-reduction-help/compressed-air-reduction-help.component.html
src/app/calculator/compressed-air/compressed-air-reduction/compressed-air-reduction-results/compressed-air-reduction-results.component.html
src/app/treasure-hunt/treasure-hunt-calculator-services/air-leak-treasure-hunt.service.ts
src/app/treasure-hunt/treasure-hunt-calculator-services/ca-reduction-treasure-hunt.service.ts

Issue 7419  - Bag Method- Hide results tables. Adjust TH results

---

src/app/shared/update-application/release-notes-modal/release-notes-modal.component.html

Add release notes for version 1.6.1

---

src/app/compressed-air-inventory/compressed-air-inventory-banner/summary-filter/selected-options/selected-options.component.css
src/app/compressed-air-inventory/compressed-air-inventory-banner/summary-filter/selected-options/selected-options.component.html
src/app/compressed-air-inventory/compressed-air-inventory-banner/summary-filter/selected-options/selected-options.component.spec.ts
src/app/compressed-air-inventory/compressed-air-inventory-banner/summary-filter/selected-options/selected-options.component.ts
src/app/compressed-air-inventory/compressed-air-inventory-banner/summary-filter/summary-filter.component.css
src/app/compressed-air-inventory/compressed-air-inventory-banner/summary-filter/summary-filter.component.html
src/app/compressed-air-inventory/compressed-air-inventory-banner/summary-filter/system-dropdown/system-dropdown.component.css
src/app/compressed-air-inventory/compressed-air-inventory-banner/summary-filter/system-dropdown/system-dropdown.component.html
src/app/compressed-air-inventory/compressed-air-inventory-banner/summary-filter/system-dropdown/system-dropdown.component.spec.ts
src/app/compressed-air-inventory/compressed-air-inventory-banner/summary-filter/system-dropdown/system-dropdown.component.ts
src/app/compressed-air-inventory/compressed-air-inventory-summary/compressed-air-inventory-summary-overview/compressed-air-inventory-overview-bar-chart/compressed-air-inventory-overview-bar-chart.component.html
src/app/compressed-air-inventory/compressed-air-inventory-summary/compressed-air-inventory-summary-overview/compressed-air-inventory-overview-bar-chart/compressed-air-inventory-overview-bar-chart.component.ts
src/app/compressed-air-inventory/compressed-air-inventory-summary/compressed-air-inventory-summary-overview/compressed-air-inventory-overview-pie-chart/compressed-air-inventory-overview-pie-chart.component.html
src/app/compressed-air-inventory/compressed-air-inventory-summary/compressed-air-inventory-summary-overview/compressed-air-inventory-overview-pie-chart/compressed-air-inventory-overview-pie-chart.component.ts
src/app/compressed-air-inventory/compressed-air-inventory-summary/compressed-air-inventory-summary-overview/compressed-air-inventory-overview-table/compressed-air-inventory-overview-table.component.css
src/app/compressed-air-inventory/compressed-air-inventory-summary/compressed-air-inventory-summary-overview/compressed-air-inventory-overview-table/compressed-air-inventory-overview-table.component.html
src/app/compressed-air-inventory/compressed-air-inventory-summary/compressed-air-inventory-summary-overview/compressed-air-inventory-overview-table/compressed-air-inventory-overview-table.component.ts
src/app/compressed-air-inventory/compressed-air-inventory-summary/compressed-air-inventory-summary-overview/compressed-air-inventory-summary-overview.component.html
src/app/compressed-air-inventory/compressed-air-inventory-summary/compressed-air-inventory-summary-overview/compressed-air-inventory-summary-overview.component.ts
src/app/compressed-air-inventory/compressed-air-inventory-summary/compressed-air-inventory-summary-overview/compressed-air-inventory-summary-overview.service.ts
src/app/compressed-air-inventory/compressed-air-inventory.module.ts
src/app/compressed-air-inventory/compressed-air-inventory.service.ts

Issue 7605: Compressed Air Inventory Summary: Overview tab and filter

---

process-flow-diagram-component/src/components/Drawer/DiagramResults.tsx

Issue 7595 - Add in system treatment results to diagram indirect costs

---

src/app/compressed-air-inventory/compressed-air-inventory-summary/compressed-air-inventory-summary-graphs/compressed-air-inventory-summary-graphs.component.css
src/app/compressed-air-inventory/compressed-air-inventory-summary/compressed-air-inventory-summary-graphs/compressed-air-inventory-summary-graphs.component.html
src/app/compressed-air-inventory/compressed-air-inventory-summary/compressed-air-inventory-summary-graphs/compressed-air-inventory-summary-graphs.component.ts
src/app/compressed-air-inventory/compressed-air-inventory-summary/compressed-air-inventory-summary-graphs/compressed-air-inventory-summary-graphs.service.ts
src/app/compressed-air-inventory/compressed-air-inventory-summary/compressed-air-inventory-summary-graphs/compressed-air-summary-graph/compressed-air-summary-graph.component.html
src/app/compressed-air-inventory/compressed-air-inventory-summary/compressed-air-inventory-summary-graphs/compressed-air-summary-graph/compressed-air-summary-graph.component.ts
src/app/compressed-air-inventory/compressed-air-inventory-summary/compressed-air-inventory-summary-graphs/compressed-air-summary-graphs-menu/compressed-air-summary-graphs-menu.component.css
src/app/compressed-air-inventory/compressed-air-inventory-summary/compressed-air-inventory-summary-graphs/compressed-air-summary-graphs-menu/compressed-air-summary-graphs-menu.component.html
src/app/compressed-air-inventory/compressed-air-inventory-summary/compressed-air-inventory-summary-graphs/compressed-air-summary-graphs-menu/compressed-air-summary-graphs-menu.component.ts
src/app/compressed-air-inventory/compressed-air-inventory-summary/compressed-air-inventory-summary.service.ts

Issue 7301: Compressed Air Inventory Summary: Graphs Tab

---

src/app/compressed-air-inventory/compressed-air-inventory-summary/compressed-air-inventory-summary-graphs/compressed-air-inventory-summary-graphs.service.ts
src/app/compressed-air-inventory/compressed-air-inventory-summary/compressed-air-inventory-summary-graphs/compressed-air-summary-graphs-menu/compressed-air-summary-graphs-menu.component.ts
src/app/compressed-air-inventory/compressed-air-inventory-summary/compressed-air-inventory-summary-table/compressed-air-inventory-summary-table.component.css
src/app/compressed-air-inventory/compressed-air-inventory-summary/compressed-air-inventory-summary-table/compressed-air-inventory-summary-table.component.html
src/app/compressed-air-inventory/compressed-air-inventory-summary/compressed-air-inventory-summary-table/compressed-air-inventory-summary-table.component.ts
src/app/compressed-air-inventory/compressed-air-inventory-summary/compressed-air-inventory-summary-table/compressed-air-inventory-summary-table.service.ts
src/app/compressed-air-inventory/compressed-air-inventory-summary/compressed-air-inventory-summary.module.ts
src/app/compressed-air-inventory/compressed-air-inventory-summary/compressed-air-inventory-summary.service.ts

Issue 7302: Compressed Air Inventory Summary: Table tab

---

process-flow-diagram-component/src/components/Diagram/FlowTypes.ts
process-flow-diagram-component/src/components/Diagram/diagramReducer.ts
process-flow-diagram-component/src/components/Drawer/ManageComponent.tsx
process-flow-diagram-component/src/components/Nodes/CustomHandle.tsx
process-flow-diagram-component/src/components/Nodes/DischargeOutletNode.tsx
process-flow-diagram-component/src/components/Nodes/IntakeSourceNode.tsx
process-flow-diagram-component/src/components/Nodes/ProcessFlowComponentNode.tsx
src/process-flow-lib/water/logic/water-components.ts

Issue - 7592 - Add all handles for intake and discharge, provide component tab conext via state

---

src/app/compressed-air-inventory/compressed-air-inventory-banner/summary-filter/compressor-type-dropdown/compressor-type-dropdown.component.css
src/app/compressed-air-inventory/compressed-air-inventory-banner/summary-filter/compressor-type-dropdown/compressor-type-dropdown.component.html
src/app/compressed-air-inventory/compressed-air-inventory-banner/summary-filter/compressor-type-dropdown/compressor-type-dropdown.component.spec.ts
src/app/compressed-air-inventory/compressed-air-inventory-banner/summary-filter/compressor-type-dropdown/compressor-type-dropdown.component.ts
src/app/compressed-air-inventory/compressed-air-inventory-banner/summary-filter/control-type-dropdown/control-type-dropdown.component.css
src/app/compressed-air-inventory/compressed-air-inventory-banner/summary-filter/control-type-dropdown/control-type-dropdown.component.html
src/app/compressed-air-inventory/compressed-air-inventory-banner/summary-filter/control-type-dropdown/control-type-dropdown.component.spec.ts
src/app/compressed-air-inventory/compressed-air-inventory-banner/summary-filter/control-type-dropdown/control-type-dropdown.component.ts
src/app/compressed-air-inventory/compressed-air-inventory-banner/summary-filter/horsepower-dropdown/horsepower-dropdown.component.css
src/app/compressed-air-inventory/compressed-air-inventory-banner/summary-filter/horsepower-dropdown/horsepower-dropdown.component.html
src/app/compressed-air-inventory/compressed-air-inventory-banner/summary-filter/horsepower-dropdown/horsepower-dropdown.component.spec.ts
src/app/compressed-air-inventory/compressed-air-inventory-banner/summary-filter/horsepower-dropdown/horsepower-dropdown.component.ts
src/app/compressed-air-inventory/compressed-air-inventory-banner/summary-filter/selected-options/selected-options.component.html
src/app/compressed-air-inventory/compressed-air-inventory-banner/summary-filter/selected-options/selected-options.component.ts
src/app/compressed-air-inventory/compressed-air-inventory-banner/summary-filter/summary-filter.component.html
src/app/compressed-air-inventory/compressed-air-inventory.module.ts
src/app/compressed-air-inventory/compressed-air-inventory.service.ts

Issue 7652: Add more categories to the CA Inventory summary filter

---

src/app/dashboard/assessment.service.ts
src/app/examples/CWSATExampleAirCooledConstant.ts
src/app/examples/CWSATExampleVINPLTConstants.ts
src/app/examples/exampleProcessCoolingConstants.ts
src/app/examples/mockProcessCooling.ts
src/app/process-cooling/process-cooling-constants.ts
src/app/process-cooling/process-cooling-results.service.ts
src/app/process-cooling/process-cooling.module.ts
src/app/process-cooling/process-cooling.service.ts
src/app/process-cooling/system-basics/system-basics-form.service.ts
src/app/process-cooling/system-basics/system-basics.component.html
src/app/process-cooling/system-basics/system-basics.component.ts
src/app/process-cooling/system-information/operations/operations.component.html
src/app/process-cooling/system-information/operations/operations.component.spec.ts
src/app/process-cooling/system-information/operations/operations.component.ts
src/app/process-cooling/system-information/system-information-form.service.spec.ts
src/app/process-cooling/system-information/system-information-form.service.ts
src/app/process-cooling/system-information/system-information.component.html
src/app/process-cooling/system-information/system-information.component.spec.ts
src/app/process-cooling/system-information/system-information.component.ts
src/app/shared/app-constants.ts
src/app/shared/create-assessment-modal/create-assessment-modal.component.ts
src/app/shared/form-control-errors.component.html
src/app/shared/form-control-errors.component.ts
src/app/shared/form-control-required.component.html
src/app/shared/form-control-required.component.ts
src/app/shared/input-unit.component.ts
src/app/shared/models/process-cooling-assessment.ts
src/app/shared/operating-hours-modal/operating-hours-modal.component.ts
src/assets/styles/forms.css

Add sys info operations component, shared components for form error and unit templates, remove systembasics properties redundant with operations

Issue 7669 - Add System Information Operations form

---

src/app/examples/CWSATExampleVINPLTConstants.ts
src/app/process-cooling-assessment/pipes/chiller-compressor-type.pipe.ts
src/app/process-cooling-assessment/process-cooling-assessment.module.ts
src/app/process-cooling-assessment/process-cooling-constants.ts
src/app/process-cooling-assessment/results-panel/help-panel/system-information-help/system-information-help.component.html
src/app/process-cooling-assessment/results-panel/help-panel/tower-help/tower-help.component.html
src/app/process-cooling-assessment/results-panel/help-panel/tower-help/tower-help.component.spec.ts
src/app/process-cooling-assessment/results-panel/help-panel/tower-help/tower-help.component.ts
src/app/process-cooling-assessment/services/process-cooling-ui.service.ts
src/app/process-cooling-assessment/system-information/system-information-form.service.ts
src/app/process-cooling-assessment/system-information/tower/tower.component.html
src/app/process-cooling-assessment/system-information/tower/tower.component.spec.ts
src/app/process-cooling-assessment/system-information/tower/tower.component.ts
src/app/shared/models/process-cooling-assessment.ts

Issue 7641 - Add tower data form

---

src/app/compressed-air-inventory/compressed-air-inventory-summary/compressed-air-inventory-summary-table/compressed-air-inventory-summary-table.component.html
src/app/compressed-air-inventory/compressed-air-inventory-summary/compressed-air-inventory-summary-table/compressed-air-inventory-summary-table.pipe.ts
src/app/compressed-air-inventory/compressed-air-inventory-summary/compressed-air-inventory-summary-table/compressed-air-inventory-summary-table.service.ts
src/app/compressed-air-inventory/compressed-air-inventory-summary/compressed-air-inventory-summary.service.ts

Issue 7645: Add data CA Inventory Summary Table Tab

---

src/app/compressed-air-inventory/compressed-air-inventory-summary/compressed-air-inventory-summary-graphs/compressed-air-inventory-summary-graphs.service.ts
src/app/compressed-air-inventory/compressed-air-inventory-summary/compressed-air-inventory-summary-graphs/compressed-air-summary-graphs-menu/compressed-air-summary-graphs-menu.component.ts
src/app/compressed-air-inventory/compressed-air-inventory-summary/compressed-air-inventory-summary.service.ts
src/app/compressed-air-inventory/compressed-air-inventory.service.ts

Issue 7644: Add data CA Inventory Summary Graphs Tab

---

src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-catalog/performance-points-catalog/performance-points-catalog.service.ts
src/app/compressed-air-inventory/compressed-air-inventory.service.ts

issue 7696: CA Inventory Catalog bug

---

process-flow-diagram-component/src/components/Drawer/ComponentNameHeader.tsx

Issue 7226 Bug Fix - Watch for changes on selected node name

---

src/app/shared/snackbar-notification/snackbar-notification.component.css

Woops - Missing comma changed applied styles

---

src/app/dashboard/copy-items/copy-items.component.ts
src/app/dashboard/directory-dashboard/directory-items/inventory-item/inventory-item.component.ts
src/app/motor-inventory/motor-inventory-setup/motor-catalog/nameplate-data/nameplate-data.component.ts
src/app/motor-inventory/motor-inventory.component.ts
src/app/psat/motor/motor.component.ts
src/app/pump-inventory/pump-inventory-setup/department-setup/department-setup.component.ts
src/app/pump-inventory/pump-inventory-setup/pump-catalog/pump-motor-catalog/pump-motor-catalog.component.ts
src/app/pump-inventory/pump-inventory.component.ts
src/app/pump-inventory/pump-inventory.service.ts
src/app/shared/connected-inventory/connected-inventory-module.ts
src/app/shared/connected-inventory/psat-integration.service.ts
src/app/shared/connected-inventory/pump-motor-integration.service.ts

issue 7758: Rename Motor Intergration Service to Pump Motor Integration Service

---

src/app/tools-suite-api/process-heating-api.service.ts

connects #7756 
use totalHeatLoss call in place of getHeatLoss

Issue 7756: update Wall Losses Signature

---

src/app/compressed-air-inventory/compressed-air-inventory-setup/compressed-air-catalog/compressed-air-motor-catalog/compressed-air-motor-catalog.component.ts
src/app/shared/connected-inventory/compressed-air-motor-integration.service.ts
src/app/shared/connected-inventory/integrations.ts

issue 7299: Connect motor inventory to compressed air inventory

---

package-lock.json
package.json
src/app/calculator/furnaces/atmosphere/atmosphere-help/atmosphere-help.component.html
src/app/calculator/furnaces/atmosphere/atmosphere-help/atmosphere-help.component.ts
src/app/phast/losses/losses-help/atmosphere-losses-help/atmosphere-losses-help.component.html
src/app/phast/losses/losses-help/atmosphere-losses-help/atmosphere-losses-help.component.ts
src/app/tools-suite-api/process-heating-api.service.ts
src/app/tools-suite-api/tools-suite-api.service.ts

update atmosphere loss calculation signature and atmosphere gasses initialization to match suite refactor
connects #7791 
links to documentation from help text
updated call to suite using function in place of class implementation
hotfix to update WallType binding (https://github.com/ORNL-AMO/MEASUR-Tools-Suite/pull/92)

Issue 7791: Atmosphere Losses Suite Refactor Updates

---

src/app/calculator/steam/condensing-economizer/condensing-economizer-form/condensing-economizer-form.component.ts
src/app/calculator/steam/condensing-economizer/condensing-economizer.component.html
src/app/calculator/steam/condensing-economizer/condensing-economizer.component.ts

Issue 7805 - Adjust container z index on modal open

---

package-lock.json
package.json
process-flow-diagram-component/package-lock.json
process-flow-diagram-component/package.json

Update to MEASUR-Tools-Suite v1.0.12

---

process-flow-diagram-component/src/components/Diagram/Diagram.tsx
process-flow-diagram-component/src/components/Diagram/DiagramAlert.tsx
process-flow-diagram-component/src/components/Diagram/diagramReducer.ts
process-flow-diagram-component/src/components/Diagram/store.ts
process-flow-diagram-component/src/components/Drawer/DebugResults.tsx
process-flow-diagram-component/src/components/Drawer/DiagramResults.tsx
process-flow-diagram-component/src/components/Drawer/ManageComponent.tsx
process-flow-diagram-component/src/components/Drawer/SharedDrawer.tsx
process-flow-diagram-component/src/components/Forms/ComponentDataForm.tsx
process-flow-diagram-component/src/components/Forms/DischargeFlowForm.tsx
process-flow-diagram-component/src/components/Forms/InSystemTreatmentForm.tsx
process-flow-diagram-component/src/components/Forms/SourceFlowForm.tsx
process-flow-diagram-component/src/validation/Validation.ts
src/app/water/convert-water-assessment.service.ts
src/app/water/discharge-outlet/discharge-outlet.component.html
src/app/water/intake-source/intake-source.component.html
src/app/water/update-assessment-from-diagram.service.ts
src/app/water/waste-water-treatment/waste-water-treatment.component.html
src/app/water/water-assessment-results.service.ts
src/app/water/water-report/executive-summary/executive-summary.component.html
src/app/water/water-report/executive-summary/executive-summary.component.ts
src/app/water/water-report/system-summary-report/system-summary-report.component.html
src/app/water/water-treatment/water-treatment.component.html
src/app/water/water-using-system/system-treatment/system-treatment.component.html
src/process-flow-lib/water/logic/results.ts
src/process-flow-lib/water/logic/utils.ts
src/process-flow-lib/water/logic/validation.ts
src/process-flow-lib/water/logic/water-components.ts
src/process-flow-lib/water/types/diagram.ts

#7769 
#7747 
#7658 
#7748 
#7746

Issue 7769 7747 7658 7748 7746 - Water Diagram Updates from QA Feedback

---

src/app/process-cooling-assessment/baseline/baseline.component.ts
src/app/process-cooling-assessment/operating-schedule/monthly-operating-schedule/monthly-operating-schedule.component.html
src/app/process-cooling-assessment/operating-schedule/monthly-operating-schedule/monthly-operating-schedule.component.ts
src/app/process-cooling-assessment/operating-schedule/operating-schedule.component.css
src/app/process-cooling-assessment/operating-schedule/operating-schedule.component.html
src/app/process-cooling-assessment/operating-schedule/operating-schedule.component.spec.ts
src/app/process-cooling-assessment/operating-schedule/operating-schedule.component.ts
src/app/process-cooling-assessment/operating-schedule/weekly-operating-schedule/weekly-operating-schedule.component.css
src/app/process-cooling-assessment/operating-schedule/weekly-operating-schedule/weekly-operating-schedule.component.html
src/app/process-cooling-assessment/operating-schedule/weekly-operating-schedule/weekly-operating-schedule.component.ts
src/app/process-cooling-assessment/process-cooling-assessment.module.ts
src/app/process-cooling-assessment/process-cooling-constants.ts
src/app/process-cooling-assessment/services/process-cooling-asessment.service.ts
src/app/process-cooling-assessment/services/weekly-operating-schedule.service.ts
src/app/shared/models/process-cooling-assessment.ts

Issue 7692 - Weekly Operating Schedule

---

package-lock.json
package.json
process-flow-diagram-component/package-lock.json
src/app/shared/update-application/release-notes-modal/release-notes-modal.component.html

Update Develop with v1.6.3
